### ISSUE TITLE
Cuckoo-dev: httpreplay doesn't work

### ISSUE THREAD

**Issue by RedWolf74** [cuckoosandbox/cuckoo#1000]
Hi,

httpreplay 0.1.15 seems to require dpkt 1.8.7 instead of 1.8.6.2. I'm running Ubuntu 14.04.1. If this is not a distribution related issue, please update the requirements.txt for dpkt too.

Cuckoo Error message:
2016-07-06 18:24:11,970 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/modules/processing/network.py", line 815, in run
    results.update(p2.run())
  File "/home/cuckoo/cuckoo/modules/processing/network.py", line 729, in run
    r = httpreplay.reader.PcapReader(open(self.pcap_path, "rb"))
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/reader.py", line 25, in __init__
    self.pcap = dpkt.pcap.Reader(fp)
TypeError: coercing to Unicode: need string or buffer, file found

cuckoo:~/cuckoo$ httpreplay --help
Traceback (most recent call last):
  File "/usr/local/bin/httpreplay", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: **The 'dpkt==1.8.7' distribution was not found and is required** by HTTPReplay

After upgrade to dpkgt 1.8.7:
cuckoo:~/cuckoo$ httpreplay --help
Usage: httpreplay [OPTIONS] PCAPFILE

Options:
  --tlsmaster PATH  TLS master secrets file
  --help            Show this message and exit.

cuckoo:~/cuckoo$ httpreplay storage/analyses/276/dump_sorted.pcap 
('192.168.4.61', 49322, '185.106.122.46', 80) 1467732020.814432 http /upload/_dispatch.php
('192.168.4.61', 49322, '185.106.122.46', 80) 1467732021.634650 http /upload/_dispatch.php
('192.168.4.61', 49322, '185.106.122.46', 80) 1467732022.404344 http /upload/_dispatch.php
INFO:httpreplay.smegma:Could not find TLS master secret for stream 192.168.4.61:49323 -> 191.232.139.253:443, skipping it.
('192.168.4.61', 49322, '185.106.122.46', 80) 1467732040.264086 http /upload/_dispatch.php
('192.168.4.61', 49381, '23.197.7.27', 80) 1467732047.069203 http /pkiops/crl/MicSecSerCA2011_2011-10-18.crl
('192.168.4.61', 49310, '160.153.74.199', 80) 1467731930.198851 http /98uhnvcx4x
('192.168.4.61', 49372, '2.22.119.65', 80) 1467732041.559856 http /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?4488f9f8451176a8

But Cuckoo analysis throws the same error, so furthermore there seems to be a need for an adjustment in network.py for passing the parameter to httpreplay.

Regards,
RedWolf

**Comment by jbremer** [comment]
Well, congrats on opening the 1000th Github issue as well as - apparently - doing a successful Locky analysis. I thought I had already bumped the `dpkt` version, but it appears that was only in the `package` branch (see also commit ca37fe0bb393093e54822b6099017191ea72751d).
Bumped now - thanks for reporting the issue.

**Comment by RedWolf74** [comment]
thanks both, the update and the congrats. It's working well now, issue closed.
