### ISSUE TITLE
hit critical timeout

### ISSUE THREAD

**Issue by blackstone-real** [cuckoosandbox/cuckoo#1002]
I have tried both RC1 and DEV in an UBUNTU box and in a MAC OSX box. The VM spins fine and cuckoo.py communicates with it but the analysis never takes place and it times out. I have tried to use this new agent instead https://github.com/jbremer/agent, but got the same results.

I run tcpdump -i vboxnet0 and cuckoo.py communicates fine with the VM agent.py. Not sure why the analysis never starts.

![image](https://cloud.githubusercontent.com/assets/20307947/16637678/d96572b0-43ae-11e6-822b-79a7b721f817.png)

Here is the debug session of cuckoo.py

2016-07-06 18:53:22,844 [lib.cuckoo.core.scheduler] DEBUG: Processing task #4
2016-07-06 18:53:22,845 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "Boleto_BancarioId3005201612.exe" (task #4, options "route=none")
2016-07-06 18:53:22,855 [lib.cuckoo.core.scheduler] INFO: File already exists at "/Users/somebox/github/cuckoo-rc/storage/binaries/0b791a36e867902ea50e92c737696f3eaabe6ed9ca863a9939db5b540892331f"
2016-07-06 18:53:22,867 [lib.cuckoo.core.scheduler] INFO: Task #4: acquired machine cuckoo2 (label=cuckoo2)
2016-07-06 18:53:22,876 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 27612 (interface=vboxnet0, host=192.168.56.102, pcap=/Users/somebox/github/cuckoo-rc/storage/analyses/4/dump.pcap)
2016-07-06 18:53:22,876 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
2016-07-06 18:53:22,957 [modules.machinery.virtualbox] DEBUG: Starting vm cuckoo2
2016-07-06 18:53:22,957 [modules.machinery.virtualbox] DEBUG: Getting status for cuckoo2
2016-07-06 18:53:23,034 [modules.machinery.virtualbox] DEBUG: Machine cuckoo2 status saved
2016-07-06 18:53:23,076 [modules.machinery.virtualbox] DEBUG: Using current snapshot for virtual machine cuckoo2
2016-07-06 18:53:23,122 [modules.machinery.virtualbox] DEBUG: Getting status for cuckoo2
2016-07-06 18:53:23,199 [modules.machinery.virtualbox] DEBUG: Machine cuckoo2 status saved
2016-07-06 18:53:25,206 [modules.machinery.virtualbox] DEBUG: Getting status for cuckoo2
2016-07-06 18:53:25,308 [modules.machinery.virtualbox] DEBUG: Machine cuckoo2 status running
2016-07-06 18:53:25,329 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo2, ip=192.168.56.102)
2016-07-06 18:53:26,336 [lib.cuckoo.core.guest] DEBUG: cuckoo2: not ready yet
2016-07-06 18:53:27,341 [lib.cuckoo.core.guest] DEBUG: cuckoo2: not ready yet
2016-07-06 18:53:28,349 [lib.cuckoo.core.guest] DEBUG: cuckoo2: not ready yet
2016-07-06 18:53:29,356 [lib.cuckoo.core.guest] DEBUG: cuckoo2: not ready yet
2016-07-06 18:53:30,361 [lib.cuckoo.core.guest] DEBUG: cuckoo2: not ready yet
2016-07-06 18:53:33,991 [lib.cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.2 (id=cuckoo2, ip=192.168.56.102)
2016-07-06 18:53:34,458 [lib.cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo2, ip=192.168.56.102)
2016-07-06 18:53:35,634 [lib.cuckoo.core.guest] DEBUG: cuckoo2: analysis still processing
2016-07-06 18:53:36,646 [lib.cuckoo.core.guest] DEBUG: cuckoo2: analysis still processing

2016-07-06 19:07:32,447 [lib.cuckoo.core.scheduler] ERROR: The analysis hit the critical timeout, terminating.
1514 packets captured
10602 packets received by filter
0 packets dropped by kernel
2016-07-06 19:07:32,452 [lib.cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2016-07-06 19:07:32,452 [modules.machinery.virtualbox] DEBUG: Stopping vm cuckoo2
2016-07-06 19:07:32,452 [modules.machinery.virtualbox] DEBUG: Getting status for cuckoo2
2016-07-06 19:07:32,531 [modules.machinery.virtualbox] DEBUG: Machine cuckoo2 status running
2016-07-06 19:07:33,546 [modules.machinery.virtualbox] DEBUG: Getting status for cuckoo2
2016-07-06 19:07:37,985 [modules.machinery.virtualbox] DEBUG: Machine cuckoo2 status poweroff
2016-07-06 19:07:38,016 [lib.cuckoo.core.scheduler] DEBUG: Released database task #5
2016-07-06 19:07:38,037 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:38,041 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path '/Users/somebox/github/cuckoo-rc/storage/analyses/5/logs'.
2016-07-06 19:07:38,041 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:38,041 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:38,044 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Debug" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:38,044 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:38,044 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:38,511 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Static" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:38,544 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Strings" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:38,573 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:38,908 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/Users/somebox/github/cuckoo-rc/modules/processing/network.py", line 764, in run
    results.update(Pcap2(pcap_path, self.get_tlsmaster()).run())
  File "/Users/somebox/github/cuckoo-rc/modules/processing/network.py", line 695, in run
    r = httpreplay.reader.PcapReader(self.pcap_path)
  File "/Users/somebox/env/lib/python2.7/site-packages/httpreplay/reader.py", line 25, in **init**
    self.pcap = dpkt.pcap.Reader(fp)
  File "/Users/somebox/env/lib/python2.7/site-packages/dpkt/pcap.py", line 111, in **init**
    self.name = fileobj.name
AttributeError: 'str' object has no attribute 'name'
2016-07-06 19:07:38,908 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:41,151 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "VirusTotal" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:41,152 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" on analysis at "/Users/somebox/github/cuckoo-rc/storage/analyses/5"
2016-07-06 19:07:41,152 [lib.cuckoo.core.plugins] DEBUG: Running 0 signatures
2016-07-06 19:07:41,175 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2016-07-06 19:07:41,238 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2016-07-06 19:07:41,239 [lib.cuckoo.core.scheduler] INFO: Task #5: reports generation completed (path=/Users/somebox/github/cuckoo-rc/storage/analyses/5)
2016-07-06 19:07:41,248 [lib.cuckoo.core.scheduler] INFO: Task #5: analysis procedure completed

**Comment by jbremer** [comment]
Can you share the sample that you're analyzing? Preferably share the zip file from `export analysis` :-)

**Comment by blackstone-real** [comment]
[storage-analyses.zip](https://github.com/cuckoosandbox/cuckoo/files/351404/storage-analyses.zip)

thanks so much! password for the zip is "infected".

**Comment by jbremer** [comment]
And what about the pcap from your `tcpdump -i vboxnet0`?

**Comment by blackstone-real** [comment]
[cuckoo-rc.pcap.pcapng.zip](https://github.com/cuckoosandbox/cuckoo/files/352070/cuckoo-rc.pcap.pcapng.zip)

this is the capture of vboxnet0

**Comment by blackstone-real** [comment]
is this a bug or a configuration issue on my side? i tried both the dev and rc1 builds and got the same timeout. anything i could try?

**Comment by jbremer** [comment]
And you configured all the IP addresses correctly?

**Comment by blackstone-real** [comment]
i think so. it is 192.168.56.1 for the host and 192.168.56.102 for the guest VM. networking does not look like to be the issue as the host talks to the guest fine. there is something in the agent side that does not kick in the analysis. the analyzer seems to be transmitted fine and received by the guest VM, but it does not start running i guess. i can't say if the payload to be analyzed has been transmitted. i don't know enough about how the process works.

**Comment by blackstone-real** [comment]
any more clues?

**Comment by HelioCD** [comment]
I too hit the same issue, using Ubuntu 14 and Cuckoo 2.0-rc1, sandbox Win7x64. IP addresses are configured properly, I can ping between the host and guest.
Any further advice would be greatly appreciated. Thanks!

**Comment by jbremer** [comment]
Sorry for the late reply. Did all of you resolve your issues already @blackstone-real @HelioCD? If so, how did you do that / what was the problem / etc?

**Comment by vineetpurswani** [comment]
I am running into the same issue. I am using Ubuntu 16.04 (Host), Cuckoo 2.0-rc2 and Win7x64 (Guest). I checked and found that old agent is being kicked on and RPC connection is setup, which is working fine. @jbremer any idea how to solve this issue? I have been trying to find a workaround since more than a week now, yet with no luck.

**Comment by cvdsouza** [comment]
Hi, 
So I'm having the same issue 
2017-03-21 00:43:56,807 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.

I'm on Ubuntu 16.04 Host , Cuckoo 2.0-rc2 and Win7x32 Guest. vboxnet0 on 192.168.56.1 and guest on 192.168.56.101

Guest has the same agent that's on rc2 branch. 

tcpdump of vboxnet0 is here : https://www.packettotal.com/cgi-bin/view-analysis.cgi?id=6f6528a91b2fa2731c66ceaf0d4d39d4

Not sure what I'm messing up here. I would really appreciate any guidance . 

Thanks.

**Comment by jbremer** [comment]
@cvdsouza is the VM able to reach the host?

**Comment by cvdsouza** [comment]
Yes , I was able to ping 192.168.56.1 successfully on the VM. I actually have two VMs now 192.168.56.101 and .102 , both able to ping the host.. but giving the critical timeout error.

**Comment by vineetpurswani** [comment]
This solved my problem - [https://github.com/cuckoosandbox/cuckoo/issues/704#issuecomment-244813495](url), except that I disable all the UAC properties in Local Security Policy utility and not just the one given in the referred comment.

**Comment by jbremer** [comment]
Going to close this issue as resolved. Upgrading to the latest Cuckoo already helps a great deal here.

**Comment by piero1974** [comment]
> Questo ha risolto il mio problema: [https://github.com/cuckoosandbox/cuckoo/issues/704#issuecomment-244813495](url) , tranne per il fatto che disattivo tutte le proprietà UAC nell'utilità della politica di sicurezza locale e non solo quella fornita nel commento indicato.

Link doesn't work. Can you post it another time please?
