### ISSUE TITLE
SQL errors after Cuckoo connects to VirtualBox

### ISSUE THREAD

**Issue by fez219** [cuckoosandbox/cuckoo#1003]
Hello,

For some reason Cuckoo is giving me a super-long traceback error that ends in SQL problems. I'm not sure what's going on, I followed everything in the Cuckoo book and should have a working sandbox.

I couldn't find anything about these problems in the documentation or other forums. I think I may have messed up a few settings or permissions early on in my build. If I can't come up with a solution soon, I will restart from scratch.

I have an Ubuntu host and a Windows 7 guest on VirtualBox. Another possible problem may be the system I'm trying to use; it's old and may have hardware issues.

If my error turns out to be something stupid I overlooked, (which is quite possible), I apologize for wasting everybody's time!

Here's what the error looks like on Command line:

Cuckoo Sandbox 2.0-rc1
www.cuckoosandbox.org
Copyright (c) 2010-2015

Checking for updates...
Good! You have the latest version available.

2016-06-27 11:37:50,365 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
Traceback (most recent call last):
File "./cuckoo.py", line 121, in
cuckoo_main(max_analysis_count=args.max_analysis_count)
File "./cuckoo.py", line 91, in cuckoo_main
sched.start()
File "/home/alexander/bin/cuckoo/lib/cuckoo/core/scheduler.py", line 598, in start
self.initialize()
File "/home/alexander/bin/cuckoo/lib/cuckoo/core/scheduler.py", line 527, in initialize
machinery = plugin()
File "/home/alexander/bin/cuckoo/lib/cuckoo/common/abstracts.py", line 73, in init
self.db.clean_machines()
File "/home/alexander/bin/cuckoo/lib/cuckoo/common/utils.py", line 258, in inner
return f(self, *args, **kwargs)
File "/home/alexander/bin/cuckoo/lib/cuckoo/core/database.py", line 460, in clean_machines
self.engine.execute(machines_tags.delete())
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1991, in execute
return connection.execute(statement, *multiparams, **params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in executeon_connection
return connection.executeclauseelement(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in executeclauseelement
compiled_sql, distilled_params
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in executecontext
context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in handledbapi_exception
exc_info
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in executecontext
context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM machines_tags']

**Comment by cssanchit** [comment]
This issue is discussed at 

https://github.com/brad-accuvant/cuckoo-modified/issues/200

have a look at it

**Comment by jbremer** [comment]
I don't think that issue is related, see also the last line in the traceback `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM machines_tags']`. Is your `db/cuckoo.sqlite` file writable (or can you make it writable - `chmod +w db/cuckoo.sqlite`)?

**Comment by jbremer** [comment]
Any update on this issue? It will be closed as resolved otherwise ;-)

**Comment by hlckalana** [comment]
@jbremer,

This command is worked for me

chown -R user-name:user-name /opt/cuckoo/cuckoo.db

Regards,
Kalana
