### ISSUE TITLE
httpreplay: AssertionError in self._readState.encContext.isBlockCipher

### ISSUE THREAD

**Issue by ChriDr** [cuckoosandbox/cuckoo#1008]
Hello,

frequently I am getting the following httpreplay error:

ERROR:modules.processing.network:Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/home/administrator/Cuckoo/utils/../modules/processing/network.py", line 815, in run
    results.update(p2.run())
  File "/home/administrator/Cuckoo/utils/../modules/processing/network.py", line 732, in run
    l = sorted(r.process(), key=lambda x: x[1])
  File "/home/administrator/.local/lib/python2.7/site-packages/httpreplay/reader.py", line 85, in process
    self.tcp and self.tcp.process(ts, ip, packet)
  File "/home/administrator/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 88, in process
    s.process(ts, tcp, to_server)
  File "/home/administrator/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 362, in process
    self.states[self.state](self, ts, tcp, to_server)
  File "/home/administrator/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 285, in state_conn
    self.parent.handle(self.s, self.ts, "tcp", sent, recv)
  File "/home/administrator/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 592, in handle
    while self.states[self.state](self, s, ts):
  File "/home/administrator/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 518, in state_decrypt
    self.tls.decrypt_server(record.type, record.data)
  File "/home/administrator/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 419, in decrypt_server
    return str(self._recordLayer._decryptThenMAC(record_type, bytearray(buf)))
  File "/home/administrator/.local/lib/python2.7/site-packages/tlslite/recordlayer.py", line 469, in _decryptThenMAC
    assert self._readState.encContext.isBlockCipher
AssertionError

I also can provide pcap files, if nessary!

Best regards,

**Comment by jbremer** [comment]
Please provide the `dump.pcap` and `tlsmaster.txt` files :-)

**Comment by ChriDr** [comment]
Thanks Jurriaan!

[dump_tlsmaster.zip](https://github.com/cuckoosandbox/cuckoo/files/362063/dump_tlsmaster.zip)

**Comment by dfirbuddy** [comment]
Hi ChriDi,Jurriaan
there seems to be an error inside tlslite-ng. I have had the same error always with RC4 based stream ciphers which are not jet support.  See => https://github.com/jbremer/httpreplay/issues/9
I wrote a small script for tshark to decode and extract information's as a workaround. The question is how we want to fix that problem. One way would be to ignore not supported cipher suites.  At leased the program should not die and continue  to decode the pcap and write a warning to the logfile.
To fix the  tlslite-ng is perhaps not that easy. An other workaround could be to decode the pcap with tshark and write the information into a xml file (option -Tpdml). Then use python and lxml to scan an import the result into cuckoo. 
Let me know what you think about this approach. 
Best Regards
 Willy

**Comment by jbremer** [comment]
As per my comment at https://github.com/jbremer/httpreplay/issues/9, I've released a new version of `httpreplay` with fixes for this issue, and updated the version number in both the `master` branch as well as the `package` branch. Closing this issue as resolved. Thanks!
