### ISSUE TITLE
Failed to run the reporting module "MongoDB":

### ISSUE THREAD

**Issue by Bressie** [cuckoosandbox/cuckoo#1027]
Hello,

I am running Cuckoo 1.2 and I am getting error Failed to run the reporting module "MongoDB"
error listed below. I am running pymongo 3.0.3 and this is the list of all packages. Is there any fix or what I am doing wrong?

# pip freeze
Django==1.8.4
Jinja2==2.7.3
Magic-file-extensions==0.2
MarkupSafe==0.23
Pillow==2.6.1
Pygments==2.0.1
Pyrex==0.9.8.5
SOAPpy==0.12.22
SQLAlchemy==0.9.8
argparse==1.2.1
bottle==0.12.7
cffi==0.8.6
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
cybox==2.1.0.12
defusedxml==0.4.1
distorm3==3
docutils==0.12
dpkt==1.6
html5lib==0.999
libvirt-python==1.2.9
lxml==3.4.0
maec==4.1.0.12
ndg-httpsclient==0.3.2
numpy==1.8.2
pefile==1.2.9.1
ply==3.4
pyOpenSSL==0.14
pyasn1==0.1.7
pycparser==2.10
pycups==1.9.63
pycurl==7.19.5
pydeep==0.4
pygobject==3.14.0
pymongo==3.0.3
pysmbc==1.0.15.3
python-apt==0.9.3.12
python-dateutil==2.5.3
python-debian==0.1.27
python-debianbts==1.11
pyxdg==0.25
reportbug==6.6.3
requests==2.4.3
roman==2.0.0
six==1.8.0
urllib3==1.9.1
vboxapi==1.0
volatility==2.3.1
wheel==0.24.0
wsgiref==0.1.2
wstools==0.4.3
yara-python==3.1

2016-08-04 15:52:33,362 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager
2016-08-04 15:52:33,655 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-08-04 15:52:33,666 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
[04/Aug/2016 15:52:36] "GET /submit/ HTTP/1.1" 200 11916
[04/Aug/2016 15:52:42] "POST /submit/ HTTP/1.1" 200 2739
2016-08-04 15:52:42,835 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_NK7LYg/PhishMe_Triage_Best_Practices_April_2016.pdf" (task=2)
2016-08-04 15:52:42,862 [lib.cuckoo.core.scheduler] INFO: Task #2: acquired machine WindowsXPSP3 (label=WindowsXPSP3)
2016-08-04 15:52:42,867 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 18770 (interface=vboxnet0, host=192.168.56.101, dump path=/root/cuckoo-1.2/storage/analyses/2/dump.pcap)
2016-08-04 15:52:44,592 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=WindowsXPSP3, ip=192.168.56.101)
2016-08-04 15:54:57,040 [lib.cuckoo.core.guest] INFO: WindowsXPSP3: analysis completed successfully
2016-08-04 15:55:37,382 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/root/cuckoo-1.2/lib/cuckoo/core/plugins.py", line 505, in process
    current.run(self.results)
  File "/root/cuckoo-1.2/modules/reporting/mongodb.py", line 87, in run
    if "cuckoo_schema" in self.db.collection_names():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 488, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 699, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 663, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused

/cuckoo-1.2# mongod
mongod --help for help and startup options
Thu Aug  4 16:17:42.260 [initandlisten] MongoDB starting : pid=18986 port=27017 dbpath=/data/db/ 64-bit host=euegis0mal02v
Thu Aug  4 16:17:42.260 [initandlisten] db version v2.4.10
Thu Aug  4 16:17:42.260 [initandlisten] git version: nogitversion
Thu Aug  4 16:17:42.260 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55
Thu Aug  4 16:17:42.260 [initandlisten] allocator: tcmalloc
Thu Aug  4 16:17:42.260 [initandlisten] options: {}
Thu Aug  4 16:17:42.260 [initandlisten] exception in initAndListen: 10296
*********************************************************************
 ERROR: dbpath (/data/db/) does not exist.
 Create this directory or give existing directory in --dbpath.
 See http://dochub.mongodb.org/core/startingandstoppingmongo
*********************************************************************
, terminating
Thu Aug  4 16:17:42.260 dbexit:
Thu Aug  4 16:17:42.260 [initandlisten] shutdown: going to close listening sockets...
Thu Aug  4 16:17:42.260 [initandlisten] shutdown: going to flush diaglog...
Thu Aug  4 16:17:42.260 [initandlisten] shutdown: going to close sockets...
Thu Aug  4 16:17:42.260 [initandlisten] shutdown: waiting for fs preallocator...
Thu Aug  4 16:17:42.260 [initandlisten] shutdown: lock for final commit...
Thu Aug  4 16:17:42.260 [initandlisten] shutdown: final commit...
Thu Aug  4 16:17:42.260 [initandlisten] shutdown: closing all files...
Thu Aug  4 16:17:42.260 [initandlisten] closeAllFiles() finished
Thu Aug  4 16:17:42.260 dbexit: really exiting now

**Comment by Bressie** [comment]
not sure if something wrong with mongodb.. when I try 

/cuckoo-1.2# mongo cuckoo
MongoDB shell version: 2.4.10
connecting to: cuckoo
Thu Aug  4 16:52:19.238 Error: couldn't connect to server 127.0.0.1:27017 at src/mongo/shell/mongo.js:145
exception: connect failed

**Comment by xistense** [comment]
"ERROR: dbpath (/data/db/) does not exist." -> imho the drive where mongo stored its databases is either unmounted, the folder itself was deleted or moved. 
You have following solutions:
1. check what happened with old information from respective folder and try to recover it (mount the drive, undelete, etc)
or
2. change dbPath in /etc/mongod.conf to a new location where mongo will create a new set of databases
or
3. create the folder /data/db and mongo will create a new set of databases there.

**Comment by Bressie** [comment]
Thanks xistense for help
