### ISSUE TITLE
Android analysis error

### ISSUE THREAD

**Issue by Haidern** [cuckoosandbox/cuckoo#1040]
I have some questions about Android analysis.This is the log:
2016-08-12 14:48:42,373 [lib.cuckoo.core.scheduler] INFO: Using "avd" as machine manager
2016-08-12 14:48:42,615 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-08-12 14:48:42,631 [lib.cuckoo.core.scheduler] INFO: Unable to determine the network interface for VM with name cuckoo1, Cuckoo will not be able to give it full internet access or route it through a VPN! Please define a default network interface for the machinery or define a network interface for each VM.
2016-08-12 14:48:42,632 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-08-12 14:53:04,507 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "xxxx.apk" (task #1, options "route=none")
2016-08-12 14:53:05,400 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired machine cuckoo1 (label=cuckoo1)
2016-08-12 14:53:05,407 [modules.auxiliary.sniffer] ERROR: Network interface not defined, network capture aborted
2016-08-12 14:53:05,409 [lib.cuckoo.common.objects] WARNING: Unable to import androguard (`pip install androguard`)
2016-08-12 14:53:06,047 [modules.machinery.avd] INFO: Stopping AVD listening on port 5554
2016-08-12 14:53:07,216 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/hero/cuckoo2.0-rc1/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/hero/cuckoo2.0-rc1/lib/cuckoo/core/scheduler.py", line 325, in launch_analysis
    machinery.start(self.machine.label, self.task)
  File "/home/hero/cuckoo2.0-rc1/modules/machinery/avd.py", line 75, in start
    self.duplicate_reference_machine(label)
  File "/home/hero/cuckoo2.0-rc1/modules/machinery/avd.py", line 126, in duplicate_reference_machine
    self.replace_content_in_file(hw_qemu_config_file, reference_machine, label)
  File "/home/hero/cuckoo2.0-rc1/modules/machinery/avd.py", line 153, in replace_content_in_file
    with open(fileName, 'r') as fd:
IOError: [Errno 2] No such file or directory: u'/home/hero/.android/avd/cuckoo1.avd/hardware-qemu.ini'

There are my questions:
   1.Where should I configure network interface? I find the place( the node ''interface") when i use virtualbox or vmware, but could not find the place in avd.conf.
  2.the folder named cuckoo1.avd was delete by cuckoo when i submit one apk file.
  3.how to set up the Android analysis environment? the http://docs.cuckoosandbox.org/en/latest/ is not detailed,where is detailed documents?

thanks!

**Comment by jbremer** [comment]
Actually, for `avd` we have a different sniffer thing in place, so you can (and should) disable the `sniffer` auxiliary module.
We have not yet fully ported the documentation, so please find it here http://cuckoo-droid.readthedocs.io/en/latest/installation/guest_android_avd/.

**Comment by jbremer** [comment]
Any update on this issue @Haidern?

**Comment by Haidern** [comment]
Thanks! I have already succeeded according to your solution。

**Comment by lovina37** [comment]
@Haidern 
can you help sniffer is disabled
I am using recent version on setup number two i.e cuckoo cuckoodroid and emulator on same host
lovina@lovina-Aspire-E1-571:~/Downloads/cuckooMode1$ python cuckoo.py

                           ),-.     /
Cuckoo Sandbox <(a ---',' no chance for malwares! (-, .> )
) >._/
_/

Cuckoo Sandbox 2.0-rc2
www.cuckoosandbox.org
Copyright (c) 2010-2015

Checking for updates...
Good! You have the latest version available.

2017-04-12 20:07:09,853 [root] INFO: Updated running task ID 5 status to failed_analysis
2017-04-12 20:07:09,897 [lib.cuckoo.core.scheduler] INFO: Using "avd" as machine manager
2017-04-12 20:07:10,142 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-12 20:07:10,180 [lib.cuckoo.core.scheduler] INFO: Unable to determine the network interface for VM with name aosx_2, Cuckoo will not be able to give it full internet access or route it through a VPN! Please define a default network interface for the machinery or define a network interface for each VM.
2017-04-12 20:07:10,181 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-04-12 20:07:44,968 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "1.apk" (task #6, options "")
2017-04-12 20:07:45,082 [lib.cuckoo.core.scheduler] INFO: Task #6: acquired machine aosx_2 (label=aosx_2)
2017-04-12 20:07:45,227 [modules.machinery.avd] INFO: Stopping AVD listening on port 5554
2017-04-12 20:07:46,412 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
File "/home/lovina/Downloads/cuckooMode1/lib/cuckoo/core/scheduler.py", line 519, in run
self.launch_analysis()
File "/home/lovina/Downloads/cuckooMode1/lib/cuckoo/core/scheduler.py", line 385, in launch_analysis
machinery.start(self.machine.label, self.task)
TypeError: start() takes exactly 2 arguments (3 given)
