### ISSUE TITLE
Analysis not working

### ISSUE THREAD

**Issue by fez219** [cuckoosandbox/cuckoo#1045]
Hello,

I followed what should be working instructions, and cross-referenced them with other instructions, and am still having issues. My Cuckoo build, as far as I can see, should be able to analyze malware. Yet, every single sample causes errors. Sometimes, I also get timeout errors. 

One last issue I have is that only a report.json is created. I don't understand why there is no report.html. Here is my latest sample run:

2016-08-17 10:09:13,770 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "npp.6.9.2.Installer.exe" (task #16, options "")
2016-08-17 10:09:13,988 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/alexander/cuckoo/storage/binaries/a329d076a349c9bffa02bfe670e1d9beaa21ce10a695db2d675e9346b6e72fca"
2016-08-17 10:09:14,097 [lib.cuckoo.core.scheduler] INFO: Task #16: acquired machine cuckoo1 (label=windows7-cuckoo)
2016-08-17 10:09:14,118 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 22921 (interface=vboxnet0, host=192.168.56.101, pcap=/home/alexander/cuckoo/storage/analyses/16/dump.pcap)
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
2016-08-17 10:09:18,294 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2016-08-17 10:09:32,232 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\rpvwuuavo\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\rpvwuuavo\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

124 packets captured
124 packets received by filter
0 packets dropped by kernel
2016-08-17 10:09:37,248 [modules.processing.static] CRITICAL: You do not have the m2crypto library installed preventing certificate extraction: pip install m2crypto
2016-08-17 10:09:38,990 [lib.cuckoo.core.scheduler] INFO: Task #16: reports generation completed (path=/home/alexander/cuckoo/storage/analyses/16)
2016-08-17 10:09:39,152 [lib.cuckoo.core.scheduler] INFO: Task #16: analysis procedure completed

**Comment by Higgsz** [comment]
Make sure that cuckoo agent is run by administrator privileges.

**Comment by fez219** [comment]
I have the agent in the startup folder, as agent.pyw and I only have a administrator account on the VM. I don't think it's that, because the VM is still listening on the correct port.

It could be networking issues, except I think I've done everything correctly with iptables and such. My VM at one point was working with internet, but not it refuses and I'm not sure why. The VM is still spun up by Cuckoo, it just doesn't correctly do the analysis.

**Comment by Higgsz** [comment]
Did you disable UAC?

**Comment by fez219** [comment]
Yes, I disabled UAC.

**Comment by fez219** [comment]
I think I just fixed some stuff in config files, I at least get html reports to show up. Here's what I get now:

2016-08-18 14:45:51,014 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "npp.6.9.2.Installer.exe" (task #18, options "")
2016-08-18 14:45:51,241 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/alexander/cuckoo/storage/binaries/a329d076a349c9bffa02bfe670e1d9beaa21ce10a695db2d675e9346b6e72fca"
2016-08-18 14:45:51,347 [lib.cuckoo.core.scheduler] INFO: Task #18: acquired machine windows7-cuckoo (label=windows7-cuckoo)
2016-08-18 14:45:51,364 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5482 (interface=vboxnet0, host=192.168.56.101, pcap=/home/alexander/cuckoo/storage/analyses/18/dump.pcap)
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
2016-08-18 14:45:58,065 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=windows7-cuckoo, ip=192.168.56.101)
2016-08-18 14:46:14,072 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\kaldspgre\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\kaldspgre\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

133 packets captured
133 packets received by filter
0 packets dropped by kernel
2016-08-18 14:46:18,349 [modules.processing.memory] ERROR: Cannot run volatility module: volatility library not available
2016-08-18 14:46:19,601 [modules.processing.static] CRITICAL: You do not have the m2crypto library installed preventing certificate extraction: pip install m2crypto
2016-08-18 14:46:21,747 [lib.cuckoo.core.scheduler] INFO: Task #18: reports generation completed (path=/home/alexander/cuckoo/storage/analyses/18)
2016-08-18 14:46:21,883 [lib.cuckoo.core.scheduler] INFO: Task #18: analysis procedure completed

**Comment by fez219** [comment]
With debug (I'll look through it in a sec and hopefully figure it out):

2016-08-18 14:45:51,014 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "npp.6.9.2.Installer.exe" (task #18, options "")
2016-08-18 14:45:51,241 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/alexander/cuckoo/storage/binaries/a329d076a349c9bffa02bfe670e1d9beaa21ce10a695db2d675e9346b6e72fca"
2016-08-18 14:45:51,347 [lib.cuckoo.core.scheduler] INFO: Task #18: acquired machine windows7-cuckoo (label=windows7-cuckoo)
2016-08-18 14:45:51,364 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5482 (interface=vboxnet0, host=192.168.56.101, pcap=/home/alexander/cuckoo/storage/analyses/18/dump.pcap)
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
2016-08-18 14:45:58,065 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=windows7-cuckoo, ip=192.168.56.101)
2016-08-18 14:46:14,072 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\kaldspgre\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\kaldspgre\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

133 packets captured
133 packets received by filter
0 packets dropped by kernel
2016-08-18 14:46:18,349 [modules.processing.memory] ERROR: Cannot run volatility module: volatility library not available
2016-08-18 14:46:19,601 [modules.processing.static] CRITICAL: You do not have the m2crypto library installed preventing certificate extraction: pip install m2crypto
2016-08-18 14:46:21,747 [lib.cuckoo.core.scheduler] INFO: Task #18: reports generation completed (path=/home/alexander/cuckoo/storage/analyses/18)
2016-08-18 14:46:21,883 [lib.cuckoo.core.scheduler] INFO: Task #18: analysis procedure completed

**Comment by fez219** [comment]
On debug mode:

2016-08-18 17:22:24,205 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-08-18 17:24:19,278 [lib.cuckoo.core.scheduler] DEBUG: Processing task #19
2016-08-18 17:24:19,304 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "npp.6.9.2.Installer.exe" (task #19, options "")
2016-08-18 17:24:19,545 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/alexander/cuckoo/storage/binaries/a329d076a349c9bffa02bfe670e1d9beaa21ce10a695db2d675e9346b6e72fca"
2016-08-18 17:24:19,625 [lib.cuckoo.core.scheduler] INFO: Task #19: acquired machine windows7-cuckoo (label=windows7-cuckoo)
2016-08-18 17:24:19,641 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6567 (interface=vboxnet0, host=192.168.56.101, pcap=/home/alexander/cuckoo/storage/analyses/19/dump.pcap)
2016-08-18 17:24:19,642 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
2016-08-18 17:24:20,295 [modules.machinery.virtualbox] DEBUG: Starting vm windows7-cuckoo
2016-08-18 17:24:20,296 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:24:20,427 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status saved
2016-08-18 17:24:20,549 [modules.machinery.virtualbox] DEBUG: Using current snapshot for virtual machine windows7-cuckoo
2016-08-18 17:24:20,870 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:24:20,964 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status saved
2016-08-18 17:24:25,366 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:24:25,498 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status running
2016-08-18 17:24:26,334 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=windows7-cuckoo, ip=192.168.56.101)
2016-08-18 17:24:27,342 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: not ready yet
2016-08-18 17:24:28,348 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: not ready yet
2016-08-18 17:24:29,357 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: not ready yet
2016-08-18 17:24:30,382 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: waiting for status 0x0001
2016-08-18 17:24:30,421 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: status ready
2016-08-18 17:24:30,478 [lib.cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=windows7-cuckoo, ip=192.168.56.101, monitor=latest, size=1696272)
2016-08-18 17:24:31,118 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analyzer started with PID 2396
2016-08-18 17:24:31,292 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: waiting for completion
2016-08-18 17:24:31,698 [lib.cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2016-08-18 17:24:32,299 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:24:33,306 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:24:34,319 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:24:35,333 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:24:36,346 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:24:37,318 [lib.cuckoo.core.resultserver] DEBUG: File upload request for shots/0001.jpg
2016-08-18 17:24:37,331 [lib.cuckoo.core.resultserver] DEBUG: Uploaded file length: 52168
2016-08-18 17:24:37,353 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:24:38,373 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:24:39,389 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\frjrmpzn\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\frjrmpzn\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

2016-08-18 17:24:39,448 [lib.cuckoo.core.resultserver] DEBUG: File upload request for shots/0002.jpg
2016-08-18 17:24:39,467 [lib.cuckoo.core.resultserver] DEBUG: Uploaded file length: 49969
125 packets captured
125 packets received by filter
0 packets dropped by kernel
2016-08-18 17:24:39,928 [lib.cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2016-08-18 17:24:39,932 [modules.machinery.virtualbox] DEBUG: Stopping vm windows7-cuckoo
2016-08-18 17:24:39,934 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:24:40,090 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status running
2016-08-18 17:24:41,371 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:24:41,526 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status poweroff
2016-08-18 17:24:43,142 [lib.cuckoo.core.scheduler] DEBUG: Released database task #19
2016-08-18 17:24:43,222 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:43,223 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:43,226 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:43,226 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:43,230 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Debug" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:43,231 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:43,232 [modules.processing.memory] ERROR: Cannot run volatility module: volatility library not available
2016-08-18 17:24:43,232 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Memory" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:43,232 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:43,233 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:44,101 [modules.processing.static] CRITICAL: You do not have the m2crypto library installed preventing certificate extraction: pip install m2crypto
2016-08-18 17:24:44,143 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Static" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:44,430 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Strings" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:44,656 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:44,757 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:46,067 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "VirusTotal" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:46,069 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" on analysis at "/home/alexander/cuckoo/storage/analyses/19"
2016-08-18 17:24:46,119 [lib.cuckoo.core.plugins] DEBUG: Running 339 signatures
2016-08-18 17:24:46,266 [lib.cuckoo.core.plugins] DEBUG: Analysis matched signature: pe_features
2016-08-18 17:24:46,349 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2016-08-18 17:24:46,446 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2016-08-18 17:24:46,859 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "ReportHTML"
2016-08-18 17:24:46,859 [lib.cuckoo.core.scheduler] INFO: Task #19: reports generation completed (path=/home/alexander/cuckoo/storage/analyses/19)
2016-08-18 17:24:47,013 [lib.cuckoo.core.scheduler] INFO: Task #19: analysis procedure completed

**Comment by jbremer** [comment]
Can you try a different binary?

**Comment by fez219** [comment]
@jbremer Just tried with the 32 bit Windows Firefox installer exe. No dice. 

Just noticed this message appear in the VM: "No injection method has been provided!"

2016-08-18 17:37:42,801 [lib.cuckoo.core.scheduler] DEBUG: Processing task #20
2016-08-18 17:37:42,828 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "FirefoxSetup48.0.1.exe" (task #20, options "")
2016-08-18 17:37:44,564 [lib.cuckoo.core.scheduler] INFO: Task #20: acquired machine windows7-cuckoo (label=windows7-cuckoo)
2016-08-18 17:37:44,584 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6940 (interface=vboxnet0, host=192.168.56.101, pcap=/home/alexander/cuckoo/storage/analyses/20/dump.pcap)
2016-08-18 17:37:44,585 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
2016-08-18 17:37:44,784 [modules.machinery.virtualbox] DEBUG: Starting vm windows7-cuckoo
2016-08-18 17:37:44,785 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:37:44,922 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status poweroff
2016-08-18 17:37:45,037 [modules.machinery.virtualbox] DEBUG: Using current snapshot for virtual machine windows7-cuckoo
2016-08-18 17:37:45,377 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:37:45,464 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status saved
2016-08-18 17:37:49,806 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:37:49,949 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status running
2016-08-18 17:37:50,830 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=windows7-cuckoo, ip=192.168.56.101)
2016-08-18 17:37:51,839 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: not ready yet
2016-08-18 17:37:52,844 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: not ready yet
2016-08-18 17:37:53,835 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: not ready yet
2016-08-18 17:37:54,849 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: waiting for status 0x0001
2016-08-18 17:37:54,882 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: status ready
2016-08-18 17:37:54,897 [lib.cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=windows7-cuckoo, ip=192.168.56.101, monitor=latest, size=1696272)
2016-08-18 17:38:19,539 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analyzer started with PID 2764
2016-08-18 17:38:19,954 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: waiting for completion
2016-08-18 17:38:20,968 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:21,980 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:22,993 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:23,205 [lib.cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2016-08-18 17:38:24,003 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:25,014 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:26,027 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:27,038 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:28,048 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:29,062 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:29,531 [lib.cuckoo.core.resultserver] DEBUG: File upload request for shots/0001.jpg
2016-08-18 17:38:29,546 [lib.cuckoo.core.resultserver] DEBUG: Uploaded file length: 42987
2016-08-18 17:38:30,077 [lib.cuckoo.core.guest] DEBUG: windows7-cuckoo: analysis not completed yet (status=2)
2016-08-18 17:38:30,665 [lib.cuckoo.core.resultserver] DEBUG: File upload request for shots/0002.jpg
2016-08-18 17:38:30,682 [lib.cuckoo.core.resultserver] DEBUG: Uploaded file length: 53930
2016-08-18 17:38:31,095 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\weuwc\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\weuwc\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

175 packets captured
175 packets received by filter
0 packets dropped by kernel
2016-08-18 17:38:31,186 [lib.cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2016-08-18 17:38:31,187 [modules.machinery.virtualbox] DEBUG: Stopping vm windows7-cuckoo
2016-08-18 17:38:31,187 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:38:31,286 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status running
2016-08-18 17:38:32,393 [modules.machinery.virtualbox] DEBUG: Getting status for windows7-cuckoo
2016-08-18 17:38:32,493 [modules.machinery.virtualbox] DEBUG: Machine windows7-cuckoo status poweroff
2016-08-18 17:38:33,901 [lib.cuckoo.core.scheduler] DEBUG: Released database task #20
2016-08-18 17:38:33,981 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:33,983 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:33,985 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:33,986 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:33,989 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Debug" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:33,990 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:33,990 [modules.processing.memory] ERROR: Cannot run volatility module: volatility library not available
2016-08-18 17:38:33,991 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Memory" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:33,991 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:33,991 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:34,380 [modules.processing.static] CRITICAL: You do not have the m2crypto library installed preventing certificate extraction: pip install m2crypto
2016-08-18 17:38:34,812 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Static" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:38,009 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Strings" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:40,164 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:40,296 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:41,557 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "VirusTotal" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:41,558 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" on analysis at "/home/alexander/cuckoo/storage/analyses/20"
2016-08-18 17:38:41,607 [lib.cuckoo.core.plugins] DEBUG: Running 339 signatures
2016-08-18 17:38:41,772 [lib.cuckoo.core.plugins] DEBUG: Analysis matched signature: pe_features
2016-08-18 17:38:41,782 [lib.cuckoo.core.plugins] DEBUG: Analysis matched signature: packer_upx
2016-08-18 17:38:42,391 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2016-08-18 17:38:44,612 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2016-08-18 17:38:45,273 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "ReportHTML"
2016-08-18 17:38:45,273 [lib.cuckoo.core.scheduler] INFO: Task #20: reports generation completed (path=/home/alexander/cuckoo/storage/analyses/20)
2016-08-18 17:38:45,422 [lib.cuckoo.core.scheduler] INFO: Task #20: analysis procedure completed

**Comment by jbremer** [comment]
Ah, time to upgrade your Cuckoo I guess.. you're on 2.0-rc1 I take it? I think we introduced an issue on our side when updating the Community stuff on 2.0-rc1..

**Comment by fez219** [comment]
@jbremer My version is 2.0-dev, is that not the same?

**Comment by fez219** [comment]
@jbremer I did that and it worked! Thanks :)

**Comment by jbremer** [comment]
@fez219 Okay, happy to hear that ;-) Let us know if you run into any other issues.
