### ISSUE TITLE
Errno 30 - Function not implemented in Database #622

### ISSUE THREAD

**Issue by srishti-agarwal** [cuckoosandbox/cuckoo#1055]
This is in reference to getting the error of missing function not implemented in database
This is the traceback call
Traceback (most recent call last):
  File "./cuckoo.py", line 20, in <module>
    from lib.cuckoo.core.scheduler import Scheduler
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 21, in <module>
    from lib.cuckoo.core.guest import GuestManager
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 28, in <module>
    db = Database()
  File "/home/cuckoo/cuckoo/lib/cuckoo/common/utils.py", line 206, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/database.py", line 386, in __init__
    raise CuckooDatabaseError("Unable to create database directory: {0}".format(e))
lib.cuckoo.common.exceptions.CuckooDatabaseError: Unable to create database directory: Unable to create folder: /home/cuckoo/cuckoo/db
Exception AttributeError: "'Database' object has no attribute 'engine'" in <bound method Database.__del__ of <lib.cuckoo.core.database.Database object at 0xb5bd6cac>> ignored

**Comment by jbremer** [comment]
Any reason for this error message? ;-)
`Unable to create folder: /home/cuckoo/cuckoo/db`

**Comment by srishti-agarwal** [comment]
Thanks :-)
