### ISSUE TITLE
Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by mahaveer1984** [cuckoosandbox/cuckoo#1060]
After submitting the sample for analysis I am getting below error. 
Does this error come because of python or cuckoo itself??
it is instantly closing virtual machine(KVM)
![cuckoo-error3](https://cloud.githubusercontent.com/assets/19815922/18042197/12c712ae-6ddd-11e6-9df0-b198e073139d.png)

**Comment by doomedraven** [comment]
@mahaveer1984 error says your vm name is too long or empty, also use only english chars(just in case)

**Comment by mahaveer1984** [comment]
ok I will try short name. My vm name is Android-cuckoo. Thank you so much

**Comment by mahaveer1984** [comment]
I have changed my virtual machine name to AC and taken new snapshot still I am facing the same issue.

2016-08-29 14:02:19,540 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/sstl01mahaveer/cuckoo/cuckoo-master/lib/cuckoo/core/scheduler.py", line 519, in run
    self.launch_analysis()
  File "/home/sstl01mahaveer/cuckoo/cuckoo-master/lib/cuckoo/core/scheduler.py", line 399, in launch_analysis
    self.guest_manage(options)
  File "/home/sstl01mahaveer/cuckoo/cuckoo-master/lib/cuckoo/core/scheduler.py", line 301, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/sstl01mahaveer/cuckoo/cuckoo-master/lib/cuckoo/core/guest.py", line 375, in start_analysis
    self.wait_available()
  File "/home/sstl01mahaveer/cuckoo/cuckoo-master/lib/cuckoo/core/guest.py", line 306, in wait_available
    socket.create_connection((self.ipaddr, self.port), 1).close()
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/usr/lib/python2.7/encodings/idna.py", line 73, in ToASCII
    raise UnicodeError("**********label empty or too long")
UnicodeError: **********label empty or too long

**Comment by mahaveer1984** [comment]
There was some configuration issue. I found the solution.

**Comment by matrixpdb** [comment]
> There was some configuration issue. I found the solution.

Please, tel me how fix this error?

Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 406, in run
    success = self.launch_analysis()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 317, in launch_analysis
    guest.start_analysis(options)
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 256, in start_analysis
    self.wait_available()
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 158, in wait_available
    socket.create_connection((self.ipaddr, self.port), 1).close()
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
