### ISSUE TITLE
ERROR: Analysis failed: The package "modules.packages.doc" start function raised an error: Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by KevinKien** [cuckoosandbox/cuckoo#1084]
Hello team,

After installation Cuckoo Sandbox 2.0-rc1, I have run command "./utils/community.py -wafb monitor". And I received this error trying to submit a .doc file into the Cuckoo SandBox. 

> 2016-09-12 17:19:26,003 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.doc" start function raised an error: Unable to execute the initial process, analysis aborted.
> 23 packets captured
> 23 packets received by filter
> 0 packets dropped by kernel
> 2016-09-12 17:19:32,349 [lib.cuckoo.common.objects] WARNING: Unable to import yara (please compile from sources)
> 2016-09-12 17:19:32,355 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
> `

I run agent with:
- Window XPSP3 32 bit
- Python 32 bit
- Offfice 2007 32 bit.

Please help me.

**Comment by alabiana** [comment]
I have the same Problem. It appeared from one to another analysis without any changes on the system.

The Sandbox Agent has this log:
2016-09-20 15:11:08,030 [analyzer] DEBUG: Starting analyzer from: C:\cbbhxa
2016-09-20 15:11:08,312 [analyzer] DEBUG: Pipe server name: \\.\PIPE\SuwmIBiLkVdEfTqY
2016-09-20 15:11:08,312 [analyzer] DEBUG: Log pipe server name: \\.\PIPE\OFWqjqidLBSQFIZocYeViQPry
2016-09-20 15:11:08,312 [analyzer] DEBUG: No analysis package specified, trying to detect it automagically.
2016-09-20 15:11:08,312 [analyzer] INFO: Automatically selected analysis package "doc"
2016-09-20 15:11:10,890 [analyzer] DEBUG: Started auxiliary module Disguise
2016-09-20 15:11:12,644 [analyzer] DEBUG: Loaded monitor into process with pid 500
2016-09-20 15:11:12,644 [lib.api.process] INFO: Successfully injected process with pid None
2016-09-20 15:11:12,644 [analyzer] DEBUG: Started auxiliary module DumpTLSMasterSecrets
2016-09-20 15:11:12,644 [analyzer] DEBUG: Started auxiliary module Human
2016-09-20 15:11:12,644 [analyzer] DEBUG: Started auxiliary module InstallCertificate
2016-09-20 15:11:12,644 [analyzer] DEBUG: Started auxiliary module Screenshots
2016-09-20 15:11:13,470 [lib.api.process] ERROR: Failed to execute process from path 'C:\\Program Files (x86)\\Microsoft Office\\Office14\\WINWORD.EXE' with arguments ['bin\\inject-x86.exe', '--app', u'C:\\PROGRA~2\\MICROS~1\\Office14\\WINWORD.EXE', '--args', u'C:\\Users\\user\\AppData\\Local\\Temp\\xxxxxxtestxx.docx', '--free', '--curdir', u'C:\\Users\\user\\AppData\\Local\\Temp'] (Error: The pipe has been ended (ERROR_BROKEN_PIPE))

And cuckoo says:
2016-09-20 15:11:07,935 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "\xxxxxxtestxx.docx" (task #35, options "route=internet,free=yes")
2016-09-20 15:11:07,942 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/user/cuckoo/storage/binaries/389199059aa9389d09eb685de04b5be507015a856b4fcc3d6b262070a829c656"
2016-09-20 15:11:08,010 [lib.cuckoo.core.scheduler] INFO: Task #35: acquired machine cuckoo-win7a (label=cuckoo-win7a)
2016-09-20 15:11:08,019 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 12719 (interface=vboxnet0, host=192.168.100.11, pcap=/home/user/cuckoo/storage/analyses/35/dump.pcap)
2016-09-20 15:11:14,547 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo-win7a, ip=192.168.100.11)
2016-09-20 15:11:28,384 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.doc" start function raised an error: Unable to execute the initial process, analysis aborted.

Sandbox: Windows 7 x64 2GB RAM Python 2.7
Host: 16.04.1 LTS x64 8GB RAM Python 2.7
Virtualbox 5.0.26 r108824

Any idea?

**Comment by nsmfoo** [comment]
Try running:  ./community.py -waf and see if this resolves your issue?

**Comment by Barbarian7** [comment]
I have the problems (Cuckoo Sandbox 2.0-rc1) same as KevinKien and alabiana.  I've tried nsmfoo's suggestion, nothing changed. 

Error: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.doc" start function raised an error: Unable to execute the initial process, analysis aborted. Traceback (most recent call last): File "C:\bfsqnafniz\analyzer.py", line 778, in <module> success = analyzer.run() File "C:\bfsqnafniz\analyzer.py", line 626, in run (package_name, e) CuckooError: The package "modules.packages.doc" start function raised an error: Unable to execute the initial process, analysis aborted. 

Error: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.pdf" start function raised an error: Unable to execute the initial process, analysis aborted. Traceback (most recent call last): File "C:\kdudhtrv\analyzer.py", line 778, in <module> success = analyzer.run() File "C:\kdudhtrv\analyzer.py", line 626, in run (package_name, e) CuckooError: The package "modules.packages.pdf" start function raised an error: Unable to execute the initial process, analysis aborted.

What should I do? Thanks.

**Comment by doomedraven** [comment]
first of all try rc2

**Comment by jbremer** [comment]
As @doomedraven said, please start by upgrading to `2.0-rc2` and see if that does the job for you.

**Comment by Barbarian7** [comment]
Hi All,
I've tried RC2, the problems remain. 
Any ideas?

**Comment by SparkyNZL** [comment]
Stupid question but... You do have word and Adobe installed aye ?

**Comment by Barbarian7** [comment]
@SparkyNZL  I guess that you must be the smartest guy, right? Regard to the "Stupid question", I "had" Office 2007 and Adobe Reader 9 installed.

**Comment by doomedraven** [comment]
omg, is like reboot if not working, you not provided that info so he was need to ask
you not even provided hashes for testing on out side, no vm info etc etc....

**Comment by jbremer** [comment]
To everyone involved here, is this issue still present?

**Comment by jbremer** [comment]
Closing for lack of information. If this is still a problem for you, please try to upgrade to the latest Cuckoo once more and see if that fixes your issues. We're currently working on some additional tweaks that should make any problems stated here much better handled / resolved. Thanks for the feedback!

**Comment by mishamehra** [comment]
hi guys,
i am using cuckoo version rc2, and have installed adobe reader5 on windowsxp VM. I am getting the following error on submitting the pdf file 
2017-05-16 12:08:06,515 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.pdf" start function raised an error: Unable to find any Adobe Reader executable.
Traceback (most recent call last):
  File "C:\wpmyp\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\wpmyp\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.pdf" start function raised an error: Unable to find any Adobe Reader executable.

However, I am not getting the same problem on submitting the word documents.
