### ISSUE TITLE
Couldn't Launch the Analysis with REST API

### ISSUE THREAD

**Issue by Sanghyun-Hong** [cuckoosandbox/cuckoo#1096]
Hi, 

I have an issue of launching an analysis with REST API. I used the Xenserver, and tried to run the analysis from the snapshot with REST API. However, when I submitted an analysis, connection of the Xenserver host disconnected, and the storage of snapshot lost. Here are the error messages:

@Cuckoo API side:
```
2016-09-17 17:09:54,440 [lib.cuckoo.core.scheduler] DEBUG: Processing task #1
2016-09-17 17:09:54,457 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "001ae6120763ee998e3eff44ada6886f315cfbdc" (task #1, options "")
2016-09-17 17:09:55,081 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired machine cuckoo (label=45dff1d7-39bb-7a05-fdba-89e9332e18d2)
2016-09-17 17:09:55,443 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 28988 (interface=xenbr0, host=192.168.0.61, pcap=/opt/Cuckoo/storage/analyses/1/dump.pcap)
2016-09-17 17:09:55,446 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2016-09-17 17:09:56,018 [modules.machinery.xenserver] DEBUG: Reverting vm 45dff1d7-39bb-7a05-fdba-89e9332e18d2 to snapshot b5494fa8-c082-9a31-95e1-4852f66ce1e6
packet_write_wait: Connection to 192.168.1.129: Broken pipe
```

@Python code:
```
Traceback (most recent call last):
  File "./matrix.py", line 355, in <module>
    init_matrix()
  File "./matrix.py", line 342, in init_matrix
    '7, or Server 2008 R2', 'poc_data') # 'win7_malware_x86')
  File "./matrix.py", line 259, in submit_analysis
    alive_response = requests.get(CUCKOO_REST_STATUS_URL)
  File "/Users/<user>/anaconda/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/<user>/anaconda/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/<user>/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/<user>/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/<user>/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.129', port=8090): Max retries exceeded with url: /cuckoo/status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10aa67b10>: Failed to establish a new connection: [Errno 60] Operation timed out',))
```

Can you tell me what can be the issue?

-S.

**Comment by doomedraven** [comment]
hm it looks more like xen issue then cuckoos one, you need debug your connection to host, if yu connect throw ssh, use ssh -vvv ....

**Comment by Sanghyun-Hong** [comment]
@doomedraven, I think the issue is related to the Cuckoo, since if we keep polling the REST API /cuckoo/status to check the analysis process. It makes the connection fail. Can you look at the issue?

**Comment by doomedraven** [comment]
@Sanghyun-Hong i don't know what you want me to check in cuckoo, it works just fine for me, sorry can't help here

**Comment by Sanghyun-Hong** [comment]
@doomedraven, Hmm... sure, however, if the /cuckoo/status REST API works, can you let me know how did you examine this API? once I submit an analysis to the Cuckoo with REST API, and use the status API, all the connections of Host is reset.

**Comment by doomedraven** [comment]
```
curl http://X:8090/tasks/create/file -F file=@pafish.exe -F timeout=30
{
  "task_id": 372
}


curl http://X:8090/cuckoo/status
{
  "cpuload": [
    X,
    X,
    X,
  ],
  "diskspace": {
    "analyses": {
      "free": X,
      "total": X,
      "used": X
    },
    "binaries": {
      "free": X,
      "total": X,
      "used": X
    }
  },
  "hostname": "X",
  "machines": {
    "available": X,
    "total": X
  },
  "memory": X,
  "tasks": {
    "completed": 0,
    "pending": 0,
    "reported": X,
    "running": 0,
    "total": 372
  },
  "version": "2.0-dev"
}
```

status requests works even in loop, with no problem

so is your connection/setup problem

**Comment by Sanghyun-Hong** [comment]
Hi, As you commented, I tried the with the curl commands, and it works. However, if I tried with the request module in the document, it says errors.

-S.

**Comment by doomedraven** [comment]
if curl works fine and requests not, it definitely not a cuckoo error.


```
>>> r = requests.post(url_base+"tasks/create/file", files=files)
>>> r.json()
{u'task_id': 375}

>>> r = requests.get(url_base+"cuckoo/status")
>>> r.json()
{u'tasks': {u'reported': X, u'completed': 0, u'total': X, u'running': 1, u'pending': 0}, u'diskspace': {u'analyses': {u'total': X, u'used': X, u'free': X}, u'binaries': {u'total': X, u'used': X, u'free': X}}, u'hostname': X', u'cpuload': [0.89, 0.45, 0.39], u'version': u'2.0-dev', u'memory': X, u'machines': {u'available': X, u'total': X}
```

works with for i in xrange(20):
     r = requests.get(url_base+"cuckoo/status")


so it's your setup error

**Comment by Sanghyun-Hong** [comment]
@doomedraven, okay, I see, thanks for the support. I will close this issue.

**Comment by doomedraven** [comment]
i hope you can find and solve your issue :)

best regards
