### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by baufrecht** [cuckoosandbox/cuckoo#1113]
Hi,

certain malware samples seem to flood the **pe_exports** field which triggers the following exception during analysis run.

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 13: ordinal not in range(128)

According to a short conversion with Jurriaan (Thx for the help) it has something to do with the File.get_exported_function()

I'm running Cuckoo 2.0-dev Commit 05ab01b1d92c36b892a8e5e1913f74ab74b5e605

If there is more information needed please feel free to ask. since I can currently reproduce this behavior if needed.

Here is a short log file output with the config variable print out in between.

```
2016-09-27 14:56:42,194 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5837 (interface=vboxnet0, host=192.168.56.38, pcap=/home/cuckoo/cuckoo/storage/analyses/1069/dump.pcap)
2016-09-27 14:56:42,561 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo39, ip=192.168.56.39)
2016-09-27 14:56:42,865 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo27, ip=192.168.56.27)
2016-09-27 14:56:43,059 [lib.cuckoo.core.scheduler] INFO: Task #1035: analysis procedure completed
2016-09-27 14:56:43,385 [lib.cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.1 (id=cuckoo25, ip=192.168.56.25)
2016-09-27 14:56:43,457 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "sample_h_jek3bw" (task #1070, options "")
2016-09-27 14:56:43,767 [lib.cuckoo.core.guest] INFO: cuckoo36: analysis completed successfully
2016-09-27 14:56:43,863 [lib.cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.1 (id=cuckoo21, ip=192.168.56.21)
2016-09-27 14:56:44,064 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo16, ip=192.168.56.16)
2016-09-27 14:56:44,329 [lib.cuckoo.core.scheduler] INFO: Task #1070: acquired machine cuckoo20 (label=cuckoo20)
['[analysis]', u'category = file', u'target = /tmp/cuckoo-tmp/upload_EkKARF/sample_z_f_40pi', u'package = ', 'file_type = PE32 executable (GUI) Intel 80386, for MS Windows', u'file_name = sample_z_f_40pi', 'clock = 20160927T14:56:22', 'id = 1
063', 'terminate_processes = False', 'options = apk_entry=:', 'enforce_timeout = False', 'timeout = 60', u'ip = 192.168.56.1', 'pe_exports = \xf8\x16\x9f\x19\x04\xa359\x90\xfc\xda\xb1\x0c\x9a\xa0\x91\xae\xd6\xb1\xedK\xcc\xc4\xc7\xa3\xac.\xb9\
xeeq\xcc\xec\x90\x96\x81\x17\xaa\xafi\x8a\x7f\x8e\x08\x17Z\xd3\x9f\xc2\xf9\x13\xdb"\x1fe\x9d\xc4@\x9e\xf6\x11\x98z.\x05\xfd\xea\xe4\x97\xafm(\xd8 \x06\x87\xf8\xe2\xcf\x81\xcd04\xe5\x90:\xbd\xe6\\E\xa7\x13/3z\xe5n|\x82\x9e?H\xd6\xa5\xa5\x900\x
94\xbe\x90\xf26\x85o\x82\x94\x06X\xcag\\p*r\xe3\xe4\x903\x88\x8b~f\x83\xb2\xd7;\x08\xae\x0c\xd2\xa3L\x18OV\x18\xf9\x94\xa26q\x89"D\xc2\xe7\xd5`P\xfb\xc7n\xb6\xd8/-Se\xa6\xa1\xcc\xc6\xb8\n\x8d\x81>O\xcbs]\x96\x8e]!\x06\xbe,~\xd5\xc2F5\xab\xb4\
xf7a{\x9c\xc5@\xcd\xdaX\xe0=\x14\xa7\xce}\xdc\xa2\xfb\xbd\xef\x14a\xc0\x1e\xd8\xac\xfb\xe3?\xea\x8f7%\x0ce\xfd\xa1%\xe1\xd0W\xd3\xdeb?\xafQ\xc5x\x9d\xf4X\x85\xfdB\x96\xed\xff\x8f\xa26\x1c\xa8\xaf\xaa\xf763`<N~\xf3\x1e\xe9#\xe9\x19\xbbQ\xb0\xb
1\x0b~,%\x1d\x12\xcfoL\xe3\x9e\x0bH\xc6\xb5\xbd>\xee\x8f\xfcE\xe6D\x9e\xe1sn[\xf0\x81i\xfc\xd1\x8f\xa8\x1b\xa7\xaeD\xc5v\xff\x92\x90\t\xd5\xd4M\xd0T\xe0\xf6\xc0C\xc0\x89If6Wj\x8a\xa4\x99\x1e\xa8;\xb7\xfa=x\x9fU\xc2\xca\x19\xc3k}\xe9E\xfd\xa7I
|}Gf*\x81\xce\x84e\xd5H\xf2J]M\xe4vCyo3k\xa8\xa4\x18J\x87(wx^*\xf76\x19\x11\x8f\xbd\xeb\xeb\xe3}\x9fJ35g\xa3\xba\xfa=z]/\xafHi\xe80\xf5\xc8\xc3\xa0\xe1\xf6@[:\x8a\n\xe0-*\xd4\xd9\xb4\xbb*\xba\x85/\xd0\x1a\xd9\'5\x89\xaa\xdeq\x17\x0f\x19U\xb0\
xcf\x83#\x99d\xb1I\xa9\xf8A_\x87\x1b\xc7\xab\x192~\xe6J|\xe7\x9a\xff\x89\xe2B@\x88S\x97\xf2\xe2g\x1a\xbd\xe8\x9a\xcf\xe1\x17vU\x1f\xb8B\x1eye\x15\x92o$\xf9m\x845\xa5o\x95\xc7\xe1g\xef\xa1\xb5\x95\x1b\xf0\xe4hN\xe0\xda\xa2\xfc\x9f\x19\xd5un\xa
5^\x8bf\xbb\xb3)\x11\x19\xbeb\x88\xb4\x93T\xa5?\xb8\xe7~/RRDD\xe8]6=\xa0\xcd\xb0\'\x86\x06\xab\x10d\xa7\x95\xf5\xa9WX?c\xf0\x9b\x1fZ\xbbd\x9e\xbdyEK|d2\xa3;e#S\xfd+\xb4]\xeb[\xce\xb6_\t\x1c\xf9\x8e\xbbD/\x87\x95K\\QqxMe\x96\xa0HZBP(\xe8)\x10\
x0f\xaa\xc3^\x1a\xc2o\x08\xde\xc3N\xf5\x90~\xd4\xae\x15\xa6\x8b\tk\xe0`\xe4\xa5$\x8fX\xe7\xa0\x14\xa5\x12s\x04w$\xe9h\xa8n!\xe2\x9a\xa7\xb2A\xdcx\xcc=\xb4\x8a\xde\x0f\xb1\xc0\xb4\x1cn\x98\xb3d\xae[\x10\xe5b\x9a\x9f\xb1\\\xac?\\,\x1dM\x83\xfa\xbcE\xa1\xcdS\x83T\x10\x1d\x19\xdbZ\x84cs8`\xb9T|\nbq\xd4!$\xbe@\xdb\'(\x01\x98\x07\xf5;4)H]D\xd5\xe3\xf6\xba%\x81&\x9b\xa4\xdf\xb3@e/\x1bW\xce\xb2y\x94\xd2!\xbaJz\x9cv^\xd9dJ\xc4b\xef3\x8b"\xb2+\x0cp<\x8e\xd1\x8dY\x87\xde\xae\x87\x91;\x11\xc2\xc7\x92~\x1c\x8eEX\x87[\xb0\xa7\xdf\x13\x0e\xb8\rS\xb3\xb8\xbf$\x15v\xbd\xcaL*\xaa\xd5\x88\xdbH\x9a\xb4d\x1c%\xa3\x18s\xe8\x1c\x87\xb4\xac\x1cy}\xfb\x9a\x07\xe7\xa1%o\x13\xe6\xb5\x1a\xb3\xa7\xf8\xdc\xcf}ys\xebq\xf5B\xce!"\xd2\x17\xacU\xaa\xd1\xd6\xc9\\\xd3\xc6b\xf8\xef\xb2\xb6\xca\xd9\xfcK\xf4\xd7\x89\xaf\xe4}<}1\xa3\x03_P\xd0P\x9a\xc5?\xe8\xd0-Ig\xed\xca\xd0\xd7p\xfc\xfa^\x83\xb5\xc6\xb0%fge@\xf8adv=Q\xed\x11\xf7\xdb\x8dB\xe0-l\xb0\xcf\x97\xd6\x06\xe7\x18hk\xe8\xe6\xb4\xaf\x1b\xe1\xdd\x85[Zm\x0c\xc7\xabj\xa5\xa2\xa2\xf0\xb4S\r\xd1T&\x87\x81\x9e2\xd4\xce\x8e\x89\xe4\xaf\xa8\x18L\xac[\xd1\xc3\x1cJ\x11\x95A\x04\\t\x95\xc3\xd5\x1a\xa8\xc9 \xc9\x7ffy{\xd3\xbcF\xd3\x0b\xec\xe7\'l\x93\t8\xbf\xdf\xb2\xeb\x03\x9em\x14Q\x0c+&\x94CDi\xca\x8c\xcex\xd2\x8a\x03&\x89\xdb\x88\x1a\xc9C\xe0\xb7\xfd|6,R,\xd3\xa8M2\x0b)\xcd7NX3E8\xdc7OW8<\xd9\xeb\xed\tB\xee\xa2OV\x1cyf(\xc0\xbd\x88[#\xc0 \xe0*\xe9Y\xc7.]\x84(\x0fD\x0b\xd0\xf7\x8f\x7f\xaf\xfaA\x81\xa8\xd5\x1b\x89N\x9aCS3\x12+l@}\xd6\xb5\xcf\x9dRN\xf4)\xee\xb3-\x07\x13\x17k\x81\xbc4\xaeJ{\x1c"\xf9\x8b\xd4h\xebM\xa7\x19\x9b\xbb\x13\x9dg\xb9\xbe\xd9Y<\xc3\xde\xe6\xad\xce\x9a\xb3\xa2\xdb\xacU\xa9\x92i\xad\xcf\x06-:\xae\xd8\xf0\x12\x98\x10\xf3`\xb3\x13?\x07\x94\xa1\xdbY\xb88&u\xe7\xc1fFYq\xae5)47\xf5\xfa\x9c\x14\x9dR\x9f\x9bQ\x85\x9c\xcf\xce\xc6\x82\x1b\x142\xfa\xbb_a\x03%\xdf`V\xc0\xc7\x18\x03\xc2\x93\x02$\x11\xb02\x07^x\x98\xc0\xfd\xfe\x04s\x9aB<\xcfM=I\x908X9o\xafO\x01\xe5\x0er\xb82;\xf2\xe1b\x8d\x06xw\xfb\x1caS\xda\x81\x9c\x85\x0e\x91\xbe\xae\xf0\xdb\x05\x7f\xd3\xe6)([\xed\xb5\xa0\xaa>\xf4\xa0\xfb\x9eW\xceC\xdcXW\xdfd=\xfey\x8fCu\xa3\t\x04_Eb>gr\xd05\xda\xb8!]\x84\x02\xdc\t\xe8\x8e\xacF\x06\xb1\xee-2J\xa0\xbd\xd2\xabs\x1f\xf8\xe2GM\x95\x1cZ\x97`\x06^\xf4\xa4{L\x08z\xdf\xaal<^\x1e\x1c(\x83\xdf\xf8\x87e \xdfLPM\xcb\xf6(@aGtl\xf6\xea\xc6\xed\xee\xccz\xacp\xa8\xf6\xdc\xe0\x81j\x1f\xa2(3\x8c\xf5\xebrc\x90(\xe9\xa9\xb8\xb6,\xf4\x05\x96G8\x80<f\xb7\xdcP\x8e\x8f\xf6n\x86a\xce\x1d\xf9&\xb4\x01\xf2\xaaU\x1462k\xea\x18X#\xbcg\x13\xa1;\xef\t\x9c\t\xbe\x0by6%\xe0\xf0#$\xd0\x11D\xc0y<\xfd\xe8kg\xb4g\xa6\xb9\xbf\x8f[Z\xce\'\x8e\x02\x81\xa4\x99\xac3\xd8\x89eL c(\x86\x8e\xd7G{a\xd7\xc2x\x8c)\x94\xdd2\xe2\xd6\x90`\xecD\xb6\xdfxu\xd2v\xfak{]\xa88\xa9Q\x04^u\xffo\xb2-\xbfX\xe4\xa5A\xec\xe9-\xb2|z}\x94\xdb\xdc\x98\x16\x8b#\xea\xd3\xdf\xa3\xa7Cp\xcb+.\x9f\x16`|c\xbew4\xb5\x87\xe6\xfb\xc5\xa3~l\xe8\x13\x99\x96\xc2\x15\xa6\xfa;\xf1\n\xe3@\xbf\xadT\xc6\xea\xb1\x80-\x1a\x8c\x87\xe6\xc8\x11\\\x8b\x9f3\x15\xb7\xe7\x01\x18\\)\x0fR\xe3M\xeesO\xcdba:\xd5V\xcfLTn\xba\xa3j\x166@5n\xbc\xd8R\r\xfe\xca\xb0Z\xd9\xf1\x85\x8b\xf9+\xed\x04I\xc1\x1e\x161\x89\xac|Q\x80N\xf32\x8a\x8d\xd1\x1aM\xeb\x8e\xf4\xb0\xdc\x10\x19w\x8d\xa6\xc0\x14\xf9\x9e\x81\x970M\xaf\xe5I\xe9R\x85\xf6;\xbe\xc6\xb5U\xe4\x8brn\xe7gC\x8d\x97\xf4z\x9a\xd4\xff\xb1\x96\x86o\x1ck\x1b\x13\xb0\xbbK\xb1\x8f\x90\x88\x04\x1f\xc5\xd9|H\xa4\x88\xfa_\x83\xe4b\t\xd8\x8a\x97\xb9\x1fT\xe9\x15u\x06\xf5\xcf\xcdItd/\x07\x07\x1f\xc2\xb9\xfer\xc0\xcb-\x8e\xf5\x92\xab\x18b\xf6:\x18\xc3\xef!\xf2\x83G\xabxO\xe2\xb2eb\xef\xc5o>Id\x9bdkq\x14?\xb4\xae)Osx\xb9\xe1]\x9f\xb2\xc2{\x02\\C-G\xa9\x0c@l\xac\x02Qt\x91\xc6cq\x16\x8a\xe6\xbeeK \x97k+\xaa\xe5tr\x01y\x17\x7f\xc4}\xe6"8ZY*\x1eg\xc60v\x88\x1f\xd9\xc4#\x94\x15\xdc\x91\xe3$\xe3\xe8\xf9fz\xca\xa2\xae\xc9\x96},\\\xa3\xd9$\x80k\xcf\x81)\xc6\x1d\x81q\x17)\xffQ\x148)\x1c\x10\xac\x87\xcf\xe0\xe0\xd0_H\xeaJ\xf3\x0fx\xb5\xcc$\xe7+\xc3\xf1\xe2*\x91H\xb2t\xe6\x7f\xe3\xe5\xea\xb6\x19\xd2+\xd7\x147-;W\xaa\x0b\x18\xe1v\\&k\xb3S\x82\xa7\xcf\xcf\xdbj\xeb\xccj\xc7\xdcj.m\xd7|\x04\xe6\n_\x0c\n\x94\xf3\xef\xa8Q\x0b\xfa^6\xaa$\x04\xc4\xd9g+vt\x9e&\xe2\xb8\xb9\xfe;wk\xe4\xc1\xa4\xcc\xefa\xc0\xf7\xc0\x86:\xa2d_^\xb7\xf6.\xdf\xf5r8\x14\x19\xa6$\xf9\x11\xc55\x12I\xfe\xb0\xb1\x81\x99}I\xc9\x05\xa9\xce\x8dI\xf3\xc6\xd2\xe4\x02\x99\x06df\xa5\x8b\xd4\x1c\xd2\xe0[\x11\x87\x8b\x88v>\xa3\xbc\xe9\xaa.\xb0\xa30"\xf9H\x02\xbc\x91\x8f\xbe\r\xc6\xceg\xdb \x1e\xefI\x82\xaf\xd7T\xba\x8b\x84\x9f2=\xc4\'\xe7\xaeL;\x88\xc6\xf0\xf1(w\x0eo\x85\xce\xdb"[\xce\xfd]\x1e\x06\xc5\xf9\xb1\xba\xc4\xd7\xf5\x9f<\xe6.\xda\x92\xa5*\xee8$\xb7-\xc8\x8a/ZH-?\xa7\xb1\xa56\x1cX\x88\xee"C \xa9Ny\xd5\xec\x8cx\xa3:Q\xc06\xb2z5*vy8~e\xf7\xc0\x9e\xf5\r[=\xd45\xc7B\x12\x9b\'\x0fr{v\xea\xb5\x168\xc1n\xfb\x1c\x943F\xf7KN\xe0\xe48\xad\x8b\\\x8a,9\x9c\xf9\x19k\xb6\xe1p3\t\'\xbeu\x11\x13%"\xcb\xff\xde\xef\x9b|\xddW^VQ\xd80\x98\xa3J\x93\xf9\xc9\xb7\xdbR\xfa\x14\xb0\xf4\x1c?\xfd+\xf6\xb2\x16\x96\x98:x1Z&\xeeQ\xf8\xcf\xed@\xc8W\xfdg\xd5\x0f\x8e\x96\x0c\xd0sg\xb5\xd5\xf9\xbde\xc4Ow\xa4\xfc\xa8\xb9\xef\xea]\xf3`[\xef\x10\x12\xa25\xd8\x13\x11\x0c\x1d\x81q\xd8\x82\x9a\xaeA\xb4\xd6GS\xb5h#\x8a\x1c-\x17\xf3\xfe\xe7{\xd5\xcb\xd5C\x94\xddx\xf2S\x02\x1cR\xecB|\xd3\xd5\xaa\x16\xf8}\xd9\xef\xab\xbf\x91\x86\xef\x82\'\x92\xc5\x02\xe8\xd2#\xfa\xf6%\xfd\xa7\x1b\x81\xa2\xc1\x94\xb2e|q\xd0n1\xdb\xe9\xaa\xae\x08S\x90\xd9\x93\x88a\x9b\x12(\x82M\x97\xd8\x91\x93\xee<\xe6\xeaZ4\x13\xbd\x8c\x19\x92R.\xa7\xc5\x81 M\xe6S`\x96\x8b\x8f\xa6Z\xf2q\xaax\x1c\xe1\xb87\xf5\x02j"%f6f\xa1L1"9\'1\x16\xb2\xc6\x1e,\x93\x8b\xb7Q\xdb\xd4\x0c\x0c\xa4\xa2iE\xfc"\x8f;\xf4\tY\x93+\r=\xf3\xd4Q\xc1\xaf\x8a\x14\xd0\xdb\xde\x82\rZ\xf6e\x0eB\xc3\xaa\xa3\x1d\xf9m\x85hp\xfa\x17\xdc\x94\x04\x9d\xda\xfa\xf4\x13\x82\xd9\x9eo_\xe3, \xa5\xd4\x98\xf4\xea\'\x12>U\xc1\x88\xff\xb1\x1b\xd3Dg\x96)\x11\xba$N\x13\xd8\\\xcb\xe7\x12\xb0\x84\xa0GVd\xf8{\x8f4\xc6\xed|\x1b\xa5D\x8a\xf1\xe8\xb6\xbe\xf3\xc9\x1a\xd9Yj\xe2%\x07\x98r\xe4\xc8p9\xb4F\xc7\x8cR1\xfaG$\xd1\x8et\xe8vA\xb7\xeb\xe3o\xa3<\xd9p\xb4\x1a?\xd5\xa6\xb4\xfc\'Ux\xbc\x03\xdaZ\xedN\xa5\x8b_J7t\xc5?\xb7\xd5y\x9c\'\xfeU4\xc3\xf2\xe5\xe7\xf5\xe8i\x8c\xdc\x80K\xbeG\xa2\x13\xe94SuZ\xa5\xfe\x88\x86h\x82;\xe1\x16i\x16\xf4l@\xf1\x0bK\xdd\x18#\xf4\x01z\x85\xd7\xbc\x0b\xa7\x7f\xf4O5\xfd\xf0\xad\xeea\xcf\xb2@\n\xd6\xaa\xaa\xeda\xde\xee7\x02\xd7\x99&\x7f\xd4\xd14\xcf\x08\x97y<\xa7\xc2\xa2Be\x05\x1d\xeel\xb0:\xb4d\xfem\x8e\xab8\xed[<Y[X\xea\x18)\x13\xfb\xfc\xf6\xc7\xbf\xe4\x19\x02\xa4\x0byc\xfa\x1c\x08\x89\xd8\xccoOY~\xc6\x82\x1c\xfa\xe6\xb8\xcf:\xa8\xd4!P1\x8d\xdcj\x0b\xd2\xa5t8\x08\xf3\xe2v\xe9d\xa7a\x82\xefM\xbe\xa2\x14M{\xa2\x9b\x92Fv\xf1\xbcF\xd2\xc7\x9aH\xeac\xe9\x01\x87q\xd8*\x02\xa3\xd5\x91Y\xf8%\xf3\xfc\x02T\xb2\xef\xe8n\xbc\xec\xaf\xa175\xcb/\xbf\x93\xa1\xc7]c\x10Bq\x10\xf8\xcd\xb4\xda\x04z+d\tE\x08I\xd9\x8d\xe7B\xde\x92i\xa3\xbaV\x88\xacd\x1e=qr\xdc\xb8\xe9\x0b@\xe0_$4MB\x90\n\xdc-\x0f&G\x91F\xd6&bh\xb2\xdd\'\xf3\xb1pY>V\x92\xf4\xc3\r\x92\x15\xee/\xe3\x13\xc3Buo2a\x82\x0f\xf2i\x9b\t\xae\xd8\x1b\n\xdd\xfb/\x17\x1c\xd2\xb7\xac\xd0\xca\'~~\xbb\xa1f\x12Ay\xb6n\\\xe0\xfd\xb4{Z\x82h\xd3Eo\xf3\xa8\x14\xfd\xb9\xe7\x82\xa0$Bd\xf0', u'port = 2042']
2016-09-27 14:56:44,663 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6004 (interface=vboxnet0, host=192.168.56.20, pcap=/home/cuckoo/cuckoo/storage/analyses/1070/dump.pcap)
2016-09-27 14:56:44,939 [lib.cuckoo.core.guest] INFO: cuckoo17: analysis completed successfully
['[analysis]', u'category = file', u'target = /tmp/cuckoo-tmp/upload_GNE__M/sample_bus06faq', u'package = ', 'file_type = PE32 executable (GUI) Intel 80386, for MS Windows', u'file_name = sample_bus06faq', 'clock = 20160927T14:56:23', 'id = 1064', 'terminate_processes = False', 'options = apk_entry=:', 'enforce_timeout = False', 'timeout = 60', u'ip = 192.168.56.1', 'pe_exports = ', u'port = 2042']
2016-09-27 14:56:45,817 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo19, ip=192.168.56.19)
2016-09-27 14:56:45,916 [lib.cuckoo.core.scheduler] INFO: Task #1061: analysis procedure completed
2016-09-27 14:56:46,138 [lib.cuckoo.core.guest] INFO: cuckoo31: analysis completed successfully
2016-09-27 14:56:46,532 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 519, in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 399, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 301, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 436, in start_analysis
    self.add_config(options)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 361, in add_config
    self.post("/store", files={"file": "\n".join(config)}, data=data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 13: ordinal not in range(128)
2016-09-27 14:56:46,610 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "sample_qjskn__y" (task #1071, options "")
2016-09-27 14:56:47,030 [lib.cuckoo.core.scheduler] INFO: Task #1055: analysis procedure completed

```

**Comment by doomedraven** [comment]
which version of pefile do you use?

**Comment by jbremer** [comment]
And can you share the sample hash maybe?

**Comment by baufrecht** [comment]
Hi, 

installed is the following version:

> dpkg -l 
> ii  python-pefile                       1.2.9.1-1.1                             all          Portable Executable (PE) parsing module for Python
> 
> pip list
> pefile (1.2.9.1)

According to the requirements.txt it seems I need pefile2 (1.2.11). Interestingly cuckoo didn't complain about that.


sample hash SHA256: a648b6ac72d5e465dc3cccf21839acdfed9b0d4e52d47594ae4dad8730da64b4

cuckoo.log
```
2016-09-29 09:05:27,367 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/cuckoo/cuckoo/storage/binaries/a648b6ac72d5e465dc3cccf21839acdfed9b0d4e52d47594ae4dad8730da64b4"
2016-09-29 09:05:27,383 [lib.cuckoo.core.scheduler] INFO: Task #15306: acquired machine cuckoo18 (label=cuckoo18)
2016-09-29 09:05:27,464 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 36541 (interface=vboxnet0, host=192.168.56.18, pcap=/home/cuckoo/cuckoo/storage/analyses/15306/dump.pcap)
2016-09-29 09:05:31,955 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo18, ip=192.168.56.18)
2016-09-29 09:05:36,809 [lib.cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.1 (id=cuckoo18, ip=192.168.56.18)
2016-09-29 09:05:41,607 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 519, in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 399, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 301, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 436, in start_analysis
    self.add_config(options)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 361, in add_config
    self.post("/store", files={"file": "\n".join(config)}, data=data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 13: ordinal not in range(128)

```
tasks.json

`{"started_on": {"$dt": "2016-09-29T09:05:27.169343"}, "duration": -1, "sample_id": 12893, "owner": "", "id": 15306, "category": "file", "priority": 1, "guest": {}, "clock": {"$dt": "2016-09-29T01:20:42.212342"}, "custom": "", "machine": "", "platform": "windows", "memory": false, "status": "running", "tags": [], "processing": null, "enforce_timeout": false, "completed_on": null, "target": "/tmp/cuckoo-tmp/upload_JXz7nX/sample_upno2u6y", "package": "", "route": null, "timeout": 60, "options": {}, "added_on": {"$dt": "2016-09-29T09:05:11.276639"}}`

**Comment by doomedraven** [comment]
can you add print before line 361?
before this
* `self.post("/store", files={"file": "\n".join(config)}, data=data)`

add
* `print config, data`

**Comment by jbremer** [comment]
He did that in a few comments above, @doomedraven :-) I just tested with that particular sample, but don't see any of the exported functions in the PE.. Odd.

**Comment by jbremer** [comment]
@baufrecht I just verified and yes indeed, with `python-pefile` this sample does indeed return an invalid exported function name. Please uninstall the package and install `pefile2` instead. Cuckoo didn't complain about it because currently it itself is not very strict about dependencies  - as long as they're imported.
With the new Cuckoo Package #863 this will change, as `pip`/`setuptools` is actually quite strict and throws around errors if an import/match was not found.
Closing as resolved (and not something that I can easily create a unit test for, unfortunately).
