### ISSUE TITLE
Android analysis issue with cuckoo IOError

### ISSUE THREAD

**Issue by decmal** [cuckoosandbox/cuckoo#1138]
Hi all,
I am trying to use cuckoo to analyze android malware. I have installed the latest version "Cuckoo Sandbox 2.0-rc1". I did all the steps stated in the manual to set up the configuration files. I have created an avd emulator named "aosx_1" and also submitted a malicious apk to cuckoo. But it raises the problem as follows:

2016-10-24 17:27:04,472 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "2d486501dcf635a5ca58bb82d3dd3539329a276d.apk" (task #1, options "")
2016-10-24 17:27:04,536 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired machine aosx (label=aosx)
2016-10-24 17:27:04,887 [modules.machinery.avd] INFO: Stopping AVD listening on port 5554
2016-10-24 17:27:06,003 **_## ### *[lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run**_*
Traceback (most recent call last):
  File "/home/mehrnoosh/Desktop/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/mehrnoosh/Desktop/cuckoo/lib/cuckoo/core/scheduler.py", line 325, in launch_analysis
    machinery.start(self.machine.label, self.task)
  File "/home/mehrnoosh/Desktop/cuckoo/modules/machinery/avd.py", line 75, in start
    self.duplicate_reference_machine(label)
  File "/home/mehrnoosh/Desktop/cuckoo/modules/machinery/avd.py", line 129, in duplicate_reference_machine
    self.replace_content_in_file(hw_qemu_config_file, reference_machine, label)
  File "/home/mehrnoosh/Desktop/cuckoo/modules/machinery/avd.py", line 156, in replace_content_in_file
    with open(fileName, 'r') as fd:
### 

[avd]
**# Specify whether we're running the Android emulator in headless mode (no GUI)
**# or with GUI - for an interactive session.****
mode = headless

**# Path to the local installation of the android emulator.**
emulator_path = /home/mehrnoosh/android-sdk/tools/emulator

**# Path to the local installation of the adb (android debug bridge) utility.**
adb_path = /home/mehrnoosh/android-sdk/platform-tools/adb

**# Path where the emulator files are located.**
avd_path = /home/mehrnoosh/.android/avd

**# Name of the reference machine that is used to duplicate.**
reference_machine = aosx_1

**# Specify a comma-separated list of available machines to be used. For each
*_# specified ID you have to define a dedicated section containing the details
*_# on the respective machine.*****\* 
machines = aosx

[aosx]
label = aosx

**# Specify the operating system platform used by current machine.**
platform = android

**# Specify the IP address of the current virtual machine. *_Make sure that the
*_# IP address is valid and that the host machine is able to reach it. If not,
**# the analysis will fail. It's always 127.0.0.1 because the android emulator**
**# runs on the loopback network interface.********
ip = 127.0.0.1

**# Specify the port for the emulator as your adb sees it.**
emulator_port = 5554

**# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
**# The Result Server will always bind to the address and port specified in cuckoo.conf,**
**# however you could set up your virtual network to use NAT/PAT, so you can specify here** 
**# the IP address for the Result Server as your machine sees it. If you don't specify an**
**# address here, the machine will use the default value from cuckoo.conf.**
**# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.**
**# Example:****
resultserver_ip = 10.0.2.2

**# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
**# The Result Server will always bind to the address and port specified in cuckoo.conf,**
**# however you could set up your virtual network to use NAT/PAT, so you can specify here**
**# the port for the Result Server as your machine sees it. If you don't specify a port**
**# here, the machine will use the default value from cuckoo.conf.**
**# Example:****
resultserver_port = 2042

**Comment by decmal** [comment]
@jbremer or anyone else who can help me, I would be grateful if you propose any suggestions in this case.

**Comment by decmal** [comment]
Hi Again,
Is anybody there? 
I have tried to solve the problem by trying to submit a task to machine "aosx_1" (please look at "avd.conf" in question above, by this command:  sudo ./submit.py --machine aosx_1 /path/to/malicious/apk
The results is now as follows:

2016-10-26 16:22:27,247 [lib.cuckoo.core.scheduler] **ERROR: Cannot acquire machine: No machines match selection criteria.**
2016-10-26 16:22:27,647 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path '/home/mehrnoosh/Desktop/cuckoo/storage/analyses/1/logs'.
2016-10-26 16:22:27,649 [modules.processing.googleplay] **ERROR: Unable to import the GooglePlay library, has it been installed properly?**
2016-10-26 16:22:27,649 [modules.processing.memory] **ERROR: Memory dump not found: to run volatility you have to enable memory_dump**
2016-10-26 16:22:27,683 [modules.processing.network] WARNING: The PCAP file does not exist at path "/home/mehrnoosh/Desktop/cuckoo/storage/analyses/1/dump.pcap".
2016-10-26 16:22:28,563 [lib.cuckoo.core.scheduler] INFO: Task #1: reports generation completed (path=/home/mehrnoosh/Desktop/cuckoo/storage/analyses/1)
2016-10-26 16:22:28,612 [lib.cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed

It creates just one .jason report file; but it seams malware has not been run inside avd emulator because there is no dynamic nalysis information in jason file.

I appreciate your help. Thanks in advance.

**Comment by jbremer** [comment]
Did you actually name your AVD `aosx_1`? Cuckoo can't seem to find it.

**Comment by decmal** [comment]
Hi Jurriaan,
Thanks to answer me. Yes, my AVD name is "aosx_1". Would you please tell me how should I change it or change the "avd.conf" configuration file? I would be really grateful if you could help me please, I am stuck here for more than one week!!

**Comment by decmal** [comment]
Dear @jbremer,

When I use an AVD named "aosx" and use the following command to submit:
**sudo ./submit.py --machine aosx  /path/to/malicious/apk**
It acquires the machine successfully but creates following **Error** messages:

2016-11-01 15:48:30,369 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "7f11794529652cf3e785e1c51b9ccbf1f00bce4a.apk" (task #1, options "")
2016-11-01 15:48:30,458 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired machine aosx (label=aosx)
2016-11-01 15:48:31,427 [lib.cuckoo.core.scheduler] **ERROR: The memory dump functionality is not available for the current machine manager.**
2016-11-01 15:48:31,427 [modules.machinery.avd] INFO: Stopping AVD listening on port 5554
2016-11-01 15:48:32,541 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/mehrnoosh/Desktop/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/mehrnoosh/Desktop/cuckoo/lib/cuckoo/core/scheduler.py", line 325, in launch_analysis
    machinery.start(self.machine.label, self.task)
  File "/home/mehrnoosh/Desktop/cuckoo/modules/machinery/avd.py", line 75, in start
    self.duplicate_reference_machine(label)
  File "/home/mehrnoosh/Desktop/cuckoo/modules/machinery/avd.py", line 129, in duplicate_reference_machine
    self.replace_content_in_file(hw_qemu_config_file, reference_machine, label)
  File "/home/mehrnoosh/Desktop/cuckoo/modules/machinery/avd.py", line 156, in replace_content_in_file
    with open(fileName, 'r') as fd:
**IOError: [Errno 2] No such file or directory: u'/home/mehrnoosh/.android/avd/aosx.avd/hardware-qemu.ini'**

Any help would be appreciated.

**Comment by jbremer** [comment]
I guess this issue has been resolved then, closing it.
