### ISSUE TITLE
Wrong url to fog prevents cuckoo from starting

### ISSUE THREAD

**Issue by mmsrubar** [cuckoosandbox/cuckoo#1146]
Hi, when I tried to run cuckoo using `python cuckoo.py` I ended up with the following exception:

```
=== Exception details ===
Cuckoo version: 2.0-dev
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Machine arch: x86_64
Git version: 657a5166d711135ee6159c8d0abc599d56d294fe
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.0 argh:0.26.2 backports-abc:0.4 backports.ssl-match-hostname:3.5.0.1 beautifulsoup4:4.4.1 blinker:1.4 certifi:2016.9.26 cffi:1.6.0 chardet:2.3.0 click:6.6 colorama:0.3.7 configargparse:0.10.0 construct:2.5.3 cryptography:1.3.2 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 elasticsearch:2.2.0 enum34:1.0.4 flask:0.10.1 h2:2.4.1 hpack:2.3.0 html2text:2016.4.2 httpreplay:0.1.17 hyperframe:3.2.0 idna:2.0 ipaddress:1.0.17 itsdangerous:0.24 jinja2:2.8 jsbeautifier:1.5.10 lxml:3.6.0 mako:1.0.1 markupsafe:0.23 mitmproxy:0.17 ndg-httpsclient:0.4.0 oletools:0.42 passlib:1.6.5 pathtools:0.1.2 peepdf:0.3.2 pefile2:1.2.11 pillow:3.2.0 pip:8.1.2 pyasn1:0.1.9 pycparser:2.14 pycrypto:2.6.1 pycurl:7.43.0 pymisp:2.4.49 pymongo:3.0.3 pyopenssl:16.2.0 pyparsing:2.1.10 pyperclip:1.5.27 python-apt:1.1.0b1 python-dateutil:2.4.2 python-editor:0.3 python-magic:0.4.6 pythonaes:1.0 pyyaml:3.12 requests:2.9.2 setuptools:20.7.0 singledispatch:3.4.0.3 six:1.10.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0a3 tornado:4.3 unity-lens-photos:1.0 urllib3:1.18 urwid:1.3.1 vboxapi:1.0 wakeonlan:0.2.2 watchdog:0.8.3 werkzeug:0.10.4 wheel:0.29.0

Traceback (most recent call last):
  File "cuckoo.py", line 122, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "cuckoo.py", line 93, in cuckoo_main
    sched.start()
  File "/home/kuki/cuckoo/lib/cuckoo/core/scheduler.py", line 670, in start
    self.initialize()
  File "/home/kuki/cuckoo/lib/cuckoo/core/scheduler.py", line 615, in initialize
    machinery.initialize(machinery_name)
  File "/home/kuki/cuckoo/lib/cuckoo/common/abstracts.py", line 97, in initialize
    self._initialize_check()
  File "/home/kuki/cuckoo/modules/machinery/physical.py", line 51, in _initialize_check
    self.fog_init()
  File "/home/kuki/cuckoo/modules/machinery/physical.py", line 197, in fog_init
    r = self.fog_query("node=tasks&sub=listhosts")
  File "/home/kuki/cuckoo/modules/machinery/physical.py", line 188, in fog_query
    return requests.post(url, data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 442, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='fog', port=80): Max retries exceeded with url: /fog/management/index.php?node=tasks&sub=listhosts (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f85b5658150>: Failed to establish a new connection: [Errno -2] Name or service not known',))

```

I'm running fog version `1.3.0-RC-15` and the correct URL should probably be: /fog/management/index.php?node=**task**&sub=listhosts

**Comment by jbremer** [comment]
Based on your traceback I'd say that Cuckoo can't reach FOG in the first place ;)

**Comment by jbremer** [comment]
Please provide more information or I'll be closing this issue :)

**Comment by mmsrubar** [comment]
I was forced to downgrade fog anyway so you can close it.

**Comment by jbremer** [comment]
Sure thing. If you have any other questions do not hesitate to let us know!
