### ISSUE TITLE
issues processing reports

### ISSUE THREAD

**Issue by lehuff** [cuckoosandbox/cuckoo#1172]
Using RC-2 on a clean install invoking process.py with python utils/process.py -p 4 -r auto

Jobs seem to run just fine a lot of the time, but I'm randomly getting the following error message followed by the process.py process crashing:

INFO:cuckoo.process:Task #7: queueing for reporting
ERROR:cuckoo.process:Caught unknown exception
Traceback (most recent call last):
  File "utils/process.py", line 128, in autoprocess
    assert task.id not in pending_results
AssertionError
Traceback (most recent call last):
  File "utils/process.py", line 203, in <module>
    main()
  File "utils/process.py", line 185, in main
    autoprocess(parallel=args.parallel)
  File "utils/process.py", line 154, in autoprocess
    pool.join()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 456, in join
    assert self._state in (CLOSE, TERMINATE)
AssertionError

**Comment by lehuff** [comment]
Even more errors, lot's of crashes with RC2:

INFO:cuckoo.process:Task #19: queueing for reporting
ERROR:lib.cuckoo.core.plugins:Failed to run the processing module "AnalysisInfo" for task #19:
Traceback (most recent call last):
  File "/opt/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 242, in process
    data = current.run()
  File "/opt/cuckoo/utils/../modules/processing/analysisinfo.py", line 37, in run
    task = json_decode(open(self.taskinfo_path).read())
  File "/opt/cuckoo/utils/../lib/cuckoo/common/utils.py", line 437, in json_decode
    return json.loads(x, object_hook=json_hook)
  File "/usr/lib64/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/opt/cuckoo/utils/../lib/cuckoo/common/utils.py", line 428, in json_hook
    return datetime.strptime(x, "%Y-%m-%dT%H:%M:%S.%f")
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2016-11-16T15:09:09' does not match format '%Y-%m-%dT%H:%M:%S.%f'
WARNING:modules.processing.baseline:Unable to run baseline processing module as we did not find the name of the Virtual Machine.
ERROR:lib.cuckoo.core.plugins:Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/opt/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/opt/cuckoo/utils/../modules/reporting/mongodb.py", line 118, in run
    report["info"]["analysis_path"] = self.analysis_path
KeyError: 'info'
INFO:cuckoo.process:Task #19: reports generation completed

**Comment by doomedraven** [comment]
return datetime.strptime(x, "%Y-%m-%dT%H:%M:%S.%f") Is not persistent error? I have ir randomly from v2.0 rc0 but it appers rarrely

**Comment by lehuff** [comment]
It doesn't happen on every analysis, but it does happen quite frequently it seems.

**Comment by doomedraven** [comment]
@lehuff can you check this one https://github.com/cuckoosandbox/cuckoo/issues/868, and provide the same info as they asked me to provide.

about `AssertionError`, i had it too, it improved in `package` branch, and if you don't want get this one, just use `process2.py` and `postgresql`

**Comment by jbremer** [comment]
Thanks for testing out the new release! As @doomedraven mentioned `process.py` has been broken since quite a while - in fact, it's not more or less broken since `2.0-rc1`. For `2.0-rc2` you're indeed recommended to use `process2.py` with `postgresql` even if this is not really documented - in the cuckoo package this situation has been much improved (but this has not been backported).
As for the other tracebacks, did you disable any `processing` modules? And I must say I haven't seen the JSON issue before, so that's interesting.

**Comment by lehuff** [comment]
I'll give process2 a shot tomorrow.  

None of the processing modules were disabled, pretty much a default setup.

**Comment by lehuff** [comment]
Not seeing any of these issues with process2.py  I dunno, I guess we should all assume process.py is broken at this point? haha

**Comment by doomedraven** [comment]
For many people it works just fine as process2, so is some magic bug :D

Best regards
Andriy
