### ISSUE TITLE
KeyError: u'physical1'

### ISSUE THREAD

**Issue by Lunakrypt** [cuckoosandbox/cuckoo#1173]
Greetings,

I am using Cuckoo Sandbox 2.0-rc1.  When I run a submit.py job.  It seems to finish the analysis without issue, but then I receive the following and have to restart cuckoo.py:

2016-11-17 14:27:04,060 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/Desktop/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/cuckoo/Desktop/cuckoo/lib/cuckoo/core/scheduler.py", line 379, in launch_analysis
    machinery.stop(self.machine.label)
  File "/home/cuckoo/Desktop/cuckoo/modules/machinery/physical.py", line 118, in stop
    self.fog_queue_task(label)
  File "/home/cuckoo/Desktop/cuckoo/modules/machinery/physical.py", line 218, in fog_queue_task
    macaddr, download = self.fog_machines[hostname]
KeyError: u'physical1'

I am using the physical.conf.  I did change the name of the guest to physical1 just in case there was an issue with the naming scheme.

**Comment by doomedraven** [comment]
First of all try rc2

Best regards
Andriy

**Comment by jbremer** [comment]
Please upgrade to `2.0-rc2` indeed and share your configuration.

**Comment by Lunakrypt** [comment]
I did upgrade to 2.0-rc2 and that particular issue is no longer occurring.  It just looks like i need to update some python tools to get everything running smoothly.  Before it had said "Good! You have the latest version available."  So I did not even check for an update.  I apologize for that.


Thank you very much for all of your quick replies.
