### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ricepotato** [cuckoosandbox/cuckoo#1182]
hello

i got segmentation fault.(core dump)

this is my cuckoo log.

2016-11-22 11:38:57,789 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/opt/cuckoo-master/lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/opt/cuckoo-master/modules/reporting/mongodb.py", line 262, in run
    self.db.analysis.save(report)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 266, in save
    return self.insert(to_save, manipulate, safe, check_keys, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 362, in insert
    self.database.connection)
InvalidDocument: BSON document too large (85859404 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2016-11-22 11:38:59,157 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Storage":
Traceback (most recent call last):
  File "/opt/cuckoo-master/lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/opt/cuckoo-master/modules/reporting/storage.py", line 296, in run
    self.db.analysis.save(report)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 266, in save
    return self.insert(to_save, manipulate, safe, check_keys, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 362, in insert
    self.database.connection)
InvalidDocument: BSON document too large (85859408 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2016-11-22 11:38:59,165 [lib.cuckoo.core.scheduler] INFO: Task #612: reports generation completed (path=/opt/cuckoo-master/storage/analyses/612)
2016-11-22 11:38:59,193 [lib.cuckoo.core.scheduler] INFO: Task #612: analysis procedure completed
2016-11-22 11:39:00,575 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/opt/cuckoo-master/lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/opt/cuckoo-master/modules/reporting/mongodb.py", line 262, in run
    self.db.analysis.save(report)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 266, in save
    return self.insert(to_save, manipulate, safe, check_keys, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 362, in insert
    self.database.connection)
InvalidDocument: BSON document too large (82165482 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2016-11-22 11:39:02,018 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Storage":
Traceback (most recent call last):
  File "/opt/cuckoo-master/lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/opt/cuckoo-master/modules/reporting/storage.py", line 296, in run
    self.db.analysis.save(report)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 266, in save
    return self.insert(to_save, manipulate, safe, check_keys, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 362, in insert
    self.database.connection)
InvalidDocument: BSON document too large (82165486 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2016-11-22 11:39:02,026 [lib.cuckoo.core.scheduler] INFO: Task #611: reports generation completed (path=/opt/cuckoo-master/storage/analyses/611)
2016-11-22 11:39:02,128 [lib.cuckoo.core.scheduler] INFO: Task #611: analysis procedure completed
Segmentation fault (core dumped)

"Storage" is my custom mongodb Reporting module. 

i have changed the value of vm upload_max_size(in cuckoo.conf) into 1048576000
may this change cause any problems?
i have 10 guest machine(virtual box).  it may memory problem?

how can i fix it?

**Comment by prats84** [comment]
make sure you have installed appropriate pymongo, and yara packages using pip. 

if the issue continues, paste in output of  pip freeze

**Comment by KillerInstinct** [comment]
Cuckoo logs aren't the correct place to look for segmentation fault issues. If you run in debug mode you may be able to see what module was executed before the fault, but it's better to look in your dmesg logs.

**Comment by jbremer** [comment]
Any feedback regarding what @KillerInstinct said, @ricepotato? Otherwise I'll be closing this issue for lack of information :-)

**Comment by jbremer** [comment]
Closing as per my comment above.
