### ISSUE TITLE
modules.packages.dll : Cannot create a file when that file already exists 

### ISSUE THREAD

**Issue by cydan33** [cuckoosandbox/cuckoo#1213]
Hey,
I get the following error:
```
2016-12-20 07:50:21,984 [lib.cuckoo.core.guest] DEBUG: xp: Ended task 158
    2016-12-20 07:50:21,987 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: [Error 183] Cannot create a file when that file already exists
    Traceback (most recent call last):
    File "C:\bivopspueo\analyzer.py", line 787, in <module>
        success = analyzer.run()
    File "C:\bivopspueo\analyzer.py", line 624, in run
        pids = self.package.start(self.target)
    File "C:\bivopspueo\modules\packages\dll.py", line 32, in start
        os.rename(path, new_path)
    WindowsError: [Error 183] Cannot create a file when that file already exists
    
    2016-12-20 07:50:21,999 [modules.machinery.virtualbox] DEBUG: Stopping vm xp
    2016-12-20 07:50:22,012 [lib.cuckoo.core.resultserver] DEBUG: Deleting task 158 (192.168.56.101)
    2016-12-20 07:50:22,051 [lib.cuckoo.core.scheduler] DEBUG: Released database task #158

```
This happens when I send a DLL file with the ".so" extension

**Comment by jbremer** [comment]
Sorry for the late response. What's the exact filename?
