### ISSUE TITLE
Restarting Analysis on a Linux VM throws an exception

### ISSUE THREAD

**Issue by JamieH** [cuckoosandbox/cuckoo#1224]
Analyzer Log:
```2016-12-29 08:30:22,004 [root] DEBUG: Starting analyzer from: /root/loquesnvsn
2016-12-29 08:30:22,005 [root] DEBUG: Storing results at: /tmp/okwUcqg
2016-12-29 08:30:22,006 [root] ERROR: Traceback (most recent call last):
  File "/root/loquesnvsn/analyzer.py", line 342, in <module>
    success = analyzer.run()
  File "/root/loquesnvsn/analyzer.py", line 134, in run
    "not exist.".format(package_name))
CuckooError: Unable to import package "modules.packages.reboot", does not exist.
Traceback (most recent call last):
  File "/root/loquesnvsn/analyzer.py", line 342, in <module>
    success = analyzer.run()
  File "/root/loquesnvsn/analyzer.py", line 134, in run
    "not exist.".format(package_name))
CuckooError: Unable to import package "modules.packages.reboot", does not exist.```
```

Cuckoo Log
```
2016-12-29 08:30:22,387 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/cuckoo/cuckoo/storage/binaries/aaa"
2016-12-29 08:30:22,448 [lib.cuckoo.core.scheduler] INFO: Task #11: acquired machine cuckoo01 (label=cuckoo01)
2016-12-29 08:30:22,460 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 10771 (interface=virbr1, host=192.168.0.6, pcap=/home/cuckoo/cuckoo/storage/analyses/11/dump.pcap)
2016-12-29 08:30:26,748 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo01, ip=192.168.0.6)
2016-12-29 08:30:27,774 [modules.auxiliary.reboot] ERROR: Reboot analysis is not backwards compatible with the Old Agent, please upgrade your target machine (<Machine('1','cuckoo01')>) to the New Agent to use the reboot analysis capabilities.
2016-12-29 08:30:29,121 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: Unable to import package "modules.packages.reboot", does not exist.
2016-12-29 08:30:29,657 [modules.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2016-12-29 08:30:29,792 [lib.cuckoo.common.objects] WARNING: Unable to import yara (please compile from sources)
2016-12-29 08:30:30,398 [elasticsearch] WARNING: POST /cuckoo-2016/cuckoo?op_type=create [status:400 request:0.009s]
2016-12-29 08:30:30,401 [lib.cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #11: TransportError(400, u'action_request_validation_exception', u'Validation Failed: 1: an id must be provided if version type or value are set;')
2016-12-29 08:30:30,534 [lib.cuckoo.core.scheduler] INFO: Task #11: reports generation completed (path=/home/cuckoo/cuckoo/storage/analyses/11)
2016-12-29 08:30:30,680 [lib.cuckoo.core.scheduler] INFO: Task #11: analysis procedure completed
```

**Comment by doomedraven** [comment]
you have error explained in log, read your log :P 
`Reboot analysis is not backwards compatible with the Old Agent, please upgrade your target machine (<Machine('1','cuckoo01')>) to the New Agent to use the reboot analysis capabilities.`

**Comment by JamieH** [comment]
I'm running the latest agent - https://github.com/cuckoosandbox/cuckoo/blob/master/agent/agent.py

**Comment by doomedraven** [comment]
@jbremer any idea what is wrong?

**Comment by JamieH** [comment]
@jbremer Surely it makes sense for the agent to be in this repository?

**Comment by jbremer** [comment]
It will be at some point, perhaps a good starting point would be the upcoming package release (see also #863). It's just that we're still supporting the *old* agent and the fact that users for most features don't have to upgrade their Agent's (which seems to be a hassle) ;-)

**Comment by jbremer** [comment]
The new Agent is now part of the `package` branch, so closing this issue as resolved. Quite unlikely that reboot analysis works with Linux as a Guest though, but that's a different issue ;-)
