### ISSUE TITLE
android emulator deleted after apk file submitted

### ISSUE THREAD

**Issue by alizohrevand** [cuckoosandbox/cuckoo#1227]
HI.
i create android emulator  correctly in android avd and put its name in avd.conf. i checked there was correct ".ini" file of it in "/.android/avd/" directory. but surprisingly after i submitted my apk file, cuckoo delete android emulator and return this error in log !!
`2016-12-31 01:08:27,784 [root] INFO: Updated running task ID 2 status to failed_analysis
2016-12-31 01:08:27,800 [lib.cuckoo.core.scheduler] INFO: Using "avd" as machine manager
2016-12-31 01:08:27,826 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-12-31 01:08:27,841 [lib.cuckoo.core.scheduler] INFO: Unable to determine the network interface for VM with name android4.1.2, Cuckoo will not be able to give it full internet access or route it through a VPN! Please define a default network interface for the machinery or define a network interface for each VM.
2016-12-31 01:08:27,841 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-12-31 01:08:47,273 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "app-debug.apk" (task #3, options "route=none,procmemdump=yes")
2016-12-31 01:08:47,331 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/android-admin/DownloadedCucukoo/cuckoo/storage/binaries/fef99fe19e4230f6f14e249258be73003f182513e584abc0df9151b540e904a7"
2016-12-31 01:08:47,350 [lib.cuckoo.core.scheduler] INFO: Task #3: acquired machine android4.1.2 (label=android4.1.2)
2016-12-31 01:08:47,353 [modules.auxiliary.sniffer] ERROR: Network interface not defined, network capture aborted
2016-12-31 01:08:47,466 [modules.machinery.avd] INFO: Stopping AVD listening on port 5554
2016-12-31 01:08:48,484 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/android-admin/DownloadedCucukoo/cuckoo/lib/cuckoo/core/scheduler.py", line 519, in run
    self.launch_analysis()
  File "/home/android-admin/DownloadedCucukoo/cuckoo/lib/cuckoo/core/scheduler.py", line 385, in launch_analysis
    machinery.start(self.machine.label, self.task)
  File "/home/android-admin/DownloadedCucukoo/cuckoo/modules/machinery/avd.py", line 75, in start
    self.duplicate_reference_machine(label)
  File "/home/android-admin/DownloadedCucukoo/cuckoo/modules/machinery/avd.py", line 117, in duplicate_reference_machine
    shutil.copyfile(avd_config_file, new_config_file)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/android-admin/.android/avd/android4.1.2.ini'`

i am sure i created emulator correctly and doubled check ".android/avd" path and there was android4.1.2.ini file in there before run cuckoo!!
ps,
sorry for my bad grammar of writing !!

**Comment by alizohrevand** [comment]
my answer was here 
https://github.com/cuckoosandbox/cuckoo/issues/1054
thanks
