### ISSUE TITLE
some database error i think and i am first time install cuckoo...

### ISSUE THREAD

**Issue by najeex** [cuckoosandbox/cuckoo#1243]
this is error 

> najeeb@najeeb:/usr/local/src/cuckoo$ python2 cuckoo.py 
Traceback (most recent call last):
  File "cuckoo.py", line 20, in <module>
    from lib.cuckoo.core.scheduler import Scheduler
  File "/usr/local/src/cuckoo/lib/cuckoo/core/scheduler.py", line 21, in <module>
    from lib.cuckoo.core.guest import GuestManager
  File "/usr/local/src/cuckoo/lib/cuckoo/core/guest.py", line 28, in <module>
    db = Database()
  File "/usr/local/src/cuckoo/lib/cuckoo/common/utils.py", line 206, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/local/src/cuckoo/lib/cuckoo/core/database.py", line 386, in __init__
    raise CuckooDatabaseError("Unable to create database directory: {0}".format(e))
lib.cuckoo.common.exceptions.CuckooDatabaseError: Unable to create database directory: Unable to create folder: /usr/local/src/cuckoo/db
Exception AttributeError: "'Database' object has no attribute 'engine'" in <bound method Database.__del__ of <lib.cuckoo.core.database.Database object at 0xb4171aec>> ignored

**Comment by doomedraven** [comment]
dont open new issues, still with first one

**Comment by jbremer** [comment]
I'm just reading the traceback, but the following doesn't sound good ;-)
```
lib.cuckoo.common.exceptions.CuckooDatabaseError: Unable to create database directory: Unable to create folder: /usr/local/src/cuckoo/db
```

**Comment by najeex** [comment]
@jbremer how to resolve this issue

**Comment by doomedraven** [comment]
add permission to write inside of  `/usr/local/src/cuckoo`

**Comment by najeex** [comment]
chmod +x or chmod 777
@doomedraven  @jbremer

**Comment by najeex** [comment]
now this happen when in change permission
`Cuckoo Sandbox 2.0-dev
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 You are running a development version! Current stable is 2.0-rc1.
2017-01-16 22:33:32,697 [root] CRITICAL: CuckooStartupError: The binaries used for Windows analysis are updated regularly, independently from the release line. It appears that you're not up-to-date. This can happen when you've just installed Cuckoo or when you've updated your Cuckoo version by pulling the latest changes from our Git repository. In order to get up-to-date, please run the following command: `./utils/community.py -wafb monitor` or `./utils/community.py -waf` if you'd also like to download over 300 Cuckoo signatures.
`

**Comment by jbremer** [comment]
Please read the message, this is not an error.

**Comment by najeex** [comment]
i know this is not error
but how to update cuckoo.. i was install yesterday

**Comment by doomedraven** [comment]
You have answer in your comment, read it
