### ISSUE TITLE
cuckoo submit --unique

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1263]
Hi 

When i submit samples i always use the unique flag, but for some reason it no longer works with the packaged version of cuckoo. When you run it the first time it works fine, but the 2nd time is a no go :( 

I get the following

-------------------------------------------------------------------------------------------------------------

cuckoo submit --platform windows --unique --owner SparkyNZL -max 2000 .
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 9, in <module>
    load_entry_point('Cuckoo==2.0.0', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 278, in submit
    bold(green("Success")), category, target, task_id
TypeError: not all arguments converted during string formatting

---------------------------------------------------------------------------------------------------------------

**Comment by jbremer** [comment]
@SparkyNZL thanks for reporting! Has been fixed now, see also the commit above :-)
