### ISSUE TITLE
Memory Error for xmlrpclib

### ISSUE THREAD

**Issue by skilgall** [cuckoosandbox/cuckoo#1276]
I am getting an error in the analyzer specifically with the xmlrpclib package.  The first Error message I receive is this:
`ERROR: Error from the Cuckoo Guest: physical1: unable to upload malware to analysis machine: <Fault 1: "<type 'exceptions.MemoryError'>:">`

Then I get a followup message:
```
ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/ubuntu/cuckoo/lib/cuckoo/core/scheduler.py", line 519, in run
    self.launch_analysis()
  File "/home/ubuntu/cuckoo/lib/cuckoo/core/scheduler.py", line 399, in launch_analysis
    self.guest_manage(options)
  File "/home/ubuntu/cuckoo/lib/cuckoo/core/scheduler.py", line 301, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/ubuntu/cuckoo/lib/cuckoo/core/guest.py", line 392, in start_analysis
    self.old.start_analysis(options, monitor)
  File "/home/ubuntu/cuckoo/lib/cuckoo/core/guest.py", line 180, in start_analysis
    self.upload_analyzer(monitor)
  File "/home/ubuntu/cuckoo/lib/cuckoo/core/guest.py", line 153, in upload_analyzer
    self.server.add_analyzer(xmlrpclib.Binary(zip_data))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault 1: "<class 'xml.parsers.expat.ExpatError'>:out of memory: line 1, column 0">
```

The binary's size is 393178537, and I even went and changed the max_upload_size to a whopping 10004857600 bytes, but to no avail.  Is there a workaround for large binaries not working with xmlrpclib?  I'm trying to make cuckoo stable through many malware samples and I'm not sure how many samples in my dataset this will affect.

**Comment by KillerInstinct** [comment]
This means the VM ran out of memory. How much memory does it have? if more than 2G you should probably run taskmgr and see what process is using up all the memory. Debug from there.

**Comment by jbremer** [comment]
Unfortunately `xmlrpclib` is known to run out of memory for larger files. As part of the new Cuckoo Agent (see also https://github.com/jbremer/agent) I plan to mitigate this issue although I haven't tested it to work properly with larger files yet (that's somewhere on the todo list).

**Comment by skilgall** [comment]
Cool, thanks for the reply and the help.  I tried to use the new agent, but it doesn't seem to work as the previous one has.
`CRITICAL: CuckooCriticalError: Error initializing machines: Unknown error occurred trying to obtain the status of physical machine physical1. Please turn it on and check the Cuckoo Agent.`
Is there a version of cuckoo that can run with this agent?

**Comment by jbremer** [comment]
I believe the Physical machinery isn't able to communicate with the new Cuckoo Agent as of now. Physical needs to be revisited as a whole, but unfortunately nobody seems to have time to really look into it currently.
