### ISSUE TITLE
Oops! Cuckoo failed in an unhandled exception!

### ISSUE THREAD

**Issue by peasead** [cuckoosandbox/cuckoo#1292]
I ran across this when attempting to start Cuckoo for the first time.

As annotated below, I am running CentOS 7.3 Core. 

I did a lot of Googling for `MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")` but wasn't able to find anything that was overly helpful...but maybe I'm not sure what I'm looking for/at?

`cuckoo/log/cuckoo.log` is blank and there are no selinux denies. 

Any help starting Cuckoo would be appreciated. 

```
=== Exception details ===
Cuckoo version: 2.0-rc2
OS version: posix
OS release: CentOS Linux 7.3.1611 Core
Python version: 2.7.5
Machine arch: x86_64
Modules: alembic:0.8.0 appdirs:1.4.0 backports.ssl-match-hostname:3.4.0.2 beautifulsoup4:4.4.1 blivet:0.61.15.59 brlapi:0.6.0 cffi:1.6.0 chardet:2.3.0 click:6.7 colorama:0.3.7 configobj:4.7.2 configshell-fb:1.1.18 coverage:3.6b3 cryptography:1.3.2 cupshelpers:1.0 custodia:0.1.0 decorator:3.4.0 di:0.3 django:1.8.4 dnspython:1.12.0 dpkt:1.8.7 ecdsa:0.13 elasticsearch:2.2.0 enum34:1.0.4 ethtool:0.8 firstboot:19.5 flask:0.10.1 fros:1.0 gssapi:1.2.0 httpreplay:0.1.17 idna:2.0 iniparse:0.4 initial-setup:0.3.9.36 ipaclient:4.4.0 ipaddress:1.0.16 ipalib:4.4.0 ipaplatform:4.4.0 ipapython:4.4.0 ipy:0.75 itsdangerous:0.24 javapackages:1.0.0 jinja2:2.8 jsbeautifier:1.5.10 jwcrypto:0.2.1 kitchen:1.1.1 kmod:0.1 langtable:0.0.31 lxml:3.6.0 mako:1.0.1 markupsafe:0.23 ndg-httpsclient:0.4.0 netaddr:0.7.5 netifaces:0.10.4 ntplib:0.3.2 oletools:0.42 packaging:16.8 peepdf:0.3.2 pefile2:1.2.11 perf:0.1 pillow:3.2.0 pip:9.0.1 ply:3.4 policycoreutils-default-encoding:0.1 pyasn1:0.1.9 pycparser:2.14 pycups:1.9.63 pycurl:7.19.0 pygobject:3.14.0 pygpgme:0.3 pyinotify:0.9.4 pykickstart:1.99.66.10 pyliblzma:0.5.3 pymisp:2.4.49 pymongo:3.0.3 pyopenssl:0.13.1 pyparsing:2.1.10 pyparted:3.9 pysmbc:1.0.13 python-augeas:0.5.0 python-dateutil:2.4.2 python-dmidecode:3.10.13 python-editor:0.3 python-ldap:2.4.15 python-magic:0.4.6 python-meh:0.25.2 python-nss:0.16.0 python-yubico:1.2.3 pythonaes:1.0 pytz:2012d pyudev:0.15 pyusb:1.0.0b1 pyxattr:0.5.1 qrcode:5.0.1 requests:2.7.0 rtslib-fb:2.1.57 seobject:0.1 sepolicy:1.1 setroubleshoot:1.1 setuptools:34.2.0 six:1.9.0 slip.dbus:0.4.0 slip:0.4.0 sqlalchemy:1.0.8 ssdeep:3.2 sssdconfig:1.14.0 targetcli-fb:2.1.fb41 tlslite-ng:0.6.0a3 urlgrabber:3.10 urllib3:1.20 urwid:1.1.1 vboxapi:1.0 volatility:2.6 wakeonlan:0.2.2 werkzeug:0.10.4 yum-langpacks:0.4.2 yum-metadata-parser:1.1.4

Traceback (most recent call last):
  File "cuckoo.py", line 120, in <module>
    test=args.test)
  File "cuckoo.py", line 68, in cuckoo_init
    init_modules()
  File "/home/variable/cuckoo/lib/cuckoo/core/startup.py", line 212, in init_modules
    import_package(modules.processing)
  File "/home/variable/cuckoo/lib/cuckoo/core/plugins.py", line 70, in import_package
    import_plugin(name)
  File "/home/variable/cuckoo/lib/cuckoo/core/plugins.py", line 60, in import_plugin
    module = __import__(name, globals(), locals(), ["dummy"], -1)
  File "/home/variable/cuckoo/modules/processing/memory.py", line 21, in <module>
    import volatility.plugins.malware.devicetree as devicetree
  File "/usr/lib/python2.7/site-packages/volatility-2.6-py2.7.egg/volatility/plugins/malware/devicetree.py", line 27, in <module>
    import volatility.plugins.malware.malfind as malfind
  File "/usr/lib/python2.7/site-packages/volatility-2.6-py2.7.egg/volatility/plugins/malware/malfind.py", line 32, in <module>
    import volatility.plugins.overlays.windows.windows as windows
  File "/usr/lib/python2.7/site-packages/volatility-2.6-py2.7.egg/volatility/plugins/overlays/windows/windows.py", line 22, in <module>
    import volatility.plugins.overlays.basic as basic
  File "/usr/lib/python2.7/site-packages/volatility-2.6-py2.7.egg/volatility/plugins/overlays/basic.py", line 33, in <module>
    import volatility.timefmt as timefmt
  File "/usr/lib/python2.7/site-packages/volatility-2.6-py2.7.egg/volatility/timefmt.py", line 27, in <module>
    import pytz
  File "/usr/lib/python2.7/site-packages/pytz/__init__.py", line 35, in <module>
    from pkg_resources import resource_stream
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```

**Comment by jbremer** [comment]
From what I can tell there's an issue with the `pytz` module that `volatility` imports. That said, we currently only support `volatility` version `2.5` officially, so perhaps a workaround would be to downgrade (you're currently on version `2.6` - I actually didn't know there's a new version already so thanks for that info).

**Comment by doomedraven** [comment]
i have v2.6 and it works fine on ubuntu, btw cuckoo is tested more under ubuntu, so i would install it on ubuntu 16.04.x as it lts

**Comment by jbremer** [comment]
True that, there's some Cuckoo functionality that doesn't work properly on CentOS ;-)

**Comment by peasead** [comment]
Thanks all, I'll check on `pytz` and Volatility.

@doomedraven I don't really want to get into a CentOS vs. Ubuntu debate (different strokes for different folks), but Ubuntu isn't going to happen.

Thanks again, gents.

**Comment by doomedraven** [comment]
Is your right to not use ubuntu :) we just say what cuckoo is tested under ubuntu so is easy for the rest deploy and get help

**Comment by peasead** [comment]
Thanks @doomedraven, I couldn't agree more :)

@jbremer it looks like you got it, it was a Volatility conflict with `pytz. I've circled it and I'll fix it later.

I'll be sure to submit a PR if I get a CentOS walkthrough done.

**Comment by jbremer** [comment]
@peasead Awesome, looking forward to it!
