### ISSUE TITLE
Cuckoo -Package - Schedualer trace

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1306]
Ive noticed this poping up from time to time, and when it does the nubmer of VM's running increases (well it appears to ) I only have 10 so its impossible to have 17 running :( Id like 17 :)
-----------------------------------------------------------

States
State	Count
failed_reporting	0
completed	30
failed_analysis	0
reported	107
**running	17**
pending	839
failed_processing	7
recovered	127

-----------------------------------------------------------------

2017-03-01 07:42:16,286 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 689, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 541, in launch_analysis
    "task_id": self.task.id,
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 34, in emit
    getattr(record, "error_action")
AttributeError: 'LogRecord' object has no attribute 'error_action'

----------------------------------------------------------------------------------

**Comment by jbremer** [comment]
I fixed this a little bit ago, will push it once I finish up merging some other stuff (tonight).

**Comment by SparkyNZL** [comment]
cheers mate, I also think this is related to the Too Many Files open thing as well 

2017-03-01 07:59:16,481 [cuckoo.machinery.virtualbox] DEBUG: Getting status for cuckoo4
2017-03-01 07:59:16,481 [cuckoo.machinery.virtualbox] WARNING: VBoxManage failed to check status for machine cuckoo4: [Errno 24] Too many open files
2017-03-01 07:59:16,481 [cuckoo.machinery.virtualbox] DEBUG: Machine cuckoo4 status False
2017-03-01 07:59:16,490 [cuckoo.core.scheduler] WARNING: Unable to stop machine cuckoo4: VBoxManage failed powering off the machine: [Errno 24] Too many open files
2017-03-01 07:59:16,529 [cuckoo.core.resultserver] DEBUG: New process (pid=1576, ppid=2320, name=e556q.exe)
2017-03-01 07:59:16,588 [cuckoo.core.resultserver] DEBUG: New process (pid=1216, ppid=2628, name=800804.exe)
2017-03-01 07:59:16,589 [cuckoo.core.resultserver] ERROR: FIXME - exception in resultserver connection ('192.168.56.44', 49193)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 259, in handle
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 297, in open_process_log
  File "/usr/lib/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 47, in emit
    with open(cwd("cuckoo.log", analysis=task_id), "a+b") as f:
IOError: [Errno 24] Too many open files: '/home/adroot/.cuckoo/storage/analyses/338/cuckoo.log'
----------------------------------------
Exception happened during processing of request from ('192.168.56.44', 49193)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 269, in handle
  File "/usr/lib/python2.7/logging/__init__.py", line 1200, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 47, in emit
    with open(cwd("cuckoo.log", analysis=task_id), "a+b") as f:
IOError: [Errno 24] Too many open files: '/home/adroot/.cuckoo/storage/analyses/338/cuckoo.log'
----------------------------------------
2017-03-01 07:59:16,674 [cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.43.
----------------------------------------
Exception happened during processing of request from ('192.168.56.43', 49557)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 650, in __init__
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 143, in setup
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 108, in register_handler
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 118, in get_ctx_for_ip
  File "/usr/lib/python2.7/logging/__init__.py", line 1212, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 47, in emit
    with open(cwd("cuckoo.log", analysis=task_id), "a+b") as f:
IOError: [Errno 24] Too many open files: '/home/adroot/.cuckoo/storage/analyses/338/cuckoo.log'
----------------------------------------
2017-03-01 07:59:16,766 [cuckoo.core.guest] DEBUG: cuckoo1: analysis not completed yet (status=2)
2017-03-01 07:59:16,788 [cuckoo.core.resultserver] DEBUG: New process (pid=2608, ppid=1576, name=pw536.exe)
2017-03-01 07:59:16,944 [cuckoo.core.guest] DEBUG: cuckoo9: error retrieving status: [Errno 111] Connection refused
2017-03-01 07:59:16,947 [cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.43.
----------------------------------------
Exception happened during processing of request from ('192.168.56.43', 49558)
Traceback (most recent call last):
2017-03-01 07:59:16,947 [cuckoo.machinery.virtualbox] DEBUG: Getting status for cuckoo2
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2017-03-01 07:59:16,948 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 689, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 586, in launch_analysis
    machinery.stop(self.machine.label)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/machinery/virtualbox.py", line 203, in stop
    self._wait_status(label, self.POWEROFF, self.ABORTED, self.SAVED)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/abstracts.py", line 305, in _wait_status
    current = self._status(label)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/machinery/virtualbox.py", line 282, in _status
    log.debug("Getting status for %s" % label)
  File "/usr/lib/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 47, in emit
    with open(cwd("cuckoo.log", analysis=task_id), "a+b") as f:
IOError: [Errno 24] Too many open files: '/home/adroot/.cuckoo/storage/analyses/340/cuckoo.log'
Exception in thread Thread-2682:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 736, in run
    "status": "error",
  File "/usr/lib/python2.7/logging/__init__.py", line 1200, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 47, in emit
    with open(cwd("cuckoo.log", analysis=task_id), "a+b") as f:
IOError: [Errno 24] Too many open files: '/home/adroot/.cuckoo/storage/analyses/340/cuckoo.log'

  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 650, in __init__
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 143, in setup
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 108, in register_handler
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 118, in get_ctx_for_ip
  File "/usr/lib/python2.7/logging/__init__.py", line 1212, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 47, in emit
    with open(cwd("cuckoo.log", analysis=task_id), "a+b") as f:
IOError: [Errno 24] Too many open files: '/home/adroot/.cuckoo/storage/analyses/338/cuckoo.log'
----------------------------------------
2017-03-01 07:59:16,967 [cuckoo.core.resultserver] DEBUG: New process (pid=3064, ppid=1216, name=86426.exe)
2017-03-01 07:59:16,967 [cuckoo.core.resultserver] ERROR: FIXME - exception in resultserver connection ('192.168.56.44', 49194)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 259, in handle
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 297, in open_process_log
  File "/usr/lib/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 47, in emit
    with open(cwd("cuckoo.log", analysis=task_id), "a+b") as f:
IOError: [Errno 24] Too many open files: '/home/adroot/.cuckoo/storage/analyses/338/cuckoo.log'
----------------------------------------
Exception happened during processing of request from ('192.168.56.44', 49194)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/resultserver.py", line 269, in handle
  File "/usr/lib/python2.7/logging/__init__.py", line 1200, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 47, in emit
    with open(cwd("cuckoo.log", analysis=task_id), "a+b") as f:
IOError: [Errno 24] Too many open files: '/home/adroot/.cuckoo/storage/analyses/338/cuckoo.log'
----------------------------------------
2017-03-01 07:59:17,019 [cuckoo.core.resultserver] DEBUG: New process (pid=3104, ppid=2608, name=j65sg76.exe)
2017-03-01 07:59:17,115 [cuckoo.core.guest] DEBUG: cuckoo8: analysis not completed yet (status=2)
2017-03-01 07:59:17,185 [cuckoo.core.guest] DEBUG: cuckoo7: analysis not completed yet (status=2)
2017-03-01 07:59:17,190 [cuckoo.core.guest] DEBUG: cuckoo5: analysis not completed yet (status=2)
2017-03-01 07:59:17,198 [cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.43.
----------------------------------------

**Comment by jbremer** [comment]
I was thinking the same, that could very much be the issue yes :)

**Comment by SparkyNZL** [comment]
it actually starting to make mroe sence now :) I decided to copy all my binaries and zero the database and start again, with the new updated package.... then i didnt have to piss around with the database as thats just asking for trouble :)

**Comment by SparkyNZL** [comment]
im trying to get a better trace for this, by they time i spot it, it scrolls through the buffer :(

**Comment by SparkyNZL** [comment]
thanks for pushing that stuff, its now all working :) and no more "Too many files" so i think we can close thoese :) whats your thoughts ? and do you ever sleep ?

**Comment by jbremer** [comment]
This once can be closed, #1295 not yet. And yes, it's on the todo list!

**Comment by SparkyNZL** [comment]
my pleasure, I enjoy it, and to be honest I;m very passionate about this project, i think what has been created is AWESOME !
