### ISSUE TITLE
Cuckoo Package - bson issue with Mongodb

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1315]
Hi cuckooers :)

Ive noticed this popping up from time to time, im not sure if this is a restriction of bson or the implementation of it with mongod ?

-------------------------------------------------------------------------

2017-03-05 12:57:28,634 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 505, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 250, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 434, in _do_batched_write_command
    max_bson_size))
DocumentTooLarge: BSON document too large (31426204 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.

------------------------------------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment]
sure can

**Comment by SparkyNZL** [comment]
ill flick it through to ya once i hunt it down :)

**Comment by Nwinternights** [comment]
I have sample that never completes a part of reducing running process timeout to 60 and disable procmem
d64a05c4e245d1cd7ef09207ecbdbd65
https://malwr.com/analysis/MTMyMjA5MDAzM2ZkNDA1YmJlOWM1ZWQxYjExNWZiNmI/
The Bson is huge more than 600MB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 599, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 263, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
DocumentTooLarge: BSON document too large (26481062 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.

regards
