### ISSUE TITLE
MongoDB - Reporting fails 

### ISSUE THREAD

**Issue by andr6** [cuckoosandbox/cuckoo#1316]
Hi,

File submission works as expected and analysis is successful.  URL submission fails to generate report.

Relevant errors on cuckoo box

2017-03-04 23:49:43,272 [lib.cuckoo.core.plugins] WARNING: The reporting module "JsonDump" returned the following error: Failed to generate JSON report: set([]) is not JSON serializable
2017-03-04 23:49:44,240 [lib.cuckoo.core.guest] DEBUG: win7: analysis not completed yet (status=2)
2017-03-04 23:49:44,848 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/opt/cuckoo/modules/reporting/mongodb.py", line 253, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
InvalidDocument: Cannot encode object: set([])
2017-03-04 23:49:45,249 [lib.cuckoo.core.guest] DEBUG: win7: analysis not completed yet (status=2)
2017-03-04 23:49:46,281 [lib.cuckoo.core.guest] DEBUG: win7: analysis not completed yet (status=2)
2017-03-04 23:49:46,741 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "ReportHTML"
2017-03-04 23:49:46,742 [lib.cuckoo.core.scheduler] INFO: Task #59: reports generation completed (path=/opt/cuckoo/storage/analyses/59)

Error on UI

ERROR :-(
The specified analysis does not exist

**Comment by jbremer** [comment]
Which version of Cuckoo are you running? I believe this is an older bug.

**Comment by SparkyNZL** [comment]
its the packaged version so might not have made it to the comit as yet ?

**Comment by SparkyNZL** [comment]
ill grab the latest and see if it still pops up

**Comment by jbremer** [comment]
@SparkyNZL this is not package ;)

**Comment by SparkyNZL** [comment]
bingo, sweet, ill close it, and it will arrive in the next commit :)

**Comment by jbremer** [comment]
@SparkyNZL I think you're confused with github issues :p

**Comment by SparkyNZL** [comment]
LOL opps

**Comment by SparkyNZL** [comment]
Yeah too much "V" today

**Comment by andr6** [comment]
What does it mean ? Something that is fixed but not committed ? 

I am using latest commit from trunk.

**Comment by jbremer** [comment]
@andr6 it's unrelated to this issue. Oke, interesting. Could you please export the analysis and upload it somewhere / send it my way so that I can take a look at your findings? :)

**Comment by andr6** [comment]
@jbremer what do you need?

**Comment by andr6** [comment]
@jbremer  Analyses folder compressed. 

https://expirebox.com/delete/82020fadf0c3612f4b6f9bb98f8cf7b3.html

**Comment by jbremer** [comment]
@andr6 I'm not sure which version of Cuckoo you're running, but I can import & process the analysis just fine. Do you have any more information on your environment & setup perhaps?

**Comment by andr6** [comment]
It's the latest from trunk.  Debian 8 with VBox 5.0.14, Mongodb 3.2.11.

**Comment by jbremer** [comment]
I'm honestly not sure what's going wrong. Could you please do a `pprint.pprint(report)` in `mongodb.py` or `pprint.pprint(results)` in `jsondump.py`, of course put in an `import pprint` as well and do it before the exception is thrown :-)
That way we can identify where the `set()` is located.

**Comment by jbremer** [comment]
Any update @andr6 ?

**Comment by andr6** [comment]
Hi @jbremer. Will do it and let you know .

**Comment by andr6** [comment]
@jbremer  Thanks for the help.

**Comment by jbremer** [comment]
@andr6 Thanks for reporting ;-) Fix is ready and will be pushed to the `package` branch soon.
For the `master` branch (`2.0-rc2` release etc) you can fix it yourself by not enabling `droidmon` (as discussed) and/or modifying line 361 of `modules/processing/droidmon.py` from `return self.droidmon` to `return {}`.
Closing this issue as resolved.
