### ISSUE TITLE
Cuckoo package update error

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1328]
Hi just did a --upgrade to the latest commit, and i get the following error

Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.0', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 16, in <module>
    from cuckoo.apps import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/__init__.py", line 11, in <module>
    from .distributed import cuckoo_distributed, cuckoo_distributed_instance
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/distributed.py", line 7, in <module>
    from cuckoo.distributed.app import create_app
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/distributed/__init__.py", line 6, in <module>
    from . import api, app, db, exception, instance, misc
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/distributed/app.py", line 9, in <module>
    from cuckoo.distributed.db import db, AlembicVersion
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/distributed/db.py", line 8, in <module>
    from flask.ext.sqlalchemy import SQLAlchemy
  File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.sqlalchemy

**Comment by jbremer** [comment]
Yes, please re-run `python setup.py install` or `python setup.py develop` (whichever you did earlier)! :) Closing as that will resolve your issue.

**Comment by SparkyNZL** [comment]
ok ill give that  a shot i ususal build up a package with ./setup.py sdist
and the pip install <package name> --upgrade

**Comment by jbremer** [comment]
That should work as well :) If you do that and get weird results at some point, don't forget to `pip uninstall cuckoo` a couple of times (don't ask).

**Comment by SparkyNZL** [comment]
Sweet, Ill do the uninstall first a few times and then try and reinstall :)

**Comment by SparkyNZL** [comment]
ok git it, the setup.py has changed, ive been using the same old one for
month as i had to make a few edits to it to get it to work. :)

Cheers
