### ISSUE TITLE
Cuckoo Package - Broken Moloch :(

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1329]
Hi guys, Ive installed the latest package release, nice work on the WGUI btw ;)

However a couple of things no longer work. when clicking on an IP or URL in the report, it give a HTML 500 error and the trace is as follows (no longer redirects to moloch)

Also a qemu error has popped up, and i dont use qemu , in the cuckoo.conf my machinery is set to  virtualbox.

The other item which is broken but was never official is the viper stuff, since it does a search and then uses a url in the following formate http://malwarelab/submit/status/13013, 13013 is the correct report, its just the "status" function is no longer there ? so you get a 404 error.'

Below is the IP trace from the webserver which should be redirecting to moloch.

---------------------------------------------------------------------------

2017-03-10 22:09:52,039 [cuckoo.common.config] ERROR: Type of config parameter qemu:vm1:kernel_path not found! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.
2017-03-10 22:09:52,039 [cuckoo.common.config] ERROR: Type of config parameter qemu:vm2:kernel_path not found! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.
2017-03-10 22:09:54,241 [web.errors] WARNING: Error providing feedback to the backend: Invalid response from Cuckoo feedback server: 404 Client Error: Not Found
2017-03-10 22:09:54,242 [django.request] ERROR: Internal Server Error: /analysis/moloch/157.56.144.215//////
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "./analysis/views.py", line 258, in moloch
    if not config("reporting:moloch:enabled"):
NameError: global name 'config' is not defined
[10/Mar/2017 22:09:54] "GET /analysis/moloch/157.56.144.215////// HTTP/1.1" 500 11909

---------------------------------------------------------------------------------------

**Comment by jbremer** [comment]
Please also post the `qemu`-related error/warning!

**Comment by SparkyNZL** [comment]
its amoungst the trace

**Comment by jbremer** [comment]
Gotcha

**Comment by SparkyNZL** [comment]
ok, im happy ive got that yara thing sorted, it was holding everything up
with the reprocessing after the database updates. Im going to hit the sac
its nearly 11pm here and its been a long week.

**Comment by jbremer** [comment]
You can ignore the `qemu` stuff. I'm still doing some configuration changes, so once you make a new CWD with the official release those issues won't be present (now you basically have outdated configuration). I'm having some unittests run atm, but the moloch thing is resolved as well.

**Comment by jbremer** [comment]
@SparkyNZL I think it should work now, please retest at your earliest convenience :)

**Comment by SparkyNZL** [comment]
Yes that is all fixed thanks :)
