### ISSUE TITLE
Problems while starting cuckoo..

### ISSUE THREAD

**Issue by Gimaa** [cuckoosandbox/cuckoo#1330]
Hi,
Please could you help me for the following issue that I'm having,
I have install all that was necessary, but when I want to run cuckoo the following error apperas, so how can I solve thiss issue,

gimium@gimium:~/Downloads/cuckoo$ ./cuckoo.py 
Traceback (most recent call last):
  File "./cuckoo.py", line 18, in <module>
    from lib.cuckoo.common.utils import exception_message
  File "/home/gimium/Downloads/cuckoo/lib/cuckoo/common/utils.py", line 32, in <module>
    import bs4
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by jbremer** [comment]
Seems like you've installed incompatible versions of `beautifulsoup4` and `lxml`. Please install versions as per `requirements.txt`.

**Comment by Gimaa** [comment]
Yes, I'm installing these requirements but again the same error, 
[requirements_installed.txt](https://github.com/cuckoosandbox/cuckoo/files/833624/requirements_installed.txt)
Here I attached the file of the install requirements process.

**Comment by Gimaa** [comment]
It's very wierd, since all the requirements are installed:
it shows that:
Requirement already satisfied: 
Including beautifulsoup4 and lxml

**Comment by jbremer** [comment]
Can you `pip uninstall html5lib beautifulsoup4` & `pip install beautifulsoup==4.4.1`?

**Comment by Gimaa** [comment]
Yes it is working now, thanks a lot :)
But could you help me with this issue as well,
while im trying to run webapp to see the results..

gimium@gimium:~/Downloads/cuckoo/web$ ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/gimium/Downloads/cuckoo/web/web/settings.py", line 20, in <module>
    raise Exception("Mongo reporting module is not enabled in cuckoo, aborting!")
Exception: Mongo reporting module is not enabled in cuckoo, aborting!

**Comment by jbremer** [comment]
Please read what the error message says ;-) Closing this issue as resolved.

**Comment by Gimaa** [comment]
Yeepp I solved the issuee,
Many many thanks.
