### ISSUE TITLE
Web interface pb

### ISSUE THREAD

**Issue by Drx51** [cuckoosandbox/cuckoo#1331]
Hy,

I've already Ok with cuckoo, but when I run this command for having the web interface, i've got a pb. I notice I made all pip install -r requirements.txt

root@mlwr:/home/cuckoo/cuckoo/web# python manage.py 
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cuckoo/cuckoo/web/web/settings.py", line 20, in <module>
    raise Exception("Mongo reporting module is not enabled in cuckoo, aborting!")
Exception: Mongo reporting module is not enabled in cuckoo, aborting!

Thanks for you help

**Comment by doomedraven** [comment]
__read the documentation__ 
`Exception: Mongo reporting module is not enabled in cuckoo, aborting!`

**Comment by jbremer** [comment]
Literally just answered the same question 10 minutes ago, #1330 :P

**Comment by jbremer** [comment]
Fwiw, in the upcoming release this message will be a little bit more clear; https://github.com/cuckoosandbox/cuckoo/blob/package/cuckoo/web/web/settings.py#L21-L26
