### ISSUE TITLE
WARNING: As you've configured Cuckoo to execute parallel analyses, we recommend you to switch to a MySQL ora PostgreSQL database as SQLite might cause some issues.

### ISSUE THREAD

**Issue by 1623664** [cuckoosandbox/cuckoo#1333]
ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/home/cuckoo/cuckoo/modules/reporting/mongodb.py", line 89, in run
    if "cuckoo_schema" in self.db.collection_names():
  File "/usr/lib/python2.7/dist-packages/pymongo/database.py", line 517, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 748, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 712, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/lib/python2.7/dist-packages/pymongo/topology.py", line 141, in select_server
    address))
  File "/usr/lib/python2.7/dist-packages/pymongo/topology.py", line 117, in select_servers
    self._error_message(selector))

**Comment by SparkyNZL** [comment]
Hi , @1623664 , posting a trace with nothing more is not very helpful, please enable us to help you by wrapping an explanation around your request.

Cheers/

**Comment by 1623664** [comment]
The error occurred after reboot, all files are tested but never displayed. To output these errors

**Comment by 1623664** [comment]
./utils/community.py --signatures --force
did not help

**Comment by 1623664** [comment]
it is also not possible to access old reports

**Comment by doomedraven** [comment]
is mongo started? which cuckoo version?

**Comment by 1623664** [comment]
last update

**Comment by 1623664** [comment]
service mongodb status
● mongodb.service - An object/document-oriented database
   Loaded: loaded (/lib/systemd/system/mongodb.service; enabled; vendor preset: 
   Active: failed (Result: exit-code) since Пн 2017-03-13 12:16:33 MSK; 1min 9s 
     Docs: man:mongod(1)
  Process: 833 ExecStart=/usr/bin/mongod --config /etc/mongodb.conf (code=exited
 Main PID: 833 (code=exited, status=14)

**Comment by doomedraven** [comment]
so you just have problems with mongo, that is not the cuckoo error, google and mongo logs maybe can help you

**Comment by 1623664** [comment]
thank you
