### ISSUE TITLE
Cuckoo Package : ES error

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1359]
2017-03-25 14:26:02,863 [cuckoo.core.startup] DEBUG: Imported modules...
2017-03-25 14:26:02,867 [elasticsearch] WARNING: HEAD /_template/cuckoo_template [status:404 request:0.002s]
2017-03-25 14:26:02,943 [pip.utils] DEBUG: lzma module is not available
2017-03-25 14:26:02,945 [pip.vcs] DEBUG: Registered VCS backend: git
2017-03-25 14:26:03,097 [pip.vcs] DEBUG: Registered VCS backend: hg
2017-03-25 14:26:03,200 [pip.vcs] DEBUG: Registered VCS backend: svn
2017-03-25 14:26:03,201 [pip.vcs] DEBUG: Registered VCS backend: bzr
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.0
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:0.8.8 androguard:3.0 asn1crypto:0.22.0 beautifulsoup4:4.4.1 cffi:1.10.0 chardet:2.3.0 click:6.6 colorama:0.3.7 cryptography:1.8.1 cuckoo:2.0.0 distribute:0.7.3 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 elasticsearch:2.2.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.10.1 functools32:3.2.3.post2 httpreplay:0.2 idna:2.5 ipaddress:1.0.18 itsdangerous:0.24 jinja2:2.8 jsbeautifier:1.6.2 jsonschema:2.6.0 m2crypto:0.24.0 mako:1.0.6 markupsafe:1.0 ndg-httpsclient:0.4.2 olefile:0.43 oletools:0.42 packaging:16.8 peepdf:0.3.4 pefile2:1.2.11 pillow:3.2.0 psycopg2:2.7.1 pyasn1:0.2.3 pycparser:2.17 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:16.2.0 pyparsing:2.2.0 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 requests:2.7.0 scapy:2.3.2 sflock:0.2.6 six:1.10.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0 urllib3:1.20 wakeonlan:0.2.2 werkzeug:0.12.1

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/main.py", line 184, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/main.py", line 121, in cuckoo_init
    init_modules()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/core/startup.py", line 190, in init_modules
    module.init_once()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/reporting/elasticsearch.py", line 51, in init_once
    if not cls.apply_template():
TypeError: unbound method apply_template() must be called with ElasticSearch instance as first argument (got nothing instead)

**Comment by jbremer** [comment]
If you could manually merge the WIP merge of #1196 and let me know if that improves ES support, that'd be great! Do note that you'll also have to generate a new CWD.
```

**Comment by SparkyNZL** [comment]
After updating ES seems to be sort of working but are getting the following error a bit.

----------------------------------------------------------------------------

2017-04-08 13:37:43,586 [elasticsearch] WARNING: POST http://192.168.20.60:9200/cuckoo-2017-04/cuckoo [status:400 request:1.619s]
2017-04-08 13:37:43,595 [cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #11: TransportError(400, u'illegal_argument_exception', u'[MalwareLab][192.168.20.60:9300][indices:data/write/index[p]]')

---------------------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment]
this is popping up a bit also

-----------------------------------------------------------------------------
2017-04-08 16:17:14,453 [cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #387: (u'3 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'call', u'_id': u'AVtLx8IvtJgC-aI1DSJs', u'error': {u'caused_by': {u'reason': u'bytes can be at most 32766 in length; got 68488', u'type': u'max_bytes_length_exceeded_exception'}, u'reason': u'Document contains at least one immense term in field="arguments.application_name" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[-22, -84, -78, -29, -120, -95, -30, -122, -85, -22, -84, -78, -30, -72, -95, -31, -66, -85, -22, -80, -81, -29, -128, -96, -30, -122, -83, -22, -80, -81]...\', original message: bytes can be at most 32766 in length; got 68488', u'type': u'illegal_argument_exception'}, u'_index': u'cuckoo-2017-04'}}, {u'index': {u'status': 400, u'_type': u'call', u'_id': u'AVtLx8IvtJgC-aI1DSJt', u'error': {u'caused_by': {u'reason': u'bytes can be at most 32766 in length; got 68488', u'type': u'max_bytes_length_exceeded_exception'}, u'reason': u'Document contains at least one immense term in field="arguments.application_name" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[-22, -84, -78, -29, -120, -95, -30, -122, -85, -22, -84, -78, -30, -72, -95, -31, -66, -85, -22, -80, -81, -29, -128, -96, -30, -122, -83, -22, -80, -81]...\', original message: bytes can be at most 32766 in length; got 68488', u'type': u'illegal_argument_exception'}, u'_index': u'cuckoo-2017-04'}}, {u'index': {u'status': 400, u'_type': u'call', u'_id': u'AVtLx8IvtJgC-aI1DSJu', u'error': {u'caused_by': {u'reason': u'bytes can be at most 32766 in length; got 68488', u'type': u'max_bytes_length_exceeded_exception'}, u'reason': u'Document contains at least one immense term in field="arguments.application_name" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[-22, -84, -78, -29, -120, -95, -30, -122, -85, -22, -84, -78, -30, -72, -95, -31, -66, -85, -22, -80, -81, -29, -128, -96, -30, -122, -83, -22, -80, -81]...\', original message: bytes can be at most 32766 in length; got 68488', u'type': u'illegal_argument_exception'}, u'_index': u'cuckoo-2017-04'}}])
------------------------------------------------------------------------------------

**Comment by jbremer** [comment]
Hm, looks like ES is imposing length limits now as well. If you have any analyses that you can share to ease our debugging, that'd be great.

**Comment by SparkyNZL** [comment]
Sure can, ill email them through tomorrow J

**Comment by SparkyNZL** [comment]
sent through to ya mate.

CHeers

**Comment by swackhamer** [comment]
I think you need to drop your previous version of the ES_template and have cuckoo automatically upload the new version which drops strings longer then 32766.

You can do this with a simple curl command if you have the ES server bound locally to 9200.

curl -XDELETE http://localhost:9200/_template/cuckoo_template

ES Docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html#delete

https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data/elasticsearch/template.json#L20

**Comment by SparkyNZL** [comment]
sweet donw, ill see how it goes, something is also cause ES to stop for
some reason, Im slowly tracking it down, but the service exits , there is
very little in var/log/elasticsearch so ill have to see if i can hunt it
down another way

Thanks for the tip :)

**Comment by jbremer** [comment]
Cool @swackhamer! Let us know if that helps @SparkyNZL :-)
Perhaps we should have Cuckoo do a check at startup to ensure the template has been properly applied?

**Comment by swackhamer** [comment]
Yeah some sort of init section would be good.  I don't know where best that would go though maybe here? 
: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/main.py#L123

Right now as is it checks for the cuckoo_template as specified by the index name in the template, and *every* single time the ES reporter runs it has to do the check to see if it already exists.  If we can call this once on startup, check to see what version of ES it is 2 or 5 and then if it is 5 apply the template *one* time that would be best.  It would be nice if there was some way we could *cache* that result so even on cuckoo restarts it doesn't have to check the ES connection, or if we could just poll it every 15 mins or something which is what logstash kinda does for you when it manages the index template.

Template name:
`cls.template_name = "%s_template" % elastic.index`

The template name could also potentially change on the ES side, or someone could have uploaded their own index template that when making the cuckoo indexes get implied instead of ours.  I am not sure how to address that specific use case other then potentially enumerating through all of the index templates installed (which could be a lot) and look for any that matched the current configured Cuckoo index.  If there was someway to do this checking on startup first run and then never again including on restarts of Cuckoo that would be best.

The problem with ES becoming unresponsive may be due to indexing very large Cuckoo reports such as ransomware runs.  Those blow up the size of Cuckoo report that needs to be indexed, even the summarized versions can grow large.

This is something that we have briefly talk about before @jbremer but we could split out each of these into a new ES document all with having the same base document.  This could also handle timeout errors on index that I have seen before when attempting to index a gigantic document.  It would essentially index just like "calls" where there can be millions of small documents per report.  Elasticsearch and especially Kibana will be able to handle these smaller documents much better then very large documents.

https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/reporting/elasticsearch.py#L190

Base document on all cuckoo documents:
 ```header = {
      "task_id": self.task["id"],
      "report_time": self.report_time,
      "report_id": self.task["id"]
}```


Things like "procmemory" should be split out to their own document as well and "signatures".  For every signature and every procmemory entry instead of being "nested" objects they should be seperate objects (that is kinda what nested does in the backend but with even more slow downs).  We could also use children / parents in ES, but I have found that to be more of a hassle then just doing something like adding a base set of fields (base document) to each document in a "collection" to be easier then having to mess around with ES's cumbersome child / parent types which don't work in Kibana either.
  https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data/elasticsearch/template.json#L45

I have allocated some time to really addressing these ES 5.x problems this week and next weekend, and would like to get started on this work if this sounds good to you, the problem is it is going to start to enforce some rigidity in the Cuckoo schema that won't be able to be changed without breaking the ES component.

**Comment by SparkyNZL** [comment]
I can verify this has stopped causing ES from crashing, and most of the errors have now 
"left the building" apart from this one

2017-04-10 00:24:07,176 [elasticsearch] WARNING: POST http://192.168.20.60:9200/cuckoo-2017-04/cuckoo [status:400 request:0.158s]
2017-04-10 00:24:07,178 [cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #5240: TransportError(400, u'illegal_argument_exception', u'[MalwareLab][192.168.20.60:9300][indices:data/write/index[p]]')

**Comment by swackhamer** [comment]
Could you post the error that you see in /var/log/elasticsearch/*.log for that time period?

**Comment by SparkyNZL** [comment]
Hi, Sorry about the delay, this week as been CRAZY !

anyhow, I seem to have sorted out the elasticsearch crashing issue, i had to increas my ES jvm stack to 14g from 8g , this seems to be keeping it up and running

Here is the information from the <clustername>.log file

-----------------------------------------------------------------------------------------

[2017-04-15T10:37:04,756][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [MalwareLab] failed to put mappings on indices [[[cuckoo-2017-04/74KGEjxxRpCj7RptU1wjRQ]]], type [cuckoo]
java.lang.IllegalArgumentException: Limit of total fields [1000] in index [cuckoo-2017-04] has been exceeded
	at org.elasticsearch.index.mapper.MapperService.checkTotalFieldsLimit(MapperService.java:576) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:409) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:327) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:260) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:311) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:674) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:653) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:612) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:1112) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:527) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201) [elasticsearch-5.2.2.jar:5.2.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

-----------------------------------------------------------------------------------------------------------------------------

**Comment by swackhamer** [comment]
Elasticsearch can be a absolute hog when it comes to consuming these very large Cuckoo documents.  I am going to attempt to break them up into smaller documents this weekend to then submit via the bulk API to ES.  It should be a little bit easier on ES and make Search and Visualization in Kibana actually usable without removing large amounts of fields manually in the index pattern configuration area.

There is a couple of other things you can do to get more "visibility" into your elasticsearch cluster.  I would recommend signing up for a free license with elastic.co for a basic license of x-pack to install monitoring: https://www.elastic.co/subscriptions .  Make sure to disable xpack.shield in:

```/etc/elasticsearch/elasticsearch.yml 
xpack.security.enabled: false```

I would also recommend installing cerebo: https://github.com/lmenezes/cerebro .  This is kopf for Elasticsearch 5.x but now in a standalone play application.

**Comment by SparkyNZL** [comment]
Yeah , I found 2.2.4 to be less of a hog, like majorly less. Any how mine
is a load issue now, at 26g of ram and 4 CPUs later all is ok apart from
load,

Cerebri is good I agree. I use to used head in the old version of ES

How would you deal with the load issue ? It's sitting as high a 7 , I'm
using a single deployment one machine is doing it all, I'm pushing about 5k
samples a day to it, I'm hoping not to have to create a full blown cluster
, mind you I do have snort, cuckoo, moloch all pushing data to it

Cheers

**Comment by swackhamer** [comment]
Do you have calls being indexed into ES?

Would there be a way you could send me either your entire ~/.cuckoo/storage folder or as many of your analysis folders in there as you could give me for testing?

Are you in the irc channel by any chance?  #cuckoosandbox on irc.freenode.net .  I am working on this today, but would like to get a ton of sample reports to test with.

By default it is False.
https://github.com/cuckoosandbox/cuckoo/blob/2371dba96216e8622e9c527796e196cc78d792b1/cuckoo/common/config.py#L734

**Comment by SparkyNZL** [comment]
Sure can, give me a few mins and I'll jump on IRC and we can discuss
further regarding the numbers u want

Cheers

**Comment by SparkyNZL** [comment]
this ES error has started now :(

2017-04-23 13:19:21,464 [elasticsearch] WARNING: POST http://192.168.20.60:9200/cuckoo-2017-04/cuckoo [status:400 request:0.004s]
2017-04-23 13:19:21,465 [cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #18210: TransportError(400, u'mapper_parsing_exception', u'failed to parse')

**Comment by swackhamer** [comment]
Can I get the /var/log/elasticsearch/*.log for that mapping parsing exception; specifically which field.

Please also post your most recent mapping as well with:

curl /cuckoo-2017-04/_mapping/

**Comment by SparkyNZL** [comment]
here is the _mappigs

**Comment by SparkyNZL** [comment]
This is still popping up :( 
----------------------------------------------------------------------------------------------------------------------


2017-04-30 13:18:13,373 [elasticsearch] WARNING: POST http://192.168.20.70:9200/cuckoo-2017-04/cuckoo [status:400 request:0.024s]
2017-04-30 13:18:13,374 [cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #304: TransportError(400, u'mapper_parsing_exception', u'failed to parse')


-----------------------------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment]
This is a new one...

-------------------------------------------------------------------------------------

2017-04-30 13:21:51,972 [elasticsearch] WARNING: POST http://192.168.20.70:9200/cuckoo-2017-04/cuckoo [status:400 request:1.621s]
2017-04-30 13:21:51,977 [cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #312: TransportError(400, u'illegal_argument_exception', u'Limit of total fields [1000] in index [cuckoo-2017-04] has been exceeded')

-------------------------------------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment]
I have found a solution for this, ES 5 limits the total index mappings to 1000, but you can extend these, in fact you will need to if you run up any malware which changes a lot of files such as ransomware.

Anyhow below is the curl command which you can issue to your ES node.

--------------------------------------------------------------------------------------
 
curl -XPUT '127.0.0.19200/cuckoo*/_settings' -d '
{
    "index.mapping.total_fields.limit": 3000
}'


--------------------------------------------------------------------------------------

**Comment by jbremer** [comment]
If we need to automatically update these limits, then don't close the issue yet :-) We'll take it into account some time, heh.

**Comment by SparkyNZL** [comment]
Oh oops yes good point , I just like closing shit :) hahaha

**Comment by geudrik** [comment]
+1 for updating core code to account for/play nicely with es when ++ dynamic fields. @SparkyNZL was just about to post your same fix here!

**Comment by rholloway** [comment]
+1 for adjusting format to not use dynamic keys as it's not good for ES to have arbitrarily large mappings. I would adjust format rather than simply update limit if possible. 

For modified file lists (Ransomware) or hash lists of anything (just very dynamic) using the hash or filename as a key isn't great. It's also harder to build searches since you don't know the key names in advance.

**Comment by SparkyNZL** [comment]
Glad it helped :)
