### ISSUE TITLE
Cuckoo Package : WEB UI , Recent 

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1363]
When click ing on Recent in the new web interface i get the following error, and no "recent files" are listed

------------------------------------------------------

2017-03-27 18:43:43,061 [django.request] ERROR: Internal Server Error: /analysis/api/tasks/recent/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/web/bin/utils.py", line 47, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/web/controllers/analysis/api.py", line 325, in tasks_recent
    f = row["target"]["file"]
KeyError: 'target'
[27/Mar/2017 18:43:43] "POST /analysis/api/tasks/recent/ HTTP/1.1" 500 11991

---------------------------------------------------------------------------------------------

**Comment by jbremer** [comment]
This should indeed be fixed, I'll do so, but the real workaround is not disabling `targetinfo`.

**Comment by jbremer** [comment]
Looks like this has been resolved in our 2.0.0 release, closing as such. Please reopen if that's not the case.
