### ISSUE TITLE
Cuckoo Package : Failed to run the processing module "Dropped"

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1373]
I have noticed this popping up from time to time, Ill check to see if this is related to the Malware or if it is just random, but this is the error.

---------------------------------------------------------------------

2017-04-01 11:44:03,731 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" on analysis at "/home/adroot/.cuckoo/storage/analyses/5921"
2017-04-01 11:44:05,657 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Dropped" for task #5921:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/core/plugins.py", line 235, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/processing/dropped.py", line 34, in run
    file_info = File(file_path=file_path).get_all()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/common/objects.py", line 394, in get_all
    infos["yara"] = self.get_yara()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/common/objects.py", line 324, in get_yara
    for match in File.yara_rules[category].match(self.file_path):
Error: internal error: 30

------------------------------------------------------------------------------------------------------

**Comment by jbremer** [comment]
I believe this is either a custom yara compile (rather than `yara-python==3.5.0`) or invalid Yara rules. Do you have any more information on this?

**Comment by jbremer** [comment]
@SparkyNZL Is this a duplicateof of your other yara-related issue?

**Comment by SparkyNZL** [comment]
Yeah it is, close this and I'll keep the other open

**Comment by jbremer** [comment]
At your command ;-)
