### ISSUE TITLE
Cuckoo Package: INetSim REMnux remote_dns_forward() error

### ISSUE THREAD

**Issue by Darjuw** [cuckoosandbox/cuckoo#1380]
I am trying to get Cuckoo to work with REMnux InetSim on the package version. But for some reason, I'm constantly getting remote_dns_forward() error.

My setup
```
**Host** 172.16.76.1 (Ubuntu 14.04)
**Malware Sandbox VMware** 172.16.76.90 (vmnet1)
**REMnux InetSim VMware** 172.16.76.128 (Have tried NAT, vmnet1, host-only)
```

My configuration
```
[inetsim]
# Route a VM to your local InetSim setup (could in theory also be any other
# type of web service / etc).
enabled = yes
server = 172.16.76.128
```

/etc/inetsim/inetsim.conf (on 172.16.76.128)
```
start service for everything
default service bind and dns address (I have tried setting it to 172.16.76.128 and 172.16.76.1 too but getting same error)
```

/etc/inetsim/inetsim.conf
`default configuration (I run INetSim using sudo inetsim)`

**Errors**

admin2@admin2-7010:~$ sudo cuckoo rooter -g admin2
```
2017-04-07 11:02:48,205 [cuckoo.apps.rooter] ERROR: Error executing command: remote_dns_forward() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/apps/rooter.py", line 388, in cuckoo_rooter
    output = handlers[command](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/apps/rooter.py", line 202, in inetsim_enable
    remote_dns_forward(ipaddr, inetsim_ip, "-A")
TypeError: remote_dns_forward() takes exactly 4 arguments (3 given)
```

admin2@admin2-7010:~$ sudo cuckoo 
```
Cuckoo Sandbox 2.0.0
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!
2017-04-07 11:00:38,947 [cuckoo.core.startup] INFO: Updated running task ID 59 status to failed_analysis
2017-04-07 11:00:39,080 [cuckoo.core.scheduler] INFO: Using "vmware" as machine manager
2017-04-07 11:00:39,822 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-07 11:00:39,850 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-04-07 11:00:56,714 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "npp.7.3.2.Installer.exe" (task #60, options "procmemdump=yes,route=inetsim")
2017-04-07 11:00:57,008 [cuckoo.core.scheduler] INFO: Task #60: acquired machine cuckoo1 (label=/home/admin2/Desktop/C/Win7/ActivatedWin7.vmx)
2017-04-07 11:00:57,057 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 13251 (interface=vmnet1, host=172.16.76.90, pcap=/home/admin2/.cuckoo/storage/analyses/60/dump.pcap)
2017-04-07 11:01:03,452 [cuckoo.core.rooter] WARNING: Rooter returned error: remote_dns_forward() takes exactly 4 arguments (3 given)
2017-04-07 11:01:04,027 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=172.16.76.90)
2017-04-07 11:01:04,039 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo1, ip=172.16.76.90)
```

The community shown on Cuckoo documentation (https://community.cuckoosandbox.org/) is down, so I'm posting here. Please assist me in solving this, I have been spending days to no avail. 

PS: Remnux InetSim works fine with my malware sandbox without Cuckoo implementation.

**Comment by doomedraven** [comment]
ok i see the bug

`remote_dns_forward(action, vm_ip, dns_ip, dns_port):`

but called in this way
`remote_dns_forward(ipaddr, inetsim_ip, "-A")`
`remote_dns_forward(ipaddr, inetsim_ip, "-D")`
`remote_dns_forward(action, vm_ip, resultserver_ip, dns_port)` <- correct

@jbremer first two should be `local_dns_forward ` no?

**Comment by doomedraven** [comment]
@Darjuw try to rename

```
remote_dns_forward(ipaddr, inetsim_ip, "-A")
remote_dns_forward(ipaddr, inetsim_ip, "-D")

to
local_dns_forward(ipaddr, inetsim_ip, "-A")
local_dns_forward(ipaddr, inetsim_ip, "-D")
```

**Comment by doomedraven** [comment]
ok i got a look on it, there an issue, @jbremer we should add dns port in inetsim section and pass it to router if we don't want to hardcode it in rooter and be able use fakedns or any other related thing

also in def is dns_port but in calling is ip

definition:
`local_dns_forward(ipaddr, dns_port, action)`

calling
` local_dns_forward(ipaddr, inetsim_ip, "-A")`

**Comment by doomedraven** [comment]
@Darjuw as quick fix before @jbremer will fix it in brach i would suggest you do the next

replace
```
remote_dns_forward(ipaddr, inetsim_ip, "-A")
remote_dns_forward(ipaddr, inetsim_ip, "-D")
```

to 

```
local_dns_forward(ipaddr, 53, "-A")
local_dns_forward(ipaddr, 53, "-D")
```
not sure if port should be int or str

but that should make magic

**Comment by jbremer** [comment]
InetSim is unfortunately not yet supported (as per our release blogpost). Hopefully we'll figure out how to fix it properly for the next release. If you find a working solution, please do let us know!

**Comment by doomedraven** [comment]
ok try patch
https://github.com/cuckoosandbox/cuckoo/pull/1435

but that works for me if i have inetsim installed in host, but maybe that should work in remote in vm, as the rule is the same which we used in past to redirrect to inetsim vm(aka remnux)

**Comment by doomedraven** [comment]
ok there upcoming patch which works with remove vm

**Comment by doomedraven** [comment]
done, feel free to test and provide feedback, works just fine here with inetsim vm
https://github.com/cuckoosandbox/cuckoo/pull/1435

**Comment by jbremer** [comment]
The InetSim PR has been merged, please test it and provide us with feedback. Please leave your comments in #1435. If something else has been discussed in this thread that I missed, but that's important in one way or another, please reopen the issue with an additional comment or copy the comment / issue / whatever to #1435.
I'll be closing this issue now. In #1435 I'll be announcing when a new alpha or stable release is out in which you may find the InetSim working once again. Thanks again for the feedback & sorry once more for the delay on our side.
Ping @Darjuw.
