### ISSUE TITLE
Cuckoo Package : Permissions issue in WGUI

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1383]
Hi, Im getting as permissions error on the landing page . the following is the trace of the error, it seems to want to make a directory, but it wont be able to as its not running as root.

--------------------------------------------------------------------

[08/Apr/2017 12:40:15] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 743
[08/Apr/2017 12:40:15] "GET /cuckoo/api/status HTTP/1.1" 301 0
2017-04-08 12:40:15,419 [django.request] ERROR: Internal Server Error: /cuckoo/api/status/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/web/bin/utils.py", line 55, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/web/controllers/cuckoo/api.py", line 28, in status
    temp_file = Files.temp_put("", "status")
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/common/files.py", line 109, in temp_put
    os.mkdir(target_path)
OSError: [Errno 13] Permission denied: 'status'
[08/Apr/2017 12:40:15] "GET /cuckoo/api/status/ HTTP/1.1" 500 17222

----------------------------------------------------------------------------------

**Comment by jbremer** [comment]
And you're able to submit analyses, because that's using the same mechanism?

**Comment by SparkyNZL** [comment]
yeah the file submit works fine

**Comment by lowson** [comment]
Had the same issue for a non virtual env deployment.

The webportal is trying to create directories here:
/usr/local/lib/python2.7/dist-packages/cuckoo/web/

A temp fix would be changing the permissions to the cuckoo user and the issue will go away:
sudo chown -R cuckoo:cuckoo /usr/local/lib/python2.7/dist-packages/cuckoo/web

Code should be updated to use the tmp directory from the conf file.

Full error logs:
Internal Server Error: /cuckoo/api/status/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/bin/utils.py", line 55, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/cuckoo/api.py", line 28, in status
    temp_file = Files.temp_put("", "status")
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/files.py", line 112, in temp_put
    os.mkdir(target_path)
OSError: [Errno 13] Permission denied: 'status'
[django.request] ERROR: Internal Server Error: /cuckoo/api/status/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/bin/utils.py", line 55, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/cuckoo/api.py", line 28, in status
    temp_file = Files.temp_put("", "status")
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/files.py", line 112, in temp_put
    os.mkdir(target_path)
OSError: [Errno 13] Permission denied: 'status'

**Comment by doomedraven** [comment]
already was reported, duplicated, check issues before posting ;)

**Comment by SparkyNZL** [comment]
oh bugga, i did have a look but didn't see it reported. Its nice to see I'm not the only one which gets it, saves me from redeploying the entire system to check it wasn't me and my fat fingers ! :)

**Comment by jbremer** [comment]
@doomedraven more bug reports on the same issue is still nice - allows me to see topics that should have a higher priority ;-)

**Comment by doomedraven** [comment]
i know but users should learn to check issues before open duplicates anyway :P
i'm getting the same in my home cuckoo btw, just installed to see if make sense update production or not :D

**Comment by jbremer** [comment]
I've put up version `2.0.1a1`, an alpha version including a fix for this issue. Please upgrade (i.e., `pip install cuckoo==2.0.1a1`). Closing this issue as fixed.
