### ISSUE TITLE
cuckoo version 2.0.0 is not work...

### ISSUE THREAD

**Issue by pinksawtooth** [cuckoosandbox/cuckoo#1392]
I tried cuckoo version 2.0.0.
I installed it referring to this document.
https://cuckoo.sh/docs/installation/host/installation.html#install-cuckoo

But it did not work.
What is wrong?

```
2017-04-11 22:56:11,718 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "test.exe" (task #5, options "procmemdump=yes,route=none")
2017-04-11 22:56:12,006 [cuckoo.core.scheduler] INFO: Task #5: acquired machine cuckoo1 (label=7)
2017-04-11 22:56:12,006 [cuckoo.core.plugins] ERROR: Unable to start auxiliary module sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 120, in start
    current.start()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 28, in start
    if "nictrace" in self.machine.options:
TypeError: argument of type 'NoneType' is not iterable
2017-04-11 22:56:32,960 [cuckoo.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label 7 to path /home/xenial/.cuckoo/storage/analyses/5/memory.dmp
2017-04-11 22:56:35,590 [cuckoo.core.rooter] CRITICAL: Unable to passthrough root command (drop_disable) as the rooter unix socket doesn't exist.
2017-04-11 22:56:35,820 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 478, in launch_analysis
    machinery.start(self.machine.label, self.task)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/machinery/virtualbox.py", line 150, in start
    if "nictrace" in machine.options:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by jbremer** [comment]
Hi, thanks for the bug report. Could you post your `virtualbox.conf`?

**Comment by doomedraven** [comment]
@pinksawtooth  @jbremer is the same as before, comment out `options` in virtuboxbox.conf and it will work

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/issues/1381

**Comment by pinksawtooth** [comment]
Thank you @doomedraven.
One error was fixed.
But this does not change "ERROR: Unable to start auxiliary module sniffer" .

2017-04-11 23:29:40,167 [cuckoo.core.startup] INFO: Updated running task ID 8 status to failed_analysis
2017-04-11 23:29:40,227 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-04-11 23:29:42,752 [cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2017-04-11 23:29:42,768 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-04-11 23:29:58,564 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "test.exe" (task #9, options "procmemdump=yes,route=none")
2017-04-11 23:29:58,765 [cuckoo.core.scheduler] INFO: Task #9: acquired machine cuckoo1 (label=7)
2017-04-11 23:29:58,775 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 9747 (interface=vboxnet0, host=192.168.56.101, pcap=/home/xenial/.cuckoo/storage/analyses/9/dump.pcap)
2017-04-11 23:30:10,819 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2017-04-11 23:30:14,870 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo1, ip=192.168.56.101)
2017-04-11 23:30:20,054 [cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
2017-04-11 23:30:20,120 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 160, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 150, in stop
    "to Ubuntu-based distributions with AppArmor)?" % (out, err)
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: /home/xenial/.cuckoo/storage/analyses/9/dump.pcap: Permission denied\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor)?
2017-04-11 23:30:29,906 [cuckoo.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label 7 to path /home/xenial/.cuckoo/storage/analyses/9/memory.dmp
2017-04-11 23:30:32,543 [cuckoo.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1028, in run
    results = VolatilityManager(self.memory_path).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 926, in __init__
    for pid in self.voptions.mask.pid_generic.split(","):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by pinksawtooth** [comment]
@jbremer
This is virtualbox.conf

```
[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui" or "headless". Please refer to VirtualBox's official
# documentation to understand the differences.
mode = gui

# Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = vboxnet0

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = cuckoo1,cuckoo2


[cuckoo1]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = 7

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.56.101

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = setting 

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
interface = 

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port = 

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
tags = 

# Mostly unused for now. Please don't fill it out.
#options = 

[cuckoo2]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = xp

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.56.102

[honeyd]
# For more information on this VM please refer to the "services" section of
# the conf/auxiliary.conf configuration file. This machine is a bit special
# in the way that its used as an additional VM for an analysis.
# *NOTE* that if this functionality is used, the VM should be registered in
# the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 192.168.56.102
# The tags should at least contain "service" and the name of this service.
# This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
# Not all services actually have a Cuckoo Agent running in the VM, for those
# services one can specify the "noagent" option so Cuckoo will just wait until
# the end of the analysis instead of trying to connect to the non-existing
# Cuckoo Agent. We can't really intercept any inter-VM communication from the
# host / gateway so in order to dump traffic between VMs we have to use a
# different network dumping approach. For this machine we use the "nictrace"
# functionality from VirtualBox (which is basically their internal tcpdump)
# and thus properly dumps inter-VM traffic.
#options = nictrace noagent
```

**Comment by pinksawtooth** [comment]
I use volatility version 2.6.

I installed it with the following command.
```
git clone https://github.com/volatilityfoundation/volatility.git
sudo python setup.py install
```
https://github.com/volatilityfoundation/volatility/wiki/Installation

**Comment by doomedraven** [comment]
ah wait isn't vol, i saw memory.py and confused things

```
File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 926, in init
for pid in self.voptions.mask.pid_generic.split(","):
AttributeError: 'NoneType' object has no attribute 'split'
```

add some logging there to print that `self.voptions` to see what is wrong there

**Comment by pinksawtooth** [comment]
I added the code as follows.
```
926         if self.voptions.mask.pid_generic is not None:
927             for pid in self.voptions.mask.pid_generic.split(","):
928                 pid = pid.strip()
929                 if pid:
930                     self.mask_pid.append(int(pid))
```
It looks like it works fine.
Is it 	wrong self.voptions.mask.pid_generic ＝ None?

**Comment by jbremer** [comment]
I'm currently working on a fix, but thanks for taking a look as well!

**Comment by jbremer** [comment]
@pinksawtooth I've put up a proper fix for the first issue (NoneType not iterable) and a potential fix for the `pid_generic` stuff, however, I'm not able to test that currently. Would you be so kind to test both fixes on your setup? Preferably also revert the change performed as part of #1381 :-)
I've put up an intermediate alpha version - you can upgrade your setup with `pip install cuckoo==2.0.1a3`.

**Comment by pinksawtooth** [comment]
thank you @jbremer.

I test cuckoo 2.0.1a3 Without commenting out ```#options = ```
It worked fine !

**Comment by jbremer** [comment]
Thanks @pinksawtooth. If you have feedback on the `memory` module working properly as well or if it's throwing different tracebacks now, that'd be great as well!

**Comment by pinksawtooth** [comment]
memory module is working properly!

**Comment by jbremer** [comment]
Ok, thank you! I think that settles this issue, closing it. If you have any other feedback and/or questions, do not hesitate to let us know :-)
