### ISSUE TITLE
Elasticsearch dependency not documented

### ISSUE THREAD

**Issue by MarkusTeufelberger** [cuckoosandbox/cuckoo#1393]
"Elasticsearch" does not really show up anywhere in the documentation, please document which version is needed and for what.

Currently the "[domain]/analysis/search/" page just causes 500 errors for me...

**Comment by MarkusTeufelberger** [comment]
Oh, and apparently Cuckoo seems to not work with Elasticsearch 5.3

**Comment by doomedraven** [comment]
check this https://github.com/cuckoosandbox/cuckoo/issues/1178

**Comment by MarkusTeufelberger** [comment]
I know, I read that one.

**Comment by jbremer** [comment]
You're correct, search is currently broken. We had to postpone some new developments in that regard etc. What about ElasticSearch 5.3, do you have any tracebacks and/or errors?

**Comment by SparkyNZL** [comment]
@jbremer 

Here is a trace from the webserver of what happens if you search an MD5 in cuckoo using ES 5.2

-----------------------------------------------------------------------------------------------------


2017-04-12 17:23:21,815 [django.request] ERROR: Internal Server Error: /analysis/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "./analysis/views.py", line 347, in search
    "term": request.POST["search"],
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/bin/utils.py", line 83, in render_template
    request, template_name, kwargs, status=kwargs.pop("status", 200)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 209, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/defaulttags.py", line 224, in render
    nodelist.append(node.render(context))
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'analysis.views.summary' with arguments '(9800,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/Apr/2017 17:23:21] "POST /analysis/search/ HTTP/1.1" 500 17114
- Broken pipe from ('192.168.20.50', 34228)
2017-04-12 17:23:23,956 [django.request] ERROR: Internal Server Error: /analysis/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "./analysis/views.py", line 347, in search
    "term": request.POST["search"],
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/bin/utils.py", line 83, in render_template
    request, template_name, kwargs, status=kwargs.pop("status", 200)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 209, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/defaulttags.py", line 224, in render
    nodelist.append(node.render(context))
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'analysis.views.summary' with arguments '(9800,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/Apr/2017 17:23:23] "POST /analysis/search/ HTTP/1.1" 500 17114
- Broken pipe from ('192.168.20.50', 34266)
[12/Apr/2017 17:23:24] "POST /analysis/search/ HTTP/1.1" 200 17289

**Comment by jbremer** [comment]
@MarkusTeufelberger @SparkyNZL this should somewhat work starting with `2.0.2a2`.
I'll leave it open for now provided that ElasticSearch should be taken into account in our documentation.

**Comment by SparkyNZL** [comment]
Yes I can confirm that the search is working-ish , It only returns one page of results with no way to see more. but it is very quick, i like that :)
