### ISSUE TITLE
Failure in AnalysisManager.run with OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by raikikon** [cuckoosandbox/cuckoo#1405]
```
cuckoo@cuckoo-VirtualBox:/opt/cuckoo$ sudo ./cuckoo.py

   ______   __  __   ______   ___   ___   ______   ______      
  /_____/\ /_/\/_/\ /_____/\ /___/\/__/\ /_____/\ /_____/\     
  \:::__\/ \:\ \:\ \\:::__\/ \::.\ \\ \ \\:::_ \ \\:::_ \ \    
   \:\ \  __\:\ \:\ \\:\ \  __\:: \/_) \ \\:\ \ \ \\:\ \ \ \   
    \:\ \/_/\\:\ \:\ \\:\ \/_/\\:. __  ( ( \:\ \ \ \\:\ \ \ \  
     \:\_\ \ \\:\_\:\ \\:\_\ \ \\: \ )  \ \ \:\_\ \ \\:\_\ \ \ 
      \_____\/ \_____\/ \_____\/ \__\/\__\/  \_____\/ \_____\/

 Cuckoo Sandbox 1.2
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Outdated! Cuckoo Sandbox version 2.0-rc1 is available now.

/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py:572: SAWarning: Can't resolve label reference 'added_on desc'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
2017-04-13 01:46:27,593 [root] INFO: Updated running task ID 9 status to failed_analysis
2017-04-13 01:46:27,636 [lib.cuckoo.core.scheduler] INFO: Using "avd" machine manager
2017-04-13 01:46:28,057 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-13 01:46:28,070 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py:572: SAWarning: Can't resolve label reference 'priority desc, added_on'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
2017-04-13 01:46:57,981 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_DBsDIe/1.apk" (task=10)
2017-04-13 01:46:57,996 [lib.cuckoo.core.scheduler] INFO: File already exists at "/opt/cuckoo/storage/binaries/4b69cf008f8d8e5276301abaf3dc301394b4c2e803c9caff628f136bc29bc4f9"
2017-04-13 01:46:58,159 [lib.cuckoo.core.scheduler] INFO: Task #10: acquired machine aosx_1 (label=aosx_1)
2017-04-13 01:47:04,117 [modules.machinery.avd] INFO: Stopping AVD listening on port 5554
2017-04-13 01:47:05,311 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 363, in run
    success = self.launch_analysis()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 248, in launch_analysis
    machinery.start(self.machine.label)
  File "/opt/cuckoo/modules/machinery/avd.py", line 75, in start
    self.start_emulator(label)
  File "/opt/cuckoo/modules/machinery/avd.py", line 182, in start_emulator
    self.emulator_processes[label] = OSCommand.executeAsyncCommand(cmd)
  File "/opt/cuckoo/modules/machinery/avd.py", line 307, in executeAsyncCommand
    return subprocess.Popen(commandAndArgs ,stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

```
here is avd.conf
```
[avd]
#Path to the local installation of the android emulator
emulator_path = /home/cuckoo/Android/Sdk/emulator

#Path to the local installation of the adb - android debug bridge utility.
adb_path = /home/cuckoo/Android/Sdk/platform-tools/adb

#Path to the emulator machine files is located
avd_path = /home/cuckoo/.android/avd

#name of the reference machine that is used to duplicate
reference_machine = aosx

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. aosx_1,aosx_2,aosx_3)
#currently supports only 1 machine for network limitations
machines =aosx_1

[aosx_1]
# Specify the label name of the current machine as specified in your
# aosx_1 configuration.
label = aosx_1

# Specify the operating system platform used by current machine
platform = android

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
# its always 127.0.0.1 because android emulator networking configurations this the loopback of the host machine
ip = 127.0.0.1

#Specify the port for the emulator as your adb sees it.
emulator_port=5554

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here 
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 10.0.2.2

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port = 2042
```

the avd emulator is not running 
may be subprocess is unable to execute the correct path ??? dont know 
please help 
already turn off the tcp dump

auxiliary.conf
   ```
 [sniffer]
# Enable or disable the use of an external sniffer (tcpdump) [yes/no].
enabled = yes

# Specify the path to your local installation of tcpdump. Make sure this
# path is correct.
tcpdump = /usr/sbin/tcpdump

# Specify the network interface name on which tcpdump should monitor the
# traffic. Make sure the interface is active.
interface = vboxnet0

# Specify a Berkeley packet filter to pass to tcpdump.
# bpf = not arp

```
i am trying to run linux in vbox with a avd in it ....with the django cuckoodroid web server .

secondly does cuckoodroid support OSX ???

can you give me a block diagaram like 
cuckoo.py > runs > schedular.py > avd.py ... may be i can try to figure this out ...

**Comment by lovina37** [comment]
@raikikon 
this is my emulator path so if u have andsroid sdk folder in downloads it should be this and for the third one i.e avd_path it should be /home/USER_NAME/.android/avd

plus set your PATH variable correctly

you can do sudo gedit ~/.bashrc

and add the following lines in the end 

export PATH=$PATH:/home/lovina/Downloads/android-sdk-linux/tools
export PATH=$PATH:/home/lovina/Downloads/android-sdk-linux/platform-tools
export PATH=$PATH:/home/lovina/Downloads/android-sdk-linux/build-tools
export PATH=$PATH:/home/lovina/Downloads/cuckoo/android-sdk-linux/build-tools/25.0.2
export PATH=$PATH:/home/lovina/Downloads/cuckoo/android-sdk-linux/build-tools/25.0.2/

THis is my path to the android sdk yours will be different also after you have done this you perform the following command

>>source ~/.bashrc

and check the path variable with 

>>echo $PATH


![image](https://cloud.githubusercontent.com/assets/14849570/24978893/449d1c9a-1fa0-11e7-9563-f940a5c434b7.png)

**Comment by lovina37** [comment]
@raikikon 

try doing this

sudo chmod 777 /root/

sudo chmod 777 /home/YOUR_Ubuntu_user_Name/.android/

see this link 

https://github.com/idanr1986/cuckoo-droid/issues/10

**Comment by raikikon** [comment]
thanks for reply 
you are right the problem is with permission not path variable 
on echo $PATH
`/home/cuckoo/bin:/home/cuckoo/.local/bin
:/usr/local/sbin
:/usr/local/bin
:/usr/sbin
:/usr/bin
:/sbin
:/bin
:/usr/games
:/usr/local/games
:/snap/bin
:/home/cuckoo/Android/Sdk/tool
:/home/cuckoo/Android/Sdk/build-tools/25.0.2/
:/home/cuckoo/Android/Sdk/platform-tools
:/home/cuckoo/Android/Sdk/emulator`

as when i reach inside /opt/cuckoo
then execute ./cuckoo.py then if i donot execute it as sudo
it give me error 
```
2017-04-13 10:00:55,866 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 363, in run
    success = self.launch_analysis()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 214, in launch_analysis
    if not self.check_file():
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 92, in check_file
    sha256 = File(self.task.target).get_sha256()
  File "/opt/cuckoo/lib/cuckoo/common/objects.py", line 155, in get_sha256
    if not self._sha256: self.calc_hashes()
  File "/opt/cuckoo/lib/cuckoo/common/objects.py", line 106, in calc_hashes
    for chunk in self.get_chunks():
  File "/opt/cuckoo/lib/cuckoo/common/objects.py", line 92, in get_chunks
    with open(self.file_path, "rb") as fd:
IOError: [Errno 13] Permission denied: u'/tmp/cuckoo-tmp/upload_rvwKNj/1.apk'
```
but then i run it as sudo ./cuckoo.py
i got the lock on the folder in the /home/cuckoo/.android/avd/
in this directory 
lock on folder aosx_1.avd
and lock on folder aosx.ini

these folder as you know are created on every time as new machine is create 
but these folder are create with suppressed permission 
already executed sudo chmod -R 777 /home/cuckoo/.android/avd/
sudo chmod -R 777 /home/cuckoo/.android/
please help 
[http://imgur.com/a/0I3X3] link to screen shot

**Comment by raikikon** [comment]
@lovina37 success
the error lies in android studio new android studio
as 
earlier emulator is in /home/cuckoo/Android/Sdk/tools/emulator
but this emulator doesnot run arm images
so i used new  /home/cuckoo/Android/Sdk/emulator
but this is only directory
hence full path will be 
/home/cuckoo/Android/Sdk/emulator/emulator
```
[avd]
#Path to the local installation of the android emulator
emulator_path = /home/cuckoo/Android/Sdk/emulator

correct
````
[avd]
#Path to the local installation of the android emulator
emulator_path = /home/cuckoo/Android/Sdk/emulator/emulator

**Comment by lovina37** [comment]
@raikikon  did u get cuckoo droid working on your system ??if yes can u tell me all the steps and which setup did u use ?? I have few doubts about hostonly network and internet ?? did u turn any firewall off ??

**Comment by raikikon** [comment]
only 1.2 and its doesnot able to execute apk in virtual machine

**Comment by hlckalana** [comment]
@lovina37,

your solution worked for me.. chmod 777 <required file with path>
