### ISSUE TITLE
Failure in analysis manager run

### ISSUE THREAD

**Issue by lovina37** [cuckoosandbox/cuckoo#1406]
@jbremer @doomedraven @leibiao 

I am using recent version on setup number two i.e cuckoo cuckoodroid and emulator on same host 
lovina@lovina-Aspire-E1-571:~/Downloads/cuckooMode1$ python cuckoo.py

                               ),-.     /
  Cuckoo Sandbox              <(a  `---',' 
     no chance for malwares!  ( `-, ._> )
                               ) _>.___/
                                   _/

 Cuckoo Sandbox 2.0-rc2
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Good! You have the latest version available.

2017-04-12 20:07:09,853 [root] INFO: Updated running task ID 5 status to failed_analysis
2017-04-12 20:07:09,897 [lib.cuckoo.core.scheduler] INFO: Using "avd" as machine manager
2017-04-12 20:07:10,142 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-12 20:07:10,180 [lib.cuckoo.core.scheduler] INFO: Unable to determine the network interface for VM with name aosx_2, Cuckoo will not be able to give it full internet access or route it through a VPN! Please define a default network interface for the machinery or define a network interface for each VM.
2017-04-12 20:07:10,181 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-04-12 20:07:44,968 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "1.apk" (task #6, options "")
2017-04-12 20:07:45,082 [lib.cuckoo.core.scheduler] INFO: Task #6: acquired machine aosx_2 (label=aosx_2)
2017-04-12 20:07:45,227 [modules.machinery.avd] INFO: Stopping AVD listening on port 5554
2017-04-12 20:07:46,412 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/lovina/Downloads/cuckooMode1/lib/cuckoo/core/scheduler.py", line 519, in run
    self.launch_analysis()
  File "/home/lovina/Downloads/cuckooMode1/lib/cuckoo/core/scheduler.py", line 385, in launch_analysis
    machinery.start(self.machine.label, self.task)
TypeError: start() takes exactly 2 arguments (3 given)

**Comment by lovina37** [comment]
@doomedraven  @jbremer Can u suggest something ??I have this folder still if u need to see anything in detail

**Comment by gtback** [comment]
Complete shot in the dark, but I'm wondering if cuckoodroid hasn't been updated to work with the latest (2.0) version of Cuckoo. If it were me, I would try an older version of Cuckoo (either 1.2, or the `legacy` branch).

**Comment by jbremer** [comment]
@lovina37 that issue was resolved in the following commit, 2b1e71d7d1c75ac681089e73982fdc514f3f46b2.
Android support hasn't been changed really (aside from being moved around here and there) for the new release, so it probably works just as well as in `2.0-rc2`, for which unfortunately I'm not sure if it's completely functional.
Btw, there's a pending pull request from last year on improving Android support, perhaps you'd like to try that out.

**Comment by blacvortex** [comment]
@lovina37 I am using the same setup, did it work for you ?

**Comment by lovina37** [comment]
@blacvortex  No It did not work for e

**Comment by blacvortex** [comment]
@lovina37 I was in the same boat as you, but the setup worked for me for Cuckoo 1.2. I am not sure why it did not work for 2.0 so give 1.2 a shot.
I see something errors out in scheduler.py for you, if you want to chase the issues then id recommend putting debug code in scheduler.py to understand what is going on. I was able to resolve an issue via adding debug code.
