### ISSUE TITLE
Internal Server Error: /analysis/search/

### ISSUE THREAD

**Issue by consen** [cuckoosandbox/cuckoo#1408]
Cuckoo 2.0 search error:

```
2017-04-13 12:26:13,214 [django.request] ERROR: Internal Server Error: /analysis/search/
Traceback (most recent call last):
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "./analysis/views.py", line 347, in search
    "term": request.POST["search"],
  File "/home/cuckoo2/cuckoo/cuckoo/web/bin/utils.py", line 83, in render_template
    request, template_name, kwargs, status=kwargs.pop("status", 200)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line329, in render
    return nodelist.render(context)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line224, in render
    nodelist.append(node.render(context))
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line507, in render
    six.reraise(*exc_info)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/cuckoo2/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'analysis.views.summary' with arguments '(21,)' and keyword arguments '{}' notfound. 0 pattern(s) tried: []
```

**Comment by jbremer** [comment]
Thanks for reporting this issue - turns out our current searching capabilities do work to some extent (we're working on improving 'em #1327 #1339). Applying the commit from @mapleray seen above does the trick, so I've taken the liberty of cherry-picking it. Thanks!

**Comment by jbremer** [comment]
@consen @mapleray We've just released an alpha release, which you can get with `pip install cuckoo==2.0.2a2`, containing a fix for the issue here. Please let me know if it also works on your side. This will be part of the upcoming `2.0.2` release.

**Comment by consen** [comment]
@jbremer It works like a charm.

**Comment by jbremer** [comment]
Thanks @consen, closing issue.
