### ISSUE TITLE
trying to redirect cuckoo

### ISSUE THREAD

**Issue by choiwj1216** [cuckoosandbox/cuckoo#1412]
Hello,

Our current cuckoo's internal ip address is: 172.20.1.96:8080
And I am trying to redirect it to triage-qa-cuckoo.pm
However, I am having trouble with this, tried to follow the instruction at:
https://cuckoo.sh/docs/usage/web.html#web-deployment

Trying to configure uwsgi and nginx, but can't get any output from cuckoo web --uwsgi, when instruction says it should be reported by that command.

Can you help me with this?

Thank you!

**Comment by jbremer** [comment]
Can you show the output from `cuckoo web --uwsgi`?

**Comment by choiwj1216** [comment]
where should it execute this command because following output is what I get.

cuckoo@LEE-TRI-QA-01:~$ cuckoo web --uwsgi
cuckoo: command not found

**Comment by doomedraven** [comment]
looks like you not have installed latest cuckoo, do you?

**Comment by choiwj1216** [comment]
it is Sandbox 2.0-rc2.

**Comment by doomedraven** [comment]
see releases section, there already 2.0.1, and the documentation you pointed is for that version

**Comment by choiwj1216** [comment]
Oh I see, did not know there is an updated version. Do I have to upgrade the cuckoo to redirect DNS?

**Comment by doomedraven** [comment]
well if you want to follow documentation, first of all you need to update, + it more stable than rc2, so would be good starting point

**Comment by choiwj1216** [comment]
how do I update it?
I executed cuckoo.sh, and it says I have the latest version available(?)

**Comment by doomedraven** [comment]
that check is not updated, you can install it with `pip install cuckoo`, check the link which you posted with documentation https://cuckoo.sh/docs/installation/host/installation.html

**Comment by choiwj1216** [comment]
thank you, so I did pip install cuckoo and then was able to run cuckoo command.
Followed all the instruction, but I am not able bring it up on web interface anymore. Thinking that I would have to stick with the old way where you execute webserver.sh?

Here are the output for uwsgi and then nginx:

```
[uwsgi]
plugins = python
module = cuckoo.web.web.wsgi
uid = cuckoo
gid = cuckoo
static-map = /static=/usr/local/lib/python2.7/dist-packages/cuckoo/web/static
# If you're getting errors about the PYTHON_EGG_CACHE, then
# uncomment the following line and add some path that is
# writable from the defined user.
# env = PYTHON_EGG_CACHE=
env = CUCKOO_APP=web
env = CUCKOO_CWD=/home/cuckoo/.cuckoo

```


```
upstream _uwsgi_cuckoo_web {
    server unix:/run/uwsgi/app/cuckoo-web/socket;
}

server {
    listen localhost:8000;

    # Cuckoo Web Interface
    location / {
        client_max_body_size 1G;
        uwsgi_pass  _uwsgi_cuckoo_web;
        include     uwsgi_params;
    }
}

```

**Comment by doomedraven** [comment]
standalone `cuckoo -d web -H 0.0.0.0 -p 8000` all commands has --help

and pay attention in your nginx conf

```
server {
    listen localhost:8000;
```

change it to just :8000

**Comment by choiwj1216** [comment]
Thank you, I tried to work it out, but keeps getting errors and now I can't bring up  WEB UI that used to work :(
This is the output:
```
cuckoo@LEE-TRI-QA-01:~$ cuckoo -d web -H 172.20.1.96 -p 8000
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.1', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 483, in web
    Database().connect()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 446, in connect
    self._create_tables()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 454, in _create_tables
    "Unable to create or connect to database: %s" % e
cuckoo.common.exceptions.CuckooDatabaseError: Unable to create or connect to database: (sqlite3.OperationalError) unable to open database file
```


nginx configurations:
```
ubuntu@LEE-TRI-QA-01:/etc/nginx/sites-enabled$ cat cuckoo-web
upstream _uwsgi_cuckoo_web {
    server unix:/run/uwsgi/app/cuckoo-web/socket;
}

server {
    listen :8000;

    # Cuckoo Web Interface
    location / {
        client_max_body_size 1G;
        uwsgi_pass  _uwsgi_cuckoo_web;
        include     uwsgi_params;
    }
}

```
```
ubuntu@LEE-TRI-QA-01:/etc/nginx/sites-enabled$ cat server
server {
listen LEE-TRI-QA-01.corp.phishme.com:80 default_server;
location / {
proxy_pass http://LEE-TRI-QA-01.corp.phishme.com:8000;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
}

```

**Comment by doomedraven** [comment]
`ls -lah $HOME/.cuckoo` or where your `--cwd` is it looks like permissions problem, kinda

**Comment by choiwj1216** [comment]
They are all owned by cuckoo user..

```
cuckoo@LEE-TRI-QA-01:~/cuckoo$ ls -lah
total 76K
drwxr-xr-x 15 cuckoo cuckoo 4.0K Jan 25 08:26 .
drwxr-xr-x 18 cuckoo cuckoo 4.0K Apr 17 12:25 ..
drwxr-xr-x  3 cuckoo cuckoo 4.0K Jan 24 16:52 agent
drwxr-xr-x  6 cuckoo cuckoo 4.0K Nov  4 23:20 analyzer
drwxr-xr-x  2 cuckoo cuckoo 4.0K Jan 25 09:00 conf
-rwxr-xr-x  1 cuckoo cuckoo 4.6K Nov  4 23:20 cuckoo.py
drwxr-xr-x 10 cuckoo cuckoo 4.0K Nov  4 23:20 data
drwxrwxr-x  2 cuckoo cuckoo 4.0K Apr 17 12:30 db
drwxr-xr-x  4 cuckoo cuckoo 4.0K Nov  4 23:20 distributed
drwxr-xr-x  4 cuckoo cuckoo 4.0K Nov  4 23:21 docs
drwxr-xr-x  3 cuckoo cuckoo 4.0K Jan 24 16:48 lib
drwxrwxr-x  2 cuckoo cuckoo 4.0K Jan 25 08:26 log
drwxr-xr-x  7 cuckoo cuckoo 4.0K Jan 25 08:26 modules
-rw-r--r--  1 cuckoo cuckoo  964 Nov  4 23:20 README.md
-rw-r--r--  1 cuckoo cuckoo  623 Nov  4 23:20 requirements.txt
drwxrwxr-x  5 cuckoo cuckoo 4.0K Jan 25 08:26 storage
drwxr-xr-x  4 cuckoo cuckoo 4.0K Nov  4 23:20 utils
drwxr-xr-x  9 cuckoo cuckoo 4.0K Jan 25 08:41 web

```

**Comment by doomedraven** [comment]
check inside of db folder, also try `sudo apt-get install sqlite3` as now it not installed by default
also post connection from `cuckoo.conf` it's empty no?

**Comment by choiwj1216** [comment]
Here is the output of db folder:
```
cuckoo@LEE-TRI-QA-01:~/cuckoo/db$ ll
total 64
drwxrwxr-x  2 cuckoo cuckoo  4096 Apr 17 12:30 ./
drwxr-xr-x 15 cuckoo cuckoo  4096 Jan 25 08:26 ../
-rw-r--r--  1 cuckoo cuckoo 50176 Apr 17 12:30 cuckoo.db
```

Database part from the cuckoo.conf.
Should I uncomment # sqlite:///foo.db?

```
[database]
# Specify the database connection string.
# NOTE: If you are using a custom database (different from sqlite), you have to
# use utf-8 encoding when issuing the SQL database creation statement.
# Examples, see documentation for more:
# sqlite:///foo.db
# postgresql://foo:bar@localhost:5432/mydatabase
# mysql://foo:bar@localhost/mydatabase
# If empty, default is a SQLite in db/cuckoo.db.
connection =

# Database connection timeout in seconds.
# If empty, default is set to 60 seconds.
timeout =
```

**Comment by doomedraven** [comment]
try to set just for test, i have as you empty, in testing server

`connection=sqlite:///cuckoo.db`

**Comment by choiwj1216** [comment]
getting same error. would the configurations of usgwi and nginx be wrong?

```
[database]
# Specify the database connection string.
# NOTE: If you are using a custom database (different from sqlite), you have to
# use utf-8 encoding when issuing the SQL database creation statement.
# Examples, see documentation for more:
# sqlite:///foo.db
# postgresql://foo:bar@localhost:5432/mydatabase
# mysql://foo:bar@localhost/mydatabase
# If empty, default is a SQLite in db/cuckoo.db.
connection = sqlite:///cuckoo.db



```
```
cuckoo@LEE-TRI-QA-01:~/cuckoo/web$ cuckoo web runserver 172.20.1.96:8000
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.1', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 483, in web
    Database().connect()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 446, in connect
    self._create_tables()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 454, in _create_tables
    "Unable to create or connect to database: %s" % e
cuckoo.common.exceptions.CuckooDatabaseError: Unable to create or connect to database: (sqlite3.OperationalError) unable to open database file

```

**Comment by doomedraven** [comment]
well what i can say, you should dig into 
```
 File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 454, in _create_tables
    "Unable to create or connect to database: %s" % e
cuckoo.common.exceptions.CuckooDatabaseError: Unable to create or connect to database: (sqlite3.OperationalError) unable to open database file
```

and add some loggging to see what is wrong there

**Comment by choiwj1216** [comment]
is there anyway to redirect its dns to something else other than ipaddress:portnumber without using uwsgi and nginx?

**Comment by jbremer** [comment]
You have to run `cuckoo`/`cuckoo -d` at least once before starting `cuckoo web` ;-)

**Comment by choiwj1216** [comment]
it seems like it didn't actually update the old version, to replace it, and created whole new cuckoo directory under .cuckoo? Is that how it should be done?

**Comment by jbremer** [comment]
Please refer to our documentation, see also the first few links on the index page https://cuckoo.sh/docs/.

**Comment by choiwj1216** [comment]
Thank you for the support!

**Comment by choiwj1216** [comment]
Actually, I lied. 
I decided to stay with the old version, so I did not import anything from old cuckoo to new directory after pip install. I only redirected its dns.
However, when I try to submit an analysis, it doesn't run properly anymore.
When I submit in web interface, it used to start analyzing, but it keeps waiting for analysis tasks as the attachment. PLEASE HELP ME :(
![webinteface](https://cloud.githubusercontent.com/assets/25231502/25293617/aa6e35d0-26a9-11e7-8998-37b2adcd74d2.PNG)
![cuckoo py](https://cloud.githubusercontent.com/assets/25231502/25293620/ad66dfee-26a9-11e7-9b6b-92fdc81081ba.PNG)
