### ISSUE TITLE
Cuckoo Package : Failed to run processing module "ProcessMemory"

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1417]
Hi guys

I noticed this has been popping up regularly of late,  but not on every sample. Any pointers ?  its a win32 exe binary.

-------------------------------------------------------------------------------------------

2017-04-15 14:56:10,499 [cuckoo.core.plugins] ERROR: Failed to run the processing module "ProcessMemory" for task #12035:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 235, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/procmemory.py", line 211, in run
    proc, self.options.get("extract_dll")
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/procmemory.py", line 180, in dump_images
    yield File(filepath).get_all()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/objects.py", line 392, in get_all
    infos["yara"] = self.get_yara()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/objects.py", line 323, in get_yara
    for match in File.yara_rules[category].match(self.file_path):
Error: internal error: 30

-------------------------------------------------------------------------------------

**Comment by swackhamer** [comment]
That is a yara rule erroring out in the yara library.  Specifically one of your process memory dumps being scanned with a yara rule is causing the error.

Try manually scanning your procmemory dumps from that run against your yara rules to find which yara rule is causing the issue.

**Comment by SparkyNZL** [comment]
Damn I was hoping that wasn't the issue, I have like 421 Yara rules ! Oh
well , I'll sort it today ;) and post the rule name.

Chur

**Comment by jbremer** [comment]
Any progress here @SparkyNZL?

**Comment by SparkyNZL** [comment]
@jbremer yeah ill work on this tomorrow and let you know the Yara rule :)

**Comment by SparkyNZL** [comment]
the yara rule which causes this is peid.yarI can supply the sample is requred

**Comment by jbremer** [comment]
@SparkyNZL Please share the hash or sample, yes. I'm mostly getting 200+ `Packers/peid.yar(57767): warning: $a is slowing down scanning` warnings when running this with the `yara` utility and no matches (but no errors either) for some unrelated file using yara-python.

**Comment by SparkyNZL** [comment]
I'm starting another batch of samples tomorrow so I'll let you know the
samples and send u the Yara rule as well

**Comment by SparkyNZL** [comment]
You got my samples for this aye ?

**Comment by SparkyNZL** [comment]
2017-05-08 19:01:41,897 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Dropped" for task #25885:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 238, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/dropped.py", line 34, in run
    file_info = File(file_path=file_path).get_all()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/objects.py", line 392, in get_all
    infos["yara"] = self.get_yara()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/objects.py", line 323, in get_yara
    for match in File.yara_rules[category].match(self.file_path):
Error: internal error: 30

If not here is another one which i can send you, if you grab the Yara rules from the project, that is what i use at the momnet,

**Comment by jbremer** [comment]
@SparkyNZL I'm going to close this issue. If you do find analyses throwing that error in the future, do let me know. Now we'll be shipping Yara `3.6.1` by default I somewhat hope this issue (among others) have been resolved.
