### ISSUE TITLE
M2Crpyto 0.26.0 Issue

### ISSUE THREAD

**Issue by hakawati** [cuckoosandbox/cuckoo#1421]
```
2017-04-18 13:07:33,332 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Static" for task #2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 235, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/static.py", line 636, in run
    static.update(PortableExecutable(f.file_path).run())
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/static.py", line 303, in run
    results["signature"] = self._get_signature()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/static.py", line 267, in _get_signature
    "email": subject.Email,
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/X509.py", line 320, in __getattr__
    return util.py3str(m2.x509_name_by_nid(self.x509_name, self.nid[attr]))
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/util.py", line 66, in py3str
    raise TypeError('No string argument provided')
TypeError: No string argument provided
```
It is an error when M2Crypto is version 0.26.0.
Fixed to 0.25.1 version.

**Comment by jbremer** [comment]
Cuckoo requires version `0.24.0`, but I've recently come aware that our "only install M2Crypto if swig exists" logic doesn't work normally speaking. Have to find a workaround. The best one being getting rid of `M2Crypto` as it's an awful library.

**Comment by ainiml** [comment]
A fix that worked for me with `m2crypto==0.24` was having it installed earlier than the other pip packages
