### ISSUE TITLE
Submitted samples stuck 'Pending' since upgrade

### ISSUE THREAD

**Issue by FoxyNPF** [cuckoosandbox/cuckoo#1425]
Hi, 

I have upgraded to the latest version of cuckoo, however since doing so my VM does not run the Malware sample. When i open up the dashboard the analysis state is 'pending'.

My VM and Host can ping each other on the 192.168.56.0/24 subnet. My previous version of cuckoo worked so i have a good idea of what should be configured.

Any advice would be appreciated, here is what happens when i fire up cuckoo:

Cuckoo Sandbox 2.0.1
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.1
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0 appdirs:1.4.3 asn1crypto:0.22.0 beautifulsoup4:4.5.3 bottle:0.12.13 bs4:0.0.1 cffi:1.10.0 chardet:2.3.0 clamd:1.0.2 click:6.6 colorama:0.3.7 cryptography:1.8.1 cuckoo:2.0.1 distorm3:3.3.4 distribute:0.7.3 django-extensions:1.6.7 django-ratelimit:1.0.1 django:1.8.4 dnspython:1.15.0 dpkt:1.8.7 dumbnet:1.12 ecdsa:0.13 editorconfig:0.12.1 elasticsearch:5.3.0 enum34:1.1.6 et-xmlfile:1.0.1 flask-sqlalchemy:2.1 flask:0.10.1 functools32:3.2.3.post2 future:0.16.0 geoip:1.3.2 httpreplay:0.2 idna:2.5 ipaddress:1.0.18 itsdangerous:0.24 java-random:1.0 jdcal:1.3 jinja2:2.8 jsbeautifier:1.6.2 jsonschema:2.6.0 libvirt-python:3.0.0 m2crypto:0.24.0 magic-file-extensions:0.2 mako:1.0.6 markupsafe:1.0 ndg-httpsclient:0.4.2 nose:1.3.7 olefile:0.43 oletools:0.42 openpyxl:2.4.2 packaging:16.8 peepdf:0.3.4 pefile2:1.2.11 pefile:1.2.10.post139 pillow:3.2.0 pip:9.0.1 psycopg2:2.6.2 pyasn1:0.2.3 pycparser:2.17 pycrypto:2.6.1 pydeep:0.4 pygal:2.3.1 pygobject:3.20.0 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:16.2.0 pyparsing:2.2.0 pype32:0.1a5 pyste:0.9.10 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 python-whois:0.6.5 pythonaes:1.0 pytz:2016.10 pyv8:1.0.dev0 pyvmomi:6.5 rarfile:3.0 requests:2.7.0 scapy:2.3.2 setuptools:34.4.1 sflock:0.2.7 six:1.10.0 sqlalchemy:1.0.8 sqlparse:0.1.18 suricatasc:0.9 tlslite-ng:0.6.0 unity-lens-photos:1.0 urllib3:1.20 vboxapi:1.0 volatility:2.6 wakeonlan:0.2.2 werkzeug:0.12.1 wheel:0.29.0 yara-python:3.4.0

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 186, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 125, in cuckoo_init
    init_yara(True)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 236, in init_yara
    index_yara()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 216, in index_yara
    with open(cwd("yara", "index_%s.yar" % category), "wb") as f:
IOError: [Errno 13] Permission denied: '/home/cuckoo/.cuckoo/yara/index_binaries.yar'

**Comment by doomedraven** [comment]
if you fix this

`OError: [Errno 13] Permission denied: '/home/cuckoo/.cuckoo/yara/index_binaries.yar'`
everything will work

`chown cuckoo:cucko /home/cuckoo/.cuckoo/ -r` should work

**Comment by FoxyNPF** [comment]
Hi,

Thanks for the quick response that cleared up that issue but i now have another I'm afraid.

When i submit a sample it goes through ok but times out after so long.

My VM can and host can definitely ping each other if i power up the VM and the VirtualBox NIC is configured as Host only.

Cuckoo Sandbox 2.0.1
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!
2017-04-18 16:01:56,231 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-04-18 16:01:59,559 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-18 16:01:59,577 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-04-18 16:02:27,443 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "syshost.exe" (task #2, options "")
2017-04-18 16:02:27,485 [cuckoo.core.scheduler] INFO: Task #2: acquired machine cuckoo (label=cuckoo)
2017-04-18 16:02:27,497 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 5616 (interface=vboxnet0, host=192.168.56.101, pcap=/home/cuckoo/.cuckoo/storage/analyses/2/dump.pcap)
2017-04-18 16:02:30,641 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo, ip=192.168.56.101)
2017-04-18 16:02:36,732 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo, ip=192.168.56.101)
2017-04-18 16:12:38,263 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
2017-04-18 16:12:38,273 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 160, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 150, in stop
    "to Ubuntu-based distributions with AppArmor)?" % (out, err)
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: /home/cuckoo/.cuckoo/storage/analyses/2/dump.pcap: Permission denied\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor)?
2017-04-18 16:12:39,574 [cuckoo.processing.behavior] WARNING: Analysis results folder does not exist at path '/home/cuckoo/.cuckoo/storage/analyses/2/logs'.
2017-04-18 16:12:40,162 [cuckoo.processing.network] WARNING: The PCAP file does not exist at path "/home/cuckoo/.cuckoo/storage/analyses/2/dump.pcap".
2017-04-18 16:12:40,163 [cuckoo.processing.debug] ERROR: Error processing task #2: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2017-04-18 16:12:40,387 [cuckoo.core.scheduler] INFO: Task #2: reports generation completed (path=/home/cuckoo/.cuckoo/storage/analyses/2)
2017-04-18 16:12:40,535 [cuckoo.core.scheduler] INFO: Task #2: analysis procedure completed

**Comment by doomedraven** [comment]
follow the documentation https://cuckoo.sh/docs/index.html
search your issue is there

**Comment by FoxyNPF** [comment]
Apologies didn't see that.. Thanks again.
