### ISSUE TITLE
Help me PLZ...........................

### ISSUE THREAD

**Issue by Killerwhale91** [cuckoosandbox/cuckoo#1444]
2017-04-21 02:53:19,010 [lib.cuckoo.core.scheduler] INFO: Task #5: acquired machine TestWinXP (label=TestWinXP)
2017-04-21 02:53:19,025 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2248 (interface=ens9, host=192.168.100.100, pcap=/opt/cuckoo/storage/analyses/5/dump.pcap)
2017-04-21 02:53:28,522 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=TestWinXP, ip=192.168.100.100)
2017-04-21 02:54:28,100 [lib.cuckoo.core.guest] INFO: TestWinXP: analysis completed successfully
2017-04-21 02:54:28,218 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Potential error while running tcpdump, did not expect the following standard error output: 'dropped privs to root'.
2017-04-21 02:54:29,496 [lib.cuckoo.core.scheduler] ERROR: Machinery error: Error dumping memory virtual machine TestWinXP: Failed to create file '/opt/cuckoo/storage/analyses/5/memory.dmp': No such file or directory
2017-04-21 02:54:33,601 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/opt/cuckoo/modules/processing/memory.py", line 1028, in run
    results = VolatilityManager(self.memory_path).run()
  File "/opt/cuckoo/modules/processing/memory.py", line 948, in run
    vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/opt/cuckoo/modules/processing/memory.py", line 59, in __init__
    self.init_config()
  File "/opt/cuckoo/modules/processing/memory.py", line 113, in init_config
    self.addr_space = utils.load_as(self.config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found

**Comment by doomedraven** [comment]
Do search on tcpdump in issues and it will point you to documentation

**Comment by jbremer** [comment]
@doomedraven this appears to be more of a volatility problem than a tcpdump one (although that's throwing around errors, indeed).
@Killerwhale91 can you perhaps configure `memory.conf` so that it already knows what it's looking for, namely a `winxp` machine? Please also refer to the Volatility docs for that.

**Comment by SparkyNZL** [comment]
@jbremer I think there are still some issues with volatility, well at lease through the WGUI , its seem to not be running it

**Comment by jbremer** [comment]
I believe I've helped you in some other issues regarding this same bug. Closing this one as resolved / duplicate. If you have additional questions, do let us know. Thanks!
