### ISSUE TITLE
ERROR: Internal Server Error: /analysis/api/tasks/recent/

### ISSUE THREAD

**Issue by MarkusTeufelberger** [cuckoosandbox/cuckoo#1449]
````
Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/bin/utils.py", line 47, in inner
     return func(request, *args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
     return func(request, *args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/analysis/api.py", line 340, in tasks_recent
     target = row["target"]["human"]
 KeyError: 'target'
````

Seems like an issue with an archive submission that didn't create a proper entry in Mongo?

I have yet to debug this further, in general it would be nice if one single error in the database doesn't completely break the "Recent" page.

**Comment by MarkusTeufelberger** [comment]
Current hypothesis:

A user uploaded a file that gets detected as archive but couldn't be processed by sflock (e.g. a 7zip or rar file without native tooling present). This still gets into Mongo somehow, but with an incomplete record.

**Comment by MarkusTeufelberger** [comment]
Apparently not, it seems somehow someone managed to submit something that didn't create a target in the first place...

**Comment by jbremer** [comment]
Did you disable the `targetinfo` module or were there any crashes during the processing of the results?
If you reprocess this analysis, does the `KeyError` go away?

**Comment by MarkusTeufelberger** [comment]
The cuckoo log shows the following error:
````
xxx [cuckoo.core.guest] WARNING: xxx: analysis caught an exception
Traceback (most recent call last):
  File "C:\tmp6pyyki\analyzer.py", line 784, in <module>
    success = analyzer.run()
  File "C:\tmp6pyyki\analyzer.py", line 572, in run
    "not exist.".format(package_name))
CuckooError: Unable to import package "modules.packages.None", does not exist.
````

It also shows that "TargetInfo" and "Static" failed to run for this task.

**Comment by jbremer** [comment]
Can you provide those stacktraces? Those are actually the core issue here ;-)
What kind of samples are you analyzing? Do you have hashes that you can share?

**Comment by MarkusTeufelberger** [comment]
Where would the stack traces be stored?

I'm analyzing general stuff on Windows, no sharing though, sorry. In this case it seems to have been a .msg file by the way, I am still not sure how someone managed to break the system like that...

**Comment by jbremer** [comment]
You can usually find those on the command-line or in `~/.cuckoo/log/cuckoo.log`. Well, the new submission screen has taken us months and months of development, and even though we've put in a lot of effort in our recursive sample unpacking logic (i.e., unpacking whatever is inside the `.msg` and submitting that instead of just pushing the `.msg` to the VM) it's still not bulletproof. I'm not even sure if commercial sandboxes provide such recursive unpacking support, so please bear with us while we try to make the best out of it ;-)

Please try to resubmit the sample and check for any tracebacks that we can work with. In the meanwhile I'll harden the web interface a bit - thanks for the feedback on that.

**Comment by jbremer** [comment]
@MarkusTeufelberger a workaround for the recent page may be found in the commit above, it'll be part of the next upcoming (alpha) release. I'm leaving this issue open provided that more error handling should be done for the `sflock` / archives part as well as the real fix, but unfortunately that will have to wait until I come across a sample that can be shared and provides the same behavior (a crash).
