### ISSUE TITLE
[cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1456]
Hi guys,

I have noticed this error popping up recently . It 

----------------------------------------------------------------------------------------------------------

2017-04-22 13:56:33,675 [cuckoo.core.scheduler] INFO: Task #19253: acquired machine cuckoo4 (label=cuckoo4)
2017-04-22 13:56:33,842 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 6847 (interface=vboxnet0, host=192.168.56.43, pcap=/home/blah/.cuckoo/storage/analyses/19253/dump.pcap)
2017-04-22 13:56:42,318 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo4, ip=192.168.56.43)
2017-04-22 13:56:47,857 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\vyhnd\analyzer.py", line 784, in <module>
    success = analyzer.run()
  File "C:\vyhnd\analyzer.py", line 639, in run
    pids = self.package.start(self.target)
  File "C:\vyhnd\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\vyhnd\lib\common\abstracts.py", line 165, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

---------------------------------------------------------------------------------------------------

**Comment by jbremer** [comment]
You're going to have to share some hashes :)

**Comment by myrinx** [comment]
same issue here:

2017-05-04 03:46:26,907 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\llplopj\analyzer.py", line 784, in <module>
    success = analyzer.run()
  File "C:\llplopj\analyzer.py", line 639, in run
    pids = self.package.start(self.target)
  File "C:\llplopj\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\llplopj\lib\common\abstracts.py", line 165, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

2017-05-04 03:46:27,005 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run

**Comment by kdeltared** [comment]
I'm having the same issue, while trying to dockerize cuckoo.
`machinery=esx` `guest vm=win 7 x64`
`sample_hash = 7f4f567e55013c9bb2b13a0bb208558f1b2d46fcbd96c2132d91beb38099019b`

```
2017-06-13 17:32:17,559 [cuckoo.core.resultserver] DEBUG: ResultServer running on 0.0.0.0:2042.
2017-06-13 17:32:17,560 [cuckoo.core.scheduler] INFO: Using "esx" as machine manager
2017-06-13 17:32:17,890 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:32:17,910 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-06-13 17:32:17,924 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-06-13 17:35:17,181 [cuckoo.core.scheduler] DEBUG: Processing task #15
2017-06-13 17:35:17,191 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "7f4f567e55013c9bb2b13a0bb208558f1b2d46fcbd96c2132d91beb38099019b" (task #15, options "procmemdump=yes,route=none")
2017-06-13 17:35:17,219 [cuckoo.core.scheduler] INFO: Task #15: acquired machine Windows7x64_1 (label=Windows7x64_1)
2017-06-13 17:35:17,347 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 81 (interface=eth0, host=192.168.104.60, pcap=/cuckoo/storage/analyses/15/dump.pcap)
2017-06-13 17:35:17,347 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2017-06-13 17:35:17,378 [cuckoo.common.abstracts] DEBUG: Starting machine Windows7x64_1
2017-06-13 17:35:17,378 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:35:17,401 [cuckoo.common.abstracts] DEBUG: Using snapshot Snapshot1 for virtual machine Windows7x64_1
2017-06-13 17:35:17,850 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:35:17,891 [cuckoo.core.guest] INFO: Starting analysis on guest (id=Windows7x64_1, ip=192.168.104.60)
2017-06-13 17:35:18,895 [cuckoo.core.guest] DEBUG: Windows7x64_1: not ready yet
2017-06-13 17:35:20,000 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=Windows7x64_1, ip=192.168.104.60)
2017-06-13 17:35:20,039 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=Windows7x64_1, ip=192.168.104.60, monitor=latest, size=3819773)
2017-06-13 17:35:20,455 [cuckoo.core.guest] DEBUG: Windows7x64_1: analysis still processing
2017-06-13 17:35:20,634 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2017-06-13 17:35:21,462 [cuckoo.core.guest] DEBUG: Windows7x64_1: analysis still processing
2017-06-13 17:35:22,355 [cuckoo.core.resultserver] DEBUG: File upload request for shots/0001.jpg
2017-06-13 17:35:22,359 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 47685
2017-06-13 17:35:22,468 [cuckoo.core.guest] DEBUG: Windows7x64_1: analysis still processing
2017-06-13 17:35:23,432 [cuckoo.core.resultserver] DEBUG: File upload request for shots/0002.jpg
2017-06-13 17:35:23,435 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 56167
2017-06-13 17:35:23,472 [cuckoo.core.guest] WARNING: Windows7x64_1: analysis caught an exception
Traceback (most recent call last):
  File "C:\tmp5nvdd0\analyzer.py", line 784, in <module>
    success = analyzer.run()
  File "C:\tmp5nvdd0\analyzer.py", line 639, in run
    pids = self.package.start(self.target)
  File "C:\tmp5nvdd0\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmp5nvdd0\lib\common\abstracts.py", line 165, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

2017-06-13 17:35:23,478 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 160, in stop
    module.stop()
  File "/usr/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 150, in stop
    "to Ubuntu-based distributions with AppArmor)?" % (out, err)
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = "tcpdump: eth0: You don't have permission to capture on that device\n(socket: Operation not permitted)\n". Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor)?
2017-06-13 17:35:23,483 [cuckoo.common.abstracts] DEBUG: Stopping machine Windows7x64_1
2017-06-13 17:35:23,483 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:35:23,650 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:35:25,165 [cuckoo.core.scheduler] DEBUG: Released database task #15
```

**Comment by gnicolao** [comment]
Hi, I'm having the same issue.
Machinery: KVM  guest vm=win 7 x64
hash: e34f0c3e659a4553cb64f12bc1308acdc0194e27b8bccd29651a31202795ebbf

`2018-07-27 19:35:52,389 [cuckoo.core.scheduler] INFO: Task #21: acquired machine Windows7x64_1 (label=Windows7x64_1)
2018-07-27 19:35:52,396 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 12568 (interface=virbr0, host=192.168.59.30)
2018-07-27 19:35:52,396 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2018-07-27 19:35:52,457 [cuckoo.common.abstracts] DEBUG: Starting machine Windows7x64_1
2018-07-27 19:35:52,457 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2018-07-27 19:35:52,473 [cuckoo.common.abstracts] DEBUG: Using snapshot Snapshot1 for virtual machine Windows7x64_1
2018-07-27 19:35:53,683 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2018-07-27 19:35:53,753 [cuckoo.core.guest] INFO: Starting analysis on guest (id=Windows7x64_1, ip=192.168.59.30)
2018-07-27 19:35:54,756 [cuckoo.core.guest] DEBUG: Windows7x64_1: not ready yet
2018-07-27 19:35:55,759 [cuckoo.core.guest] DEBUG: Windows7x64_1: not ready yet
2018-07-27 19:35:56,761 [cuckoo.core.guest] DEBUG: Windows7x64_1: not ready yet
2018-07-27 19:35:56,767 [cuckoo.core.guest] DEBUG: Windows7x64_1: waiting for status 0x0001
2018-07-27 19:35:56,769 [cuckoo.core.guest] DEBUG: Windows7x64_1: status ready
2018-07-27 19:35:56,778 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=Windows7x64_1, ip=192.168.59.30, monitor=latest, size=3852382)
2018-07-27 19:35:57,447 [cuckoo.core.guest] DEBUG: Windows7x64_1: analyzer started with PID 2872
2018-07-27 19:35:57,483 [cuckoo.core.guest] DEBUG: Windows7x64_1: waiting for completion
2018-07-27 19:35:57,616 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2018-07-27 19:35:58,488 [cuckoo.core.guest] DEBUG: Windows7x64_1: analysis not completed yet (status=2)
2018-07-27 19:35:59,491 [cuckoo.core.guest] DEBUG: Windows7x64_1: analysis not completed yet (status=2)
2018-07-27 19:36:00,496 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\bbkctsa\analyzer.py", line 800, in <module>
    success = analyzer.run()
  File "C:\bbkctsa\analyzer.py", line 652, in run
    pids = self.package.start(self.target)
  File "C:\bbkctsa\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\bbkctsa\lib\common\abstracts.py", line 166, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

2018-07-27 19:36:00,887 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2018-07-27 19:36:00,899 [cuckoo.common.abstracts] DEBUG: Dumping memory for machine Windows7x64_1
2018-07-27 19:36:18,338 [cuckoo.common.abstracts] DEBUG: Stopping machine Windows7x64_1
2018-07-27 19:36:18,338 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2018-07-27 19:36:18,856 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2018-07-27 19:36:19,961 [cuckoo.core.scheduler] DEBUG: Released database task #21
2018-07-27 19:36:19,995 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #21
2018-07-27 19:36:19,996 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #21
2018-07-27 19:36:19,997 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #21
2018-07-27 19:36:19,997 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #21
2018-07-27 19:36:19,997 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #21
2018-07-27 19:36:19,997 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #21
2018-07-27 19:36:19,997 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #21
2018-07-27 19:36:20,202 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #21
2018-07-27 19:36:20,208 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #21
2018-07-27 19:36:28,316 [cuckoo.core.plugins] DEBUG: Executed processing module "Suricata" for task #21
2018-07-27 19:36:28,320 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #21
2018-07-27 19:36:28,320 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #21
2018-07-27 19:36:28,321 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #21
2018-07-27 19:36:28,321 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #21
2018-07-27 19:36:28,323 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #21
2018-07-27 19:36:28,325 [cuckoo.core.plugins] DEBUG: Running 540 signatures
2018-07-27 19:36:28,418 [cuckoo.core.plugins] DEBUG: Analysis matched signature: has_pdb
2018-07-27 19:36:28,418 [cuckoo.core.plugins] DEBUG: Analysis matched signature: packer_entropy
2018-07-27 19:36:28,418 [cuckoo.core.plugins] DEBUG: Analysis matched signature: pe_features
2018-07-27 19:36:28,446 [cuckoo.core.plugins] DEBUG: Executed reporting module "SingleFile"`

**Comment by cyjcyjcyj** [comment]
Has anyone resolved this problem?

**Comment by DragonQuestHero** [comment]
same issues...
calc.exe

cuckoo1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpwlk6pb/analyzer.py", line 800, in <module>
    success = analyzer.run()
  File "C:/tmpwlk6pb/analyzer.py", line 652, in run
    pids = self.package.start(self.target)
  File "C:\tmpwlk6pb\modules\packages\exe.py", line 27, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmpwlk6pb\lib\common\abstracts.py", line 171, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

**Comment by DragonQuestHero** [comment]
ok...i got
guest vm need administrator account....
