### ISSUE TITLE
Rooter.py SQLAlchemy issue

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#1459]
I have 1.0.13 installed...is it required to have EXACTLY version 1.0.8?
~~~
root@other:~/.cuckoo/conf# python /usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/apps/rooter.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/apps/rooter.py", line 20, in <module>
    from cuckoo.misc import version as __version__
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/auxiliary/__init__.py", line 6, in <module>
    from cuckoo.core.plugins import enumerate_plugins
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/core/plugins.py", line 13, in <module>
    from cuckoo.common.config import config2
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/common/config.py", line 15, in <module>
    from cuckoo.common.objects import Dictionary
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/common/objects.py", line 19, in <module>
    from cuckoo.common.whitelist import is_whitelisted_domain
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/common/whitelist.py", line 6, in <module>
    from cuckoo.misc import cwd
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.0-py2.7.egg/cuckoo/misc.py", line 31, in <module>
    version = pkg_resources.require("Cuckoo")[0].version
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (SQLAlchemy 1.0.13 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('sqlalchemy==1.0.8'), set(['Cuckoo']))
~~~

**Comment by doomedraven** [comment]
Looks like

**Comment by jbremer** [comment]
`1.0.13` most likely also works, but before we upgrade our suggested `sqlalchemy` version we're first going to need unit tests for most of our database interaction - which, for the biggest part, is still not present.
Due to some issues we've had in the past with 3rd party libraries being updated after our release I'm a bit "protective" of upgrading 'em without any testing.

**Comment by DigiAngel** [comment]
Understood...lemme know if I can do any testing as I'm running both 1
and 2 in tandem.  Thank you.

**Comment by jbremer** [comment]
Sure thing. Will be closing this issue in the meanwhile, though. Thanks for reporting.
