### ISSUE TITLE
Why Error???

### ISSUE THREAD

**Issue by Killerwhale91** [cuckoosandbox/cuckoo#1467]
KVM Virtualization(Main Server)
ubuntu16.04(VM server) -> WindowsXP(VM Client)
192.168.250.250  -----------------192.168.250.125

why did error?????????????
memory.dmp File is 0Bytes

2017-04-24 21:15:41,436 [lib.cuckoo.core.scheduler] INFO: Task #2: acquired machine CuckooClient (label=CuckooClient)
2017-04-24 21:15:41,552 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 1579 (interface=ens3, host=192.168.250.125, pcap=/root/cuckoo/storage/analyses/2/dump.pcap)
2017-04-24 21:15:50,835 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=CuckooClient, ip=192.168.250.125)
2017-04-24 21:16:52,965 [lib.cuckoo.core.guest] INFO: CuckooClient: analysis completed successfully
2017-04-24 21:16:53,090 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Potential error while running tcpdump, did not expect the following standard error output: 'dropped privs to root'.
2017-04-24 21:16:53,987 [lib.cuckoo.core.scheduler] ERROR: Machinery error: Error dumping memory virtual machine CuckooClient: Failed to create file '/root/cuckoo/storage/analyses/2/memory.dmp': No such file or directory
2017-04-24 21:17:11,989 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/root/cuckoo/modules/processing/memory.py", line 1028, in run
    results = VolatilityManager(self.memory_path).run()
  File "/root/cuckoo/modules/processing/memory.py", line 948, in run
    vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/root/cuckoo/modules/processing/memory.py", line 59, in __init__
    self.init_config()
  File "/root/cuckoo/modules/processing/memory.py", line 113, in init_config
    self.addr_space = utils.load_as(self.config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 VMWareMetaAddressSpace: VMware metadata file is not available
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: -
 QemuCoreDumpElf: ELF Header signature invalid
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 WindowsAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 LinuxAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 IA32PagedMemoryPae: No valid DTB found
 IA32PagedMemory: No valid DTB found
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found

**Comment by jbremer** [comment]
Because your `memory.dmp` file is empty. The commit you find above will in the future show you a nice error message rather than the Volatility output (which is much less meaningful). In other words, something went wrong with the creation of the VM memory dump.
I'm not sure if we can help you with that? KVM VM memory dumping should work.

**Comment by jbremer** [comment]
We've put out `2.0.3a2` including the commit mentioned above. Other than that I think the Cuckoo part has been resolved here?

**Comment by jbremer** [comment]
@Killerwhale91 can this issue be closed?

**Comment by jbremer** [comment]
I assume that's a yes. Feel free to reopen or create a new issue if you have additional questions and/or feedback!

**Comment by dimis79** [comment]
Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
2017-07-13 11:23:18,724 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Potential error while running tcpdump, did not expect the following standard error output: 'dropped privs to root'.
2017-07-13 11:23:26,200 [modules.processing.behavior] WARNING: Analysis results folder does not contain any behavior log file

Please help me ! how to solve it!

**Comment by doomedraven** [comment]
don't run as root, change permissions and run as normal user

**Comment by dimis79** [comment]
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:18: UserWarning: You're using python 2, it is strongly recommended to use python >=3.3
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.3")
/usr/local/lib/python2.7/dist-packages/pymisp/mispevent.py:26: UserWarning: You're using python 2, it is strongly recommended to use python >=3.3
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.3")
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:36: UserWarning: You're using python 2, it is strongly recommended to use python >=3.3
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.3")
2017-07-13 16:53:23,732 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-07-13 16:53:25,647 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-07-13 16:53:25,662 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-07-13 16:54:42,976 [lib.cuckoo.core.scheduler] INFO: Starting analysis of URL "192.168.1.164" (task #28, options "route=none,procmemdump=yes")
2017-07-13 16:54:43,082 [lib.cuckoo.core.scheduler] INFO: Task #28: acquired machine windows7 (label=windows7)
2017-07-13 16:54:43,121 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 4256 (interface=vboxnet0, host=192.168.1.164, pcap=/opt/cuckoo/storage/analyses/28/dump.pcap)
2017-07-13 16:54:54,932 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=windows7, ip=192.168.1.164)
2017-07-13 16:58:16,857 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
2017-07-13 16:58:17,054 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: vboxnet0: That device is not up\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor)?
2017-07-13 16:58:23,851 [modules.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2017-07-13 16:58:23,952 [modules.processing.network] WARNING: The PCAP file does not exist at path "/opt/cuckoo/storage/analyses/28/dump.pcap".
2017-07-13 16:58:23,990 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "vlc-2.2.6-win32.exe" (task #29, options "")
2017-07-13 16:58:25,140 [lib.cuckoo.core.scheduler] INFO: Task #28: reports generation completed (path=/opt/cuckoo/storage/analyses/28)
2017-07-13 16:58:25,257 [lib.cuckoo.core.scheduler] INFO: Task #28: analysis procedure completed
2017-07-13 16:58:25,650 [lib.cuckoo.core.scheduler] INFO: File already exists at "/opt/cuckoo/storage/binaries/6000f3a1386c06eed2a61ede6437df2e537e1bcaac73a4a32b7648a99ffcb6ed"
2017-07-13 16:58:25,724 [lib.cuckoo.core.scheduler] INFO: Task #29: acquired machine windows7 (label=windows7)
2017-07-13 16:58:25,737 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5359 (interface=vboxnet0, host=192.168.1.164, pcap=/opt/cuckoo/storage/analyses/29/dump.pcap)
2017-07-13 16:58:31,818 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=windows7, ip=192.168.1.164)
2017-07-13 17:01:32,583 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: windows7: the guest initialization hit the critical timeout, analysis aborted.
2017-07-13 17:01:32,655 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: vboxnet0: That device is not up\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor)?
2017-07-13 17:01:34,275 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path '/opt/cuckoo/storage/analyses/29/logs'.
2017-07-13 17:01:42,012 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static" for task #29:
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 242, in process
    data = current.run()
  File "/opt/cuckoo/modules/processing/static.py", line 680, in run
    static.update(PortableExecutable(self.file_path).run())
  File "/opt/cuckoo/modules/processing/static.py", line 347, in run
    results["signature"] = self._get_signature()
  File "/opt/cuckoo/modules/processing/static.py", line 311, in _get_signature
    "email": subject.Email,
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/X509.py", line 320, in __getattr__
    return util.py3str(m2.x509_name_by_nid(self.x509_name, self.nid[attr]))
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/util.py", line 66, in py3str
    raise TypeError('No string argument provided')
TypeError: No string argument provided
2017-07-13 17:01:45,456 [modules.processing.network] WARNING: The PCAP file does not exist at path "/opt/cuckoo/storage/analyses/29/dump.pcap".
2017-07-13 17:01:47,607 [lib.cuckoo.core.scheduler] INFO: Task #29: reports generation completed (path=/opt/cuckoo/storage/analyses/29)
Please help me to solve all of them !

**Comment by doomedraven** [comment]
Did yoy even read the manual and error?

vboxnet0: That device is not up\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor)?

**Comment by dimis79** [comment]
Yes but I 'm confused! I don't know how to do it! I tried to solve about the internet information but I can't. It's the first time that I have this problem. Please help me!

**Comment by doomedraven** [comment]
In manual you have all steps which you need, read it slowly!
