### ISSUE TITLE
Failed to run the processing module "Static" for task #

### ISSUE THREAD

**Issue by bnder321** [cuckoosandbox/cuckoo#1513]
Hello everybody,

I sometimes get this error during samples analysis.
**Failed to run the processing module "Static" for task #**

I wounder if someone could advice. 

Thank you.

**Comment by jbremer** [comment]
Well, please include more logs ;-)

**Comment by bnder321** [comment]
First of all, I really appreciate your prompt response.

the log:

017-05-01 03:58:20,135 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "VirusShare_034fff6bbd4ff9bb58dcae1db972fab0" (task #185, options "")
2017-05-01 03:58:20,169 [lib.cuckoo.core.scheduler] INFO: Task #185: acquired machine cuckoo1 (label=aa)
2017-05-01 03:58:20,238 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 102797 (interface=vboxnet0, host=192.168.56.102, pcap=/home/cuckoo/analysis/cuckoo/storage/analyses/185/dump.pcap)
2017-05-01 03:58:25,039 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.102)
2017-05-01 04:00:36,415 [lib.cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
**2017-05-01 04:00:41,130 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static" for task #185:
Traceback (most recent call last):
  File "/home/cuckoo/analysis/cuckoo/lib/cuckoo/core/plugins.py", line 242, in process
    data = current.run()
  File "/home/cuckoo/analysis/cuckoo/modules/processing/static.py", line 680, in run
    static.update(PortableExecutable(self.file_path).run())
  File "/home/cuckoo/analysis/cuckoo/modules/processing/static.py", line 347, in run
    results["signature"] = self._get_signature()
  File "/home/cuckoo/analysis/cuckoo/modules/processing/static.py", line 308, in _get_signature
    "country": subject.C,
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/X509.py", line 320, in __getattr__
    return util.py3str(m2.x509_name_by_nid(self.x509_name, self.nid[attr]))
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/util.py", line 66, in py3str
    raise TypeError('No string argument provided')
TypeError: No string argument provided**
2017-05-01 04:01:08,470 [lib.cuckoo.core.scheduler] INFO: Task #185: reports generation completed (path=/home/cuckoo/analysis/cuckoo/storage/analyses/185)
2017-05-01 04:01:08,494 [lib.cuckoo.core.scheduler] INFO: Task #185: analysis procedure completed

**Comment by jbremer** [comment]
What version of `m2crypto` do you have installed (`pip freeze|grep -i m2crypto`)?

**Comment by bnder321** [comment]
M2Crypto==0.26.0

**Comment by jbremer** [comment]
You're going to need `0.24.0` for Cuckoo. Actually, we want to replace the library in the first place, but there isn't really an easy replacement for our use-case (as far as I saw anyway).

**Comment by bnder321** [comment]
is it a straight forward downgrade , and the current cuckoo  installation will not be affected?

**Comment by jbremer** [comment]
Yes, just `pip install m2crypto==0.24.0`, it should resolve your issue.
Our new release is completely different (in a good way) though :-)

**Comment by bnder321** [comment]
There is another issue and I am not sure whether it is relevant to this . the log is : 

2017-05-01 03:41:46,576 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "VirusShare_03473ea972b7f1754c202ade18972d80" (task #177, options "")
2017-05-01 03:41:46,603 [lib.cuckoo.core.scheduler] INFO: Task #177: acquired machine cuckoo1 (label=hr02)
2017-05-01 03:41:46,664 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 100460 (interface=vboxnet0, host=192.168.56.102, pcap=/home/cuckoo/analysis/cuckoo/storage/analyses/177/dump.pcap)
2017-05-01 03:41:51,347 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.102)
**2017-05-01 03:42:04,200 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\fhpmcst\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\fhpmcst\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.**

2017-05-01 03:42:08,019 [lib.cuckoo.core.scheduler] INFO: Task #177: reports generation completed (path=/home/cuckoo/analysis/cuckoo/storage/analyses/177)
2017-05-01 03:42:08,037 [lib.cuckoo.core.scheduler] INFO: Task #177: analysis procedure completed

**Comment by jbremer** [comment]
We'll have to give that sample a spin, thanks for reporting :)

**Comment by bnder321** [comment]
I've tried pip install m2crypto==0.24.0  but I get following error: 

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GzBB3u/m2crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-NlNmCO-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-GzBB3u/m2crypto/

**Comment by jbremer** [comment]
Meh, do you have `swig` installed?

**Comment by bnder321** [comment]
swig wasn't installed. now, install m2crypto==0.24.0  succeeded.

**Comment by bnder321** [comment]
now I am getting this error (but with only some samples):
ERROR: Unable to open /home/cuckoo/analysis/cuckoo/storage/analyses/249/dump_sorted.pcap

**Comment by jbremer** [comment]
You can either ignore that or upgrade your Cuckoo ;)

**Comment by bnder321** [comment]
is there a new version of Cuckoo? I thought I have the latest.

**Comment by jbremer** [comment]
That check is unfortunately not working very well. I shared the link to our blogpost earlier.. ;)

**Comment by bnder321** [comment]
The m2crypto issue has been resolved by downgrading to 0.24.0.
Thanks a lot @jbremer.
