### ISSUE TITLE
AttributeError when submitting samples.

### ISSUE THREAD

**Issue by Waffles-2** [cuckoosandbox/cuckoo#1517]
When I try to submit a sample to cuckoo using the command `cuckoo submit /path/to/binary` I receive the error `AttributeError: 'NoneType' object has no attribute 'id'`

Also to note is that submitting URLs work fine also using the command `cuckoo submit -u http://www.google.com`. I have also tried `cuckoo clean`

Below is the full error:

```
Traceback (most recent call last):
  File "c:\python27\scripts\cuckoo-script.py", line 11, in <module>
    load_entry_point('Cuckoo==2.0.2', 'console_scripts', 'cuckoo')()
  File "c:\python27\lib\site-packages\click-6.6-py2.7.egg\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click-6.6-py2.7.egg\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click-6.6-py2.7.egg\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click-6.6-py2.7.egg\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click-6.6-py2.7.egg\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click-6.6-py2.7.egg\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python27\lib\site-packages\cuckoo-2.0.2-py2.7.egg\cuckoo\main.py", line 279, in submit
    for category, target, task_id in l:
  File "c:\python27\lib\site-packages\cuckoo-2.0.2-py2.7.egg\cuckoo\apps\apps.py", line 193, in submit_tasks
    task_id = db.add_path(file_path=filepath, **data)
  File "c:\python27\lib\site-packages\cuckoo-2.0.2-py2.7.egg\cuckoo\core\database.py", line 1107, in add_path
    enforce_timeout, clock, "file", submit_id)
  File "c:\python27\lib\site-packages\cuckoo-2.0.2-py2.7.egg\cuckoo\common\utils.py", line 189, in inner
    return f(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\cuckoo-2.0.2-py2.7.egg\cuckoo\core\database.py", line 1018, in add
    task.sample_id = sample.id
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by jbremer** [comment]
Most likely your database hasn't been setup properly, can you run `cuckoo -d submit ...` instead and share the output? Thanks!

**Comment by Waffles-2** [comment]
Here is the output from `cuckoo -d submit ...`

```
No handlers could be found for logger "cuckoo.compat.magic"
Traceback (most recent call last):
  File "C:\PYTHON27\LIB\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\PYTHON27\LIB\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\scripts\cuckoo.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python27\lib\site-packages\cuckoo\main.py", line 279, in submit
    for category, target, task_id in l:
  File "c:\python27\lib\site-packages\cuckoo\apps\apps.py", line 193, in submit_tasks
    task_id = db.add_path(file_path=filepath, **data)
  File "c:\python27\lib\site-packages\cuckoo\core\database.py", line 1107, in add_path
    enforce_timeout, clock, "file", submit_id)
  File "c:\python27\lib\site-packages\cuckoo\common\utils.py", line 189, in inner
    return f(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\cuckoo\core\database.py", line 1018, in add
    task.sample_id = sample.id
```

**Comment by jbremer** [comment]
Interesting! Aside from some minor tweaks that have to be done in Cuckoo as you're using a 64-bit Python setup (which isn't fully supported but is fine otherwise), I'd like to investigate this SQL issue. I see a number of reasons why this may happen. Could you share a SQL dump with me (either here or drop me an email at `jbr@cuckoo.sh`). Thanks!

**Comment by Waffles-2** [comment]
Thanks a lot @jbremer I have sent you an email.

**Comment by jbremer** [comment]
This issue has been resolved (and checked on both sides) with the commit above, closing it. Thanks!
