### ISSUE TITLE
Unable to load the Cuckoo plugin at feedback.py: cannot import name binary_type

### ISSUE THREAD

**Issue by cchansk** [cuckoosandbox/cuckoo#1518]
Any commands that I type with cuckoo gives me the below alert.

Traceback (most recent call last):
  File "/usr/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.2', 'console_scripts', 'cuckoo')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/lib/python2.7/site-packages/cuckoo/reporting/__init__.py", line 10, in <module>
    __file__, "cuckoo.reporting", globals(), Report
  File "/usr/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 44, in enumerate_plugins
    "review its contents and/or validity!" % (fname, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at feedback.py: cannot import name binary_type. Please review its contents and/or validity!

**Comment by jbremer** [comment]
What happens when you run the following in a Python shell `import cuckoo.reporting.feedback`?
For me this looks roughly as follows:
```
(cuckoo)➜  cuckoo git:(master) ✗ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cuckoo.reporting.feedback
>>> 
```

**Comment by cchansk** [comment]
When I first ran it, it looked like I was missing a lot of dependencies. I got the follow errors as I installed them one after another.

pkg_resources.DistributionNotFound: The 'scapy==2.3.2' distribution was not found and is required by Cuckoo
pkg_resources.DistributionNotFound: The 'idna>=2.0.0' distribution was not found and is required by requests". **However, pip said it was already installed, so I ran pip install idna==2.1**
pkg_resources.DistributionNotFound: The 'cryptography>=1.3.4' distribution was not found and is required by requests"
pkg_resources.DistributionNotFound: The 'pyOpenSSL>=0.14' distribution was not found and is required by requests
pkg_resources.DistributionNotFound: The 'functools32' distribution was not found and is required by jsonschema

However, now I'm showing the same results as you have above, but I'm still getting the same errors:

Traceback (most recent call last):
  File "/usr/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.2', 'console_scripts', 'cuckoo')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/lib/python2.7/site-packages/cuckoo/reporting/__init__.py", line 10, in <module>
    __file__, "cuckoo.reporting", globals(), Report
  File "/usr/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 44, in enumerate_plugins
    "review its contents and/or validity!" % (fname, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at feedback.py: cannot import name binary_type. Please review its contents and/or validity!

**Comment by jbremer** [comment]
Perhaps run `pip install -U pip setuptools` first & then try to re-install Cuckoo? You're certainly missing a whole bunch of stuff as-is. What OS are you running? And what does my Python question from above give for you?

**Comment by cchansk** [comment]
I'm running centos. Below is the results i get now:

Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cuckoo.reporting.feedback
>>>

**Comment by doomedraven** [comment]
centos is not very good supported

**Comment by cchansk** [comment]
I did eventually get it to work after a while. With setuptools vers. 34, I was not able to run pip install -U --force-reinstall cuckoo. This looks like it was due to an issue with the newer version of setuptools ([https://github.com/pypa/setuptools/issues/951](url)). After I downgraded to setuptools 32, then I was able to force reinstall of cuckoo and it now seems to be working.

Thanks for the help.

**Comment by jbremer** [comment]
Damn, thanks for letting us know the root origin of the issue! That's some bad stuff over there :)
