### ISSUE TITLE
Upgrading to 2.0 issue = ContextualVersionConflict

### ISSUE THREAD

**Issue by CQRuu** [cuckoosandbox/cuckoo#1528]
Hi!

Would need your advice here. I have a working cuckoo (2.0RC), and would like to upgrade to version 2.0. However, when I followed the guide to install cuckoo, it throws the error messages below whenever I ran cuckoo commands (I tried to install cuckoo on my host machine, as well as creating a virtual environment before running):

(env) cuckoo@mycomp:/opt/cuckoo_new/env/bin$ cuckoo --cwd ~/.cuckoo_new
Traceback (most recent call last):
  File "/opt/cuckoo_new/env/bin/cuckoo", line 7, in <module>
    from cuckoo.main import main
  File "/opt/cuckoo_new/env/lib/python2.7/site-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/opt/cuckoo_new/env/lib/python2.7/site-packages/cuckoo/auxiliary/__init__.py", line 6, in <module>
    from cuckoo.core.plugins import enumerate_plugins
  File "/opt/cuckoo_new/env/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 13, in <module>
    from cuckoo.common.config import config2
  File "/opt/cuckoo_new/env/lib/python2.7/site-packages/cuckoo/common/config.py", line 15, in <module>
    from cuckoo.common.objects import Dictionary
  File "/opt/cuckoo_new/env/lib/python2.7/site-packages/cuckoo/common/objects.py", line 19, in <module>
    from cuckoo.common.whitelist import is_whitelisted_domain
  File "/opt/cuckoo_new/env/lib/python2.7/site-packages/cuckoo/common/whitelist.py", line 6, in <module>
    from cuckoo.misc import cwd
  File "/opt/cuckoo_new/env/lib/python2.7/site-packages/cuckoo/misc.py", line 31, in <module>
    version = pkg_resources.require("Cuckoo")[0].version
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 1.9 (/Library/Python/2.7/site-packages), Requirement.parse('django==1.8.4'), set(['Cuckoo']))
(env) cuckoo@mycomp:/opt/cuckoo_new/env/bin$ 

There are multiple conflicts with my python packages: pymisp, django, httpreplay etc. May I know if there are any ways to avoid the conflict? I tried uninstalling the current python packages and installing the required versions, it shows a message but doesn't resolve the ContextualVersionConflict:

Found existing installation: Django 1.9
    Not uninstalling django at /Library/Python/2.7/site-packages, outside environment /opt/cuckoo_new/env/bin/..
Successfully installed django-1.8.4

Thanks!

**Comment by jbremer** [comment]
Hm. In the virtualenv you've installed `django==1.8.4` and you still get that? Kind of odd.

**Comment by jbremer** [comment]
Any update here @CQRuu ?

**Comment by CQRuu** [comment]
For each of the conflict, I removed the .dist-info or .egg-info package that was mentioned in the ContextualVersionConflicts.
 (eg. Django-1.9.dist-info/ at path /Library/Python/2.7/site-packages, tlslite_ng-0.6.0a3-py2.7.egg-info at path /Library/Python/2.7/site-packages). I ran the command  `cuckoo --cwd ~/.cuckoo_new` until there were no conflicts and it could work. thanks! :D

**Comment by jbremer** [comment]
Sounds about right, thanks for the feedback!
