### ISSUE TITLE
Cuckoo Development setup issues - Pillow-3.2.0 issue

### ISSUE THREAD

**Issue by zashraf1337** [cuckoosandbox/cuckoo#1529]
Hello,

I believe I have got all the dependencies needed, this is what happens when I try to 
run:

```
virtualenv ~/venvs/cuckoo-development
. ~/venvs/cuckoo-development/bin/activate
python setup.py develop | tee setup.develop.out
```
```
Searching for cffi>=1.4.1
Reading https://pypi.python.org/simple/cffi/
Best match: cffi 1.10.0
Downloading https://pypi.python.org/packages/5b/b9/790f8eafcdab455bcd3bd908161f802c9ce5adbf702a83aa7712fcc345b7/cffi-1.10.0.tar.gz#md5=2b5fa41182ed0edaf929a789e602a070
Processing cffi-1.10.0.tar.gz
Writing /tmp/easy_install-MV0BWy/cryptography-1.8.1/temp/easy_install-C8DScF/cffi-1.10.0/setup.cfg
Running cffi-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-MV0BWy/cryptography-1.8.1/temp/easy_install-C8DScF/cffi-1.10.0/egg-dist-tmp-NcN_sV
compiling '_configtest.c':
__thread int some_threadlocal_variable_42;

^[[31m
The following error has occurred while trying to install Cuckoo!
^[[0m
Traceback (most recent call last):
  File "setup.py", line 98, in do_setup
    setuptools.setup(**kwargs)

...

File "setup.py", line 64, in ask_supports_thread
    for line in open(os.path.join(cwd_private, "cwd", "hashes.txt"), "rb"):
  File "/usr/lib/python2.7/distutils/command/config.py", line 232, in try_compile
    self._compile(body, headers, include_dirs, lang)
  File "/usr/lib/python2.7/distutils/command/config.py", line 138, in _compile
    self.compiler.compile([src], include_dirs=include_dirs)
  File "/tmp/easy_install-i3tUSG/Pillow-3.2.0/mp_compile.py", line 41, in _mp_compile
TypeError: 'NoneType' object is not callable

```

**Comment by jbremer** [comment]
Please show the output without the `|tee` part.

**Comment by zashraf1337** [comment]
In the next run:
```
Running cryptography-1.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4H_EJq/cryptography-1.8.1/egg-dist-tmp-x__5Mq
Searching for cffi>=1.4.1
Reading https://pypi.python.org/simple/cffi/
Best match: cffi 1.10.0
Downloading https://pypi.python.org/packages/5b/b9/790f8eafcdab455bcd3bd908161f802c9ce5adbf702a83aa7712fcc345b7/cffi-1.10.0.tar.gz#md5=2b5fa41182ed0edaf929a789e602a070
Processing cffi-1.10.0.tar.gz
Writing /tmp/easy_install-4H_EJq/cryptography-1.8.1/temp/easy_install-R1MvJN/cffi-1.10.0/setup.cfg
Running cffi-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4H_EJq/cryptography-1.8.1/temp/easy_install-R1MvJN/cffi-1.10.0/egg-dist-tmp-y_W7i9
compiling '_configtest.c':
__thread int some_threadlocal_variable_42;

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -c _configtest.c -o _configtest.o
success!
removing: _configtest.c _configtest.o
compiling '_configtest.c':
int main(void) { __sync_synchronize(); return 0; }

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -c _configtest.c -o _configtest.o
x86_64-linux-gnu-gcc -pthread _configtest.o -o _configtest
success!
removing: _configtest.c _configtest.o _configtest

Installed /tmp/easy_install-4H_EJq/cryptography-1.8.1/cffi-1.10.0-py2.7-linux-x86_64.egg
Searching for pycparser

```
and then it comes to:
```
Installed /home/zashraf/venvs/cuckoo-development/lib/python2.7/site-packages/enum34-1.1.6-py2.7.egg
Searching for setuptools>=11.3
Reading https://pypi.python.org/simple/setuptools/
Best match: setuptools 35.0.2
Downloading https://pypi.python.org/packages/88/13/7d560b75334a8e4b4903f537b7e5a1ad9f1a2f1216e2587aaaf91b38c991/setuptools-35.0.2.zip#md5=c368b4970d3ad3eab5afe4ef4dbe2437
Processing setuptools-35.0.2.zip
Writing /tmp/easy_install-GiYcgr/setuptools-35.0.2/setup.cfg
Running setuptools-35.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-GiYcgr/setuptools-35.0.2/egg-dist-tmp-MwQQz1
^[[31m
The following error has occurred while trying to install Cuckoo!
^[[0m
Traceback (most recent call last):
  File "setup.py", line 98, in do_setup
    setuptools.setup(**kwargs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()

...
File "/home/zashraf/venvs/cuckoo-development/local/lib/python2.7/site-packages/pkg_resources.py", line 1477, in build_zipmanifest
    zfile = zipfile.ZipFile(path)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/usr/lib/python2.7/zipfile.py", line 231, in _EndRecData
    return _EndRecData64(fpin, -sizeEndCentDir, endrec)
  File "/usr/lib/python2.7/zipfile.py", line 173, in _EndRecData64
    if sig != stringEndArchive64Locator:
RuntimeError: maximum recursion depth exceeded in cmp

**Comment by jbremer** [comment]
Probably another `setuptools` issue, see also https://github.com/cuckoosandbox/cuckoo/issues/1518.

**Comment by jbremer** [comment]
Closed as per PM.

**Comment by zashraf1337** [comment]
Not resolved ... (was a misunderstanding in PM) the issue exists :)

**Comment by zashraf1337** [comment]
created - https://github.com/pypa/setuptools/issues/1027

**Comment by zashraf1337** [comment]
works fine if I manually do 
```
pip install -U setuptools==34.4.1
```
and then continue with 
```
python setup.py develop
```
