### ISSUE TITLE
Error while insert data into mongo db

### ISSUE THREAD

**Issue by arulraji** [cuckoosandbox/cuckoo#1530]
when i try to integrate malheur report generation in the reporting module. I get some following error while inserting data into mongodb 
(P.S json, html and malheur report generated successfully)
(cuckoo version 2.0.2)

2017-05-10 15:21:59,089 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 566, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 250, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 436, in _insert
    self.codec_options, sock_info)
InvalidDocument: Cannot encode object: set([])

Please give some suggestion to take forward the analysis successfully

**Comment by doomedraven** [comment]
convert your set to list and no problems

**Comment by arulraji** [comment]
if i disable the malheur report generation, mongo db insertion successfully happened. Still i need to convert the data from set to list?

**Comment by jbremer** [comment]
Yes, the problem is somewhere in your module ;)

**Comment by doomedraven** [comment]
inside of your malheur report generator script, search for `= set()` or something like that and at the end of the script just do `=list(X)` withoit see variables i can't say you exactly, but you should get the idea

**Comment by jbremer** [comment]
Any update here @arulraji ?
