### ISSUE TITLE
Vsphere ubuntu guest Powering off before analysis starting

### ISSUE THREAD

**Issue by WalterJia** [cuckoosandbox/cuckoo#1546]
2017-05-12 09:47:02,467 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo1, ip=192.168.1.12, monitor=latest, size=35210)
2017-05-12 09:47:03,375 [cuckoo.machinery.vsphere] INFO: Powering off virtual machine Linux_Sandbox_Ubuntu_Guest
2017-05-12 09:47:05,473 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/sg/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/home/sg/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis
    self.guest_manage(options)
  File "/home/sg/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 393, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/sg/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 455, in start_analysis
    self.upload_analyzer(monitor)
  File "/home/sg/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 362, in upload_analyzer
    self.determine_analyzer_path()
  File "/home/sg/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 350, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/home/sg/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 309, in post
    r = session.post(url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 425, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='192.168.1.12', port=8000): Max retries exceeded with url: /mkdtemp (Caused by <class 'httplib.BadStatusLine'>: '')

**Comment by doomedraven** [comment]
did you applied all linux fixes from my PRs?

**Comment by WalterJia** [comment]
Thanks for the quick reply. where is your PRs, can you give me the link and let me check,? thanks a lot.

**Comment by doomedraven** [comment]
there is many here in Pull request but just pushed all in one with a lot of linux analyzer improvements, you should apply many of them for correct work

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/pull/1545

**Comment by WalterJia** [comment]
I use the following command to install the cuckoo, you mean cuckoo2.0.2 doesn't include these changes #1545?
pip download cuckoo
pip install  Cuckoo-2.0.2.tar.gz

**Comment by doomedraven** [comment]
correct, not include you should apply them manually as if not you will get a lot of errors and crashes

**Comment by WalterJia** [comment]
Got it, given the setup I have installed, what should I do next step, can you give me some guidance, thanks a lot.

**Comment by WalterJia** [comment]
In case I make more mistake， I hope you can give me more information step by step, thanks a lot.

**Comment by doomedraven** [comment]
go to changed files in that PR and edit the corresponding files, there no more steps on it

**Comment by doomedraven** [comment]
but if you need to test few samples, feel free to use my setup https://linux.huntingmalware.com

**Comment by WalterJia** [comment]
Your work is very respected, I am very appreciate cover for me at the embarrassed moment, thank you very much,.
Let me try your solution, will let you know the update.

**Comment by doomedraven** [comment]
bear in mind, sh4/motorola still not supported architectures, but that one should be x32 or x64, let me know if you have any problem with that

**Comment by jbremer** [comment]
Let us know what you think of the PR @WalterJia! We'll be working on merging it to an upcoming Cuckoo version soon'ish :-)

**Comment by WalterJia** [comment]
I want to learn how many platforms are supported in cuckoo linux, the Linux sandbox supports the dynamic analysis and get the behavior for arm/mips samples?, thanks a lot.

**Comment by doomedraven** [comment]
All in which you can get running linux :p

**Comment by doomedraven** [comment]
well not only linux, but any *nix, as i have vms of *bsd in local setup

**Comment by doomedraven** [comment]
@WalterJia is this one is your sample? `d8d02704bd48437e3b9ce1e7efdbcb94 ` for some reason there some samples which bypass all checks %) and executes in incorrect vm, i never was able to reproduce that, so if yes how you uploaded sample? here is correct analysis https://linux.huntingmalware.com/analysis/2870/summary/  is Gafgyt

**Comment by WalterJia** [comment]
Sounds really cool, about arm platform, I want to known whether the systemtap tool can trace the behavior in qemu-arm system, as far as I know the systemtap only support linux because of the dgbsys limitation, could you please give me more information about the linux-arm guest installation and deploment?, thanks.

**Comment by doomedraven** [comment]
current systemtap works only for x32, so you would need to patch/port it, but there another ways to get behavior from the arches ;)

**Comment by doomedraven** [comment]
that is funny your samples bypass sample check, to pick the correct vm, check 
```
Type	ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped
```
```
Name	Label	Started On	Shutdown On
armel	armel	2017-05-12 22:24:10	2017-05-12 22:29:50
```

should be x32, i will get a look tomorrow how it possible, bcz with my samples it never happened

**Comment by WalterJia** [comment]
have a good weekend, very glad to talk with you.

**Comment by doomedraven** [comment]
you too :)
