### ISSUE TITLE
Failure in AnalysisManager.run KeyError: 'SYSTEMDRIVE'

### ISSUE THREAD

**Issue by ofekbgu** [cuckoosandbox/cuckoo#1549]
Hello 
I have few problems with using cuckoo and maybe they are all related to each other.
1. The main problem: when I trying to analysis it throws me : 
`2017-05-14 15:07:57,235 [cuckoo.core.startup] INFO: Updated running task ID 5 status to failed_analysis
2017-05-14 15:07:57,252 [cuckoo.core.startup] INFO: Updated running task ID 4 status to failed_analysis
2017-05-14 15:07:57,264 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-05-14 15:07:58,423 [cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2017-05-14 15:07:58,440 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-05-14 15:07:59,533 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "doc.txt" (task #6, options "procmemdump=yes,route=none")
2017-05-14 15:07:59,571 [cuckoo.core.scheduler] INFO: Task #6: acquired machine vm1_ubuntu1604 (label=vm1_ubuntu1604)
2017-05-14 15:07:59,578 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 1424 (interface=vboxnet0, host=192.168.56.101, pcap=/home/ofekisra/.cuckoo/storage/analyses/6/dump.pcap)
2017-05-14 15:08:00,594 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "doc.txt" (task #7, options "procmemdump=yes,route=none")
2017-05-14 15:08:00,630 [cuckoo.core.scheduler] INFO: Task #7: acquired machine vm2_ubuntu1604 (label=vm2_ubuntu1604)
2017-05-14 15:08:00,640 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 1524 (interface=vboxnet0, host=192.168.56.102, pcap=/home/ofekisra/.cuckoo/storage/analyses/7/dump.pcap)
2017-05-14 15:08:04,415 [cuckoo.core.guest] INFO: Starting analysis on guest (id=vm1_ubuntu1604, ip=192.168.56.101)
2017-05-14 15:08:06,073 [cuckoo.core.guest] INFO: Starting analysis on guest (id=vm2_ubuntu1604, ip=192.168.56.102)
2017-05-14 15:08:09,494 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=vm1_ubuntu1604, ip=192.168.56.101)
2017-05-14 15:08:11,065 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 393, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 453, in start_analysis
    self.upload_analyzer(monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 360, in upload_analyzer
    self.determine_analyzer_path()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 340, in determine_analyzer_path
    systemdrive = "%s\\" % self.environ["SYSTEMDRIVE"]
KeyError: 'SYSTEMDRIVE'

`
2. when I want to analysis with the web server or with submit command it does not start until I'm running "cuckoo" command in other terminal. specific in the web server gui it's stuck on "pending"   

Thanks a lot!

**Comment by doomedraven** [comment]
are you trying to run linux vm? if yes, then see fix here https://github.com/cuckoosandbox/cuckoo/pull/1545

**Comment by ofekbgu** [comment]
yes my host and the guests are Ubuntu1604.... thanks I'm checking it now

**Comment by doomedraven** [comment]
then you should apply some fixes for analyzer and some other files for correct work, that will be merged once, but i don't expect it soon

**Comment by ahroobe** [comment]
I have same problem in both Ubuntu 14 64bit and Debian 8 32bit. Is there expected date to merge? or... should i just look at your revision code and change code myself and rebuild with setup.py?

**Comment by doomedraven** [comment]
yes, that would be the faster solution

**Comment by jbremer** [comment]
We're working on integrating the Linux PR and more Linux-related things, stay tuned :)

**Comment by jbremer** [comment]
This has been resolved since `2.0.4` (or earlier), please upgrade. Closing as resolved. Thanks!
