### ISSUE TITLE
UnicodeEncodeError in API task list

### ISSUE THREAD

**Issue by lolnate** [cuckoosandbox/cuckoo#1553]
I'm receiving the following error when getting a task list via the API:

```
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/apps/api.py", line 244, in tasks_list
    task["target"] = task["target"].decode("latin-1")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u1ebf' in position 27: ordinal not in range(128)
```

In the current code base, this occurs here: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/apps/api.py#L237

I was able to circumvent the problem by placing a try/except block around the decode line and ignore failures. This seems to work fine and returns the task list as expected via the API. My current code looks like this:

```
try:
    task["target"] = task["target"].decode("latin-1")
except UnicodeEncodeError:
    log.warning('UnicodeEncodeError caught when parsing tasks.')
```

**Comment by doomedraven** [comment]
can you post filename?

**Comment by jbremer** [comment]
Something unicode :-) Will take a look in a bit, thanks for reporting!

**Comment by Magicked** [comment]
Unicode is always fun! :)

Sample name is: `/tmp/cuckoo-tmp/tmpSnN_Mf/K\u1ebf ho\u1ea1ch t\u0103ng l\u01b0\u01a1ng, ngh\u1ec9 T\u1ebft n\u0103m 2017.doc`

The real name should be: `Kế hoạch tăng lương, nghỉ Tết năm 2017.doc`

**Comment by jbremer** [comment]
This issue has now been fixed in the commit above. This will be taken into the next alpha or stable release! :)

**Comment by jbremer** [comment]
In the meantime I'm going to close this issue, thanks again!

**Comment by jbremer** [comment]
Release as part of `2.0.4a3`!
