### ISSUE TITLE
reboot analysis error

### ISSUE THREAD

**Issue by rich7mcs** [cuckoosandbox/cuckoo#1562]
Hi,
I am trying to use cuckoo to perform reboot analyses in tasks previously analyzed correctly. So the first analyses of EXE files is performed without problems, but when I try to use the Reboot module(i.e., using the cuckoo API --> $curl http://localhost:8090/tasks/reboot/1), I get the following error: 

Error performing callback 'prepare_guest' on auxiliary module 'Reboot'

I have updated the cuckoo agent in the guests to the version 0.7.

Could you help me to fix this error. 

This is the log of the reboot analysis:

`2017-05-16 12:51:21,317 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-05-16 12:51:21,323 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-05-16 12:52:05,884 [cuckoo.core.scheduler] DEBUG: Processing task #92
2017-05-16 12:52:05,891 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "sample1.exe" (task #92, options "")
2017-05-16 12:52:06,024 [cuckoo.core.scheduler] INFO: Task #92: acquired machine cuckoo5 (label=cuckoo5)
2017-05-16 12:52:06,024 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Reboot
2017-05-16 12:52:06,029 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 9811 (interface=vboxnet0, host=192.168.56.105, pcap=/home/cuckoo/.cuckoo/storage/analyses/92/dump.pcap)
2017-05-16 12:52:06,029 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2017-05-16 12:52:06,107 [cuckoo.machinery.virtualbox] DEBUG: Starting vm cuckoo5
2017-05-16 12:52:06,354 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine cuckoo5 to its current snapshot
2017-05-16 12:52:12,279 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo5, ip=192.168.56.105)
2017-05-16 12:52:13,282 [cuckoo.core.guest] DEBUG: cuckoo5: not ready yet
2017-05-16 12:52:14,285 [cuckoo.core.guest] DEBUG: cuckoo5: not ready yet
2017-05-16 12:52:15,281 [cuckoo.core.guest] DEBUG: cuckoo5: not ready yet socket
2017-05-16 12:52:17,285 [cuckoo.core.guest] DEBUG: cuckoo5: not ready yet
2017-05-16 12:52:18,288 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo5, ip=192.168.56.105)
2017-05-16 12:52:18,300 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo5, ip=192.168.56.105, monitor=latest, size=3821000)
2017-05-16 12:52:18,717 [cuckoo.auxiliary.reboot] INFO: Preparing task #92 for a reboot analysis..
2017-05-16 12:52:18,720 [cuckoo.core.plugins] ERROR: Error performing callback 'prepare_guest' on auxiliary module 'Reboot'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 142, in callback
    getattr(module, "cb_%s" % name, default)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 57, in cb_prepare_guest
    self._push_dropped_files(analysis_path)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 50, in _push_dropped_files
    self.guest_manager.post("/store", files=files, data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 310, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.105:8000/store
2017-05-16 12:52:19,466 [cuckoo.core.guest] DEBUG: cuckoo5: analysis still processing
2017-05-16 12:52:19,729 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2017-05-16 12:52:20,472 [cuckoo.core.guest] DEBUG: cuckoo5: analysis still processing
2017-05-16 12:52:21,477 [cuckoo.core.guest] DEBUG: cuckoo5: analysis still processing`

**Comment by craigdods** [comment]
Just to comment, I'm seeing the same issue in my setup. Can replicate it via the Web GUI as well.
`2017-05-24 12:14:14,390 [cuckoo.auxiliary.reboot] INFO: Preparing task #27 for a reboot analysis..
2017-05-24 12:14:16,151 [cuckoo.core.plugins] ERROR: Error performing callback 'prepare_guest' on auxiliary module 'Reboot'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 142, in callback
    getattr(module, "cb_%s" % name, default)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 57, in cb_prepare_guest
    self._push_dropped_files(analysis_path)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 50, in _push_dropped_files
    self.guest_manager.post("/store", files=files, data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 310, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
`

**Comment by jbremer** [comment]
I have an idea.. perhaps the target directories where the Reboot module wants to store data don't exist yet. Will have to investigate later.

**Comment by rauvolaj** [comment]
Found this issue through a search, so I figured I'd post my same error. This was done through the web GUI. In my situation I had performed the original analysis then chose the "reboot analysis" link from within the summary page.

2017-08-03 10:57:02,523 [cuckoo.auxiliary.reboot] INFO: Preparing task #7 for a reboot analysis..
2017-08-03 10:57:58,775 [cuckoo.core.plugins] ERROR: Error performing callback 'prepare_guest' on auxiliary module 'Reboot'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 142, in callback
    getattr(module, "cb_%s" % name, default)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 57, in cb_prepare_guest
    self._push_dropped_files(analysis_path)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 50, in _push_dropped_files
    self.guest_manager.post("/store", files=files, data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 310, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.101:8000/store

**Comment by muradkose** [comment]
I had the same problem, but resolved it by changing the file name which was too long and crappy characters,

**Comment by likescam** [comment]
I have the same error log, When performed Reboot Analysic, cuckoo did not start the VM, but its restore VM to the lasted snapshot, so the result is VM did not have the state that runing malware before :(
Here is the error log: I use the lasted Agent v0.11
Can anyone help me?
```
2021-01-18 17:01:53,607 [cuckoo.auxiliary.reboot] INFO: Preparing task #124 for a reboot analysis..
2021-01-18 17:02:15,175 [cuckoo.core.plugins] ERROR: Error performing callback 'prepare_guest' on auxiliary module 'Reboot'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 145, in callback
    getattr(module, "cb_%s" % name, default)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 57, in cb_prepare_guest
    self._push_dropped_files(analysis_path)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 50, in _push_dropped_files
    self.guest_manager.post("/store", files=files, data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 339, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://10.10.10.5:8000/store
2021-01-18 17:02:16,277 [cuckoo.core.resultserver] DEBUG: Task #124: live log analysis.log initialized.
2021-01-18 17:02:17,991 [cuckoo.core.resultserver] DEBUG: Task #124 is sending a BSON stream
2021-01-18 17:02:19,372 [cuckoo.core.resultserver] DEBUG: Task #124: File upload for 'shots/0001.jpg'
```
