### ISSUE TITLE
Error 'No JSON object could be decoded'

### ISSUE THREAD

**Issue by bumbastik777** [cuckoosandbox/cuckoo#1563]
log:
Cuckoo Sandbox 2.0.2
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!
2017-05-16 15:26:31,568 [cuckoo.core.startup] INFO: Rescheduled task with ID 9 and target /tmp/cuckoo-tmp/tmpj44SF2/RemoveWAT1.exe: task #10
2017-05-16 15:26:33,424 [cuckoo.core.startup] INFO: Rescheduled task with ID 8 and target /tmp/cuckoo-tmp/tmpjndQUx/база НЗФ 2.exe: task #11
2017-05-16 15:26:33,808 [cuckoo.core.startup] INFO: Rescheduled task with ID 7 and target /home/sandbox/Загрузки/RemoveWAT1.exe: task #12
2017-05-16 15:26:33,866 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-05-16 15:26:34,979 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-05-16 15:26:35,002 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-05-16 15:26:36,192 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "RemoveWAT1.exe" (task #10, options "procmemdump=yes,route=none")
2017-05-16 15:26:36,457 [cuckoo.core.scheduler] INFO: Task #10: acquired machine cuckoo1 (label=win7_x64)
2017-05-16 15:26:36,470 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 13775 (interface=vboxnet0, host=192.168.56.101, pcap=/home/sandbox/.cuckoo/storage/analyses/10/dump.pcap)
2017-05-16 15:26:44,048 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2017-05-16 15:26:48,110 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo1, ip=192.168.56.101)
2017-05-16 15:27:02,325 [cuckoo.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label win7_x64 to path /home/sandbox/.cuckoo/storage/analyses/10/memory.dmp
2017-05-16 15:27:07,804 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 393, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 450, in start_analysis
    self.query_environ()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 335, in query_environ
    self.environ = self.get("/environ").json()["environ"]
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by jbremer** [comment]
Hm, odd. Could you please run an analysis with the `sniffer.debug=0` option enabled and share the PCAP?

**Comment by bumbastik777** [comment]
How or where i can enable `sniffer.debug=0` option?

**Comment by jbremer** [comment]
If you do `cuckoo submit -o sniffer.debug=1 file.exe` (yes, `1`, not `0`). Thanks!

**Comment by aida1515** [comment]
Hello.
I have this problem too.
Here is an output of the error:

 ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 393, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 450, in start_analysis
    self.query_environ()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 335, in query_environ
    self.environ = self.get("/environ").json()["environ"]
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I enabled the sniffer.debug=0 option.
Could you please tell where I can find the PCAP file.

**Comment by aida1515** [comment]
Is there any information regarding this issue?

**Comment by jbremer** [comment]
Closing issue for lack of additional information. Most likely a setup issue with the Agent on the Guest. Please reopen issue if you have the `dump.pcap` file for me, which you can find at `$CWD/storage/analyses/task_id/dump.pcap`. Thanks!
