### ISSUE TITLE
sqlite3 error when running webserver

### ISSUE THREAD

**Issue by jtingkir** [cuckoosandbox/cuckoo#1567]
I keep getting this error when running cuckoo web runserver.
some information:
1. I'm running it on linux mint 17.3 (ubuntu 14.04).
2. running cuckoo on virtual env.
3. I've installed mongodb and not changing database connection on conf. 
4. the cwd, virtualenv, and mongodb "data/db" is now on the same directory ("named cuckoo_linux") in an NTFS partition. 
5. The funny thing is I manage to get it to work yesterday, and it fail again today. Although I moved /data/db to another director, It could probably be the cause. But I've tried moving it back, still not working.

any suggestion is greatly appreciated. Thank you.
```
Traceback (most recent call last):
  File "/media/aldo/Data/cuckoo_linux/venv/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.2', 'console_scripts', 'cuckoo')()
  File "/media/aldo/Data/cuckoo_linux/venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/media/aldo/Data/cuckoo_linux/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/media/aldo/Data/cuckoo_linux/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/media/aldo/Data/cuckoo_linux/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/aldo/Data/cuckoo_linux/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/media/aldo/Data/cuckoo_linux/venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/media/aldo/Data/cuckoo_linux/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 488, in web
    Database().connect()
  File "/media/aldo/Data/cuckoo_linux/venv/local/lib/python2.7/site-packages/cuckoo/core/database.py", line 446, in connect
    self._create_tables()
  File "/media/aldo/Data/cuckoo_linux/venv/local/lib/python2.7/site-packages/cuckoo/core/database.py", line 454, in _create_tables
    "Unable to create or connect to database: %s" % e
cuckoo.common.exceptions.CuckooDatabaseError: Unable to create or connect to database: (sqlite3.OperationalError) unable to open database file
```

**Comment by jtingkir** [comment]
I'm pretty convinced that setting up cwd in NTFS is the root cause. I'm moving everything (not just mongodb) back to linux partition and it run just fine.

sorry for the trouble.
