### ISSUE TITLE
Attribute error when run web runserver with cuckoo on elasticsearch

### ISSUE THREAD

**Issue by MikeChenX** [cuckoosandbox/cuckoo#1569]
Hi,Has anyone seen the error?
My elasticsearch configuration in reporting.conf：

```
[elasticsearch]
enabled = yes
hosts = 127.0.0.1:9200
timeout = 300
calls = no
index = cuckoo
index_time_pattern = yearly
cuckoo_node = es-node-n1
```

When execute ”python /opt/cuckoo/web/manage.py runserver“，get that：
```
Traceback (most recent call last):
  File "./web/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.5-py2.7.egg/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.5-py2.7.egg/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.5-py2.7.egg/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.5-py2.7.egg/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.5-py2.7.egg/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/cuckoo/web/web/settings.py", line 33, in <module>
    if cfg.elasticsearch.get("enabled"):
AttributeError: Config instance has no attribute 'elasticsearch'
```
How to solve this problem?

**Comment by SparkyNZL** [comment]
what version of ES are you running and what is the version of Cuckoo ?

**Comment by jbremer** [comment]
This is indeed an older version of Cuckoo. Please upgrade to one of our latest versions first and we can go from there. Closing issue. Thanks!
