### ISSUE TITLE
404 on clicking "report" after analysis

### ISSUE THREAD

**Issue by BrandonEckert** [cuckoosandbox/cuckoo#1571]
Good morning, I just setup a new cuckoo sandbox. Everything loads successfully, and I am able to analyze a file. However, once the analysis is completed, and I click to view the report...I get a 404 error. Also, I do not see any recent analysis.  When I SSH into my sandbox, and goto ~/.cuckoo/storage/analyses/ I see all of the reports. Any ideas?

**Comment by doomedraven** [comment]
no logs no ideas

**Comment by BrandonEckert** [comment]
Sorry about that, attached are the logs for my last analysis.
Also, I do notice an error on the SingleFile for generating PDFs. I did run pip install weazyprint and have the module.  Also, I tried with and without generating a PDF enabled.
[log.txt](https://github.com/cuckoosandbox/cuckoo/files/1008547/log.txt)

**Comment by doomedraven** [comment]
can you execute cuckoo `cuckoo -d` and provide log after analysis, also as cuckoo version, thanks

**Comment by BrandonEckert** [comment]
Here you go. I ran cuckoo -d web runserver 0.0.0.0:8000 as an fyi
[log.txt](https://github.com/cuckoosandbox/cuckoo/files/1008695/log.txt)

**Comment by BrandonEckert** [comment]
Sorry, use this one.
[log.txt](https://github.com/cuckoosandbox/cuckoo/files/1008700/log.txt)

**Comment by doomedraven** [comment]
Awesome quantity of logs <3 really :)

Did you see this ? 

ERROR: Error processing task #8: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration

**Comment by SparkyNZL** [comment]
The report that you are looking up, did it give you a Bson error when it was being processed ? (you can reprocess the item with cuckoo -d process -r <sample number> )? if so , re-run the sample with a shorter timeout like 60 seconds. The issue is (especially if you are running up ransomware) that the BSON document exceeds the maximum , it still says the samples is reported but in fact it causes an error in MongoDB and the item actually never fully populates. Please have a look at the other "Issues" BSON exceeds 

Hope this helps

**Comment by vikaskarunakaran** [comment]
I have configured ubuntu 17.10 guest with virtualbox for ELF analysis. I am able to ping form host to guest and guest to host with vboxnet0. Result server IP: 192.168.56.1 and guest IP: 192.168.56.104.

While analysis the VM closes as soon as it starts for and gives a 404 error. But all my other Windows Guest Analysis are running properly.

**Comment by vikaskarunakaran** [comment]
2018-02-28 11:53:52,379 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
[2018-02-28 11:54:20] Processing task #33
[2018-02-28 11:54:20] Starting analysis of FILE "xx64" (task #33, options "procmemdump=yes,route=none")
2018-02-28 11:54:20,140 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "xx64" (task #33, options "procmemdump=yes,route=none")
[2018-02-28 11:54:20] Task #33: acquired machine ubuntu (label=ubuntu_17_x64)
2018-02-28 11:54:20,185 [cuckoo.core.scheduler] INFO: Task #33: acquired machine ubuntu (label=ubuntu_17_x64)
[2018-02-28 11:54:20] Started sniffer with PID 5172 (interface=vboxnet0, host=192.168.56.104)
2018-02-28 11:54:20,192 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 5172 (interface=vboxnet0, host=192.168.56.104)
[2018-02-28 11:54:20] Started auxiliary module: Sniffer
[2018-02-28 11:54:20] Starting vm ubuntu_17_x64
[2018-02-28 11:54:20] Restoring virtual machine ubuntu_17_x64 to base
[2018-02-28 11:54:24] Starting analysis on guest (id=ubuntu, ip=192.168.56.104)
2018-02-28 11:54:24,101 [cuckoo.core.guest] INFO: Starting analysis on guest (id=ubuntu, ip=192.168.56.104)
[2018-02-28 11:54:25] ubuntu: not ready yet
[2018-02-28 11:54:26] ubuntu: not ready yet
[2018-02-28 11:54:27] ubuntu: not ready yet
[2018-02-28 11:54:28] Guest is running Cuckoo Agent 0.8 (id=ubuntu, ip=192.168.56.104)
2018-02-28 11:54:28,125 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=ubuntu, ip=192.168.56.104)
[2018-02-28 11:54:28] Uploading analyzer to guest (id=ubuntu, ip=192.168.56.104, monitor=latest, size=30538)
[2018-02-28 11:54:28] Stopped auxiliary module: Sniffer
[2018-02-28 11:54:30] Successfully generated memory dump for virtual machine with label ubuntu_17_x64 to path /home/cuckoo/.cuckoo/storage/analyses/33/memory.dmp
2018-02-28 11:54:30,275 [cuckoo.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label ubuntu_17_x64 to path /home/cuckoo/.cuckoo/storage/analyses/33/memory.dmp
[2018-02-28 11:54:30] Stopping vm ubuntu_17_x64
[2018-02-28 11:54:32] Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 698, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 499, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 483, in start_analysis
    self.upload_analyzer(monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 390, in upload_analyzer
    self.determine_analyzer_path()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 368, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 330, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.104:8000/mkdtemp
2018-02-28 11:54:32,037 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 698, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 499, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 483, in start_analysis
    self.upload_analyzer(monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 390, in upload_analyzer
    self.determine_analyzer_path()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 368, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 330, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.104:8000/mkdtemp

**Comment by vikaskarunakaran** [comment]
Ping requests from guest to host

vikas@home:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:76:dd:19 brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.104/24 brd 192.168.56.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe76:dd19/64 scope link 
       valid_lft forever preferred_lft forever
vikas@home:~$ ping 192.168.56.1
PING 192.168.56.1 (192.168.56.1) 56(84) bytes of data.
64 bytes from 192.168.56.1: icmp_seq=1 ttl=64 time=0.105 ms
64 bytes from 192.168.56.1: icmp_seq=2 ttl=64 time=0.135 ms
64 bytes from 192.168.56.1: icmp_seq=3 ttl=64 time=0.303 ms
64 bytes from 192.168.56.1: icmp_seq=4 ttl=64 time=0.104 ms
64 bytes from 192.168.56.1: icmp_seq=5 ttl=64 time=0.139 ms
64 bytes from 192.168.56.1: icmp_seq=6 ttl=64 time=0.065 ms
64 bytes from 192.168.56.1: icmp_seq=7 ttl=64 time=0.346 ms
64 bytes from 192.168.56.1: icmp_seq=8 ttl=64 time=0.135 ms
^Z
[2]+  Stopped                 ping 192.168.56.1
vikas@home:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=43 time=40.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=43 time=40.5 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=43 time=40.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=43 time=40.3 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=43 time=41.0 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=43 time=40.2 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=43 time=40.3 ms
^Z
[3]+  Stopped                 ping 8.8.8.8

**Comment by doomedraven** [comment]
ping != ping to agent, you should test always connectivity with `curl http://vm_ip:8000`

did you start agent as root?
```
2018-02-28 11:54:32,037 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 698, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 499, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 483, in start_analysis
    self.upload_analyzer(monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 390, in upload_analyzer
    self.determine_analyzer_path()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 368, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 330, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.104:8000/mkdtemp
```

**Comment by vikaskarunakaran** [comment]
cuckoo@ubuntu:~$ curl http://192.168.56.104:8000
{"message": "Cuckoo Agent!", "version": "0.8", "features": ["execpy", "pinning", "logs", "largefile", "unicodepath"]}

And, when I added agent.py to sudo it works

Thanks

**Comment by vikaskarunakaran** [comment]
Now a different issue as happened.

After the analysis id done, html report is not displayed in dashboard.

The HTML file is available in storage but not showing the task ID in dashboard.

Attaching new log file
[cuckoo.log](https://github.com/cuckoosandbox/cuckoo/files/1766671/cuckoo.log)

**Comment by doomedraven** [comment]
that is normal what it's not shown as it has mongo problems, can you share hash/sample?

```
2018-02-28 15:51:29,032 [cuckoo.core.plugins] WARNING: The reporting module "SingleFile" returned the following error: The weasyprint library hasn't been installed on your Operating System and as such we can't generate a PDF report for you. You can install 'weasyprint' manually by running 'pip install weasyprint' or by compiling and installing package yourself.
2018-02-28 15:51:29,223 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 614, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 236, in run
    chunk_id = self.db.calls.insert(to_insert)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1926, in insert
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 436, in _insert
    self.codec_options, sock_info)
InvalidStringData: strings in documents must be valid UTF-8: '\x8d\x0c\\u028AQ\x04\x88\x10\x80y\x07\xcc\xf4\xef\xe2'
```

**Comment by vikaskarunakaran** [comment]
@doomedraven 
You can download it from here http://download1584.mediafire.com/7ytuff8awnbg/gg9lwz1q2oab8ww/http-packed.7z

Password: infected

sample md5: 53afdbd7ce13bc783175848e828088b6

**Comment by doomedraven** [comment]
@jbremer mongo problem confirmed on https://linux.huntingmalware.com/analysis/12568/summary/

**Comment by doomedraven** [comment]
```
{'status': '', 'raw': 'Wed Feb 28 17:03:23 2018.748482 cp@b7734cf9[1161] write(7, "\\215\\f\\u028AQ\\004\\210\\020\\200y\\a\\314\\364\\357\\342", 131072) = 131072\n', 'api': 'write', 'return_value': '131072', 'instruction_pointer': 'b7734cf9', 'time': datetime.datetime(2018, 2, 28, 17, 3, 23, 748482), 'process_name': 'cp', 'pid': 1161, 'arguments': {'p2': '131072', 'p0': '7', 'p1': '\x8d\x0c\\u028AQ\x04\x88\x10\x80y\x07\xcc\xf4\xef\xe2'}}
```
