### ISSUE TITLE
report.html not found 

### ISSUE THREAD

**Issue by Roucuck** [cuckoosandbox/cuckoo#1573]
when i run cuckoo it execute the virtualmachine but it doesen't close and the analyse don't stop some report are generated json , memor.dump,dump.mitm,dump.pcap and am enabled the htmlreport in the reporting.conf file  but it doesen't generate a html report  
this is my log :+1: 

2017-05-18 01:18:46,459 [lib.cuckoo.core.scheduler] INFO: Task #16: acquired machine Xp (label=Xp)
2017-05-18 01:18:46,533 [modules.auxiliary.mitm] INFO: Started mitm interception with PID 5098 (ip=192.168.56.1, port=50000).
2017-05-18 01:18:46,634 [lib.cuckoo.core.plugins] WARNING: Unable to start auxiliary module sniffer: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
2017-05-18 01:18:55,978 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=Xp, ip=192.168.56.102)
2017-05-18 01:19:16,846 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/sandbox/Téléchargements/cuckoo/lib/cuckoo/core/scheduler.py", line 519, in run
    self.launch_analysis()
  File "/home/sandbox/Téléchargements/cuckoo/lib/cuckoo/core/scheduler.py", line 436, in launch_analysis
    machinery.dump_memory(self.machine.label, dump_path)
  File "/home/sandbox/Téléchargements/cuckoo/modules/machinery/virtualbox.py", line 274, in dump_memory
    "with label %s to path %s", label, path)
  File "/usr/lib/python2.7/logging/__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/home/sandbox/Téléchargements/cuckoo/lib/cuckoo/core/log.py", line 42, in emit
    f.write("%s\n" % self.format(record))
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)

**Comment by Roucuck** [comment]
my agent.py in my virtualmachine :  
![image](https://cloud.githubusercontent.com/assets/27987230/26182205/e6f92730-3b76-11e7-889e-71f0b9daf3d0.png)
any help please

**Comment by jbremer** [comment]
Interesting! Well, the problem seems related to your unicode username - I'll have a more in-depth look later. Thanks for reporting :)

**Comment by Roucuck** [comment]
ok so there is no solution  to solve my problem now ?

**Comment by jbremer** [comment]
Not calling the Cuckoo directory `Téléchargements` will go a long way. Also upgrading to the latest version (see also our official blogpost) might help ;-)

**Comment by jbremer** [comment]
Please find the two commits above - those should fix the issues for now. If similar issues present themself, do let us know. You'll be able to find these commits in the next alpha or stable release (although as I see you were still running `2.0-rc2` or older). Closing this issue as resolved.
