### ISSUE TITLE
 The 'scapy==2.3.2' distribution was not found and is required by Cuckoo

### ISSUE THREAD

**Issue by xorpierre** [cuckoosandbox/cuckoo#1597]
Fresh server, Debian Jessie, was following docs, installed all python deps and cuckoo via pip.
Upon issuing cuckoo -d for the first time I get:

Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'scapy==2.3.2' distribution was not found and is required by Cuckoo

Scarpy 2.3.3 is installed, maybe it requires 2.3.2 as it seems hardcoded?

**Comment by doomedraven** [comment]
try specified version

**Comment by xorpierre** [comment]
true, didnt know pip can do that, but now I hang here

pkg_resources.DistributionNotFound: The 'requests[security]==2.13.0' distribution was not found and is required by Cuckoo

and

pip install requests[security]==2.13.0
Downloading/unpacking requests[security]==2.13.0
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB): 584kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 552, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 426, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range

**Comment by xorpierre** [comment]
I managed to install all deps after trying around a bit ;)
Should be included in the cuckoo install though

**Comment by doomedraven** [comment]
it is included in installer https://github.com/cuckoosandbox/cuckoo/blob/master/setup.py#L197
