### ISSUE TITLE
Failed to run the reporting module: MongoDB

### ISSUE THREAD

**Issue by craigdods** [cuckoosandbox/cuckoo#1598]
Issue has cropped up this morning and is even occurring on files that it had previously analyzed successfully.

Trace is here - what can I upload to assist?

`2017-05-23 12:20:09,271 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 566, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 250, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
`

**Comment by doomedraven** [comment]
can you provide sample for test it ?

**Comment by craigdods** [comment]
I've been using 84c82835a5d21bbcf75a61706d8ab549 if you've got it already. I can upload it again shortly if you can't find it

**Comment by craigdods** [comment]
hxxps://transfer.sh/PnDIl/CYBERed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa.EXE

change the xx to tt (of course)

**Comment by SparkyNZL** [comment]
If you read the error it is because the BSON document is too large. This is fairly common with Ransomware where a LOT of files are being changed . What you can do is cut the time the VM is running for back to say 60 seconds. This how ever will limit the amount of information collected, 

If you are running the WGUI you will also see a 404 when you try and view the report as the information never makes it into MongoDB

"DocumentTooLarge: BSON document too large (18693693 bytes) - the connected server supports BSON document sizes up to 16777216 bytes."

essentially if your capture is over 16megs is size it will fail.

**Comment by JReming85** [comment]
Its a MongoDB limitation, not on cuckoo.

The only thing they could do is separate the sections of I think either memory or processing into their own smaller blobs.

Last time I had cuckoo installed and ran into this problem I saw they were looking into it with no ETA (around a year ago) and currently the only way to resolve it is cut out some of the larger stuff from your reports or limit run time.

**Comment by ChenJhua** [comment]
I also have this problem, can you elaborate on how to solve it? Thanks

**Comment by doomedraven** [comment]
you can do search in issues and found my fix for this

**Comment by ChenJhua** [comment]
I'm sorry, I don't know how to find this problem. Can you tell me the link? Thanks

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/issues?utf8=✓&q=mongo+


<img width="444" alt="captura de pantalla 2018-09-12 a las 11 18 41" src="https://user-images.githubusercontent.com/1856495/45415302-a4643d00-b67d-11e8-85bb-5f6bee527091.png">

**Comment by ChenJhua** [comment]
The solution is not very good. Thank you for your help. Thanks

**Comment by doomedraven** [comment]
oka
