### ISSUE TITLE
Cuckoo Package: 2.0.3a5 Web Process crash

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1604]
This is a weird one, but when ever i resize the terminal window which i have the web process running in crashes

-------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 9, in <module>
    load_entry_point('Cuckoo==2.0.3a5', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 530, in web
    ("cuckoo",) + args
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/management/commands/runserver.py", line 49, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/management/commands/runserver.py", line 88, in handle
    self.run(**options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/core/management/commands/runserver.py", line 97, in run
    autoreload.main(self.inner_run, None, options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/utils/autoreload.py", line 325, in main
    reloader(wrapped_main_func, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/utils/autoreload.py", line 296, in python_reloader
    exit_code = restart_with_reloader()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.4-py2.7.egg/django/utils/autoreload.py", line 282, in restart_with_reloader
    exit_code = os.spawnve(os.P_WAIT, sys.executable, args, new_environ)
  File "/usr/lib/python2.7/os.py", line 575, in spawnve
    return _spawnvef(mode, file, args, env, execve)
  File "/usr/lib/python2.7/os.py", line 548, in _spawnvef
    wpid, sts = waitpid(pid, 0)
OSError: [Errno 4] Interrupted system call

-----------------------------------------------------------------------------------------------------------------

**Comment by jbremer** [comment]
In this case I don't think we can do much. Sorry, going to have to close it. Thanks for the feedback, though.
