### ISSUE TITLE
Quick fix for those with capstone issues

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#1617]
Error:
~~~
The following error has occurred while trying to install Cuckoo!

Traceback (most recent call last):
  File "setup.py", line 90, in do_setup
    setuptools.setup(**kwargs)
  File "/usr/lib/python2.7/distutils/core.py", line 166, in setup
    raise SystemExit, "error: " + str(msg)
SystemExit: error: Setup script exited with error: SandboxViolation: mkdir('/usr/lib/python2.7/dist-packages/capstone', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

Make sure that you've installed all requirements for Cuckoo 
to be installed properly! Please refer to our documentation: 
https://cuckoo.sh/docs/installation/host/requirements.html

Once you have triple checked that all dependencies have been 
installed but Cuckoo still fails, please feel free to reach 
out to us on IRC / email / Github!
~~~

cd build (or wherever):
~~~
wget https://pypi.python.org/packages/e7/29/e9ad2a12c38f19e9ca8aff05122e5b9e271da6ecbfb6c4e20aee381b49ff/capstone-3.0.4.tar.gz
tar xvf capstone-3.0.4.tar.gz
cd capstone-3.0.4
python ./setup.py build
sudo python ./setup.py install
~~~
Painless!

**Comment by jbremer** [comment]
This is what you got when doing `python setup.py install` on the Cuckoo repository? Odd.

**Comment by DigiAngel** [comment]
Aye...after git pulling:
~~~
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    analyzer
	modified:   cuckoo/data-private/cwd/hashes.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	cuckoo/data/monitor/2bd01ede5c5258d5fce2e38bc58348a62c11ce33/

no changes added to commit (use "git add" and/or "git commit -a")
~~~
