### ISSUE TITLE
Error parsing memory dump in KVM

### ISSUE THREAD

**Issue by takadito** [cuckoosandbox/cuckoo#1628]
I'm using KVM with Win 7 SP1 x86. The volatility plugin failed with "AddrSpaceError: No suitable address space mapping found"
(I have correctly configured the profile both in memory.conf [guest_profile = Win7SP1x86] and kvm.conf [osprofile = Win7SP1x86].

2017-06-05 16:20:41,272 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory" for task #6:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 238, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1118, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1000, in __init__
    self.vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 79, in __init__
    self.init_config()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 150, in init_config
    self.addr_space = utils.load_as(self.config)
  File "/usr/local/lib/python2.7/dist-packages/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF error: did not find any PT_NOTE segment with VBCORE
 VMWareMetaAddressSpace: VMware metadata file is not available
 QemuCoreDumpElf: ELF error: did not find any PT_NOTE segment with CORE
 VMWareAddressSpace: Invalid VMware signature: 0x464c457f
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 WindowsAMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 LinuxAMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 AMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 IA32PagedMemoryPae: Failed valid Address Space check
 IA32PagedMemory: Failed valid Address Space check
 OSXPmemELF: No PT_LOAD segments found
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Profile does not have valid Address Space check

Any idea?

**Comment by jbremer** [comment]
Can you try `Win7SP1x86_23418` instead?

**Comment by takadito** [comment]
:(

2017-06-05 16:42:52,692 [cuckoo.processing.memory] ERROR: Error running Volatility on machine 'cuckoo1': An incorrect OS has been specified for this machine! Please provide the correct one or Cuckoo won't be able to provide Volatility-based results for analyses with this VM.

**Comment by jbremer** [comment]
Can you try analyzing the memory dump manually using `vol.py`?

**Comment by takadito** [comment]
The same error.. 

vol.py -f memory.dmp --profile=Win7SP1x86 pslist
Volatility Foundation Volatility Framework 2.6

No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 VMWareMetaAddressSpace: VMware metadata file is not available
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF error: did not find any PT_NOTE segment with VBCORE
 VMWareAddressSpace: Invalid VMware signature: 0x464c457f
 QemuCoreDumpElf: ELF error: did not find any PT_NOTE segment with CORE
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 WindowsAMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 LinuxAMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 AMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 IA32PagedMemoryPae: Failed valid Address Space check
 IA32PagedMemory: Failed valid Address Space check
 OSXPmemELF: No PT_LOAD segments found
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Profile does not have valid Address Space check

**Comment by jbremer** [comment]
Well, then at least it isn't Cuckoo's fault ;-) Please try some more profile's to figure out the correct one.
You can also run `vol.py imageinfo` to get such information.

**Comment by takadito** [comment]
I've tried all the profiles the from imageinfo output.. no success..

vol.py -f memory.dmp imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : Win7SP1x86_23418, Win7SP0x86, Win7SP1x86
                     AS Layer1 : FileAddressSpace (/home/user/.cuckoo/storage/analyses/6/memory.dmp)
                      PAE type : No PAE
                           DTB : 0x185000L
                          KDBG : 0x2d192c0L
          Number of Processors : 0
     Image Type (Service Pack) : 0
             KUSER_SHARED_DATA : 0xffdf0000L

maybe this is related to the way cuckoo acquire the memory dump?

thanks!

**Comment by JohnDoe60** [comment]
Same here with a Win7x64 profile. It seems that there's something wrong with the dump file. Processing the VBox .ELF file with same profile works fine.

```
vboxmanage debugvm "win7_x64" dumpvmcore --filename ~/win7_x64.elf
vol.py -f ~/win7_x64.elf --profile=Win7SP1x64 pslist
```
