### ISSUE TITLE
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by solower** [cuckoosandbox/cuckoo#1680]
```
^Croot@blackey-virtual-machine:/opt/cuckoo# python cuckoo.py 

  eeee e   e eeee e   e  eeeee eeeee 
  8  8 8   8 8  8 8   8  8  88 8  88 
  8e   8e  8 8e   8eee8e 8   8 8   8 
  88   88  8 88   88   8 8   8 8   8 
  88e8 88ee8 88e8 88   8 8eee8 8eee8

 Cuckoo Sandbox 2.0-rc2
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Good! You have the latest version available.

2017-06-27 16:32:14,952 [root] INFO: Updated running task ID 59 status to failed_analysis
2017-06-27 16:32:14,973 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-06-27 16:32:16,844 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-06-27 16:32:16,859 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-06-27 16:32:33,356 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "1V17.0.exe" (task #60, options "route=none,procmemdump=yes")
2017-06-27 16:32:33,417 [lib.cuckoo.core.scheduler] INFO: File already exists at "/opt/cuckoo/storage/binaries/10f6750074bea056d42958846b8de840c0cc58c765ecefc684b0cf5797ed27e1"
2017-06-27 16:32:33,434 [lib.cuckoo.core.scheduler] INFO: Task #60: acquired machine cuckoo1 (label=sandboxR)
2017-06-27 16:32:33,507 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6428 (interface=vboxnet0, host=192.168.56.101, pcap=/opt/cuckoo/storage/analyses/60/dump.pcap)
2017-06-27 16:32:38,333 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2017-06-27 16:32:43,362 [lib.cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo1, ip=192.168.56.101)
2017-06-27 16:32:43,901 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Potential error while running tcpdump, did not expect the following standard error output: 'dropped privs to root'.
2017-06-27 16:32:45,243 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 519, in run
    self.launch_analysis()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 399, in launch_analysis
    self.guest_manage(options)
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 301, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/opt/cuckoo/lib/cuckoo/core/guest.py", line 448, in start_analysis
    self.post("/store", files=files, data=data)
  File "/opt/cuckoo/lib/cuckoo/core/guest.py", line 298, in post
    return session.post(url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.1-py2.7.egg/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.1-py2.7.egg/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.1-py2.7.egg/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.1-py2.7.egg/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

```

> ERROR: Failure in AnalysisManager.run

and

> Unable to stop auxiliary module: Potential error while running tcpdump, did not expect the following standard error output: 'dropped privs to root'.

i can't solve two problems, please help me

**Comment by doomedraven** [comment]
you use very old version of cuckoo, update to latest version first

**Comment by jbremer** [comment]
If possible, please upgrade to our latest version, see also our blogpost from a few months back; https://cuckoosandbox.org/2017-04-07-cuckoo-sandbox-200.html I think that would address both issues that you presented here.

**Comment by jbremer** [comment]
Any update here @solower? Next time I'll be closing this issue if no additional information is provided :-)

**Comment by jbremer** [comment]
Closing for lack of additional information.
