### ISSUE TITLE
analyzer does not work!

### ISSUE THREAD

**Issue by 0xBigBan** [cuckoosandbox/cuckoo#1688]
Hey,
I got this error when I use `cuckoo submit  --options arguments='aa bb' binary.exe`

```
2017-07-01 01:54:30,015 [cuckoo.core.guest] WARNING: win7: analysis caught an exception
Traceback (most recent call last):
  File "C:\tmprlpdb9\analyzer.py", line 789, in <module>
    success = analyzer.run()
  File "C:\tmprlpdb9\analyzer.py", line 644, in run
    pids = self.package.start(self.target)
  File "C:\tmprlpdb9\modules\packages\exe.py", line 20, in start
    os.rename(path, new_path)
WindowsError: [Error 183] 

```
And of course cuckoo reports nothing on processing part.

**Comment by jbremer** [comment]
Thanks for reporting. Which version of Cuckoo are you running?

**Comment by FireAVR** [comment]
Hi, I am seeing same issue. I am using version 2.0.3

**Comment by JaimePolo** [comment]
same here:

running cuckoo 2.0.4

Traceback (most recent call last):
	  File "C:/tmptm1sln/analyzer.py", line 794, in <module>
	    success = analyzer.run()
	  File "C:/tmptm1sln/analyzer.py", line 649, in run
	    pids = self.package.start(self.target)
	  File "C:\tmptm1sln\modules\packages\exe.py", line 23, in start
	    return self.execute(path, args=shlex.split(args))
	  File "C:\tmptm1sln\lib\common\abstracts.py", line 165, in execute
	    "Unable to execute the initial process, analysis aborted."
	CuckooPackageError: Unable to execute the initial process, analysis aborted
