### ISSUE TITLE
Upload fails 3.2 GB exe

### ISSUE THREAD

**Issue by netpacket** [cuckoosandbox/cuckoo#1710]
The failure could be that I am uploading a file over 1 GB. The uploading page is stuck on waiting to upload the file. 

Cuckoo web output:
[12/Jul/2017 09:26:24] "POST /analysis/api/tasks/info/ HTTP/1.1" 200 793
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.3', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 530, in web
    ("cuckoo",) + args
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 49, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 88, in handle
    self.run(**options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 97, in run
    autoreload.main(self.inner_run, None, options)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 325, in main
    reloader(wrapped_main_func, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 296, in python_reloader
    exit_code = restart_with_reloader()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 282, in restart_with_reloader
    exit_code = os.spawnve(os.P_WAIT, sys.executable, args, new_environ)
  File "/usr/lib/python2.7/os.py", line 575, in spawnve
    return _spawnvef(mode, file, args, env, execve)
  File "/usr/lib/python2.7/os.py", line 548, in _spawnvef
    wpid, sts = waitpid(pid, 0)
OSError: [Errno 4] Interrupted system call
cuckoo@T440p-1572:~/.cuckoo/conf$ [12/Jul/2017 09:26:25] "POST /analysis/api/tasks/info/ HTTP/1.1" 200 761

Cuckoo web is still running.

**Comment by jbremer** [comment]
Try to run the Web Interface in production mode, i.e., behind `uwsgi`/`nginx` rather than `cuckoo web`. Please see also the docs. I think that may just help in this particular situation. Do note that support for a 3.2 GB-sized file isn't guaranteed (although I did test successful analysis with 1 GB-sized files) ;-)

**Comment by netpacket** [comment]
Alright, I successfully set up nginx and uswgi. I am getting a new error message but same issue.

(venv) cuckoo@T440p-1572:~$ cuckoo web
Performing system checks...

System check identified no issues (0 silenced).
July 20, 2017 - 08:55:58
Django version 1.8.4, using settings 'cuckoo.web.web.settings'
Starting development server at http://localhost:8000/
Quit the server with CONTROL-C.
[20/Jul/2017 08:56:07] "GET / HTTP/1.1" 200 25226
[20/Jul/2017 08:56:07] "GET /static/css/vendor.css HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/css/main.css HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/vendor.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[20/Jul/2017 08:56:07] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[20/Jul/2017 08:56:08] "GET /static/images/close.png HTTP/1.1" 304 0
[20/Jul/2017 08:56:08] "GET /static/images/loading.gif HTTP/1.1" 304 0
[20/Jul/2017 08:56:08] "GET /static/images/prev.png HTTP/1.1" 304 0
[20/Jul/2017 08:56:08] "GET /static/images/next.png HTTP/1.1" 304 0
[20/Jul/2017 08:56:08] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 716
[20/Jul/2017 08:56:08] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[20/Jul/2017 08:56:08] "GET /static/fonts/Roboto_normal_500_default.woff HTTP/1.1" 304 0
[20/Jul/2017 08:56:08] "GET /static/fonts/Roboto_normal_700_default.woff HTTP/1.1" 304 0
[20/Jul/2017 08:56:08] "GET /static/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 0
[20/Jul/2017 08:56:08] "GET /cuckoo/api/status HTTP/1.1" 200 567
[20/Jul/2017 08:59:00] "POST /submit/api/presubmit/ HTTP/1.1" 302 0
[20/Jul/2017 08:59:00] "GET /submit/pre/11/ HTTP/1.1" 200 19868
[20/Jul/2017 08:59:02] "GET /submit/pre/11/ HTTP/1.1" 200 19868
[20/Jul/2017 08:59:02] "GET /static/css/vendor.css HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/css/main.css HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/vendor.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/images/close.png HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/images/loading.gif HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/images/prev.png HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/images/next.png HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[20/Jul/2017 08:59:02] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[20/Jul/2017 08:59:35] "POST /submit/api/filetree/ HTTP/1.1" 200 855
- Broken pipe from ('127.0.0.1', 55674)

If not already in list for Cuckoo updates, can upload size for the Cuckoo web be in next wave of updates. Thanks.

**Comment by jbremer** [comment]
Well, what do you expect? :-) VirusTotal and related services barely handle a few hundred megabytes. Please try submitting through the command-line rather than the Web Interface, i.e., `cuckoo submit bigfile.exe`. You could also try extending the HTTP request timeouts (please let me know how & if that helps anything)!
