### ISSUE TITLE
Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by Anim-IT** [cuckoosandbox/cuckoo#1726]
Hi
I've been using cuckko for some time and yesterday  I installed new version by pip.
I didn't migrate old config just new cuckoo with new configs.
I have installed all necessary packages and of course transferred new agent.py to windows snapshot .
But I can't do too much because after windows snapshot is up cuckoo crash every time. Not sure how to fix this problem.
Bellow some log.
Tom

2017-07-21 12:15:15,904 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2017-07-21 12:15:16,924 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo1, ip=192.168.53.120)
2017-07-21 12:15:16,999 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo1
2017-07-21 12:15:18,590 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 393, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 450, in start_analysis
    self.query_environ()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 335, in query_environ
    self.environ = self.get("/environ").json()["environ"]
  File "/usr/local/lib/python2.7/dist-packages/requests-2.13.0-py2.7.egg/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Anim-IT** [comment]
Hi
After many tries I've managed to start cuckoo but with older agent.py
Just in ubuntu cuckoo 2.0.3 with agent 0.7 and win7x86 didn't work
With older agent it started.
Now I have problem with process which crashes in every analysis .
As I see it was reported in previous report #1495 but without follow up

RpcRaiseException+0x4b RpcExceptionFilter-0xf rpcrt4+0x1df6e @ 0x7584df6e
NdrMapCommAndFaultStatus+0x3d3 NdrServerContextNewUnmarshall-0xb2e rpcrt4+0x16033 @ 0x75846033
NDRCContextBinding+0xec NdrSendReceive-0x7 rpcrt4+0x3f886 @ 0x7586f886
SLClose-0x28c osppc+0x2cb5 @ 0x6d3e2cb5
SLLoadApplicationPolicies+0xb30 SLCallServer-0x31f osppc+0x15629 @ 0x6d3f5629
SLClose+0x4d1 SLpBeginGenuineTicketTransaction-0x4703 osppc+0x3412 @ 0x6d3e3412
SLGetApplicationPolicy+0x355b SLRegisterPlugin-0x341 osppc+0xd714 @ 0x6d3ed714
SLUnloadApplicationPolicies+0x1033 SLConsumeRight-0x280 osppc+0xeceb @ 0x6d3eeceb
SLGetPolicyInformation+0x26 SLGetPolicyInformationDWORD-0x4 osppc+0x105dd @ 0x6d3f05dd
mso98win32client+0x16804 @ 0x65cf6804
mso98win32client+0x1677a @ 0x65cf677a
mso98win32client+0x1744c @ 0x65cf744c
mso98win32client+0x17299 @ 0x65cf7299
mso98win32client+0x15d3f @ 0x65cf5d3f
mso98win32client+0x159c4 @ 0x65cf59c4
mso98win32client+0x158fb @ 0x65cf58fb
mso98win32client+0x15833 @ 0x65cf5833
mso98win32client+0x13c84 @ 0x65cf3c84
mso98win32client+0x13660 @ 0x65cf3660
mso98win32client+0x1cfb2 @ 0x65cfcfb2
mso98win32client+0x1cec1 @ 0x65cfcec1
mso98win32client+0x1ce83 @ 0x65cfce83
mso98win32client+0x1bb1c @ 0x65cfbb1c
mso98win32client+0x1ba92 @ 0x65cfba92
_MsoWchToUpperLid@12+0x47ec1 _MsoWchToLowerLid@12-0x30d33 mso20win32client+0x58085 @ 0x66ad8085
_MsoWchToUpperLid@12+0x1b633 _MsoWchToLowerLid@12-0x5d5c1 mso20win32client+0x2b7f7 @ 0x66aab7f7
_MsoWchToUpperLid@12+0x1b768 _MsoWchToLowerLid@12-0x5d48c mso20win32client+0x2b92c @ 0x66aab92c
_MsoWchToUpperLid@12+0x1b633 _MsoWchToLowerLid@12-0x5d5c1 mso20win32client+0x2b7f7 @ 0x66aab7f7
_MsoWchToUpperLid@12+0x1b5ab _MsoWchToLowerLid@12-0x5d649 mso20win32client+0x2b76f @ 0x66aab76f
_MsoWchToUpperLid@12+0x15100 _MsoWchToLowerLid@12-0x63af4 mso20win32client+0x252c4 @ 0x66aa52c4
_MsoWchToUpperLid@12+0x13678 _MsoWchToLowerLid@12-0x6557c mso20win32client+0x2383c @ 0x66aa383c
_MsoWchToUpperLid@12+0x105bd _MsoWchToLowerLid@12-0x68637 mso20win32client+0x20781 @ 0x66aa0781
_MsoWchToUpperLid@12+0xfee2 _MsoWchToLowerLid@12-0x68d12 mso20win32client+0x200a6 @ 0x66aa00a6
BaseThreadInitThunk+0x12 OpenFileMappingA-0xc kernel32+0x4ef8c @ 0x76c5ef8c
RtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x6367a @ 0x775a367a
RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x6364d @ 0x775a364d

exception.instruction_r: c9 c2 10 00 89 45 c0 eb ed 3d 01 01 00 00 0f 85
exception.symbol: RaiseException+0x54 GetSidSubAuthorityCount-0x3c kernelbase+0x845d
exception.instruction: leave
exception.module: KERNELBASE.dll
exception.exception_code: 0xc004f012
exception.offset: 33885
exception.address: 0x7559845d
registers.esp: 114812136
registers.edi: 114812312
registers.eax: 114812136
registers.ebp: 114812216
registers.edx: 95889520
registers.ebx: 114813368
registers.esi: 3221549074
registers.ecx: 2147483648
