### ISSUE TITLE
An Html page makes cuckoo to stop analysis

### ISSUE THREAD

**Issue by Nwinternights** [cuckoosandbox/cuckoo#1739]
An html page (without or with a fake extension) makes cuckoo to crash.
here is the md5: d901676729e2af7f58987d4e20d2bf5e ( I uploaded on malwr just for making it available to download) https://malwr.com/analysis/YjViZjE2Y2RhZjBkNDM0NmFkODMzYTAyNDUyNTJlMDg/
here the traceback:
INFO: Guest is running Cuckoo Agent 0.7 (id=matrix02, ip=192.168.56.102)
2017-07-29 15:13:31,787 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=matrix02, ip=192.168.56.102, monitor=latest, size=3819928)
2017-07-29 15:13:32,123 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2017-07-29 15:13:32,124 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm matrix02
2017-07-29 15:13:33,618 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 698, in run
self.launch_analysis()
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 499, in launch_analysis
self.guest_manage(options)
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
self.guest_manager.start_analysis(options, monitor)
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 480, in start_analysis
self.post("/store", files=files, data=data)
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 309, in post
r.raise_for_status()
File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.102:8000/store

**Comment by Nwinternights** [comment]
Update: today 5 over 5 gave me error but sometime the analysis goes ok. I guess its a randomic issue

**Comment by jbremer** [comment]
Sound very odd. The `/store` API endpoint that's mentioned in your traceback indicates a file transfer towards the Guest, however, that should normally work just fine. Do you have extremely high CPU loads or out of disk issues?

**Comment by Nwinternights** [comment]
CPU and I/o disk are ok. I guess I can close the issue cause it's too randomic. I'll try to investigate by myself :-)
If I 've any new proofs I'll open it.
as always, thanks for your support.

**Comment by Sharpnxr** [comment]
I met exactly the same situation. I'v submitted twice but failed twice. Have you figured out what caused this?
