### ISSUE TITLE
KeyError: 'SYSTEMDRIVE' 

### ISSUE THREAD

**Issue by Mato-Z** [cuckoosandbox/cuckoo#1747]
Hello, I have the same problem as here: https://github.com/cuckoosandbox/cuckoo/issues/1549. I use Debian 8 x64 as host and Debian 8 x64 as guest and VirtualBox (5.1.26). What is the current state for solving of this issue please? 

```
 Cuckoo Sandbox 2.0.3
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!
2017-08-01 18:31:47,349 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-08-01 18:31:49,054 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-08-01 18:31:49,125 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-08-01 18:32:13,526 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "test.txt" (task #4, options "")
2017-08-01 18:32:13,681 [cuckoo.core.scheduler] INFO: Task #4: acquired machine Debian8-1 (label=Debian8-1)
2017-08-01 18:32:13,709 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 28599 (interface=vboxnet0, host=192.168.30.11, pcap=/root/.cuckoo/storage/analyses/4/dump.pcap)
2017-08-01 18:32:25,142 [cuckoo.core.guest] INFO: Starting analysis on guest (id=Debian8-1, ip=192.168.30.11)
2017-08-01 18:32:30,215 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=Debian8-1, ip=192.168.30.11)
2017-08-01 18:32:37,102 [cuckoo.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label Debian8-1 to path /root/.cuckoo/storage/analyses/4/memory.dmp
2017-08-01 18:32:47,867 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/root/.cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/root/.cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis
    self.guest_manage(options)
  File "/root/.cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 393, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/root/.cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 453, in start_analysis
    self.upload_analyzer(monitor)
  File "/root/.cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 360, in upload_analyzer
    self.determine_analyzer_path()
  File "/root/.cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 340, in determine_analyzer_path
    systemdrive = "%s\\" % self.environ["SYSTEMDRIVE"]
KeyError: 'SYSTEMDRIVE'
```

**Comment by doomedraven** [comment]
if you read the referer issue you will see link to fix it there, https://github.com/cuckoosandbox/cuckoo/pull/1545

official fix will be integrated soon -> https://github.com/daanfs/cuckoo/blob/linux-analysis/cuckoo/core/guest.py

**Comment by Mato-Z** [comment]
@doomedraven thanks for info.

**Comment by doomedraven** [comment]
if you need it now, you can use https://linux.huntingmalware.com

**Comment by jbremer** [comment]
Yes, as @doomedraven mentioned all of this has been fixed and will be merged in our upcoming release, thanks to @daanfs. We'll keep you updated. For now you can check out our development version which should include all of your required goodies.

**Comment by Omar-hr** [comment]
Hey guys,
I'm new to this, so sorry if this is stupid question. I am having this exact same error with cuckoodroid 2.0.3
I checked the mentioned [https://github.com/cuckoosandbox/cuckoo/pull/1545](link) but I didn't understand what I should do. Can anyone kindly provide me with the general steps that I should follow in order to get it fixed until the merged version is released? I would really appreciate it

Thanks

**Comment by Omar-hr** [comment]
I am using **android_on_linux** analyzer by the way

**Comment by Omar-hr** [comment]
Please guys, I would really appreciate if anyone can help me... I'm stuck here

**Comment by doomedraven** [comment]
check what i post, do search in code for `SYSTEMDRIVE` and backport it to your cuckoo, done

**Comment by Omar-hr** [comment]
Thank you very much. However, I'm now getting a different error:

```

2017-08-15 14:39:20,196 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis
    self.guest_manage(options)
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 393, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 464, in start_analysis
    self.upload_analyzer(monitor)
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 371, in upload_analyzer
    self.determine_analyzer_path()
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 348, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 309, in post
    r = session.post(url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

```
Should I open a new issue?

**Comment by doomedraven** [comment]
replace your guest.py with this one https://github.com/cuckoosandbox/cuckoo/blob/eaff7f5183845e14ff557993991be93e1791e3d9/cuckoo/core/guest.py

i don't know why you just don't do that

**Comment by doomedraven** [comment]
try replace your guest.py  with https://github.com/cuckoosandbox/cuckoo/blob/c6276083c08f111fa1a3d18ad5978bbe08b5ada6/cuckoo/core/guest.py

**Comment by Omar-hr** [comment]
Yea I already tried that:

```
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.3', 'console_scripts', 'cuckoo')()
  File "/home/omar/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/omar/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/home/omar/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/home/omar/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/main.py", line 30, in <module>
    from cuckoo.core.scheduler import Scheduler
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 24, in <module>
    from cuckoo.core.guest import GuestManager
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 557
    return self.old.server
SyntaxError: 'return' outside function
```

**Comment by doomedraven** [comment]
google is your friend ;) is easy

**Comment by Omar-hr** [comment]
Thank you for your time, yea that was easy, sorry...
So I got the file fixed but now I'm getting `Failure in AnalysisManager.run` again:

```
ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis
    self.guest_manage(options)
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 393, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 455, in start_analysis
    self.upload_analyzer(monitor)
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 362, in upload_analyzer
    self.determine_analyzer_path()
  File "/home/omar/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 350, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
UnboundLocalError: local variable 'systemdrive' referenced before assignment

```

**Comment by doomedraven** [comment]
yup you should extend this one, but the better is backport how it handled in upcoming release to which i pointed 
https://github.com/cuckoosandbox/cuckoo/blob/eaff7f5183845e14ff557993991be93e1791e3d9/cuckoo/core/guest.py#L336 i think it starts here

**Comment by vivekgupta123** [comment]
i m running ubuntu 17.04 as guest VM and cuckoo 2.0.3. I have been getting  following error: 
systemdrive = "%s\\" % self.environ["SYSTEMDRIVE"]
KeyError: 'SYSTEMDRIVE'

So as per suggestion i updated the guest.py and analyzer.py

Now i m getting the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 393, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 461, in start_analysis
    self.upload_analyzer(monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 369, in upload_analyzer
    self.determine_analyzer_path()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 347, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 307, in post
    r = session.post(url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by daanfs** [comment]
Please check out our development version which has the required fixes for linux analysis to work.

**Comment by foronine** [comment]
@vivekgupta123 I'm having the same issue, did you manage to fix it?

**Comment by daanfs** [comment]
@foronine which version of cuckoo are you using? As mentioned this should be fixed in the development version and upcoming 2.0.4 release.

**Comment by foronine** [comment]
We're using 2.0.3, we just realized the agent was expecting Content-Type to be passed in the requests. We made that tweak and it did the trick for the ConnectionError: ('Connection aborted.', BadStatusLine("''",)) issue.
I'll give 2.0.4 a try whenever its out, but I'm already using the development guest.py, which still has the BadStatusLine issue.

**Comment by vivekgupta123** [comment]
no i could not fix it.

**Comment by Omar-hr** [comment]
Nope, couldn't solve it as well. I tried everything
The best option for me was to get back to 1.2 for now

**Comment by doomedraven** [comment]
>> Nope, I couldn't solve it either. I tried everything

lol but not even tried read what i pointed

**Comment by Omar-hr** [comment]
> lol but not even tried read what i pointed

lol how are you assuming that?

**Comment by foronine** [comment]
@doomedraven This is still an issue with guest.py in the development branch.

This fixed it for us. Change on line 350:

r = self.post("/mkdtemp", data={"dirpath": systemdrive})

To:

r = self.post("/mkdtemp", data={"dirpath": systemdrive}, headers={"Content-Type": 'application/json'})

@Omar-hr @vivekgupta123 Give it a try and see if that fixes the issue for you.

**Comment by doomedraven** [comment]
bcz i did the PR with fix for it, and it was easy to do a c&p to fix it, and i tried to point you, but well that is not my cuckoo, so i don't care :P

**Comment by doomedraven** [comment]
dev branch is not related to my PR :) @daanfs  check that in your branch

**Comment by daanfs** [comment]
@foronine are you using the old or new `agent.py`? 2.0.3 still uses the old one while the development version uses the new one.

**Comment by daanfs** [comment]
The patch @foronine suggested might be useful to keep things compatible with the old agent, I will have a look at that.

**Comment by Omar-hr** [comment]
> @Omar-hr @vivekgupta123 Give it a try and see if that fixes the issue for you.

Thanks man, I'll give it a try 

> bcz i did the PR with fix for it, and it was easy to do a c&p to fix it, and i tried to point you, but well that is not my cuckoo, so i don't care :P

I tried what you told me to do, and it didn't work. I don't know why, maybe I did something wrong, but thanks anyways

**Comment by foronine** [comment]
agent.py still expects content-type unless I'm in the wrong repo. It also looks like my 2.0.3 install came with agent.py md5 71e052e71e0a8fa25dbcdc29a8a6f3ba which is that same as the one in the repo.

def do_POST(self):
        environ = {
            "REQUEST_METHOD": "POST",
            "CONTENT_TYPE": self.headers.get("Content-Type"),
        }

**Comment by daanfs** [comment]
@foronine That is indeed the correct version of the agent. Have you replaced the `agent.py` on your guest VM with that one? I can't replicate your issue in our current development version.

**Comment by vivekgupta123** [comment]
@daanfs how to view the development version?

**Comment by jbremer** [comment]
Cuckoo version `2.0.4` has been released including all of @daanfs' Linux Analyzer and related improvements. I suggest everyone in this thread to upgrade and see if they're still running into issues. If you do have errors / etc, please start a new issue.
CC @Mato-Z @vivekgupta123 @foronine @Omar-hr
