### ISSUE TITLE
Race condition in report

### ISSUE THREAD

**Issue by CrimsonGlory** [cuckoosandbox/cuckoo#1754]
Cuckoo categorizes a task as 'reported' before the report plugins finishes. So retrieving the report just after the status change to 'reported' will provide an incomplete report. Deleting it will show a crash.

```
syslog:Aug  3 15:07:16 CuckooServer2 bash[1062]: 2017-08-03 15:07:16,258 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "84df36e6f42b50d8153d495e0713e29017652d99.exe" (task #11131, options "")
syslog:Aug  3 15:07:16 CuckooServer2 bash[1062]: 2017-08-03 15:07:16,679 [cuckoo.core.scheduler] INFO: Task #11131: acquired machine Windows7x64_2 (label=Windows7x64_2)
syslog:Aug  3 15:07:17 CuckooServer2 bash[1062]: 2017-08-03 15:07:17,416 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 8771 (interface=vboxnet0, host=192.168.59.66, pcap=/home/genesis/.cuckoo/storage/analyses/11131/dump.pcap)
syslog:Aug  3 15:12:10 CuckooServer2 bash[1312]: 2017-08-03 15:12:10,062 [cuckoo.apps.apps] INFO: Task #11131: reporting task
syslog:Aug  3 15:12:22 CuckooServer2 bash[1312]: 2017-08-03 15:12:22,807 [cuckoo.apps.apps] INFO: Task #11131: reports generation completed
syslog:Aug  3 15:12:23 CuckooServer2 bash[1322]: 2017-08-03 15:12:23,387 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:23] "GET /pcap/get/11131 HTTP/1.1" 200 -
syslog:Aug  3 15:12:23 CuckooServer2 bash[1322]: 2017-08-03 15:12:23,459 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:23] "GET /tasks/report/11131/all?tar=gz HTTP/1.1" 200 -
syslog:Aug  3 15:12:23 CuckooServer2 bash[1322]: 2017-08-03 15:12:23,565 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:23] "GET /tasks/screenshots/11131/0001 HTTP/1.1" 200 -
syslog:Aug  3 15:12:23 CuckooServer2 bash[1322]: 2017-08-03 15:12:23,568 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:23] "GET /tasks/screenshots/11131/0002 HTTP/1.1" 200 -
syslog:Aug  3 15:12:23 CuckooServer2 bash[1322]: 2017-08-03 15:12:23,571 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:23] "GET /tasks/screenshots/11131/0003 HTTP/1.1" 200 -
syslog:Aug  3 15:12:23 CuckooServer2 bash[1322]: 2017-08-03 15:12:23,574 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:23] "GET /tasks/screenshots/11131/0004 HTTP/1.1" 200 -
syslog:Aug  3 15:12:23 CuckooServer2 bash[1322]: 2017-08-03 15:12:23,576 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:23] "GET /tasks/screenshots/11131/0005 HTTP/1.1" 200 -
syslog:Aug  3 15:12:23 CuckooServer2 bash[1322]: 2017-08-03 15:12:23,578 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:23] "GET /tasks/screenshots/11131/0006 HTTP/1.1" 200 -
syslog:Aug  3 15:12:23 CuckooServer2 bash[1322]: 2017-08-03 15:12:23,582 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:23] "GET /tasks/screenshots/11131/0007 HTTP/1.1" 404 -
syslog:Aug  3 15:12:24 CuckooServer2 bash[1322]: 2017-08-03 15:12:24,019 [werkzeug] INFO: 192.168.20.46 - - [03/Aug/2017 15:12:24] "GET /tasks/delete/11131 HTTP/1.1" 200 -
syslog:Aug  3 15:12:24 CuckooServer2 bash[1062]: 2017-08-03 15:12:24,050 [cuckoo.core.plugins] ERROR: #033[31mFailed to run the processing module "NetworkAnalysis" for task #11131:#033[0m
syslog:Aug  3 15:12:24 CuckooServer2 bash[1062]: IOError: [Errno 2] No such file or directory: u'/home/genesis/.cuckoo/storage/analyses/11131/cuckoo.log'
syslog:Aug  3 15:12:24 CuckooServer2 bash[1062]: IOError: [Errno 2] No such file or directory: u'/home/genesis/.cuckoo/storage/analyses/11131/cuckoo.log'
syslog:Aug  3 15:12:24 CuckooServer2 bash[1062]: IOError: [Errno 2] No such file or directory: u'/home/genesis/.cuckoo/storage/analyses/11131/cuckoo.log'
```

**Comment by jbremer** [comment]
Are you sure? https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/core/scheduler.py#L708-L709 https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/apps/apps.py#L264-L265 ?

**Comment by CrimsonGlory** [comment]
In the logs, it says 15:12:22
```
syslog:Aug  3 15:12:22 CuckooServer2 bash[1312]: 2017-08-03 15:12:22,807 [cuckoo.apps.apps] INFO: Task #11131: reports generation completed
```

Then, two seconds later:
```
syslog:Aug  3 15:12:24 CuckooServer2 bash[1062]: 2017-08-03 15:12:24,050 [cuckoo.core.plugins] ERROR: #033[31mFailed to run the processing module "NetworkAnalysis" for task #11131:#033[0m
```

If it had already finished two seconds ago, why print the 'failed to run xyz' after that?
That's why I thought this was a race condition. I have no idea about the internals of cuckoo.

**Comment by jbremer** [comment]
Not sure. Please share the entire Cuckoo log (not `syslog`!) and we can have a better look at it.

**Comment by jbremer** [comment]
Closing issue as resolved. Sorry for missing it earlier @CrimsonGlory, but in the meanwhile a friend had reported the same issue, see also b943edb52579333ce91fa17b508b644ba158b2de. Thanks!

**Comment by CrimsonGlory** [comment]
I think this issue is still happening in at least version 2.0.6
An easy way to reproduce this is to haVe a script querying constantly at the API with /tasks/list?status=reported and as soon as a file appears, delete it. This will produce a stacktrace on the logs.

```
2019-07-12 22:35:49,425 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "do_not_delete_c8a13f239d18fd108afcf6d0bbd608ffb8ba1efa.exe" (task #7292, options "")
2019-07-12 22:35:50,320 [cuckoo.core.scheduler] INFO: Task #7292: acquired machine Windows7x32_2 (label=Windows7x32_2)
2019-07-12 22:35:50,732 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 9063 (ip=192.168.20.48, port=50001).
2019-07-12 22:35:51,214 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 9066 (interface=virbr0, host=192.168.59.66)
2019-07-12 22:35:58,932 [cuckoo.core.guest] INFO: Starting analysis on guest (id=Windows7x32_2, ip=192.168.59.66)
2019-07-12 22:36:04,768 [cuckoo.processing.behavior] WARNING: Behavior log file u'2560.bson' is not a file.
2019-07-12 22:36:04,776 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 748, in run
    self.process_results()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 688, in process_results
    results = RunProcessing(task=self.task).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 312, in run
    key, result = self.process(module, results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 265, in process
    extra={"task_id": self.task["id"]}
  File "/usr/lib/python2.7/logging/__init__.py", line 1207, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1200, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 35, in emit
    getattr(record, "error_action", None)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/utils.py", line 199, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 998, in add_error
    log.debug("Database error adding error log: {0}".format(e))
  File "/usr/lib/python2.7/logging/__init__.py", line 1162, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/log.py", line 48, in emit
    with open(cwd("cuckoo.log", analysis=task_id), "a+b") as f:
IOError: [Errno 2] No such file or directory: u'/home/genesis/.cuckoo/storage/analyses/7275/cuckoo.log'
2019-07-12 22:36:08,746 [cuckoo.core.scheduler] WARNING: Original file does not exist anymore: "/home/genesis/.cuckoo/tmp/tmp2xljoF/do_not_delete_ef95323fbe84bfc53fbbb0a6544a7d4fe90c9faa.exe": File not found.
2019-07-12 22:36:08,746 [cuckoo.core.scheduler] WARNING: Copy of the original file does not exist anymore: "/home/genesis/.cuckoo/storage/binaries/e92df578e6456b3fdb840fe2ef06038970196e49187476ecf4d137efdabcfb1b": File not found
2019-07-12 22:36:08,746 [cuckoo.core.scheduler] INFO: Task #7291: reports generation completed
2019-07-12 22:36:08,788 [cuckoo.core.scheduler] INFO: Task #7291: analysis procedure completed
```
