### ISSUE TITLE
Ubuntu 17.04  guest giving connection error after updating analyzer.py and guest.py

### ISSUE THREAD

**Issue by vivekgupta123** [cuckoosandbox/cuckoo#1786]
i m running ubuntu 17.04 as guest VM and cuckoo 2.0.3. 
I have been getting  following error: 
systemdrive = "%s\" % self.environ["SYSTEMDRIVE"] KeyError: 'SYSTEMDRIVE' 

So as per suggestion i updated the guest.py and analyzer.py

 Now i m getting the following error: 

Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 697, in run self.launch_analysis()
 File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 498, in launch_analysis self.guest_manage(options) 
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 393, in guest_manage self.guest_manager.start_analysis(options, monitor) 
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 461, in start_analysis self.upload_analyzer(monitor) 
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 369, in upload_analyzer self.determine_analyzer_path() 
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 347, in etermine_analyzer_path r = self.post("/mkdtemp", data={"dirpath": systemdrive})
 File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 307, in post 
r = session.post(url, *args, **kwargs) 
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post 
return self.request('POST', url, data=data, json=json, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request 
resp = self.send(prep, **send_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send 
r = adapter.send(request, **kwargs)]
File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send 
raise ConnectionError(err, request=request)
 ConnectionError: ('Connection aborted.', BadStatusLine("''",))
--

**Comment by daanfs** [comment]
Please check out our development version which has the required fixes for linux analysis to work.

**Comment by vivekgupta123** [comment]
@daanfs how to check development version?
