### ISSUE TITLE
Error running httpreplay-based PCAP analysis (UnknownHttpEncoding: x-compress)

### ISSUE THREAD

**Issue by tUn4** [cuckoosandbox/cuckoo#1787]
Hi,
i've faced many sample that raise this error and not found any solution to fix it.
Here is pcap file: 
[89404ed1eb8cbbdb6b10495ac51b27fe45c8978a2538108050a959c0e1add9f0_dump.zip](https://github.com/cuckoosandbox/cuckoo/files/1230377/89404ed1eb8cbbdb6b10495ac51b27fe45c8978a2538108050a959c0e1add9f0_dump.zip)

[cuckoo.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/lib/python2.7/site-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/processing/network.py", line 897, in run
    results.update(p2.run())
  File "/home/cuckoo/cuckoo/lib/python2.7/site-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/processing/network.py", line 776, in run
    l = sorted(r.process(), key=lambda x: x[1])
  File "build/bdist.linux-x86_64/egg/httpreplay/reader.py", line 126, in process
    self.tcp and self.tcp.finish()
  File "build/bdist.linux-x86_64/egg/httpreplay/smegma.py", line 91, in finish
    stream.finish()
  File "build/bdist.linux-x86_64/egg/httpreplay/smegma.py", line 367, in finish
    self.parent.handle(self.s, self.ts, "tcp", sent, recv)
  File "build/bdist.linux-x86_64/egg/httpreplay/smegma.py", line 600, in handle
    while self.states[self.state](self, s, ts):
  File "build/bdist.linux-x86_64/egg/httpreplay/smegma.py", line 557, in state_stream
    self.parent.handle(s, ts, "tls", "".join(sent), "".join(recv))
  File "build/bdist.linux-x86_64/egg/httpreplay/cobweb.py", line 171, in handle
    res = self.parse_response(ts, recv)
  File "build/bdist.linux-x86_64/egg/httpreplay/cobweb.py", line 130, in parse_response
    raise UnknownHttpEncoding(content_encoding)

**Comment by jbremer** [comment]
Thanks for reporting! What you're saying is correct, i.e., that we don't handle `x-compress` currently. This can be easily fixed, but please provide a correct PCAP - AFAIK this one doesn't have an actual `x-compress` stream.

**Comment by jbremer** [comment]
@tUn4 do you have a PCAP with said HTTP streams?

**Comment by tUn4** [comment]
So sad to say that i can not remember the task id that was generated this error. I will let you know if i'm get it again. Thanks for your supporting.

**Comment by jbremer** [comment]
No worries, looking forward to a correct PCAP :-)

**Comment by jbremer** [comment]
Unfortunately closing this issue for lack of additional information. Would be great if you find a PCAP with `x-compress` encoding, in that case, please reopen this issue. I'd be happy to add support for it. Thanks!
