### ISSUE TITLE
ERROR: Failed to run the processing module "DroppedBuffer" 

### ISSUE THREAD

**Issue by ac3l1k** [cuckoosandbox/cuckoo#1826]
Hello, 

I have the following error: 

```
ERROR: Failed to run the processing module "DroppedBuffer" for task #634:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/core/plugins.py", line 238, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/processing/buffer.py", line 24, in run
    file_info = File(file_path=file_path).get_all()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/common/objects.py", line 392, in get_all
    infos["yara"] = self.get_yara()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/common/objects.py", line 325, in get_yara
    for _, key, value in match.strings:
AttributeError: 'str' object has no attribute 'strings'
```

My host OS is Ubuntu 14.04 with python version 2.7.6.
As far as I know, I have installed all the requirements successfully. Most of the tasks are fine and they complete without an error. But in some cases, I get this error (see above).

edit: The yara version I installed is python-yara 3.6.0.

Hope someone can help.
Best regards

**Comment by jbremer** [comment]
Hmm, that seems odd. Are you sure you have `yara-python==3.6.0`? Please upgrade to the latest version (`pip install -U cuckoo`) released this week to see if that resolves any problems - it should install `yara-python==3.6.3`.

**Comment by ac3l1k** [comment]
Hi, 

After upgrading nothing works :( 
I get this error:

```
2017-09-08 11:38:28,869 [cuckoo.apps.apps] WARNING: This is the first time you're running Cuckoo after updating your local version of Cuckoo. We're going to update files in your CWD that require updating. Note that we'll first ensure that no custom patches have been applied by you before applying any modifications of our own.
2017-09-08 11:38:29,057 [cuckoo.apps.apps] INFO: Automated migration of your CWD was successful! Continuing execution of Cuckoo as expected.
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.4
OS version: posix
OS release: Ubuntu 14.04 trusty
Python version: 2.7.6
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0.1 apt-xapian-index:0.45 asn1crypto:0.22.0 beautifulsoup4:4.5.3 bottle:0.12.0 capstone:3.0.5rc2 cffi:1.10.0 chardet:2.3.0 click:6.6 colorama:0.3.7 command-not-found:0.3 cryptography:2.0.3 cuckoo:2.0.4.4 cybox:2.0.1.4 debtagshw:0.1 defer:1.0.6 dirspec:13.10 distorm3:3.3.4 distribute:0.7.3 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 duplicity:0.6.23 ecdsa:0.13 egghatch:0.2.1 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 hachoir-core:1.3.3 hachoir-metadata:1.3.3 hachoir-parser:1.3.4 html5lib:0.999 httplib2:0.8 httpreplay:0.2.1 idna:2.6 ipaddress:1.0.18 itsdangerous:0.24 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 libvirt-python:1.2.2 lockfile:0.8 lxml:3.3.3 m2crypto:0.26.0 maec:4.0.1.0 magic-file-extensions:0.2 mako:1.0.7 markupsafe:1.0 nose:1.3.1 oauthlib:0.6.1 olefile:0.43 oletools:0.42 oneconf:0.3.7.14.4.1 openpyxl:1.7.0 pam:0.4.2 peepdf:0.3.6 pefile2:1.2.11 pefile:1.2.9.1 pexpect:3.1 pillow:3.2.0 pip:9.0.1 piston-mini-client:0.7.5 pycparser:2.18 pycrypto:2.6.1 pycups:1.9.66 pydeep:0.2 pyelftools:0.24 pygobject:3.12.0 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.2.0 pyserial:2.6 pysmbc:1.0.14.1 python-apt:0.9.3.5ubuntu2 python-dateutil:2.4.2 python-debian:0.1.21-nmu2ubuntu2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 pyxdg:0.25 reportlab:3.0 requests:2.13.0 scapy:2.3.2 sessioninstaller:0.0.0 setuptools:36.2.7 sflock:0.2.16 six:1.10.0 software-center-aptd-plugins:0.0.0 sqlalchemy:1.0.8 system-service:0.1.6 tlslite-ng:0.6.0 twisted-core:13.2.0 twisted-web:13.2.0 typing:3.6.2 unicorn:1.0.1 unity-lens-photos:1.0 urllib3:1.22 vboxapi:1.0 virtualenv:1.11.4 volatility:2.6 wakeonlan:0.2.2 werkzeug:0.12.2 wheel:0.24.0 xdiagnose:3.6.3build2 yara-python:3.6.3 yara:1.7.7 zope.interface:4.0.5

2017-09-08 11:38:29,708 [cuckoo] ERROR: AttributeError: Rules instance has no attribute 'save'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 216, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 127, in cuckoo_init
    init_yara()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 259, in init_yara
    File.yara_rules["memory"].save(cwd("stuff", "dumpmem.yarac"))
AttributeError: Rules instance has no attribute 'save'
```

**Comment by ac3l1k** [comment]
Ok,  I installed cuckoo 2.0.4. successfully, now. After removing all the files and folders in .cuckoo of the previous installation, the upgrade worked.

**Comment by jbremer** [comment]
It said you had installed `yara==1.7.1` which is a very old version of Yara, should probably uninstall that ;-)

**Comment by jbremer** [comment]
Closing as resolved.
