### ISSUE TITLE
Error in misc.py script to extract database information from cuckoo.conf

### ISSUE THREAD

**Issue by adrrodgar** [cuckoosandbox/cuckoo#1836]
When I perform SQLite queries to cuckoo.db in version 2.0.4 I get the following error:
`Traceback (most recent call last):
  File "proofStatus.py", line 9, in <module>
    db.connect()
  File "/home/adrian/.local/lib/python2.7/site-packages/cuckoo/core/database.py", line 428, in connect
    dsn = config("cuckoo:database:connection")
  File "/home/adrian/.local/lib/python2.7/site-packages/cuckoo/common/config.py", line 1078, in config
    file_name, cfg=cfg, strict=strict, raw=raw, loose=loose
  File "/home/adrian/.local/lib/python2.7/site-packages/cuckoo/common/config.py", line 919, in __init__
    config.read(cfg or cwd("conf", "%s.conf" % file_name))
  File "/home/adrian/.local/lib/python2.7/site-packages/cuckoo/misc.py", line 60, in cwd
    return os.path.join(_root, *args)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'`

My code is:

`path = "/home/adrian/.cuckoo/cuckoo.db"
db = Database()
db.connect()
info = db.list_tasks(status="reported")
for task in info:
    print(task.id)`

I have solved it but in a dirty way. I have entered the query as parameter dsn in the connect method:

`db.connect(dsn="sqlite:///" + path)`

I then had the following error again:

`Traceback (most recent call last):
  File "proofStatus.py", line 8, in <module>
    db.connect(dsn="sqlite:///" + path)
  File "/home/adrian/.local/lib/python2.7/site-packages/cuckoo/core/database.py", line 438, in connect
    self.engine.pool_timeout = config("cuckoo:database:timeout")
  File "/home/adrian/.local/lib/python2.7/site-packages/cuckoo/common/config.py", line 1078, in config
    file_name, cfg=cfg, strict=strict, raw=raw, loose=loose
  File "/home/adrian/.local/lib/python2.7/site-packages/cuckoo/common/config.py", line 919, in __init__
    config.read(cfg or cwd("conf", "%s.conf" % file_name))
  File "/home/adrian/.local/lib/python2.7/site-packages/cuckoo/misc.py", line 60, in cwd
    return os.path.join(_root, *args)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'`

So, I have been forced to modify the database.py file:

`# Connection timeout.
 #self.engine.pool_timeout = config("cuckoo:database:timeout")
 self.engine.pool_timeout = 60`

Now if it works as expected, but I think the fix is ​​dirty.

**Comment by jbremer** [comment]
Hi, please call `decide_cwd()` first! See, e.g., https://github.com/cuckoosandbox/cuckoo/blob/master/stuff/rawdb.py. Hope that helps :-)

**Comment by adrrodgar** [comment]
Hello @jbremer  your solution works correctly, if you want you can close this issue.
Thank you very much.

**Comment by jbremer** [comment]
Feel free to do so yourself @adrrodgar ;)
