### ISSUE TITLE
MISP Reporting Error - ValidatioError: u'Event' is a required property

### ISSUE THREAD

**Issue by arnydo** [cuckoosandbox/cuckoo#1859]
Recently started receiving this error. Not sure if this is a MISP issue or Cuckoo.

`2017-09-20 16:46:38,286 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MISP
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 614, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/misp.py", line 118, in run
    self.maldoc_network(results, event)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/misp.py", line 48, in maldoc_network
    self.misp.add_url(event, sorted(list(urls)))
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 517, in add_url
    return self._send_attributes(event, attributes, proposal)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 367, in _send_attributes
    e.load(event)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/mispevent.py", line 232, in load
    jsonschema.validate(event, self.json_schema_lax)
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: u'Event' is a required property`

**Comment by arnydo** [comment]
Here is an additional error:

`2017-09-25 16:18:21,219 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MISP
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 614, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/misp.py", line 110, in run
    event_id=event["Event"]["id"],
KeyError: 'Event'`

**Comment by arnydo** [comment]
Looks like this issue may be related to a recent update of CakePHP.
It has been resolved.

https://github.com/MISP/MISP/issues/2496
