### ISSUE TITLE
Problem with tcpdump

### ISSUE THREAD

**Issue by Omar-hr** [cuckoosandbox/cuckoo#1860]
Hello,

I'm having an issue with **tcpdump** although it used to work fine before. I didn't change anything with my system other than normal updates. 
This is the error message:

```
2017-09-21 13:20:05,826 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 162, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 154, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = "tcpdump: vboxnet0: You don't have permission to capture on that device\n(socket: Operation not permitted)\n". Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?

```

I started by trying the instructions  [here](https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump) but when I type 
`sudo aa-disable /usr/sbin/tcpdump`

I'm getting 
```
Disabling /usr/sbin/tcpdump.

ERROR: /sbin/apparmor_parser: Unable to remove "/usr/sbin/tcpdump".  Profile doesn't exist

```
I tried uninstalling tcpdump and following the [requirements](https://cuckoo.readthedocs.io/en/latest/installation/host/requirements/) page to install it again but I got the same error when I try to disable the apparmor profile.

Next thing I tried was to stop and remove apparmor, but I still got the same error in cuckoo.

I also tried to allow tcpdump to run as a non-root user but I got it messed up even more, and cuckoo won't even start (critical error), so I had to reinstall it again.

Again, I never got this error before, it used to work just fine, I don't know what happened.

Can someone help me please? I would really appreciate it!

**Comment by Omar-hr** [comment]
Running 
`sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump`
and restarting solved the issue

**Comment by vinod50rao** [comment]
Hi, 
I'm not able to dump the pcap and strings from the submit sample using cuckoo, i'm using windows 10 with virtual box 5.2, getting error 
can you please help me out with this.


2017-11-16 14:51:34,680 [cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
2017-11-16 14:51:34,709 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\cuckoo\core\plugins.py", line 162, in stop
    module.stop()
  File "c:\python27\lib\site-packages\cuckoo\auxiliary\sniffer.py", line 154, in stop
    "to Ubuntu-based distributions with AppArmor, see also %s)?" %
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'c:\\tools\\tcpdump.exe: listening on VirtualBox Host-Only Network\r\nc:\\tools\\tcpdump.exe: Error opening adapter: The operation completed successfully. (0)\r\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
2017-11-16 14:51:41,542 [cuckoo.processing.network] WARNING: The PCAP file does not exist at path "C:\Users\****\.cuckoo\storage\analyses\5\dump.pcap".
2017-11-16 14:51:42,661 [cuckoo.core.scheduler] INFO: Task #5: reports generation completed
2017-11-16 14:51:42,697 [cuckoo.core.scheduler] INFO: Task #5: analysis procedure completed

**Comment by icedxu** [comment]
I  set the timeout 
cuckoo submit --enforce-timeout 480 /home/icedxu/ransomware/
cuckoo 
,but  I  get a error，  cuckoo sandbox run for a minute and it's over.
and  I can not get any information;
what should I do?

**Comment by Wapiti08** [comment]
> 
> 
> Hi,
> I'm not able to dump the pcap and strings from the submit sample using cuckoo, i'm using windows 10 with virtual box 5.2, getting error, using cuckoo version 2.4
> can you please help me out with this.
> 
> 2017-11-16 14:51:34,680 [cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
> 2017-11-16 14:51:34,709 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
> Traceback (most recent call last):
> File "c:\python27\lib\site-packages\cuckoo\core\plugins.py", line 162, in stop
> module.stop()
> File "c:\python27\lib\site-packages\cuckoo\auxiliary\sniffer.py", line 154, in stop
> "to Ubuntu-based distributions with AppArmor, see also %s)?" %
> CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'c:\tools\tcpdump.exe: listening on VirtualBox Host-Only Network\r\nc:\tools\tcpdump.exe: Error opening adapter: The operation completed successfully. (0)\r\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
> 2017-11-16 14:51:41,542 [cuckoo.processing.network] WARNING: The PCAP file does not exist at path "C:\Users****.cuckoo\storage\analyses\5\dump.pcap".
> 2017-11-16 14:51:42,661 [cuckoo.core.scheduler] INFO: Task #5: reports generation completed
> 2017-11-16 14:51:42,697 [cuckoo.core.scheduler] INFO: Task #5: analysis procedure completed


You gotta find the sniffer.py under cuckoo foloder(recommend using tool called everything): and do the following two modifications. 
    for line in err.split(“\r\n”):
    if not line continue or line.startswith(err_whitelist_start):
    continue

    err_whitelist_start = (
    “tcpdump: listening on “,
    “/mnt/c/bin/tcpdump.exe: listening on “,
    )
