### ISSUE TITLE
agent start problem

### ISSUE THREAD

**Issue by artv2007** [cuckoosandbox/cuckoo#1866]
Hi all
I have a problem with start agent.py on a VirtualBox VM.
I install latest version of cuckoo. When I first run cuckoo -d , cuckoo generate config files in CWD and agent.py on the same dir too.
I make new vm in virtualbox, win7x64, boot from iso image, make clear install.
Disable FW, AutoUpdate and UAC and nothing more.
Install 2.7.14 python from original site. I try to install x86 and x64 version too.
I upload from cuckoo host by http agent.py file and save it in the c:\python27 dir.
I run cmd from admin and start agent.py - and nothing more. No error, no info messages, no logs. Agent not start.
I try to check netstat on another cmd - no port 8000.
How I can debug start process of agent.py? Any logs?
What I do wrong?

**Comment by tr4cefl0w** [comment]
What command did you use to run the agent.py?

**Comment by jbremer** [comment]
Closing for lack of additional information. Please reopen if you do have more feedback. Thanks!
BTW, best to use 32-bit Python in the VM.

**Comment by giveitatry168** [comment]
I encountered a similar problem. Agent.py was copy/paste to notepad from a Linux server. After "c:\python27\python.exe agent.py" is entered on a terminal window or powershell, a blank line (cr) was printed. Should a message like the following get displayed:

[+] Starting agent on ...

I don't see such text in agent.py though. How to verify agent is running? It is not shown in task manager.

**Comment by doomedraven** [comment]
`curl vm_ip:8000`

**Comment by giveitatry168** [comment]
{"message": "Cuckoo Agent!", "version": "0.8", "features": ["execpy", "pinning", "logs", "largefile", "unicodepath"]}

**Comment by giveitatry168** [comment]
Looks like the connection is fine. The host can also be ping from analysis VM. But the log shows the host was unable to connect to analysis. I've verified analysis is up and running. Below is the log:

2018-06-22 14:37:19,386 [cuckoo.core.scheduler] INFO: Task #1: acquired machine xxx (label=xxx)
2018-06-22 14:37:19,393 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 8420 (interface=eth0, host=xxx)
2018-06-22 14:37:19,393 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2018-06-22 14:37:19,579 [cuckoo.machinery.vsphere] INFO: Reverting machine xxx to snapshot xxx-001
2018-06-22 14:37:28,699 [cuckoo.core.guest] INFO: Starting analysis on guest (id=xxx, ip=xxx)
2018-06-22 14:37:29,703 [cuckoo.core.guest] DEBUG: analysis1: not ready yet
2018-06-22 14:37:30,708 [cuckoo.core.guest] DEBUG: analysis1: not ready yet
...
2018-06-22 14:40:28,859 [cuckoo.core.scheduler] ERROR: Error from machine 'xxx': it appears that this
 Virtual Machine hasn't been configured properly as the Cuckoo Host wasn't able to connect to the Guest. Th
ere could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/doc
s/faq/index.html#troubleshooting-vm-network-configuration
2018-06-22 14:40:28,866 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cuckoo/core/plugins.py", line 163, in stop
    module.stop()
  File "/usr/lib64/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 156, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = ''
 and stderr = 'tcpdump: eth0: No such device exists\n(SIOCGIFHWADDR: No such device)\n'. Did you enable the
 extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter onl
y applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permi
ssion-denied-for-tcpdump)?
2018-06-22 14:40:29,028 [cuckoo.machinery.vsphere] INFO: Powering off virtual machine Win10Horizon
2018-06-22 14:40:30,073 [cuckoo.core.scheduler] DEBUG: Released database task #1
2018-06-22 14:40:30,103 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #1
2018-06-22 14:40:30,104 [cuckoo.processing.behavior] WARNING: Analysis results folder does not exist at pat
h '/home/cuckoo/.cuckoo/storage/analyses/1/logs'.

**Comment by giveitatry168** [comment]
Is there a way to stop Cuckoo from Powering off the analysis machine?
> 2018-06-22 14:40:29,028 [cuckoo.machinery.vsphere] INFO: Powering off virtual machine xxx

**Comment by doomedraven** [comment]
you have problem with tcpdump, see documentation you have link in error, if that doesn't work see my pull requests.

no, that is correct, cuckoo should do that. why do you need to not stop it?

**Comment by giveitatry168** [comment]
Thanks! Tcpdump fixed.

I would expect the VM will be reverted after examining a sample. Shutdown the VM requires the admin to bring it up manually.

**Comment by giveitatry168** [comment]
I would guess it always shuts down the VM after a sample has been analyzed, then revert to snapshot.
