### ISSUE TITLE
Errors running analysis on physical guest

### ISSUE THREAD

**Issue by cuckool** [cuckoosandbox/cuckoo#1878]
Hello,
I would like to run Cuckoo on a physical machine. Because of the issue #1396 , I have installed Cuckoo version 2.0.4 on Debian 9. On my physical guest, I have the old agent (the one from the version 2.0-rc2). 
The analysis launch without any problem but I keep getting the same error : 
```

2017-10-06 19:17:18,757 [cuckoo.core.startup] INFO: Updated running task ID 1 status to failed_analysis
2017-10-06 19:17:18,766 [cuckoo.core.startup] WARNING: Unable to import yara (please compile from sources)
2017-10-06 19:17:18,768 [cuckoo.core.scheduler] INFO: Using "physical" as machine manager
2017-10-06 19:17:18,948 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-10-06 19:17:18,964 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-10-06 19:17:20,038 [cuckoo.core.scheduler] INFO: Starting analysis of URL "google.com" (task #2, options "")
2017-10-06 19:17:20,073 [cuckoo.core.scheduler] INFO: Task #2: acquired machine cuckooG (label=cuckooG)
2017-10-06 19:17:20,080 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 14705 (interface=ens38, host=169.254.0.10, pcap=/home/cuckoo/.cuckoo/storage/analyses/2/dump.pcap)
2017-10-06 19:17:20,148 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckooG, ip=169.254.0.10)
2017-10-06 19:19:26,377 [cuckoo.core.guest] INFO: cuckooG: analysis completed successfully
2017-10-06 19:19:26,400 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 160, in stop
    module.stop()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 150, in stop
    "to Ubuntu-based distributions with AppArmor)?" % (out, err)
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = "tcpdump: ens38: You don't have permission to capture on that device\n(socket: Operation not permitted)\n". Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor)?
2017-10-06 19:19:26,459 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 594, in launch_analysis
    machinery.stop(self.machine.label)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/machinery/physical.py", line 103, in stop
    output = subprocess.check_output(args)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
 I installed Cuckoo following the doc for versions 2.0.1

Here is my physical.conf file : 
```
[physical]
# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. physical1,physical2,physical3)
machines = cuckooG

# Credentials to access the machine
user = mat
password = mat

# Default network interface.
interface = ens38

[fog]
# Credentials to access the FOG website. We're using basic screenscraping
# techniques to programmatically schedule new "image download tasks", i.e., to
# instruct FOG to make a laptop restore the original image on the next reboot.
# Note: if you're using FOG to manage your physical machines without the
# cronjob functionality as per documentation you *will* have to change the
# following "none" to "localhost" or similar (the "none" is for backwards
# compatibility where users are still using the cronjob-style tasking, and
# thus effectively ignore the FOG integration). The FOG functionality has only
# been tested against the FOG 1.2.0 stable release.
hostname = 169.254.0.16
username = fog
password = password


[cuckooG]
# Specify the label name of the current machine as specified in your
# physical machine configuration.
label = cuckooG

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current machine. Make sure that the IP address
# is valid and that the host machine is able to reach it. If not, the analysis
# will fail.
ip = 169.254.0.10
```

My cuckoo.conf is configured to use the physical machinery and the result server is the IP of my Cuckoo host. These are the only modification on my configuration files.

I have tried to reinstall Cuckoo multiple time, with different version and several Linux distributions.

**Comment by cuckool** [comment]
In addition I'd like to state that a report folder is created, it contains screenshots, files, logs and the binary. However, the processing part is missing.

I resolved the issue with the sniffer (a simple chmod -R 7777 /usr/sbin/tcpdump).

**Comment by RicoVZ** [comment]
Hello Cuckool,

This error indicates a binary used to send the shutdown command is missing.

See http://docs.cuckoosandbox.org/en/latest/installation/guest_physical/requirements/#additional-host-requirements

It states the Cuckoo host needs the 'samba-common-bin' package.

**Comment by cuckool** [comment]
Damn, I guess I skipped this part... Sorry for the disturbance. I'll install this package right away ! Thanks a lot RicoVZ.
