### ISSUE TITLE
UnicodeEncodeError: in filename

### ISSUE THREAD

**Issue by mschneider82** [cuckoosandbox/cuckoo#1880]
Hello,

I got the following error trying process a pdf file with the german letter ü included in the filename.
The analyse works fine by renaming the letter 'ü' to 'ue'.

```
Traceback (most recent call last):
  File "C:/tmptdqbsl/analyzer.py", line 794, in <module>
    success = analyzer.run()
  File "C:/tmptdqbsl/analyzer.py", line 649, in run
    pids = self.package.start(self.target)
  File "C:\tmptdqbsl\modules\packages\pdf.py", line 69, in start
    trigger="file:%s" % path
  File "C:\tmptdqbsl\lib\common\abstracts.py", line 163, in execute
    maximize=maximize, env=env, trigger=trigger):
  File "C:\tmptdqbsl\lib\api\process.py", line 288, in execute
    output = subprocess_checkoutput(argv, env)
  File "C:\tmptdqbsl\lib\api\process.py", line 32, in subprocess_checkoutput
    args, stdin=subprocess.PIPE, stderr=subprocess.PIPE, env=env,
  File "C:\Python27\lib\subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 144: ordinal not in range(128)
```

**Comment by RicoVZ** [comment]
Hey mschneider82,

Could you tell us what version of Cuckoo you are using?

**Comment by mschneider82** [comment]
Hi i am running Version 2.0.4
the file was uploaded from a windows PC by using the webinterface

**Comment by jbremer** [comment]
Thanks! This might an issue specific to documents (i.e., PDFs & Office documents), we'll have a further look at it.

**Comment by RealLinkers** [comment]
Hello, I am experiencing a similar problem.

Traceback (most recent call last):
  File "C:/tmprhrlmz/analyzer.py", line 794, in <module>
    success = analyzer.run()
  File "C:/tmprhrlmz/analyzer.py", line 649, in run
    pids = self.package.start(self.target)
  File "C:\tmprhrlmz\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmprhrlmz\lib\common\abstracts.py", line 165, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

**Comment by mgesp** [comment]
Hi, I'm having the same issue with Office documents that have "special" characters such as á, é, í and so on...

Traceback (most recent call last):
  File "C:/tmpeel8xc/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmpeel8xc/analyzer.py", line 650, in run
    pids = self.package.start(self.target)
  File "C:\tmpeel8xc\modules\packages\xls.py", line 62, in start
    excel, args=[path], mode="office", trigger="file:%s" % path
  File "C:\tmpeel8xc\lib\common\abstracts.py", line 164, in execute
    maximize=maximize, env=env, trigger=trigger):
  File "C:\tmpeel8xc\lib\api\process.py", line 275, in execute
    output = subprocess_checkoutput(argv, env)
  File "C:\tmpeel8xc\lib\api\process.py", line 32, in subprocess_checkoutput
    args, stdin=subprocess.PIPE, stderr=subprocess.PIPE, env=env,
  File "C:\Python27\lib\subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 134: ordinal not in range(128)

This is also resolved when changing those characters.

Thanks!

**Comment by jbremer** [comment]
Thanks, we can definitely reproduce this - have to find a proper solution though as it appears to be non-trivial so far.

**Comment by jbremer** [comment]
Cuckoo Monitor binaries have now been pushed and included in Cuckoo's automated migration code. In other words, the functionality here is all ready for usage.

**Comment by jbremer** [comment]
This is part of our `2.0.6` release, closing as resolved. Thanks!
