### ISSUE TITLE
adapters.py raises ConnectionErrorwith Connection aborted.', BadStatusLine("''",)

### ISSUE THREAD

**Issue by vikram-rajpuro** [cuckoosandbox/cuckoo#1893]
As soon as I provide samples from web console it starts virtual box and terminates it with below error message. My host and guest are connected and agent also working please point me out where things went wrong.

2017-10-12 17:02:49,943 [cuckoo.core.guest] INFO: Starting analysis on guest (id=MACOS_1, ip=192.168.56.101)
2017-10-12 17:02:50,951 [cuckoo.core.guest] DEBUG: MACOS_1: not ready yet
2017-10-12 17:02:51,959 [cuckoo.core.guest] DEBUG: MACOS_1: not ready yet
2017-10-12 17:02:52,967 [cuckoo.core.guest] DEBUG: MACOS_1: not ready yet
2017-10-12 17:02:53,975 [cuckoo.core.guest] DEBUG: MACOS_1: not ready yet
2017-10-12 17:02:54,980 [cuckoo.core.guest] DEBUG: MACOS_1: not ready yet
2017-10-12 17:02:55,987 [cuckoo.core.guest] DEBUG: MACOS_1: not ready yet
2017-10-12 17:02:57,030 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=MACOS_1, ip=192.168.56.101)
2017-10-12 17:02:57,040 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=MACOS_1, ip=192.168.56.101, monitor=latest, size=108827)
2017-10-12 17:02:57,082 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: MITM
2017-10-12 17:02:57,083 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2017-10-12 17:02:57,083 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm MACOS_1
2017-10-12 17:02:58,342 [cuckoo.core.scheduler] **ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):**
File "/Users/ashutosh/venv/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 698, in run
self.launch_analysis()
File "/Users/ashutosh/venv/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 499, in launch_analysis
self.guest_manage(options)
File "/Users/ashutosh/venv/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
self.guest_manager.start_analysis(options, monitor)
File "/Users/ashutosh/venv/lib/python2.7/site-packages/cuckoo/core/guest.py", line 465, in start_analysis
self.upload_analyzer(monitor)
File "/Users/ashutosh/venv/lib/python2.7/site-packages/cuckoo/core/guest.py", line 372, in upload_analyzer
self.determine_analyzer_path()
File "/Users/ashutosh/venv/lib/python2.7/site-packages/cuckoo/core/guest.py", line 350, in determine_analyzer_path
r = self.post("/mkdtemp", data={"dirpath": systemdrive})
File "/Users/ashutosh/venv/lib/python2.7/site-packages/cuckoo/core/guest.py", line 311, in post
r = session.post(url, *args, **kwargs)
File "/Users/ashutosh/venv/lib/python2.7/site-packages/requests/sessions.py", line 535, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/Users/ashutosh/venv/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
resp = self.send(prep, **send_kwargs)
File "/Users/ashutosh/venv/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
r = adapter.send(request, **kwargs)
File "/Users/ashutosh/venv/lib/python2.7/site-packages/requests/**adapters.py**", line 473, in send
**raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))**

Regards,
Vikram Sinha

**Comment by daanfs** [comment]
See also https://github.com/cuckoosandbox/cuckoo/issues/1876. Is the `agent.py` running as root inside your guest? 

It might be worth improving the `agent.py` error reporting instead of silently failing here.

**Comment by jbremer** [comment]
Please do @daanfs! :)

**Comment by jbremer** [comment]
The fix for the mentioned issue has now been resolved! Please check it out.

**Comment by vikram-rajpuro** [comment]
Hello
Greetings.

Thanks Jurriaan Bremer.

Best Regards,
Vikram Sinha.

**Comment by vikram-rajpuro** [comment]
As of now I am able to analyse samples but there is network issue between my guest to host communication. I am able to ping a request from guest to host and host to guest with no problem but my guest is not connected with internet.
So when a provide samples from my web console process fails with the gives error like the below screenshot- : 

![screen shot 2017-10-31 at 12 22 36 pm](https://user-images.githubusercontent.com/16700728/32210950-5135db42-be36-11e7-802c-3b85c6dff6a7.png)

@daanfs where should I check; which package is not got imported; where should I find it; and which module makes this error - : xmlrpclib.ProtocolError:  <ProtocolError for 127.0.0.1:8080/RPC2: 404 Not Found>

thanks for your help till now.

br,
Vikram Sinha

**Comment by seantree** [comment]
@jbremer can you also suggest what to do with this problem?

**Comment by daanfs** [comment]
@vikram-rajpuro: Can you try specifying a package using the `--package` option when submitting a file via the command line? Try `bash`, `macho`, `app`, or `zip` depending on the sample you are submitting.

**Comment by seantree** [comment]
Hi @daanfs ,

I am also getting the same problem and yes I tried to submit the sample through terminal on the below link you can check that it's generating the new error:
https://github.com/cuckoosandbox/cuckoo/issues/1849

**Comment by vikram-rajpuro** [comment]
@daanfs  by specifying the package is shows that my package.py file throwing the exception - : 
File "/tmp_ApzEw/lib/core/packages.py", line 31, in choose_package_class "exist.".format(name)) Exception: Unable to import package "None": it does not exist.

Please let me know if I am going in the write direction... @jbremer @doomedraven

**Comment by doomedraven** [comment]
bcz for linux there only generic package, update sflock to latest version and it will recognize package correctly automatically

**Comment by vikram-rajpuro** [comment]
@doomedraven If there is only generic package available for linux then how many packages are available for Mac... After all I am willing setup the sandbox environment for Mac Malware analysis.

@daanfs @jbremer

**Comment by doomedraven** [comment]
i not checked but i think also only generic

**Comment by vikram-rajpuro** [comment]
@doomedraven  I checked and there are available packages for Mac e.g.. app, bash, macho, zip but still giving error "Analysis failed: Could not find an appropriate analysis package" 

I am providing the Mac-O file for analysis

**Comment by vikram-rajpuro** [comment]
The another setup which I tried is : [https://github.com/alonlavian/cuckoo](url)

**Comment by jbremer** [comment]
So, what's the end result @vikram-rajpuro ? Is it working or not?

**Comment by vikram-rajpuro** [comment]
Not completely @jbremer; file monitor is not working so the paths are not getting recorded. otherwise
receiving all other information related to infected file.
