### ISSUE TITLE
Incomplete possible TLS Handshake record found and unable to connect back

### ISSUE THREAD

**Issue by aflick2486** [cuckoosandbox/cuckoo#1898]
Having an issue when analyzing a file, Cuckoo is able to run the Guest environment, but after a minute or two it throws errors like this:

``` 2017-10-17 09:34:09,260 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "file.pdf" (task #13, options "enable-services=False,procmemdump=yes,route=none")
2017-10-17 09:34:09,296 [cuckoo.core.scheduler] INFO: Task #13: acquired machine cuckoo1 (label=winbox-7)
2017-10-17 09:34:09,348 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 3773 (interface=vboxnet0, host=192.168.56.101, pcap=/usr/local/cuckoo/.cuckoo/storage/analyses/13/dump.pcap)
2017-10-17 09:34:14,055 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2017-10-17 09:37:14,959 [cuckoo.core.scheduler] ERROR: Error from machine 'cuckoo1': it appears that this Virtual Machine hasn't been configured properly as the Cuckoo Host wasn't able to connect to the Guest. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2017-10-17 09:37:16,413 [cuckoo.processing.behavior] WARNING: Analysis results folder does not exist at path '/usr/local/cuckoo/.cuckoo/storage/analyses/13/logs'.
2017-10-17 09:37:20,032 [cuckoo.processing.network] ERROR: Incomplete possible TLS Handshake record found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/network.py", line 540, in _https_identify
    record = dpkt.ssl.RECORD_TYPES[record.type](record.data)
  File "/usr/local/lib/python2.7/dist-packages/dpkt/dpkt.py", line 87, in __init__
    self.unpack(args[0])
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ssl.py", line 336, in unpack
    raise dpkt.NeedData
NeedData
2017-10-17 09:37:20,157 [cuckoo.processing.network] ERROR: Incomplete possible TLS Handshake record found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/network.py", line 540, in _https_identify
    record = dpkt.ssl.RECORD_TYPES[record.type](record.data)
  File "/usr/local/lib/python2.7/dist-packages/dpkt/dpkt.py", line 87, in __init__
    self.unpack(args[0])
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ssl.py", line 336, in unpack
    raise dpkt.NeedData
NeedData
2017-10-17 09:37:23,636 [cuckoo.processing.debug] ERROR: Error processing task #13: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2017-10-17 09:37:26,646 [cuckoo.core.scheduler] INFO: Task #13: reports generation completed (path=/usr/local/cuckoo/.cuckoo/storage/analyses/13)
2017-10-17 09:37:26,667 [cuckoo.core.scheduler] INFO: Task #13: analysis procedure completed
```
I believe I have all of the networking configured correctly because I can ping from the Cuckoo host to the Guest and vice versa and the Guest is using Virtual Box host only with all firewalls turned off. Any help is greatly appreciated thank you!

**Comment by jbremer** [comment]
Not a very critical error, but we'd be happy to take a look if you share the PCAP. Thanks in advance.

**Comment by nicpenning** [comment]
I found a website that when analyzed triggers this as well except for it hangs and does not finish the analysis.

Try submitting this URL, without the [] of course.

https[:]//downloads[.]bluebeam[.]com[:]443/software/downloads/2017.0.30/vu/BbVu2017.0.30.exe

**Comment by jbremer** [comment]
Can't do much without PCAPs. Closing issue due to that. Please reopen if you have some PCAPs for us.

**Comment by PoolHell** [comment]
[dump_https_error.zip](https://github.com/cuckoosandbox/cuckoo/files/4203709/dump_https_error.zip)
