### ISSUE TITLE
Cuckoo wired Error on Agent

### ISSUE THREAD

**Issue by cuckoouser** [cuckoosandbox/cuckoo#1918]
Hello,
I'm using cuckoo v2.0.4, with VirtualBox
I have an agent with python 2.7 in it, Windows7.
been trying to run an exe file on cuckoo (all configured and installed as your guide), for example calc.exe.
and I get this error:
"""
Error from the Cuckoo Guest: Analysis failed: Unable to execute the initial process, analysis aborted. Traceback (most recent call last): File "C:\wbkfmdd\analyzer.py", line 794, in <module> success = analyzer.run() File "C:\wbkfmdd\analyzer.py", line 649, in run pids = self.package.start(self.target) File "C:\wbkfmdd\modules\packages\exe.py", line 23, in start return self.execute(path, args=shlex.split(args)) File "C:\wbkfmdd\lib\common\abstracts.py", line 165, in execute "Unable to execute the initial process, analysis aborted." CuckooPackageError: Unable to execute the initial process, analysis aborted. 
"""
I saw that after running there are some wired\random strings folders with a lot of empty Python files in it, like abstracts.py (all on agent), the file that is in the error is empty.

I hope I get replication from you guys !! I`d really want to use cuckoo sandbox.

**Comment by gugronnier** [comment]
same error here: https://github.com/cuckoosandbox/cuckoo/issues/1672
but problem not solved for cuckoo 2.0.5

for cuckoo 2.0.4, update your cuckoo version

**Comment by jbremer** [comment]
Please share a sample. Will be closing this issue otherwise.

**Comment by gugronnier** [comment]
the link to my sample : 
https://mega.nz/#!oEkRBIwY!4kQMJI1IKbxS5M_6yDM9hZy4t4o4q3lT73vNwI1nCAk

my version is already updated, i installed it last week (github version)

**Comment by gugronnier** [comment]
i also find the source code of this sample, but i can't share it here (it is not secure)

**Comment by gugronnier** [comment]
if you want it, contact me by mail with my public gpg key.
