### ISSUE TITLE
AttributeError: function 'SHGetKnownFolderPath' not found

### ISSUE THREAD

**Issue by eskriett** [cuckoosandbox/cuckoo#1934]
The [RecentFiles](https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data/analyzer/windows/modules/auxiliary/recentfiles.py) auxiliary module does not run on Windows XP as the [`SHGetKnownFolderPath`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762188(v=vs.85).aspx) Shell32.dll call is only defined for Windows Vista and above. The following error occurs during runtime:

```
2017-11-03 07:43:24,335 [analyzer] ERROR: Auxiliary module RecentFiles was not implemented
Traceback (most recent call last):
  File "C:/tmp3dszd_/analyzer.py", line 623, in run
    aux.start()
  File "C:\tmp3dszd_\modules\auxiliary\recentfiles.py", line 55, in start
    dirpath = self.get_path()
  File "C:\tmp3dszd_\modules\auxiliary\recentfiles.py", line 43, in get_path
    r = SHELL32.SHGetKnownFolderPath(
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SHGetKnownFolderPath' not found
```

Is Windows XP still supported by Cuckoo? If it is, it may be worth checking the OS version first, and if running below Vista, falling back to [`SHGetFolderPath`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762181(v=vs.85).aspx). If it's not (which would be a shame), it may be worth updating the documentation to make this clearer.

**Comment by jbremer** [comment]
Heh, interesting! Been a while since I ran Cuckoo on Windows XP myself, but this should obviously have been caught by our functional unit tests. Will fix it soon'ish!

**Comment by johnnymythology** [comment]
I am currently setting up Windows XP for Cuckoo Sandbox and experienced the same issue as well. After studying the function "SHGetKnownFolderPath", it is no longer support for version Windows Vista and down. For backward compatibility, Windows is using "SHGetFolderPathA" function. I lack the experience in Windows Programming and hence, is unable to provide the necessary changes to this new function. 

However, this does not mean that Windows XP is not supported!

If you access the recentfiles.py file from the host OS (Ubuntu in my case), you can navigate to /.cuckoo/analyzer/windows/modules/auxiliary/recentfiles.py (Cuckoo will basically create a temporary folder in the Guest Windows OS with all these files) and comment out the function that is causing this error. From my understanding, this SHGetFolderPath is only used for logging purposes and does not affect the intention of this file. (Please correct me if I am wrong). I managed to run cuckoo without any issues after commenting out.

`#r = SHELL32.SHGetKnownFolderPath(
 #           uuid.UUID(self.locations[location]).get_bytes_le(),
 #           0, None, ctypes.byref(dirpath)
 #      )
 #       if r:
 #           log.warning("Error obtaining user directory: 0x%08x", r)
 #           return`
