### ISSUE TITLE
Warning Win10 analysis caught an exception

### ISSUE THREAD

**Issue by hackdefendr** [cuckoosandbox/cuckoo#1936]
`2017-11-05 14:43:21,988 [cuckoo.core.guest] WARNING: Win10: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpquacvd/analyzer.py", line 794, in <module>
    success = analyzer.run()
  File "C:/tmpquacvd/analyzer.py", line 649, in run
    pids = self.package.start(self.target)
  File "C:\tmpquacvd\modules\packages\pdf.py", line 69, in start
    trigger="file:%s" % path
  File "C:\tmpquacvd\lib\common\abstracts.py", line 158, in execute
    self.init_regkeys(self.REGKEYS)
  File "C:\tmpquacvd\lib\common\abstracts.py", line 114, in init_regkeys
    key_handle = CreateKey(rootkey, subkey)
WindowsError: [Error 5] Access is denied`

My problem with this error is that an EXE analysis works just fine. When I try to analyze anything else I get this Access Denied error with no hint as to what access is being denied.

**Comment by hackdefendr** [comment]
For completeness I created a Windows 7 (32-bit) VM to run the same test against.  I got the same error.

WHAT IS BEING DENIED???

**Comment by josu98** [comment]
Have the same problem but with a Win8.1 32 bit VM. The analysis completes though and a "empty" report is created.

**Comment by josu98** [comment]
Works fine with XP VM.
