### ISSUE TITLE
MongoDB issue after Update to latest version

### ISSUE THREAD

**Issue by RealLinkers** [cuckoosandbox/cuckoo#1937]
Hello, 

I am running 
MongoDB shell version: 2.6.10
Cuckoo Sandbox 2.0.4

Ports are correct, netstat -ano shows it is listening on the correct port.
I also tried the following solution, removing lock file and repairing:
https://stackoverflow.com/questions/6857781/what-is-the-use-of-the-mongo-lock-file
I also have deleted the database and let the process create it again.
Mysql.sock file removal has been tested aswell.

Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 614, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 263, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)

mongolog shows only that it has started up

Nothing seems to be helping at the moment.
Any assistance will be very much appreciated.

PIP FREEZE
alembic==0.8.8
androguard==3.0.1
argh==0.26.2
asn1crypto==0.23.0
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.5.3
blinker==1.4
bottle==0.12.7
brotlipy==0.6.0
capstone==3.0.5rc2
certifi==2017.7.27.1
cffi==1.11.2
chardet==2.3.0
clamd==1.0.2
click==6.6
colorama==0.3.7
ConfigArgParse==0.11.0
construct==2.5.3
cryptography==1.5.3
cssutils==1.0.2
Cuckoo==2.0.4.4
distorm3==3.3.4
Django==1.8.4
django-extensions==1.6.7
dmidecode==0.8.1
dpkt==1.8.7
dumbnet==1.12
ecdsa==0.13
EditorConfig==0.12.1
egghatch==0.2.1
elasticsearch==5.3.0
enum34==1.1.6
et-xmlfile==1.0.1
ez-setup==0.9
Flask==0.12.2
Flask-SQLAlchemy==2.1
functools32==3.2.3.post2
h2==2.4.4
hpack==2.3.0
html2text==2016.9.19
HTTPReplay==0.2.1
hyperframe==4.0.2
idna==2.6
ipaddress==1.0.18
itsdangerous==0.24
jdcal==1.3
Jinja2==2.9.6
jsbeautifier==1.6.2
jsonschema==2.6.0
libvirt-python==1.3.1
lxml==3.6.0
M2Crypto==0.24.0
Magic-file-extensions==0.2
Mako==1.0.7
MarkupSafe==1.0
meld3==1.0.2
mitmproxy==0.18.2
MySQL-python==1.2.5
mysqlclient==1.3.12
olefile==0.43
oletools==0.42
openpyxl==2.4.9
passlib==1.6.5
pathtools==0.1.2
peepdf==0.3.6
pefile==1.2.10.post139
pefile2==1.2.11
Pillow==3.2.0
psycopg2==2.7.3.2
pyasn1==0.1.9
pycparser==2.18
pycrypto==2.6.1
pydeep==0.2
pyelftools==0.24
pymisp==2.4.54
pymongo==3.0.3
pyOpenSSL==16.2.0
pyparsing==2.1.10
pyperclip==1.5.32
python-dateutil==2.4.2
python-editor==1.0.3
python-magic==0.4.12
pythonaes==1.0
pytz==2017.2
PyYAML==3.12
requests==2.13.0
scapy==2.3.2
SFlock==0.2.17
singledispatch==3.4.0.3
six==1.10.0
SQLAlchemy==1.0.8
sqlparse==0.1.18
supervisor==3.2.0
tlslite-ng==0.6.0
tornado==4.4.3
typing==3.5.2.2
ujson==1.35
unicorn==1.0.1
unity-lens-photos==1.0
urllib3==1.22
urwid==1.3.1
virtualenv==15.0.1
VMCloak==0.4.4
volatility==2.6
wakeonlan==0.2.2
watchdog==0.8.3
Werkzeug==0.12.2
yara-python==3.6.3

**Comment by RealLinkers** [comment]
It seems that I have fixed the issue via removing a few YARA rules. They seemed to be crashing the process of dumping the data to MongoDB.
