### ISSUE TITLE
Catch an exception while analysing jigsaw ransonware sample.

### ISSUE THREAD

**Issue by allanng78** [cuckoosandbox/cuckoo#1953]
Hi Guy,
I received this error when analysing ransomware. Please help. 

2017-11-14 11:50:27,630 [cuckoo.core.guest] WARNING: win7_1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpl5a5gj/analyzer.py", line 794, in <module>
    success = analyzer.run()
  File "C:/tmpl5a5gj/analyzer.py", line 649, in run
    pids = self.package.start(self.target)
  File "C:\tmpl5a5gj\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmpl5a5gj\lib\common\abstracts.py", line 165, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

**Comment by allanng78** [comment]
I am running win7 64bit virtualbox VM. The network is on hostonly. Software such as .net 3.5,4,4.5.1,4.5.2, 6.5, java sdk, ms office 2013, adobe reader are installed.

**Comment by RicoVZ** [comment]
Hi allang78.

Could you please also post the analyzer log (called analysis.log) for this analysis?
This log might show some more information on why the process could not be started.

Thanks!
