### ISSUE TITLE
Unable to submit sample though Cuckoo GUI

### ISSUE THREAD

**Issue by rehanalam1** [cuckoosandbox/cuckoo#1964]
Hi There,

Till yesterday we had our cuckoo in working condition.  But today I see (after reboot) I'm unable to submit file though browser (chrome + Firefox). It keeps saying 

> Loading your submitted files

 under "submit file >> configure".  I'm using cuckoo 2.0.4. 

However its working fine in through terminal. Could you please help me out?

**Comment by doomedraven** [comment]
first of all post the error from console where web is started, so we can get some clues what is wrong

**Comment by rehanalam1** [comment]
> cuckoo@man:~/.cuckoo/web## cuckoo web runserver
Performing system checks...

System check identified no issues (0 silenced).
November 17, 2017 - 12:18:15
Django version 1.8.4, using settings 'cuckoo.web.web.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[17/Nov/2017 12:18:47] "GET / HTTP/1.1" 200 25510
[17/Nov/2017 12:18:48] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/css/vendor.css HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/vendor.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/css/main.css HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[17/Nov/2017 12:18:48] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[17/Nov/2017 12:18:50] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[17/Nov/2017 12:18:50] "GET /static/fonts/Roboto_normal_500_default.woff HTTP/1.1" 304 0
[17/Nov/2017 12:18:50] "GET /static/fonts/Roboto_normal_700_default.woff HTTP/1.1" 304 0
[17/Nov/2017 12:18:50] "GET /static/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 0
[17/Nov/2017 12:18:50] "GET /static/images/loading.gif HTTP/1.1" 304 0
[17/Nov/2017 12:18:50] "GET /static/images/next.png HTTP/1.1" 304 0
[17/Nov/2017 12:18:50] "GET /static/images/prev.png HTTP/1.1" 304 0
[17/Nov/2017 12:18:50] "GET /static/images/close.png HTTP/1.1" 304 0
[17/Nov/2017 12:18:50] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 702
[17/Nov/2017 12:18:52] "GET /cuckoo/api/status HTTP/1.1" 200 556
[17/Nov/2017 12:19:15] "GET / HTTP/1.1" 200 25510
[17/Nov/2017 12:19:16] "GET /static/css/vendor.css HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/vendor.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/css/main.css HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[17/Nov/2017 12:19:16] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[17/Nov/2017 12:19:18] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[17/Nov/2017 12:19:18] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[17/Nov/2017 12:19:18] "GET /static/images/prev.png HTTP/1.1" 304 0
[17/Nov/2017 12:19:18] "GET /static/images/loading.gif HTTP/1.1" 304 0
[17/Nov/2017 12:19:18] "GET /static/images/next.png HTTP/1.1" 304 0
[17/Nov/2017 12:19:18] "GET /static/images/close.png HTTP/1.1" 304 0
[17/Nov/2017 12:19:18] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 702
[17/Nov/2017 12:19:19] "GET /cuckoo/api/status HTTP/1.1" 200 555
[17/Nov/2017 12:20:26] "GET / HTTP/1.1" 200 25510
[17/Nov/2017 12:20:26] "GET /static/js/vendor.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/css/vendor.css HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/css/main.css HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[17/Nov/2017 12:20:26] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[17/Nov/2017 12:20:28] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[17/Nov/2017 12:20:28] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[17/Nov/2017 12:20:28] "GET /static/images/prev.png HTTP/1.1" 304 0
[17/Nov/2017 12:20:28] "GET /static/images/loading.gif HTTP/1.1" 304 0
[17/Nov/2017 12:20:28] "GET /static/images/next.png HTTP/1.1" 304 0
[17/Nov/2017 12:20:28] "GET /static/images/close.png HTTP/1.1" 304 0
[17/Nov/2017 12:20:28] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 702
[17/Nov/2017 12:20:28] "GET /cuckoo/api/status HTTP/1.1" 200 556
[17/Nov/2017 12:22:41] "GET / HTTP/1.1" 200 25510
[17/Nov/2017 12:22:42] "GET /static/css/vendor.css HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/css/main.css HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/vendor.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[17/Nov/2017 12:22:42] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[17/Nov/2017 12:22:43] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[17/Nov/2017 12:22:43] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[17/Nov/2017 12:22:43] "GET /static/images/prev.png HTTP/1.1" 304 0
[17/Nov/2017 12:22:43] "GET /static/images/loading.gif HTTP/1.1" 304 0
[17/Nov/2017 12:22:43] "GET /static/images/next.png HTTP/1.1" 304 0
[17/Nov/2017 12:22:44] "GET /static/images/close.png HTTP/1.1" 304 0
[17/Nov/2017 12:22:44] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 702
[17/Nov/2017 12:22:44] "GET /cuckoo/api/status HTTP/1.1" 200 556
[17/Nov/2017 12:23:30] "GET / HTTP/1.1" 200 25510
[17/Nov/2017 12:23:31] "GET /static/css/vendor.css HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/vendor.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/css/main.css HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:31] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:32] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:32] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:32] "GET /static/images/next.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:32] "GET /static/images/loading.gif HTTP/1.1" 304 0
[17/Nov/2017 12:23:32] "GET /static/images/prev.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:32] "GET /static/images/close.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:32] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 702
[17/Nov/2017 12:23:33] "GET /cuckoo/api/status HTTP/1.1" 200 557
[17/Nov/2017 12:23:39] "POST /submit/api/presubmit/ HTTP/1.1" 302 0
[17/Nov/2017 12:23:39] "GET /submit/pre/20/ HTTP/1.1" 200 20152
[17/Nov/2017 12:23:41] "GET /submit/pre/20/ HTTP/1.1" 200 20152
[17/Nov/2017 12:23:41] "GET /static/css/vendor.css HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/handlebars-templates.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/css/main.css HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/hexdump.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/vendor.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/loader.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/analysis_sidebar.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/sticky.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/submission.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/process_tree.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/recent.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/analysis_network.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/analysis_export.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/app.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/js/cuckoo/analysis_feedback.js HTTP/1.1" 304 0
[17/Nov/2017 12:23:41] "GET /static/favicon-32x32.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:42] "GET /static/graphic/cuckoo_inverse.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:42] "GET /static/graphic/cuckoo-coffee-cup.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:42] "GET /static/images/next.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:42] "GET /static/images/prev.png HTTP/1.1" 304 0
[17/Nov/2017 12:23:42] "GET /static/images/loading.gif HTTP/1.1" 304 0
[17/Nov/2017 12:23:42] "GET /static/images/close.png HTTP/1.1" 304 0
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.4.4', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 552, in web
    ("cuckoo",) + args
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 49, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 88, in handle
    self.run(**options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 97, in run
    autoreload.main(self.inner_run, None, options)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 325, in main
    reloader(wrapped_main_func, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 296, in python_reloader
    exit_code = restart_with_reloader()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 282, in restart_with_reloader
    exit_code = os.spawnve(os.P_WAIT, sys.executable, args, new_environ)
  File "/usr/lib/python2.7/os.py", line 575, in spawnve
    return _spawnvef(mode, file, args, env, execve)
  File "/usr/lib/python2.7/os.py", line 548, in _spawnvef
    wpid, sts = waitpid(pid, 0)
OSError: [Errno 4] Interrupted system call
cuckoo@man:~/.cuckoo/web# [17/Nov/2017 12:25:13] "POST /submit/api/filetree/ HTTP/1.1" 200 795
- Broken pipe from ('192.168.15.135', 36978)


Here is the web console logs/error.

**Comment by rehanalam1** [comment]
@doomedraven further I could substantiate that the issue is only happening when I try to submit PDF sample. I tried with both infected sample and clean one, but both failed.

However, earlier, I could analyze pdf as well. I have installed pdf v9 on guest machine.

**Comment by rehanalam1** [comment]
I tried with new cuckoo installation and basic configuration, first few PDF samples were analyzed but later it stopped working. Started throwing Broken Pipe error.

Any suggestion or help will be much appreciated.
