### ISSUE TITLE
Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by pbsask** [cuckoosandbox/cuckoo#1970]
I have been trying to setup cuckoo for a week now, I have rebuilt the environment 5 times thinking I may have missed something but every time I end up with the same result.

Both the host and the guest are running Ubuntu 16.04

Any pointers would be appreciated.

This is the output on the console when I submit a file:

2017-11-18 12:11:23,875 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "coconut" (task #3, options "procmemdump=yes,route=none")
2017-11-18 12:11:24,012 [cuckoo.core.scheduler] INFO: Task #3: acquired machine Cuckoo-Guest01 (label=Cuckoo-Guest01)
2017-11-18 12:11:24,079 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7659 (interface=vboxnet0, host=192.168.56.101)
2017-11-18 12:11:36,472 [cuckoo.core.guest] INFO: Starting analysis on guest (id=Cuckoo-Guest01, ip=192.168.56.101)
2017-11-18 12:11:39,515 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=Cuckoo-Guest01, ip=192.168.56.101)
2017-11-18 12:11:41,264 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 698, in run
    self.launch_analysis()
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 499, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 465, in start_analysis
    self.upload_analyzer(monitor)
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 372, in upload_analyzer
    self.determine_analyzer_path()
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 350, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 311, in post
    r = session.post(url, *args, **kwargs)
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/cuckoo/sandbox/local/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by doomedraven** [comment]
do search in issues, that is reported many times, and answered ;)

**Comment by pbsask** [comment]
Thanks, I had searched and didnt see anything the first few times, I see it now.

The docs should probably be modified to include running as root if thats a requirement.

http://docs.cuckoosandbox.org/en/0.5/installation/guest/agent/

**Comment by doomedraven** [comment]
first you should check latest http://docs.cuckoosandbox.org/en/latest/installation/guest/agent/ not 0.5 version, and which part exactly?

**Comment by pbsask** [comment]
Its the same in that version

> In the $CWD/agent/ directory you will find the agent.py file. Copy this file to the Guest operating system (in whatever way you want, perhaps a temporary shared folder or by downloading it from a webserver on the host, we recommend the latter) and run it. The Agent will launch a small API server that the host will be able to talk to.

If this said to "run it as root" or with elevated privilege it would mean people following the documents verbatim don't have the same error I did.  Just a suggestion.
