### ISSUE TITLE
Mongodb files 2GB not cleaned

### ISSUE THREAD

**Issue by reynas** [cuckoosandbox/cuckoo#1981]
When performing the delete action using the API, the files get removed but the mongodb files are not touched. /var/lib/mongodb/cuckoo.1 until cuckoo.29 are 2GB each.

Can this be resolved in any way?

**Comment by doomedraven** [comment]
just add 

```
repconf = Config("reporting")

# this required for Iocs API
FULL_DB = False
if repconf.mongodb.enabled:
    import pymongo
    results_db = pymongo.MongoClient(
                     repconf.mongodb.host,
                     repconf.mongodb.port
                 )[repconf.mongodb.db]
    FULL_DB = True
```

and in fund `task_delete` add

```
            if FULL_DB:
                task = results_db.analysis.find_one({"info.id": task_id})
                if task is not None:
                    for processes in task.get("behavior", {}).get("processes", []):
                        [results_db.calls.remove(call) for call in processes.get("calls", [])]

                    results_db.analysis.remove({"info.id": task_id})
```

**Comment by reynas** [comment]
I guess I'll need to add more than this, I'm getting a whole lot of errors
I used reporting:mongodb:enabled  as I got an error the format wasn't correct.
What am I missing here?

Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 7, in <module>
    from cuckoo.main import main
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 16, in <module>
    from cuckoo.apps import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/__init__.py", line 11, in <module>
    from .api import cuckoo_api
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/api.py", line 33, in <module>
    print config("reporting:mongodb:enabled")
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/config.py", line 1057, in config
    file_name, cfg=cfg, strict=strict, raw=raw, loose=loose
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/config.py", line 910, in __init__
    config.read(cfg or cwd("conf", "%s.conf" % file_name))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/misc.py", line 57, in cwd
  File "/usr/local/bin/cuckoo", line 7, in <module>
        from cuckoo.main import main
return os.path.join(_root, *args)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 16, in <module>
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 7, in <module>
    from cuckoo.apps import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/__init__.py", line 11, in <module>
        from cuckoo.main import main
from .api import cuckoo_api
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/api.py", line 33, in <module>
    elif path == '' or path.endswith('/'):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 16, in <module>
        from cuckoo.apps import (
print config("reporting:mongodb:enabled")
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/__init__.py", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/config.py", line 1057, in config
AttributeError: 'NoneType' object has no attribute 'endswith'
    from .api import cuckoo_api
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/api.py", line 33, in <module>
    print config("reporting:mongodb:enabled")
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/config.py", line 1057, in config
    file_name, cfg=cfg, strict=strict, raw=raw, loose=loose
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/config.py", line 910, in __init__
    config.read(cfg or cwd("conf", "%s.conf" % file_name))
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/misc.py", line 57, in cwd
    return os.path.join(_root, *args)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
    file_name, cfg=cfg, strict=strict, raw=raw, loose=loose
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/config.py", line 910, in __init__
    config.read(cfg or cwd("conf", "%s.conf" % file_name))
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/misc.py", line 57, in cwd
    return os.path.join(_root, *args)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by jbremer** [comment]
Don't use `Config()` in a global setting. Cuckoo first needs to initialize the CWD before you can use that. Anyway, we'll be working on this (known) issue in the upcoming months, please stay tuned and for now I'll close this issue.
