### ISSUE TITLE
Cuckoo 2.0.5 API - Internal Server Error

### ISSUE THREAD

**Issue by spiritium** [cuckoosandbox/cuckoo#2016]
Trying to upload files with through the WGUI. The GUI gives me a submission error and the logs show the following:

```
2017-12-15 14:14:52,779 [django.request] ERROR: Internal Server Error: /submit/api/presubmit
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/submission/api.py", line 63, in presubmit
    submit_id = submit_manager.pre(submit_type="files", data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/submit.py", line 140, in pre
    return db.add_submit(path_tmp, submit_type, submit_data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/utils.py", line 199, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 1238, in add_submit
    return submit_id
UnboundLocalError: local variable 'submit_id' referenced before assignment
```

Please let me know if there are any ideas about this. Been looking into this for sometime and can't seem to find a resolution even after re-installation. Thanks!

**Comment by RicoVZ** [comment]
Hi spiritium,

Did you happen to have debug mode enabled? I think there is some database error occuring, before the submit id is retrieved, after which is still tries to return `submit_id`.

Could post you the full log (on a paste service :))? If you did not have debug mode enabled, could you enabled it and see what error is logged by the database, if any? Would be really helpful!

Debug mode can be enabled by starting web like so: `cuckoo --debug web`

**Comment by spiritium** [comment]
Sorry for the delayed reply. I turned on debug mode and got the following meesage:

```
2017-12-18 07:01:08,989 [cuckoo.core.database] DEBUG: Database error adding submit entry: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'INSERT INTO submit (tmp_path, added, submit_type, data) VALUES (?, ?, ?, ?)'] [parameters: ('/tmp/cuckoo-tmp/tmp0GY5Vp', '2017-12-18 12:01:08.987072', 'files', '{"errors": [], "data": [{"data": "/tmp/cuckoo-tmp/tmp0GY5Vp/Task.exe", "type": "file", "options": {}}], "options": {}}')]
```

I looked around and tried to implement the fix in https://github.com/cuckoosandbox/cuckoo/issues/1003, but that did not work.

```
chmod +w db/cuckoo.db
```

**Comment by spiritium** [comment]
Sorry for the delayed reply. I turned on debug mode and got the following meesage:

```
2017-12-18 07:01:08,989 [cuckoo.core.database] DEBUG: Database error adding submit entry: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'INSERT INTO submit (tmp_path, added, submit_type, data) VALUES (?, ?, ?, ?)'] [parameters: ('/tmp/cuckoo-tmp/tmp0GY5Vp', '2017-12-18 12:01:08.987072', 'files', '{"errors": [], "data": [{"data": "/tmp/cuckoo-tmp/tmp0GY5Vp/Task.exe", "type": "file", "options": {}}], "options": {}}')]
```

I looked around and tried to implement the fix in https://github.com/cuckoosandbox/cuckoo/issues/1003, but that did not work.

```
chmod +w db/cuckoo.db
```

**Comment by spiritium** [comment]
Just attempted this again and it finally went through. Issues been resolved. Thank you!
