### ISSUE TITLE
Error on running ./cuckoo.py

### ISSUE THREAD

**Issue by yahyeabukar** [cuckoosandbox/cuckoo#2027]
i have installed cuckoo on ubuntu 16  when i run i got these error, i run ./utils/community.py -waf and sudo -H pip install -r requirements.txt , but still error exists , please can you help me 
codka@ubuntu:~/Downloads/cuckoo$ ./cuckoo.py

  Cuckoo Sandbox 2.0-rc2
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Outdated! Cuckoo Sandbox version 2.1.0 is available now.
2017-12-24 12:16:08,799 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0-rc2
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.0 backports-abc:0.5 backports.shutil-get-terminal-size:1.0.0 beautifulsoup4:4.4.1 bleach:2.1.2 certifi:2017.11.5 cffi:1.6.0 chardet:2.3.0 click:6.7 colorama:0.3.7 configparser:3.5.0 cryptography:1.3.2 decorator:4.1.2 distorm3:3.3.4 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 elasticsearch:2.2.0 entrypoints:0.2.3 enum34:1.0.4 et-xmlfile:1.0.1 flask:0.10.1 functools32:3.2.3.post2 html5lib:1.0b8 httpreplay:0.1.17 idna:2.0 ipaddress:1.0.14 ipykernel:4.7.0 ipython-genutils:0.2.0 ipython:5.5.0 ipywidgets:7.0.5 itsdangerous:0.24 jdcal:1.3 jinja2:2.8 jsbeautifier:1.5.10 jsonschema:2.6.0 jupyter-client:5.1.0 jupyter-console:5.2.0 jupyter-core:4.4.0 jupyter:1.0.0 lxml:3.6.0 mako:1.0.1 markupsafe:0.23 mistune:0.8.3 nbconvert:5.3.1 nbformat:4.4.0 ndg-httpsclient:0.4.0 notebook:5.2.2 oletools:0.42 openpyxl:2.4.9 pandocfilters:1.4.2 pathlib2:2.3.0 peepdf:0.3.2 pefile2:1.2.11 pexpect:4.3.0 pickleshare:0.7.4 pillow:3.2.0 pip:9.0.1 prompt-toolkit:1.0.15 ptyprocess:0.5.2 pyasn1:0.1.8 pycparser:2.14 pycrypto:2.6.1 pycurl:7.43.0 pygments:2.2.0 pyliblzma:0.5.3 pymisp:2.4.49 pymongo:3.0.3 pyopenssl:0.15.1 pysqlite:1.0.1 python-dateutil:2.4.2 python-editor:0.3 python-magic:0.4.6 pythonaes:1.0 pyzmq:16.0.3 qtconsole:4.3.1 requests:2.7.0 rpm-python:4.12.0.1 scandir:1.6 setuptools:38.2.4 simplegeneric:0.8.1 singledispatch:3.4.0.3 six:1.11.0 sqlalchemy:1.0.8 terminado:0.8.1 testpath:0.3.1 tlslite-ng:0.6.0a3 tornado:4.5.2 traitlets:4.3.2 ujson:1.35 unity-lens-photos:1.0 urlgrabber:3.9.1 urllib3:1.22 vboxapi:1.0 volatility:2.6 wakeonlan:0.2.2 wcwidth:0.1.7 webencodings:0.5.1 werkzeug:0.10.4 wheel:0.29.0 widgetsnbextension:3.0.8 yara-python:3.7.0 yum-metadata-parser:1.1.4

Traceback (most recent call last):
  File "./cuckoo.py", line 122, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "./cuckoo.py", line 93, in cuckoo_main
    sched.start()
  File "/home/codka/Downloads/cuckoo/lib/cuckoo/core/scheduler.py", line 670, in start
    self.initialize()
  File "/home/codka/Downloads/cuckoo/lib/cuckoo/core/scheduler.py", line 599, in initialize
    machinery = plugin()
  File "/home/codka/Downloads/cuckoo/lib/cuckoo/common/abstracts.py", line 76, in __init__
    self.db.clean_machines()
  File "/home/codka/Downloads/cuckoo/lib/cuckoo/common/utils.py", line 281, in inner
    return f(self, *args, **kwargs)
  File "/home/codka/Downloads/cuckoo/lib/cuckoo/core/database.py", line 486, in clean_machines
    self.engine.execute(machines_tags.delete())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'DELETE FROM machines_tags']

**Comment by doomedraven** [comment]
rc2 is dam old, upgrade to latest version `sudo pip install cuckoo`

**Comment by yahyeabukar** [comment]
Thanks doomedraven i upgraded using your command sudo pip install cuckoo , i run again ./cuckoo.py  i found these error 
codka@ubuntu:~/Downloads/cuckoo$ ./cuckoo.py
Traceback (most recent call last):
  File "./cuckoo.py", line 20, in <module>
    from lib.cuckoo.core.scheduler import Scheduler
  File "/home/codka/Downloads/cuckoo/lib/cuckoo/core/scheduler.py", line 21, in <module>
    from lib.cuckoo.core.guest import GuestManager
  File "/home/codka/Downloads/cuckoo/lib/cuckoo/core/guest.py", line 13, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by doomedraven** [comment]
if you used my command, you cann't anymore execute it as you do `codka@ubuntu:~/Downloads/cuckoo$ ./cuckoo.py`

follow the documentation, and use `cuckoo --help`
