### ISSUE TITLE
Cuckoo 2.0.5.2 & Elastic Search 5.4.0 Issue

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#2029]
Hi everything was working perfectly before installing elastic search. 
I have installed the elastic search by following this issue (https://github.com/cuckoosandbox/cuckoo/issues/1432) 

after configuring everything according to 1432 post, I have started facing the some issue while running cuckoo -d

=================================================================================

Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!

 Our latest blogposts:
 * Cuckoo Sandbox 2.0.5: Office DDE, December 03, 2017.
   Brand new release based on a DDE case study.
   More at https://cuckoosandbox.org/blog/205-office-dde

 * Cuckoo Sandbox 2.0.4, September 06, 2017.
   Introducing Malware Configuration Extraction.
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-204

 * Cuckoo Sandbox 2.0.0, March 30, 2017.
   First Cuckoo package release!
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-v2

2017-12-27 15:37:21,058 [cuckoo.core.startup] DEBUG: Imported modules...
2017-12-27 15:37:21,060 [elasticsearch] WARNING: HEAD http://127.0.0.1:9200/_template/cuckoo_template [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/sandbox/venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9d210>: Failed to establish a new connection: [Errno 111] Connection refused
2017-12-27 15:37:21,061 [elasticsearch] WARNING: HEAD http://127.0.0.1:9200/_template/cuckoo_template [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/sandbox/venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9d050>: Failed to establish a new connection: [Errno 111] Connection refused
2017-12-27 15:37:21,062 [elasticsearch] WARNING: HEAD http://127.0.0.1:9200/_template/cuckoo_template [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/sandbox/venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9d150>: Failed to establish a new connection: [Errno 111] Connection refused
2017-12-27 15:37:21,063 [elasticsearch] WARNING: HEAD http://127.0.0.1:9200/_template/cuckoo_template [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/sandbox/venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/sandbox/venv/lib/python2.7/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9d0d0>: Failed to establish a new connection: [Errno 111] Connection refused
2017-12-27 15:37:21,490 [pip.utils] DEBUG: lzma module is not available
2017-12-27 15:37:21,491 [pip.vcs] DEBUG: Registered VCS backend: git
2017-12-27 15:37:21,500 [pip.vcs] DEBUG: Registered VCS backend: hg
2017-12-27 15:37:21,534 [pip.vcs] DEBUG: Registered VCS backend: svn
2017-12-27 15:37:21,534 [pip.vcs] DEBUG: Registered VCS backend: bzr
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.5
OS version: posix
OS release: CentOS Linux 7.4.1708 Core
Python version: 2.7.5
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:0.8.8 androguard:3.0.1 asn1crypto:0.24.0 beautifulsoup4:4.5.3 capstone:3.0.5rc2 cffi:1.11.2 chardet:2.3.0 click:6.6 colorama:0.3.7 cryptography:2.1.4 cuckoo:2.0.5.2 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 egghatch:0.2.1 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 httpreplay:0.2.1 idna:2.6 ipaddress:1.0.19 itsdangerous:0.24 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 mako:1.0.7 markupsafe:1.0 olefile:0.43 oletools:0.51 peepdf:0.3.6 pefile2:1.2.11 pillow:3.2.0 pip:9.0.1 pycparser:2.18 pycrypto:2.6.1 pyelftools:0.24 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.5.0 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 requests:2.13.0 scapy:2.3.2 setuptools:38.2.4 sflock:0.2.17 six:1.11.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0 unicorn:1.0.1 urllib3:1.22 wakeonlan:0.2.2 werkzeug:0.13 yara-python:3.6.3

2017-12-27 15:37:21,546 [cuckoo] ERROR: ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9d0d0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9d0d0>: Failed to establish a new connection: [Errno 111] Connection refused)
Traceback (most recent call last):
  File "/home/sandbox/venv/lib/python2.7/site-packages/cuckoo/main.py", line 230, in main
    cuckoo_init(level, ctx)
  File "/home/sandbox/venv/lib/python2.7/site-packages/cuckoo/main.py", line 137, in cuckoo_init
    init_modules()
  File "/home/sandbox/venv/lib/python2.7/site-packages/cuckoo/core/startup.py", line 183, in init_modules
    module.init_once()
  File "/home/sandbox/venv/lib/python2.7/site-packages/cuckoo/reporting/elasticsearch.py", line 50, in init_once
    if not elastic.client.indices.exists_template(cls.template_name):
  File "/home/sandbox/venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/sandbox/venv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 475, in exists_template
    name), params=params)
  File "/home/sandbox/venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/sandbox/venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 123, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9d0d0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9d0d0>: Failed to establish a new connection: [Errno 111] Connection refused)
===============================================================================

Kindly  let me know if there is any solution for this

**Comment by SparkyNZL** [comment]
can you do a curl http://127.0.0.1:9200

and post the result please.

**Comment by jbremer** [comment]
Connection refused - sounds like ElasticSearch isn't running as @SparkyNZL suggested. Please provide additional feedback or this issue will be closed (as the issue seems somewhat obvious).

**Comment by jbremer** [comment]
Closing issue as resolved. Feel free to reopen if you have new information.
