### ISSUE TITLE
[cuckoo.processing.network] ERROR: Incomplete possible TLS Handshake record found and [cuckoo.processing.network] ERROR: Error running httpreplay-based PCAP analysis

### ISSUE THREAD

**Issue by hscu** [cuckoosandbox/cuckoo#2043]
Hello,

I'm running cuckoo 2.0.5 on Ubuntu 16.04.3 LTS. During the last couple of days the installation worked fine.
Today there was an error in the debug log regarding a possible incomplete TLS handshake and another one regarding a TLSBadRecordMAC.
The problem is that probly caused by those errors the HTTP(S) connections tab is empty in cuckoo in the network analysis section. 

Here is the complete error from the log:
2018-01-04 10:06:11,979 [cuckoo.processing.network] ERROR: Incomplete possible TLS Handshake record found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/network.py", line 528, in _https_identify
    record = dpkt.ssl.RECORD_TYPES[record.type](record.data)
  File "/usr/local/lib/python2.7/dist-packages/dpkt/dpkt.py", line 87, in __init__
    self.unpack(args[0])
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ssl.py", line 336, in unpack
    raise dpkt.NeedData
NeedData
2018-01-04 10:06:12,401 [cuckoo.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/network.py", line 891, in run
    results.update(p2.run())
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/network.py", line 768, in run
    l = sorted(r.process(), key=lambda x: x[1])
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/reader.py", line 126, in process
    self.tcp and self.tcp.finish()
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 91, in finish
    stream.finish()
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 367, in finish
    self.parent.handle(self.s, self.ts, "tcp", sent, recv)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 600, in handle
    while self.states[self.state](self, s, ts):
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 539, in state_stream
    sent.append(self.tls.decrypt_client(record.type, record.data))
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 431, in decrypt_client
    return self.decrypt(self.client_cipher, record_type, buf)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 420, in decrypt
    record_type, bytearray(buf)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 548, in _decryptThenMAC
    raise TLSBadRecordMAC()
TLSBadRecordMAC

Please find attached the dump.pcap. 
[dump.zip](https://github.com/cuckoosandbox/cuckoo/files/1602900/dump.zip)

The tlsmaster.txt is empty (0 bytes).

**Comment by jbremer** [comment]
Thanks. I can indeed reproduce the first `NeedData` exception, however, the `TLSBadRecordMAC` implies that you do in fact have a filled `tlsmaster.txt` file - otherwise there would be nothing to decrypt for the SSL/TLS streams (IIRC). Checking it out.
