### ISSUE TITLE
cuckoo Unable to stop auxiliary module: Sniffer

### ISSUE THREAD

**Issue by jmg49** [cuckoosandbox/cuckoo#2049]
hi, 

i have this error in a task summary report, 

i've tried what i have found here  👍 

sudo apt-get install apparmor-utils
sudo aa-disable /usr/sbin/tcpdump
sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
getcap /usr/sbin/tcpdump =  cap_net_admin,cap_net_raw+eip

reboot but always the same error , 

thanks in advance

**Comment by doomedraven** [comment]
try

```
groupadd pcap
usermod -a -G pcap cuckoo
chgrp pcap /usr/sbin/tcpdump
setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
```

**Comment by jmg49** [comment]
i change for a fedora 25 in root to not be in trouble with sudo 
same thing, even with your suggestion

**Comment by doomedraven** [comment]
ubuntu 16.04 is tested and suggested OS for cuckoo, about root *facepalm*, never do it

**Comment by jbremer** [comment]
Hehe, yeah, no Fedora expert here. Perhaps it requires a different workaround ;-)
Anyone else know what's up?

**Comment by mativl** [comment]
check the analysis.log and if something like this appears:

"Traceback (most recent call last):
   File "C: /tmpxavkbv/analyzer.py", line 624, in run
     aux.start ()
   File "C: \ tmpxavkbv \ modules \ auxiliary \ recentfiles.py", line 55, in start
     dirpath = self.get_path ()
   File "C: \ tmpxavkbv \ modules \ auxiliary \ recentfiles.py", line 43, in get_path
     r = SHELL32.SHGetKnownFolderPath (
   File "C: \ Python27 \ lib \ ctypes \ __ init__.py", line 379, in __getattr__
     func = self .__ getitem __ (name)
   File "C: \ Python27 \ lib \ ctypes \ __ init__.py", line 384, in __getitem__
     func = self._FuncPtr ((name_or_ordinal, self))
AttributeError: function 'SHGetKnownFolderPath' not found
"
It may be a problem similar to #1934 . It seems that it is from XP, I solved it by installing a Windows 7 as a virtual machine and I got it perfectly.
