### ISSUE TITLE
Problem with cyrillic (russian) symbols

### ISSUE THREAD

**Issue by MetallDoktor** [cuckoosandbox/cuckoo#2053]
Hello again!

There is actually one more problem I've faced: whenever a file with Cyrillic symbols in its name is submitted, analysis always catches following exception:

**UnicodeEncodeError: 'ascii' codec can't encode characters in position 123-129: ordinal not in range(128)**

There is no behavior analysis form such tasks. Of course, it can be solved with a simple renaming of the origin file, but it is rather annoying anyway.

Is there anything can be done with this?

Thank you!

**Comment by noideal** [comment]
Unicode file paths are not currently supported in Yara
https://github.com/VirusTotal/yara-python/issues/48

This is listed as a TODO item in 'startup.py' and 'objects.py'

**Comment by jbremer** [comment]
Could be an issue outside of the Yara integration though, do you have more complete logs for us @MetallDoktor ? Otherwise will be closing this issue.

**Comment by MetallDoktor** [comment]
Here is an example of logs below. Pretty the same for any file with cyrillic symbols in its name.

2018-01-30 17:21:06,849 [cuckoo.core.scheduler] INFO: Task #79: acquired machine cuckoo_gamma (label=cuckoo_gamma)
2018-01-30 17:21:06,882 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 31529 (interface=vboxnet0, host=192.168.56.8)
2018-01-30 17:21:06,883 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2018-01-30 17:21:06,944 [cuckoo.machinery.virtualbox] DEBUG: Starting vm cuckoo_gamma
2018-01-30 17:21:07,311 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine cuckoo_gamma to its current snapshot
2018-01-30 17:21:11,027 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo_gamma, ip=192.168.56.8)
2018-01-30 17:21:12,031 [cuckoo.core.guest] DEBUG: cuckoo_gamma: not ready yet
2018-01-30 17:21:13,036 [cuckoo.core.guest] DEBUG: cuckoo_gamma: not ready yet
2018-01-30 17:21:14,041 [cuckoo.core.guest] DEBUG: cuckoo_gamma: not ready yet
2018-01-30 17:21:14,085 [cuckoo.core.guest] DEBUG: cuckoo_gamma: not ready yet
2018-01-30 17:21:16,050 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo_gamma, ip=192.168.56.8)
2018-01-30 17:21:16,082 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo_gamma, ip=192.168.56.8, monitor=latest, size=6653925)
2018-01-30 17:21:16,558 [cuckoo.core.guest] DEBUG: cuckoo_gamma: analysis still processing
2018-01-30 17:21:16,897 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2018-01-30 17:21:17,567 [cuckoo.core.guest] DEBUG: cuckoo_gamma: analysis still processing
2018-01-30 17:21:18,577 [cuckoo.core.guest] DEBUG: cuckoo_gamma: analysis still processing
2018-01-30 17:21:19,586 [cuckoo.core.guest] DEBUG: cuckoo_gamma: analysis still processing
2018-01-30 17:21:20,595 [cuckoo.core.guest] DEBUG: cuckoo_gamma: analysis still processing
2018-01-30 17:21:21,601 [cuckoo.core.guest] WARNING: cuckoo_gamma: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpvt6hai/analyzer.py", line 794, in <module>
    success = analyzer.run()
  File "C:/tmpvt6hai/analyzer.py", line 649, in run
    pids = self.package.start(self.target)
  File "C:\tmpvt6hai\modules\packages\js.py", line 28, in start
    return self.execute(wscript, args=[path], trigger="file:%s" % path)
  File "C:\tmpvt6hai\lib\common\abstracts.py", line 163, in execute
    maximize=maximize, env=env, trigger=trigger):
  File "C:\tmpvt6hai\lib\api\process.py", line 288, in execute
    output = subprocess_checkoutput(argv, env)
  File "C:\tmpvt6hai\lib\api\process.py", line 32, in subprocess_checkoutput
    args, stdin=subprocess.PIPE, stderr=subprocess.PIPE, env=env,
  File "C:\Python27\lib\subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 114-119: ordinal not in range(128)

2018-01-30 17:21:21,785 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2018-01-30 17:21:21,786 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo_gamma
2018-01-30 17:21:22,093 [cuckoo.core.resultserver] DEBUG: File upload request for shots/0001.jpg
2018-01-30 17:21:25,099 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 13272
2018-01-30 17:21:25,214 [cuckoo.core.scheduler] DEBUG: Released database task #79
2018-01-30 17:21:25,228 [cuckoo.core.scheduler] INFO: Task #79: analysis procedure completed

**Comment by jbremer** [comment]
This is part of our `2.0.6` release, closing as resolved. Thanks!
