### ISSUE TITLE
Yara and ssdeep always none , none matched

### ISSUE THREAD

**Issue by jmg49** [cuckoosandbox/cuckoo#2055]
hello , 

i changed my cuckoo installation on a Fedora 25 ,  i never have yara sign or ssdeep , 

yara is installed with pip , i 've tried to clcone git and build / install too ....same thing with pydeep ssdeeep

here is my cuckoo log from an analysis , except the sniffer error i can't fix, all seems to be alright .

if you have an idea , thanks 

`
2018-01-11 15:55:47,676 [cuckoo.core.scheduler] INFO: Task #2: acquired machine cuckoo1 (label=seven1)
2018-01-11 15:55:47,787 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 1546 (interface=vboxnet0, host=10.48.54.113)
2018-01-11 15:55:47,787 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2018-01-11 15:55:47,861 [cuckoo.machinery.virtualbox] DEBUG: Starting vm seven1
2018-01-11 15:55:48,197 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine seven1 to sn2
2018-01-11 15:55:52,083 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=10.48.54.113)
2018-01-11 15:55:53,158 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:55:54,163 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:55:55,168 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:55:55,240 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:55:57,246 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:55:58,251 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:55:59,257 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:56:00,264 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:56:01,269 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:56:02,274 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:56:03,279 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:56:04,283 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-01-11 15:56:09,301 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=cuckoo1, ip=10.48.54.113)
2018-01-11 15:56:20,138 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo1, ip=10.48.54.113, monitor=latest, size=3840773)
2018-01-11 15:56:42,977 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2018-01-11 15:56:46,495 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:56:50,703 [cuckoo.core.resultserver] DEBUG: New process (pid=4028, ppid=4004, name=jvauyc32.exe)
2018-01-11 15:56:51,122 [cuckoo.core.resultserver] DEBUG: File upload request for shots/0001.jpg
2018-01-11 15:56:51,138 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 43823
2018-01-11 15:56:52,261 [cuckoo.core.resultserver] DEBUG: File upload request for shots/0002.jpg
2018-01-11 15:56:52,270 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 43396
2018-01-11 15:56:52,333 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:56:58,211 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:04,030 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:09,871 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:15,717 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:21,726 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:57:21,730 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:23,514 [cuckoo.core.resultserver] DEBUG: File upload request for memory/4028-1.dmp
2018-01-11 15:57:23,910 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 12365232
2018-01-11 15:57:27,739 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:57:27,742 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:33,750 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:57:33,753 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:39,760 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:57:39,763 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:45,770 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:57:45,773 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:51,778 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:57:51,781 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:57:57,787 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:57:57,790 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:03,799 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:03,803 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:09,811 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:09,815 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:15,825 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:15,828 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:21,836 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:21,840 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:27,846 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:27,850 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:33,858 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:33,861 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:39,870 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:39,873 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:45,878 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:45,881 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:51,890 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:51,893 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:58:57,900 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:58:57,903 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:59:03,908 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:59:03,912 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:59:09,918 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:59:09,921 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:59:15,930 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:59:15,934 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:59:21,942 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:59:21,945 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:59:27,951 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:59:27,955 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:59:33,963 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:59:33,966 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:59:39,974 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:59:39,978 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:59:45,986 [cuckoo.core.guest] INFO: Virtual Machine /status failed (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.48.54.113', port=8000): Read timed out. (read timeout=5)",),))
2018-01-11 15:59:45,989 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-01-11 15:59:46,991 [cuckoo.core.guest] INFO: cuckoo1: end of analysis reached!
2018-01-11 15:59:47,007 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 162, in stop
    module.stop()
  File "/usr/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 154, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: vboxnet0: That device is not up\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
2018-01-11 15:59:58,987 [cuckoo.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label seven1 to path /root/.cuckoo/storage/analyses/2/memory.dmp
2018-01-11 15:59:58,989 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm seven1
2018-01-11 16:00:21,484 [cuckoo.core.scheduler] DEBUG: Released database task #2
2018-01-11 16:00:21,596 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #2
2018-01-11 16:00:21,603 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #2
2018-01-11 16:00:21,604 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #2
2018-01-11 16:00:21,605 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #2
2018-01-11 16:00:31,973 [cuckoo.processing.memory] DEBUG: Executing volatility 'pslist' module.
2018-01-11 16:00:33,796 [cuckoo.processing.memory] DEBUG: Executing volatility 'psxview' module.
2018-01-11 16:00:58,502 [cuckoo.processing.memory] DEBUG: Executing volatility 'callbacks' module.
2018-01-11 16:01:14,081 [cuckoo.processing.memory] DEBUG: Executing volatility 'ssdt' module.
2018-01-11 16:01:20,686 [cuckoo.processing.memory] DEBUG: Executing volatility 'timers' module.
2018-01-11 16:01:24,218 [cuckoo.processing.memory] DEBUG: Skipping 'messagehooks' volatility module
2018-01-11 16:01:24,218 [cuckoo.processing.memory] DEBUG: Executing volatility 'getsids' module.
2018-01-11 16:01:26,797 [cuckoo.processing.memory] DEBUG: Executing volatility 'privs' module.
2018-01-11 16:01:29,807 [cuckoo.processing.memory] DEBUG: Executing volatility 'malfind' module.
2018-01-11 16:01:36,727 [cuckoo.processing.memory] DEBUG: Skipping 'apihooks' volatility module
2018-01-11 16:01:36,727 [cuckoo.processing.memory] DEBUG: Executing volatility 'dlllist' module.
2018-01-11 16:01:40,686 [cuckoo.processing.memory] DEBUG: Executing volatility 'handles' module.
2018-01-11 16:02:15,625 [cuckoo.processing.memory] DEBUG: Executing volatility 'ldrmodules' module.
2018-01-11 16:02:29,614 [cuckoo.processing.memory] DEBUG: Executing volatility 'mutantscan' module.
2018-01-11 16:02:32,792 [cuckoo.processing.memory] DEBUG: Executing volatility 'devicetree' module.
2018-01-11 16:02:36,258 [cuckoo.processing.memory] DEBUG: Executing volatility 'svcscan' module.
2018-01-11 16:02:39,471 [cuckoo.processing.memory] DEBUG: Executing volatility 'modscan' module.
2018-01-11 16:02:42,402 [cuckoo.processing.memory] DEBUG: Executing volatility 'yarascan' module.
2018-01-11 16:03:09,791 [cuckoo.processing.memory] DEBUG: Executing volatility 'netscan' module.
2018-01-11 16:03:13,904 [cuckoo.core.plugins] DEBUG: Executed processing module "Memory" for task #2
2018-01-11 16:03:14,084 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #2
2018-01-11 16:03:14,338 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #2
2018-01-11 16:03:14,339 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #2
2018-01-11 16:03:14,438 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #2
2018-01-11 16:03:14,734 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #2
2018-01-11 16:03:14,756 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #2
2018-01-11 16:03:14,762 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #2
2018-01-11 16:03:14,763 [cuckoo.processing.network] WARNING: The PCAP file does not exist at path "/root/.cuckoo/storage/analyses/2/dump.pcap".
2018-01-11 16:03:14,763 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #2
2018-01-11 16:03:15,197 [cuckoo.core.plugins] DEBUG: Executed processing module "VirusTotal" for task #2
2018-01-11 16:03:15,197 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #2
2018-01-11 16:03:15,198 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #2
2018-01-11 16:03:15,210 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #2
2018-01-11 16:03:15,214 [cuckoo.core.plugins] DEBUG: Running 473 signatures
2018-01-11 16:03:15,567 [cuckoo.core.plugins] DEBUG: Analysis matched signature: antivirus_virustotal
2018-01-11 16:03:15,568 [cuckoo.core.plugins] DEBUG: Analysis matched signature: packer_entropy
2018-01-11 16:03:15,568 [cuckoo.core.plugins] DEBUG: Analysis matched signature: peid_packer
2018-01-11 16:03:15,568 [cuckoo.core.plugins] DEBUG: Analysis matched signature: volatility_handles_1
2018-01-11 16:03:15,569 [cuckoo.core.plugins] DEBUG: Analysis matched signature: volatility_ldrmodules_1
2018-01-11 16:03:15,569 [cuckoo.core.plugins] DEBUG: Analysis matched signature: volatility_malfind_2
2018-01-11 16:03:15,569 [cuckoo.core.plugins] DEBUG: Analysis matched signature: volatility_svcscan_1
2018-01-11 16:03:15,570 [cuckoo.core.plugins] DEBUG: Analysis matched signature: volatility_svcscan_3
2018-01-11 16:03:16,333 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2018-01-11 16:03:16,756 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2018-01-11 16:03:16,756 [cuckoo.core.scheduler] INFO: Task #2: reports generation completed
2018-01-11 16:03:16,770 [cuckoo.core.scheduler] INFO: Task #2: analysis procedure completed

`

**Comment by doomedraven** [comment]
```
    groupadd pcap
    usermod -a -G pcap cuckoo
    chgrp pcap /usr/sbin/tcpdump
    setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
 ```


for yara, did yara match statically file?

**Comment by jbremer** [comment]
And do you have Yara rules installed?

**Comment by jbremer** [comment]
Closing due to lack of additional information, feel free to reopen if you have new information.
