### ISSUE TITLE
ERROR: Failed to start sniffer

### ISSUE THREAD

**Issue by faraanh** [cuckoosandbox/cuckoo#2064]
I'v installed cuckoo on my windows 10, cuckoo web run ok but some components have problems. This is the first problems when I start to analysis a file:
2018-01-17 15:06:59,727 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "spa.exe" (task #9, options "procmemdump=yes,route=none")
2018-01-17 15:06:59,897 [cuckoo.core.scheduler] INFO: Task #9: acquired machine cuckoo1 (label=win7)
2018-01-17 15:07:00,164 [cuckoo.auxiliary.sniffer] ERROR: Failed to start sniffer (interface=VirtualBox Host-Only Network, host=192.168.56.104, pcap=C:\Users\faraa\.cuckoo\storage\analyses\9\dump.pcap)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\cuckoo\auxiliary\sniffer.py", line 88, in start
    pargs, stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True
  File "c:\python27\lib\site-packages\cuckoo\misc.py", line 199, in Popen
    return subprocess.Popen(*args, **kwargs)
  File "c:\python27\lib\subprocess.py", line 672, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 740] The requested operation requires elevation

**Comment by noideal** [comment]
This appears to be a permissions issue. Make sure that the user running the cuckoo process has full permissions to use PCAP on that interface

**Comment by faraanh** [comment]
thank you for your idea, I've chang the permissions like this but the but the error is out
![image](https://user-images.githubusercontent.com/24148680/35178926-b0aa7562-fdc2-11e7-84fd-208ad8e284e0.png)

**Comment by jbremer** [comment]
Are you running as Administrator on the Windows host?

**Comment by RicoVZ** [comment]
@faraanh Are you still having this issue? If so, are you running tcpdump as Administrator?

**Comment by jbremer** [comment]
Closing issue for lack of additional information - feel free to reopen if you have an update for us.
