### ISSUE TITLE
TypeError: exception() got an unexpected keyword argument 'extra'

### ISSUE THREAD

**Issue by faraanh** [cuckoosandbox/cuckoo#2067]
hi everyone, I don't know why my cuckoo has a problem like this, can you help me please?

2018-01-18 21:44:33,690 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2018-01-18 21:44:37,140 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2018-01-18 21:44:37,187 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2018-01-18 21:45:23,624 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "spa.exe" (task #25, options "procmemdump=yes,route=none")
2018-01-18 21:45:23,836 [cuckoo.core.scheduler] INFO: Task #25: acquired machine cuckoo1 (label=win7)
2018-01-18 21:45:23,940 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 19260 (interface=\Device\NPF_{4FC2420D-015F-43AF-82FE-6C137AB12C2C}, host=192.168.56.104)
2018-01-18 21:45:38,092 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.104)
2018-01-18 21:45:42,322 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=cuckoo1, ip=192.168.56.104)
2018-01-18 21:45:44,098 [cuckoo.core.guest] WARNING: cuckoo1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmp1tbrcv/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmp1tbrcv/analyzer.py", line 580, in run
    "not exist.".format(package_name))
CuckooError: Unable to import package "modules.packages.None", does not exist.

Exception in thread Thread-12:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\site-packages\cuckoo\core\scheduler.py", line 745, in run
    "status": "error",
TypeError: exception() got an unexpected keyword argument 'extra'

**Comment by jbremer** [comment]
Are you running Python `2.7.3` or similar? If so, please upgrade it :-)

**Comment by RicoVZ** [comment]
@faraanh Are you still having this issue? If so, what is your Python version? :smile:
