### ISSUE TITLE
In DESPERATE need for help - Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by Omar-hr** [cuckoosandbox/cuckoo#2069]
Hello everyone,

I've been dealing with Cuckoodroid as part of a university project I am working on since Summer 2017, and I've been trying so many different setups and different versions of Cuckoo, but I couldn't successfully do a single full analysis so far. This project is the only thing that is holding my graduation so I am really desperate for help. 
My current setup is Cuckoo 2.0.5 running on Ubuntu 17.10 (required to have the latest version due to university policies), and using VirtualBox 5.2.6 running the same version of Ubuntu as well. I followed all the instructions and manuals very carefully. But the furthest I could get is this:

```
2018-01-18 14:36:19,675 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2018-01-18 14:36:20,971 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2018-01-18 14:36:20,986 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2018-01-18 14:36:41,646 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "DU.apk" (task #21, options "procmemdump=yes,route=none")
2018-01-18 14:36:41,864 [cuckoo.core.scheduler] INFO: Task #21: acquired machine new cuckoodroid (label=new cuckoodroid)
2018-01-18 14:36:41,872 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 6442 (interface=vboxnet0, host=192.168.56.102)
2018-01-18 14:37:09,585 [cuckoo.core.guest] INFO: Starting analysis on guest (id=new cuckoodroid, ip=192.168.56.102)
2018-01-18 14:37:09,753 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=new cuckoodroid, ip=192.168.56.102)
2018-01-18 14:37:14,997 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 698, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 499, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 483, in start_analysis
    self.upload_analyzer(monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 390, in upload_analyzer
    self.determine_analyzer_path()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 368, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 330, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.102:8000/mkdtemp


```

I tried searching this error but I couldn't find anything related other than the ConnectionError or HTTPError with /store which I don't believe are related.

My best results were with cuckoo version 1.2, which used to work fine (with the exception of a GooglePlay error that I couldn't figure out, but didn't affect my work much anyways). But recently it has been failing the network analysis for some reason, although I didn't change anything in that setup. I know it's a very old version, and I won't get any support for it, but just felt like sharing my problem in case anyone has the time.

I really appreciate if anyone can help me get a successful analysis on any version of Cuckoo.

Thanks a lot

**Comment by doomedraven** [comment]
2.0.5 won't work for android, as you told, 1.2

**Comment by Omar-hr** [comment]
Thanks for responding. Is 1.2 still supported if I want to post the issue?

**Comment by doomedraven** [comment]
itsn't, but maybe someone can help you, there was one nice issue describing how to set it, but go for https://github.com/idanr1986/cuckoo-droid

**Comment by Omar-hr** [comment]
Alright, thanks a lot
