### ISSUE TITLE
2.0.5 cuckoo web interface Expetion on Ubutu LTS

### ISSUE THREAD

**Issue by smalinskiy** [cuckoosandbox/cuckoo#2071]
Hello Team!

successfully installed cuckoo but unable to run web-django interface..

^Croot@probe2:~/.cuckoo/conf# /etc/init.d/mongodb status
● mongodb.service - An object/document-oriented database
   Loaded: loaded (/lib/systemd/system/mongodb.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-01-18 13:06:59 MSK; 20h ago
     Docs: man:mongod(1)
 Main PID: 10160 (mongod)
   CGroup: /system.slice/mongodb.service
           └─10160 /usr/bin/mongod --config /etc/mongodb.conf

Jan 18 13:06:59 probe2 systemd[1]: Started An object/document-oriented database.
root@probe2:~/.cuckoo/conf# 

----------------------------------------
Exception happened during processing of request from ('10.21.214.104', 8392)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 102, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 167, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer

**Comment by smalinskiy** [comment]
NGFW start to inspect HTTP1.2 on uncommont port, not cuckoo issue.
