### ISSUE TITLE
2.0.5 with esxi machinery on esxi 6.5

### ISSUE THREAD

**Issue by smalinskiy** [cuckoosandbox/cuckoo#2077]
hello team,

have problem with running esxi guest on esxi 6.5
cuckoo is able to stop VM, revert to clear snapshot but unlucky with running VM.
additionaly im able to run VM with virsh with same credential as cuckoo esxi.conf have.
esxi console constantly spam - Find By Uuid when cuckoo awaits VM.
if i run VM manually, cuckoo is see this.

# ?no_verify disables the SSL signature check. By default it is self signed
dsn = esx://10.36.79.226/?no_verify=1
username = sandbox
password = !rfrnec74

machines = Gamma 

# Specify the name of the default network interface that will be used
# when dumping network traffic with tcpdump.
# Example (eth0 is the interface name):
interface = ens192

[Gamma]
# Specify the label name of the current machine as specified in your
# libvirt configuration.
label = Rev-Gamma64

2018-01-23 18:06:38,304 [cuckoo.common.abstracts] DEBUG: Getting status for Rev-Gamma64
2018-01-23 18:06:38,314 [cuckoo.common.abstracts] DEBUG: Waiting 57 cuckooseconds for machine Rev-Gamma64 to switch to status ('running',)
2018-01-23 18:06:39,315 [cuckoo.common.abstracts] DEBUG: Getting status for Rev-Gamma64
2018-01-23 18:06:39,387 [cuckoo.common.abstracts] DEBUG: Waiting 58 cuckooseconds for machine Rev-Gamma64 to switch to status ('running',)
2018-01-23 18:06:40,388 [cuckoo.common.abstracts] DEBUG: Getting status for Rev-Gamma64
2018-01-23 18:06:40,398 [cuckoo.common.abstracts] DEBUG: Waiting 59 cuckooseconds for machine Rev-Gamma64 to switch to status ('running',)
2018-01-23 18:06:41,400 [cuckoo.common.abstracts] DEBUG: Getting status for Rev-Gamma64
2018-01-23 18:06:41,470 [cuckoo.common.abstracts] DEBUG: Waiting 60 cuckooseconds for machine Rev-Gamma64 to switch to status ('running',)
2018-01-23 18:06:42,471 [cuckoo.common.abstracts] DEBUG: Getting status for Rev-Gamma64
2018-01-23 18:06:42,482 [cuckoo.common.abstracts] DEBUG: Waiting 61 cuckooseconds for machine Rev-Gamma64 to switch to status ('running',)
2018-01-23 18:06:42,482 [cuckoo.core.scheduler] ERROR: Error starting Virtual Machine! VM: Gamma, error: Timeout hit while for machine Rev-Gamma64 to change status
2018-01-23 18:06:42,482 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 162, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 154, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: ens192: That device is not up\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
2018-01-23 18:06:42,487 [cuckoo.common.abstracts] DEBUG: Stopping machine Rev-Gamma64
2018-01-23 18:06:42,487 [cuckoo.common.abstracts] DEBUG: Getting status for Rev-Gamma64
2018-01-23 18:06:42,495 [cuckoo.core.scheduler] WARNING: Unable to stop machine Rev-Gamma64: Trying to stop an already stopped machine Rev-Gamma64
2018-01-23 18:06:42,499 [cuckoo.core.rooter] CRITICAL: Unable to passthrough root command (drop_disable) as the rooter unix socket doesn't exist.
2018-01-23 18:06:42,504 [cuckoo.core.scheduler] DEBUG: Released database task #1
2018-01-23 18:06:42,530 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #1
2018-01-23 18:06:42,530 [cuckoo.processing.behavior] WARNING: Analysis results folder does not exist at path '/home/cuckoo/.cuckoo/storage/analyses/1/logs'.
2018-01-23 18:06:42,531 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #1
2018-01-23 18:06:42,531 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #1
2018-01-23 18:06:42,531 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #1
2018-01-23 18:06:42,532 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #1
2018-01-23 18:06:42,532 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #1
2018-01-23 18:06:42,533 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #1
2018-01-23 18:06:42,533 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #1
2018-01-23 18:06:45,204 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #1
2018-01-23 18:06:45,332 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #1
2018-01-23 18:06:45,380 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #1
2018-01-23 18:06:45,380 [cuckoo.processing.network] WARNING: The PCAP file does not exist at path "/home/cuckoo/.cuckoo/storage/analyses/1/dump.pcap".
2018-01-23 18:06:45,380 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #1
2018-01-23 18:06:45,381 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #1
2018-01-23 18:06:45,381 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #1
2018-01-23 18:06:45,381 [cuckoo.processing.debug] ERROR: Error processing task #1: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2018-01-23 18:06:45,387 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #1
2018-01-23 18:06:45,387 [cuckoo.core.plugins] DEBUG: Running 0 signatures
2018-01-23 18:06:45,409 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2018-01-23 18:06:45,456 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2018-01-23 18:06:45,456 [cuckoo.core.scheduler] INFO: Task #1: reports generation completed
2018-01-23 18:06:45,467 [cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed

**Comment by jbremer** [comment]
I've updated your post to not include your own password. Well, seems like Cuckoo can't reach the VM. Did you properly install the Cuckoo Agent and configure all IP addresses etc? See also the docs URL that is linked at the end.

**Comment by marcelmalware** [comment]
@jbremer how can i modify the timeout setting for cuckoo, by default, cuckoo host waits about 30 minutes after lost connection before shutting down the analysis and the vm. It is not the cuckoo.conf timeouts.

**Comment by RicoVZ** [comment]
Hi @marcelmalware. For new questions, please create a new issue. If you post on issues that are older, not many people will see the question. :smile: 

And to answer your question:
You should not have to modify it.

The total maximum time an analysis should run is the analysis timeout (default 120 seconds ) + the critical timeout (default 60 seconds).
After this, Cuckoo should shut down the VM. 

In your `cuckoo.conf`. There is a `[timeouts]` section. It has a `default = ` and a `critical = `. These times are in seconds.

If the sum of these is not 30 minutes and you have not submitted a task with a custom timeout, you should not have to wait 30 minutes. This means something else is likely causing the problem.

Could you create a new issue describing this behavior if it persists? That way, other users can also read it and may be able to help you.

**Comment by marcelmalware** [comment]
Thanks @RicoVZ , i'll dig into it.
