### ISSUE TITLE
ElasticSearch throws an unhandled exception!

### ISSUE THREAD

**Issue by cmderpt** [cuckoosandbox/cuckoo#2085]
I am trying to install ElasticSearch. I don't configure anything. I use default setting elasticsearch.yml and reporting.conf (enabled elasticsearch). When I run cuckoo:
```python

                          .:
                          ::
    .-.     ,  :   .-.    ;;.-.  .-.   .-.
   ;       ;   ;  ;       ;; .' ;   ;';   ;'
   `;;;;'.'`..:;._`;;;;'_.'`  `.`;;'  `;;'

 Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

2018-01-29 11:56:28,737 [elasticsearch] WARNING: PUT http://127.0.0.1:9200/_template/cuckoo_template [status:400 request:0.127s]
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.5
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:0.8.8 androguard:3.0.1 asn1crypto:0.24.0 beautifulsoup4:4.5.3 capstone:3.0.5rc2 cffi:1.11.4 chardet:2.3.0 click:6.6 colorama:0.3.7 cryptography:2.1.4 cuckoo:2.0.5.2 distorm3:3.3.4 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 egghatch:0.2.1 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 httpreplay:0.2.1 idna:2.6 ipaddress:1.0.19 itsdangerous:0.24 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 m2crypto:0.24.0 mako:1.0.7 markupsafe:1.0 olefile:0.43 oletools:0.51 peepdf:0.3.6 pefile2:1.2.11 pillow:3.2.0 pip:9.0.1 pkg-resources:0.0.0 pycparser:2.18 pycrypto:2.6.1 pyelftools:0.24 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.5.0 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 requests:2.13.0 scapy:2.3.2 setuptools:38.4.0 sflock:0.2.17 six:1.11.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0 unicorn:1.0.1 urllib3:1.22 volatility:2.6 wakeonlan:0.2.2 werkzeug:0.14.1 wheel:0.30.0 yara-python:3.6.3

2018-01-29 11:56:29,010 [cuckoo] ERROR: RequestError: TransportError(400, u'mapper_parsing_exception', u'Failed to parse mapping [cuckoo]: Could not convert [procmemory.include_in_root] to boolean')
Traceback (most recent call last):
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/cuckoo/main.py", line 230, in main
    cuckoo_init(level, ctx)
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/cuckoo/main.py", line 137, in cuckoo_init
    init_modules()
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/cuckoo/core/startup.py", line 183, in init_modules
    module.init_once()
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/cuckoo/reporting/elasticsearch.py", line 51, in init_once
    if not cls.apply_template():
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/cuckoo/reporting/elasticsearch.py", line 76, in apply_template
    name=cls.template_name, body=json.dumps(template)
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 458, in put_template
    name), params=params, body=body)
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/cuckoo/stable/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 124, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'Failed to parse mapping [cuckoo]: Could not convert [procmemory.include_in_root] to boolean')
```
This is the first time I install ElasticSearch so please help me :(

**Comment by w0r1dhe110** [comment]
What is your ElasticSearch version?

**Comment by cmderpt** [comment]
My ElasticSearch's version is 6.1.2
```
{
  "name" : "ni_jaYb",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "eWvG_r-jSTaEw5wjnCvOMA",
  "version" : {
    "number" : "6.1.2",
    "build_hash" : "5b1fea5",
    "build_date" : "2018-01-10T02:35:59.208Z",
    "build_snapshot" : false,
    "lucene_version" : "7.1.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by SparkyNZL** [comment]
Doesn't work on ES 6, use ES 5.6.6 instead please













On Wed, Jan 31, 2018 at 7:33 PM +1300, "cmderpt" <notifications@github.com> wrote:












My ElasticSearch's version is 6.1.2
{
  "name" : "ni_jaYb",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "eWvG_r-jSTaEw5wjnCvOMA",
  "version" : {
    "number" : "6.1.2",
    "build_hash" : "5b1fea5",
    "build_date" : "2018-01-10T02:35:59.208Z",
    "build_snapshot" : false,
    "lucene_version" : "7.1.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
