### ISSUE TITLE
Error Running Cuckoo after Upgrade

### ISSUE THREAD

**Issue by jwilczek** [cuckoosandbox/cuckoo#2089]
Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 Error checking for the latest Cuckoo version: HTTPSConnectionPool(host='cuckoosandbox.org', port=443): Max retries exceeded with url: /updates.json?version=2.0.5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f26dfae91d0>, 'Connection to cuckoosandbox.org timed out. (connect timeout=6)'))!
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.5
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0.1 asn1crypto:0.24.0 beautifulsoup4:4.5.3 capstone:3.0.5rc2 cffi:1.11.4 chardet:2.3.0 click:6.6 colorama:0.3.7 cryptography:2.1.4 cuckoo:2.0.5.2 distorm3:3.3.0 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 egghatch:0.2.1 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 html5lib:0.999 httpreplay:0.2.1 idna:2.6 ipaddress:1.0.19 itsdangerous:0.24 jdcal:1.0 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 lxml:3.6.0 m2crypto:0.24.0 mako:1.0.7 markupsafe:1.0 ndg-httpsclient:0.4.0 olefile:0.43 oletools:0.51 openpyxl:2.3.0 peepdf:0.3.6 pefile2:1.2.11 pillow:3.2.0 pip:9.0.1 psycopg2:2.6.2 py:1.4.31 pyasn1:0.1.8 pycparser:2.18 pycrypto:2.6.1 pydeep:0.2 pyelftools:0.24 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.5.0 pytest:2.8.7 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 pytz:2014.10 requests:2.13.0 scapy:2.3.2 setuptools:38.4.0 sflock:0.2.17 six:1.11.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0 typing:3.6.1 unicorn:1.0.1 unity-lens-photos:1.0 urllib3:1.22 uwsgi:2.0.14 vboxapi:1.0 virtualenv:15.0.1 volatility:2.5 wakeonlan:0.2.2 werkzeug:0.14.1 wheel:0.29.0 yara-python:3.6.3 yara:1.7.7

2018-01-30 16:41:58,736 [cuckoo] ERROR: AttributeError: Rules instance has no attribute 'save'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 230, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 139, in cuckoo_init
    init_yara()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 266, in init_yara
    File.yara_rules["memory"].save(cwd("stuff", "dumpmem.yarac"))
AttributeError: Rules instance has no attribute 'save'

**Comment by jwilczek** [comment]
My mistake, i thought both yara and yara-python were required.
