### ISSUE TITLE
Failed to run the processing module "Memory"

### ISSUE THREAD

**Issue by najashark** [cuckoosandbox/cuckoo#2129]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
The problem is when my `memory.conf` is set to `delete memdump = yes` it will delete `memory.dmp` before volatility scan is finished so some plug-in cannot run because the file is not the anymore
when `delete memdump = no` is set, there is no problem arise

##### My Cuckoo version and operating system are:
cuckoo == 2.0.5
OS == ubuntu 16.04x64

##### This can be reproduced by:
memory.conf
```python
#Basic settings
[basic]
#Profile to avoid wasting time identifying it
guest_profile = Win7SP1x64
#Delete memory dump after volatility processing.
delete_memdump = yes
```
##### The log, error, files etc can be found at:
```
2018-02-19 12:46:59,036 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory" for task #9:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 240, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1118, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1039, in run
    results[plugin_name] = getattr(self.vol, plugin_name)()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 950, in netscan
    for net_obj, proto, laddr, lport, raddr, rport, state in commands:
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/volatility/plugins/netscan.py", line 207, in calculate
    addr_space = utils.load_as(self._config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 FileAddressSpace: Filename must be specified and exist
 ArmAddressSpace: No base Address Space
```

**Comment by RicoVZ** [comment]
Hi najashark,

Thanks for reporting this issue! 
We will take a look into it.

**Comment by RicoVZ** [comment]
I tried to reproduce it, but I did not get any errors. Could you post the file, or a hash of the file for which this analysis was?

**Comment by najashark** [comment]
Right now the `memory.dmp` is deleted after `yarascan` module is finished which is make the netscan module failed.
i just run the pafish.exe binary from https://github.com/a0rtega/pafish
```
2018-03-12 22:00:21,962 [cuckoo.processing.memory] DEBUG: Executing volatility 'yarascan' module.
2018-03-12 22:01:07,801 [cuckoo.processing.memory] DEBUG: Executing volatility 'netscan' module.
2018-03-12 22:01:11,198 [volatility.debug] WARNING: NoneObject as string: Pointer Owner invalid
2018-03-12 22:01:11,230 [cuckoo.core.plugins] DEBUG: Executed processing module "Memory" for task #4
2018-03-12 22:01:12,501 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory" for task #4:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 240, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1118, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1039, in run
    results[plugin_name] = getattr(self.vol, plugin_name)()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 950, in netscan
    for net_obj, proto, laddr, lport, raddr, rport, state in commands:
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/volatility/plugins/netscan.py", line 207, in calculate
    addr_space = utils.load_as(self._config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 FileAddressSpace: Filename must be specified and exist
 ArmAddressSpace: No base Address Space

```

**Comment by najashark** [comment]
Here i attach my configuration
[conf.zip](https://github.com/cuckoosandbox/cuckoo/files/1810013/conf.zip)

maybe it can reproduce the error

**Comment by ivocarv** [comment]
I'm having the same problem. Cuckoo 2.0.6 running on vSphere 6.7 (with vsphere machinery). I thought that it was related to the new profiles on volatility 2.6, but when i set delete_memdup = no, the error stops (but fills the disk because each memdump is 4gb).

**Comment by ivocarv** [comment]
Solved. I'm using supervisord.conf, and forgot to set process_results = off in cuckoo.conf as stated on the documentation: https://cuckoo.sh/docs/usage/start.html. 

PS: perhaps cuckoo process module should check for this setting and refuse to run.

**Comment by jbremer** [comment]
Yeah, checking that might be useful. But the user should still read the error somewhere then..
