### ISSUE TITLE
InvalidStringData: strings in documents must be valid UTF-8

### ISSUE THREAD

**Issue by Nwinternights** [cuckoosandbox/cuckoo#2134]
##### My issue is:
A sample makes cuckoo failing analysis (404 on web page)
##### My Cuckoo version and operating system are:
2.0.5
Ubuntu 16.04 x64

##### This can be reproduced by:
fd8e0c54aca0e38366cf27cd7266710 . With Inetsim enabled the anlisys went ok, but with VPN or Internet enabled the analysis goes ko  with EHLO commands using unicode strings
[sample.zip](https://github.com/cuckoosandbox/cuckoo/files/1741768/sample.zip)

##### The log, error, files etc can be found at:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 614, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 263, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
InvalidStringData: strings in documents must be valid UTF-8: 'EHLO 10.0.0.43\r\nSTARTTLS\r\n\x16\x03\x01\x00\xab\x01\x00\x00\xa7\x03\x03\xe4\xc2\x07\x1c\xb1v\t\x86\xfe\xa0\xf4F\xaeZ\x94\xbf\x00)\x8e\xd5\xaf\xfd\xaf\xd2lG\x8d4`\xe0b\x9b\x00\x008\xc0,\xc00\x00\x9f\xcc\xa9\xcc\xa8\xcc\xaa\xc0+\xc0/\x00\x9e\xc0$\xc0(\x00k\xc0#\xc0\'\x00g\xc0\n\xc0\x14\x009\xc0\t\xc0\x13\x003\x00\x9d\x00\x9c\x00=\x00<\x005\x00/\x00\xff\x01\x00\x00F\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\n\x00\x08\x00\x1d\x00\x17\x00\x19\x00\x18\x00#\x00\x00\x00\r\x00 \x00\x1e\x06\x01\x06\x02\x06\x03\x05\x01\x05\x02\x05\x03\x04\x01\x04\x02\x04\x03\x03\x01\x03\x02\x03\x03\x02\x01\x02\x02\x02\x03\x00\x16\x00\x00\x00\x17\x00\x00\x16\x03\x01\x01\x06\x10\x00\x01\x02\x01\x00\x8c\xfd\xa6\xc3\xca\xcb\xdb\x19\xd3~B\xda\xb1\x1b\xbd\xe7Mr\xdc*\xbePlx\xafX\x19\x1d\xf41\x82\x82\xf2\xe7\xf7\xd9{Y\x0b;u{\xf8\xb9\xe8\xb1\xcfA\x9d~L\x9f\x0f\x7f+\xfc\x90\x9a+\rq[3\xf1N\x83\x08[\x9b\x04\x82\xd1\x10\xc2\xea\x98%\x18\x00\xaf\xa62\xeb\xdd$\xe3\xf0\x19\xf0\x8d\xd3\xf3\x03\xbb\xaf\xfc_\xf1/D\x93\x83T\xe1\x01\x97\xdb\xc5\x12\xd6\xc1\x1e\xa9:`/\x1en\xbd\x03\x9d\xfd\x07\x8c\\\'\x05h\xcdQ`\x17\x93\xe6=\xae\xc8\x9a\xdbG\xac\xa3\x99EE\x97I\x0f\xbaQ\x8d\'\xcd\xb2[\x08\x16\xc4\x90\xa7M\xdf\x95\xfcea\xd2S\x12\x10e\xe7\xb5>\xf3C\x87\xfa\x16\xc5\xa3 \xf1%\xc0[\x16q\xec\xa2c[\x05\no\xed\xce\x9e7\xbaX9\x82\x11T\x99g#8\n\x8a\n\xa1\t\x08\x99Ph%\xac$\x0f\x87\xf7C\xccc\x96\xd2A\xf8y\x10\xdcu`\xf9\x91\xcd\xbbx\x0b\xce\xf7yo\x9f\xbf\x8a\xf64\x04\x9e\xc2>\x07\x14\x03\x01\x00\x01\x01\x16\x03\x01\x000U\x8b\x1b\xe9\x9d\xc6\x84\xd5\xd0M*\xa8\xec\x1c\xdd\xe2\x82\xf3r\x13\xab|\xd7\x9d\r\x01o<\xd2\x00\xc8\x94`\xbe\xfb\x04\xb1\xdc!\xb8\t\x04\x04\xf0b\xe2\xba=\x17\x03\x01\x00 Y]\xcb\t\xd6S\x16\xdc\x9e\x83\x8a\x92\xbe\x92L\x87y~\xeb)\xf8ac\x84\x84\xf9\x83\xa9b\xf6\x1a\xee\x17\x03\x01\x000\xd6H\xc5\xb9/\x99\x9c\xaa\xed=\xe8I\xdch\xa7wv5\xb3(\t\xd1\xe4\x81=\xa1\xd5\xb1\x80\xc2\xd4^\xf36Q\xf2\x9bb\xd7\x91\x9d\xef\xe7\xcf&\\\xad\x82\x17\x03\x01\x00 \x17r\xe6\xe94"\x91Y\x82\xd6p\xbe\xc4KA\x17\x87\xd2\xce\xf0j\xbb\x01\x972\xcc\x1b-x\x10$\xd3\x17\x03\x01\x00 \xdf\x94=\x1f\xd7\x1d\xd3 Bsk\xfa\xa0\xfe\x8a2\xc1\xce\xdc\xfd5HD\xff\x1d+:\x0ci\xc7#\xb6\x15\x03\x01\x00 \x83K6d$\xe4\xc9)\xfd\xa9\x8c-W&y}{\x0f\x16\x14hw\x8dk\xa97FX\x83\xaf\x7f4'

**Comment by jbremer** [comment]
Thanks, could you also share `dump.pcap` with us?

**Comment by Nwinternights** [comment]
[pcap.zip](https://github.com/cuckoosandbox/cuckoo/files/1741849/pcap.zip)
Indeed it's very interesting pcap :-)

**Comment by Nwinternights** [comment]
https://github.com/cuckoosandbox/cuckoo/issues/2134

**Comment by Nwinternights** [comment]
@jbremer Do u have any news about this clue?
regards

**Comment by RicoVZ** [comment]
Not yet, I think @Nwinternights  This should happen less often with PDFs now. But can still happen.
I will add this to our todo, and look into the pcap when I find some time to do so.

Thanks :smile:
