### ISSUE TITLE
Cuckoo Custom Processing Module how can I get calls object from results dict?

### ISSUE THREAD

**Issue by alperkarakus** [cuckoosandbox/cuckoo#2139]
##### This can be reproduced by: 
class MyModule(Processing):
     def run(self):
          self.key="mymodule"
          for process in results.get("behavior", {}).get("processes", []):
               log.info(process["calls"])
          return None

**Comment by doomedraven** [comment]
`self._caller.results.get("behavior", {}).get("processes", []):`

**Comment by alperkarakus** [comment]
Hi @doomedraven  when I tried your solution I got an AttributeError: 'MyModule' object has no attribute '_caller' bellow is my code and output. Am I missing something in configuration?

import logging

from cuckoo.common.abstracts import Processing

log = logging.getLogger(__name__)

class MyModule(Processing):
    """Dropped buffer analysis."""

    def run(self):
        self.key = "mymodule"

        for process in self._caller.results.get("behavior", {}).get("processes", []):
            log.info(process["calls"])

        return None

2018-02-23 09:25:18,917 [cuckoo.core.plugins] ERROR: Failed to run the processing module "MyModule" for task #36:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 240, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/mymodule.py", line 13, in run
    for process in self._caller.results.get("behavior", {}).get("processes", []):
AttributeError: 'MyModule' object has no attribute '_caller'

Hello @jbremer  when I set the order to 2 or 998 it dose not differ and again the calls object is empty below is my code and output. Is there a way to get calls object in processing modules?

import logging

from cuckoo.common.abstracts import Processing

log = logging.getLogger(__name__)

class MyModule(Processing):
    order = 2

    def run(self):
        self.key = "mymodule"

        for process in self.results.get("behavior", {}).get("processes", []):
            log.info(process["calls"])

        return None


2018-02-23 09:54:04,262 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #37
2018-02-23 09:54:05,324 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #37
2018-02-23 09:54:05,332 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #37
2018-02-23 09:54:05,332 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #37
2018-02-23 09:54:06,651 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #37
2018-02-23 09:54:07,548 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #37
2018-02-23 09:54:07,549 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #37
2018-02-23 09:54:07,651 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #37
2018-02-23 09:54:09,507 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #37
2018-02-23 09:54:09,733 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #37
2018-02-23 09:54:09,827 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #37
2018-02-23 09:54:10,294 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #37
2018-02-23 09:54:10,295 [cuckoo.processing.mymodule] INFO: []
2018-02-23 09:54:10,295 [cuckoo.core.plugins] DEBUG: Executed processing module "MyModule" for task #37
2018-02-23 09:54:10,296 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #37
2018-02-23 09:54:10,297 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #37

Thanks for your comments.

**Comment by doomedraven** [comment]
add after `self.key = "mymodule"` logging.info(dir(self)) to see all the posibility ;)

**Comment by alperkarakus** [comment]
@doomedraven  I got 2018-02-23 13:56:28,447 [cuckoo.processing.mymodule] INFO: ['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'analysis_path', 'baseline_path', 'buffer_path', 'cuckoolog_path', 'dropped_meta_path', 'dropped_path', 'enabled', 'extracted_path', 'file_path', 'init_once', 'key', 'log_path', 'logs_path', 'machine', 'memory_path', 'mitmerr_path', 'mitmout_path', 'network_path', 'options', 'order', 'package_files', 'pcap_path', 'pmemory_path', 'results', 'run', 'set_baseline', 'set_machine', 'set_options', 'set_path', 'set_results', 'set_task', 'shots_path', 'suricata_path', 'task', 'taskinfo_path', 'tlsmaster_path']
options inorder to get call not empty which one'(s) should be setted or used?

**Comment by doomedraven** [comment]
you have `results`, you can start digging on `self.results` ;)

**Comment by alperkarakus** [comment]
In the results dict there is behaviour object which contains procesess and processes object contains the calls object. I need the api calls for processing. In cuckoo/processing/platforms/windows.py in class MonitorProcessLog there is a function __nonzero__ which should be set true inorder to get process["calls"] from results["behavior"] however I couln't managet to get calls object it is always empty. But thanks a lot @doomedraven

**Comment by alperkarakus** [comment]
I slove the problem and got the calls in a processing module

class MyModule(Processing):

	def run(self):
		self.key = "mymodule"
		data = dict(self.results)

		if "behavior" in data and "processes" in data["behavior"]:
			new_processes = []
			for process in data["behavior"]["processes"]:
				new_process = dict(process)

				# Loop on each process call.
				for call in process["calls"]:
					# Print call
					log.info(call)

		return None
