### ISSUE TITLE
Cuckoo Error While running it

### ISSUE THREAD

**Issue by mpravinkumar** [cuckoosandbox/cuckoo#2160]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

My issue is:
root@root:~# cuckoo
Traceback (most recent call last):
  File "/usr/bin/cuckoo", line 6, in <module>
    from cuckoo.main import main
  File "/usr/lib/python2.7/dist-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/lib/python2.7/dist-packages/cuckoo/auxiliary/__init__.py", line 6, in <module>
    from cuckoo.core.plugins import enumerate_plugins
  File "/usr/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 13, in <module>
    from cuckoo.common.config import config2
  File "/usr/lib/python2.7/dist-packages/cuckoo/common/config.py", line 13, in <module>
    from cuckoo.common.objects import Dictionary
  File "/usr/lib/python2.7/dist-packages/cuckoo/common/objects.py", line 6, in <module>
    import androguard
ImportError: No module named androguard

**Comment by RicoVZ** [comment]
Hi mpravinkumar,

The import error on start is a bit odd, as the Cuckoo package should install androguard.

As the issue template asked:
- What Cuckoo version are you using, and what is your os?
- How did you install the package?

You could try manually installing androguard, but I fear that it might not be the only missing package.
For now, I would recommend to reinstall Cuckoo using the Cuckoo package. We recommend that Cuckoo is installed in a virtualenv. This is to prevent other versions of dependencies from interfering with Cuckoo dependencies.

For more info on installing, see https://cuckoo.sh/docs/installation/host/installation.html

**Comment by jbremer** [comment]
It appears that you partially installed Cuckoo somehow. Please install it correctly (and perhaps upgrade to the latest version). Closing issue as resolved.
