### ISSUE TITLE
volatility is not working

### ISSUE THREAD

**Issue by k142094** [cuckoosandbox/cuckoo#2181]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
volatility doesn't work with cuckoo
##### My Cuckoo version and operating system are:
OS: Ubuntu 16.04.1
Cuckoo Version: 2.0.5
VirtualBox: 5.1.34
VM: Windows7x86Sp1
##### This can be reproduced by:
installing the latest version of cuckoo and voltality
##### The log, error, files etc can be found at:
2018-03-20 11:28:45,717 [cuckoo.processing.memory] ERROR: Cannot run volatility module: the volatility library is not available. Please install it according to their documentation.

**Comment by doomedraven** [comment]
`Cannot run volatility module: the volatility library is not available. Please install it according to their documentation.`

as error says, you just installed in incorrectly, does `vol.py -h` works?

**Comment by k142094** [comment]
i followed everything up to their guide. i even raised an issue at volatility
but those guys aren't responding at the moment
sorry for the late response
Traceback (most recent call last):
  File "/usr/local/bin/vol.py", line 57, in <module>
    import volatility.commands as commands
  File "/usr/local/lib/python2.7/site-packages/volatility/commands.py", line 33, in <module>
    from volatility.renderers.sqlite import SqliteRenderer
  File "/usr/local/lib/python2.7/site-packages/volatility/renderers/sqlite.py", line 22, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

**Comment by av-gantimurov** [comment]
@k142094 
`sudo apt install libsqlite3-dev`
