### ISSUE TITLE
Mitmproxy causes error

### ISSUE THREAD

**Issue by Mokatsu** [cuckoosandbox/cuckoo#2184]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I installed mitmdump, followed the instruction( placed the cert in CWD/.cuckoo/analyzer/windows/bin/[cername], turned it on in auxilary.conf, then rebooted cuckoo and it gave me the error below. I tried turning it off since then I keep getting the same error.
##### My Cuckoo version and operating system are:
2.0.5
Host: ubuntu 16.04
guest: windows 7
##### The log, error, files etc can be found at:
<pre><code>Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 230, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 121, in cuckoo_init
    check_version()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 105, in check_version
    params={"version": version}, timeout=6
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 411, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 775, in load_verify_locations
    _raise_current_error()
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]<pre/><code/>

**Comment by doomedraven** [comment]
that is pyopenssl error, not cuckoo's

**Comment by Mokatsu** [comment]
I looked through the documentation and there is no guide on how to set up the cert fro mitmdump other than what is stated within a configuration file. Is there an actual guide

**Comment by doomedraven** [comment]
yup, in mitmdump page
