### ISSUE TITLE
TypeErros on processing module / analyser.py

### ISSUE THREAD

**Issue by QLRxFrozen** [cuckoosandbox/cuckoo#2197]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
The analysis of Windows PE files is failing with the Error 'Failed to run the processing module "Static" for task#6:
[...] raise TypeError No string argument provided'. 
When I try to analyze files that are not Windows PE files, I get the TypeErros in the analyzer.py. I made only one Issue for both cases, because I think they are linked, but if you wish I can split this into two issues.

##### My Cuckoo version and operating system are:
Cuckoo Sandbox 2.0.5
Debian 9.3 (Stretch)
M2Crypto 0.29.0 (every lower version fails at build)

##### This can be reproduced by:
I'm not quite sure if this can be reproduced. But you could try installing M2Crypto 0.29.0 and submitting a Windows PE file.

#############################################
#############################################
 2018-03-27 09:53:10,880 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2018-03-27 09:53:11,989 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2018-03-27 09:53:12,015 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2018-03-27 09:53:54,423 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "PsExec" (task #6, options "")
2018-03-27 09:53:54,550 [cuckoo.core.scheduler] INFO: Task #6: acquired machine sb002-wskome (label=sb002-wskome)
2018-03-27 09:53:54,565 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 30893 (interface=vboxnet0, host=192.168.2.10)
2018-03-27 09:53:58,460 [cuckoo.core.guest] INFO: Starting analysis on guest (id=sb002-wskome, ip=192.168.2.10)
2018-03-27 09:54:01,491 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=sb002-wskome, ip=192.168.2.10)
2018-03-27 09:56:12,588 [cuckoo.core.guest] INFO: sb002-wskome: analysis completed successfully
2018-03-27 09:56:15,172 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Static" for task #6:
Traceback (most recent call last):
  File "/home/sandy/c_venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 240, in process
    data = current.run()
  File "/home/sandy/c_venv/local/lib/python2.7/site-packages/cuckoo/processing/static.py", line 1067, in run
    static.update(PortableExecutable(f.file_path).run())
  File "/home/sandy/c_venv/local/lib/python2.7/site-packages/cuckoo/processing/static.py", line 326, in run
    results["signature"] = self._get_signature()
  File "/home/sandy/c_venv/local/lib/python2.7/site-packages/cuckoo/processing/static.py", line 290, in _get_signature
    "email": subject.Email,
  File "/home/sandy/c_venv/local/lib/python2.7/site-packages/M2Crypto/X509.py", line 321, in __getattr__
    return util.py3str(m2.x509_name_by_nid(self.x509_name, self.nid[attr]))
  File "/home/sandy/c_venv/local/lib/python2.7/site-packages/M2Crypto/util.py", line 66, in py3str
    raise TypeError('No string argument provided')
TypeError: No string argument provided
2018-03-27 09:56:16,673 [cuckoo.core.scheduler] INFO: Task #6: reports generation completed
2018-03-27 09:56:16,684 [cuckoo.core.scheduler] INFO: Task #6: analysis procedure completed

##########################################
##########################################
2018-03-27 10:07:37,124 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "Team_Banner.pdf" (task #7, options "procmemdump=yes,route=none")
2018-03-27 10:07:37,301 [cuckoo.core.scheduler] INFO: Task #7: acquired machine sb002-wskome (label=sb002-wskome)
2018-03-27 10:07:37,322 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 31934 (interface=vboxnet0, host=192.168.2.10)
2018-03-27 10:07:41,286 [cuckoo.core.guest] INFO: Starting analysis on guest (id=sb002-wskome, ip=192.168.2.10)
2018-03-27 10:07:44,347 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=sb002-wskome, ip=192.168.2.10)
2018-03-27 10:07:54,012 [cuckoo.core.guest] WARNING: sb002-wskome: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpqvujio/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmpqvujio/analyzer.py", line 650, in run
    pids = self.package.start(self.target)
  File "C:\tmpqvujio\modules\packages\pdf.py", line 59, in start
    reader = self.get_path("Adobe Reader")
  File "C:\tmpqvujio\lib\common\abstracts.py", line 79, in get_path
    for path in self.enum_paths():
  File "C:\tmpqvujio\lib\common\abstracts.py", line 62, in enum_paths
    os.getenv("HomeDrive") + "\\",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

2018-03-27 10:07:58,867 [cuckoo.core.scheduler] INFO: Task #7: reports generation completed
2018-03-27 10:07:58,882 [cuckoo.core.scheduler] INFO: Task #7: analysis procedure completed

**Comment by jbremer** [comment]
First issue needs a signed PE, such that `M2Crypto` is invoked. There's a PR on supporting `M2Crypto` versions more recent than `0.24.0`.
Second issue seems to be missing environment variable(s). How did you setup the VM?

**Comment by RicoVZ** [comment]
@QLRxFrozen Poke. Some information on how you setup your VM could help us determine the issue.

**Comment by RicoVZ** [comment]
No problem :smile: 

Thanks for providing the information that you did have. As far as I can judge, this is caused by the environment variable `HomeDrive` being empty/None. We will investigate what can cause this on Windows 7 and try to mitigate it.

Thanks!
