### ISSUE TITLE
Cuckoo Update Required: OSX sandbox MAC-A-Malware Documentation Needed & Cuckoo Update is required

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#2201]
Hello Guys,

Recently few days ago in blackhat asia 2018 someone created the macosx sandbox and he also submitted his work to github. @jbremer kindly update the cuckoo with that and kindly update the documentation part. So that we can setup the machines.

Thanks & Regards
Seantree

**Comment by Ryuchen** [comment]
Could you past the github address please

**Comment by doomedraven** [comment]
https://github.com/phdphuc/mac-a-mal-cuckoo

**Comment by doomedraven** [comment]
feel free to prepare the PR to help to devs :P

**Comment by Ryuchen** [comment]
Anyone can help build the vm？Any document？

**Comment by Ryuchen** [comment]
http://www.contrib.andrew.cmu.edu/~somlo/OSXKVM/
this is blog can't see~

**Comment by doomedraven** [comment]
you can download it from there https://github.com/rodionovd/cuckoo-osx-analyzer/wiki/Setting-up-the-environment

**Comment by seantree** [comment]
lets see if anyone complete with the document with the MAC-A-Malware it would be great for the researchers.

**Comment by jbremer** [comment]
We'll look at it *eventually*, but are also busy with other things @seantree ;-)

**Comment by seantree** [comment]
ok @jbremer I will try to do something with this, let see where the path will goes )

**Comment by seantree** [comment]
just want to know few thing getting one error in guest macos while uploading the sample to guest machine of macosx 10.8 agent.py throw 1 error:


Import named error: no module named lib.common.config 

I am using the agent (cuckoo v2.0RC2) with cuckoo legacy and I have also cross checked with the file in cuckoo folder config file was present.
.
Waiting for solution.
.
Thanks & Regards
Seantree

**Comment by seantree** [comment]
Hi Any Updates??

**Comment by doomedraven** [comment]
no time :(

**Comment by seantree** [comment]
I have tried but facing few problems :( no that's why waiting for someone also to contribute their time in this, I thought that you were also working on this :(

**Comment by doomedraven** [comment]
that is in my ToDo, but idk when i will be able to do that, that isn't a high prior right now

**Comment by seantree** [comment]
Can you refer some person who is also working on this, I am ready to do work with him, I already spent so much time on this but faces few problems if someone else work on this I can share and exchange my knowledge and experiences on this.

**Comment by doomedraven** [comment]
no idea who works on this, and why not share here so you maybe can save time to someone who starts?

**Comment by seantree** [comment]
Definitely I will share it, I need a time to write everything, In my free time I will write it don't worry. Sharing is caring :)

**Comment by phdphuc** [comment]
> Import named error: no module named lib.common.config

@seantree It was fixed in this [commit](https://github.com/phdphuc/mac-a-mal-cuckoo/commit/d7e413160fe0c3948a0010643e239994207fcd08)

**Comment by zentavr** [comment]
@phdphuc - I wonder why you created your code on legacy branch of cuckoo? Can I use that with cuckoo 2.0.6?

**Comment by zentavr** [comment]
@Ryuchen - I was able to build and run MacOS 10.6 and 10.3 as the guests in Virtualbox.

**Comment by seantree** [comment]
@zentavr Hi Can you please tell me how did you configure? Can you please share your steps with us? Is your cuckoo is able to analyze MAC OSX samples properly?

**Comment by seantree** [comment]
Thank you for this but it would be great if you post a video, if it's possible for you

**Comment by seantree** [comment]
I am using MAC Machine so can you tell me what to do because the steps you given I think it's for fresh CPU machine, it's little bit confusing for me.

**Comment by zentavr** [comment]
@seantree - unfortunately I cannot do the video.
Re: "mac machine" - are you mean MacOS as a host?

**Comment by seantree** [comment]
Yes @zentavr

**Comment by zentavr** [comment]
I did on Linux Ubuntu :)

**Comment by seantree** [comment]
Ok No Problem, I have one CENTOS 7 Machine is setup as host & I am using MACOS 10.8 as a guest with cuckoo legacy

**Comment by zentavr** [comment]
The next step is to install the OS. The steps are different for Sierra and High Sierra (HS is more complicated :) )

In order to make your life much easier I created 2 helpers which are [here](https://gist.github.com/zentavr/a74827cad4987c6637d5d8382a0e56c7). There are 2 scripts inside:
* **create-osx.sh** - the helper which builds the VM
* **clone_medium.sh** - the helper which creates the disk clone.

Both guys are the BASH scripts, so you can pass `--help` to them and see the rest of the parameters.

## MacOS X 10.12.6 Sierra installation
I need to mention, that the OSes are not Hackintosh or things like that - they are unmodified and run on VirtualBox as is. A couple of Important settings could nit be done using VirtualBox GUI, so many nights were spent to study the forums and the manual of Virtualbox.

I create the VM in this way:
```
# su - cuckoo
$ ./create-osx.sh --name "Mac OS X Sierra 10.12" \
    --type "MacOS1012_64" --identifier "iMac11,3" \
    --bios efi --cpus 4 --cpuid "IvyBridge i7-3770" \
    --memory 4096 --videoram 64 \
    --drive 20480 \
    --rdp --rdpuser osx --rdppassword zxcvbn \
    --usb 3 \
    --cd "/VMs/iso/SierraCDR.iso"
```

After that I start the VM in Virtualbox GUI (Ok, I start it in headless mode and use RDP) and have fun.

## MacOS X 10.13.5 High Sierra installation
The process is described in [this guide][https://www.insanelymac.com/forum/topic/309654-run-vanilla-os-x-el-capitan-sierra-or-high-sierra-in-virtualbox-5034-on-a-windows-host/?page=3&tab=comments#comment-2517889] and is a little bit complicated.

### Creating the machine:

```
# su - cuckoo
$ ./create-osx.sh --name "Mac OS X Sierra 10.13" \
    --type "MacOS1013_64" --identifier "iMac11,3" \
    --bios efi --cpus 4 --cpuid "IvyBridge i7-3770" \
    --memory 4096 --videoram 64 \
    --drive 20480 \
    --rdp --rdpuser osx --rdppassword zxcvbn \
    --usb 3 \
    --cd "/VMs/iso/HSierraCDR.iso"
```

### Stage 1: Deploying the installer

1. Boot from High Sierra ISO
2. Choose **Disk Utillity** from the installer and format Virtual HDD using HFS+J filesystem
3. Back at the main screen, select **Reinstall macOS**. It will create first phase "/macOS Install Data" on target volume
   eg "HiSierra".

### Stage 2: Install the system

In the second phase, "/macOS Install Data" packages are extracted and installed on the disk. 
On restarting the system, you will need to jump into UEFI shell (F12 when in VirtualBox GUI/RDP). 
Type the 2 lines below, followed by <Enter> after each line...
```
FS1:
"\macOS Install Data\Locked Files\Boot Files\boot.efi"
```
will restart the installation process...

### Stage 3: Finishing the installation

Final third installation phase is rebuilding kextcaches, booting to the completed installation to select language and 
setup new user etc.

**Comment by zentavr** [comment]
I use [Objective See](https://objective-see.com/malware.html) as a source of poisoned software.
When I tried to upload the zip package (via Cuckoo's web interface) - I had an error.
```
2018-07-06 18:14:34,645 [cuckoo.core.scheduler] DEBUG: Processing task #3
2018-07-06 18:14:34,650 [cuckoo.core.scheduler] INFO: Starting analysis of ARCHIVE "AbkPro.app.zip" (task #3, options "filename=Contents/MacOS/AbkPro,procmemdump=yes,route=none")
2018-07-06 18:14:34,795 [cuckoo.core.scheduler] INFO: Task #3: acquired machine cuckoo-2.0-sierra-bs (label=cuckoo-2.0-sierra-bs)
2018-07-06 18:14:35,058 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7728 (interface=vboxnet0, host=192.168.56.105)
2018-07-06 18:14:35,058 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2018-07-06 18:14:35,066 [cuckoo.machinery.virtualbox] DEBUG: Starting vm cuckoo-2.0-sierra-bs
2018-07-06 18:14:35,399 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine cuckoo-2.0-sierra-bs to vminit
2018-07-06 18:14:44,310 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo-2.0-sierra-bs, ip=192.168.56.105)
2018-07-06 18:14:45,313 [cuckoo.core.guest] DEBUG: cuckoo-2.0-sierra-bs: not ready yet
2018-07-06 18:14:46,318 [cuckoo.core.guest] DEBUG: cuckoo-2.0-sierra-bs: not ready yet
2018-07-06 18:14:47,322 [cuckoo.core.guest] DEBUG: cuckoo-2.0-sierra-bs: not ready yet
2018-07-06 18:14:48,326 [cuckoo.core.guest] DEBUG: cuckoo-2.0-sierra-bs: not ready yet
2018-07-06 18:14:49,330 [cuckoo.core.guest] DEBUG: cuckoo-2.0-sierra-bs: not ready yet
2018-07-06 18:14:49,340 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=cuckoo-2.0-sierra-bs, ip=192.168.56.105)
2018-07-06 18:14:49,347 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo-2.0-sierra-bs, ip=192.168.56.105, monitor=latest, size=109360)
2018-07-06 18:14:49,511 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2018-07-06 18:14:49,512 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo-2.0-sierra-bs
2018-07-06 18:14:51,490 [cuckoo.core.scheduler] ERROR: ESC[31mFailure in AnalysisManager.runESC[0m
Traceback (most recent call last):
  File "/opt/.cuckoovenv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 737, in run
    self.launch_analysis()
  File "/opt/.cuckoovenv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 527, in launch_analysis
    self.guest_manage(options)
  File "/opt/.cuckoovenv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/opt/.cuckoovenv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 483, in start_analysis
    self.upload_analyzer(monitor)
  File "/opt/.cuckoovenv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 390, in upload_analyzer
    self.determine_analyzer_path()
  File "/opt/.cuckoovenv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 368, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/opt/.cuckoovenv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 330, in post
    r.raise_for_status()
  File "/opt/.cuckoovenv/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.105:8000/mkdtemp
```
