### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by Crossady** [cuckoosandbox/cuckoo#2208]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
today i install the cuckoo and try to run the example in the document
"cuckoo submit --url  bing.com"
Then I ran into a strange error.
```
Traceback (most recent call last):
  File "C:/tmpbsou6y/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmpbsou6y/analyzer.py", line 650, in run
    pids = self.package.start(self.target)
  File "C:\tmpbsou6y\modules\packages\ie.py", line 125, in start
    iexplore = self.get_path("Internet Explorer")
  File "C:\tmpbsou6y\lib\common\abstracts.py", line 79, in get_path
    for path in self.enum_paths():
  File "C:\tmpbsou6y\lib\common\abstracts.py", line 62, in enum_paths
    os.getenv("HomeDrive") + "\\",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
##### My Cuckoo version and operating system are:
Cuckoo version: 2.0.5
Guests: windows 7
Hosts: Ubuntu 16.04
##### This can be reproduced by:
I tried files and urls, got same reuslt.
I have noticed[ issue 890](https://github.com/cuckoosandbox/cuckoo/issues/890)
And I tried run python on windows7, got the same result as McCurity.

##### The log, error, files etc can be found at:
Analyzer.log
```
2018-03-30 05:07:56,000 [analyzer] DEBUG: Starting analyzer from: C:\tmpbsou6y
2018-03-30 05:07:56,078 [analyzer] DEBUG: Pipe server name: \??\PIPE\JSBqYZtOAkTWvkpSUJcvoN
2018-03-30 05:07:56,078 [analyzer] DEBUG: Log pipe server name: \??\PIPE\WUfNydzlkfhaZkzO
2018-03-30 05:07:56,092 [analyzer] DEBUG: No analysis package specified, trying to detect it automagically.
2018-03-30 05:07:56,092 [analyzer] INFO: Automatically selected analysis package "ie"
2018-03-30 05:07:57,875 [analyzer] DEBUG: Started auxiliary module DbgView
2018-03-30 05:07:58,453 [analyzer] DEBUG: Started auxiliary module Disguise
2018-03-30 05:07:59,233 [analyzer] DEBUG: Loaded monitor into process with pid 456
2018-03-30 05:07:59,233 [analyzer] DEBUG: Started auxiliary module DumpTLSMasterSecrets
2018-03-30 05:07:59,233 [analyzer] DEBUG: Started auxiliary module Human
2018-03-30 05:07:59,233 [analyzer] DEBUG: Started auxiliary module InstallCertificate
2018-03-30 05:07:59,233 [analyzer] DEBUG: Started auxiliary module Reboot
2018-03-30 05:07:59,233 [modules.auxiliary.recentfiles] WARNING: Error obtaining user directory: 0x-7ff8fffe
2018-03-30 05:07:59,233 [analyzer] DEBUG: Started auxiliary module RecentFiles
2018-03-30 05:07:59,233 [analyzer] DEBUG: Started auxiliary module Screenshots
2018-03-30 05:07:59,233 [analyzer] DEBUG: Started auxiliary module LoadZer0m0n
```
cuckoo.log
```
2018-03-30 05:09:28,673 [cuckoo.core.scheduler] INFO: Task #5: acquired machine window7 (label=window7)
2018-03-30 05:09:28,709 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 18445 (interface=virbr0, host=192.168.88.131)
2018-03-30 05:09:28,709 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2018-03-30 05:09:28,725 [cuckoo.machinery.virtualbox] DEBUG: Starting vm window7
2018-03-30 05:09:28,850 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine window7 to Snapshot1
2018-03-30 05:09:31,158 [cuckoo.core.guest] INFO: Starting analysis on guest (id=window7, ip=192.168.88.131)
2018-03-30 05:09:32,162 [cuckoo.core.guest] DEBUG: window7: not ready yet
2018-03-30 05:09:33,166 [cuckoo.core.guest] DEBUG: window7: not ready yet
2018-03-30 05:09:34,174 [cuckoo.core.guest] DEBUG: window7: not ready yet
2018-03-30 05:09:35,181 [cuckoo.core.guest] DEBUG: window7: not ready yet
2018-03-30 05:09:36,188 [cuckoo.core.guest] DEBUG: window7: not ready yet
2018-03-30 05:09:37,191 [cuckoo.core.guest] DEBUG: window7: not ready yet
2018-03-30 05:09:37,212 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=window7, ip=192.168.88.131)
2018-03-30 05:09:37,234 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=window7, ip=192.168.88.131, monitor=latest, size=3840773)
2018-03-30 05:09:38,007 [cuckoo.core.guest] DEBUG: window7: analysis still processing
2018-03-30 05:09:39,023 [cuckoo.core.guest] DEBUG: window7: analysis still processing
2018-03-30 05:09:40,032 [cuckoo.core.guest] DEBUG: window7: analysis still processing
2018-03-30 05:09:41,043 [cuckoo.core.guest] DEBUG: window7: analysis still processing
2018-03-30 05:09:41,044 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2018-03-30 05:09:42,058 [cuckoo.core.guest] DEBUG: window7: analysis still processing
2018-03-30 05:09:43,072 [cuckoo.core.guest] DEBUG: window7: analysis still processing
2018-03-30 05:09:44,078 [cuckoo.core.guest] DEBUG: window7: analysis still processing
2018-03-30 05:09:45,086 [cuckoo.core.guest] WARNING: window7: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpbsou6y/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmpbsou6y/analyzer.py", line 650, in run
    pids = self.package.start(self.target)
  File "C:\tmpbsou6y\modules\packages\ie.py", line 125, in start
    iexplore = self.get_path("Internet Explorer")
  File "C:\tmpbsou6y\lib\common\abstracts.py", line 79, in get_path
    for path in self.enum_paths():
  File "C:\tmpbsou6y\lib\common\abstracts.py", line 62, in enum_paths
    os.getenv("HomeDrive") + "\\",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

2018-03-30 05:09:45,146 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2018-03-30 05:09:45,147 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm window7
2018-03-30 05:09:48,393 [cuckoo.core.scheduler] DEBUG: Released database task #5
2018-03-30 05:09:48,473 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #5
2018-03-30 05:09:48,475 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #5
2018-03-30 05:09:48,476 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #5
2018-03-30 05:09:48,476 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #5
2018-03-30 05:09:48,477 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #5
2018-03-30 05:09:48,478 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #5
2018-03-30 05:09:48,479 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #5
2018-03-30 05:09:48,479 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #5
2018-03-30 05:09:48,480 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #5
2018-03-30 05:09:48,480 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #5
2018-03-30 05:09:48,481 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #5
2018-03-30 05:09:48,482 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #5
2018-03-30 05:09:48,483 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #5
2018-03-30 05:09:48,483 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #5
2018-03-30 05:09:48,487 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #5
2018-03-30 05:09:48,490 [cuckoo.core.plugins] DEBUG: Running 473 signatures
2018-03-30 05:09:48,608 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
```

**Comment by Crossady** [comment]
I try install it again and it works。 I don't know why
