### ISSUE TITLE
can't generate report with pdf files

### ISSUE THREAD

**Issue by rayenmessaoudi** [cuckoosandbox/cuckoo#2209]
##### My issue is:
Can't generate report with pdf files.
##### My Cuckoo version and operating system are:
version : 2.0.5
OS : ubuntu 16.04

##### The log, error :
2018-03-29 14:35:59,063 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 614, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 264, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
DocumentTooLarge: BSON document too large (63188990 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.

**Comment by anand-guddu** [comment]
ssdeep hash: tnxLSUXY7WSIGgjQvYaxKMiZA+yH6uw1ECvGX6H7O3YpPNaG
md5 hash: 48e4a8c42a7e84c8279d1b489dc51023

**Comment by doomedraven** [comment]
search in issues i have posted solutions too many times
