### ISSUE TITLE
Database error counting machines

### ISSUE THREAD

**Issue by BhautikRamani** [cuckoosandbox/cuckoo#2241]
Hello Dears,
When I tried to submit the sample from the web interface, it throws me this.

2018-04-23 12:00:00,784[cuckoo.core.database] DEBUG: Database error counting machines: (sqlite3.OperationalError) no such table: machines [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT machines.id AS machines_id, machines.name AS machines_name, machines.label AS machines_label, machines.ip AS machines_ip, machines.platform AS machines_platform, machines.options AS machines_options, machines.interface AS machines_interface, machines.snapshot AS machines_snapshot, machines.locked AS machines_locked, machines.locked_changed_on AS machines_locked_changed_on, machines.status AS machines_status, machines.status_changed_on AS machines_status_changed_on, machines.resultserver_ip AS machines_resultserver_ip, machines.resultserver_port AS machines_resultserver_port \nFROM machines \nWHERE machines.locked = 0) AS anon_1']

**Comment by jbremer** [comment]
Please run `cuckoo` once before running `cuckoo web`. Your database isn't initialized.

**Comment by BhautikRamani** [comment]
ok thanks, @jbremer

**Comment by BhautikRamani** [comment]
thanks @jbremer ,
its solved.
But I got another issue after completing the sample. Getting error message in the report : **Unable to stop auxiliary module: Sniffer**.
Should I do any changes in the auxiliary.conf?

**Comment by jbremer** [comment]
Can you post more log lines than just the `unable to..` line?

**Comment by BhautikRamani** [comment]
2018-04-23 12:30:50,609 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2018-04-23 12:30:50,675 [cuckoo.machinery.virtualbox] DEBUG: Starting vm cuckoo1
2018-04-23 12:30:50,853 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine cuckoo1 to its current snapshot
2018-04-23 12:31:26,304 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.1.61)
2018-04-23 12:31:27,348 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-23 12:31:28,353 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-23 12:31:29,345 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-23 12:31:31,352 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-23 12:31:34,684 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo1, ip=192.168.1.61)
2018-04-23 12:31:35,119 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo1, ip=192.168.1.61, monitor=latest, size=1791809)
2018-04-23 12:31:37,220 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:38,243 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:39,253 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:40,263 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:41,274 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:42,292 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:43,545 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:44,558 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:45,566 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:46,575 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:47,585 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:48,594 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:49,610 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:50,620 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:51,630 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:52,640 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:53,657 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:54,670 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:55,696 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:56,731 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:57,742 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:58,755 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:31:59,766 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:00,777 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:00,988 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2018-04-23 12:32:01,786 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:02,795 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:03,829 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:04,857 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:05,883 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:06,908 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:07,921 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:08,937 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:09,298 [cuckoo.core.resultserver] DEBUG: New process (pid=2252, ppid=2228, name=InstallBC201401.exe)
2018-04-23 12:32:09,948 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:10,958 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:11,981 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:12,990 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:14,118 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:15,129 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:15,195 [cuckoo.core.resultserver] DEBUG: File upload request for files/77098fbeb11a37c5_46698E37.dat
2018-04-23 12:32:15,210 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 95172
2018-04-23 12:32:16,139 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:17,149 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:17,408 [cuckoo.core.resultserver] DEBUG: File upload request for files/e3b0c44298fc1c14_TSRFF8B.tmp
2018-04-23 12:32:18,189 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:19,199 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:20,305 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:21,314 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:22,346 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:23,361 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:24,377 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:25,743 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:26,818 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:27,835 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:28,931 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:29,942 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:30,968 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:31,980 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:32,990 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:34,043 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:35,059 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:36,072 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:37,080 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:38,142 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:39,153 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:40,173 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:42,700 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:43,762 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:44,773 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:45,781 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:46,791 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:47,802 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:48,817 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:49,828 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:50,852 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:51,862 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:52,878 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:53,889 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:54,901 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:55,911 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:56,933 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:57,955 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:58,973 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:32:59,985 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:00,997 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:02,007 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:03,026 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:04,079 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:05,089 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:06,102 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:07,112 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:08,121 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:09,134 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:10,152 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:11,197 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:12,207 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:13,217 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:14,247 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:15,257 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:16,273 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:17,287 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:18,300 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:19,384 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:20,398 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:21,408 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:22,417 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:23,429 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:24,437 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:25,446 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:26,457 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:27,468 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:28,480 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:29,491 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:30,501 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:31,513 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:32,523 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:33,535 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:34,566 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:35,579 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:36,591 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:37,600 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:38,616 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:39,628 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:40,643 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:41,202 [cuckoo.core.resultserver] DEBUG: New process (pid=2488, ppid=2252, name=regsvr32.exe)
2018-04-23 12:33:41,654 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:42,669 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:43,679 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:44,696 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:45,711 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:46,720 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:47,730 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:48,739 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:49,751 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:50,759 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:51,770 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:52,782 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:53,805 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:54,816 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:55,829 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:56,842 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:57,853 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:58,876 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:33:59,890 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:00,902 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:01,916 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:02,927 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:03,946 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:04,956 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:05,968 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:06,983 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:08,001 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:09,263 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:10,277 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:11,292 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:11,589 [cuckoo.core.resultserver] DEBUG: New process (pid=2580, ppid=2252, name=regsvr32.exe)
2018-04-23 12:34:12,321 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:13,335 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:14,350 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:15,362 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:15,752 [cuckoo.core.resultserver] DEBUG: File upload request for memory/2488-1.dmp
2018-04-23 12:34:16,379 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:17,397 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:18,406 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:19,425 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:20,437 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:21,349 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 46799832
2018-04-23 12:34:21,451 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:22,465 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:23,476 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:24,487 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:25,503 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:26,515 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:27,525 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:28,541 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:29,571 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:30,583 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:31,596 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:32,607 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:33,616 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:34,626 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:35,656 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:35,953 [cuckoo.core.resultserver] DEBUG: File upload request for memory/2580-1.dmp
2018-04-23 12:34:36,410 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 49880072
2018-04-23 12:34:36,675 [cuckoo.core.resultserver] DEBUG: New process (pid=2728, ppid=2252, name=regsvr32.exe)
2018-04-23 12:34:36,683 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2018-04-23 12:34:37,685 [cuckoo.core.guest] INFO: cuckoo1: end of analysis reached!
2018-04-23 12:34:37,891 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 162, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 154, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: vboxnet0: That device is not up\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
2018-04-23 12:34:37,985 [cuckoo.core.resultserver] DEBUG: File upload request for memory/2728-1.dmp
2018-04-23 12:34:38,473 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo1
2018-04-23 12:34:39,029 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 50269288
2018-04-23 12:34:39,353 [cuckoo.core.resultserver] DEBUG: New process (pid=2796, ppid=2252, name=regsvr32.exe)
2018-04-23 12:34:45,387 [cuckoo.core.scheduler] DEBUG: Released database task #1
2018-04-23 12:34:45,458 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #1
2018-04-23 12:34:46,220 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #1
2018-04-23 12:34:46,336 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #1
2018-04-23 12:34:46,337 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #1
2018-04-23 12:34:48,664 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #1
2018-04-23 12:34:50,261 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #1
2018-04-23 12:34:50,262 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #1
2018-04-23 12:34:50,263 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #1
2018-04-23 12:34:55,259 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #1
2018-04-23 12:34:56,183 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #1
2018-04-23 12:34:56,497 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #1
2018-04-23 12:34:56,498 [cuckoo.processing.network] WARNING: The PCAP file does not exist at path "/root/.cuckoo/storage/analyses/1/dump.pcap".
2018-04-23 12:34:56,498 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #1
2018-04-23 12:34:56,499 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #1
2018-04-23 12:34:56,499 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #1
2018-04-23 12:34:56,708 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #1
2018-04-23 12:34:56,709 [cuckoo.core.plugins] DEBUG: Running 0 signatures
2018-04-23 12:35:00,633 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2018-04-23 12:35:04,389 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2018-04-23 12:35:04,389 [cuckoo.core.scheduler] INFO: Task #1: reports generation completed
2018-04-23 12:35:04,401 [cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed

**Comment by doomedraven** [comment]
check your error there is link for solution

**Comment by BhautikRamani** [comment]
I tried that solution which is given in that link, but it didn't work.

**Comment by jbremer** [comment]
Also read the error: `tcpdump: vboxnet0: That device is not up` ;-)

**Comment by BhautikRamani** [comment]
What kind of changes I have to do? 
I tried many things from the cuckoo documents and from other places, but I am not able to solve this issue.

**Comment by RicoVZ** [comment]
Hi BhautikRamani,

As jbremer said, the log contains the error `tcpdump: vboxnet0: That device is not up`. This means the network interface `vboxnet0` cannot be found. Make sure this network interface exists and is up.

**Comment by jbremer** [comment]
Closing issue for lack of additional information - please reopen if you have an update for us.
