### ISSUE TITLE
submit files with python error

### ISSUE THREAD

**Issue by h0rs3fa11** [cuckoosandbox/cuckoo#2254]
##### My issue is:
I use cuckoo document(submit an analysis ->python function),the code is:
```python
from cuckoo.core.database import Database
db = Database()
db.add_path("/tmp/malware.exe")
```
and I got error:
```
Traceback (most recent call last):
  File "submit_cuckoo.py", line 8, in submit
    task_id = db.add_path(SAMPLE_FILE)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 1105, in add_path
    enforce_timeout, clock, "file", submit_id)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/utils.py", line 196, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 981, in add
    session = self.Session()
AttributeError: 'Database' object has no attribute 'Session'
```
Why?How to solve this?
##### My Cuckoo version and operating system are:
2.0.5 and Ubuntu 17.04

**Comment by RicoVZ** [comment]
Hi h0rs3fa11,

Before you can use any of the db methods that add/request data from the Database, you need to call the `.connect()` method. 

So this should work.
```python
from cuckoo.core.database import Database
db = Database()
db.connect()
db.add_path("/tmp/malware.exe")
```

Note: you only have to call the `.connect()` once while your application runs. So it is fine if this is located in some initialization code.

**Comment by h0rs3fa11** [comment]
Hi RicoVZ,Thank you for your answer. After I call connect(), I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    task_id = submit_cuckoo.submit(file_path)
  File "/media/cuckoo/HORSE/GraduationProject/submit_cuckoo.py", line 17, in submit
    db.connect()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 428, in connect
    dsn = config("cuckoo:database:connection")
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/config.py", line 1078, in config
    file_name, cfg=cfg, strict=strict, raw=raw, loose=loose
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/config.py", line 919, in __init__
    config.read(cfg or cwd("conf", "%s.conf" % file_name))
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/misc.py", line 64, in cwd
    return os.path.join(_root, *args)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by RicoVZ** [comment]
Ah, I misunderstood, if you are using the cuckoo libs outside of Cuckoo itself, you also have to specify what the $CWD is. This is were all Cuckoo configs and the database file is stored by default.

The cwd is located in your user home by default.

Try this:

```python
from cuckoo.core.database import Database
from cuckoo.misc import decide_cwd

decide_cwd("path to your cwd")
db = Database()
db.connect()
db.add_path("/tmp/malware.exe")
```

**Comment by h0rs3fa11** [comment]
This problem has been solved, Thank you!
