### ISSUE TITLE
errno attribute in TypeError exception object

### ISSUE THREAD

**Issue by ttufts** [cuckoosandbox/cuckoo#2270]
https://github.com/cuckoosandbox/cuckoo/blob/cee4f2fd8084a988db8c0a1c3017ecedd0d541db/cuckoo/core/resultserver.py#L58

errno attribute appears to only available in OSError exceptions (and maybe only Windows?).

https://docs.python.org/2/library/exceptions.html

On an OS X system, I'm getting an AttributeError during startup. 

2018-05-15 14:02:01,434 [cuckoo] ERROR: AttributeError: 'exceptions.TypeError' object has no attribute 'errno'
Traceback (most recent call last):
  File "~/venv/lib/python2.7/site-packages/cuckoo/main.py", line 234, in main
    cuckoo_main(maxcount)
  File "~/venv/lib/python2.7/site-packages/cuckoo/main.py", line 180, in cuckoo_main
    ResultServer()
  File "~/venv/lib/python2.7/site-packages/cuckoo/common/utils.py", line 131, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "~/venv/lib/python2.7/site-packages/cuckoo/core/resultserver.py", line 58, in __init__
    if e.errno == errno.EADDRINUSE:
AttributeError: 'exceptions.TypeError' object has no attribute 'errno'

---

(venv) bash-3.2$ python -V
Python 2.7.14

(venv) bash-3.2$ pip freeze
alembic==0.8.8
androguard==3.0.1
asn1crypto==0.24.0
beautifulsoup4==4.5.3
capstone==3.0.5rc2
cffi==1.11.5
chardet==2.3.0
click==6.6
colorama==0.3.7
cryptography==2.2.2
Cuckoo==2.0.5.3
Django==1.8.4
django-extensions==1.6.7
dpkt==1.8.7
ecdsa==0.13
egghatch==0.2.2
elasticsearch==5.3.0
enum34==1.1.6
Flask==0.12.2
Flask-SQLAlchemy==2.1
functools32==3.2.3.post2
future==0.16.0
HTTPReplay==0.2.3
idna==2.6
ipaddress==1.0.22
itsdangerous==0.24
Jinja2==2.9.6
jsbeautifier==1.6.2
jsonschema==2.6.0
libmagic==1.0
Mako==1.0.7
MarkupSafe==1.0
olefile==0.43
oletools==0.51
peepdf==0.4.1
pefile2==1.2.11
Pillow==3.2.0
pycparser==2.18
pycrypto==2.6.1
pyelftools==0.24
pyguacamole==0.6
pymisp==2.4.54
pymongo==3.0.3
python-dateutil==2.4.2
python-editor==1.0.3
python-magic==0.4.12
pythonaes==1.0
requests==2.13.0
roach==0.1.2
SFlock==0.3.2
six==1.11.0
SQLAlchemy==1.0.8
tlslite-ng==0.6.0
unicorn==1.0.1
urllib3==1.22
wakeonlan==0.2.2
Werkzeug==0.14.1
yara-python==3.6.3

**Comment by jbremer** [comment]
Hm, interesting. Could you perhaps log which exception is being thrown for you? Thanks!

**Comment by RicoVZ** [comment]
Thanks for posting the exception @ttufts :smile: . We will take a look into it.

**Comment by b0urb0n** [comment]
I can make a pull-request for this.  My approach would be to just replace the instances of `e.errno` with `getattr(e, 'errno', None)`

**Comment by b0urb0n** [comment]
PR: https://github.com/cuckoosandbox/cuckoo/pull/2378
