### ISSUE TITLE
Command Line arguments of binary file

### ISSUE THREAD

**Issue by AliHussainciit** [cuckoosandbox/cuckoo#2272]
**What is the correct way to pass command line arguments to the binary file using the submit utility of cuckoo?**

 First of all my cuckoo installation is working fine as it should be. I was reading the documentation provided on the official cuckoo's site, I came across the command line argument to the binary file through the submit utility of the cuckoo.

**Example: submit a local binary and specify a custom analysis package and some options (in this case a command line argument for the malware):**
**$ cuckoo submit --package exe --options arguments=--dosomething /path/to/binary.exe**

Now I am trying to submit the .exe of the C-language program which takes an input string named data with the following command.

**cuckoo submit --package exe --timeout 7 --platform windows --options --arguments "data=ali.txt" main64.exe**

or

**cuckoo submit --package exe --timeout 7 --platform windows --options arguments="data=ali.txt" main64.exe**

 The above command ends up with the error **Unable to execute the initial process, analysis aborted** which is described in the cuckoo logs below.

`2018-05-21 11:11:06,294 [cuckoo.core.scheduler] INFO: Task #20: acquired machine windowsxp (label=windowsxp)
2018-05-21 11:11:06,326 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 5727 (interface=vboxnet0, host=192.168.56.10)
2018-05-21 11:11:06,329 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2018-05-21 11:11:06,496 [cuckoo.machinery.virtualbox] DEBUG: Starting vm windowsxp
2018-05-21 11:11:07,479 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine windowsxp to snapshot1
2018-05-21 11:11:14,294 [cuckoo.core.guest] INFO: Starting analysis on guest (id=windowsxp, ip=192.168.56.10)
2018-05-21 11:11:15,307 [cuckoo.core.guest] DEBUG: windowsxp: not ready yet
2018-05-21 11:11:15,619 [cuckoo.core.guest] DEBUG: windowsxp: not ready yet
2018-05-21 11:11:17,636 [cuckoo.core.guest] DEBUG: windowsxp: not ready yet
2018-05-21 11:11:18,640 [cuckoo.core.guest] DEBUG: windowsxp: not ready yet
2018-05-21 11:11:18,649 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=windowsxp, ip=192.168.56.10)
2018-05-21 11:11:19,397 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=windowsxp, ip=192.168.56.10, monitor=latest, size=3840932)
2018-05-21 11:11:20,028 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:21,047 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:22,070 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:23,092 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:24,116 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:25,140 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:26,163 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:27,131 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2018-05-21 11:11:27,169 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:28,191 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:29,199 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:30,223 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2018-05-21 11:11:31,228 [cuckoo.core.guest] WARNING: windowsxp: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmp7pezmd/analyzer.py", line 798, in <module>
    **success = analyzer.run()
  File "C:/tmp7pezmd/analyzer.py", line 650, in run
    pids = self.package.start(self.target)
  File "C:\tmp7pezmd\modules\packages\exe.py", line 25, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmp7pezmd\lib\common\abstracts.py", line 166, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.**

2018-05-21 11:11:31,708 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2018-05-21 11:11:31,709 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm windowsxp
2018-05-21 11:11:37,007 [cuckoo.core.scheduler] DEBUG: Released database task #20
2018-05-21 11:11:37,214 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #20
2018-05-21 11:11:37,214 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2018-05-21 11:11:37,215 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #20
2018-05-21 11:11:37,215 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #20
2018-05-21 11:11:37,215 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #20
2018-05-21 11:11:37,216 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #20
2018-05-21 11:11:37,217 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #20
2018-05-21 11:11:37,217 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #20
2018-05-21 11:11:37,217 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #20
2018-05-21 11:11:37,588 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #20
2018-05-21 11:11:37,597 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #20
2018-05-21 11:11:37,605 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #20
2018-05-21 11:11:42,653 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #20
2018-05-21 11:11:42,654 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #20
2018-05-21 11:11:42,655 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #20
2018-05-21 11:11:42,663 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #20
2018-05-21 11:11:42,667 [cuckoo.core.plugins] DEBUG: Running 472 signatures
2018-05-21 11:11:42,815 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
`

**Comment by doomedraven** [comment]
did you try without that ali.txt?

**Comment by AliHussainciit** [comment]
but i need to pass the argument so that the main64.exe can create file named **ali.txt**. The main64.exe stops for user input, analyzer waits and terminate the analysis on timeout.

**Comment by doomedraven** [comment]
just try without to see if that works without that

**Comment by AliHussainciit** [comment]
I have tried without the "ali.txt" analysis completes fine but the timeout triggers because of main64.exe requires input from the user with scanf() function of c.

**Comment by doomedraven** [comment]
well now you know what you need to investigate

**Comment by RicoVZ** [comment]
Hi AliHussainciit,

Thanks for creating an issue.

If your goal here is to execute the executable `main64.exe` with the command line arguments `data=ali.txt`, then using `--options arguments="data=ali.txt"` should work. I just tried it with a random exe, and the arguments do get passed to it.

Note that the `arguments` key is for passing command line arguments.

Another note: I am not sure if it is your goal, but in the submission commands you have posted, you are using `--timeout 7`. It is your goal to have the analysis time out after 7 seconds? As `--timeout` accepts the timeout in seconds.

**Comment by AliHussainciit** [comment]
Thanks RicoVZ,
I can adjust the timeout option, but my real concern was,  how to pass the arguments to the binary file? which is resolved now. **Thanks everyone for your time.**
