### ISSUE TITLE
cuckoo latest version not working

### ISSUE THREAD

**Issue by cuckoo-linux** [cuckoosandbox/cuckoo#2286]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
cuckoo not working 

##### My Cuckoo version and operating system are:
ubuntu 13.10
cuckoo latest release in october 2017

##### The log, error, files etc can be found at:
cuckoo@cuckoo-OptiPlex-9020:~$ cuckoo -d
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sqlalchemy==1.0.8' distribution was not found and is required by Cuckoo

**Comment by doomedraven** [comment]
Lol why do you use sonold cuckoo and ubuntu? You should use ubuntu 16.04 and latest cuckoo 2.0.5

**Comment by RicoVZ** [comment]
Hi cuckoo-linux,

This following error is the problem:
`pkg_resources.DistributionNotFound: The 'sqlalchemy==1.0.8' distribution was not found and is required by Cuckoo`

It states you do not have the required `sqlachemy` version installed. You can get that specific version by using `pip install sqlalchemy==1.0.8`.

**Comment by jbremer** [comment]
`sqlalchemy` probably fails to install on your version of Ubuntu or so. Closing issue for lack of additional information - please reopen if you have an update for us.
