### ISSUE TITLE
Cuckoo start error

### ISSUE THREAD

**Issue by Add420** [cuckoosandbox/cuckoo#2296]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:

 Cuckoo Sandbox              <(a  `---','
     no chance for malwares!  ( `-, ._> )
                               ) _>.___/
                                   _/

 Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.5.3', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 240, in main
    sys.stderr.write(exception_message())
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/utils.py", line 260, in exception_message
    for package in pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'

**Comment by doomedraven** [comment]
You need to do a downgrade of pip 

pip install pip==9.0.3

**Comment by Add420** [comment]
Thanks doomedraven got it fixed. Modified the config file and cuckoo is running now.

**Comment by michaelkasede** [comment]
@Add420 I have the same exact problem. What do I modify in the config file to get cuckoo to work?
Please help. I keep running into a different problem after fixing another. @RicoVZ I think am almost giving up on this installation. Need your help.

           _       _                   _             _              _            _
          /\ \     /\_\               /\ \           /\_\           /\ \         /\ \
         /  \ \   / / /         _    /  \ \         / / /  _       /  \ \       /  \ \
        / /\ \ \  \ \ \__      /\_\ / /\ \ \       / / /  /\_\    / /\ \ \     / /\ \ \
       / / /\ \ \  \ \___\    / / // / /\ \ \     / / /__/ / /   / / /\ \ \   / / /\ \ \
      / / /  \ \_\  \__  /   / / // / /  \ \_\   / /\_____/ /   / / /  \ \_\ / / /  \ \_\
     / / /    \/_/  / / /   / / // / /    \/_/  / /\_______/   / / /   / / // / /   / / /
    / / /          / / /   / / // / /          / / /\ \ \     / / /   / / // / /   / / /
   / / /________  / / /___/ / // / /________  / / /  \ \ \   / / /___/ / // / /___/ / /
  / / /_________\/ / /____\/ // / /_________\/ / /    \ \ \ / / /____\/ // / /____\/ /
  \/____________/\/_________/ \/____________/\/_/      \_\_\\/_________/ \/_________/

 Cuckoo Sandbox 2.0.6
 www.cuckoosandbox.org
 Copyright (c) 2010-2018

2018-12-05 17:41:17,742 [pip._internal.vcs] DEBUG: Registered VCS backend: git
2018-12-05 17:41:17,743 [pip._internal.vcs] DEBUG: Registered VCS backend: hg
2018-12-05 17:41:17,744 [pip._internal.vcs] DEBUG: Registered VCS backend: svn
2018-12-05 17:41:17,744 [pip._internal.vcs] DEBUG: Registered VCS backend: bzr
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 242, in main
    sys.stderr.write(exception_message())
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/utils.py", line 262, in exception_message
    for package in pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'

**Comment by CorbinHu** [comment]
> Thanks doomedraven for your help. I am still getting other error. It says configuration error. However, I have check the conf files its ok as per the installation tutorial.
> 
> cuckoo@ubuntu:~$ cuckoo
> 
> ```
>         _       _                   _             _              _            _
>       /\ \     /\_\               /\ \           /\_\           /\ \         /\ \
>      /  \ \   / / /         _    /  \ \         / / /  _       /  \ \       /  \ \
>     / /\ \ \  \ \ \__      /\_\ / /\ \ \       / / /  /\_\    / /\ \ \     / /\ \ \
>    / / /\ \ \  \ \___\    / / // / /\ \ \     / / /__/ / /   / / /\ \ \   / / /\ \ \
>   / / /  \ \_\  \__  /   / / // / /  \ \_\   / /\_____/ /   / / /  \ \_\ / / /  \ \_\
>  / / /    \/_/  / / /   / / // / /    \/_/  / /\_______/   / / /   / / // / /   / / /
> / / /          / / /   / / // / /          / / /\ \ \     / / /   / / // / /   / / /
> ```
> 
> / / /________ / / /_**/ / // / /**______ / / / \ \ \ / / /_**/ / // / /**_/ / /
> / / /_********/ / /****/ // / /****_****/ / / \ \ \ / / /****/ // / /****/ / /************//********_/ /___********_//_/ __\/********_/ /_________/
> 
> Cuckoo Sandbox 2.0.5
> [www.cuckoosandbox.org](http://www.cuckoosandbox.org)
> Copyright (c) 2010-2017
> 
> 2018-06-04 18:14:54,363 [cuckoo.common.config] ERROR: Type of config parameter auxiliary:sniffer:interface not found! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.
> 2018-06-04 18:14:54,365 [cuckoo] CRITICAL: CuckooConfigurationError: Configuration value auxiliary:sniffer:bpf not present! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.

How did you solve this question, and also encountered the same problem?

**Comment by elnazkm** [comment]
I got the same error. How should I resolve it ?

ubuntu@ubuntu:~$ cuckoo -d

                               ),-.     /
  Cuckoo Sandbox              <(a  `---','
     no chance for malwares!  ( `-, ._> )
                               ) _>.___/
                                   _/

 Cuckoo Sandbox 2.0.7
 www.cuckoosandbox.org
 Copyright (c) 2010-2018

2019-10-08 15:29:00,868 [cuckoo] DEBUG: Increasing resource limit for number of open files to 4096
2019-10-08 15:29:00,868 [cuckoo] ERROR: The maximum number of open files is low (4096). If you do not increase it, you may run into errors later on.
2019-10-08 15:29:00,868 [cuckoo] ERROR: See also: https://cuckoo.sh/docs/faq/index.html#ioerror-errno-24-too-many-open-files
2019-10-08 15:29:00,869 [cuckoo] CRITICAL: CuckooConfigurationError: Configuration value auxiliary:sniffer:bpf not present! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.
