### ISSUE TITLE
Repeated needless opening of Start menu during analysis

### ISSUE THREAD

**Issue by capnspacehook** [cuckoosandbox/cuckoo#2306]
Every analysis I've done so far using Cuckoo, using a fresh XP box as a sandbox has resulted in Cuckoo thinking the Windows start menu button is a button of the malware, and continually presses it. Sample log:

```2018-06-05 13:01:06,000 [analyzer] DEBUG: Starting analyzer from: C:\tmpqijh57
2018-06-05 13:01:06,000 [analyzer] DEBUG: Pipe server name: \\.\PIPE\pqCfunegsqnXmyQyhHEvMPyFPjuSLCP
2018-06-05 13:01:06,000 [analyzer] DEBUG: Log pipe server name: \\.\PIPE\ZjqDjNvhwwGrtBHGPOSrtr
2018-06-05 13:01:06,437 [analyzer] DEBUG: Started auxiliary module DbgView
2018-06-05 13:01:08,796 [analyzer] DEBUG: Started auxiliary module Disguise
2018-06-05 13:01:09,062 [analyzer] DEBUG: Loaded monitor into process with pid 904
2018-06-05 13:01:09,062 [analyzer] DEBUG: Started auxiliary module DumpTLSMasterSecrets
2018-06-05 13:01:09,062 [analyzer] DEBUG: Started auxiliary module Human
2018-06-05 13:01:09,062 [analyzer] DEBUG: Started auxiliary module InstallCertificate
2018-06-05 13:01:09,062 [analyzer] DEBUG: Started auxiliary module Reboot
2018-06-05 13:01:09,062 [analyzer] ERROR: Auxiliary module RecentFiles was not implemented
Traceback (most recent call last):
  File "C:/tmpqijh57/analyzer.py", line 624, in run
    aux.start()
  File "C:\tmpqijh57\modules\auxiliary\recentfiles.py", line 55, in start
    dirpath = self.get_path()
  File "C:\tmpqijh57\modules\auxiliary\recentfiles.py", line 43, in get_path
    r = SHELL32.SHGetKnownFolderPath(
  File "C:\Python27\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SHGetKnownFolderPath' not found
2018-06-05 13:01:09,062 [analyzer] DEBUG: Started auxiliary module Screenshots
2018-06-05 13:01:09,062 [analyzer] DEBUG: Started auxiliary module LoadZer0m0n
2018-06-05 13:01:09,062 [analyzer] INFO: No process IDs returned by the package, running for the full timeout.
2018-06-05 13:01:09,125 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:11,546 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:13,655 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:15,733 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:17,875 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:19,967 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:22,046 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:24,203 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:26,312 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:28,405 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:30,483 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:32,640 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:34,733 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:36,875 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:39,062 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:41,203 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:43,467 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:45,578 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:47,655 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:49,780 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:51,890 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:53,983 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:56,062 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:01:58,187 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:00,265 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:02,342 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:04,467 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:06,546 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:08,625 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:10,703 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:12,858 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:15,015 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:17,092 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:19,171 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:21,250 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:23,390 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:25,467 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:27,546 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:29,655 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:31,780 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:33,858 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:35,937 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:38,015 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:40,203 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:42,280 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:44,358 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:46,437 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:48,546 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:50,625 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:52,703 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:54,780 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:56,890 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:02:58,967 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:03:01,046 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:03:03,125 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:03:05,233 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:03:07,312 [modules.auxiliary.human] INFO: Found button u'start', clicking it
2018-06-05 13:03:08,375 [analyzer] INFO: Analysis timeout hit, terminating analysis.
2018-06-05 13:03:08,375 [analyzer] INFO: Analysis completed.
```

Is this normal behavior? Or is this an error with the human.py logic?

**Comment by RicoVZ** [comment]
Hi capnspacehook,

Thanks for posting an issue.

Well, unfortunately yes. The Human module operates by detecting a Windows dialogs etc and the buttons in it. In Windows XP, the start button is a button of this class.

The Human will click one of these buttons if its button label is in its list of strings. This list contains things  like: _execute, open, start_, etc, in several languages. Currently, the only way to get it to stop showing this behavior in Windows XP, is removing the string "start" from this list.

You edit this file in your working directory:
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data/analyzer/windows/modules/auxiliary/human.py#L39

**Comment by capnspacehook** [comment]
Ok thanks. Makes sense. Guess I'll add an if statement that will remove 'start' from the list of buttons to click if the guest is XP. Let me know if you would want me to make this a pull request, or possibly look into other methods of not clicking the start menu in XP while not removing the 'start' string altogether.

**Comment by RicoVZ** [comment]
@capnspacehook Thanks :smile:  We are currently already working on a renewed human module in which this issue should be solved. So it won't be needed for now.

**Comment by capnspacehook** [comment]
Ok sounds good! Closing issue then.
