### ISSUE TITLE
Fail to install egghatch [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by giveitatry168** [cuckoosandbox/cuckoo#2317]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:
# pip install egghatch
Collecting egghatch
  Downloading https://files.pythonhosted.org/packages/08/86/e966e2a1821daf3da6ac244cfe13288f13ac092d0da5bd18e57e263c0ae8/egghatch-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579) -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p0ilGr/egghatch/setup.py", line 57, in <module>
        "mock==2.0.0",
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1053, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-p0ilGr/egghatch/

Please note that pip.conf is:
[global]
trusted-host = pypi.python.org
               pypi.org
               files.pythonhosted.org

All other packages were installed fine except this one (egghatch).

**Comment by RicoVZ** [comment]
Hi giveitatry168,

Thanks for posting an issue.

I have not been able to reproduce this issue. Can you try upgrading your pip version?
It seems multiple pip users are having this issue: https://github.com/pypa/pip/issues/4459 and the advice there is to upgrade the version.

**Comment by giveitatry168** [comment]
Hi RicoVZ,

Thanks for your quick response. My pip version is already uptodate:

# pip install --upgrade --user pip --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages (10.0.1)

**Comment by giveitatry168** [comment]
False alarm. It turns out I need to enable company certificate.
