### ISSUE TITLE
Failed to run the processing module "Static"

### ISSUE THREAD

**Issue by mkrsfcmp** [cuckoosandbox/cuckoo#2335]
##### My issue is:
After update to 2.0.6.1 every analysis fails to run static analysis.

##### My Cuckoo version and operating system are:

$ pip list | grep -i cuckoo
Cuckoo                       2.0.6.1    
$ cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 

##### This can be reproduced by:

Running any analysis.

##### The log, error, files etc can be found at:

cuckoo.log contains:
```
[...]
2018-06-21 02:16:27,429 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Static" for task #155:
Traceback (most recent call last):
  File "/home/cuckoo/venv/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 241, in process
    data = current.run()
  File "/home/cuckoo/venv/lib/python2.7/site-packages/cuckoo/processing/static.py", line 1075, in run
    static.update(PortableExecutable(f.file_path).run())
  File "/home/cuckoo/venv/lib/python2.7/site-packages/cuckoo/processing/static.py", line 317, in run
    results["signature"] = self._get_signature()
  File "/home/cuckoo/venv/lib/python2.7/site-packages/cuckoo/processing/static.py", line 281, in _get_signature
    "email": subject.Email,
  File "/home/cuckoo/venv/lib/python2.7/site-packages/M2Crypto/X509.py", line 317, in __getattr__
    return six.ensure_text(m2.x509_name_by_nid(self.x509_name, self.nid[attr]))
  File "/home/cuckoo/venv/lib/python2.7/site-packages/M2Crypto/six.py", line 906, in ensure_text
    raise TypeError("not expecting type '%s'" % type(s))
TypeError: not expecting type '<type 'NoneType'>'
[...]
```

For reference pip list from my system:
```
Package                      Version    
---------------------------- -----------
alembic                      0.8.8      
androguard                   3.0.1      
argh                         0.26.2     
asn1crypto                   0.24.0     
backports-abc                0.5        
backports.ssl-match-hostname 3.5.0.1    
beautifulsoup4               4.5.3      
blinker                      1.4        
brotlipy                     0.6.0      
cairocffi                    0.8.1      
CairoSVG                     1.0.22     
capstone                     3.0.5rc2   
certifi                      2018.4.16  
cffi                         1.11.5     
chardet                      2.3.0      
click                        6.6        
colorama                     0.3.7      
ConfigArgParse               0.11.0     
construct                    2.5.3      
cryptography                 2.2.2      
cssselect2                   0.2.1      
cssutils                     1.0.2      
Cuckoo                       2.0.6.1    
distorm3                     3.3.4      
Django                       1.8.4      
django-extensions            1.6.7      
dpkt                         1.8.7      
ecdsa                        0.13       
EditorConfig                 0.12.2     
egghatch                     0.2.2      
elasticsearch                5.3.0      
enum34                       1.1.6      
Flask                        0.12.2     
Flask-SQLAlchemy             2.1        
functools32                  3.2.3.post2
future                       0.16.0     
h2                           2.4.4      
hpack                        2.3.0      
html2text                    2016.9.19  
html5lib                     1.0.1      
HTTPReplay                   0.2.3      
hyperframe                   4.0.2      
idna                         2.7        
ipaddress                    1.0.22     
itsdangerous                 0.24       
Jinja2                       2.9.6      
jsbeautifier                 1.6.2      
jsonschema                   2.6.0      
lxml                         3.6.0      
M2Crypto                     0.30.1     
Mako                         1.0.7      
MarkupSafe                   1.0        
mitmproxy                    0.18.2     
olefile                      0.43       
oletools                     0.51       
passlib                      1.6.5      
pathtools                    0.1.2      
pdfrw                        0.4        
peepdf                       0.4.2      
pefile2                      1.2.11     
Pillow                       3.2.0      
pip                          10.0.1     
pyasn1                       0.1.9      
pycparser                    2.18       
pycrypto                     2.6.1      
pydeep                       0.2        
pyelftools                   0.24       
pyguacamole                  0.6        
pymisp                       2.4.54     
pymongo                      3.0.3      
pyOpenSSL                    16.2.0     
pyparsing                    2.1.10     
pyperclip                    1.5.32     
Pyphen                       0.9.4      
python-dateutil              2.4.2      
python-editor                1.0.3      
python-magic                 0.4.12     
pythonaes                    1.0        
PyYAML                       3.12       
requests                     2.13.0     
roach                        0.1.2      
scapy                        2.3.2      
setuptools                   28.8.0     
SFlock                       0.3.5      
singledispatch               3.4.0.3    
six                          1.10.0     
SQLAlchemy                   1.0.8      
tinycss2                     0.6.1      
tlslite-ng                   0.6.0      
tornado                      4.4.3      
typing                       3.5.2.2    
unicorn                      1.0.1      
urllib3                      1.23       
urwid                        1.3.1      
volatility                   2.6        
wakeonlan                    0.2.2      
watchdog                     0.8.3      
WeasyPrint                   0.42.3     
webencodings                 0.5.1      
Werkzeug                     0.14.1     
wheel                        0.29.0     
yara-python                  3.6.3      

```

**Comment by RicoVZ** [comment]
Hi mkrsfcmp,

Thanks for posting an issue.

Can you share the sample you were analyzing with us? :smile: 
That way we can reproduce and fix the issue.

**Comment by RicoVZ** [comment]
@mkrsfcmp 
I overlooked the version of your m2crypto. :sweat_smile: 
At this time, Cuckoo needs a specific version `0.24.0`.

I could confirm the error. It only happens with other versions than the recommended version, though.

Try `pip install m2crypto==0.24.0`.

**Comment by mkrsfcmp** [comment]
Yep. Downgrading to 0.24.0 seems to have helped.
Two things though:
1) I don't recall having anything else installed on this machine so upgrade to 0.30.1 must have happened as a side effect of upgrading cuckoo.
2) After upgrading/downgrading modules the server still doesn't work very well up to the need of reboot. I have no clue why since I restart all cuckoo services and still have problems.
But after complete reboot it seems that it's working for now. And the score jumped from 10.4 to 12 (Out of 10 :rofl: )
