### ISSUE TITLE
Error when running cuckoo

### ISSUE THREAD

**Issue by jakilla** [cuckoosandbox/cuckoo#2341]
hello, I have a problem with the launch of cuckoo

##### The log, error, files etc can be found at:   

2018-06-26 05:50:01,977 [cuckoo] ERROR: KeyError: 'label'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 234, in main
    cuckoo_main(maxcount)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 182, in cuckoo_main
    sched.start()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 903, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 838, in initialize
    machinery.initialize(machinery_name)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/abstracts.py", line 175, in initialize
    self._initialize(module_name)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/abstracts.py", line 211, in _initialize
    label=options[self.LABEL],
KeyError: 'label'

I do not understand where these errors come from 

if anyone could enlighten me that would be very nice

**Comment by RicoVZ** [comment]
Hi jakilla,

Thanks for posting an issue.

I suspect this error is caused by missing fields in a machinery config file. Are you using Virtualbox? If so, please post the output of `$CWD/conf/virtualbox.conf`. If you are using another machinery module, please post its config.

**Comment by jakilla** [comment]
[virtualbox]
* Specify which VirtualBox mode you want to run your machines on.
* Can be "gui" or "headless". Please refer to VirtualBox's official
* documentation to understand the differences.
mode = headless

* Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
* If you are running Cuckoo on Mac OS X you have to change the path as follows:
* path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

* Default network interface.
interface = vboxnet0

* Specify a comma-separated list of available machines to be used. For each
* specified ID you have to define a dedicated section containing the details
* on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = analys

* If remote control is enabled in cuckoo.conf, specify a port range to use.
* Virtualbox will bind the VRDP interface to the first available port.
controlports = 5000-5050

[analys]
* Specify the label name of the current machine as specified in your
* VirtualBox configuration.
* label = analys

* Specify the operating system platform used by current machine
* [windows/darwin/linux].
platform = windows

* Specify the IP address of the current virtual machine. Make sure that the
* IP address is valid and that the host machine is able to reach it. If not,
* the analysis will fail.
ip = 10.0.2.15

Thank you for your prompt response

after looking at my virtualbox configuration file, i noticed that there was a small mistake, after adjusting it, the errors that i have indicated are gone but there is a critical error that indicates that cuckoo n can not find my virtual machine


> CuckooCriticalError: Please update your configuration. Unable to shut 'analys' down or find the machine in its proper state: The virtual machine 'analys' doesn't exist! Please create one or more Cuckoo analysis VMs and properly fill out the Cuckoo configuration!

my vm communicates well with my cuckoo...


![image](https://user-images.githubusercontent.com/40600995/41918753-3efc794e-795d-11e8-9188-c2e7df10abfc.png)

**Comment by RicoVZ** [comment]
@jakilla Great, that is one error solved! :smile: 

This error is shows when the VM specified is not found by Virtualbox. This usually occurs when Cuckoo is started with `sudo`, as this starts Cuckoo as the `root` user and search on that user for your VM.

How do you start Cuckoo?

**Comment by jakilla** [comment]
![image](https://user-images.githubusercontent.com/40600995/41962403-368724ce-79f5-11e8-90b1-8c30a5b44d9a.png)

I was able to solve the problem by not passing through the root as you indicated it to me, however I still have errors in the analysis (it goes forward 😄 )

**Comment by doomedraven** [comment]
If you read the output you have links to solutions

**Comment by jakilla** [comment]
> If you read the output you have links to solutions

I followed the link for the communication problem with my vm, nothing clearly explained my case, however I think I found the source of the problem, the python agent python.py should not be done correctly because the  cmd windows does not move (see screen)

moreover it does not tell me where it stops at the level of the script, do you know or could I see it ?



![image](https://user-images.githubusercontent.com/40600995/41977089-d6069b78-7a1e-11e8-8104-827c94e10623.png)

**Comment by doomedraven** [comment]
Do search in issues it was answered a lot of times :)
