### ISSUE TITLE
Analysis not functioning properly

### ISSUE THREAD

**Issue by quantm1366** [cuckoosandbox/cuckoo#2349]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are:  
My Cuckoo version and operating system are: 
Cuckoo Sandbox 2.0.6 DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

##### The log, error, files etc can be found at:

WARNING: Windows7-64: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpmcakix/analyzer.py", line 800, in <module>
    success = analyzer.run()
  File "C:/tmpmcakix/analyzer.py", line 652, in run
    pids = self.package.start(self.target)
  File "C:\tmpmcakix\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmpmcakix\lib\common\abstracts.py", line 166, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

**Comment by quantm1366** [comment]
I found the below link scouring past issues. Should really think about adding the fact that the guest username needs to be "Administrator" once I activated that account, moved the agent.py to administrators startup folder, took a new snapshot and deleted the previous account everything worked like a dream

so my suggestion is either add that to the "Preparing the Guest" documentation or create a variable for guest user name in the $virtual_software.conf

https://github.com/cuckoosandbox/cuckoo/issues/2177

Thanks for making the old issues easily searchable though!

**Comment by fahronona** [comment]
i have same issue but i can not understand how fix it , i try follow your step but i still upset
