### ISSUE TITLE
How to Improve script file  Identification

### ISSUE THREAD

**Issue by cssxn** [cuckoosandbox/cuckoo#2351]
I have a lot of Samples which are named with `MD5 ` that without any extension. mostly these are malicious script files，etc.. ps1、js，vbs.

Cuckoo can not identify that，and will rise an error message：

```
2018-07-02 21:19:21,643 [cuckoo.core.guest] WARNING: vm002: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmp_bebkw/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmp_bebkw/analyzer.py", line 580, in run
    "not exist.".format(package_name))
CuckooError: Unable to import package "modules.packages.None", does not exist.

```

**Comment by doomedraven** [comment]
for start for example, sharing the hashes?

**Comment by cssxn** [comment]
@doomedraven 

no hashes, you cloud create a malicious PowerShell file without extension. throw it into cuckoo and see what happen

**Comment by doomedraven** [comment]
You can write extension for sflock to identify it and ser correct package

**Comment by cssxn** [comment]
@doomedraven 
I have thousands of thousands malware named with MD5，so I can‘t do this manually！

**Comment by doomedraven** [comment]
ifyou can't than wait for someone to do your work :P

**Comment by cssxn** [comment]
heheda
