### ISSUE TITLE
Unable to stop auxiliary module: Sniffer

### ISSUE THREAD

**Issue by cssxn** [cuckoosandbox/cuckoo#2399]
```
2018-07-27 01:21:26,682 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 163, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 156, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: vboxnet0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: No such device\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?

```

Then I've got this

```
ubuntu@ubuntu:~$ sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
ubuntu@ubuntu:~$ sudo aa-disable  /usr/sbin/tcpdump
Disabling /usr/sbin/tcpdump.

ERROR: /sbin/apparmor_parser: Unable to remove "/usr/sbin/tcpdump".  Profile doesn't exist

```

**Comment by doomedraven** [comment]
see PRs about fix it

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/pull/2132

**Comment by cssxn** [comment]
@doomedraven 

```
ubuntu@ubuntu:~$ sudo groupadd pcap
ubuntu@ubuntu:~$  sudo usermod -a -G pcap cuckoo
ubuntu@ubuntu:~$ sudo chgrp pcap /usr/sbin/tcpdump
ubuntu@ubuntu:~$ sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
ubuntu@ubuntu:~$ getcap /usr/sbin/tcpdump
/usr/sbin/tcpdump = cap_net_admin,cap_net_raw+eip
ubuntu@ubuntu:~$ sudo aa-disable  /usr/sbin/tcpdump 
Disabling /usr/sbin/tcpdump.

ERROR: /sbin/apparmor_parser: Unable to remove "/usr/sbin/tcpdump".  Profile doesn't exist

ubuntu@ubuntu:~$ 


```

**Comment by doomedraven** [comment]
that isn't an error, thats fine, apparmor not always has a profile for tcpdump, the most important if that works with cuckoo

**Comment by cssxn** [comment]
@doomedraven 

is not working. same error occurs

**Comment by doomedraven** [comment]
ah wait i not even checked error
```
ff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: vboxnet0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl faile
```

what about `ifconfig` log? as it says vboxnet0 doesn't exist

**Comment by cssxn** [comment]
@doomedraven 
```
ubuntu@ubuntu:~$ ifconfig 
ens33     Link encap:Ethernet  HWaddr 00:0c:29:a8:7e:63  
          inet addr:192.168.89.156  Bcast:192.168.89.255  Mask:255.255.255.0
          inet6 addr: fe80::c075:4a15:c693:b2af/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:116601 errors:0 dropped:0 overruns:0 frame:0
          TX packets:73092 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:125431299 (125.4 MB)  TX bytes:13985469 (13.9 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:10378 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10378 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4653671 (4.6 MB)  TX bytes:4653671 (4.6 MB)

```

**Comment by doomedraven** [comment]
there is your problem, now read your error(BOLD), CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = __'tcpdump: vboxnet0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: No such device\n'.__ Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?

**Comment by cssxn** [comment]
I've done everything of that URL says. doesn't help。

**Comment by doomedraven** [comment]
you didn't read/understand your error, vboxnet0 is the virtual box network interface, and it's not listed in your `ifconfig`

you can't sniff on non existing interface

google, `why vboxnet0 not started` or `how to start vboxnet0` etc

**Comment by RicoVZ** [comment]
Hi cssxn,

As the error says, the device cannot be found. The device being the network interface `vboxnet0` in this case.

Does it appear when you run `vboxmanage list hostonlyifs`?

If so, you can bring it up using ` ip link set vboxnet0 up`.

If it does not appear in that list, use the following commands to create it:
`vboxmanage hostonlyif create`
`vboxmanage hostonlyif ipconfig vboxnet0 --ip 192.168.56.1` (or another IP if you have a different subnet for your VMs)

**Comment by manzy90** [comment]
Hi Cuckoo Support team

I am receiving a similar error, i did check and vboxnet0 is up. I also looked at the link for FAQ for TCP as well.

This is from the cuckoo box terminal
2018-10-08 19:53:04,997 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2018-10-08 19:53:05,743 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2018-10-08 19:53:05,752 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2018-10-08 19:53:28,489 [cuckoo.core.scheduler] INFO: Starting analysis of URL "https://poloniex.com.cropac.club" (task #4, options "procmemdump=yes,route=none")
2018-10-08 19:53:28,588 [cuckoo.core.scheduler] INFO: Task #4: acquired machine windowsxp (label=windowsxp)
2018-10-08 19:53:28,593 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7016 (interface=vboxnet0, host=192.168.56.10)
2018-10-08 19:53:32,598 [cuckoo.core.guest] INFO: Starting analysis on guest (id=windowsxp, ip=192.168.56.10)
2018-10-08 19:53:35,637 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=windowsxp, ip=192.168.56.10)
2018-10-08 19:53:37,873 [cuckoo.core.guest] WARNING: windowsxp: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpf5nkiv/analyzer.py", line 800, in <module>
    success = analyzer.run()
  File "C:/tmpf5nkiv/analyzer.py", line 652, in run
    pids = self.package.start(self.target)
  File "C:\tmpf5nkiv\modules\packages\ie.py", line 127, in start
    iexplore, args=[target], maximize=True, mode="iexplore"
  File "C:\tmpf5nkiv\lib\common\abstracts.py", line 159, in execute
    self.init_regkeys(self.REGKEYS)
  File "C:\tmpf5nkiv\lib\common\abstracts.py", line 121, in init_regkeys
    SetValueEx(key_handle, key, 0, REG_DWORD, value)
WindowsError: [Error 5] Access is denied

2018-10-08 19:53:37,970 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 163, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 156, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'dropped privs to root\ntcpdump: /home/cuckoo/.cuckoo/storage/analyses/4/dump.pcap: Permission denied\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
2018-10-08 19:53:40,334 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2018-10-08 19:53:40,341 [cuckoo.processing.network] WARNING: The PCAP file does not exist at path "/home/cuckoo/.cuckoo/storage/analyses/4/dump.pcap".
2018-10-08 19:53:40,350 [cuckoo.core.scheduler] INFO: Task #4: reports generation completed
2018-10-08 19:53:40,358 [cuckoo.core.scheduler] INFO: Task #4: analysis procedure completed

**Comment by icedxu** [comment]
I  get these  "icedxu@icedxu:~$ sudo aa-disable  /usr/sbin/tcpdump

ERROR: Syntax Error: Unknown line found in file /etc/apparmor.d/usr.lib.snapd.snap-confine.real line 100:
    change_profile unsafe /** -> [^u/]**,
"

**Comment by SparkyNZL** [comment]
have you checked your permissions on TCPDUMP.?

**Comment by Ma780aPar** [comment]
> you didn't read/understand your error, vboxnet0 is the virtual box network interface, and it's not listed in your `ifconfig`
> 
> you can't sniff on non existing interface
> 
> google, `why vboxnet0 not started` or `how to start vboxnet0` etc

Look at virtualbox.conf configuration:

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
interface = PUT interface name HERE which you are using for capturing

**Comment by SparkyNZL** [comment]
Hi

if your vobxnet0 interface is not listed but it is in virtualbox, then
type the following

1: ifconfig (check to see if its listed if not do the following)
2: vboxmanage list vms
3: ifconfig (is it listed now ? (if not you need to ensure that you
have added it to your interfaces file)


if it is listed you are all set to go :)

Cheers

**Comment by sagarbade** [comment]
hey check this my ip config works fine but it shows **Unable to stop auxiliary module: Sniffer**

**cuckoo@max-cuckoo:/opt/cuckoo$ ifconfig
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.27  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::d783:ac22:2784:8311  prefixlen 64  scopeid 0x20<link>
        ether 2c:27:d7:3d:fc:6a  txqueuelen 1000  (Ethernet)
        RX packets 381583  bytes 459275345 (459.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 195556  bytes 15477704 (15.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xfe400000-fe420000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1074612  bytes 172058771 (172.0 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1074612  bytes 172058771 (172.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vboxnet0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.56.1  netmask 255.255.255.0  broadcast 192.168.56.255
        inet6 fe80::800:27ff:fe00:0  prefixlen 64  scopeid 0x20<link>
        ether 0a:00:27:00:00:00  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1296  bytes 171957 (171.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0**

Cuckoo analysis log is follows:

2019-09-23 10:31:06,205 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Replay
2019-09-23 10:31:06,205 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 164, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/sniffer.py", line 156, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = "tcpdump: vboxnet0: You don't have permission to capture on that device\n(socket: Operation not permitted)\n". Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
2019-09-23 10:31:06,356 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo1
2019-09-23 10:31:07,771 [cuckoo.core.resultserver] DEBUG: Stopped tracking machine 192.168.56.101 for task #10
2019-09-23 10:31:07,899 [cuckoo.core.scheduler] DEBUG: Released database task #10
2019-09-23 10:31:08,059 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #10
2019-09-23 10:31:08,487 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #10
2019-09-23 10:31:08,488 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #10
2019-09-23 10:31:08,488 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #10
2019-09-23 10:31:08,712 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #10
2019-09-23 10:31:08,826 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #10
2019-09-23 10:31:08,826 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #10
2019-09-23 10:31:08,827 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #10
2019-09-23 10:31:09,198 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #10
2019-09-23 10:31:09,216 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #10
2019-09-23 10:31:09,218 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #10
2019-09-23 10:31:09,218 [cuckoo.processing.network] WARNING: The PCAP file does not exist at path "/opt/cuckoo/storage/analyses/10/dump.pcap".
2019-09-23 10:31:09,218 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #10
2019-09-23 10:31:09,219 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #10
2019-09-23 10:31:09,219 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #10
2019-09-23 10:31:09,222 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #10
2019-09-23 10:31:09,222 [cuckoo.core.plugins] DEBUG: Running 0 signatures
2019-09-23 10:31:09,325 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2019-09-23 10:31:09,952 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2019-09-23 10:31:09,952 [cuckoo.core.scheduler] INFO: Task #10: reports generation completed
2019-09-23 10:31:09,958 [cuckoo.core.scheduler] INFO: Task #10: analysis procedure completed

**Comment by sagarbade** [comment]
i use latest version of cuckoo

**Comment by sagarbade** [comment]
ERROR:
It appears that the environment of your Virtual Machine is partially unknown to us in the sense that we haven't added special support for it yet (for 95% of the time the analysis will work perfectly fine, though). By doing a special, fully automated, analysis you can automatically obtain the environment-specific Windows DLLs and other goodies that the Cuckoo Sandbox Core Developer team can use to add support for your version of Windows. In order to share this data back to us, please click on .
