### ISSUE TITLE
Failed to run the reporting module: Moloch

### ISSUE THREAD

**Issue by 1623664** [cuckoosandbox/cuckoo#2420]
Hi!

My issue is:
ERROR: Failed to run the reporting module: Moloch
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 623, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/moloch.py", line 67, in run
    "Error submitting PCAP to Moloch: %s" % e)
CuckooProcessingError: Error submitting PCAP to Moloch: Command '['/data/moloch/bin/moloch-capture', '-c', '/data/moloch/etc/config.ini', '-r', '/home/cuckoo/.cuckoo/storage/analyses/7/dump.pcap', '-n', 'cuckoo', '-q', '-t', 'sha256:b37f982a04bba345845fdb588c88a1857c820933430219ad5bdb1b4dcfb1554a', '-t', 'sha1:80eb83d244921bb2f06098a3bf2fc42252f628e5', '-t', 'sha512:1fcede0d49a8b51a504e31435de154aa13140ec34f917e75e57ccd2dedc05a2f887a91cd748c305eb90d1b32c7352497abd82c853c77259e64a0418b819a941b', '-t', 'cuckoo:7', '-t', 'md5:6d1e9105e8ccd3a6504f06c9c5c5e3aa']' returned non-zero exit status 1

The command is successfully executed in the terminal

**Comment by RicoVZ** [comment]
Hi 16236641,

Thanks for posting an issue.

Can you tell us if this happens for all analyses? :smile: 

> The command is successfully executed in the terminal
Have you executed the exact command that Cuckoo does (with the same pcap)?

**Comment by 1623664** [comment]
Yes it happens for all analyzes. I executed the command:

/data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -r /home/cuckoo/.cuckoo/storage/analyses/7/dump.pcap -n cuckoo -q -t sha256:b37f982a04bba345845fdb588c88a1857c820933430219ad5bdb1b4dcfb1554a -t sha1:80eb83d244921bb2f06098a3bf2fc42252f628e5 -t sha512:1fcede0d49a8b51a504e31435de154aa13140ec34f917e75e57ccd2dedc05a2f887a91cd748c305eb90d1b32c7352497abd82c853c77259e64a0418b819a941b -t cuckoo:7 -t 
 md5:6d1e9105e8ccd3a6504f06c9c5c5e3aa

the command was executed successfully.


This is repeated in each report

**Comment by JReming85** [comment]
This also happens for me.

Few weird things, even though cuckoo reports it as failed, it is still added when I look at the web viewer.

It also adds successfully when done manually with 2 warnings

<code>
Sep 18 11:05:00 field.c:249 moloch_field_define(): WARNING - Field kind in db date doesn't match field kind seconds in capture for field cert.notbefore
Sep 18 11:05:00 field.c:249 moloch_field_define(): WARNING - Field kind in db date doesn't match field kind seconds in capture for field cert.notafter
</code>

**Comment by JReming85** [comment]
@1623664 

I just resolved my own issue, which might be the same for you.

somehow nobody:daemon lost access to /data/moloch/bin & /data/moloch/raw

Both of them somehow got restricted to root, and once you call moloch-capture, it cant go and access files after the dump.

Fix the permissions and you should be all set

**Comment by dkni0** [comment]
@JReming85 

Hi,I have the same problem

``
ERROR: Failed to run the reporting module: Moloch
``

permissions list
  
 ``
drwxr-xr-x   2 root   root   4096 12月 14 17:20 bin
drwx------   2 nobody root  12288 12月 19 12:32 raw
 ``

How should I fix permissions？thank you

**Comment by eoinmiller-r7** [comment]
Stumbled on this as well, looks like the default `pcapDir` value in Moloch's `config.ini` (`/data/moloch/raw`) is set to 700:

```drwx------   2 nobody root 4.0K Mar 23 06:51 raw/```

```$ ls -laFh /data/moloch/raw/
ls: cannot open directory '/data/moloch/raw/': Permission denied```

If you just set it to 755 you will be good to go.
```sudo chmod 755 /data/moloch/raw/```
