### ISSUE TITLE
Submit Error

### ISSUE THREAD

**Issue by laputa1312** [cuckoosandbox/cuckoo#2433]
when I submit the file and show error with  "Something went wrong!
The server returned an error. Please check our file compatibility list with the file you're trying to upload or try again.
If the problem persists, send us a feedback report."

here is the following log from web.

May I know anything I missed or mess up something. 
I follow the instruction from the website.

2018-08-07 17:28:52,457 [django.request] ERROR: Internal Server Error: /submit/api/presubmit
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/submission/api.py", line 64, in presubmit
    submit_id = submit_manager.pre(submit_type="files", data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/submit.py", line 123, in pre
    path_tmp = Folders.create_temp()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/files.py", line 72, in create_temp
    return tempfile.mkdtemp(dir=path or temppath())
  File "/usr/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/tmp/cuckoo-tmp-root/tmpxxJKeF'

thanks for the reply and advise.

**Comment by doomedraven** [comment]
read error, don't execute cuckoo as root, and see folder doesn't exit, create it

**Comment by doomedraven** [comment]
If you run cuckoo as root expect problems like this, read the documentation!
