### ISSUE TITLE
Baseline fails

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2437]
##### My issue is:
Baseline fails with the below, normal submissions work just fine.
~~~
2018-08-11 20:44:29,009 [cuckoo.processing.debug] ERROR: Error processing task #1: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2018-08-11 20:44:29,123 [cuckoo.core.plugins] ERROR: Failed to run 'on_complete' of the rtf_unknown_character_set signature
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo2-venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 414, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "/home/cuckoo/.cuckoo/signatures/windows/office_rtf.py", line 55, in on_complete
    filetype = self.get_results("target", {})["file"]["type"]
KeyError: 'file'
2018-08-11 20:44:29,128 [cuckoo.core.plugins] ERROR: Failed to run 'on_complete' of the rtf_unknown_version signature
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo2-venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 414, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "/home/cuckoo/.cuckoo/signatures/windows/office_rtf.py", line 27, in on_complete
    filetype = self.get_results("target", {})["file"]["type"]
KeyError: 'file'
2018-08-11 20:44:29,140 [cuckoo.core.plugins] ERROR: Failed to run 'on_complete' of the url_file signature
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo2-venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 414, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "/home/cuckoo/.cuckoo/signatures/windows/url_file.py", line 21, in on_complete
    if "Internet shortcut" not in self.file.get("type", ""):
AttributeError: 'URLFile' object has no attribute 'file'
2018-08-11 20:44:31,280 [cuckoo.core.scheduler] INFO: Task #1: reports generation completed
2018-08-11 20:44:31,300 [cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed
~~~
##### My Cuckoo version and operating system are:
Latest cuckoo, Debian Stretch

##### This can be reproduced by:
cuckoo submit --baseline

**Comment by DigiAngel** [comment]
Thank you..I did the force for community, but here are the results:
~~~
018-08-12 07:49:51,281 [cuckoo.processing.debug] ERROR: Error processing task #1: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
~~~
Analyzer.log is empty, also behavior is blank...is this considered normal?  Thanks again.
![screenshot from 2018-08-12 07-51-52](https://user-images.githubusercontent.com/947191/44002728-daa53c3e-9e04-11e8-9f83-1ff573079bf3.png)
![Uploading Screenshot from 2018-08-12 07-35-00.png…]()

**Comment by RicoVZ** [comment]
@DigiAngel 
For a baseline task, yes. :smile:  Nothing is placed inside the analysis machine during this task, so no processes etc are tracked.

**Comment by DigiAngel** [comment]
Heh....I guess that makes sense....ok cool thank you :)
