### ISSUE TITLE
UnicodeEncodeError in logging module

### ISSUE THREAD

**Issue by mygodwzy** [cuckoosandbox/cuckoo#2442]
I'm receiving the following error when outputing file name of analyzed target into log pipe via the logging module API:
`2018-08-20 11:26:26,089 [cuckoo.core.guest] WARNING: cuckoo1: analysis caught an exception   
Traceback (most recent call last):   
  File "C:/tmps3abwr/analyzer.py", line 952, in <module>   
    success = analyzer.run()   
  File "C:/tmps3abwr/analyzer.py", line 781, in run   
    pids = self.package.start(self.target)   
  File "C:\tmps3abwr\modules\packages\zip.py", line 96, in start   
    log.debug("Missing file option, auto executing: {0}".format(file_name))   
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-13: ordinal not in range(128)   `
My code is:
`log.debug("Missing file option, auto executing: {0}".format(file_name))`

**Comment by doomedraven** [comment]
what is your file_name in this case?

**Comment by mygodwzy** [comment]
file name：计时计费管理系统V16.exe

**Comment by doomedraven** [comment]
goodle unicode decodes/encodes, but you will get a lot of problem with different unicodes later

**Comment by RicoVZ** [comment]
Hi mygodwzy,

Thanks for posting an issue. :smile: 

> Is there any other solution?

Not really, at the moment. I will be sure to add this to our "fix list".
