### ISSUE TITLE
UnicodeEncodeError when submit a file

### ISSUE THREAD

**Issue by qux-bbb** [cuckoosandbox/cuckoo#2473]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
when I submit a file which name contains chinese charactors, "UnicodeEncodeError" is found.  
##### My Cuckoo version and operating system are:
Cuckoo version: 2.0.6  
operating system: ubuntu  
##### This can be reproduced by:
Submit a file which name contains chinese charactors.  
##### The log, error, files etc can be found at:
```
/home/cuckoo/venv-develop/bin/python /home/cuckoo/cuckoo/cuckoo/main.py submit /home/cuckoo/tmp/早上
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/cuckoo/main.py", line 752, in <module>
    main()
  File "/home/cuckoo/venv-develop/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/cuckoo/venv-develop/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/cuckoo/venv-develop/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cuckoo/venv-develop/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cuckoo/venv-develop/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cuckoo/venv-develop/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cuckoo/cuckoo/cuckoo/main.py", line 324, in submit
    for category, target, task_id in l:
  File "/home/cuckoo/cuckoo/cuckoo/apps/apps.py", line 198, in submit_tasks
    task_id = db.add_path(file_path=filepath, **data)
  File "/home/cuckoo/cuckoo/cuckoo/core/database.py", line 1150, in add_path
    enforce_timeout, clock, "file", submit_id)
  File "/home/cuckoo/cuckoo/cuckoo/common/utils.py", line 196, in inner
    return f(self, *args, **kwargs)
  File "/home/cuckoo/cuckoo/cuckoo/core/database.py", line 1108, in add
    session.commit()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 790, in commit
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 392, in commit
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 372, in _prepare_impl
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2004, in flush
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2122, in _flush
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2086, in _flush
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 373, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 532, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 174, in save_obj
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 781, in _emit_insert_statements
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 914, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1344, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 450, in do_execute
  File "/home/cuckoo/venv-develop/lib/python2.7/site-packages/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
  File "/home/cuckoo/venv-develop/lib/python2.7/site-packages/MySQLdb/connections.py", line 278, in literal
    return self.escape(o, self.encoders)
  File "/home/cuckoo/venv-develop/lib/python2.7/site-packages/MySQLdb/connections.py", line 208, in unicode_literal
    return db.literal(u.encode(unicode_literal.charset))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 17-18: ordinal not in range(256)

Process finished with exit code 1
```

**Comment by doomedraven** [comment]
what chars do you use in your db connection is cuckoo.conf?

**Comment by qux-bbb** [comment]
at first I do not specify the charset, and I found UnicodeEncodeError.  
when I specify utf8 as my charset, the output is:  
```
/home/cuckoo/venv-develop/bin/python /home/cuckoo/cuckoo/cuckoo/main.py submit /home/cuckoo/tmp/早上
Skipped: File "/home/cuckoo/tmp/早上" as it has already been analyzed
```
I had search it in code, and found the task_id is None in /cuckoo/cuckoo/core/database.py line 1109.

**Comment by qux-bbb** [comment]
the filename is 早上.

**Comment by qux-bbb** [comment]
Well, I solved the problem partially. In commandline, I can submit a file which name contains chinese charactors, but it can not run well in web page.    
I'm using mysql database. When you create or connect a database, you should specify the character encoding.Like this:  
```
# create database and grant to cuckoo
CREATE DATABASE IF NOT EXISTS cuckoo default charset utf8 COLLATE utf8_general_ci;
GRANT all ON cuckoo.* TO 'cuckoo'@'localhost' identified by 'goodmorning';

# configure database connection
connection = mysql://cuckoo:goodmorning@localhost/cuckoo?charset=utf8
```
Then you can submit a file which name contains chinese charactors by commandline.    

The problem of web page is a little hard. I'm trying to fix it. The problem like this:  
```
Something went wrong!
The server returned an error. Please check our file compatibility list with the file you're trying to upload or try again.
If the problem persists, send us a feedback report.
```

**Comment by qux-bbb** [comment]
About the problem of web page, I found that is caused by my nginx proxy.  
If I use cuckoo web directly and visit webpage by cuckoo web port, there will be no such problem.  
Thanks for your help.
