### ISSUE TITLE
500 error. MISP Package.

### ISSUE THREAD

**Issue by hutism** [cuckoosandbox/cuckoo#2499]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:
2018-09-28 10:51:55,920 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MISP
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 623, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/misp.py", line 115, in run
    self.sample_hashes(results, event)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/misp.py", line 28, in sample_hashes
    comment="File submitted to Cuckoo",
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 399, in add_hashes
    return self._send_attributes(event, attributes, proposal)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 369, in _send_attributes
    response = self.update_event(event['Event']['id'], json.dumps(e, cls=EncodeUpdate))
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 277, in update_event
    return self._check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 175, in _check_response
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 908, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.2.10/events/35
Sep 28 10:51:55 main.c:609 main(): THREAD 0x7fa0d608f780
2018-09-28 10:51:57,165 [cuckoo.apps.apps] INFO: Task #35: reports generation completed

**Comment by hutism** [comment]
> Did you search in issues im pretty sure that is pymisp problem

Thanks. I searched for the cause, but couldn't find it. I reinstalled pymisp. 
"pip install pymisp", and
"pip3 install pymisp".

**Comment by doomedraven** [comment]
what about ? https://github.com/cuckoosandbox/cuckoo/issues/2470
