### ISSUE TITLE
Web Interface Apache / cuckoo web runsever

### ISSUE THREAD

**Issue by itsecforu** [cuckoosandbox/cuckoo#2507]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Hello everyone!
When I started `cuckoo -d ` -it seems as it starts normally. (screenshot 1.png)
![1](https://user-images.githubusercontent.com/38696837/46334869-57490a80-c62e-11e8-8ed5-96def72c20b4.png)
1. First I tried to set up Apache2 for web-interfaces.
My **wsgi.py:**
```
import os, sys
sys.path.append('/opt/cuckoo')
sys.path.append('/opt/cuckoo/web/web/')
os.chdir('/opt/cuckoo/web/web/')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "web.settings")

    # This application object is used by any WSGI server configured to use
    # this file. This includes Django's development server, if the
    # WSGI_APPLICATION setting points here.
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
```
My **/etc/apache2/sites-enable/cuckoo.conf:**
```
<Location />
Require all granted
</Location>
<VirtualHost *:88>
    LogLevel debug
    ServerName cuckoo.local
    ServerAdmin admin
    DocumentRoot /opt/cuckoo/web
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
#   WSGIScriptAlias / /opt/cuckoo/web/web/wsgi.py
   WSGIScriptAlias / /usr/local/lib/python2.7/dist-packages/cuckoo/web/web/wsgi.py
<Directory /usr/local/lib/pytho2.7/dist-packeges/cuckoo/web/web/ >
	<Files wsgi.py>
	</Files>
#	Require all granted
    </Directory>
    Alias /static /opt/cuckoo/web/static
    <Directory /opt/cuckoo/web/static/>
#	Require all granted
    </Directory>
</VirtualHost>
```
Then i get **Internal Server Error**
![7](https://user-images.githubusercontent.com/38696837/46335189-58c70280-c62f-11e8-826a-3d14f1911133.png)
File /etc/apache2/envvars:
```
# envvars - default environment variables for apache2ctl

# this won't be correct after changing uid
unset HOME

# for supporting multiple apache2 instances
if [ "${APACHE_CONFDIR##/etc/apache2-}" != "${APACHE_CONFDIR}" ] ; then
	SUFFIX="-${APACHE_CONFDIR##/etc/apache2-}"
else
	SUFFIX=
fi

# Since there is no sane way to get the parsed apache2 config in scripts, some
# settings are defined via environment variables and then used in apache2ctl,
# /etc/init.d/apache2, /etc/logrotate.d/apache2, etc.
export APACHE_RUN_USER=user
export APACHE_RUN_GROUP=user
# temporary state file location. This might be changed to /run in Wheezy+1
export APACHE_PID_FILE=/var/run/apache2/apache2$SUFFIX.pid
export APACHE_RUN_DIR=/var/run/apache2$SUFFIX
export APACHE_LOCK_DIR=/var/lock/apache2$SUFFIX
# Only /var/log/apache2 is handled by /etc/logrotate.d/apache2.
export APACHE_LOG_DIR=/var/log/apache2$SUFFIX

## The locale used by some modules like mod_dav
export LANG=C
## Uncomment the following line to use the system default locale instead:
#. /etc/default/locale

export LANG

## The command to get the status for 'apache2ctl status'.
## Some packages providing 'www-browser' need '--dump' instead of '-dump'.
#export APACHE_LYNX='www-browser -dump'

## If you need a higher file descriptor limit, uncomment and adjust the
## following line (default is 8192):
#APACHE_ULIMIT_MAX_FILES='ulimit -n 65536'

## If you would like to pass arguments to the web server, add them below
## to the APACHE_ARGUMENTS environment.
#export APACHE_ARGUMENTS=''

## Enable the debug mode for maintainer scripts.
## This will produce a verbose output on package installations of web server modules and web application
## installations which interact with Apache
#export APACHE2_MAINTSCRIPT_DEBUG=1
```

Part of Apache error logs:

```
[Tue Oct 02 10:06:48.930893 2018] [wsgi:warn] [pid 17879:tid 139647401326464] mod_wsgi: Compiled for Python/2.7.11.
[Tue Oct 02 10:06:48.930976 2018] [wsgi:warn] [pid 17879:tid 139647401326464] mod_wsgi: Runtime using Python/2.7.12.
[Tue Oct 02 10:06:48.931600 2018] [mpm_event:notice] [pid 17879:tid 139647401326464] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Oct 02 10:06:48.931617 2018] [core:notice] [pid 17879:tid 139647401326464] AH00094: Command line: '/usr/sbin/apache2'
[Tue Oct 02 10:07:23.384814 2018] [authz_core:debug] [pid 17883:tid 139647237748480] mod_authz_core.c(809): [client 127.0.0.1:56772] AH01626: authorization result of Require all granted: granted
[Tue Oct 02 10:07:23.384863 2018] [authz_core:debug] [pid 17883:tid 139647237748480] mod_authz_core.c(809): [client 127.0.0.1:56772] AH01626: authorization result of <RequireAny>: granted
[Tue Oct 02 10:07:23.384925 2018] [authz_core:debug] [pid 17883:tid 139647237748480] mod_authz_core.c(809): [client 127.0.0.1:56772] AH01626: authorization result of Require all granted: granted
[Tue Oct 02 10:07:23.384933 2018] [authz_core:debug] [pid 17883:tid 139647237748480] mod_authz_core.c(809): [client 127.0.0.1:56772] AH01626: authorization result of <RequireAny>: granted
[Tue Oct 02 10:07:23.394198 2018] [wsgi:info] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772] mod_wsgi (pid=17883, process='', application='cuckoo.local:88|'): Loading WSGI script '/usr/local/lib/python2.7/dist-packages/cuckoo/web/web/wsgi.py'.
[Tue Oct 02 10:07:23.734324 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772] mod_wsgi (pid=17883): Target WSGI script '/usr/local/lib/python2.7/dist-packages/cuckoo/web/web/wsgi.py' cannot be loaded as Python module.
[Tue Oct 02 10:07:23.734349 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772] mod_wsgi (pid=17883): Exception occurred processing WSGI script '/usr/local/lib/python2.7/dist-packages/cuckoo/web/web/wsgi.py'.
[Tue Oct 02 10:07:23.734368 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772] Traceback (most recent call last):
[Tue Oct 02 10:07:23.734385 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]   File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/web/wsgi.py", line 32, in <module>
[Tue Oct 02 10:07:23.734438 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]     application = get_wsgi_application()
[Tue Oct 02 10:07:23.734449 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]   File "/home/user/.local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Tue Oct 02 10:07:23.734515 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]     django.setup()
[Tue Oct 02 10:07:23.734527 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]   File "/home/user/.local/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
[Tue Oct 02 10:07:23.734556 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Tue Oct 02 10:07:23.734565 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]   File "/home/user/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
[Tue Oct 02 10:07:23.734617 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]     self._setup(name)
[Tue Oct 02 10:07:23.734628 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]   File "/home/user/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
[Tue Oct 02 10:07:23.734643 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]     self._wrapped = Settings(settings_module)
[Tue Oct 02 10:07:23.734651 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]   File "/home/user/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
[Tue Oct 02 10:07:23.734674 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Tue Oct 02 10:07:23.734684 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Tue Oct 02 10:07:23.734716 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772]     __import__(name)
[Tue Oct 02 10:07:23.734734 2018] [wsgi:error] [pid 17883:tid 139647237748480] [client 127.0.0.1:56772] ImportError: No module named settings
[Tue Oct 02 10:07:34.380612 2018] [mpm_event:notice] [pid 17879:tid 139647401326464] AH00491: caught SIGTERM, shutting down

```
2nd Issue.
I tried to start web-interface to run:
`cuckoo web -H 127.0.0.1 -p 8000
`
I get the other errors on my terminal and web browser:
![5](https://user-images.githubusercontent.com/38696837/46335437-1d790380-c630-11e8-8b81-13006057a32e.png)
![2](https://user-images.githubusercontent.com/38696837/46335452-31bd0080-c630-11e8-977a-480955e8c239.png)

##### My Cuckoo version and operating system are:
Ubuntu 16.04 | cuckoo sandbox 2.0.6. | Apache 2.4.18
##### This can be reproduced by:

Intel Core i5-3330 CPU 3.00GHx

##### The log, error, files etc can be found at:
I pit this below case by case

**Comment by itsecforu** [comment]
I tried to make nginx as web server 
Now I get 502 error :-1: 

access log:

`127.0.0.1 - user [02/Oct/2018:16:10:39 +0300] "GET / HTTP/1.1" 502 182 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
`
error log: 

```
2018/10/02 16:09:58 [warn] 22655#22655: conflicting server name "" on 127.0.0.1:80, ignored
2018/10/02 16:09:58 [warn] 22657#22657: conflicting server name "" on 127.0.0.1:80, ignored
2018/10/02 16:10:39 [error] 22660#22660: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "127.0.0.1"
```

site-enabled/cuckoo:
```

server {
    listen 10.23.110.160:443 ssl http2;
    ssl_certificate /etc/nginx/ssl/cuckoo.crt;
    ssl_certificate_key /etc/nginx/ssl/cuckoo.key;
    ssl_dhparam /etc/nginx/ssl/dhparam.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off; # Requires nginx >= 1.5.9
    # Uncomment this next line if you are using a signed, trusted cert
    #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    root /usr/share/nginx/html;
    index index.html index.htm;
    client_max_body_size 101M;
    auth_basic "Login required";
    auth_basic_user_file /etc/nginx/htpasswd;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /storage/analysis {
       alias /opt/cuckoo/storage/analyses/;
       autoindex on;
       autoindex_exact_size off;
       autoindex_localtime on;
    }

    location /static {
      alias /opt/cuckoo/web/static/;
    }
}

server {
    listen 10.23.110.160:80;
    return 301 https://$server_name$request_uri;
}


server {
  listen 127.0.0.1:8080;

    root /home/cuckoo/vmshared;

     location / {
           try_files $uri $uri/ =404;
           autoindex on;
           autoindex_exact_size off;
           autoindex_localtime on;
     }
}

# Host the upstream legacy API 
server {
    listen 10.23.110.160:4343 ssl http2;
    ssl_certificate /etc/nginx/ssl/cuckoo.crt;
    ssl_certificate_key /etc/nginx/ssl/cuckoo.key;
    ssl_dhparam /etc/nginx/ssl/dhparam.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off; # Requires nginx >= 1.5.9
   # Uncomment this next line if you are using a signed, trusted cert
    #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    root /usr/share/nginx/html;
    index index.html index.htm;
    client_max_body_size 101M;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Restrict access
       allow 10.23.110.160;
      #allow 192.168.1.0/24;
      deny all;
    }
}

```
Link :

**https://infosecspeakeasy.org/t/howto-build-a-cuckoo-sandbox/27**

Dunno what did I wrong.
Plz help me guys

**Comment by doomedraven** [comment]
first of all you blowed the nginx conf, that link is for cuckoo-mod, use `cuckoo -h` to see how to generate confs, first make it works iwth http and then with https, + you can see a lto of issues like this in issues so i would suggest to go there first to read them and maybe that save you time

**Comment by itsecforu** [comment]
> first of all you blowed the nginx conf, that link is for cuckoo-mod, use `cuckoo -h` to see how to generate confs, first make it works iwth http and then with https, + you can see a lto of issues like this in issues so i would suggest to go there first to read them and maybe that save you time

Do you mean cuckoo-mod is another product?

**Comment by doomedraven** [comment]
yes

**Comment by doomedraven** [comment]
see link `https://github.com/spender-sandbox/cuckoo-modified.git` != `https://github.com/cuckoosandbox/cuckoo.git`

**Comment by itsecforu** [comment]
```
cuckoo -h
Error: no such options -h
```
Is it normal?
> k `https://github.com/spender-sandbox/cuckoo-modified.git` != `https://github.com/cuckoosandbox/cuckoo.git`

I got it, thx u

**Comment by doomedraven** [comment]
try --help

**Comment by itsecforu** [comment]
> try --help

This flag didnt print information about configs.
There are options about run and management users

**Comment by doomedraven** [comment]
there are options as nginx/uwsgi which generetes configs for you

**Comment by itsecforu** [comment]
![1](https://user-images.githubusercontent.com/38696837/46356806-2a1b4d00-c66c-11e8-84c7-32de46559ac7.png)
Hmm, I feel blind

**Comment by doomedraven** [comment]
you need to learn investigate on your own a bit ;) 
`cuckoo web --help`

**Comment by itsecforu** [comment]
I studied official manual at docs.cuckoosandbox.org about tips of set up web interfaces. 

system cant find the packages: uwsgi ,uwsgi-plugin-python nginx after
```
$ sudo apt-get update
$ sudo apt-get install uwsgi uwsgi-plugin-python nginx
```
![2018-10-03 10-40-07](https://user-images.githubusercontent.com/38696837/46396954-81b3ca00-c6f9-11e8-889b-158f17cc1105.png)

**Comment by doomedraven** [comment]
missed source in sources.list? google is your friend ;)

**Comment by itsecforu** [comment]
it seems its pip packages. 
Nothing abount "sources.list" in documentaions

**Comment by doomedraven** [comment]
apt uses sources.list in ubuntu, google it ;)

**Comment by itsecforu** [comment]
> apt uses sources.list in ubuntu

I know it , lol. But uwsgi is pip package and not relevant to apt

**Comment by itsecforu** [comment]
> no... but there is no uwsgi package in yak only in the lts release: https://packages.ubuntu.com/xenial/uwsgi

I install packages from this source, but all the same

![1](https://user-images.githubusercontent.com/38696837/47088486-4a7c0780-d227-11e8-9b02-d15f9747cf53.png)

Logs when i started web daemon:
`cuckoo web -H 127.0.0.1 -p 8000 
Performing system checks...

System check identified no issues (0 silenced).
October 17, 2018 - 16:06:51
Django version 1.8.4, using settings 'cuckoo.web.web.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/home/user/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 50, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/user/.local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named headers
[17/Oct/2018 16:07:05] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/home/user/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 50, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/user/.local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named headers
[17/Oct/2018 16:07:05] "GET /favicon.ico HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 579, in web
    ("cuckoo",) + args
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 49, in execute
    super(Command, self).execute(*args, **options)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 88, in handle
    self.run(**options)
  File "/home/user/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 97, in run
    autoreload.main(self.inner_run, None, options)
  File "/home/user/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 325, in main
    reloader(wrapped_main_func, args, kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 296, in python_reloader
    exit_code = restart_with_reloader()
  File "/home/user/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 282, in restart_with_reloader
    exit_code = os.spawnve(os.P_WAIT, sys.executable, args, new_environ)
  File "/usr/lib/python2.7/os.py", line 575, in spawnve
    return _spawnvef(mode, file, args, env, execve)
  File "/usr/lib/python2.7/os.py", line 548, in _spawnvef
    wpid, sts = waitpid(pid, 0)
OSError: [Errno 4] Interrupted system call
`

**Comment by doomedraven** [comment]
did you read your error?
```
ImportError: No module named headers
```

**Comment by itsecforu** [comment]
> django version? i suspect that headers version is why you have problems
> i was blind version is in there, i would suggest to start django consile and try to do that imports
> if that works check why it doesn't work with django in cuckoo

> django version? i suspect that headers version is why you have problems

```
user@cuckoo:~$ python -V
Python 2.7.12
user@cuckoo:~$ python -c "import django; print(django.get_version())"
1.8.4
```

**Comment by itsecforu** [comment]
@doomedraven 
>  check why it doesn't work with django in cuckoo
I dont know how to do it  :-(

**Comment by doomedraven** [comment]
google it :) im not a django expect sorry
