### ISSUE TITLE
Cuckoo add_path error

### ISSUE THREAD

**Issue by ChenJhua** [cuckoosandbox/cuckoo#2520]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are:
Cuckoo:2.0.6
CentOS 7 + Win7 64

##### The log, error, files etc can be found at:

**>>> from cuckoo.core.database import Database
>>> db=Database()
>>> db.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenjh/cuckoo/venv/lib/python2.7/site-packages/cuckoo/core/database.py", line 444, in connect
    dsn = config("cuckoo:database:connection")
  File "/home/chenjh/cuckoo/venv/lib/python2.7/site-packages/cuckoo/common/config.py", line 1084, in config
    file_name, cfg=cfg, strict=strict, raw=raw, loose=loose
  File "/home/chenjh/cuckoo/venv/lib/python2.7/site-packages/cuckoo/common/config.py", line 925, in __init__
    config.read(cfg or cwd("conf", "%s.conf" % file_name))
  File "/home/chenjh/cuckoo/venv/lib/python2.7/site-packages/cuckoo/misc.py", line 62, in cwd
    return os.path.join(_root, *args)
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
>>> db.add_path("/data/test_submit/hda.qcow2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenjh/cuckoo/venv/lib/python2.7/site-packages/cuckoo/core/database.py", line 1150, in add_path
    enforce_timeout, clock, "file", submit_id)
  File "/home/chenjh/cuckoo/venv/lib/python2.7/site-packages/cuckoo/common/utils.py", line 196, in inner
    return f(self, *args, **kwargs)
  File "/home/chenjh/cuckoo/venv/lib/python2.7/site-packages/cuckoo/core/database.py", line 1026, in add
    session = self.Session()
AttributeError: 'Database' object has no attribute 'Session'**

**Comment by ChenJhua** [comment]
```
from cuckoo.core.database import Database
from cuckoo.misc import decide_cwd

decide_cwd("path to your cwd")
db = Database()
db.connect()
db.add_path("/tmp/malware.exe")
```

**Comment by RicoVZ** [comment]
Hi ChenJhua,

Thanks for posting an issue. Did adding `decide_cwd` solve the issue?

**Comment by ChenJhua** [comment]
It's settled. Thank you for your help
