### ISSUE TITLE
Elasticsearch reporting module fails with ES 6: Failed to parse mapping [cuckoo]: Could not convert [procmemory.include_in_root] to boolean

### ISSUE THREAD

**Issue by seanthegeek** [cuckoosandbox/cuckoo#2542]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:

Attempting to save analysis reports to Elasticsearch 6 fails 

##### The log, error, files etc can be found at:

2018-10-28 17:04:20,236 [cuckoo] ERROR: RequestError: RequestError(400, u'mapper_parsing_exception', u'Failed to parse mapping [cuckoo]: Could not convert [procmemory.include_in_root] to boolean')
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 233, in main
    cuckoo_init(level, ctx)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 148, in cuckoo_init
    init_modules()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/startup.py", line 184, in init_modules
    module.init_once()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/reporting/elasticsearch.py", line 50, in init_once
    if not cls.apply_template():
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/reporting/elasticsearch.py", line 75, in apply_template
    name=cls.template_name, body=json.dumps(template)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 442, in put_template
    name), params=params, body=body)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: RequestError(400, u'mapper_parsing_exception', u'Failed to parse mapping [cuckoo]: Could not convert [procmemory.include_in_root] to boolean')

**Comment by doomedraven** [comment]
yep, use 5.x

**Comment by SparkyNZL** [comment]
6.x is not supported please use 5.x

Cheers.

**Comment by RicoVZ** [comment]
Hi seanthegeek,

Thanks for posting an issue. As @doomedraven and @SparkyNZL say. Unfortunately, the ES mapping has not been made ES 6 ready yet. This is something that is on our todo-list.

**Comment by seanthegeek** [comment]
Thanks. I downgraded to ES 5 and it worked. I'll leave this issue open to track ES 6 support.

**Comment by wroersma** [comment]
I'm currently working on it and have a script to re-index it as well so you
have an easy way to move from 5.x to 6.x

**Comment by SparkyNZL** [comment]
Has anyone updated the ES template as yet ?

**Comment by Kolano** [comment]
I'm presuming this is the same with ES 7, released April 10th.

**Comment by doomedraven** [comment]
ES 5.6 is latest supported version

**Comment by SparkyNZL** [comment]
Yup, these things really need to be addressed before cuckoo becomes entirely obsolete, most of the infrastructure which it operates on is no longer secure, ELK has a number of security issues in ver5.

sent from my spaceship !

________________________________

**Comment by doomedraven** [comment]
pay for enterprise support and you will get it :P

**Comment by reox** [comment]
@doomedraven does enterprise support also gives an agent which runs on windows 10? So you do have working templates for ES6 and 7 but will only give them away for moneyz?

**Comment by doomedraven** [comment]
I dont have nothing to see with cuckoo, im just a cuckoo user, for that you
need to speak with @jbremer
