### ISSUE TITLE
Mongo vs Elasticsearch

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2561]
So...I've always wondered this.  I'm hitting the 16 meg mongodb limit more and more which results in no results in the web based interface.  Will disabling mongodb and enabling es fix this up?  Thank you.

**Comment by doomedraven** [comment]
;)

**Comment by DigiAngel** [comment]
Looks like disabling mongodb isn't an option :(
~~~
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file
~~~

**Comment by SparkyNZL** [comment]
certainly is.

How many Yara rules do you have enabled ?

**Comment by doomedraven** [comment]
taht is another one, a lot of yara in yara exchange are garbage and FPs, you can save also space if you comment out to not to save the matched strings only rule and offset

**Comment by DigiAngel** [comment]
I have a fair bit...tried the ES route but that tanked miserably:
~~~
2018-11-21 14:46:48,928 [elasticsearch] WARNING: POST http://127.0.0.1:9200/cuckoo2-2018/cuckoo [status:N/A request:36.116s]
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo2-venv/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/cuckoo/cuckoo2-venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/cuckoo/cuckoo2-venv/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/cuckoo/cuckoo2-venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/cuckoo/cuckoo2-venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 470, in begin
    self.msg = HTTPMessage(self.fp, 0)
  File "/usr/lib/python2.7/mimetools.py", line 25, in __init__
    rfc822.Message.__init__(self, fp, seekable)
  File "/usr/lib/python2.7/rfc822.py", line 108, in __init__
    self.readheaders()
  File "/usr/lib/python2.7/httplib.py", line 309, in readheaders
    raise HTTPException("got more than %d headers" % _MAXHEADERS)
ProtocolError: ('Connection aborted.', HTTPException('got more than 100 headers',))
~~~

**Comment by doomedraven** [comment]
ES version?

**Comment by DigiAngel** [comment]
5.6.0

**Comment by doomedraven** [comment]
thats weird, well why just not to backport that what i told you? :P

**Comment by DigiAngel** [comment]
Doomed....LoL...I get the feeling you are thinking I know how to do, what you've told me to do ;)  I have no idea how to backport anything in cuckoo2.  If I did....I wouldn't be here now ;)  I always appreciate your help and the fact you're always responding.  So...if you'd tell me HOW to backport, I'm all eyes.

**Comment by doomedraven** [comment]
ah ok that change the thing then i can tell you what to do :P

**Comment by doomedraven** [comment]
[mongodb.txt](https://github.com/cuckoosandbox/cuckoo/files/2605921/mongodb.txt)
change to .py this should works

**Comment by DigiAngel** [comment]
Awesome...thank you I'll give this a go and report my findings.

**Comment by doomedraven** [comment]
you are welcome, check almost all is at the end of the file so as you can check it check size and kick it off, so at least the rest of report is there, but if you use a lot of yaras, kick of saving matched things, only names and offset that solves this problem also

**Comment by doomedraven** [comment]
@DigiAngel worked?

**Comment by DigiAngel** [comment]
Like a champ thank you :)

**Comment by doomedraven** [comment]
Amazing :)
