### ISSUE TITLE
Cuckoo Task analyzed but website doesn't contain any analysis information

### ISSUE THREAD

**Issue by raeeawe** [cuckoosandbox/cuckoo#2600]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are:
cuckoo version 2.06 , os linux ubuntu

##### The log, error, files etc can be found at:

2019-01-14 10:59:17,766 [cuckoo.core.scheduler] INFO: Using "vmware" as machine manager
2019-01-14 10:59:19,051 [cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2019-01-14 10:59:19,054 [cuckoo.core.scheduler] WARNING: As you've configured Cuckoo to execute parallel analyses, we recommend you to switch to a MySQL or a PostgreSQL database as SQLite might cause some issues.
2019-01-14 10:59:19,062 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2019-01-14 10:59:37,580 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "s.exe" (task #1, options "port=False,procmemdump=yes,route=none")
2019-01-14 10:59:37,712 [cuckoo.core.scheduler] INFO: Task #1: acquired machine cuckoo1 (label=/home/cuckoo/vmware/cl1
![screenshot from 2019-01-14 11-16-24](https://user-images.githubusercontent.com/46664068/51096277-dcc38580-17ed-11e9-8d33-e6d1d5191477.png)
.vmx)
2019-01-14 10:59:37,739 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 11607 (interface=vmnet1, host=192.168.214.129)
2019-01-14 10:59:53,655 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.214.129)
2019-01-14 10:59:58,285 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=cuckoo1, ip=192.168.214.129)
2019-01-14 11:02:38,144 [cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
14/1/2019 -- 11:14:01 - <Notice> - This is Suricata version 4.1.0 RELEASE
14/1/2019 -- 11:14:01 - <Notice> - all 13 packet processing threads, 4 management threads initialized, engine started.
14/1/2019 -- 11:14:01 - <Notice> - Signal Received.  Stopping engine.
14/1/2019 -- 11:14:02 - <Notice> - Pcap-file module read 1 files, 238 packets, 23947 bytes

![screenshot from 2019-01-14 11-16-24](https://user-images.githubusercontent.com/46664068/51096281-e5b45700-17ed-11e9-9aec-c9bd09a0123d.png)

**Comment by raeeawe** [comment]
This issue is very random, i had analyzed over 100 files that can be sucessfully reported, however this issue just occurred randomly . I do not recall any changes I made to any configuration file that would cause this

**Comment by raeeawe** [comment]
2019-01-14 11:47:06,548 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 623, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 263, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
DocumentTooLarge: BSON document too large (95907497 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2019-01-14 11:47:06,861 [cuckoo.apps.apps] INFO: Task #2: reports generation completed

**Comment by raeeawe** [comment]
still nothing shown even though it says completed

**Comment by k41zen** [comment]
I have exactly the same issue. I'm running 2 analysis instances (cuckoo -d process instance1/2) which completed but nothing is showing in the web gui. I even tried "cuckoo clean" as I had huge gaps but that doesn't help either.

2019-01-24 10:48:28,817 [cuckoo.apps.apps] INFO: Task #1: reporting task
2019-01-24 10:48:28,829 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #1
2019-01-24 10:48:28,951 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #1
2019-01-24 10:48:30,986 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #1
2019-01-24 10:48:30,986 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #1
2019-01-24 10:48:35,445 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #1
2019-01-24 10:52:42,080 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #1
2019-01-24 10:52:42,081 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #1
2019-01-24 10:52:42,333 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #1
2019-01-24 10:52:42,458 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #1
2019-01-24 10:52:42,461 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #1
2019-01-24 10:52:42,525 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #1
2019-01-24 10:52:42,668 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #1
2019-01-24 10:52:43,005 [cuckoo.core.plugins] DEBUG: Executed processing module "VirusTotal" for task #1
2019-01-24 10:52:43,006 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #1
2019-01-24 10:52:43,006 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #1
2019-01-24 10:52:43,010 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #1
2019-01-24 10:52:43,013 [cuckoo.core.plugins] DEBUG: Running 540 signatures
2019-01-24 10:52:44,003 [cuckoo.core.plugins] DEBUG: Analysis matched signature: pdf_attachments
2019-01-24 10:52:44,004 [cuckoo.core.plugins] DEBUG: Analysis matched signature: pdf_javascript
2019-01-24 10:52:44,004 [cuckoo.core.plugins] DEBUG: Analysis matched signature: pdf_openaction
2019-01-24 10:52:44,004 [cuckoo.core.plugins] DEBUG: Analysis matched signature: pdf_openaction_js
2019-01-24 10:52:44,004 [cuckoo.core.plugins] DEBUG: Analysis matched signature: creates_doc
2019-01-24 10:52:44,004 [cuckoo.core.plugins] DEBUG: Analysis matched signature: dropper
2019-01-24 10:52:44,005 [cuckoo.core.plugins] DEBUG: Analysis matched signature: antivirus_virustotal
2019-01-24 10:52:44,005 [cuckoo.core.plugins] DEBUG: Analysis matched signature: process_martian
2019-01-24 10:52:44,005 [cuckoo.core.plugins] DEBUG: Analysis matched signature: memdump_urls
2019-01-24 10:52:44,005 [cuckoo.core.plugins] DEBUG: Analysis matched signature: injection_resumethread
2019-01-24 10:52:52,427 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2019-01-24 10:52:52,438 [cuckoo.apps.apps] INFO: Task #1: reports generation completed

**Comment by k41zen** [comment]
I was running mongodb v3 but to get rid of the BSON errors I upgraded to v4. Ever since then every file analyses fine (even those that failed previously) BUT not one successful report has made it to the recent section of the webgui. Things are getting worse
