### ISSUE TITLE
Mongodb.py new creates error Global Name 'log'

### ISSUE THREAD

**Issue by KlausItem** [cuckoosandbox/cuckoo#2603]
After change of my mongodb.py because of the 16MB limit i got this error.
Is there anything i missed ???

Cuckoo 2.0.6

analysis completed successfully
Jan 14 08:02:16 main.c:609 main(): THREAD 0x7f8d4c93a780
2019-01-14 08:02:43,877 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 623, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 301, in run
    log.error(str(e))
NameError: global name 'log' is not defined
2019-01-14 08:02:43,888 [cuckoo.core.scheduler] INFO: Task #1416: reports generation completed
2019-01-14 08:02:43,970 [cuckoo.core.scheduler] INFO: Task #1416: analysis procedure completed

**Comment by doomedraven** [comment]
was solved in the PR, replace and close

**Comment by doomedraven** [comment]
@jbremer close
