### ISSUE TITLE
Can not run cuckoo

### ISSUE THREAD

**Issue by omaemaru** [cuckoosandbox/cuckoo#2623]
When I type cuckoo -d to start it I get this

````
cuckoo -d
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.1.4 (/usr/lib/python2.7/dist-packages), Requirement.parse('cryptography>=2.3'), set(['pyOpenSSL']))
```

**Comment by omaemaru** [comment]
Fixed it by installing an older cryptography version.

**Comment by doomedraven** [comment]
@jbremer  close
