### ISSUE TITLE
Getting line errors when starting cuckoo

### ISSUE THREAD

**Issue by omaemaru** [cuckoosandbox/cuckoo#2626]
`2019-01-29 13:14:18,737 [pip._internal.utils.misc] DEBUG: lzma module is not available
2019-01-29 13:14:18,771 [pip._internal.vcs] DEBUG: Registered VCS backend: git
2019-01-29 13:14:18,772 [pip._internal.vcs] DEBUG: Registered VCS backend: hg
2019-01-29 13:14:18,772 [pip._internal.vcs] DEBUG: Registered VCS backend: svn
2019-01-29 13:14:18,772 [pip._internal.vcs] DEBUG: Registered VCS backend: bzr
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.6.2', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 242, in main
    sys.stderr.write(exception_message())
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/utils.py", line 262, in exception_message
    for package in pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'`

**Comment by omaemaru** [comment]
Fixed it by installing a different Python version.

**Comment by ammarahmad93** [comment]
Thats great 

Can you share the scripts please.

Thanks alot.

**Comment by omaemaru** [comment]
Get Python2.7 or delete any other python you already have and then get the 2.7
