### ISSUE TITLE
Unable to find any Microsoft Office Word executable.

### ISSUE THREAD

**Issue by omaemaru** [cuckoosandbox/cuckoo#2656]
##### My Cuckoo version and operating system are: Last version and Windows7 32x

   _______ _     _ _______ _     _  _____   _____
   |       |     | |       |____/  |     | |     |
   |_____  |_____| |_____  |    \_ |_____| |_____|

 Cuckoo Sandbox 2.0.6
 www.cuckoosandbox.org
 Copyright (c) 2010-2018

2019-02-15 15:44:36,083 [cuckoo] WARNING: It appears that you haven't loaded any Cuckoo Signatures. Signatures are highly recommended and improve & enrich the information extracted during an analysis. They also make up for the analysis score that you see in the Web Interface - so, pretty important!
2019-02-15 15:44:36,100 [cuckoo] WARNING: You'll be able to fetch all the latest Cuckoo Signaturs, Yara rules, and more goodies by running the following command:
2019-02-15 15:44:36,101 [cuckoo] INFO: $ cuckoo community
2019-02-15 15:44:36,101 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2019-02-15 15:44:39,277 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2019-02-15 15:44:39,286 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2019-02-15 15:45:09,720 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "Contrato.doc" (task #11, options "procmemdump=yes,route=none")
2019-02-15 15:45:09,766 [cuckoo.core.scheduler] INFO: Task #11: acquired machine cuckoo1 (label=cuckoo1)
2019-02-15 15:45:09,805 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 11722 (interface=vboxnet0, host=192.168.56.101)
2019-02-15 15:45:14,364 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2019-02-15 15:45:23,235 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=cuckoo1, ip=192.168.56.101)
2019-02-15 15:46:06,626 [cuckoo.core.guest] WARNING: cuckoo1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpb2zwwo/analyzer.py", line 800, in <module>
    success = analyzer.run()
  File "C:/tmpb2zwwo/analyzer.py", line 652, in run
    pids = self.package.start(self.target)
  File "C:\tmpb2zwwo\modules\packages\doc.py", line 70, in start
    word = self.get_path("Microsoft Office Word")
  File "C:\tmpb2zwwo\lib\common\abstracts.py", line 84, in get_path
    application)
CuckooPackageError: Unable to find any Microsoft Office Word executable.

2019-02-15 15:46:08,079 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2019-02-15 15:46:18,337 [cuckoo.core.scheduler] INFO: Task #11: reports generation completed
2019-02-15 15:46:18,343 [cuckoo.core.scheduler] INFO: Task #11: analysis procedure completed

**Comment by omaemaru** [comment]
Solved

**Comment by doomedraven** [comment]
close than //c @jbremer
