### ISSUE TITLE
Analysis Failed: IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by angeloliveira** [cuckoosandbox/cuckoo#2681]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:

A month ago I set up a sandbox environment running Cuckoo 2.0.6 on Ubuntu 16.04 LTS and Windows XP SP3 guest. Performed a lot of tests with different malware. Everything was OK. Took a snapshot. For my surprise, today I started looking at that again (snapshot) and got the following error. Note that the error happens frequently with different malware, but not always. The running conditions are the same (same computer, network, etc). Please help!

##### My Cuckoo version and operating system are:

Cuckoo 2.0.6 on Ubuntu 16.04 LTS and Windows XP SP3 guest.

##### This can be reproduced by:

Starting an analysis of malware.

##### The log, error, files etc can be found at:

2019-03-11 18:43:10,320 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2019-03-11 18:43:36,207 [cuckoo.core.scheduler] DEBUG: Processing task #1
2019-03-11 18:43:36,220 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "cerber.exe" (task #1, options "")
2019-03-11 18:43:36,275 [cuckoo.core.scheduler] INFO: Task #1: acquired machine windowsxp (label=windowsxp)
2019-03-11 18:43:36,284 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 32491 (interface=vboxnet0, host=192.168.56.10)
2019-03-11 18:43:36,285 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2019-03-11 18:43:36,383 [cuckoo.machinery.virtualbox] DEBUG: Starting vm windowsxp
2019-03-11 18:43:36,723 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine windowsxp to snapshot1
2019-03-11 18:43:38,570 [cuckoo.core.guest] INFO: Starting analysis on guest (id=windowsxp, ip=192.168.56.10)
2019-03-11 18:43:39,575 [cuckoo.core.guest] DEBUG: windowsxp: not ready yet
2019-03-11 18:43:40,582 [cuckoo.core.guest] DEBUG: windowsxp: not ready yet
2019-03-11 18:43:41,588 [cuckoo.core.guest] DEBUG: windowsxp: not ready yet
2019-03-11 18:43:42,593 [cuckoo.core.guest] DEBUG: windowsxp: not ready yet
2019-03-11 18:43:43,597 [cuckoo.core.guest] DEBUG: windowsxp: not ready yet
2019-03-11 18:43:43,726 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=windowsxp, ip=192.168.56.10)
2019-03-11 18:43:43,776 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=windowsxp, ip=192.168.56.10, monitor=latest, size=3967696)
2019-03-11 18:43:44,486 [cuckoo.core.guest] DEBUG: windowsxp: analysis still processing
2019-03-11 18:43:44,899 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2019-03-11 18:43:45,498 [cuckoo.core.guest] WARNING: windowsxp: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpxebjdg/analyzer.py", line 800, in <module>
    success = analyzer.run()
  File "C:/tmpxebjdg/analyzer.py", line 574, in run
    __import__(package_name, globals(), locals(), ["dummy"], -1)
  File "C:\tmpxebjdg\modules\packages\exe.py", line 7, in <module>
    import shlex
  File "C:\Python27\lib\shlex.py", line 54
    fG2?G????j'=v?_???/?3?O??/o?=?MA ?8???#C??[???<???Y??-?s?????V???G]^?Q????>='??:SkM??
                                                                                                     ^
IndentationError: unindent does not match any outer indentation level

2019-03-11 18:43:45,538 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2019-03-11 18:43:45,539 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm windowsxp
2019-03-11 18:43:46,870 [cuckoo.core.scheduler] DEBUG: Released database task #1
2019-03-11 18:43:46,913 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #1
2019-03-11 18:43:46,913 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2019-03-11 18:43:46,914 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #1
2019-03-11 18:43:46,914 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #1
2019-03-11 18:43:46,915 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #1
2019-03-11 18:43:46,916 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #1
2019-03-11 18:43:46,917 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #1
2019-03-11 18:43:46,918 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #1
2019-03-11 18:43:46,918 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #1
2019-03-11 18:43:47,498 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #1
2019-03-11 18:43:47,561 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #1
2019-03-11 18:43:47,650 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #1
2019-03-11 18:43:47,652 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #1
2019-03-11 18:43:47,652 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #1
2019-03-11 18:43:47,653 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #1
2019-03-11 18:43:47,656 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #1
2019-03-11 18:43:47,658 [cuckoo.core.plugins] DEBUG: Running 540 signatures
2019-03-11 18:43:47,838 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2019-03-11 18:43:47,873 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2019-03-11 18:43:47,874 [cuckoo.core.scheduler] INFO: Task #1: reports generation completed
2019-03-11 18:43:47,884 [cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed

**Comment by angeloliveira** [comment]
Just reinstalled the whole thing. Worked out. Thanks!
