### ISSUE TITLE
Unable to stop auxiliary module: Sniffer Traceback(CuckooOperationalError)

### ISSUE THREAD

**Issue by chanseng** [cuckoosandbox/cuckoo#2683]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
i have tried#2132,it just fixed permission denied,but a new issue showed 
by the way,i  changed the cuckoo.conf upload_max_size to 314572800 ,but it does not work
thanks a lot
##### My Cuckoo version and operating system are:
cuckoo2.0.6  
host:ubuntu16.0.4
vm:win7

##### The log, error, files etc can be found at:
Unable to stop auxiliary module: Sniffer Traceback (most recent call last): 

 File "/home/cuck/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 163, in stop module.stop() 

 File "/home/cuck/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 174, in stop self._check_output(out, err) 

 File "/home/cuck/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 135, in _check_output "the following standard error output: %r." % line 

CuckooOperationalError: Potential error while running tcpdump, did not expect the following standard error output: 'et), capture size 262144 bytes\n152 packets captured\n154 packets received by filter\n0 packets dropped by ke'.

**Comment by chanseng** [comment]
This is from the cuckoo box terminal

**2019-03-13 14:05:31,291 [cuckoo.core.scheduler] DEBUG: Processing task #9
2019-03-13 14:05:31,342 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "ez_setup.py" (task #9, options "procmemdump=yes,route=none")
2019-03-13 14:05:31,437 [cuckoo.core.scheduler] INFO: Task #9: acquired machine cuckoo1 (label=cuckoo1)
2019-03-13 14:05:31,453 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 21429 (interface=vboxnet0, host=192.168.56.101)
2019-03-13 14:05:31,456 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2019-03-13 14:05:31,582 [cuckoo.machinery.virtualbox] DEBUG: Starting vm cuckoo1
2019-03-13 14:05:31,990 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine cuckoo1 to snapshot1
2019-03-13 14:05:35,562 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2019-03-13 14:05:36,582 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-03-13 14:05:37,593 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-03-13 14:05:38,476 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=cuckoo1, ip=192.168.56.101)
2019-03-13 14:05:38,549 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo1, ip=192.168.56.101, monitor=latest, size=3967696)
2019-03-13 14:05:40,200 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
......
2019-03-13 14:05:44,240 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2019-03-13 14:05:44,584 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2019-03-13 14:05:45,250 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
......
2019-03-13 14:05:53,345 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2019-03-13 14:05:54,012 [cuckoo.core.resultserver] DEBUG: File upload request for shots/0001.jpg
2019-03-13 14:05:54,024 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 57991
2019-03-13 14:05:54,352 [cuckoo.core.guest] WARNING: cuckoo1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmp4c0ser/analyzer.py", line 800, in <module>
    success = analyzer.run()
  File "C:/tmp4c0ser/analyzer.py", line 652, in run
    pids = self.package.start(self.target)
  File "C:\tmp4c0ser\modules\packages\python.py", line 28, in start
    return self.execute(python, args=args, trigger="file:%s" % path)
  File "C:\tmp4c0ser\lib\common\abstracts.py", line 166, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted
2019-03-13 14:05:54,486 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/home/cuck/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 163, in stop
    module.stop()
  File "/home/cuck/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 174, in stop
    self._check_output(out, err)
  File "/home/cuck/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 135, in _check_output
    "the following standard error output: %r." % line
CuckooOperationalError: Potential error while running tcpdump, did not expect the following standard error output: 'et), capture size 262144 bytes\n158 packets captured\n160 packets received by filter\n0 packets dropped by ke'.
2019-03-13 14:05:54,531 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo1
2019-03-13 14:05:57,793 [cuckoo.core.scheduler] DEBUG: Released database task #9
2019-03-13 14:05:57,885 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #9
2019-03-13 14:05:57,886 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2019-03-13 14:05:57,886 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #9
2019-03-13 14:05:57,887 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #9
2019-03-13 14:05:57,887 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #9
2019-03-13 14:05:57,898 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #9
2019-03-13 14:05:57,899 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #9
2019-03-13 14:05:57,900 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #9
2019-03-13 14:05:57,911 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #9
2019-03-13 14:05:57,915 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #9
2019-03-13 14:05:57,918 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #9
2019-03-13 14:05:57,921 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #9
2019-03-13 14:05:57,951 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #9
2019-03-13 14:05:57,952 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #9
2019-03-13 14:05:57,952 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #9
2019-03-13 14:05:57,957 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #9
2019-03-13 14:05:57,963 [cuckoo.core.plugins] DEBUG: Running 540 signatures
2019-03-13 14:05:58,187 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2019-03-13 14:05:58,328 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2019-03-13 14:05:58,328 [cuckoo.core.scheduler] INFO: Task #9: reports generation completed 
2019-03-13 14:05:58,342 [cuckoo.core.scheduler] INFO: Task #9: analysis procedure completed2019-03-13 14:05:31,291 [cuckoo.core.scheduler] DEBUG: Processing task #9

2019-03-13 14:05:31,342 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "ez_setup.py" (task #9, options "procmemdump=yes,route=none")
2019-03-13 14:05:31,437 [cuckoo.core.scheduler] INFO: Task #9: acquired machine cuckoo1 (label=cuckoo1)
2019-03-13 14:05:31,453 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 21429 (interface=vboxnet0, host=192.168.56.101)
2019-03-13 14:05:31,456 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2019-03-13 14:05:31,582 [cuckoo.machinery.virtualbox] DEBUG: Starting vm cuckoo1
2019-03-13 14:05:31,990 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine cuckoo1 to snapshot1
2019-03-13 14:05:35,562 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2019-03-13 14:05:36,582 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-03-13 14:05:37,593 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-03-13 14:05:38,476 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=cuckoo1, ip=192.168.56.101)
2019-03-13 14:05:38,549 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo1, ip=192.168.56.101, monitor=latest, size=3967696)
2019-03-13 14:05:40,200 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
......
2019-03-13 14:05:44,240 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2019-03-13 14:05:44,584 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2019-03-13 14:05:45,250 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
......
2019-03-13 14:05:53,345 [cuckoo.core.guest] DEBUG: cuckoo1: analysis still processing
2019-03-13 14:05:54,012 [cuckoo.core.resultserver] DEBUG: File upload request for shots/0001.jpg
2019-03-13 14:05:54,024 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 57991
2019-03-13 14:05:54,352 [cuckoo.core.guest] WARNING: cuckoo1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmp4c0ser/analyzer.py", line 800, in <module>
    success = analyzer.run()
  File "C:/tmp4c0ser/analyzer.py", line 652, in run
    pids = self.package.start(self.target)
  File "C:\tmp4c0ser\modules\packages\python.py", line 28, in start
    return self.execute(python, args=args, trigger="file:%s" % path)
  File "C:\tmp4c0ser\lib\common\abstracts.py", line 166, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

2019-03-13 14:05:54,486 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/home/cuck/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 163, in stop
    module.stop()
  File "/home/cuck/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 174, in stop
    self._check_output(out, err)
  File "/home/cuck/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 135, in _check_output
    "the following standard error output: %r." % line
CuckooOperationalError: Potential error while running tcpdump, did not expect the following standard error output: 'et), capture size 262144 bytes\n158 packets captured\n160 packets received by filter\n0 packets dropped by ke'.
2019-03-13 14:05:54,531 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo1
2019-03-13 14:05:57,793 [cuckoo.core.scheduler] DEBUG: Released database task #9
2019-03-13 14:05:57,885 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #9
2019-03-13 14:05:57,886 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2019-03-13 14:05:57,886 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #9
2019-03-13 14:05:57,887 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #9
2019-03-13 14:05:57,887 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #9
2019-03-13 14:05:57,898 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #9
2019-03-13 14:05:57,899 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #9
2019-03-13 14:05:57,900 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #9
2019-03-13 14:05:57,911 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #9
2019-03-13 14:05:57,915 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #9
2019-03-13 14:05:57,918 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #9
2019-03-13 14:05:57,921 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #9
2019-03-13 14:05:57,951 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #9
2019-03-13 14:05:57,952 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #9
2019-03-13 14:05:57,952 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #9
2019-03-13 14:05:57,957 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #9
2019-03-13 14:05:57,963 [cuckoo.core.plugins] DEBUG: Running 540 signatures
2019-03-13 14:05:58,187 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2019-03-13 14:05:58,328 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2019-03-13 14:05:58,328 [cuckoo.core.scheduler] INFO: Task #9: reports generation completed 

**

thanks a lot : )
