### ISSUE TITLE
LoadZer0m0n fails

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2691]
##### My issue is:
LoadZer0m0n fails

##### My Cuckoo version and operating system are:
Latest cuckoo, Ubuntu 18 host, Win 10 1709 guest

##### This can be reproduced by:
Running any analysis with analysis = kernel

##### The log, error, files etc can be found at:
~~~
2019-03-17 07:01:25,043 [analyzer] ERROR: Cannot execute auxiliary module LoadZer0m0n: Command '['sc', 'stop', 'PcaSvc']' returned non-zero exit status 1062
Traceback (most recent call last):
  File "C:/tmpzsz2ni/analyzer.py", line 622, in run
    aux.start()
  File "C:\tmpzsz2ni\modules\auxiliary\zer0m0n.py", line 30, in start
    subprocess_checkcall(["sc", "stop", "PcaSvc"])
  File "C:\tmpzsz2ni\lib\api\process.py", line 100, in subprocess_checkcall
    stderr=subprocess.PIPE, env=env,
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['sc', 'stop', 'PcaSvc']' returned non-zero exit status 1062
~~~

**Comment by DigiAngel** [comment]
Anyone?
