### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by KennyTe** [cuckoosandbox/cuckoo#2704]
2019-04-01 03:33:55,572 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 737, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 527, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 480, in start_analysis
    self.query_environ()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 355, in query_environ
    self.environ = self.get("/environ").json()["environ"]
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
Why:?

**Comment by LetMeR00t** [comment]
Hi,
If this is the latest Cuckoo version, I suggest you to modify the cuckoo agent on your VM.
It should be in 0.8 version and not in 0.1 as mentionnés in your debug.
