### ISSUE TITLE
Cucko web interface will not start

### ISSUE THREAD

**Issue by mmbenque** [cuckoosandbox/cuckoo#2707]
Able to start cuckoo using the command: cuckoo
also used the following commands during configuration:
Cuckoo Working Directory

$ sudo mkdir /opt/cuckoo
$ sudo chown cuckoo:cuckoo /opt/cuckoo
$ cuckoo --cwd /opt/cuckoo

Confirmed it's not a permissions issue by issuing the following command:
sudo -u cuckoo cuckoo --cwd /opt/cuckoo
Output see below

Error message:
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.
[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100

MongoDB authentication (optional).
username =
password =

cuckoo --cwd /opt/cuckoo command returns:
Traceback (most recent call last):
File "/usr/local/bin/cuckoo", line 10, in 
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in call
return self.main(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1037, in invoke
return Command.invoke(self, ctx)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 242, in main
sys.stderr.write(exception_message())

**Comment by mmbenque** [comment]
Error message:
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.
[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100
# MongoDB authentication (optional).
username = 
password = 

cuckoo --cwd /opt/cuckoo command returns:
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 242, in main
    sys.stderr.write(exception_message())

**Comment by LetMeR00t** [comment]
Hi,
Did you check with a netstat command if your mongodb instance is running ?

**Comment by doomedraven** [comment]
@jbremer  looks like can be closed, no response since april

**Comment by jbremer** [comment]
Thanks @doomedraven :)
