### ISSUE TITLE
Failed_processing for significant amount of samples

### ISSUE THREAD

**Issue by TheWarthog123** [cuckoosandbox/cuckoo#2711]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

**ISSUE:**
Cuckoo is marking samples as failed_processing. This error is present for significant amount of samples. Also the buffer/cache size is continuously growing and is not being freed.

**ENVIRONMENT:**
Cuckoo - 2.0.5.3
Ubuntu 18.04
RAM - 32 GB
ESX 6.5,5.5
Number of workers - 16
No. of cuckoo process - 3

**ERROR MESSAGE AT 'cuckoo process'**
2019-04-10 20:38:46,621 [cuckoo.core.plugins] ERROR: Failed to run 'on_call' of the moves_self signature
Traceback (most recent call last):
  File "/home/user/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 413, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "/home/user/.cuckoo/signatures/windows/moves_self.py", line 25, in on_call
    if self.initial_process in oldpath:
TypeError: coercing to Unicode: need string or buffer, list found
2019-04-10 20:38:46,622 [cuckoo.apps.apps] ERROR: Task #227: error reporting: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/home/user/cuckoo/local/lib/python2.7/site-packages/cuckoo/apps/apps.py", line 264, in process_task
    process(task["target"], copy_path, task)
  File "/home/user/cuckoo/local/lib/python2.7/site-packages/cuckoo/apps/apps.py", line 220, in process
    RunSignatures(results=results).run()
  File "/home/user/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 514, in run
    self.yield_calls(proc)
  File "/home/user/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 454, in yield_calls
    if self.call_signature(sig, sig.on_call, call, proc) is False:
  File "/home/user/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 424, in call_signature
    extra={"task_id": task_id}
  File "/usr/lib/python2.7/logging/__init__.py", line 1207, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1200, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/home/user/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/log.py", line 34, in emit
    self.format(record), int(record.task_id),
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by TheWarthog123** [comment]
Few tasks does not even throw this error but the status for that task is failed_analysis.
Database used - postgresql

**Comment by TheWarthog123** [comment]
The machine is also getting hung during powering off a machine. The machine was hung at that state for more than 10 hours and did not even throw any error.
**ERROR:**

2019-04-10 22:35:30,881 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:31,900 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:32,919 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:33,938 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:34,956 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:35,975 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:36,995 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:38,015 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:39,032 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:40,050 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:41,066 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:42,086 [cuckoo.core.guest] DEBUG: Machine_CW_W7_64_10: analysis still processing
2019-04-10 22:35:42,881 [cuckoo.core.resultserver] DEBUG: File upload request for files/09dab62af8d1355c_xacoziyecakefasomoja xuruyilizajamo fuvonocudolaribapekafixetado kocawepeyemibejere juhoyafayaxatugeluvosabefela
2019-04-10 22:35:43,097 [cuckoo.core.guest] INFO: Machine_CW_W7_64_10: analysis completed successfully
2019-04-10 22:35:50,764 [cuckoo.machinery.vsphere] INFO: Powering off virtual machine Machine_CW_W7_64_10

**Memory**

              total        used        free      shared  buff/cache   available
Mem:            31G        6.1G        2.5G        387M         22G         24G
Swap:          979M          0B        979M

CPU usage is low, no issue with that

Have used ESX as a host and used vsphere as a machinery as using ESX machinery was throwing multiple errors in libvirt. All those issues were resolved using vsphere machinery but facing the above issue.

**Comment by abay123** [comment]
I get the same problem when I input "cuckoo submit --package ff -u http://xx.html" to submit a url .It show that 

2019-08-20 15:19:30,737 [cuckoo.core.plugins] ERROR: Failed to run 'on_call' of the moves_self signature
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 462, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "/home/abay/.cuckoo/signatures/windows/moves_self.py", line 25, in on_call
    if self.initial_process in oldpath:
TypeError: coercing to Unicode: need string or buffer, list found
2019-08-20 15:19:30,865 [cuckoo.core.plugins] ERROR: Failed to run 'on_call' of the moves_self signature
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 462, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "/home/abay/.cuckoo/signatures/windows/moves_self.py", line 25, in on_call
    if self.initial_process in oldpath:
TypeError: coercing to Unicode: need string or buffer, list found
2019-08-20 15:19:31,024 [cuckoo.core.plugins] ERROR: Failed to run 'on_call' of the moves_self signature
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 462, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "/home/abay/.cuckoo/signatures/windows/moves_self.py", line 25, in on_call
    if self.initial_process in oldpath:
TypeError: coercing to Unicode: need string or buffer, list found
