### ISSUE TITLE
BUG:LoadZer0m0n error

### ISSUE THREAD

**Issue by wuhoocd** [cuckoosandbox/cuckoo#2724]
My issue is:
LoadZer0m0n error

My Cuckoo version and operating system are:
cuckoo 2.0.6, Linux kali 4.19.0-kali3-amd64 host, Windows 7 X64 SP1 guest

This can be reproduced by:
cuckoo submit -o analysis=kernel xxx.exe

The analysis log:

`[analyzer] ERROR: Cannot execute auxiliary module LoadZer0m0n: [Errno 2] No such file or directory: 'C:\\Windows\\sysnative\\drivers\\texFDNHzQceAhdCC.sys'
Traceback (most recent call last):
  File "C:/tmpqm3lci/analyzer.py", line 622, in run
    aux.start()
  File "C:\tmpqm3lci\modules\auxiliary\zer0m0n.py", line 33, in start
    d.install()
  File "C:\tmpqm3lci\lib\core\driver.py", line 22, in install
    self.copy_driver()
  File "C:\tmpqm3lci\lib\core\driver.py", line 56, in copy_driver
    shutil.copy(self.driver_path, self.install_path)
  File "C:\Python27\lib\shutil.py", line 139, in copy
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'C:\\Windows\\sysnative\\drivers\\texFDNHzQceAhdCC.sys'`

I read the ~/.cuckoo/analyzer/windows/lib/core/driver.py, i think the copy_driver method has a bug,it has reversed the value of install_dir when judge the os platform is x64 or x86, so i modified the method as below:

def copy_driver(self):

        if platform.machine().endswith("64"):
            self.driver_path = os.path.join(
                "bin", "%s-x64.sys" % self.driver_name
            )
            install_dir = os.path.expandvars(
               "%SystemRoot%\\system32\\drivers"
            )
        else:
            self.driver_path = os.path.join(
                "bin", "%s-x86.sys" % self.driver_name
            )
            install_dir = os.path.expandvars(
                "%SystemRoot%\\sysnative\\drivers"
            )
            
        if not os.path.exists(self.driver_path):
            raise CuckooError("Error locating %s driver!" % self.driver_name)

        self.install_path = os.path.join(
            install_dir, "%s.sys" % self.install_name
        )

        shutil.copy(self.driver_path, self.install_path)`

the LoadZer0m0n succeed, then a bigger problem appeared: the client system crashed, and show a blue screen, the cuckoo analysis.log:

`2019-04-29 23:10:32,651 [analyzer] DEBUG: Started auxiliary module LoadZer0m0n
2019-04-29 23:10:32,651 [analyzer] INFO: zer0m0n: Loaded version Feb 19 2019 14:20:25
2019-04-29 23:10:32,651 [lib.core.ioctl] WARNING: Error performing ioctl (0x00222010): 87!`

**Comment by wuhoocd** [comment]
I changed the client's python from python-2.7.16.amd64 to python-2.7.16, and restore the driver.py, the the LoadZer0m0n succeed, but blue screen client happened still.
