### ISSUE TITLE
Migrate from SQLite3 to PostgreSQL

### ISSUE THREAD

**Issue by leniwiec16** [cuckoosandbox/cuckoo#2742]
##### My issue is: 
I encounter error while trying to migrate from default sqlite db to postgres

##### My Cuckoo version and operating system are:
Cuckoo 2.0.6
Ubuntu 18.04.1 LTS

##### This can be reproduced by:
Here are the steps I took:

Install dependencies ( psycopg2-2.8.2):
pip install psycopg2

Stop Cuckoo services:
sudo venv/bin/supervisorctl stop cuckoo:

Stop webui related services:
sudo systemctl stop nginx.service
sudo systemctl stop uwsgi.service

Create cuckoo db and user:
sudo -u postgres -i
psql
postgres=# create database cuckoo;
postgres=# create user cuckoo with encrypted password '<redacted>';
postgres=# grant all privileges on database cuckoo to cuckoo;
\q
exit

Modify relevant line in cuckoo.conf:
connection = postgresql://cuckoo:<redacted>@localhost:5432/cuckoo

cuckoo migrate

##### The log, error, files etc can be found at:

(venv) cuckoo@cuckoo-Virtual-Machine:~$ cuckoo migrate
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5aa718cc79e1, Database migration (from Cuckoo 0.6-1.0 to 1.1)
Traceback (most recent call last):
  File "/home/cuckoo/venv/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "./env.py", line 59, in <module>
    run_migrations_online()
  File "./env.py", line 52, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/home/cuckoo/venv/lib/python2.7/site-packages/cuckoo/private/db_migration/versions/from_0_6_to_1_1.py", line 77, in upgrade
    sa.Column("tag_id", sa.Integer, sa.ForeignKey("tags.id")),
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/operations/ops.py", line 1098, in create_table
    return operations.invoke(op)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 194, in create_table
    self._exec(schema.CreateTable(table))
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "machines" does not exist
 [SQL: '\nCREATE TABLE machines_tags (\n\tmachine_id INTEGER, \n\ttag_id INTEGER, \n\tFOREIGN KEY(machine_id) REFERENCES machines (id), \n\tFOREIGN KEY(tag_id) REFERENCES tags (id)\n)\n\n']
>>> Error migrating your database..

What am I missing? Is it possible to do migration like that? I'd really appreciate your help.

**Comment by RicoVZ** [comment]
Hey leniwiec16.

Thanks for posting an issue.

>  Is it possible to do migration like that? 

Unfortunately, not with the migration tool. This tool is meant to update/migrate the database schema of one database to a newer version in case of Cuckoo updates. It might happen that new tables/columns etc are added or deleted.

Migrating a Cuckoo database from one RDBMS to another is not something that is supported by Cuckoo.

**Comment by leniwiec16** [comment]
I see, that's a pity. Thanks for quick reply. In theory, if I were to use tool like [https://github.com/dimitri/pgloader](url) to manually migrate the db, is there a chance that Cuckoo will  pick up were it left off or am I better to start from scratch? 

I'll leave this open for the time being in case anyone has some bright ideas.

**Comment by leniwiec16** [comment]
Ok. I've managed to do it with a 3rd party tool and everything seem to work. I've followed the steps listed here: [https://tutorialinux.com/today-learned-migrating-sqlite-postgres-easy-sequel/](url)

Assuming the same config and steps from the first post to create postgres db, next I:

**Install some dependencies:**
sudo apt install ruby
sudo apt install ruby-dev
sudo apt install postgresql-server-dev-10
sudo apt install libsqlite3-dev

**Installing rubygems:**
download tgz archive from https://rubygems.org/pages/download
tar -xvf rubygems-3.0.3.tgz
cd rubygems-3.0.3/
sudo ruby setup.rb

**Installing sequel and some other tools:**
sudo gem install sequel pg sqlite3

**Migrating the database:**
sequel -C sqlite:///home/cuckoo/.cuckoo/cuckoo.db postgresql://cuckoo:<redacted>@localhost:5432/cuckoo  

After that I launched cuckoo process as usual and it didn't throw any error. Analysis are working correctly. Hopefully this helps someone :)

**Comment by RicoVZ** [comment]
Thanks for sharing that, @leniwiec16 :slightly_smiling_face:
