### ISSUE TITLE
Mongodb AutoReconnect: 127.0.0.1:27017: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by alienzoX** [cuckoosandbox/cuckoo#2746]
##### My issue is:
First sample submission is going well and store properly But second sample and beyond give the error for reporting and storing data in mongo: (****AutoReconnect: 127.0.0.1:27017: [Errno 104] Connection reset by peer - full error at below section)**.**
I've tried many ways, delete mongo and install different version and etc. could any one please help with with this error.
Cheers.

##### My Cuckoo version and operating system are:
Cuckoo Version: 2.0.6
Mongo version 3.0.3
pymongo version: 3.0.3

##### The log, error, files etc can be found at: (Second sample reporting error ** first one store properly. )
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 623, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 104, in run
    sample_id = self.store_file(sample, filename=fname)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 60, in store_file
    existing = self.db.fs.files.find_one({"sha256": file_obj.get_sha256()})
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 744, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 755, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 88, in send_message_with_response
    response_data = sock_info.receive_message(1, request_id)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 216, in receive_message
    self._raise_connection_failure(error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 314, in _raise_connection_failure
    _raise_connection_failure(self.address, error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 58, in _raise_connection_failure
    raise AutoReconnect(msg)
AutoReconnect: 127.0.0.1:27017: [Errno 104] Connection reset by peer

**Comment by alienzoX** [comment]
Alright, I've just figured it out where the issue is coming from this means the sample didn't submit to VM for analysis so it returns NULL and basically the mongo says has nothing to put in.
NOW the thing is When I submit Malware through web GUI is working FINE, however when I submit the same sample or anything else with this command is not work:
`runuser -l cuckoo -c "cuckoo submit --machine <MACHINENAME> <SAMPLE_PATH"`

Interesting thing here is after submission with command line we have this:
`Django version 1.8.4, using settings 'cuckoo.web.web.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
2019-06-08 03:35:27,877 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "sample1" (task #47, options "")
2019-06-08 03:35:27,929 [cuckoo.core.scheduler] INFO: Task #47: acquired machine cuckoo1 (label=win7x644)
2019-06-08 03:35:27,938 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 33841 (interface=vboxnet0, host=192.168.56.120)
2019-06-08 03:35:31,648 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.120)
2019-06-08 03:35:35,729 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=cuckoo1, ip=192.168.56.120)
2019-06-08 03:35:41,348 [cuckoo.core.guest] INFO: Virtual Machine /status failed (CuckooGuestError('Cuckoo Agent failed without error status, please try upgrading to the latest version of agent.py (>= 0.8) and notify us if the issue persists.',))`

A couple of seconds later after the VM status is up:
`HTTP/1.0 200 OK
Server: Cuckoo Agent Python/2.7.15
Date: Sat, 08 Jun 2019 03:38:52 GMT
Content-type: text/html; charset=mbcs
Content-Length: 102406`

Once is done it failed to report to mongo: (because submit failed to pass file)
`019-06-08 03:39:39,828 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 623, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 104, in run
    sample_id = self.store_file(sample, filename=fname) 
[...]
AutoReconnect: 127.0.0.1:27017: [Errno 104] Connection reset by peer
` 
It means `cuckoo submit` command cant pass sample to VM however WEB GUI submission is working fine 

ANY idea Whats Going on Here ? 

Thanks.

**Comment by doomedraven** [comment]
that is problem with mongo not cuckoo, you need to investigate that what is wrong with your mongo setup

**Comment by doomedraven** [comment]
That is mongo, not pymongo
