### ISSUE TITLE
Running cuckoo web gives 

### ISSUE THREAD

**Issue by Markcus35** [cuckoosandbox/cuckoo#2748]
My issue is: I am running cuckoo on KALI version 2019.2 if I run the cuckoo web command below error is what I get in return: I I can submit malware for analysis via CLI but I can not open the web server of cuckoo., 

root@KALICUCOOhost:~# cuckoo web
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f861e11f758>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 405, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (admin.E402) 'django.contrib.auth.context_processors.auth' must be in TEMPLATES in order to use the admin application.

**Comment by RicoVZ** [comment]
Hi Markcus35,

Thanks for posting an issue. Can you tell us what version of Cuckoo you are running?

You can check the version is you run `pip show cuckoo`.

**Comment by Markcus35** [comment]
Name: Cuckoo
Version: 2.0.6.2
Summary: Automated Malware Analysis System
Home-page: https://cuckoosandbox.org/
Author: Stichting Cuckoo Foundation
Author-email: cuckoo@cuckoofoundation.org
License: GPLv3
Location: /usr/lib/python2.7/dist-packages
Requires: requests, scapy
Required-by:
