### ISSUE TITLE
Remote Control on Xen

### ISSUE THREAD

**Issue by bas27** [cuckoosandbox/cuckoo#2749]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html
Yes i read
##### My issue is:
Setting the remote control to Xen does not work.
When I send a file for testing in the sandbox and at the same time perform the analysis settings: 1. I turn on the remote control, 
2. I turn off the human activity simulation, 
3. I click the Analysis button, 
the file is sent in the standby mode (pending) 

##### My Cuckoo version and operating system are:
Version: 2.0.6
Ubuntu server 16.04.6 on XenServer 7.6

##### This can be reproduced by:

Установка guacd

```
sudo apt -y установить libcairo2-dev libjpeg-turbo8-dev libpng-dev libossp-uuid-dev libfreerdp-dev
mkdir / tmp / guac-build && cd / tmp / guac-build
wget https://www.apache.org/dist/guacamole/1.0.0/source/guacamole-server-1.0.0.tar.gz
$ tar xvf guacamole-server-1.0.0.tar.gz && cd guacamole-server-1.0.0
$ ./configure --with-init-dir = / etc / init.d
$ make && sudo make install && cd ..
$ sudo ldconfig
$ sudo /etc/init.d/guacd start
```

Then for cuckcoo.conf I added the following lines at the bottom of the file:

[remotecontrol]
enabled = yes
guacd_host = localhost 
guacd_port = 4822

##### The log, error, files etc can be found at:
`cat /home/cuckoo/.cuckoo/storage/analyses/68/cuckoo.log`
```
2019-06-05 13:24:40,554 [cuckoo.core.scheduler] INFO: Task #68: acquired machine cuckoo1 (label=29c552a9-b85a-d5d2-7447-bad8acd48f9e)
2019-06-05 13:24:40,575 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 8195 (interface=eth1, host=192.168.56.2)
2019-06-05 13:24:40,575 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2019-06-05 13:24:40,578 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 737, in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 474, in launch_analysis
    "Remote control support has not been implemented "
CuckooMachineError: Remote control support has not been implemented for this machinery.
```

`cat /home/cuckoo/.cuckoo/log/cuckoo.log`
```
2019-06-05 13:24:40,513 [cuckoo.core.scheduler] DEBUG: Processing task #68
2019-06-05 13:24:40,523 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "my_source.rdg" (task #68, options "human=0,procmemdump=yes,remotecontrol=yes,route=internet")
2019-06-05 13:24:40,554 [cuckoo.core.scheduler] INFO: Task #68: acquired machine cuckoo1 (label=29c552a9-b85a-d5d2-7447-bad8acd48f9e)
2019-06-05 13:24:40,575 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 8195 (interface=eth1, host=192.168.56.2)
2019-06-05 13:24:40,575 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2019-06-05 13:24:40,578 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 737, in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 474, in launch_analysis
    "Remote control support has not been implemented "
CuckooMachineError: Remote control support has not been implemented for this machinery.
```

If additional information is required ready to provide.

**Comment by RicoVZ** [comment]
Hi bas27,

Thanks for posting an issue.
Unfortunately, RDP is currently only supported when using Virtualbox. It is something we are working on.

**Comment by bas27** [comment]
Thank you for your prompt response(((!
Are there any waiting times for a new release?

**Comment by RicoVZ** [comment]
No specific date yet, but the improvements I spoke of are still in development and will not be included in the newest release, as this will be very soon.
