### ISSUE TITLE
Failure in AnalysisManager.run, 500 Server Error

### ISSUE THREAD

**Issue by leniwiec16** [cuckoosandbox/cuckoo#2753]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Some analysis fail with Internal Server Error for url: http://192.168.122.101:8000/store
##### My Cuckoo version and operating system are:
Cuckoo 2.0.6
Ubuntu 18.04.1 LTS

##### This can be reproduced by:
Submitting samples via API. Also, I've recently replicated my main Win7 VM to 4 hosts which are being run concurrently and that's when the issue started it seems.  I can't share the samples because they contain sensitive data but uploading the file again works fine so I don't think it's related to the specific file or filetype. 
##### The log, error, files etc can be found at:
2019-06-17 12:20:58,907 [cuckoo.core.scheduler] DEBUG: Processing task #5126
2019-06-17 12:20:58,916 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "<redacted>" (task #5126, options "")
2019-06-17 12:20:58,939 [cuckoo.core.scheduler] INFO: Task #5126: acquired machine Win7x64_1 (label=Win7x64_1)
2019-06-17 12:20:58,947 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 184319 (interface=virbr0, host=192.168.122.101)
2019-06-17 12:20:58,948 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2019-06-17 12:20:58,962 [cuckoo.common.abstracts] DEBUG: Starting machine Win7x64_1
2019-06-17 12:20:58,963 [cuckoo.common.abstracts] DEBUG: Getting status for Win7x64_1
2019-06-17 12:20:58,981 [cuckoo.common.abstracts] DEBUG: Using snapshot snapshot1 for virtual machine Win7x64_1
2019-06-17 12:21:03,600 [cuckoo.common.abstracts] DEBUG: Getting status for Win7x64_1
2019-06-17 12:21:03,681 [cuckoo.core.guest] INFO: Starting analysis on guest (id=Win7x64_1, ip=192.168.122.101)
2019-06-17 12:21:03,701 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=Win7x64_1, ip=192.168.122.101)
2019-06-17 12:21:03,721 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=Win7x64_1, ip=192.168.122.101, monitor=latest, size=3968936)
2019-06-17 12:21:04,205 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2019-06-17 12:21:04,206 [cuckoo.common.abstracts] DEBUG: Stopping machine Win7x64_1
2019-06-17 12:21:04,206 [cuckoo.common.abstracts] DEBUG: Getting status for Win7x64_1
2019-06-17 12:21:04,559 [cuckoo.common.abstracts] DEBUG: Getting status for Win7x64_1
2019-06-17 12:21:04,635 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 737, in run
    self.launch_analysis()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 527, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 501, in start_analysis
    self.post("/store", files=files, data=data)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 330, in post
    r.raise_for_status()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.122.101:8000/store

What I experience seem on par with #1739

**Comment by RicoVZ** [comment]
Hi leniwiec16,

Thanks for posting an issue.
This is likely caused by the Cuckoo agent not having permission to write the uploaded file (probably while uploading the analyzer). The agent must run with administrator privileges.

Can you test it manually? Boot one of the VM, and POST a file to the agent.

`curl http://192.168.122.101:8000/store -F "filepath=C:\testfolder" -F "file=@somefile"`

**Comment by leniwiec16** [comment]
> 
> 
> Hi leniwiec16,
> 
> Thanks for posting an issue.
> This is likely caused by the Cuckoo agent not having permission to write the uploaded file (probably while uploading the analyzer). The agent must run with administrator privileges.
> 
> Can you test it manually? Boot one of the VM, and POST a file to the agent.
> 
> `curl http://192.168.122.101:8000/store -F "filepath=C:\testfolder" -F "file=@somefile"`

Hi RicoVZ,

Thanks for reply. I've tested all my VMs, also concurrently. Nothing indicating the problem:

`cuckoo@cuckoo-Virtual-Machine:~/Downloads$ curl http://192.168.122.101:8000/store -F "filepath=C:\testfolder" -F "file=@<redacted>"
{"message": "Successfully stored file"}
cuckoo@cuckoo-Virtual-Machine:~/Downloads$ curl http://192.168.122.102:8000/store -F "filepath=C:\testfolder" -F "file=@<redacted>"
{"message": "Successfully stored file"}
cuckoo@cuckoo-Virtual-Machine:~/Downloads$ curl http://192.168.122.103:8000/store -F "filepath=C:\testfolder" -F "file=@<redacted>"
{"message": "Successfully stored file"}
cuckoo@cuckoo-Virtual-Machine:~/Downloads$ curl http://192.168.122.104:8000/store -F "filepath=C:\testfolder" -F "file=@<redacted>"
{"message": "Successfully stored file"}`

**Comment by ziadmoubayed** [comment]
Thanks for your help. I have a similar issue when uploading a file using the api.

> 2019-07-09 17:24:49,749 [cuckoo.core.scheduler] INFO: Task #105: acquired machine cuckoo1 (label=cuckoo1)
2019-07-09 17:24:49,784 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 10989 (interface=vboxnet0, host=192.168.56.101)
2019-07-09 17:24:54,774 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2019-07-09 17:24:57,805 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=cuckoo1, ip=192.168.56.101)
2019-07-09 17:25:02,094 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 737, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 527, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 501, in start_analysis
    self.post("/store", files=files, data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 330, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.101:8000/store

**Comment by ne1llee** [comment]
**My Cuckoo version and operating system are:**
Cuckoo 2.0.7
Centos 7

Hi, RicoVZ,

I also encountered the same problem, it appears randomly and cannot locate the cause.


![image](https://user-images.githubusercontent.com/12810839/63225020-bb50cf00-c1fe-11e9-9ffe-223b41a0713a.png)

**Comment by nidorinas** [comment]
Hello, I have the same problem. However when I tried to do:
`curl http://192.168.122.101:8000/store -F "filepath=C:\testfolder" -F "file=@somefile"`
I get a message saying 'no file has been provided' and error code 400. May I know how to proceed on this?
