### ISSUE TITLE
I have an error when I installed cuckoo via pip to run the cuckoo process 1 command.

### ISSUE THREAD

**Issue by 821104180** [cuckoosandbox/cuckoo#2756]
2019-06-20 14:30:54,844 [cuckoo] INFO: Initialized instance=1, ready to process some tasks
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 449, in process
    process_tasks(instance, maxcount, timeout)
TypeError: process_tasks() takes exactly 2 arguments (3 given)
--------------------------------------------------------------------------------------------------
apps.py file is not up to date

**Comment by 821104180** [comment]
Sorry, it is my fault
