### ISSUE TITLE
Task scheduler broken when specifying analysis machine using the API

### ISSUE THREAD

**Issue by bitback** [cuckoosandbox/cuckoo#2761]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
On the current setup I use 4 analysis VMs running on KVM. When submitting files using the API or web interface and let Cuckoo automatically decide which system should be used for the analysis, everything works like a charm.

But when submitting e.g. 10 files to a specific analysis system (using the API), Cuckoo tries to start all analysis as the same time which end up in curious errors. Only a few of them are processed successfully, all the others end up in errors.

Cuckoo is up to date and also, agent.py has been updated on the analysis VM to version 0.10. As mentioned above, when Cuckoo itself will decide which analysis system will be chosen, submitting 100 files works fine.

##### My Cuckoo version and operating system are:
- Operating system: Ubuntu 18.04 (Kernel version: 4.15.0-52-generic x86_64 GNU/Linux)
- Cuckoo version: 2.0.8

##### This can be reproduced by:
Using multiple analyzer VMs (at least two) and submit e.g. 10 files to the analyzer and specify cuckoo_vm_1 as analyzer machine.

##### The log, error, files etc can be found at:
cuckoo.log

```2019-06-25 12:57:05,019 [cuckoo.core.guest] INFO: Starting analysis #104 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 12:57:05,027 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 12:57:05,756 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "office.docx" (task #110, options "")
2019-06-25 12:57:06,910 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "office.docx" (task #111, options "")
2019-06-25 12:57:08,023 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "office.docx" (task #112, options "")
2019-06-25 12:57:09,149 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "office.docx" (task #113, options "")
2019-06-25 12:58:15,848 [cuckoo.core.guest] INFO: win7-32: analysis completed successfully
2019-06-25 12:58:16,399 [cuckoo.core.scheduler] INFO: Task #104: analysis procedure completed
2019-06-25 12:58:16,458 [cuckoo.core.scheduler] INFO: Task #109: acquired machine win7-32 (label=win7-32)
2019-06-25 12:58:16,467 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 6541 (ip=192.168.122.1, port=50000).
2019-06-25 12:58:16,476 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 6542 (interface=virbr0, host=192.168.122.203)
2019-06-25 12:58:22,081 [cuckoo.core.guest] INFO: Starting analysis #109 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 12:58:22,109 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 12:59:34,220 [cuckoo.core.guest] INFO: win7-32: analysis completed successfully
2019-06-25 12:59:34,767 [cuckoo.core.scheduler] INFO: Task #109: analysis procedure completed
2019-06-25 12:59:34,868 [cuckoo.core.scheduler] INFO: Task #108: acquired machine win7-32 (label=win7-32)
2019-06-25 12:59:34,876 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 6788 (ip=192.168.122.1, port=50000).
2019-06-25 12:59:34,891 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 6789 (interface=virbr0, host=192.168.122.203)
2019-06-25 12:59:34,910 [cuckoo.core.scheduler] INFO: Task #107: acquired machine win7-32 (label=win7-32)
2019-06-25 12:59:34,916 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 6790 (ip=192.168.122.1, port=50001).
2019-06-25 12:59:34,922 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 6791 (interface=virbr0, host=192.168.122.203)
2019-06-25 12:59:41,063 [cuckoo.core.guest] INFO: Starting analysis #108 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 12:59:44,538 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 12:59:44,721 [cuckoo.core.guest] INFO: Starting analysis #107 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 12:59:47,413 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 12:59:49,000 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 541, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 404, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 488, in start_analysis
    self.get("/pinning")
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 320, in get
    do_raise and r.raise_for_status()
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.122.203:8000/pinning
2019-06-25 12:59:49,050 [cuckoo.core.scheduler] INFO: Task #110: acquired machine win7-32 (label=win7-32)
2019-06-25 12:59:49,059 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 6911 (ip=192.168.122.1, port=50001).
2019-06-25 12:59:49,069 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 6914 (interface=virbr0, host=192.168.122.203)
2019-06-25 12:59:53,987 [cuckoo.core.guest] INFO: Starting analysis #110 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 12:59:53,995 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 12:59:54,107 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:01:06,802 [cuckoo.core.guest] INFO: win7-32: analysis completed successfully
2019-06-25 13:01:06,809 [cuckoo.core.guest] INFO: win7-32: analysis completed successfully
2019-06-25 13:01:07,302 [cuckoo.core.scheduler] WARNING: Unable to stop machine win7-32: Trying to stop an already stopped machine win7-32
2019-06-25 13:01:07,367 [cuckoo.core.resultserver] WARNING: ResultServer did not have a task with ID 110 and IP 192.168.122.203
2019-06-25 13:01:07,401 [cuckoo.core.scheduler] INFO: Task #108: analysis procedure completed
2019-06-25 13:01:07,451 [cuckoo.core.scheduler] INFO: Task #110: analysis procedure completed
2019-06-25 13:01:07,768 [cuckoo.core.scheduler] INFO: Task #106: acquired machine win7-32 (label=win7-32)
2019-06-25 13:01:07,775 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 7155 (ip=192.168.122.1, port=50000).
2019-06-25 13:01:07,783 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7156 (interface=virbr0, host=192.168.122.203)
2019-06-25 13:01:13,732 [cuckoo.core.guest] INFO: Starting analysis #106 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 13:01:13,741 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 13:02:25,040 [cuckoo.core.guest] INFO: win7-32: analysis completed successfully
2019-06-25 13:02:25,611 [cuckoo.core.scheduler] INFO: Task #106: analysis procedure completed
2019-06-25 13:02:26,087 [cuckoo.core.scheduler] INFO: Task #112: acquired machine win7-32 (label=win7-32)
2019-06-25 13:02:26,091 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 7398 (ip=192.168.122.1, port=50000).
2019-06-25 13:02:26,096 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7399 (interface=virbr0, host=192.168.122.203)
2019-06-25 13:02:26,122 [cuckoo.core.scheduler] INFO: Task #113: acquired machine win7-32 (label=win7-32)
2019-06-25 13:02:26,122 [cuckoo.core.scheduler] INFO: Task #105: acquired machine win7-32 (label=win7-32)
2019-06-25 13:02:26,127 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 7400 (ip=192.168.122.1, port=50001).
2019-06-25 13:02:26,131 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 7401 (ip=192.168.122.1, port=50002).
2019-06-25 13:02:26,134 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7402 (interface=virbr0, host=192.168.122.203)
2019-06-25 13:02:26,141 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7403 (interface=virbr0, host=192.168.122.203)
2019-06-25 13:02:31,850 [cuckoo.core.guest] INFO: Starting analysis #112 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 13:02:35,885 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 13:02:39,701 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Cuckoo Agent failed without error status, please try upgrading to the latest version of agent.py (>= 0.10) and notify us if the issue persists.
2019-06-25 13:02:39,852 [cuckoo.core.guest] INFO: Starting analysis #105 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 13:02:40,241 [cuckoo.core.scheduler] INFO: Task #112: analysis procedure completed
2019-06-25 13:02:41,263 [cuckoo.core.scheduler] INFO: Task #111: acquired machine win7-32 (label=win7-32)
2019-06-25 13:02:41,268 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 7532 (ip=192.168.122.1, port=50000).
2019-06-25 13:02:41,272 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7533 (interface=virbr0, host=192.168.122.203)
2019-06-25 13:02:46,125 [cuckoo.core.guest] INFO: Starting analysis #111 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 13:02:46,134 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 13:02:46,942 [cuckoo.core.guest] INFO: Starting analysis #113 on guest (id=win7-32, ip=192.168.122.203)
2019-06-25 13:02:48,076 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 13:02:48,079 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win7-32, ip=192.168.122.203)
2019-06-25 13:02:49,218 [cuckoo.core.resultserver] WARNING: ResultServer did not have a task with ID 113 and IP 192.168.122.203
2019-06-25 13:02:49,236 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 541, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 404, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 488, in start_analysis
    self.get("/pinning")
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 320, in get
    do_raise and r.raise_for_status()
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.122.203:8000/pinning
2019-06-25 13:02:49,261 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 541, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 404, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 488, in start_analysis
    self.get("/pinning")
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 320, in get
    do_raise and r.raise_for_status()
  File "/home/cuckoo/venv-cuckoo/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.122.203:8000/pinning
2019-06-25 13:02:54,441 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:00,452 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:06,457 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:12,467 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:18,477 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:24,486 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:30,496 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:36,505 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:40,578 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:43,650 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:46,722 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:49,794 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:52,866 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:55,938 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:03:59,010 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:02,082 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:05,154 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:08,226 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:11,298 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:14,370 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:17,442 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:20,514 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:23,586 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:26,658 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:29,730 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:32,802 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:35,874 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:38,946 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:42,018 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:45,090 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:48,162 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:51,234 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:54,306 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:04:57,378 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:00,450 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:03,522 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:06,595 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:09,666 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:12,738 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:15,810 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:18,882 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:21,954 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:25,026 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:28,098 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:31,170 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:34,242 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:37,314 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:40,386 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:43,458 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:46,530 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:49,602 [cuckoo.core.guest] WARNING: Virtual Machine /status failed. This can indicate the guest losing network connectivity
2019-06-25 13:05:50,605 [cuckoo.core.guest] INFO: win7-32: end of analysis reached!
2019-06-25 13:05:50,739 [cuckoo.core.scheduler] WARNING: Unable to stop machine win7-32: Trying to stop an already stopped machine win7-32
2019-06-25 13:05:50,762 [cuckoo.core.resultserver] WARNING: ResultServer did not have a task with ID 111 and IP 192.168.122.203
2019-06-25 13:05:50,795 [cuckoo.core.scheduler] INFO: Task #111: analysis procedure completed
```

**Comment by RicoVZ** [comment]
Hey bitback,

Thanks for posting an issue.

Obviously that is not supposed to happen. I will look into this. Can you please share the full cuckoo.log via pastebin link?

**Comment by bitback** [comment]
Hey RicoVZ,

Thanks for the quick response.

Following the pastebin links:
https://pastebin.com/eca8U02s -> cuckoo.conf
https://pastebin.com/dkurzsUX -> kvm.conf
https://pastebin.com/5uiXeRJ1 -> cuckoo.log
https://pastebin.com/L4CqatZm -> process-instance1.json

FYI: #1 - #30 are executables where Cuckoo decided which analysis system will be used (looks pretty good). For #31 - #40 the 32 bit system has been selected via API (here the error occurs).

**Comment by RicoVZ** [comment]
Thanks for posting those. :slightly_smiling_face: 

I suspect this is some issue with the database causing the machine to not lock properly.

Can you run Cuckoo again with these tasks, but with the `--debug` flag? After that, please post the full log file again.

`cuckoo --debug`

**Comment by bitback** [comment]
Here's the debugging log: https://pastebin.com/Z5s4REWt

**Comment by bitback** [comment]
@RicoVZ any updates on this?

**Comment by RicoVZ** [comment]
Sorry @bitback I lost the log, and the paste seems to have been removed.

Can you share the log again?

**Comment by Al33t** [comment]
Compare #3105, are those the same conditions? Your log does not go back far enough to tell.

**Comment by Al33t** [comment]
Compare #3105, are those the same conditions?
Seems so:
`019-06-25 13:02:26,122 [cuckoo.core.scheduler] INFO: Task #113: acquired machine win7-32 (label=win7-32)
`2019-06-25` 13:02:26,122 [cuckoo.core.scheduler] INFO: Task #105: acquired machine win7-32 (label=win7-32)

**Comment by Al33t** [comment]
Compare #3105, are those the same conditions?
Seems so:
`019-06-25 13:02:26,122 [cuckoo.core.scheduler] INFO: Task #113: acquired machine win7-32 (label=win7-32)
`2019-06-25` 13:02:26,122 [cuckoo.core.scheduler] INFO: Task #105: acquired machine win7-32 (label=win7-32)
