### ISSUE TITLE
Unable to execute the initial process, analysis aborted

### ISSUE THREAD

**Issue by kkkelvinkk** [cuckoosandbox/cuckoo#2764]
##### My issue is:
Some exe will produce "Unable to execute the initial process, analysis aborted" error. I suspected it may related the exe is compiled using Visual Studio Community.

##### My Cuckoo version and operating system are:
My Cuckoo version is 2.0.7. The host operating system is Windows 10 build 1903 running Virtual PC 6.0.8. Most of the library and cuckoo itself is actually running inside Windows SubSystem for Linux (Ubuntu 16.04). The guest OS is Windows 7 SP1 with latest patch.

##### This can be reproduced by:
I can reproduce whenever upload a specific exe file.

##### The log, error, files etc can be found at:
2019-06-25 22:49:04,391 [cuckoo.core.scheduler] INFO: Task #46: reports generation completed
2019-06-25 22:49:04,401 [cuckoo.core.scheduler] INFO: Task #46: analysis procedure completed
2019-06-25 22:51:09,111 [cuckoo.core.scheduler] DEBUG: Processing task #47
2019-06-25 22:51:09,119 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "version_1.exe" (task #47, options "procmemdump=yes,route=none")
2019-06-25 22:51:09,188 [cuckoo.core.scheduler] INFO: Task #47: acquired machine Win7_64 (label=Win7_64)
2019-06-25 22:51:09,190 [cuckoo.core.resultserver] DEBUG: Now tracking machine 192.168.137.104 for task #47
2019-06-25 22:51:09,192 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Replay
2019-06-25 22:51:09,229 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 26204 (interface=\Device\NPF_{366DAF6A-ED57-4964-9F7B-363BE845B756}, host=192.168.137.104)
2019-06-25 22:51:09,232 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2019-06-25 22:51:09,281 [cuckoo.machinery.virtualbox] DEBUG: Starting vm Win7_64
2019-06-25 22:51:09,589 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine Win7_64 to cuckoo_ready
2019-06-25 22:51:33,074 [cuckoo.core.guest] INFO: Starting analysis #47 on guest (id=Win7_64, ip=192.168.137.104)
2019-06-25 22:54:30,842 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=Win7_64, ip=192.168.137.104)
2019-06-25 22:54:30,934 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=Win7_64, ip=192.168.137.104, monitor=latest, size=3884763)
2019-06-25 22:54:31,353 [cuckoo.core.resultserver] DEBUG: Task #47: live log analysis.log initialized.
2019-06-25 22:54:32,229 [cuckoo.core.guest] WARNING: Win7_64: analysis #47 caught an exception
Traceback (most recent call last):
  File "C:/tmpfsobkd/analyzer.py", line 808, in <module>
    success = analyzer.run()
  File "C:/tmpfsobkd/analyzer.py", line 657, in run
    pids = self.package.start(self.target)
  File "C:\tmpfsobkd\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmpfsobkd\lib\common\abstracts.py", line 166, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

2019-06-25 22:54:32,269 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Replay
2019-06-25 22:54:32,278 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2019-06-25 22:54:32,284 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm Win7_64
2019-06-25 22:54:33,697 [cuckoo.core.resultserver] DEBUG: Stopped tracking machine 192.168.137.104 for task #47
2019-06-25 22:54:33,699 [cuckoo.core.resultserver] DEBUG: Cancel <Context for LOG> for task 47L
2019-06-25 22:54:33,709 [cuckoo.core.scheduler] DEBUG: Released database task #47
2019-06-25 22:54:33,732 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #47
2019-06-25 22:54:33,736 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2019-06-25 22:54:33,738 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #47
2019-06-25 22:54:33,741 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #47
2019-06-25 22:54:33,744 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #47
2019-06-25 22:54:33,758 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #47
2019-06-25 22:54:33,760 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #47
2019-06-25 22:54:33,763 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #47
2019-06-25 22:54:33,769 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #47
2019-06-25 22:54:34,102 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #47
2019-06-25 22:54:34,114 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #47
2019-06-25 22:54:34,124 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #47
2019-06-25 22:54:39,462 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #47
2019-06-25 22:54:39,465 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #47
2019-06-25 22:54:39,468 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #47
2019-06-25 22:54:39,473 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #47
2019-06-25 22:54:39,492 [cuckoo.core.plugins] DEBUG: Running 542 signatures
2019-06-25 22:54:39,602 [cuckoo.core.plugins] DEBUG: Analysis matched signature: dead_host
2019-06-25 22:54:39,604 [cuckoo.core.plugins] DEBUG: Analysis matched signature: network_http
2019-06-25 22:54:39,606 [cuckoo.core.plugins] DEBUG: Analysis matched signature: nolookup_communication
2019-06-25 22:54:39,616 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2019-06-25 22:54:39,647 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2019-06-25 22:54:39,649 [cuckoo.core.scheduler] INFO: Task #47: reports generation completed
2019-06-25 22:54:39,659 [cuckoo.core.scheduler] INFO: Task #47: analysis procedure completed
[version_1.zip](https://github.com/cuckoosandbox/cuckoo/files/3326501/version_1.zip)

**Comment by kkkelvinkk** [comment]
I find the problem is related to user rights. I started agent.py with "Run as administrator", and it seems to be fine now.

**Comment by RicoVZ** [comment]
Just missed your issue, sorry. :sweat_smile: 
Thanks for the update and closing the issue @kkkelvinkk
