### ISSUE TITLE
HTTPError: 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by testgitaaron** [cuckoosandbox/cuckoo#2768]
##### My issue is:
When I executed agent.py at the guest, I was unable to analyze the file successfully.

##### My Cuckoo version and operating system are:
My cuckoo version is 2.0.7, my host and my guest are both ubuntu 16.04LTS

============The following is my log with my config===========

2019-06-30 04:26:47,680 [cuckoo.core.guest] INFO: Starting analysis #13 on guest (id=cuckoo1, ip=192.168.86.128)
2019-06-30 04:26:48,685 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:49,691 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:49,788 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:50,792 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:51,797 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:52,801 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:53,806 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:54,810 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:55,816 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:56,823 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:57,830 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2019-06-30 04:26:58,842 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=cuckoo1, ip=192.168.86.128)
2019-06-30 04:26:58,858 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo1, ip=192.168.86.128, monitor=latest, size=30535)
2019-06-30 04:26:58,867 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Replay
2019-06-30 04:26:58,907 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2019-06-30 04:26:58,908 [cuckoo.machinery.vmware] DEBUG: Stopping vm /home/aaron/vmware/cuckoo1/cuckoo1.vmx
2019-06-30 04:27:00,023 [cuckoo.core.resultserver] DEBUG: Stopped tracking machine 192.168.86.128 for task #13
2019-06-30 04:27:00,029 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/aaron/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/home/aaron/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 541, in launch_analysis
    self.guest_manage(options)
  File "/home/aaron/.local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 404, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/aaron/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 494, in start_analysis
    self.upload_analyzer(monitor)
  File "/home/aaron/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 399, in upload_analyzer
    self.determine_analyzer_path()
  File "/home/aaron/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 377, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/home/aaron/.local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 339, in post
    r.raise_for_status()
  File "/home/aaron/.local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.86.128:8000/mkdtemp

[cuckoo.txt](https://github.com/cuckoosandbox/cuckoo/files/3342834/cuckoo.txt)
[vmware.txt](https://github.com/cuckoosandbox/cuckoo/files/3342835/vmware.txt)

======The following is the network information of my host and guest.======
HOST
![擷取](https://user-images.githubusercontent.com/43289336/60396146-3e936400-9b70-11e9-8d73-5faf36850933.PNG)

GUEST
![擷取2](https://user-images.githubusercontent.com/43289336/60396168-64b90400-9b70-11e9-8f97-20710efc83b1.PNG)

I have guessed that it might be a firewall problem, but I turned it off, but I am not sure if I am doing it right.
Please help me!!! I have been troubled for a long time, if there is still a lack of information, you can tell me.

**Comment by SparkyNZL** [comment]
Please review you network settings they don't appear to be correct. i don't see your host only adapter ? as a starter.

**Comment by Al33t** [comment]
Checkout #3105, are those the same conditions?
