### ISSUE TITLE
cuckoo.common.exceptions.CuckooDependencyError: Missing MySQL database driver (install with `pip install mysql-python` on Linux or `pip install mysqlclient` on Windows)

### ISSUE THREAD

**Issue by NewSystemGames** [cuckoosandbox/cuckoo#2779]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Been trying to install cuckoo with Ubuntu subsystem for windows (WSL) + Windows 10, Been having issues all the way but managed to get past most except this one, I don't understand what the problem is, I have mysql started (On bash) which has cuckoo database, and cuckoo username/passwords which both are on cuckoo.conf file, dont know what they want??? 

##### My Cuckoo version and operating system are:
Latest version of cuckoo, Windows 10 
##### This can be reproduced by:
unsure
##### The log, error, files etc can be found at:
`C:\Windows\system32>cuckoo web
Traceback (most recent call last):
  File "C:\Python27\Scripts\cuckoo-script.py", line 11, in <module>
    load_entry_point('Cuckoo==2.0.7', 'console_scripts', 'cuckoo')()
  File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python27\lib\site-packages\cuckoo\main.py", line 643, in web
    Database().connect()
  File "c:\python27\lib\site-packages\cuckoo\core\database.py", line 453, in connect
    self._connect_database(dsn)
  File "c:\python27\lib\site-packages\cuckoo\core\database.py", line 533, in _connect_database
    "Missing MySQL database driver (install with "
cuckoo.common.exceptions.CuckooDependencyError: Missing MySQL database driver (install with `pip install mysql-python` on Linux or `pip install mysqlclient` on Windows)

C:\Windows\system32>`

**Comment by RicoVZ** [comment]
Hi NewSystemGames,

Thanks for posting an issue.

This looks like you are missing the MySQL client for Python. The error message also indicates this:

>Missing MySQL database driver (install with pip install mysql-pythonon Linux orpip install mysqlclient` on Windows.

Can you try installing the client by running:
`pip install mysqlclient`

**Comment by NewSystemGames** [comment]
Hey! thank you for your answer, Im pretty sure i already ran this command, But just to confirm, I'm using Bash With Windows 10, I Installed mysql on bash ubuntu, should i run this command on bash then, right?

**Comment by NewSystemGames** [comment]
I redid the whole re-installation of cuckoo just to be sure again, same exact problem... hopeless

**Comment by nrrpinto** [comment]
Are you running cuckoo from a VENV?

If so, try to install MYSQLCLIENT using the PIP2 inside of the environment.

If in linux it would be something like:

`/home/<user>/venv/bin/pip2 install mysqlclient`
