### ISSUE TITLE
TypeError: community() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by Odyssey2247** [cuckoosandbox/cuckoo#2781]
I try to update the signatures with the command:

    $ cuckoo community

But I get the following error:

    jhon$ cuckoo community
    Traceback (most recent call last):
      File "/usr/local/bin/cuckoo", line 11, in <module>
        sys.exit(main())
      File "/home/jhon/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/home/jhon/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/home/jhon/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/jhon/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/jhon/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/home/jhon/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
    TypeError: community() got an unexpected keyword argument 'file'
    jhon$ 

this happens to me in 2 computers

cuckoo version: 2.0.7
ubuntu version: 18.04
architecture: x64
python version: 2.7.15+

**Comment by RicoVZ** [comment]
Hi Odyssey2247,

Thanks for reporting an issue.

I have not been able to reproduce this. Do any perform any commands before `cuckoo community`? Could you also tell us how you installed Cuckoo and if you have edited *any* code after that?

**Comment by Odyssey2247** [comment]
do not modify anything of cuckoo, this happens to me in 2 computers with ubuntu 18.04 (both use the same version of ubuntu and python), the first three commands I used were:

    $cuckoo                    //no errors
    $cuckoo -d               //VirtualBox errors by vboxnet0 interface (nothing serious)
    $cuckoo community //error

**Comment by Odyssey2247** [comment]
i fixed it simple removing "click" package
    pip uninstall click
