### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shutdown'

### ISSUE THREAD

**Issue by JoaquinHervasFarru** [cuckoosandbox/cuckoo#2816]
Hi everyone, I'm trying to install and use Cuckoo Sandbox with VMware vSphere, the steps I followed to install are listed in [this](https://tom-churchill.blogspot.com/2017/08/setting-up-cuckoo-sandbox-step-by-step.html?m=1) tutorial.

##### To start cuckoo I'm executing:
`sudo cuckoo -d --cwd /app/cuckoo` 
##### My Cuckoo version and operating system are:
Cuckoo: 2.0.7
OS: Ubuntu 10.04 bionic
##### The log and config files etc can be found at:
[cuckoo.log](https://github.com/cuckoosandbox/cuckoo/files/3439878/cuckoo.log)
[cuckoo.conf](https://github.com/cuckoosandbox/cuckoo/files/3439882/cuckoo.zip)
##### The file permissions of `/app/cuckoo` are:
`/app`: 755
`/app/cuckoo`: 755

Also, I've already reinstalled the `libvirt-python` library but I keep getting the same error.

**Comment by Trainee75** [comment]
Hello,

Never run cuckoo under root.

**Comment by Trainee75** [comment]
Hi,
Never run cuckoo under root. To start cuckoo :
1- Type cuckoo -d to create the CWD : https://cuckoo.readthedocs.io/en/2.0.6.2/installation/host/cwd/#configuration
2 - Configure esx.conf, cuckoo.conf ... : https://cuckoo.readthedocs.io/en/2.0.6.2/installation/host/configuration/
3 - Start cuckoo : https://cuckoo.readthedocs.io/en/2.0.6.2/usage/start/

The tutorial that you used is interesting but old, I advise you to read the official documentation of Cuckoo Sandbox.

**Comment by cvandeplas** [comment]
I have exactly the same issue, starting cuckoo with user privileges.

**Comment by JoaquinHervasFarru** [comment]
Hi Trainee75,

Thanks for the advice, I'll check the documentation and run cuckoo as a user and let you know what happens.

> Hi,
> Never run cuckoo under root. To start cuckoo :
> 1- Type cuckoo -d to create the CWD: https://cuckoo.readthedocs.io/en/2.0.6.2/installation/host/cwd/#configuration
> 2 - Configure esx.conf, cuckoo.conf ... : https://cuckoo.readthedocs.io/en/2.0.6.2/installation/host/configuration/
> 3 - Start cuckoo : https://cuckoo.readthedocs.io/en/2.0.6.2/usage/start/
> 
> The tutorial that you used is interesting but old, I advise you to read the official documentation of Cuckoo Sandbox.

**Comment by JoaquinHervasFarru** [comment]
> I have exactly the same issue, starting cuckoo with user privileges.
> 
> Further investigation in the source pointed me to the `pyvmomi` library.
> 
> > ```
> >        raise CuckooDependencyError(
> >            "Couldn't import pyVmomi, please install it (using "
> >            "`pip install -U pyvmomi`)"
> >        )
> > ```
> 
> Installing this library as recommended resolves the issue.
> I'm not sure why this exception is not caught in the logs though.

Hi, cavndeplas!

I tried reinstalling the library several times but the error keeps appearing, what version did you use to solve the issue?



> Hi,
> Never run cuckoo under root. To start cuckoo :
> 1- Type cuckoo -d to create the CWD: https://cuckoo.readthedocs.io/en/2.0.6.2/installation/host/cwd/#configuration
> 2 - Configure esx.conf, cuckoo.conf ... : https://cuckoo.readthedocs.io/en/2.0.6.2/installation/host/configuration/
> 3 - Start cuckoo : https://cuckoo.readthedocs.io/en/2.0.6.2/usage/start/
> 
> The tutorial that you used is interesting but old, I advise you to read the official documentation of Cuckoo Sandbox.

Hi Trainee75!

I've been trying to solve the issue reinstalling cuckoo several times in various methods but so far I've had no luck, I've followed the guide to configure it using the esx.conf file but the issue persists, please let me know what else can I do.

**Comment by cvandeplas** [comment]
The version that was installed is the latest one available:
```
$ pip list | fgrep pyvm
pyvmomi                            6.7.1.2018.12
```
When installing, please ensure:
- you install it with python version 2, so `pip` (and not `pip3`)
- it is installed system-wide or in the user-level of the user running cuckoo
- if you use a `venv`, you're installing it in the `venv`

**Comment by JoaquinHervasFarru** [comment]
Hi cvandeplas!

That's exactly the version I'm using but there is one dependency that's different from the official guide and I think that might be causing the issue, the official guide asks to install m2crypto with `sudo pip install m2crypto==0.24.0` but every time I try to install that specific version with that specific command I get an error message, I'm only able to install the latest version of m2crypto (m2crypto-0.35.2)

> The version that was installed is the latest one available:
> 
> ```
> $ pip list | fgrep pyvm
> pyvmomi                            6.7.1.2018.12
> ```
> 
> When installing, please ensure:
> 
> * you install it with python version 2, so `pip` (and not `pip3`)
> * it is installed system-wide or in the user-level of the user running cuckoo
> * if you use a `venv`, you're installing it in the `venv`

**Comment by cvandeplas** [comment]
I also have m2crypto 0.35.2 . 
Looking quickly at your log it looks like your install is indeed a bit broken.  If I was you I would clean up cuckoo (uninstall + remove all files) and reinstall it from a clean slate.

**Comment by RicoVZ** [comment]
Hi @JoaquinHervasFarru,

Thanks for posting an issue and apologies for the late reply.

The error you are seeing "Nonetype does not have.." is a bug, and is surpressing the actual error. This will be fixed in the next patch-release. Normally, you would indeed see that a specific library etc is missing.

**Comment by andyrat33** [comment]
I have tried from clean install twice and end up with the same error. 
I have installed the missing library as discussed in this thread but the error remains 
'NoneType' object has no attribute 'shutdown'

(venv) cuckoo@cuckoo:~/.cuckoo$ pip2 install -U pyvmomi
Requirement already up-to-date: pyvmomi in /opt/cuckoo/venv/lib/python2.7/site-packages (6.7.3)
Requirement already satisfied, skipping upgrade: six>=1.7.3 in /opt/cuckoo/venv/lib/python2.7/site-packages (from pyvmomi) (1.14.0)
Requirement already satisfied, skipping upgrade: requests>=2.3.0 in /opt/cuckoo/venv/lib/python2.7/site-packages (from pyvmomi) (2.13.0)

2020-01-19 18:35:22,898 [cuckoo] ERROR: AttributeError: 'NoneType' object has no attribute 'shutdown'
Traceback (most recent call last):
  File "/opt/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 298, in main
    cuckoo_main(maxcount)
  File "/opt/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 248, in cuckoo_main
    stop()
  File "/opt/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 231, in stop
    sched.stop()
  File "/opt/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 945, in stop
    machinery.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
