### ISSUE TITLE
mac(host):ERROR: Unable to stop auxiliary module: Sniffer

### ISSUE THREAD

**Issue by wxmustard** [cuckoosandbox/cuckoo#2830]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
 I use mac os as cuckoo host, when I submit a file for analysis, cuckoo will throw Error：Unable to stop auxiliary module: Sniffer，You don't have permission to capture on that device\n((cannot open BPF device) /dev/bpf0: Permission denied)

##### My Cuckoo version and operating system are: 
Cuckoo 2.0.7
Host : MacOS Mojave 0.14.5 (macbook)
guest: Centos7 (virtualbox)
Host and guest can ping each other.
##### This can be reproduced by:Permission denied
I readed the cuckoo doc. The doc tell me `sudo apt-get install apparmor-utils sudo aa-disable /usr/sbin/tcpdump`  But I don't find apparmor.

##### The log, error, files etc can be found at:
```bash
2019-08-08 18:29:25,832 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Replay
2019-08-08 18:29:25,832 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/Users/mustard/Library/Python/2.7/lib/python/site-packages/cuckoo/core/plugins.py", line 164, in stop
    module.stop()
  File "/Users/mustard/Library/Python/2.7/lib/python/site-packages/cuckoo/auxiliary/sniffer.py", line 156, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = "tcpdump: vboxnet0: You don't have permission to capture on that device\n((cannot open BPF device) /dev/bpf0: Permission denied)\n". Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
2019-08-08 18:29:25,837 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm centos7-2
```

**Comment by wxmustard** [comment]
Solved!
- 关闭mac保护机制
  - 方法：重启，屏幕黑了按下cmd+R直至屏幕亮起，选择语言，在最上方的导航栏中找到终端进入，输入csrutil disable，重启
- sudo chmod +s /usr/sbin/tcpdump
