### ISSUE TITLE
Failed to run the processing module "memory" with VMware

### ISSUE THREAD

**Issue by KnottA** [cuckoosandbox/cuckoo#2833]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Cannot process memory dump from VMware machinery.

##### My Cuckoo version and operating system are:
Cuckoo version: 2.0.7 (latest). 
Host machine is Ubuntu 18.04 LTS.
Client/VM machine: Win7SP1x64
Using VMware Workstation Pro 15.1.0 build-13591040

##### This can be reproduced by:
By using VMware Workstation?

##### The log, error, files etc can be found at:
```
2019-08-11 16:31:45,095 [cuckoo.core.scheduler] INFO: Using "vmware" as machine manager
2019-08-11 16:31:45,423 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2019-08-11 16:31:45,433 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2019-08-11 16:31:49,552 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "EWACS-User-Guide.pdf" (task #9, options "")
2019-08-11 16:31:49,587 [cuckoo.core.scheduler] INFO: Task #9: acquired machine cuckoo01_win7x64 (label=/home/cuckoo/cuckoo_files/VMware_share/client01_win7x64/client01_win7x64.vmx)
2019-08-11 16:31:49,596 [cuckoo.auxiliary.mitm] INFO: Started mitm interception with PID 21852 (ip=192.168.134.1, port=50000).
2019-08-11 16:31:49,605 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 21853 (interface=vmnet8, host=192.168.134.61)
2019-08-11 16:31:58,797 [cuckoo.core.guest] INFO: Starting analysis #9 on guest (id=cuckoo01_win7x64, ip=192.168.134.61)
2019-08-11 16:31:59,816 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=cuckoo01_win7x64, ip=192.168.134.61)
2019-08-11 16:34:02,230 [cuckoo.core.guest] INFO: cuckoo01_win7x64: analysis completed successfully
2019-08-11 16:38:10,226 [cuckoo.machinery.vmware] INFO: Successfully generated memory dump for virtual machine with label /home/cuckoo/cuckoo_files/VMware_share/client01_win7x64/client01_win7x64.vmx 
2019-08-11 16:38:14,517 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory" for task #9:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 246, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1118, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1039, in run
    results[plugin_name] = getattr(self.vol, plugin_name)()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 172, in pslist
    for process in command.calculate():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/win32/tasks.py", line 88, in pslist
    for p in get_kdbg(addr_space).processes():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/plugins/overlays/windows/kdbg_vtypes.py", line 42, in processes
    raise AttributeError("Could not list tasks, please verify your --profile with kdbgscan")
AttributeError: Could not list tasks, please verify your --profile with kdbgscan
2019-08-11 16:38:15,355 [cuckoo.core.scheduler] INFO: Task #9: reports generation completed
2019-08-11 16:38:15,361 [cuckoo.core.scheduler] INFO: Task #9: analysis procedure completed

```

**Comment by KnottA** [comment]
Just a sidenote; created a clean new cuckoo installation with version 2.0.6 also, just to see if I would get the same error.. Got the exact same error with the same VMware build... 

Memory forensic seems important, only workaround is to use Virtualbox I guess? 
To bad that i bought a VMware license dedicated for this cuckoo lab 🤣 
Beside this error, Cuckoo is totally awesome! Thank you so much 😄👏

**Comment by doomedraven** [comment]
you have wrong profile, if you read the error, use kdbgscan vol plugin to get correct profile for your VM

**Comment by vt-now** [comment]
If you're sure the profile is the right one, you might just be missing some files Volatility needs (vmsn, vmss). More details here: https://github.com/cuckoosandbox/cuckoo/issues/1842
