### ISSUE TITLE
Prepare physical guest machine without use Fog

### ISSUE THREAD

**Issue by flycows01** [cuckoosandbox/cuckoo#2860]
Thank for read it!

##### My issue is: 
    My physical machine is a Cloud computer(It can be back to clean image without use FOG software  when machine reboot).When I use this  physical machine as guest, Host machine can not conect to guest. 
    And this is particularly strange the physical machine is shutdown but host is waiting for analysis tasks ... like this:
**2019-09-07 15:04:05,474 [cuckoo.core.scheduler] INFO: Using "physical" as machine manager
   2019-09-07 15:04:08,564 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
   2019-09-07 15:04:08,569 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.**
and when the physical machine is runing  the warning is like this:
**CuckooCriticalError: Error initializing machines: Unknown error occurred trying to obtain the           status of physical machine Administrator. Please turn it on and check the Cuckoo Agent.**
    I followed the installation document and spent a lot of time, but I still did not solve this problem. How should I solve this problem?

##### My Cuckoo version and operating system are:
Cuckoo version: cuckoo2.0.7    OS:ubuntu 18 LTS      win7_x64

**Comment by doomedraven** [comment]
Check pull requests there was a fix for that

**Comment by flycows01** [comment]
I don't understand what you mean, can you elaborate？

**Comment by flycows01** [comment]
I don't understand what you mean, can you elaborate？@ doomedraven

**Comment by doomedraven** [comment]
Search there https://github.com/cuckoosandbox/cuckoo/pulls im from phone

**Comment by flycows01** [comment]
There is no way to solve my problem. Thank you for your help@ doomedraven

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/pull/2839

**Comment by flycows01** [comment]
Thank you very much for your help@doomedraven. This problem has been solved.
There is a new problem, I hope you can give some advice to solve it.
I have tried the solution of "permission denied-for-tcpdump" in F&Q, but it still hasn't been solved.
The error is as follows:

**2019-09-09 16:56:56,392 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=Administrator, ip=192.168.12.21)
2019-09-09 16:58:36,111 [cuckoo.core.guest] INFO: Administrator: analysis completed successfully
2019-09-09 16:58:36,117 **[cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer**
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/core/plugins.py", line 164, in stop
    module.stop()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/auxiliary/sniffer.py", line 156, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: eth0: No such device exists\n(SIOCGIFHWADDR: No such device)\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
2019-09-09 16:58:36,137 **[cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run**
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/core/scheduler.py", line 639, in launch_analysis
    machinery.stop(self.machine.label)
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/machinery/physical.py", line 105, in stop
    output = subprocess.check_output(args)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory**

**Comment by doomedraven** [comment]
try this if you didn't tried it yet

```
    adduser cuckoo
    usermod -G cuckoo -a cuckoo
    groupadd pcap
    usermod -a -G pcap cuckoo
    chgrp pcap /usr/sbin/tcpdump
    setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump

``

**Comment by flycows01** [comment]
Here's how I do it。

sudo usermod -G bary -a bary
[sudo] password for bary: 
bary@cuckoo:~$ groupadd pcap
groupadd: group 'pcap' already exists
bary@cuckoo:~$ sudo usermod -a -G pcap bary
bary@cuckoo:~$ chgrp pcap /usr/sbin/tcpdump
chgrp: changing group of '/usr/sbin/tcpdump': Operation not permitted
bary@cuckoo:~$ sudo chgrp pcap /usr/sbin/tcpdump
bary@cuckoo:~$ sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
bary@cuckoo:~$ sudo apt-get install apparmor-utils -y

0 upgraded, 0 newly installed, 0 to remove and 90 not upgraded.
bary@cuckoo:~$ sudo aa-disable /usr/sbin/tcpdump
Disabling /usr/sbin/tcpdump.

**ERROR: /sbin/apparmor_parser: Unable to remove "/usr/sbin/tcpdump".  Profile doesn't exist**

**Comment by doomedraven** [comment]
thats fine, now try again execute an analysis

**Comment by flycows01** [comment]
Same result, my physical machine is win7_64 bit, is this the reason.Do I need to modify a lot of the source code if I want it to work on a 64-bit system?

**Comment by doomedraven** [comment]
hm no, the problem should be on host where you have cuckoo, there some problems with tcpdump, try to disable sniffer to verify what the rest works just fine, so once you will have it, you will have core problem and it will be easier to solve it, but check if tcpdump is also in default location `/usr/sbin/tcpdump`

**Comment by flycows01** [comment]
There's still one problem:
2019-09-09 17:36:52,194 [cuckoo.core.guest] INFO: Administrator: analysis completed successfully
2019-09-09 17:36:52,214 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run

**Comment by doomedraven** [comment]
can you run cuckoo with `-d` for debug output?

**Comment by flycows01** [comment]
ok

**Comment by flycows01** [comment]
Log is shown below:

2019-09-09 17:42:53,382 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Replay
2019-09-09 17:42:53,416 [cuckoo.machinery.physical] DEBUG: Checking if machine u'Administrator' is running.
2019-09-09 17:42:53,416 [cuckoo.machinery.physical] DEBUG: Getting status for machine: Administrator.
2019-09-09 17:42:53,422 [cuckoo.machinery.physical] DEBUG: Machine already running: Administrator.
2019-09-09 17:42:53,434 [cuckoo.core.guest] INFO: Starting analysis #7 on guest (id=Administrator, ip=192.168.12.21)
2019-09-09 17:42:53,440 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=Administrator, ip=192.168.12.21)
2019-09-09 17:42:53,455 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=Administrator, ip=192.168.12.21, monitor=latest, size=3884763)
2019-09-09 17:42:53,700 [cuckoo.core.resultserver] DEBUG: Task #7: live log analysis.log initialized.
2019-09-09 17:42:54,026 [cuckoo.core.resultserver] DEBUG: Task #7 is sending a BSON stream
2019-09-09 17:42:54,231 [cuckoo.core.resultserver] DEBUG: Task #7 is sending a BSON stream
2019-09-09 17:42:55,228 [cuckoo.core.resultserver] DEBUG: Task #7: File upload for 'shots/0001.jpg'
2019-09-09 17:42:55,237 [cuckoo.core.resultserver] DEBUG: Task #7 uploaded file length: 122443
2019-09-09 17:42:58,638 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:00,701 [cuckoo.core.resultserver] DEBUG: Task #7: File upload for 'shots/0002.jpg'
2019-09-09 17:43:00,711 [cuckoo.core.resultserver] DEBUG: Task #7 uploaded file length: 126815
2019-09-09 17:43:01,850 [cuckoo.core.resultserver] DEBUG: Task #7: File upload for 'shots/0003.jpg'
2019-09-09 17:43:01,859 [cuckoo.core.resultserver] DEBUG: Task #7 uploaded file length: 122443
2019-09-09 17:43:03,669 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:08,695 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:13,724 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:18,751 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:23,780 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:28,808 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:33,834 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:38,861 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:43,891 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:48,919 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:53,949 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:43:58,976 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:44:00,418 [cuckoo.core.resultserver] DEBUG: Task #7: File upload for 'shots/0004.jpg'
2019-09-09 17:44:00,428 [cuckoo.core.resultserver] DEBUG: Task #7 uploaded file length: 123296
2019-09-09 17:44:01,552 [cuckoo.core.resultserver] DEBUG: Task #7: File upload for 'shots/0005.jpg'
2019-09-09 17:44:01,561 [cuckoo.core.resultserver] DEBUG: Task #7 uploaded file length: 122443
2019-09-09 17:44:04,003 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:44:09,030 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:44:14,058 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:44:19,086 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:44:24,114 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:44:29,129 [cuckoo.core.resultserver] DEBUG: Task #7: File upload for 'memory/2076-1.dmp'
2019-09-09 17:44:29,147 [cuckoo.core.guest] DEBUG: Administrator: analysis #7 still processing
2019-09-09 17:44:29,645 [cuckoo.core.resultserver] DEBUG: Task #7 uploaded file length: 46973832
2019-09-09 17:44:31,156 [cuckoo.core.guest] INFO: Administrator: analysis completed successfully
2019-09-09 17:44:31,161 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Replay
2019-09-09 17:44:31,161 [cuckoo.machinery.physical] DEBUG: Getting status for machine: Administrator.
2019-09-09 17:44:31,166 [cuckoo.machinery.physical] DEBUG: Rebooting machine: Administrator.
2019-09-09 17:44:31,178 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/core/scheduler.py", line 639, in launch_analysis
    machinery.stop(self.machine.label)
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/machinery/physical.py", line 105, in stop
    output = subprocess.check_output(args)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by flycows01** [comment]
In the directory "/ usr/lib/python2.7 subprocess. Py", subprocess. Py files exist

**Comment by doomedraven** [comment]
no no, that isn't a subprocess problem, is an arg problem, my suggestion is go to 
`/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/machinery/physical.py` line 105 and before `output = subprocess.check_output(args)` add `print(args)`

**Comment by flycows01** [comment]
God, please take my knee.I think I solved the problem.

**Comment by flycows01** [comment]
Hi，Genius@doomedraven
       When my cuckoo analysis is complete, an error like this is prompted .  I think this might be [physical:interface] Configuration error.How should this parameter be configured in Windows 7 physical matchine.Can you help me ?

------Sniffer StopProc ID :<subprocess.Popen object at 0x7f123ab81250> self.proc
------Sniffer StopProc Poll() :1 poll
2019-09-16 13:27:15,011 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/core/plugins.py", line 164, in stop module.stop() File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/auxiliary/sniffer.py", line 159, in stop
(out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = '**tcpdump: Ethernet: No such device exists\n(SIOCGIFHWADDR: No such device)**\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?

**Comment by doomedraven** [comment]
from what i see, you need to use the same iface as for internet connection 

https://github.com/cuckoosandbox/cuckoo/blob/c41c7c5cb09416b7cfc6159811792679e20762f2/cuckoo/private/cwd/conf/physical.conf#L11
