### ISSUE TITLE
sqlite3.OperationalErro

### ISSUE THREAD

**Issue by AkhtarKamal1** [cuckoosandbox/cuckoo#2863]
cuckoo@cuckoo-Inspiron-3420:/opt/cuckoo/web$ cuckoo web runserver
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 643, in web
    Database().connect()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 465, in connect
    self._create_tables()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 473, in _create_tables
    "Unable to create or connect to database: %s" % e
cuckoo.common.exceptions.CuckooDatabaseError: Unable to create or connect to database: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by doomedraven** [comment]
good day to you too

check the database owner

**Comment by AkhtarKamal1** [comment]
brother haw i can solve this problem give me some detail please

**Comment by doomedraven** [comment]
`ls -lah <path_to_db>` i don't have v2 setup but it should be in $CWD

**Comment by ryanbekabe** [comment]
Hi @AkhtarKamal1
I suggest disabling SQLite and activating MongoDB.

**Comment by doomedraven** [comment]
Thats totally wrong, mongo is for webgui and analysis datq, sqlite is task
basic info db as default engine

**Comment by RANGERBEE** [comment]
Some notes for you guys...

- one nugget that may or may not apply:
```console
cuckoo@cuckoo:~$ sed -i "/\[mongodb\]/{ N; s/.*/\[mongodb\]\nenabled = yes/; }" /home/$CUCKOO_USER/.cuckoo/conf/reporting.conf
```

- another nugget....

My cleandb.sh script below:
```bash
#!/bin/bash
# make your startup and kill scripts and put it in /root location
sudo /root/cuckoo-kill.sh
cuckoo clean
sleep 5s
# Must run clean twice or there will some weird sqlLite error on restart.
cuckoo clean
sleep 3s
sudo chown -R cuckoo:cuckoo /home/cuckoo/.cuckoo/log
# Ensure the log folder is owned by cuckoo
sudo /root/cuckoo-start.sh

exit 0
```

so -  stop cuckoo, clean+clean, check log/ ownership,  start cuckoo....
