### ISSUE TITLE
Unable to execute the initial process

### ISSUE THREAD

**Issue by gaffaneyk** [cuckoosandbox/cuckoo#2873]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is: 
When submitting exe's and msi's to cuckoo, I get a "CuckooPackageError: Unable to execute the initial process, analysis aborted."

The cuckoo agent is being ran from an account i created in the win 7 x64 guest call ced cukcoo, who is in the administrators group. The agent is being ran at startup. Netstat -a shows that the guest is listening on port 8000, not sure what's going on, any help would be great!

##### My Cuckoo version and operating system are: 
Ubuntu Server 18.04, cuckoo 2.0.7

##### The log, error, files etc can be found at:

**Terminal Error**
WARNING: cuckoo1: analysis #8 caught an exception
Traceback (most recent call last):
  File "C:/tmpggqyat/analyzer.py", line 808, in <module>
    success = analyzer.run()
  File "C:/tmpggqyat/analyzer.py", line 657, in run
    pids = self.package.start(self.target)
  File "C:\tmpggqyat\modules\packages\msi.py", line 17, in start
    return self.execute(msi_path, args=["/I", path])
  File "C:\tmpggqyat\lib\common\abstracts.py", line 166, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

**Cuckoo Log**
2019-09-17 21:11:40,119 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2019-09-17 21:11:41,862 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2019-09-17 21:11:41,873 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2019-09-17 21:13:04,521 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "MobaXterm_installer_12.1.msi" (task #8, options "procmemdump=yes,route=none")
2019-09-17 21:13:04,879 [cuckoo.core.scheduler] INFO: Task #8: acquired machine cuckoo1 (label=cuckoo1)
2019-09-17 21:13:04,911 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7273 (interface=vboxnet0, host=192.168.1.10)
2019-09-17 21:13:13,845 [cuckoo.core.guest] INFO: Starting analysis #8 on guest (id=cuckoo1, ip=192.168.1.10)
2019-09-17 21:13:17,872 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=cuckoo1, ip=192.168.1.10)
2019-09-17 21:13:57,881 [cuckoo.core.guest] WARNING: cuckoo1: analysis #8 caught an exception
Traceback (most recent call last):
  File "C:/tmpggqyat/analyzer.py", line 808, in <module>
    success = analyzer.run()
  File "C:/tmpggqyat/analyzer.py", line 657, in run
    pids = self.package.start(self.target)
  File "C:\tmpggqyat\modules\packages\msi.py", line 17, in start
    return self.execute(msi_path, args=["/I", path])
  File "C:\tmpggqyat\lib\common\abstracts.py", line 166, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

2019-09-17 21:14:02,773 [cuckoo.core.scheduler] INFO: Task #8: reports generation completed
2019-09-17 21:14:02,781 [cuckoo.core.scheduler] INFO: Task #8: analysis procedure completed

**Comment by doomedraven** [comment]
but it works if you exec it by hand?

**Comment by gaffaneyk** [comment]
No, if I double click on the agent.py, create my snapshot, then shutdown the VM. I'll still get the same error when I submit a sample to cuckoo.

**Comment by doomedraven** [comment]
I mean sample executed by hand

**Comment by gaffaneyk** [comment]
Oh, yes, the sample will execute by hand. This occurs with various msi’s and exe’s.
