### ISSUE TITLE
Unable to Stop Auxiliary Module: Sniffer for windows 10 host  

### ISSUE THREAD

**Issue by suresh30917** [cuckoosandbox/cuckoo#2890]
##### 

##### Cuckoo Log:2019-10-11 11:54:40,355 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\cuckoo\core\plugins.py", line 164, in stop
    module.stop()
  File "c:\python27\lib\site-packages\cuckoo\auxiliary\sniffer.py", line 156, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = '\n********************************************************************\n**

**Comment by Evert0x** [comment]
Hi, thank you for creating this issue. Cuckoo is not supporting windows 10. Please check this issue for a list of all the operating systems cuckoo supports. https://github.com/cuckoosandbox/cuckoo/issues/2784

**Comment by RicoVZ** [comment]
Hi @suresh30917,

Thanks for posting an issue.

We can't see the actual error, but we can see that there is error output. 
`\n********************************************************************\n**` looks like the top line of an error that tcpdump on Windows showed. It likely displayed an error saying it does not have permission to run.

Can you check if you can run it manually on the user on which Cuckoo is running?

**Comment by Wapiti08** [comment]
My situation is what there will be such error when i submit a link. In fact, in my guest machine the link can not be loaded(host-only network)
