### ISSUE TITLE
Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by andreaukk** [cuckoosandbox/cuckoo#2893]
Hello I get the following error while doing analysis on a physical machine. I'm running debian 10.
I got no analysis results, even if the analysis seem to be completed

2019-10-20 19:00:46,592 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 639, in launch_analysis
    machinery.stop(self.machine.label)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/machinery/physical.py", line 106, in stop
    output = subprocess.check_output(args)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by RicoVZ** [comment]
Hi andreaukk,

Thanks for posting an issue.

This is because the `net` tool is missing. It crashes when trying to use a net rcp command, but the tool is unavailable. This tool is required: http://manpages.ubuntu.com/manpages/bionic/man8/net.8.html

It is available in this package: https://launchpad.net/ubuntu/bionic/+package/samba-common-bin

It can be installed using `apt install samba-common-bin`.
