### ISSUE TITLE
Volatility API interface fails processing virtualbox memory dump for Ubuntu Guest OS

### ISSUE THREAD

**Issue by klapeyron1** [cuckoosandbox/cuckoo#2899]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
`[cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory" for task #219`

During processing virtualbox memory dump for the Linux Guest Volatility API fails. Seem like it has hard coded plugin commands for Windows memory dump.
For example in **cuckoo/processing/memory.py** line 172: pslist(self) function:
```python
    def pslist(self):
        results = []
        command = taskmods.PSList(self.config)
        for process in command.calculate():
            results.append({
                "process_name": str(process.ImageFileName),
                "process_id": int(process.UniqueProcessId),
                "parent_id": int(process.InheritedFromUniqueProcessId),
                "num_threads": str(process.ActiveThreads),
                "num_handles": s(process.ObjectTable.HandleCount),
                "session_id": s(process.SessionId),
                "create_time": str(process.CreateTime or ""),
                "exit_time": str(process.ExitTime or ""),
            })
        return dict(config={}, data=results)
```

Could be replaced with:

```python
  def pslist(self):
        results = []
        if self.osprofile.startswith("Linux"):
            command = self.plugins["linux_pslist"](self.config)
            for process in command.calculate():
                results.append({
                    "process_name": str(process.Name),
                    "process_id": int(process.Pid),
                    "proccess_uid": str(process.Uid),
                    "create_time": str(process.StartTime or "")
                })
        else:
            command = taskmods.PSList(self.config)
            for process in command.calculate():
                results.append({
                    "process_name": str(process.ImageFileName),
                    "process_id": int(process.UniqueProcessId),
                    "parent_id": int(process.InheritedFromUniqueProcessId),
                    "num_threads": str(process.ActiveThreads),
                    "num_handles": s(process.ObjectTable.HandleCount),
                    "session_id": s(process.SessionId),
                    "create_time": str(process.CreateTime or ""),
                    "exit_time": str(process.ExitTime or ""),
                })
```

##### My Cuckoo version and operating system are:
Cuckoo version: 2.0.7
Host OS: Ubuntu 16.04
VirtualBox Guest OS: Ubuntu 16.04
Volatilty version: 2.6.1
Volatilty profile: LinuxUbuntu1604x64 (from [here](https://github.com/volatilityfoundation/profiles/tree/master/Linux/Ubuntu/x64))

##### This can be reproduced by:
Enable Volatility processing for Linux malware sample
```bash
host& vol.py --info | grep Linux
   Volatility Foundation Volatility Framework 2.6.1
   LinuxUbuntu1604x64    - A Profile for Linux Ubuntu1604 x64
   LinuxAMD64PagedMemory          - Linux-specific AMD 64-bit address space.
   linux_aslr_shift           - Automatically detect the Linux ASLR shift
   linux_banner               - Prints the Linux banner information
   linux_yarascan             - A shell in the Linux memory image
```

##### The log, error, files etc can be found at:
```text
[cuckoo.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label cuckoo_ubuntu2 to path /home/cuckoo/.cuckoo/storage/analyses/219/memory.dmp
[cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo_ubuntu2
[cuckoo.core.resultserver] DEBUG: Stopped tracking machine 192.168.56.101 for task #219
[cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory" for task #219:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/core/plugins.py", line 246, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/processing/memory.py", line 1141, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/processing/memory.py", line 1057, in run
    results[plugin_name] = getattr(self.vol, plugin_name)()
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/processing/memory.py", line 232, in callbacks
    for (sym, cb, detail), mods, mod_addrs in command.calculate():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/plugins/malware/callbacks.py", line 545, in calculate
    modlist = list(modules.lsmod(addr_space))
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/win32/modules.py", line 33, in lsmod
    for m in tasks.get_kdbg(addr_space).modules():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/win32/tasks.py", line 50, in get_kdbg
    if obj.VolMagic(addr_space).KPCR.value:
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/obj.py", line 751, in __getattr__
    return self.m(attr)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/obj.py", line 733, in m
    raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
AttributeError: Struct VOLATILITY_MAGIC has no member KPCR

```

**Comment by BernaldoPenasAntelo** [comment]
Same issue here

My Cuckoo version and operating system are:

Cuckoo version: 2.0.7
Host OS: Debian 10.6
VirtualBox Guest OS: Debian 10.6
Volatilty version: 2.6.1
Volatilty profile: LinuxDebian_106x64    - A Profile for Linux Debian_106 x64

I have created my own linux profile in guest machine and copy it to volatility's host, i have tested that volatility shows it as a new profile and run a new scan having the result:
  
```
raceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 246, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1118, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1039, in run
    results[plugin_name] = getattr(self.vol, plugin_name)()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 172, in pslist
    for process in command.calculate():
  File "/usr/local/lib/python2.7/dist-packages/volatility/win32/tasks.py", line 88, in pslist
    for p in get_kdbg(addr_space).processes():
  File "/usr/local/lib/python2.7/dist-packages/volatility/win32/tasks.py", line 50, in get_kdbg
    if obj.VolMagic(addr_space).KPCR.value:
  File "/usr/local/lib/python2.7/dist-packages/volatility/obj.py", line 751, in __getattr__
    return self.m(attr)
  File "/usr/local/lib/python2.7/dist-packages/volatility/obj.py", line 733, in m
    raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
AttributeError: Struct VOLATILITY_MAGIC has no member KPCR

```
