### ISSUE TITLE
MAEC Report in Cuckoo 2.0.7

### ISSUE THREAD

**Issue by Zodiacc999** [cuckoosandbox/cuckoo#2901]
I'm not able to get the report in MAEC format in Cuckoo 2.0.7. 
I've tried to add the MAEC file into reporting section of cuckoo but in new Cuckoo there is no reporting folder in /cuckoo.

**Comment by Evert0x** [comment]
Hi, thank you for your posting the issue, you should copy every maec file in https://github.com/MAECProject/cuckoo/blob/maec5.0-cuckoo2.0/cuckoo/reporting/ to your reporting directory. In the comments at the top of the maecreport.py file there are some instructions.

Please let me know if you need more information.

**Comment by fugitive101** [comment]
I have followed the steps and the result is: 
Traceback (most recent call last):
  File "/home/user/venv/cuckoo/bin/cuckoo", line 5, in <module>
    from cuckoo.main import main
  File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/auxiliary/__init__.py", line 6, in <module>
    from cuckoo.core.plugins import enumerate_plugins
  File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 16, in <module>
    from cuckoo.common.abstracts import Configuration, Signature
  File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/common/abstracts.py", line 12, in <module>
    from cuckoo.common.config import config
  File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/common/config.py", line 920
    def get_section_types(self, file_name, section, strict=False, loose=False):
      ^
SyntaxError: invalid syntax

Help Please.
