### ISSUE TITLE
Database error deleting task: Class '__builtin__.NoneType' is not mapped

### ISSUE THREAD

**Issue by ayetorello** [cuckoosandbox/cuckoo#2909]
Hi !

I'm having the following error when trying to delete a task from the database.

I'm running the latest Cuckoo release "version": "2.0.7" with machines with Windows 7

2019-11-24 22:21:20,643 [werkzeug] INFO: 192.168.10.10 - - [24/Nov/2019 22:21:20] "GET /tasks/delete/105 HTTP/1.1" 200 -
Nov 24 22:21:20 cuckooserver bash[1192]: 2019-11-24 22:21:20,859 [cuckoo.core.database] ERROR: #033[31mDatabase error deleting task: Class '__builtin__.NoneType' is not mapped#033[0m
Nov 24 22:21:20 cuckooserver bash[1192]: Traceback (most recent call last):
Nov 24 22:21:20 cuckooserver bash[1192]:   File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 1510, in delete_task
Nov 24 22:21:20 cuckooserver bash[1192]:     session.delete(task)
Nov 24 22:21:20 cuckooserver bash[1192]:   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1980, in delete
Nov 24 22:21:20 cuckooserver bash[1192]:     raise exc.UnmappedInstanceError(instance)
Nov 24 22:21:20 cuckooserver bash[1192]: UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
Nov 24 22:21:20 cuckooserver bash[1192]: 2019-11-24 22:21:20,859 [cuckoo.core.database] ERROR: #033[31mDatabase error deleting task: Class '__builtin__.NoneType' is not mapped#033[0m
Nov 24 22:21:20 cuckooserver bash[1192]: Traceback (most recent call last):
Nov 24 22:21:20 cuckooserver bash[1192]:   File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 1510, in delete_task
Nov 24 22:21:20 cuckooserver bash[1192]:     session.delete(task)
Nov 24 22:21:20 cuckooserver bash[1192]:   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1980, in delete
Nov 24 22:21:20 cuckooserver bash[1192]:     raise exc.UnmappedInstanceError(instance)
Nov 24 22:21:20 cuckooserver bash[1192]: UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
Nov 24 22:21:20 cuckooserver bash[1192]: [24/Nov/2019 22:21:20] "GET /analysis/remove/105/ HTTP/1.1" 200 12340

Let me know if I can provide you with any additional information

**Comment by CrimsonGlory** [comment]
I'm having the same issue.

**Comment by RicoVZ** [comment]
Hi ayetorello,

Thanks for creating an issue.

I will take a look at it.

**Comment by RicoVZ** [comment]
I cannot reproduce it (yet). Can you share what DBMS you are using? Sqlite is the default. Did you change it to anything else?

**Comment by ayetorello** [comment]
Yes, sorry I forgot to mention it, I changed it to postgres (PostgreSQL) 10.10

**Comment by RicoVZ** [comment]
Thanks! :slightly_smiling_face: 

It looks like it is some odd race condition. I will change how a task is deleted a bit. That should solve the issue.

Thanks for reporting!

**Comment by CrimsonGlory** [comment]
Could be related to this?
https://github.com/cuckoosandbox/cuckoo/issues/1754#issuecomment-511416985
