### ISSUE TITLE
cuckoo Distributed

### ISSUE THREAD

**Issue by nadir3392** [cuckoosandbox/cuckoo#2922]
Hello,
I installed cuckoo 2.0.7 under ubuntu 16.04 with the Windows guest machine installed in VBox, it works very well, now I have configured the couckoo distribute and nothing to display in the web interface, and I want a technical explanation of what it is the couckoo distribute + cuckoo api and REST API.

cuckoo api -H 192.168.42.14 -P 8090
result
<img width="645" alt="git11" src="https://user-images.githubusercontent.com/37904476/70830536-b092f900-1df0-11ea-986e-0f321bd19642.png">

cuckoo distributed server 192.168.42.14:9003

<img width="957" alt="git1" src="https://user-images.githubusercontent.com/37904476/70830609-e1732e00-1df0-11ea-8018-b444c6f7f2c0.png">
 with this error in Terminal ubuntu :
### ### ### ### 
192.168.42.15 - - [13/Dec/2019 15:41:01] "GET /api/stats?period=week&include=memory_usage HTTP/1.1" 500 -
192.168.42.15 - - [13/Dec/2019 15:41:01] "GET /api/stats?period=week&include=amount_prio_queued HTTP/1.1" 200 -
[2019-12-13 15:41:01,203] ERROR in app: Exception on /api/stats [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/distributed/views/api.py", line 503, in stats_get
    statistics[name] = stat_handlers[name](end_date, steps, nodes)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/distributed/views/api.py", line 949, in _get_nodes_processes
    ).order_by(NodeStatus.timestamp.desc()).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2445, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2281, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 71, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 428, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 486, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/type_api.py", line 1010, in process
    return process_value(value, dialect)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/distributed/db.py", line 42, in process_result_value
    return json.loads(value)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
192.168.42.15 - - [13/Dec/2019 15:41:01] "GET /api/stats?period=week&include=active_processes HTTP/1.1" 500 -
192.168.42.15 - - [13/Dec/2019 15:41:01] "GET /static/images/refresh.svg HTTP/1.1" 304 -
### ### ### ### ### 
pls help me.
thank's

**Comment by nadir3392** [comment]
fixed.
