### ISSUE TITLE
Keeping getting this error everytime the sample is run  AnalysisManager.run Tracebac

### ISSUE THREAD

**Issue by Shersto** [cuckoosandbox/cuckoo#2954]
Always get the same issue when submitting a sample.

2020-02-07 07:36:38,384 [cuckoo.core.startup] DEBUG:     |-- office ole.yar
2020-02-07 07:36:38,387 [cuckoo.core.scheduler] INFO: Using "esx" as machine manager
2020-02-07 07:36:38,837 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7
2020-02-07 07:36:38,920 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2020-02-07 07:36:38,944 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2020-02-07 07:37:32,062 [cuckoo.core.scheduler] DEBUG: Processing task #21
2020-02-07 07:37:32,079 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "7d73c4fd84e3dc96cac5ed31419becbd00a18db43cca205df759                                                                                                                                                                                        4a4d77d90f5c" (task #21, options "procmemdump=yes,route=none")
2020-02-07 07:37:32,183 [cuckoo.core.scheduler] INFO: Task #21: acquired machine Windows7 (label=Windows7)
2020-02-07 07:37:32,184 [cuckoo.core.resultserver] DEBUG: Now tracking machine 10.10.10.9 for task #21
2020-02-07 07:37:32,433 [cuckoo.common.abstracts] DEBUG: Starting machine Windows7
2020-02-07 07:37:32,433 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7
2020-02-07 07:37:32,543 [cuckoo.common.abstracts] DEBUG: Using snapshot clean for virtual machine Windows7
2020-02-07 07:37:38,480 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7
2020-02-07 07:37:39,120 [cuckoo.core.guest] INFO: Starting analysis #21 on guest (id=Windows7, ip=10.10.10.9)
2020-02-07 07:37:40,126 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 07:37:41,135 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 07:37:42,142 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 07:37:43,149 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 07:37:44,156 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 07:38:28,073 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=Windows7, ip=10.10.10.9)
2020-02-07 07:38:31,164 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=Windows7, ip=10.10.10.9, monitor=latest, size=3053                                                                                                                                                                                        5)
2020-02-07 07:38:49,426 [cuckoo.common.abstracts] DEBUG: Stopping machine Windows7
2020-02-07 07:38:49,427 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7
2020-02-07 07:38:52,582 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7
2020-02-07 07:38:52,698 [cuckoo.core.resultserver] DEBUG: Stopped tracking machine 10.10.10.9 for task #21
2020-02-07 07:38:52,742 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 541, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 404, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 512, in start_analysis
    self.post("/store", files=files, data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 339, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://10.10.10.9:8000/store

**Comment by RicoVZ** [comment]
Hi Shersto,

Thanks for posting an issue.

This looks like the Cuckoo Agent (The component sending the 500 error) cannot store anything on disk. This is the most common reason. Is your agent being run with admin privileges?

**Comment by Shersto** [comment]
I will check that...it should be admin

**Comment by Shersto** [comment]
If that doesn't work any other suggestions I can try?

**Comment by Shersto** [comment]
Same issue despite running agent as administrator

**Comment by Shersto** [comment]
Now after changing folder permissions, etc this is what is displayed 2020-02-07 11:29:41,018 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7
2020-02-07 11:29:41,633 [cuckoo.core.guest] INFO: Starting analysis #23 on guest (id=Windows7, ip=10.10.10.9)
2020-02-07 11:29:42,643 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 11:29:43,658 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 11:29:44,665 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 11:29:45,673 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 11:29:46,685 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 11:29:47,721 [cuckoo.core.guest] DEBUG: Windows7: not ready yet
2020-02-07 11:30:32,455 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=Windows7, ip=10.10.10.9)
2020-02-07 11:30:40,480 [cuckoo.core.guest] ERROR: No valid analyzer found at path: /home/cuckoo/.cuckoo/analyzer/Windows
2020-02-07 11:30:40,481 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: No valid analyzer found for Windows platform!
2020-02-07 11:30:40,523 [cuckoo.common.abstracts] DEBUG: Stopping machine Windows7
2020-02-07 11:30:40,524 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7
2020-02-07 11:30:42,185 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7
2020-02-07 11:30:42,296 [cuckoo.core.resultserver] DEBUG: Stopped tracking machine 10.10.10.9 for task #23
2020-02-07 11:30:42,338 [cuckoo.core.scheduler] DEBUG: Released database task #23
2020-02-07 11:30:42,415 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #23
2020-02-07 11:30:42,417 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2020-02-07 11:30:42,418 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #23
2020-02-07 11:30:42,419 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #23
2020-02-07 11:30:42,420 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #23
2020-02-07 11:30:42,422 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #23
2020-02-07 11:30:42,423 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #23
2020-02-07 11:30:42,424 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #23
2020-02-07 11:30:42,425 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #23
2020-02-07 11:30:43,008 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #23
2020-02-07 11:30:43,025 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #23
2020-02-07 11:30:43,035 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #23
2020-02-07 11:30:43,036 [cuckoo.processing.network] WARNING: The PCAP file does not exist at path "/home/cuckoo/.cuckoo/storage/analyses/23/dump.pcap".
2020-02-07 11:30:43,036 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #23
2020-02-07 11:30:43,037 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #23
2020-02-07 11:30:43,037 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #23
2020-02-07 11:30:43,038 [cuckoo.processing.debug] ERROR: Error processing task #23: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2020-02-07 11:30:43,090 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #23
2020-02-07 11:30:43,120 [cuckoo.core.plugins] DEBUG: Running 542 signatures
2020-02-07 11:30:43,384 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2020-02-07 11:30:43,396 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
2020-02-07 11:30:43,396 [cuckoo.core.scheduler] INFO: Task #23: reports generation completed
2020-02-07 11:30:43,405 [cuckoo.core.scheduler] INFO: Task #23: analysis procedure completed
