### ISSUE TITLE
Unable to load the Cuckoo plugin at cuckoo.reporting.mist_json: No module named lib.cuckoo.common.abstracts.

### ISSUE THREAD

**Issue by prantik1995** [cuckoosandbox/cuckoo#2959]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I want to run additional reporting module "mist_json.py" and I placed it on the /cuckoo/cuckoo/reporting/ directory, and also add it to the reporting.conf

While try to start cuckoo, the following error shows....
Traceback (most recent call last):
  File "/tmp/cuckoo-development/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo', 'console_scripts', 'cuckoo')()
  File "/tmp/cuckoo-development/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/cuckoo-development/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/tmp/cuckoo-development/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/tmp/cuckoo-development/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/cuckoo/cuckoo/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/home/cuckoo/cuckoo/cuckoo/reporting/__init__.py", line 10, in <module>
    __file__, "cuckoo.reporting", globals(), Report
  File "/home/cuckoo/cuckoo/cuckoo/core/plugins.py", line 46, in enumerate_plugins
    "review its contents and/or validity!" % (module_name, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at cuckoo.reporting.mist_json: No module named lib.cuckoo.common.abstracts. Please review its contents and/or validity!

**Comment by iMac-Ant18** [comment]
@prantik1995 Hi, I have the same issue. Could I ask you how did you solve?
