### ISSUE TITLE
ERROR: Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by halfliffe** [cuckoosandbox/cuckoo#2963]
I have a problem:

2020-02-18 14:28:53,749 [cuckoo.core.scheduler] DEBUG: Processing task #33
2020-02-18 14:28:53,782 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "NetSpot.exe" (task #33, options "procmemdump=yes,route=none")
2020-02-18 14:28:54,042 [cuckoo.core.scheduler] INFO: Task #33: acquired machine cuckoo1 (label=cuckoo1)
2020-02-18 14:28:54,045 [cuckoo.core.resultserver] DEBUG: Now tracking machine 192.168.1.50 for task #33
2020-02-18 14:28:54,054 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Replay
2020-02-18 14:28:54,135 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 11907 (interface=enp0s3, host=192.168.1.50)
2020-02-18 14:28:54,137 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2020-02-18 14:28:54,229 [cuckoo.machinery.virtualbox] DEBUG: Starting vm cuckoo1
2020-02-18 14:28:54,461 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine cuckoo1 to its current snapshot
2020-02-18 14:28:57,839 [cuckoo.core.guest] INFO: Starting analysis #33 on guest (id=cuckoo1, ip=192.168.1.50)
2020-02-18 14:28:58,849 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2020-02-18 14:28:59,861 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2020-02-18 14:29:00,872 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2020-02-18 14:29:01,884 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2020-02-18 14:29:01,913 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=cuckoo1, ip=192.168.1.50)
2020-02-18 14:29:02,232 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Replay
2020-02-18 14:29:02,235 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2020-02-18 14:29:02,235 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo1
2020-02-18 14:29:03,474 [cuckoo.core.resultserver] DEBUG: Stopped tracking machine 192.168.1.50 for task #33
**2020-02-18 14:29:03,483 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run**
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 541, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 404, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 491, in start_analysis
    self.query_environ()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 364, in query_environ
    self.environ = self.get("/environ").json()["environ"]
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
**ValueError: No JSON object could be decoded**

Test CURL OK:

s@s:~$ curl -vvv 192.168.1.50:8000
* Rebuilt URL to: 192.168.1.50:8000/
*   Trying 192.168.1.50...
* TCP_NODELAY set
* Connected to 192.168.1.50 (192.168.1.50) port 8000 (#0)
> GET / HTTP/1.1
> Host: 192.168.1.50:8000
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: Cuckoo Agent Python/2.7.17
< Date: Tue, 18 Feb 2020 11:37:21 GMT
< 
* Closing connection 0
{"message": "Cuckoo Agent!", "version": "0.10", "features": ["execpy", "pinning", "logs", "largefile", "unicodepath"]}s@s:~$ 

Please, help

**Comment by halfliffe** [comment]
s@s:~$ ls -l ~/.cuckoo/storage/analyses/33/
total 44
lrwxrwxrwx 1 s s   97 фев 18 14:28 binary -> /home/s/.cuckoo/storage/binaries/f938d7b3e0e1a6691cecc5d6eba0a3a2ce3253a7fafe0c4bcf6a8fad3e8f1567
drwxr-sr-x 2 s s 4096 фев 18 14:28 buffer
-rw-r--r-- 1 s s 2928 фев 18 14:29 cuckoo.log
-rw-r--r-- 1 s s  642 фев 18 14:29 dump.pcap
drwxr-sr-x 2 s s 4096 фев 18 14:28 extracted
drwxr-sr-x 2 s s 4096 фев 18 14:28 files
drwxr-sr-x 2 s s 4096 фев 18 14:28 logs
drwxr-sr-x 2 s s 4096 фев 18 14:28 memory
drwxr-sr-x 2 s s 4096 фев 18 14:28 reports
drwxr-sr-x 2 s s 4096 фев 18 14:28 shots
-rw-r--r-- 1 s s  602 фев 18 14:28 task.json
s@s:~$

**Comment by halfliffe** [comment]
And, summary return 404 error (screenshot): [https://ibb.co/dGrg6Kg](url)
