### ISSUE TITLE
Remote Control Error occured

### ISSUE THREAD

**Issue by gmndz90** [cuckoosandbox/cuckoo#2964]
##### My issue is: 
Remote Control(Guacamole) is not working. I keep getting "an error occurred" or a black screen when connected. 

- I enabled the "Remote Control" option in analyze.

-  I disabled "Enable Simulated Human Interaction" before submitting. 

##### My Cuckoo version and operating system are:
Cuckoo:  2.0.7 (Virtual Env)
OS: Ubuntu 16.04
Virtualbox: 6.1.2 w/extension pack
Python: 2.7

##### Troubleshooting Steps:

**1. Installed Extension Pack from Virtualbox**
      - Confirmed it was installed by looking at Tools and Extensions
**2. Installed Guacamole using the following method:**
           _$ sudo apt -y install libcairo2-dev libjpeg-turbo8-dev libpng-dev libossp-uuid-dev libfreerdp 
                             dev
           $ mkdir /tmp/guac-build && cd /tmp/guac-build
           $ wget https://www.apache.org/dist/guacamole/0.9.14/source/guacamole-server- 
                    0.9.14.tar.gz
            $ tar xvf guacamole-server-0.9.14.tar.gz && cd guacamole-server-0.9.14
           $ ./configure --with-init-dir=/etc/init.d
           $ make && sudo make install && cd ..
           $ sudo ldconfig
           $ sudo /etc/init.d/guacd start
**3. Researched and found that there could be a "CSRF Authentication issue". Therefore I followed the steps in "littlejob"'s post https://github.com/cuckoosandbox/cuckoo/issues/2787** : 
           _need to modify this file: /usr/local/lib/python2.7/dist-packages/cuckoo/web/analysis/urls.py

            towards the top add the below underneath from django.conf.urls import url
            from django.views.decorators.csrf import csrf_exempt

           then around line 26ish - comment out url(r"^(?P<task_id>\d+)/control/tunnel/.*", 
           ControlApi.tunnel, name="analysis/control/tunnel"),

           add the following directly below:
           url(r"^(?P<task_id>\d+)/control/tunnel/.*", csrf_exempt(ControlApi.tunnel), 
          name="analysis/control/tunnel"),

          then around line 50ish - comment out url(r"^api/tasks/info/$", AnalysisApi.tasks_info),

          add the following directly below:
          url(r"^api/tasks/info/$", csrf_exempt(AnalysisApi.tasks_info)),_

**Results:**
I am running cuckoo from virtual env. I dont know if Cuckoo 2.0.7 still has this issue but my box does not have a cuckoo folder in " /usr/local/lib/python2.7/dist-packages/". So, I cant modify the  "/usr/local/lib/python2.7/dist-packages/cuckoo/web/analysis/urls.py" since it does not exist in that location. I do have the urls.py in the following location: "/venv/lib/python2.7/site-packages/cuckoo/web/analysis/urls.py". So I performed the changes in that path. Still nothing. 

**4. Confirmed Port binding (look at cuckoo log)**
INFO: Successfully set remote control ports for virtual machine with label Win7_Analysis: 5000-5050

##### Analyzer Log:
[Analyzer.txt](https://github.com/cuckoosandbox/cuckoo/files/4220962/Analyzer.txt)

##### Cuckoo Log:
[Cuckoo.txt](https://github.com/cuckoosandbox/cuckoo/files/4220960/Cuckoo.txt)

**Comment by TylerTenlen** [comment]
Did you find a solution to this? I am having issues getting Guac to work as well. I have made the changes mentioned in step 3 with the "CSRF authentication changes". My tunnel is randomly closing with no error logs

**Comment by harahauk** [comment]
I am seeing this as well. I am on ubuntu 18.04 not using virtualenv, did the modification to the urls.py file. I am wondering if it might be a routing issue.

Seeing this in my syslog:
guacd[23454]: Protocol "rdp" selected                                                                                                                                                                              
guacd[23454]: Connection ID is "$7a9a4d31-f5e2-401f-89c8-8dc11a314802"
guacd[23454]: No security mode specified. Defaulting to RDP.
guacd[23454]: Loading keymap "base"
guacd[23454]: Loading keymap "en-us-qwerty"
guacd[23454]: No available audio encoding. Sound disabled.
guacd[23454]: Starting client
guacd[23454]: guacdr connected.
guacd[23454]: guacsnd connected.
guacd[23454]: Connected to RDPDR 1.12 as client 0x0001 
guacd[23454]: Ignoring server capability set type=0x0001, length=44
guacd[23454]: Ignoring server capability set type=0x0005, length=8
guacd[23454]: Sending capabilities...
guacd[23454]: Capabilities sent.
guacd[23454]: Client ID confirmed
guacd[23453]: Guacamole handshake failed: Timed out
guacd[23454]: Client is not responding.
guacd[23454]: Client disconnected

**Comment by harahauk** [comment]
I am thinking that my problem is that I'm not building the latest guacd from source, so I have something to work on
Also found this

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/analysis/control/api.py", line 73, in tunnel
    return ControlApi._do_write(request, conn)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/analysis/control/api.py", line 203, in _do_write
    guac = sockets[cache_key]
KeyError: 'ac4303f0-044f-42cd-a02c-1dfbb7f2e4b1'

**Comment by harahauk** [comment]
Ok, so I have gotten mostly to the bottom of this as I go. First of the guacd in ubuntu 18.04 seems too old. Compiling version 1.0.0 or the one mentioned in the docs seemed to to the trick on that LTS of ubuntu, but your mileage may vary depending on OS. But the real error seemed to be in my nginx to uwsgi proxying. I advice you to try a supported version of guacd and just try running the dev server "cuckoo web -H 0.0.0.0" to try and see if your issues persist. If they dont you propably have a webserver issue. Hope that helps.

**Comment by TylerTenlen** [comment]
@harahauk  Thanks for looking into this. I will have to give this a try. It has been many months since I have been working on this project however, I have been really wanting to get back into it.

**Comment by harahauk** [comment]
Solved the rest of my problems while also running nginx over https:
https://github.com/cuckoosandbox/cuckoo/issues/2529#issuecomment-444511087

This goes in your uwsgi config:
processes = 1
threads = 4

This goes in your nginx config in the server directive:
uwsgi_buffering off;

Now I have to backtrack if the modded source of urls.py, the custom build of guacamole solved this or all combined. But I have a working automated ansible deployed system somewhat tainted by hacks, but mostly auto-deployed by now =)
