### ISSUE TITLE
 WARNING: win7cuckoo1: analysis #4 caught an exception

### ISSUE THREAD

**Issue by sreemanshanker** [cuckoosandbox/cuckoo#2972]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is: Analyzer module is failing. After running an update earlier yesterday, ive been receiving this issue.
[cuckoofail.txt](https://github.com/cuckoosandbox/cuckoo/files/4286644/cuckoofail.txt)

##### The log, error, files etc can be found at:
2020-03-04 09:51:29,774 [cuckoo.core.guest] WARNING: cuckoo1: analysis #5 caught an exception
Traceback (most recent call last):
  File "C:/tmpa325nf/analyzer.py", line 808, in <module>
    success = analyzer.run()
  File "C:/tmpa325nf/analyzer.py", line 657, in run
    pids = self.package.start(self.target)
  File "C:\tmpa325nf\modules\packages\doc.py", line 72, in start
    word, args=[path], mode="office", trigger="file:%s" % path
  File "C:\tmpa325nf\lib\common\abstracts.py", line 164, in execute
    maximize=maximize, env=env, trigger=trigger):
  File "C:\tmpa325nf\lib\api\process.py", line 338, in execute
    output = subprocess_checkoutput(argv, env)
  File "C:\tmpa325nf\lib\api\process.py", line 105, in subprocess_checkoutput
    args, stdin=subprocess.PIPE, stderr=subprocess.PIPE, env=env,
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
  File "C:\tmpa325nf\lib\api\process.py", line 83, in spCreateProcessW
    raise WindowsError(KERNEL32.GetLastError())
WindowsError: 2

**Comment by RicoVZ** [comment]
Hi sreemanshanker,

Thanks for posting an issue.

Windows error 2 means 'File not found'. I probably cannot find the file to execute.
>  After running an update earlier yesterday

What kind of update?

It looks like somehow the file is being removed before it can be executed. It might be Windows defender on your VM or something else doing this.

**Comment by sreemanshanker** [comment]
Hi Rico,
The file is defintely there. Its a linux box, and ive disable the antivirus as well.
I ran the thing from start to end, and in the logs you can see the file is there, the permissions are for cuckoo and the failure happening.

**Comment by sreemanshanker** [comment]
ive tried reinstalling it, and get hit with the same issue.

no one else facing the same issue? :(

**Comment by 10150042** [comment]
me too.
how can I solve this problem?
Is any idea?
