### ISSUE TITLE
ERROR: Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by xcampax** [cuckoosandbox/cuckoo#2973]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is: ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 541, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 404, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 488, in start_analysis
    self.get("/pinning")
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/guest.py", line 320, in get
    do_raise and r.raise_for_status()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.10:8000/pinning

**Comment by RicoVZ** [comment]
Hi xcampax,

Thanks for posting an issue.

Hmm odd. Can you try the following:

1. Restore the snapshot for this VM manually.
2. Start the VM manually.
3. `curl http://<vm ip>:8000/pinning`
4. Post the output.

**Comment by Al33t** [comment]
Checkout #3105, are those the same conditions?
