### ISSUE TITLE
Internal Server Error (500) while running cuckoo api

### ISSUE THREAD

**Issue by meenabharti** [cuckoosandbox/cuckoo#3000]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:
 
[2020-03-31 18:21:12,872] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/api.py", line 694, in api_auth_required
    401, "Authentication in the form of an "
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/api.py", line 36, in json_error
    r = jsonify(message=message)
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
2020-03-31 18:21:12,873 [werkzeug] INFO: 192.168.100.94 - - [31/Mar/2020 18:21:12] "GET / HTTP/1.1" 500 -

**Comment by mesquidar** [comment]
I had the same problem it seems it is a problem of flask and its dependencies.
I installed a previous version of werkzeug and it seems to work 

pip install werkzeug==0.16.1

Hope it helps

**Comment by hatem2018** [comment]
Hello,
I have the same problem, pip install werkzeug==0.16.1 did not solve my issue. please help -- thank you

2020-04-16 23:02:18,450 [werkzeug] INFO:  * Running on http://localhost:8090/ (P                                                                             ress CTRL+C to quit)
[2020-04-16 23:02:52,844] ERROR in app: Exception on /files/view/sha256/2c2b7dd5                                                                             057c132982102b3017b14ee71471612f3328ba24deec801edc1f3129 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi                                                                             _app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full                                                                             _dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in hand                                                                             le_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in hand                                                                             le_http_exception
    return handler(e)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/api.py", line 694, in                                                                              api_auth_required
    401, "Authentication in the form of an "
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/api.py", line 36, in                                                                              json_error
    r = jsonify(message=message)
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 251, in json                                                                             ify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in                                                                              __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
2020-04-16 23:02:52,846 [werkzeug] INFO: 127.0.0.1 - - [16/Apr/2020 23:02:52] "G                                                                             ET /files/view/sha256/2c2b7dd5057c132982102b3017b14ee71471612f3328ba24deec801edc                                                                             1f3129 HTTP/1.1" 500 -

**Comment by mesquidar** [comment]
> 
> 
> Hello,
> I have the same problem, pip install werkzeug==0.16.1 did not solve my issue. please help -- thank you
> 
> 2020-04-16 23:02:18,450 [werkzeug] INFO: * Running on http://localhost:8090/ (P ress CTRL+C to quit)
> [2020-04-16 23:02:52,844] ERROR in app: Exception on /files/view/sha256/2c2b7dd5 057c132982102b3017b14ee71471612f3328ba24deec801edc1f3129 [GET]
> Traceback (most recent call last):
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi _app
> response = self.full_dispatch_request()
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full _dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in hand le_user_exception
> return self.handle_http_exception(e)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in hand le_http_exception
> return handler(e)
> File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/api.py", line 694, in api_auth_required
> 401, "Authentication in the form of an "
> File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/api.py", line 36, in json_error
> r = jsonify(message=message)
> File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 251, in json ify
> if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
> File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in **getattr**
> return getattr(self._get_current_object(), name)
> AttributeError: 'Request' object has no attribute 'is_xhr'
> 2020-04-16 23:02:52,846 [werkzeug] INFO: 127.0.0.1 - - [16/Apr/2020 23:02:52] "G ET /files/view/sha256/2c2b7dd5057c132982102b3017b14ee71471612f3328ba24deec801edc 1f3129 HTTP/1.1" 500 -

Hello, check your flask version is 0.12.2 and then install werkzeug 0.16.1
Hope it helps

**Comment by hatem2018** [comment]
Hello, thanks for your reply but unfortunately this did not solve the problem, i have this two version for flask (0.12.2) and i reinstalled werkzeug with 0.16.1 version (even old one i tried to install it but the same issue), i also tried cuckoo venv installation and global installation (both same result) :(
I am using OS ubuntu 18.04 and Cuckoo 2.0.7
it's possible to downgrade cuckoo to 2.0.6 without problem to avoid this incompatibility ?   
your advice is most welcome. thanks a lot

**Comment by hatem2018** [comment]
Thanks it solved my issue, when i installed werkzeug with 0.16.1 version in cuckoo user profil

**Comment by XhstormR** [comment]
I have the same problem

**Comment by XhstormR** [comment]
see https://github.com/pallets/flask/issues/2549

**Comment by nadir3392** [comment]
hi guys, my cuckoo 2.07 os ubuntu 16.04
i have this error after running : cuckoo api 192.168.42.14:1337
------------------------------
{
  "message": "Authentication in the form of an 'Authorization: Bearer <TOKEN>' header is required"
}
---------------------------
can you help me
