### ISSUE TITLE
Cuckoo installed but not run

### ISSUE THREAD

**Issue by harelber** [cuckoosandbox/cuckoo#3034]
My issue is: Can't run cuckoo. It's stuck before running.

My Cuckoo version and operating system are: the latest cuckoo version, the OS is ubuntu 16.04

The log, error, files etc can be found at: the following lines:

Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 5, in <module>
    from cuckoo.main import main
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/__init__.py", line 10, in <module>
    __file__, "cuckoo.processing", globals(), Processing
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 46, in enumerate_plugins
    "review its contents and/or validity!" % (module_name, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at cuckoo.processing.procmemory: cannot import name XOR. Please review its contents and/or validity!

**Comment by jhelmsen** [comment]
harelber,

My group is having the same issue with Cuckoo.  Did you ever find a fix for this problem?

Helmsen
