### ISSUE TITLE
Cannot submit exe nor zip files for analysis

### ISSUE THREAD

**Issue by fyoozr** [cuckoosandbox/cuckoo#3045]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I cannot submit "exe" nor "zip" file for analysis while the other files like pdf, docx, xlsx, works fine.
##### My Cuckoo version and operating system are:
Cuckoo 2.0.7
Ubuntu 16.04.6 LTS
##### This can be reproduced by:
By Submitting a file for analysis.
##### The log, error, files etc can be found at:
[02/Jun/2020 15:47:05] "GET /cuckoo/api/status HTTP/1.1" 200 1779
2020-06-02 15:47:13,617 [django.request] ERROR: Internal Server Error: /submit/api/presubmit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/submission/api.py", line 65, in presubmit
    body = json.loads(request.body)
  File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 231, in body
    raise RawPostDataException("You cannot access body after reading from request's data stream")
RawPostDataException: You cannot access body after reading from request's data stream
2020-06-02 15:47:13,617 [django.request] ERROR: Internal Server Error: /submit/api/presubmit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/submission/api.py", line 65, in presubmit
    body = json.loads(request.body)
  File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 231, in body
    raise RawPostDataException("You cannot access body after reading from request's data stream")
RawPostDataException: You cannot access body after reading from request's data stream
[02/Jun/2020 15:47:13] "POST /submit/api/presubmit/ HTTP/1.1" 500 13173

**Comment by ByamB4** [comment]
Suspecious, Have you tried submit files from your **CLI**  [more](https://cuckoo.readthedocs.io/en/latest/usage/submit/)

**Comment by fyoozr** [comment]
@ByamB4 Thank for your reply. Is seems that it works from CLI. The exe file was analyzed without issues.

**Comment by fyoozr** [comment]
Ok, CLI is fine but I need this to work from the GUI as not everyone has CLI access.
