### ISSUE TITLE
Oops! Cuckoo failed in an unhandled exception! Using "virtualbox" as machine manager

### ISSUE THREAD

**Issue by ramadhanbeno** [cuckoosandbox/cuckoo#3049]
I get an error when running cuckoo -d on venv, at the end of the line displays the message AttributeError: 'NoneType' object has no attribute 'shutdown'. can anyone solve this problem?

Cuckoo V2.0.7 on ubuntu 18.04 bionic

------------------------------------------------------------------------------------------------------------------------------------
[cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.7
OS version: posix
OS release: Ubuntu 18.04 bionic
Python version: 2.7.17
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:1.0.10 androguard:3.0.1 argparse:1.2.1 attrs:19.3.0 beautifulsoup4:4.5.3 capstone:3.0.5rc2 cffi:1.14.0 chardet:2.3.0 click:6.6 colorama:0.3.7 configparser:4.0.2 contextlib2:0.6.0.post1 cryptography:2.9.2 cuckoo:2.0.7 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.15 egghatch:0.2.3 elasticsearch:5.3.0 enum34:1.1.10 flask-sqlalchemy:2.4.0 flask:0.12.2 functools32:3.2.3.post2 future:0.18.2 gevent:1.2.2 greenlet:0.4.16 httpreplay:0.2.6 idna:2.9 importlib-metadata:1.6.1 ipaddress:1.0.23 itsdangerous:1.1.0 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:3.2.0 libvirt-python:5.3.0 mako:1.1.3 markupsafe:1.1.1 olefile:0.43 oletools:0.51 pathlib2:2.3.5 peepdf:0.4.2 pefile2:1.2.11 pillow:3.2.0 pip:20.1.1 pkg-resources:0.0.0 pycparser:2.20 pycrypto:2.6.1 pyelftools:0.24 pyguacamole:0.6 pymisp:2.4.106 pymongo:3.0.3 pyopenssl:19.1.0 pyrsistent:0.16.0 python-dateutil:2.4.2 python-editor:1.0.4 python-magic:0.4.12 python:2.7.17 pythonaes:1.0 pyvmomi:7.0 requests:2.13.0 roach:0.1.2 scandir:1.10.0 scapy:2.3.2 setuptools:44.1.1 sflock:0.3.10 six:1.15.0 sqlalchemy:1.3.3 tlslite-ng:0.6.0 unicorn:1.0.1 urllib3:1.25.9 wakeonlan:0.2.2 werkzeug:1.0.1 wheel:0.34.2 wsgiref:0.1.2 yara-python:3.6.3 zipp:1.2.0

2020-06-10 22:51:07,339 [cuckoo] ERROR: AttributeError: 'NoneType' object has no attribute 'shutdown'
Traceback (most recent call last):
  File "/home/x/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 298, in main
    cuckoo_main(maxcount)
  File "/home/x/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 248, in cuckoo_main
    stop()
  File "/home/x/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 231, in stop
    sched.stop()
  File "/home/x/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 945, in stop
    machinery.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'

**Comment by botherder** [comment]
What virtualization option did you configure? Would you be able to share the relevant config entries?

**Comment by ramadhanbeno** [comment]
thank you for your reply, I use Windows7 SP1 virtual machine with python 2.7.18
for configuration as below.
[virtualbox.conf.txt](https://github.com/cuckoosandbox/cuckoo/files/4767926/virtualbox.conf.txt)
[cuckoo.conf.txt](https://github.com/cuckoosandbox/cuckoo/files/4767928/cuckoo.conf.txt)

**Comment by M1dor1ya** [comment]
I have met the same exception

2020-06-18 01:47:33,146 [cuckoo.core.scheduler] INFO: Using "kvm" as machine manager
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.7
OS version: posix
OS release: Ubuntu 18.04 bionic
Python version: 2.7.17
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:1.0.10 androguard:3.0.1 argparse:1.2.1 attrs:19.3.0 beautifulsoup4:4.5.3 capstone:3.0.5rc2 cffi:1.14.0 chardet:2.3.0 click:6.6 colorama:0.3.7 configparser:4.0.2 contextlib2:0.6.0.post1 cryptography:2.9.2 cuckoo:2.0.7 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.15 egghatch:0.2.3 elasticsearch:5.3.0 enum34:1.1.10 flask-sqlalchemy:2.4.0 flask:0.12.2 functools32:3.2.3.post2 future:0.18.2 gevent:1.2.2 greenlet:0.4.16 httpreplay:0.2.6 idna:2.9 importlib-metadata:1.6.1 ipaddress:1.0.23 itsdangerous:1.1.0 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:3.2.0 mako:1.1.3 markupsafe:1.1.1 olefile:0.43 oletools:0.51 pathlib2:2.3.5 peepdf:0.4.2 pefile2:1.2.11 pillow:3.2.0 pip:20.1.1 pkg-resources:0.0.0 psycopg2:2.8.5 pycparser:2.20 pycrypto:2.6.1 pyelftools:0.24 pyftpdlib:1.5.6 pyguacamole:0.6 pymisp:2.4.106 pymongo:3.0.3 pyopenssl:19.1.0 pyrsistent:0.16.0 python-dateutil:2.4.2 python-editor:1.0.4 python-magic:0.4.12 python:2.7.17 pythonaes:1.0 requests:2.13.0 roach:0.1.2 scandir:1.10.0 scapy:2.3.2 setuptools:44.1.1 sflock:0.3.10 six:1.15.0 sqlalchemy:1.3.3 tlslite-ng:0.6.0 unicorn:1.0.1 urllib3:1.25.9 wakeonlan:0.2.2 werkzeug:1.0.1 wheel:0.34.2 wsgiref:0.1.2 yara-python:3.6.3 zipp:1.2.0

2020-06-18 01:47:33,374 [cuckoo] ERROR: AttributeError: 'NoneType' object has no attribute 'shutdown'
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 298, in main
    cuckoo_main(maxcount)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 248, in cuckoo_main
    stop()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/main.py", line 231, in stop
    sched.stop()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/scheduler.py", line 945, in stop
    machinery.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'

**Comment by 1llusionary** [comment]
I have fixed this.You can check this issue:[https://github.com/cuckoosandbox/cuckoo/issues/2867](url)
