### ISSUE TITLE
POST error for http://192.168.101.133:8000/mkdtemp on OSX

### ISSUE THREAD

**Issue by KraneBrain** [cuckoosandbox/cuckoo#3055]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are: 2.0.7 with host and guest as OSX

The below is the error I'm seeing for cuckoo on OSX (guest and host). I am using vmnet1 as my interface in vmware. The guest OSX account is administrator and I've tried running the agent as root and not root. Sometimes the error does not occur and it just never escapes the python command "r = session.post(url, *args, **kwargs)" inside cuckoo/core/guest.py inside the function "    def post(self, method, *args, **kwargs):"

It seems OSX is less popular of the cuckoo OSs but I'd appreciate any help.

2020-06-23 12:48:08,073 [cuckoo.core.scheduler] INFO: Using "vmware" as machine manager
2020-06-23 12:48:08,313 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2020-06-23 12:48:08,321 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2020-06-23 12:48:14,461 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "EAPOLController" (task #111, options "")
2020-06-23 12:48:14,483 [cuckoo.core.scheduler] INFO: Task #111: acquired machine cuckoo1 (label=/Users/X/Virtual Machines.localized/cuckoo1.vmwarevm/cuckoo1.vmx)
2020-06-23 12:48:14,506 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 5966 (interface=vmnet1, host=192.168.101.133)
2020-06-23 12:48:22,987 [cuckoo.core.guest] INFO: Starting analysis #111 on guest (id=cuckoo1, ip=192.168.101.133)
2020-06-23 12:48:23,395 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=cuckoo1, ip=192.168.101.133)
2020-06-23 12:48:24,179 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/Users/X/Library/Python/2.7/lib/python/site-packages/cuckoo/core/scheduler.py", line 755, in run
    self.launch_analysis()
  File "/Users/X/Library/Python/2.7/lib/python/site-packages/cuckoo/core/scheduler.py", line 541, in launch_analysis
    self.guest_manage(options)
  File "/Users/X/Library/Python/2.7/lib/python/site-packages/cuckoo/core/scheduler.py", line 404, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/Users/X/Library/Python/2.7/lib/python/site-packages/cuckoo/core/guest.py", line 502, in start_analysis
    self.upload_analyzer(monitor)
  File "/Users/X/Library/Python/2.7/lib/python/site-packages/cuckoo/core/guest.py", line 406, in upload_analyzer
    self.determine_analyzer_path()
  File "/Users/X/Library/Python/2.7/lib/python/site-packages/cuckoo/core/guest.py", line 382, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/Users/X/Library/Python/2.7/lib/python/site-packages/cuckoo/core/guest.py", line 343, in post
    r.raise_for_status()
  File "/Users/X/Library/Python/2.7/lib/python/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.101.133:8000/mkdtemp

**Comment by KraneBrain** [comment]
This issue is due to the guest.py using "/" as the directory. So either change guest.py function "determine_system_drive(self):" to return "/Users/YourUser" or run "sudo mount -uw /" inside the guest before the snapshot.

Be sure to install pymongo on the guest. Now i'm dealing with a broken pipe issue 

2020-06-24 16:05:57,597 [root] DEBUG: Starting analyzer from /tmp1hpnEc
2020-06-24 16:05:57,598 [root] DEBUG: Storing results at: /tmp/cYhtgwjx
2020-06-24 16:05:44,049 [modules.auxiliary.screenshots] WARNING: Python Image Library is not installed, screenshots are disabled
2020-06-24 16:05:44,049 [analyzer] DEBUG: Started auxiliary module Screenshots
2020-06-24 16:06:15,954 [root] ERROR: Traceback (most recent call last):
  File "/tmp1hpnEc/analyzer.py", line 204, in <module>
    success = analyzer.run()
  File "/tmp1hpnEc/analyzer.py", line 95, in run
    self._analysis(package)
  File "/tmp1hpnEc/analyzer.py", line 147, in _analysis
    package.start()
  File "/tmp1hpnEc/lib/core/packages.py", line 95, in start
    self.apicalls_analysis()
  File "/tmp1hpnEc/lib/core/packages.py", line 107, in apicalls_analysis
    self.host.send_api(call)
  File "/tmp1hpnEc/lib/core/host.py", line 86, in send_api
    "args" : self._prepare_args(thing)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/tmp1hpnEc/analyzer.py", line 204, in <module>
    success = analyzer.run()
  File "/tmp1hpnEc/analyzer.py", line 95, in run
    self._analysis(package)
  File "/tmp1hpnEc/analyzer.py", line 147, in _analysis
    package.start()
  File "/tmp1hpnEc/lib/core/packages.py", line 95, in start
    self.apicalls_analysis()
  File "/tmp1hpnEc/lib/core/packages.py", line 107, in apicalls_analysis
    self.host.send_api(call)
  File "/tmp1hpnEc/lib/core/host.py", line 86, in send_api
    "args" : self._prepare_args(thing)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe

**Comment by cc-sir** [comment]
I have the same issue: error: [Errno 32] Broken pipe:
```
2020-08-10 14:18:54,385 [root] DEBUG: Starting analyzer from /tmpY8ddwO
2020-08-10 14:18:54,385 [root] DEBUG: Storing results at: /tmp/WKHcjxeGiN
2020-08-10 15:37:36,036 [modules.auxiliary.screenshots] WARNING: Python Image Library is not installed, screenshots are disabled
2020-08-10 15:37:36,036 [analyzer] DEBUG: Started auxiliary module Screenshots
2020-08-10 15:37:59,430 [root] ERROR: Traceback (most recent call last):
  File "/tmpY8ddwO/analyzer.py", line 193, in <module>
    success = analyzer.run()
  File "/tmpY8ddwO/analyzer.py", line 95, in run
    self._analysis(package)
  File "/tmpY8ddwO/analyzer.py", line 136, in _analysis
    package.start()
  File "/tmpY8ddwO/lib/core/packages.py", line 95, in start
    self.apicalls_analysis()
  File "/tmpY8ddwO/lib/core/packages.py", line 107, in apicalls_analysis
    self.host.send_api(call)
  File "/tmpY8ddwO/lib/core/host.py", line 59, in send_api
    self._send_new_process(thing)
  File "/tmpY8ddwO/lib/core/host.py", line 176, in _send_new_process
    module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/tmpY8ddwO/analyzer.py", line 193, in <module>
    success = analyzer.run()
  File "/tmpY8ddwO/analyzer.py", line 95, in run
    self._analysis(package)
  File "/tmpY8ddwO/analyzer.py", line 136, in _analysis
    package.start()
  File "/tmpY8ddwO/lib/core/packages.py", line 95, in start
    self.apicalls_analysis()
  File "/tmpY8ddwO/lib/core/packages.py", line 107, in apicalls_analysis
    self.host.send_api(call)
  File "/tmpY8ddwO/lib/core/host.py", line 59, in send_api
    self._send_new_process(thing)
  File "/tmpY8ddwO/lib/core/host.py", line 176, in _send_new_process
    module
  File "/System/Library/Frameworks/Python.framework/Version
```
Did you solve it, thanks!
