### ISSUE TITLE
Unable to create or connect to database: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by ImOxygen233** [cuckoosandbox/cuckoo#3071]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html
Yes
##### My issue is:
I can't run cuckoo web server,it says"Unable to create or connect to database: (sqlite3.OperationalError) unable to open database file"

##### My Cuckoo version and operating system are:
Cuckoo:2.07 System:Ubuntu 20.04 LTS Desktop

##### The log, error, files etc can be found at:
![image](https://user-images.githubusercontent.com/51868343/87220516-fb7ceb00-c396-11ea-9c81-c892530d8f1e.png)

**Comment by ImOxygen233** [comment]
I 'm already set up MongoDB and MySQL（SQLite also）,but it still doesn't work

**Comment by ImOxygen233** [comment]
I run this command "cuckoo -d" and get:
`2020-07-11 17:04:35,121 [cuckoo] CRITICAL: CuckooDependencyError: Missing MySQL database driver (install with `pip install mysql-python` on Linux or `pip install mysqlclient` on Windows)`

**Comment by ImOxygen233** [comment]
But I can't use pip to install it

![image](https://user-images.githubusercontent.com/51868343/87220738-17818c00-c399-11ea-9b10-5c92c7bca3f3.png)

**Comment by ImOxygen233** [comment]
Re:I run web server successful,but cuckoo doesn't work

```
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.7
OS version: posix
OS release: Ubuntu 20.04 focal
Python version: 2.7.18rc1
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:1.0.10 androguard:3.0.1 appdirs:1.4.4 argparse:1.2.1 attrs:19.3.0 beautifulsoup4:4.5.3 bottle:0.12.18 capstone:3.0.5rc2 cffi:1.14.0 chardet:2.3.0 click:6.6 colorama:0.3.7 configparser:4.0.2 contextlib2:0.6.0.post1 cryptography:2.9.2 cuckoo:2.0.7 distlib:0.3.0 distorm3:3.4.4 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.15 egghatch:0.2.3 elasticsearch:5.3.0 enum34:1.1.10 et-xmlfile:1.0.1 filelock:3.0.12 flask-sqlalchemy:2.4.0 flask:0.12.2 functools32:3.2.3.post2 future:0.18.2 gevent:1.2.2 greenlet:0.4.16 httpreplay:0.2.6 idna:2.9 importlib-metadata:1.7.0 importlib-resources:2.0.1 install:1.3.0 ipaddress:1.0.23 itsdangerous:1.1.0 jdcal:1.4.1 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:3.2.0 mako:1.1.3 markupsafe:1.1.1 mysql-python:1.2.5 olefile:0.43 oletools:0.51 openpyxl:2.6.4 pathlib2:2.3.5 peepdf:0.4.2 pefile2:1.2.11 pefile:2019.4.18 pillow:3.2.0 pip:20.1.1 pycparser:2.20 pycrypto:2.6.1 pydeep:0.4 pyelftools:0.24 pyguacamole:0.6 pymisp:2.4.106 pymongo:3.0.3 pyopenssl:19.1.0 pyrsistent:0.16.0 python-dateutil:2.4.2 python-editor:1.0.4 python-magic:0.4.12 python:2.7.18rc1 pythonaes:1.0 pytz:2020.1 requests:2.13.0 roach:0.1.2 scandir:1.10.0 scapy:2.3.2 setuptools:44.1.1 sflock:0.3.10 singledispatch:3.4.0.3 six:1.15.0 sqlalchemy:1.3.3 tlslite-ng:0.6.0 typing:3.7.4.1 ujson:2.0.3 unicorn:1.0.1 urllib3:1.25.9 vboxapi:1.0 virtualenv:20.0.25 volatility:2.6.1 wakeonlan:0.2.2 werkzeug:1.0.1 wheel:0.34.2 wsgiref:0.1.2 yara-python:3.6.3 yara:1.7.7 zipp:1.2.0

2020-07-11 19:11:39,921 [cuckoo] ERROR: AttributeError: Rules instance has no attribute 'save'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 297, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 192, in cuckoo_init
    init_yara()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 358, in init_yara
    File.yara_rules["dumpmem"].save(cwd("stuff", "dumpmem.yarac"))
AttributeError: Rules instance has no attribute 'save'
iscro@ISCRO-Server-Jiangsu1:~/guacamole-server-1.1.0$ 


```
