### ISSUE TITLE
ERROR: Failed to run the processing module "Suricata"

### ISSUE THREAD

**Issue by SomeDunes** [cuckoosandbox/cuckoo#3073]
##### My issue is: 
After basic setup of suricata verified by:
suricata -c /etc/suricata/suricata.yaml -r /opt/cuckoo/storage/analyses/1/dump.pcap -v
That outputed result correctly.

I tryed setup suricata inside analyse but with error that I dont know how to debug further.

Cuckoo log provide me this :

2020-07-14 12:12:41,264 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Suricata" for task #1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 246, in process
    data = current.run()
  File "/usr/lib/python2.7/site-packages/cuckoo/processing/suricata.py", line 288, in run
    self.parse_eve_json()
  File "/usr/lib/python2.7/site-packages/cuckoo/processing/suricata.py", line 125, in parse_eve_json
    event = json.loads(line)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Based on this I assumed some kind of a problem with logging results into results folder of analyses. Cat on fast.log looks like this:

07/14/2020-14:36:02.772568  [**] [1:2210054:1] SURICATA STREAM excessive retransmissions [**] [Classification: Generic Protocol Command Decode] [Priority: 3] {TCP} 8.152.225.213:80 -> 10.0.0.1:49353

stats.log is also full of data. But file "eve.json" mentioned in python error is empty. 

Can somone help me with debuging on this further?

##### My Cuckoo version and operating system are:
Cuckoo version: 2.0.7
OS: CentOS Linux release 7.8.2003 (Core)

##### This can be reproduced by:
Reproducing by instaling cuckoo sandbox and suricata. Than setup suricata as basic as possible and maybe you will get same error.

**Comment by SomeDunes** [comment]
So after discussion on slack with two experienced members. I managed to execute suricata analyses. 

I can recommend this (already recomended) webinar for install and setup guide:
https://www.youtube.com/watch?v=Ru1jvx-6SbI

Based on my changes after watching this webinar. I changed eve.log location back to default at processing.conf:
[suricata]
eve_log =  eve.json

Also proper done suricata-update is needed. I found out some problems with rights in /tmp folder.
I recommend running suricata-update as cuckoo user and debug. It should be all fine than.
