### ISSUE TITLE
WindowsError: 225

### ISSUE THREAD

**Issue by Niatruc** [cuckoosandbox/cuckoo#3096]
##### My issue is:
My cuckoo log was shown as below and I cannot find any posted issue similar to what i have encountered. Any suggestion?

2020-09-04 10:10:47,379 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "a2p.exe" (task #8, options "procmemdump=yes,route=none")
2020-09-04 10:10:47,444 [cuckoo.core.scheduler] INFO: Task #8: acquired machine win10_vbox (label=win10_vbox)
2020-09-04 10:10:47,455 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 14329 (interface=vboxnet0, host=192.168.56.3)
2020-09-04 10:10:55,161 [cuckoo.core.guest] INFO: Starting analysis #8 on guest (id=win10_vbox, ip=192.168.56.3)
2020-09-04 10:10:58,181 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=win10_vbox, ip=192.168.56.3)
2020-09-04 10:11:07,801 [cuckoo.core.guest] WARNING: win10_vbox: analysis #8 caught an exception
Traceback (most recent call last):
  File "C:/tmpqdutwo/analyzer.py", line 808, in <module>
    success = analyzer.run()
  File "C:/tmpqdutwo/analyzer.py", line 657, in run
    pids = self.package.start(self.target)
  File "C:\tmpqdutwo\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmpqdutwo\lib\common\abstracts.py", line 164, in execute
    maximize=maximize, env=env, trigger=trigger):
  File "C:\tmpqdutwo\lib\api\process.py", line 338, in execute
    output = subprocess_checkoutput(argv, env)
  File "C:\tmpqdutwo\lib\api\process.py", line 105, in subprocess_checkoutput
    args, stdin=subprocess.PIPE, stderr=subprocess.PIPE, env=env,
  File "C:\Python27\lib\subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
  File "C:\tmpqdutwo\lib\api\process.py", line 83, in spCreateProcessW
    raise WindowsError(KERNEL32.GetLastError())
WindowsError: 225

2020-09-04 10:11:11,749 [cuckoo.core.scheduler] INFO: Task #8: reports generation completed
2020-09-04 10:11:11,759 [cuckoo.core.scheduler] INFO: Task #8: analysis procedure completed
##### My Cuckoo version and operating system are:
cuckoo version: 2.0.7
host: ubuntu 18
guest: window 10

**Comment by D3rpyCat** [comment]
Hi,
I looked up System Error Codes in the official Microsoft documentation and I found that the error code 225 means "ERROR_VIRUS_INFECTED" so you have to make sure that your AV is down before running an analysis with Cuckoo.
Link to the Microsoft docs : https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

**Comment by Niatruc** [comment]
> Hi,
> I looked up System Error Codes in the official Microsoft documentation and I found that the error code 225 means "ERROR_VIRUS_INFECTED" so you have to make sure that your AV is down before running an analysis with Cuckoo.
> Link to the Microsoft docs : https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

@D3rpyCat Thanks for your suggestion！Actually I have toggle my guests’os to Windows7 and then this error disappeared (for the same PE file sample). But thanks for your point to my issue!

**Comment by Niatruc** [comment]
> Hello,
> i have exactly the same issue with my Windows 10 Guest Machine. I have already deactivated Windows Defender, but it doesn't work.

Have you ever tried a Windows 7 Guest Machine? I found no solution on the internet and then turned to a Win7 guest, and this error does not showed up anymore.

**Comment by secTube91** [comment]
Hello Niatruc,
of course it works with a Windows 7 Guest. However i would like to set up an analysis environment with Windows 7 and Windows 10. In April 2020 i had no problems to install Windows 10 as guest. It's may possible that Microsoft made some changes in newer Windows 10 versions.

**Comment by secTube91** [comment]
Hello Niatruc,
i was able to solve the problem. The problem was indeed the AntiVirus. 
I had deactivated it, but i didn't noticed, that it was enabled again after i restarted the machine.
After I switched the Microsofts Real-time protection off again, the analysis worked successfully.
Best regards,
Mario

**Comment by Niatruc** [comment]
> Hello Niatruc,
> i was able to solve the problem. The problem was indeed the AntiVirus.
> I had deactivated it, but i didn't noticed, that it was enabled again after i restarted the machine.
> After I switched the Microsofts Real-time protection off again, the analysis worked successfully.
> Best regards,
> Mario

That's great! Seems I should retry to solve my Win10 guest problem...
