### ISSUE TITLE
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at cuckoo.processing.procmemory: cannot import name RSAImplementation. Please review its contents and/or validity!

### ISSUE THREAD

**Issue by zsdostar** [cuckoosandbox/cuckoo#3104]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at cuckoo.processing.procmemory: cannot import name RSAImplementation. Please review its contents and/or validity!

##### My Cuckoo version and operating system are:
```shell
[root@localhost src]# pip freeze | grep Cuckoo
Cuckoo==2.0.7

[root@localhost src]# python --version
Python 2.7.5

[root@localhost src]# uname -a
Linux localhost 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost src]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

```
##### This can be reproduced by:
```shell
[root@localhost src]# cuckoo
/usr/lib/python2.7/site-packages/sflock/decode/office.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
  File "/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.7', 'console_scripts', 'cuckoo')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/lib/python2.7/site-packages/cuckoo/processing/__init__.py", line 10, in <module>
    __file__, "cuckoo.processing", globals(), Processing
  File "/usr/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 46, in enumerate_plugins
    "review its contents and/or validity!" % (module_name, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at cuckoo.processing.procmemory: cannot import name RSAImplementation. Please review its contents and/or validity!

```
##### The log, error, files etc can be found at:
the console output

**Comment by zsdostar** [comment]
When I switched to cuckoo==2.0.5, no this error appeared

**Comment by zsdostar** [comment]
And pip version update to 20, make another error

so pip version may need to keep ==9.x.y
