### ISSUE TITLE
cuckoo] ERROR: AttributeError: 'NoneType' object has no attribute 'shutdown'

### ISSUE THREAD

**Issue by Viper727** [cuckoosandbox/cuckoo#3198]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
[cuckoo] ERROR: AttributeError: 'NoneType' object has no attribute 'shutdown'
##### My Cuckoo version and operating system are:
2021-04-20 14:57:44,219 [cuckoo.core.scheduler] INFO: Using "vsphere" as machine manager
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.7
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: i686
Modules: adium-theme-ubuntu:0.3.4 alembic:1.0.10 androguard:3.0.1 argparse:1.2.1 attrs:20.2.0 beautifulsoup4:4.5.3 capstone:3.0.5rc2 certifi:2020.6.20 cffi:1.14.2 chardet:2.3.0 click:6.6 colorama:0.3.7 configparser:4.0.2 contextlib2:0.6.0.post1 crypto:1.4.1 cryptography:3.1 cuckoo:2.0.7 distorm3:3.5.0 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.16.0 egghatch:0.2.3 elasticsearch:5.3.0 enum34:1.1.10 flask-sqlalchemy:2.4.0 flask:0.12.2 functools32:3.2.3.post2 future:0.18.2 gevent:1.2.2 greenlet:0.4.16 httpreplay:0.2.6 idna:2.10 importlib-metadata:1.7.0 ipaddress:1.0.23 itsdangerous:1.1.0 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:3.2.0 m2.6.20 cffi:1.14.2 chardet:2.3.0 click:6.6 colorama:0.3.7 configparser:4.0.2 contextlib2:0.6.0.post1 crypto:1.4.1 cryptography:3.1 cuckoo:2.0.7 distorm3:3.5.0 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.16.0 egghatch:0.2.3 elasticsearch:5.3.0 enum34:1.1.10 flask-sqlalchemy:2.4.0 flask:0.12.2 functools32:3.2.3.post2 future:0.18.2 gevent:1.2.2 greenlet:0.4.16 httpreplcrypto:0.24.0 mako:1.1.3 markupsafe:1.1.1 naked:0.1.31 olefile:0.43 oletools:0.51 pathlib2:2.3.5 peepdf:0.4.2 pefile2:1.2.11 pillow:3.2.0 pip:20.3.4 pycparser:2.20 pycrypto:2.6.1 pydeep:0.4 pyelftools:0.24 pyguacamole:0.6 pymisp:2.4.106 pymongo:3.0.3 pyopenssl:19.1.0 pyrsistent:0.16.1 python-dateutil:2.4.2 python-editor:1.0.4 python-magic:0.4.12 python:2.7.12 pythonaes:1.0 pyyaml:5.3.1 requests:2.13.0 roach:0.1.2 scandir:1.10.0 scapy:2.3.2 setuptools:44.1.1 sflock:0.3.10 shellescape:3.8.1 six:1.15.0 sqlalchemy:1.3.3 tlslite-ng:0.6.0 unicorn:1.0.1 unity-lens-photos:1.0 urllib3:1.25.10 volatility:2.6.1 wakeonlan:0.2.2 werkzeug:1.0.1 wsgiref:0.1.2 yara-python:3.6.3 zipp:1.2.0

##### The log, error, files etc can be found at:
2021-04-20 14:57:44,347 [cuckoo] ERROR: AttributeError: 'NoneType' object has no attribute 'shutdown'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 298, in main
    cuckoo_main(maxcount)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 248, in cuckoo_main
    stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 231, in stop
    sched.stop()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 945, in stop
    machinery.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'

**Comment by Viper727** [comment]
pip install -U pyvmomi solved the issue.
