### ISSUE TITLE
Volatility: Generic error excuting volatility

### ISSUE THREAD

**Issue by teknition** [cuckoosandbox/cuckoo#429]
I thought I configured it correctly, this error would say otherwise. Before installing Volatility, I installed the dependencies, Distorm3, Yara, Yara-python, PyCrypto, PIL, and GMP.

the error happens on different lines no matter what modules I enable or disable. The only error in common is line 830, which is the vol.run()

2014-12-24 10:24:33,816 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/opt/cuckoo/modules/processing/memory.py", line 830, in run
    results = vol.run()
  File "/opt/cuckoo/modules/processing/memory.py", line 748, in run
    results["callbacks"] = vol.callbacks()
  File "/opt/cuckoo/modules/processing/memory.py", line 150, in callbacks
    module = tasks.find_module(mods, mod_addrs, command.kern_space.address_mask(cb))
AttributeError: 'Callbacks' object has no attribute 'kern_space'

**Comment by mmcduffie1** [comment]
I can't find a solution for this. It seems volatility is either ahead or behind cuckoo.

2015-07-21 18:28:46,251 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/home/john/cuckoo/modules/processing/memory.py", line 960, in run
    results = VolatilityManager(self.memory_path).run()
  File "/home/john/cuckoo/modules/processing/memory.py", line 895, in run
    vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/home/john/cuckoo/modules/processing/memory.py", line 50, in __init__
    self.init_config()
  File "/home/john/cuckoo/modules/processing/memory.py", line 106, in init_config
    if self.get_dtb():
  File "/home/john/cuckoo/modules/processing/memory.py", line 56, in get_dtb
    for ep in ps.calculate():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.4-py2.7.egg/volatility/plugins/filescan.py", line 356, in calculate
    addr_space = utils.load_as(self._config, astype = 'physical')
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.4-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 FileAddressSpace: Invalid profile WinXPx86 selected
 ArmAddressSpace: No base Address Space

**Comment by tvashish** [comment]
Do we have any solution for @mmcduffie1 problem?
