### ISSUE TITLE
Analysis not starting on Proxmox KVM

### ISSUE THREAD

**Issue by tysonmax20042003** [cuckoosandbox/cuckoo#519]
Hello,

I think I have the same issue as: Network Analysis failure #494.
On current build and on Ubuntu 14.10 Server. All parts of Cuckoo works but no PCAP files. Storage folder has full permissions. 

2015-04-10 14:27:01,488 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" on analysis at "/home/cuckoo/bin/cuckoo/storage/analyses/20"
2015-04-10 14:27:01,489 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "NetworkAnalysis":
Traceback (most recent call last):
  File "/home/cuckoo/bin/cuckoo/lib/cuckoo/core/plugins.py", line 186, in process
    data = current.run()
  File "/home/cuckoo/bin/cuckoo/modules/processing/network.py", line 593, in run
    sort_pcap(self.pcap_path, sorted_path)
  File "/home/cuckoo/bin/cuckoo/modules/processing/network.py", line 708, in sort_pcap
    batch_sort(inc, outpath, output_class=lambda path: SortCap(path, linktype=inc.linktype))
  File "/home/cuckoo/bin/cuckoo/modules/processing/network.py", line 635, in batch_sort
    current_chunk = list(islice(input_iterator,buffer_size))
  File "/home/cuckoo/bin/cuckoo/modules/processing/network.py", line 677, in **iter**
    self.fd = dpkt.pcap.Reader(open(self.name, "rb"))
IOError: [Errno 2] No such file or directory: '/home/cuckoo/bin/cuckoo/storage/analyses/20/dump.pcap'
2015-04-10 14:27:01,490 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" on analysis at "/home/cuckoo/bin/cuckoo/storage/analyses/20"
2015-04-10 14:27:01,490 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Static" on analysis at "/home/cuckoo/bin/cuckoo/storage/analyses/20"
2015-04-10 14:27:01,490 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Strings" on analysis at "/home/cuckoo/bin/cuckoo/storage/analyses/20"
2015-04-10 14:27:01,491 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" on analysis at "/home/cuckoo/bin/cuckoo/storage/analyses/20"
2015-04-10 14:27:02,690 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "VirusTotal" on analysis at "/home/cuckoo/bin/cuckoo/storage/analyses/20"
2015-04-10 14:27:02,690 [lib.cuckoo.core.plugins] DEBUG: Applying signature overlays for signatures: creates_exe
2015-04-10 14:27:02,723 [lib.cuckoo.core.plugins] DEBUG: Running non-evented signatures
2015-04-10 14:27:02,723 [lib.cuckoo.core.plugins] DEBUG: Running signature "creates_exe"

**Comment by gtback** [comment]
I think I had this same error the last time I set up a Cuckoo instance. If I remember correctly, I had forgotten to set the capabilities on the tcpdump binary (see [here](http://docs.cuckoosandbox.org/en/latest/installation/host/requirements/#installing-tcpdump)).  Of course, it could be something else that is causing the `dump.pcap` file to not be created. 

In any event, I think a clearer error message ("NetworkAnalysis module failed to run because no PCAP file was generated") might be helpful.

**Comment by tysonmax20042003** [comment]
All set. Hummm. Not sure what the issue is. I hope someone else sees this and has a resolution. Thanks gtback for the help.

**Comment by tysonmax20042003** [comment]
All set. Hummm. Not sure what the issue is. I hope someone else sees this and has a fix. Thanks gtback for the help.

**Comment by botherder** [comment]
It is most certainly what @gtback said. Can you verify that you can run `tcpdump -i eth0 -n` from Cuckoo's user?

**Comment by tysonmax20042003** [comment]
I do see network traffic from eth0. From cuckoo user I ran sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump 
Also getcap /usr/sbin/tcpdump
with the correct result.
/usr/sbin/tcpdump = cap_net_admin,cap_net_raw+eip

**Comment by tysonmax20042003** [comment]
I think its a problem with 2015-04-10 14:27:01,488 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" on analysis at "/home/cuckoo/bin/cuckoo/storage/analyses/20"
and 
IOError: [Errno 2] No such file or directory: '/home/cuckoo/bin/cuckoo/storage/analyses/20/dump.pcap'
2015-04-10 14:27:01,490 [lib.cuckoo.core.plugins] DEBUG: Executed processing module

**Comment by tysonmax20042003** [comment]
After trying to run another try today I am getting the same error as post "MongoDB "disconnect" error #522"

2015-04-17 00:58:17,408 [lib.cuckoo.core.plugins] DEBUG: Running non-evented signatures
2015-04-17 00:58:17,408 [lib.cuckoo.core.plugins] DEBUG: Running signature "creates_exe"
2015-04-17 00:58:17,408 [lib.cuckoo.core.plugins] DEBUG: Running signature "generic_metrics"
2015-04-17 00:58:17,417 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2015-04-17 00:58:17,454 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/cuckoo/bin/cuckoo/lib/cuckoo/core/plugins.py", line 505, in process
    current.run(self.results)
  File "/home/cuckoo/bin/cuckoo/modules/reporting/mongodb.py", line 216, in run
    self.conn.disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 1050, in __call__
    self.__name, self.__client.__class__.__name__))
TypeError: 'Database' object is not callable. If you meant to call the 'disconnect' method on a 'MongoClient' object it is failing because no such method exists.
2015-04-17 00:58:17,948 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "ReportHTML"
2015-04-17 00:58:17,948 [lib.cuckoo.core.scheduler] INFO: Task #35: reports generation completed (path=/home/cuckoo/bin/cuckoo/storage/analyses/35)
2015-04-17 00:58:18,172 [lib.cuckoo.core.scheduler] INFO: Task #35: analysis procedure completed

**Comment by botherder** [comment]
What is the network configuration you adopted for your VM?

**Comment by tysonmax20042003** [comment]
Yup no problem.  Cuckoo PC has 2 interfaces one for my internal range and eth1 is a 10base network (10.1.0.1) with only one physical VM configuration in Cuckoo. (actually the Windows 7 is in a KVM container through Proxmox. irrelevant but thought to let you know.) windows 7 is 10.1.0.2 static with its gateway to the Cuckoo host. Routing looks ok.  I went to the Windows 7 PC and is able to access the Internet and Cuckoo but using IPTABLES routing traffic form eth1 10.1.0.1 to my network gateway only. So routing and DNS looks ok for the cuckoo box and windows 7 system. Windows 7 firewall is off and IPTABLES all traffic allowed inbound to cuckoo.

**Comment by botherder** [comment]
I've heard people having issues with Proxmox. There's obviously something wrong in your setup as the analysis is never started and it seems to be stuck at a startup point.

I'm not too familiar with KVM+Cuckoo so better to loop @jekil in. It would be useful if you could share the config files.

**Comment by tysonmax20042003** [comment]
Really! Wonder why?  I have a few environments and the only problems when it comes to networking would be if anyone uses internal NAT and not a Bridged adaptor setup form my experience. NAT has problems with communication with other VM's.

 I will get my configs for cuckoo.conf and physical.Conf on Monday.  I am not in the area of my Setup.  Did you want like a pastbin link for both?

**Comment by botherder** [comment]
Pastebin would be best, thanks.

**Comment by tysonmax20042003** [comment]
Here are my configs. Please let me know if you would like my iptables config. Thanks again to you guys for helping. 

Cuckoo:
eth0: 192.168.1.12
eth1: 10.1.0.1

Win7 PC: 10.1.0.2

Cuckoo Config: http://pastebin.com/gHPZAGZr
auxiliary.conf: http://pastebin.com/j3GjPDJu
reporting.conf: http://pastebin.com/MEcdkU56
processing.conf: http://pastebin.com/JvRyWWxD

**Comment by tysonmax20042003** [comment]
Also I have this installed:

root@Cuckoo-Host:~/.pip# pip freeze
Django==1.8
Jinja2==2.7.2
Landscape-Client==14.12
Magic-file-extensions==0.2
MarkupSafe==0.18
PAM==0.4.2
Pyrex==0.9.8.5
SQLAlchemy==0.8.4
Twisted-Core==13.2.0
apt-xapian-index==0.45
argparse==1.2.1
bottle==0.12.0
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
cybox==2.1.0.10
dpkt==1.6
html5lib==0.999
libvirt-python==1.2.2
pefile==1.2.9.1
pyOpenSSL==0.13
pymongo==2.6.3
pyserial==2.6
python-apt==0.9.3.5ubuntu1
python-debian==0.1.21-nmu2ubuntu2
python-magic==0.4.6
requests==2.2.1
six==1.5.2
ssdeep==2.0-0.1
ssh-import-id==3.21
urllib3==1.7.1
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.0.5

**Comment by tysonmax20042003** [comment]
I tried it again today and same problem. I think? Looks to be this issue again. OSError: [Errno 2] No such file or directory

Cuckoo Sandbox 1.3-dev

2015-05-05 22:28:19,682 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/bin/cuckoo/lib/cuckoo/core/scheduler.py", line 363, in run
    success = self.launch_analysis()
  File "/home/cuckoo/bin/cuckoo/lib/cuckoo/core/scheduler.py", line 281, in launch_analysis
    machinery.stop(self.machine.label)
  File "/home/cuckoo/bin/cuckoo/modules/machinery/physical.py", line 88, in stop
    shutdown = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-05-05 22:28:20,128 [lib.cuckoo.core.resultserver] DEBUG: New connection from: 10.1.0.2:49245
2015-05-05 22:28:20,128 [lib.cuckoo.core.resultserver] DEBUG: File upload request for shots/0006.jpg
2015-05-05 22:28:20,130 [lib.cuckoo.core.resultserver] DEBUG: Uploaded file length: 92948
2015-05-05 22:28:20,130 [lib.cuckoo.core.resultserver] DEBUG: Connection closed: 10.1.0.2:49245
2015-05-05 22:28:20,352 [lib.cuckoo.core.resultserver] DEBUG: Connection closed: 10.1.0.2:49235
2015-05-05 22:31:48,983 [lib.cuckoo.common.abstracts] INFO: Still 1 guests alive. Shutting down...
2015-05-05 22:31:48,986 [modules.machinery.physical] DEBUG: Getting status for machine: Windows7x64.
2015-05-05 22:31:48,999 [modules.machinery.physical] DEBUG: Rebooting machine: Windows7x64.
Traceback (most recent call last):
  File "./cuckoo.py", line 107, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "./cuckoo.py", line 79, in cuckoo_main
    sched.stop()
  File "/home/cuckoo/bin/cuckoo/lib/cuckoo/core/scheduler.py", line 478, in stop
    machinery.shutdown()
  File "/home/cuckoo/bin/cuckoo/lib/cuckoo/common/abstracts.py", line 230, in shutdown
    self.stop(machine.label)
  File "/home/cuckoo/bin/cuckoo/modules/machinery/physical.py", line 88, in stop
    shutdown = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


I checked iptables to see if a rule is blocking it and no traffic on my blocked rules using iptables -L INPUT -v and iptabled -L OUTPUT -v

Connections on Cuckoo system connections
![image](https://cloud.githubusercontent.com/assets/11822285/7486804/cba5ae4c-f378-11e4-9f61-5abb05ddbdb2.png)

Connections on Win7 PC:
![image](https://cloud.githubusercontent.com/assets/11822285/7486809/dcd55cb2-f378-11e4-956c-c10796163380.png)

**Comment by jbremer** [comment]
Sorry for the late reply, but I only see this issue now. Please check my following comments in another issue, that will resolve your issue: https://github.com/cuckoobox/cuckoo/issues/546#issuecomment-108785757 and https://github.com/cuckoobox/cuckoo/issues/546#issuecomment-108785942.

**Comment by jbremer** [comment]
Can we close this issue?
