### ISSUE TITLE
UnicodeError "label too long" in guest.py wait_available()

### ISSUE THREAD

**Issue by l0ft1369** [cuckoosandbox/cuckoo#699]
My cuckoo.py just started puking this out after one of the last updates. Like within the last 2 weeks max. I am not exactly sure which update did it, or what the stack trace is trying to tell me, so I'll just post it here. 

2015-12-10 23:28:07,313 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/jc/cuckoo/lib/cuckoo/core/scheduler.py", line 439, in run
    success = self.launch_analysis()
  File "/home/jc/cuckoo/lib/cuckoo/core/scheduler.py", line 326, in launch_analysis
    self.guest_manage(options)
  File "/home/jc/cuckoo/lib/cuckoo/core/scheduler.py", line 254, in guest_manage
    guest.start_analysis(options, monitor)
  File "/home/jc/cuckoo/lib/cuckoo/core/guest.py", line 375, in start_analysis
    self.wait_available()
  File "/home/jc/cuckoo/lib/cuckoo/core/guest.py", line 270, in wait_available
    socket.create_connection((self.ipaddr, self.port), 1).close()
  File "/usr/lib64/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/usr/lib64/python2.7/encodings/idna.py", line 73, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

no idea what that means. I will try shutting the api, web interface and cuckoo itself down and then running utils/community.py -wafb master and utils/community.py wafb 2.0 to see if that helps but I really doubt that it will. I have only tried analyzing one binary so far so I am not sure if this is being caused by the piece of software I am trying to analyze or what. Please let me know what else I can do to help troubleshoot this message.

Thanks,
l0ft

**Comment by l0ft1369** [comment]
Also wanted to follow up. After I tried updating the community stuff I went back in through the web interface and submitted www.google.com which is my default for testing on here. Got a similar stack trace as last time. Check it out:

2015-12-10 23:40:58,878 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/jc/cuckoo/lib/cuckoo/core/scheduler.py", line 439, in run
    success = self.launch_analysis()
  File "/home/jc/cuckoo/lib/cuckoo/core/scheduler.py", line 326, in launch_analysis
    self.guest_manage(options)
  File "/home/jc/cuckoo/lib/cuckoo/core/scheduler.py", line 254, in guest_manage
    guest.start_analysis(options, monitor)
  File "/home/jc/cuckoo/lib/cuckoo/core/guest.py", line 375, in start_analysis
    self.wait_available()
  File "/home/jc/cuckoo/lib/cuckoo/core/guest.py", line 270, in wait_available
    socket.create_connection((self.ipaddr, self.port), 1).close()
  File "/usr/lib64/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/usr/lib64/python2.7/encodings/idna.py", line 73, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

So I'm not really sure what's going on, but something is. The system is Fedora 22 (and was working). It's 64 bit and I keep everything up to date using dnf. 

Thanks,
l0ft

**Comment by jbremer** [comment]
Well, if you look closely it appears to be an error related to `getaddrinfo` / something with unicode encodings. Not really sure how that comes in to play here..

**Comment by jbremer** [comment]
Did you correctly configure the IP address of said machine - can you share your configuration with us?

**Comment by jbremer** [comment]
Closing this issue. Please re-open if you have new information on this issue etc.
