### ISSUE TITLE
 ERROR: Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by andr3w77** [cuckoosandbox/cuckoo#720]
I'm running into this error while trying to an analyse and exe

2015-12-30 11:12:50,340 [lib.cuckoo.core.scheduler] ERROR: VBoxManage exited with error restoring the machine's snapshot
2015-12-30 11:12:50,345 [lib.cuckoo.core.scheduler] CRITICAL: A critical error has occurred trying to use the machine with name WinXP during an analysis due to which it is no longer in a working state, please report this issue and all of the related environment details to the developers so we can improve this situation. (Note that before we would simply remove this VM from doing any more analyses, but as all the VMs will eventually be depleted that way, hopefully we'll find a better solution now).
0 packets captured
0 packets received by filter
0 packets dropped by kernel
2015-12-30 11:12:50,405 [lib.cuckoo.core.scheduler] WARNING: Unable to stop machine WinXP: Trying to stop an already stopped vm WinXP
2015-12-30 11:12:50,419 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/agiron/cuckoo-master/lib/cuckoo/core/scheduler.py", line 446, in run
    self.launch_analysis()
  File "/home/agiron/cuckoo-master/lib/cuckoo/core/scheduler.py", line 393, in launch_analysis
    self.unroute_network()
  File "/home/agiron/cuckoo-master/lib/cuckoo/core/scheduler.py", line 226, in unroute_network
    if self.interface:
AttributeError: 'AnalysisManager' object has no attribute 'interface'
2015-12-30 11:13:47,736 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.101.
2015-12-30 11:13:47,737 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.101.
2015-12-30 11:13:47,793 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.101.
2015-12-30 11:13:47,793 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.101.
2015-12-30 11:13:47,822 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.101.
2015-12-30 11:13:47,823 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.101.
^C2015-12-30 11:15:01,803 [lib.cuckoo.common.abstracts] INFO: Still 1 guests alive. Shutting down...
2015-12-30 11:15:02,059 [lib.cuckoo.common.abstracts] WARNING: Unable to shutdown machine WinXP, please check manually. Error: Trying to stop an already stopped vm WinXP

**Comment by jbremer** [comment]
Fixed the issue, but please do not that you still have to fix your environment as the `WinXP` VM is not behaving properly ;-)
