### ISSUE TITLE
Support latest pymongo

### ISSUE THREAD

**Issue by akapucu** [cuckoosandbox/cuckoo#721]
2015-12-31 13:50:03,049 [lib.cuckoo.core.plugins] DEBUG: Running 339 signatures
2015-12-31 13:50:03,099 [lib.cuckoo.core.plugins] DEBUG: Analysis matched signature: antivirus_virustotal
2015-12-31 13:50:03,301 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2015-12-31 13:50:33,398 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/opt/new/new-git/cuckoo/lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/opt/new/new-git/cuckoo/modules/reporting/mongodb.py", line 89, in run
    if "cuckoo_schema" in self.db.collection_names():
  File "build/bdist.linux-i686/egg/pymongo/database.py", line 517, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python2.7/contextlib.py", line 17, in **enter**
    return self.gen.next()
  File "build/bdist.linux-i686/egg/pymongo/mongo_client.py", line 748, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.linux-i686/egg/pymongo/mongo_client.py", line 712, in _get_socket
    server = self._get_topology().select_server(selector)
  File "build/bdist.linux-i686/egg/pymongo/topology.py", line 141, in select_server
    address))
  File "build/bdist.linux-i686/egg/pymongo/topology.py", line 117, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused

**Comment by botherder** [comment]
Well, seems like you don't have MongoDB running.

**Comment by akapucu** [comment]
even i start mangodb i still get this

2016-01-01 15:13:19,474 [lib.cuckoo.common.objects] WARNING: Unable to import yara (please compile from sources)
2016-01-01 15:13:27,470 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 505, in process
    current.run(self.results)
  File "/opt/cuckoo/modules/reporting/mongodb.py", line 216, in run
    self.conn.disconnect()
  File "build/bdist.linux-i686/egg/pymongo/database.py", line 1091, in __call__
    self.__name, self.__client.__class__.__name__))
TypeError: 'Database' object is not callable. If you meant to call the 'disconnect' method on a 'MongoClient' object it is failing because no such method exists.
2016-01-01 15:13:29,485 [lib.cuckoo.core.scheduler] INFO: Task #6: reports generation completed (path=/opt/cuckoo/storage/analyses/6)

any idea?

**Comment by jbremer** [comment]
Which version of `pymongo` are you using?

**Comment by akapucu** [comment]
pip freeze | grep pymongo
pymongo==3.2

**Comment by jbremer** [comment]
A new version of `pymongo`, I see. We'll have to fix that later, but for this reason the `requirements.txt` file contains hardcoded version numbers - so to avoid these issues with library upgrades, giving us the time to test support before upgrading to the latest and greatest.
We should probably update our documentation regarding this as the `requirements.txt` versions are not reflected in the documentation, @botherder thoughts?

**Comment by jbremer** [comment]
Going to close this issue. Sure, upgrading `pymongo` is still on the todo list, but we'll be doing that eventually once we have some better unit testing in-place for that.
