### ISSUE TITLE
httpreplay break cuckoo

### ISSUE THREAD

**Issue by akapucu** [cuckoosandbox/cuckoo#722]
After installing httpreplay cuckoo stop working here is output

2016-01-01 18:46:23,262 [root] DEBUG: Importing modules...
Traceback (most recent call last):
  File "cuckoo.py", line 118, in <module>
    test=args.test)
  File "cuckoo.py", line 66, in cuckoo_init
    init_modules()
  File "/opt/new/new-git/cuckoo/lib/cuckoo/core/startup.py", line 236, in init_modules
    import_package(modules.processing)
  File "/opt/new/new-git/cuckoo/lib/cuckoo/core/plugins.py", line 69, in import_package
    import_plugin(name)
  File "/opt/new/new-git/cuckoo/lib/cuckoo/core/plugins.py", line 59, in import_plugin
    module = __import__(name, globals(), locals(), ["dummy"], -1)
  File "/opt/new/new-git/cuckoo/modules/processing/network.py", line 30, in <module>
    import httpreplay
  File "build/bdist.linux-i686/egg/httpreplay/__init__.py", line 6, in <module>
  File "build/bdist.linux-i686/egg/httpreplay/cut.py", line 8, in <module>
  File "build/bdist.linux-i686/egg/httpreplay/smegma.py", line 368, in <module>
  File "build/bdist.linux-i686/egg/httpreplay/smegma.py", line 374, in _TLSStream
AttributeError: 'module' object has no attribute 'SSL3_V'

**Comment by jbremer** [comment]
This issue is due to an old version of `dpkt`. I'll add a warning for that in `httpreplay`.
Could you in the meanwhile `pip install dpkt`?

**Comment by akapucu** [comment]
I did upgrade here is output

pip freeze | grep HTTP
HTTPReplay==0.1.4

pip freeze | grep dpkt
dpkt==1.8.6.2

I also remove dpkt and installed again.

 Checking for updates...
 Okay! You are running a development version.
Traceback (most recent call last):
  File "cuckoo.py", line 118, in <module>
    test=args.test)
  File "cuckoo.py", line 66, in cuckoo_init
    init_modules()
  File "/opt/new/new-git/cuckoo/lib/cuckoo/core/startup.py", line 236, in init_modules
    import_package(modules.processing)
  File "/opt/new/new-git/cuckoo/lib/cuckoo/core/plugins.py", line 69, in import_package
    import_plugin(name)
  File "/opt/new/new-git/cuckoo/lib/cuckoo/core/plugins.py", line 59, in import_plugin
    module = __import__(name, globals(), locals(), ["dummy"], -1)
  File "/opt/new/new-git/cuckoo/modules/processing/network.py", line 30, in <module>
    import httpreplay
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/__init__.py", line 6, in <module>
    from .cut import (
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/cut.py", line 8, in <module>
    import httpreplay.smegma
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 368, in <module>
    class _TLSStream(tlslite.tlsrecordlayer.TLSRecordLayer):
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 374, in _TLSStream
    dpkt.ssl.SSL3_V: (3, 0),
AttributeError: 'module' object has no attribute 'SSL3_V'
root@darkbox:/opt/new/new-git/cuckoo#

**Comment by jbremer** [comment]
Can you upgrade to `httpreplay 0.1.5`, hoping this will fix the issue :)

**Comment by akapucu** [comment]
jbremer,
Now, I can continue to running cukcoo but I think i am running latest version of dpkt. which is 1.8.6.2.
Is there any other version of dpkt that i dont know?

**Comment by jbremer** [comment]
That should be the one.. perhaps it's using `python-dpkt` over dpkt in pip?

**Comment by akapucu** [comment]
Yeap good call. I dont get warning anymore but :)

After analysis on cuckoo i am still seeing 

" Deprecation note: While processing this analysis you did not have the httpreplay Python library installed. Installing this library (i.e., pip install httpreplay) will allow Cuckoo to do more proper PCAP analysis including but not limited to showing full HTTP and HTTPS (!) requests and responses. It is recommended that you install this library and possibly reprocess any interesting analysis tasks. "
 
Under network the analysis

By the way you may want to update requirement.txt for httpreplay version.

**Comment by jbremer** [comment]
I'll investigate that issue later. Yes, thanks, I was going to do that after your confirmation that the workaround resolves the traceback.

**Comment by ashemery** [comment]
I had that same error coming out in Network tab, it was resolved by:
pip install --upgrade dpkt

I think the problem was that I installed dpkt using apt-get "python-dpkt".

**Comment by jbremer** [comment]
For some reasons related to `python-dpkt` I'm unable to test this locally, could you perhaps temporarily uninstall pip's dpkt and make a screenshot / paste the output of the Web daemon so I can further investigate the issue, @ashemery?

**Comment by ashemery** [comment]
Excuse me, was a bit busy with other stuff. Hope the snapshots below is what you're looking for?

![dpkt-prob](https://cloud.githubusercontent.com/assets/3056337/12565753/bc4e683c-c3be-11e5-9d5c-610cbce12a04.png)
![old-dpkt](https://cloud.githubusercontent.com/assets/3056337/12565754/bc5c3386-c3be-11e5-9ba5-db12c050947e.png)

Let me know if I can help you with anything further.

**Comment by Ads5740** [comment]
Hi all,
I encountered the same issue:

" Deprecation note: While processing this analysis you did not have the httpreplay Python library installed. Installing this library (i.e., pip install httpreplay) will allow Cuckoo to do more proper PCAP analysis including but not limited to showing full HTTP and HTTPS (!) requests and responses. It is recommended that you install this library and possibly reprocess any interesting analysis tasks. "

To troubleshout I launched a python shell under the cuckoo location and entered the following:

cuckoo$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dpkt

I initially got an error:

/f testc:sdadad
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dpkt/__init__.py", line 12, in <module>
    import aoe
  File "/usr/local/lib/python2.7/dist-packages/dpkt/aoe.py", line 6, in <module>
    from decorators import deprecated
  File "/usr/local/lib/python2.7/dist-packages/dpkt/decorators.py", line 4, in <module>
    from test import pystone
ImportError: cannot import name pystone

To fix:

copied the pystone.py file form /usr/lib/python2.7/test >> /usr/local/lib/python2.7/dist-packages/dpkt

and edited the decorator.py located in /usr/local/lib/python2.7/dist-packages/dpkt to:

import warnings
from timeit import Timer
# from test import pystone
import pystone
from time import sleep

result:

cuckoo$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dpkt
>>>

the fault is now gone and analysis back to working order

**Comment by jbremer** [comment]
Nice @Ads5740, I've had this exact issue for a fairly long period of time on my laptop.. these steps resolved the issue ;-) (I never bothered to fix it myself to be honest).
Is this something that should be documented perhaps - it is unrelated to the original issue that was presented here (which was because of `apt-get install python-dpkt` instead of `pip install dpkt`), but it's an issue that I've had myself too.

**Comment by jbremer** [comment]
This is an issue with the `python-dpkt` apt package. Now that `httpreplay` forces a more recent version of `dpkt` it will automatically make `pip` / `setuptools` install a more recent version and thus ignore the `python-dpkt`-related issues. Therefore closing this issue.

**Comment by mahaveer1984** [comment]
Just comment out 
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
and pymongo==3.0.3
install them independently pefile you get from github
