### ISSUE TITLE
MACHINEA: unable to upload config to analysis machine

### ISSUE THREAD

**Issue by GelosSnake** [cuckoosandbox/cuckoo#723]
A specific sample is causing a UTF-8 error breaking cuckoo report service: 
Sample sha256 hash (can provide if needed): 158e2525d395f7d4db0dca32504c73caef099aab7e580db45ef82f9b243051ee
Seems like it does not reproduce under malwr.com: 
https://malwr.com/analysis/ZmQwMjU4YmZhY2VmNDliMThhYmIxZWQ2NGI3NmQ2ZTM/ 
Another example:
https://malwr.com/analysis/NTI1MGMxZDk4NTBmNGQ3MThjZTBlZWE3YThmZjEzZmI/

```
WARNING:modules.processing.behavior:Analysis results folder does not exist at path '/home/cuckoo/cuckoo/storage/analyses/303/logs'.
ERROR:lib.cuckoo.core.plugins:Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/cuckoo/utils/../modules/reporting/mongodb.py", line 224, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 436, in _insert
    self.codec_options, sock_info)
InvalidStringData: strings in documents must be valid UTF-8: '>+;;\x86\xbf\xd4\xd6\'\xbe\xa7\xbf\xdc\xee\xb1b\xa4J\xed\xbb\xd0+\x95\xf1\x06\xe8\x9c\xea\t|l\x10\x80\x14\x1f\xbc(\xa4\xd9 \r\xe0\xff\x7f\xcf(Z\x18\x11Qs(od\xb9\xc9\xd4\xaf6\xa6\xe5\xb8\xda\xc1\xd2\x05\xbc\xc7\xf3\xbc\xc8\xb0\xcc\x91\xac\xa6~\x85\x1fi\xb6a\xad\xb6\x9e\x05\xbfim\xe7\x83O\x83f\xd7\xf3G\xb2\x81\xd3$\x8f4\xc1d\'@h\xc0\xa2\xe79\xe0S\xb214\x96C:\xc8\xc9~(\x15\xe1\x14z\xe0\x97\xaa\x7f\xa9-BpF<\x9d\x99\xa3\x1d\xb0\xcd\xd0\xc1l\x86\xb9,r\x8dQ\xd1t\x18\x02\x8cT\x8e\x9a\xefL\x8b&&\xac\xbcV\xaf\xfd\xb4h\x99\x86\xd0\xb6\x0c\x97\xc8lW\x13\x95\xe8\xc0\t\xac\xe2\xcbq\xcb`\xbdM\xda\xf2\x91\xc1\x8d\xf1\xa3\xec\xd6\x81\xbc\x8dP\xbcV\xc6/>1|i\xe2\x9b2\x14\x87\x07X2\x13\xc6jw\x1c\tb\xab\xe3~J\xc0\x994\xfb\xbe\xfa\x88]\x15\xd4U\x9a\x05\x07\xa8:#\xf2\xad\t\'\x89\x931\x8d^\xa9\x05\xc4q\xeaK\xd9\x8d\xad\x1d\xf2\x82M\x95\xf7\x89\xe3\xebG\x91w\xbeQZ.\x99q\x8as\x06n0\x17\xb2hN\xd6x,l\xdaO&U\x13|{j\x80\x85\xf13\xd5\xb2\xb9)\xfe2=\xd5u \x8e\xb8v\n\r\xa4u\xadczu\x06\xf7k\x10\xf4f8T\x10\xae\x0f\xd9]\x1c\xfd\x99\x10\x1c\x1aq\x8a\x85\xd1p=\x0c\x14<\x1b\xd126\xc6h\xaf9\xb1\xa2i\n\xc4\x07\xbe\xdaW\xdc\xabx\x83\x01\xfc\xfe%\x12\r5\x12\xa1\xae\xe6En?\xdc.\xdf\x01J>?\'\xd1vkLv\x90\x048 \xf0E\x19}\xa3\x14\xacu\xe0\xef\xf8s\x05\xd2\x82-\xe8(2\xc4\xf6nN`\x87-9\x8cI;\xde\x12\xd2\xa4\xf9\x0c\x8b\x8f\xa8g\x98\xfb\xed$\x86;\x10\xec\xbcn\x0b\xe9\x0e\x88r\xeb\xee\x85yA\x1a\xd4\r\xd9\xb4>!\x919\xae\xac\xc5\xbb\xaf\xfa\x7fI\x890\xe6}EE\xc2\x87\x07\xd63:\x8eu\xfd\xec\xc3f\x038\x97\x03\xb7\xdc\xbc\x19\xcc_\xd6\x04P#E`\xea\x18\xa3\x91\x19=\x88ws\x88H\x08n\xfe\x9e\xc1\x1f\x12\x99\n\xeay*\xff@-#]\xa4:\x96Q\xcb\x8a\xe2\x92}\xdd\xd0\xffr\x8d\x94\x82\x83\xe3\xa1)\xc2\n\x8e\x92]\xe4\x8d*dc*\xd0\xce\rK\xe6a\xe7\xc1\xdeC\xe8\xc5\xd2w\x90<\xa8q\x80\xac\xda\x86\xfd(\xed\x05\xcc\x9e\x13\x05\xd2d\x9efk\xd59\x84Wb\x02\x82\xb3q\x05No\xe9\xb1\xaf\x11DI\t\xdey`\x9a\xae9\xe9n\xe20wDxL\x96\x15\x13J{\x16i\x04`G\x97,K\xfc"\x8e\x1d\xe9\xb1\xfa$\x9b\xdd`\x92s\x8d\xcd\x80\x87\xaef}\xf6je\xbd\x9c\x05\xcfc6\x0ev\x93W\x96X.\xcd\x8d\x8afI\x836\xa3j^cV\x93\xd7\x83\xa4\x10\xbe\xff/zZJ>sk!!\x06\xa5\x11\x8c_\xa1eG\xa9\x99\x05j,y\xf9\x05\r\x16\xa5\xf3L\x89\xcd,\xd7\r\x10\xd7\xd9\xd9f\xf9\x8e\xd8\xcczI-3\xdb\x85\xee8\xe4\x18\x93}\x0f\xe0\xddp\x86\x99S\xe3\x03\x9e\x96\xdd\xc9\xca\x1ae\x9a\xbe\x0eCo>\x85\xf8.k(b\xc7\x0f\xf7\xc0j;\xf50\xaf\xea\xbc\xbd\xf7\x7fE\x98_)\x80!\xf3\xa7x\xce\x15\xf2\x13%:\xac\xbb6zw\x81w\x81\x8f|\xd0\xf08w8@\xed9E\x9d^\xf3\x81i\x9d\x9eqI T\x86\xf2]\xf5\x8e\x18;\xa5<3\x93\xe0\xe4\x05|J\x96\t h\x0f7T\xefR\xd28Z\xcc \x81\xd7R;X\xf4fp\xc7g\x8b\xd0C\xe6\xa1\xd8\xb5\x10}o\x13\x9cE\x97|\x86A|T\xd9)\xdf\xdaD!\xec:\xac\xde\x08\x10b\xc6 \xdb\xa8\xe1\x8a\xe6\xb8\xf9\x88\x84rY\xda\xc9Y\xe1\'\x12\x9fs\x02\xeeQ\xec\xd5e\xe4=\x15\x89\xc24[\xe0\x90!q\x18FwY\xf9[\xe3\xd3\xb5\xa0\xac\x07\xd6\x8296\x87\xcc\x18\xb6\xfd8\xe9\x83.L\xfa0\x17`\x83\x14S\xce\xc8\xde\xb9\x9c\x9e\x08;)\xfa\xc2J\xab\xb0_p\x96fD\xee\x16q\xf2{S)\xc2\x8a,\xcc0\xa7~%\x07\xcePg\xb0\xd9Q\x0exY\x9b\xaf\x93|\xa3\xff\'\xe4\xc2\x84\xb7t\xc2\xb0\xa6\x89[h\xb6(\x94\'\xb4\ncB\xba\x96\x0f\x07\xb54"\xb2\x1d\x80\xfdp\xfdQT\xf8\xd7\x9e\x18f\xe6\xa5\xaac\xca\xeba\xca\xbf\xfc\x96U\xc8\xf7\xe7\xee\x80Of\xd8zS\xc0\xa9Xj\xb6\xc5\x11\x04d\x03\x02\xb5+n\xc6\x0eNt\xf2\x01\x7f\xea0\x0c\xf8\xb0Qc\xe3\xe6^\xd3\x1e\xfc\xbc(\xa9\x08\xd12N$\xe9\xd4A\xe05\xad\xd5\xe9\x0e1\x88r\xf9a\xf2\x1a\x12lhC\xb0\xe2Z%\xa2I\xbf\x01=;\x0fK\x05`\xa4\xb2\xd8\xec\x85T\xc2l\xed~\xe4\x0c\x17\xde%\xab\x15\xfa\x8ad\xce>xO`\x16+\xb5u\xdc,\xfba\x83\xa4\xf2\x01B\xb9V\xc0\xc5a\xa3@\x97\\\xa4a\xbd;B\xe6\xc6\x9e\x7f\xc7\xce(\xba\xe2#\xae\x8d\xd7\x93\xc1\xeb\xfe\xa6\x8cV\xe7#\x96E\xd7\xbe\x02!\x18\xddDi%\xa4j\xe2\x04\xd7r\xe7MJN?\xbd\xc9\x8d\x05J\xd7\xcb\x98\x1b\x94[\x8f\xde\xb2\xd0,VS]\xca\x1e\x1e%G\xf8\x03\xfda>dA\x80\x19\xaf\x97s\xc1\x8e\xf9\x0b\xe7=@\xa8\xe8\xb7\xf9\x17\x8f\xbbqZy\xe1\x0c=^Cs\xca\xd3e1\x02Hq\xa4kX\xea\x8db\xb0d\x856\x1e\xf4 v\x89T\x9d\x12\xf4\xfeO\x1c\xbf\xb3-O\xbf(<\xbb\xfb\xe2\xac*\x15m\xf1\x16\xaat d:t\\"^\x035\xeea\xe9\x14\xfb{\x8e;\x9cGi\xf3\xe76w\xdd\xed\x13\xfc\x86a\xdd\xfb\xba\xe4\x8c&;6|M\xbf\xf1\xa3yu\xb9\xc57a\xe4E\xc9`\x05QK\x97\xf8\x80\xe4\x9dD(\xad\xb1\xea\xf8\xde\xbb\x14\xa6a\xf6\x1f\xb4\xeb}\xf8\xa5/\x17\xdd\'\xce\xf9\xd5\xf7\x1ao\x92\x9f\xd1\x80\x80<_\x18-\xf8SR`\xf3\r\xc8\x80\xa0\xdf0\x1d\xf5"\x87\xc0\xee\xe1\xaf_,G-\x07\xc8\xd6g\x9f\x9d\x0e\xb3\xe8\x95 \xe6\x03\xcc\xc4Y#\x89[\x80Qg\xda\x93M2O\xe2\xedB\xd7\xcd\xa3ei\x83\xeb\xa6\xd5\xfb\xddq\xc3\xd5(\xf0\x9f\xfd\x17\xa2\xc4X\x81{K\xcc\xc3\x1bJi\x0f\xe0t\x81\xbb\xf5d\xf5t\x84\xfb P\xbe\xa1\xeeAqZAq6\xe8\x94`\x8b\x87|\xeaf\xe5\x8e\x94\x06l\xac\xa7\x0c\x06\xd8\x0e8\xe4\x02\x07E\x02w\x02\xb6S\xe2L\xa0\xf7\x07b\xc0\xc8\x9d\rg\x1d\x10\x96\x01\xb0\xe8\xbfN\xf04O\x97\x1c6Ob\x0e&cx\x90\xd4\xc2R\x86s\xc1\x1ck\xdf\xf7\x03\xcb\x1fnv\xd7\x02ex*\x08\x93KQ\x07\xf8\x04\xd6\'\xa1\xc7\xb7=\xf7\xcf\x8d\x94{p\xee\xa6\xfc\xb3\xb3b\xba_\x1a\xf8\xfaY\x1cI\xfa\xd1VqW\xaeO\x1b<\x05\x14w\x0f\xb3g\x16Qd\xf9\t\xf1\x87y\xf4]\x07V\x02\xe6\xd2\x95\xdbh{"(BzN\x17\xf8\xe7\x97\x112\xa9\xd4\x99\xc8uU\xd32\x1f\xa7b~\x0f\r\x85\x93\xdc\xc8\x9d\x83n\xce\x8f\x16\x14\x8e\xa0\xe0y\xd4\xce\x8dr\xfa\xb4+\xef\xeb\x86\x9a\xb1\xaa\xaf\x87je!q\x81L\\\xb8\xa2\x9b\xc0\xb3\xb9\xaf\xb5>\x19\x03\xa4R\xe2a\xef\x85\xf9\xcfS\x8d\x08\xd2Q&b)\xa4\xf2\xdf\x19\xda5\xe6\xeb\x8b}@5\xc5\xa3w\xfd\xbe\xb5\xe3\xf4\xc8\xa9\x895#\xef\x80W1N\x92\xc4\x14\x8e+\x8e\xd1\xee\xdbEo\\\x0f\x86\xb5\xe3\x9dFz\xf0r\x05\xaf.iu\x91-\x0cP\xae5\xebJ\xa9\xbf\xa9n\xe9\x9b\xf6R\xa3\xbb"\xed\xdc\x18\xe3\xfel@\x9fF\nj:\x0c\xec32\xba\x9aV\xb2p\xd0\x06\xb5\xde\xc4\xb7\x82\xe2\x10\x8b\t\x9b\x07\x9d\xf8\xf0Y\xe4\x8f\xcf1}n\x9a:s\x0bw;o~\x8f*\xe2\xbfi\xf3\x82\x99\xe8TA\xe7\xa2u\x14\xdf\x85<${ qHN\xe51\xe3FMK\x84=\xa6\x8a\xddI\xfd\xfd\xfd0|\xbf\xd2v\xf8\xda_\xed\xceDF\xb0\x15\rp\xf3\xd6;\xfd$\xe3\xf8\xd9.V\xfa\x82\xe9\xed`\xf3\t\xd5Y\xbc\x01{`\xa9\xce~\xd3\x99\x8f\xf48^Oyz\xc0{\xc9\xe4\xfa\xe5\xe4\xb7_L\xee\x87\xee\xbfU\xda\xffg\xe8\xa1]\x7f\xed\x81m\x8df\x1dA$\xfe\xc1\xac\xb5o\'\xb5L;0\x08/\x1c\xd7>\xc0}\xb0 \x1d\xe3\xae,R\x18\x17\x172v\xd7\n\t\xbb\x97\xc9\xcf)H\x1d\x9d\xe8\x0b\x12e\xf2\xa8\xf5M\xf4\xfd$)\xf3\x0c\x0b\xee\x9d\x94\xf0\x1b\x94ymi(9\xa0]2G\x88k\x1e\x1f\x1a\xd5VD\xebz\x86\x97\x98)\x84\xb01O\xc0+V\xf9\x96\x07\xe5\x85\xe2\x94?\x83\xa6\x95\x90\x99\xb1z\xbd{\x8b\xea\xbd2!\x06\x8eK\xe3\n\x1b\xc0iC\xa8\x91\xb2z\xafp\xa9N8\xfa\x87\x1a\x15_\x1b]\xa0d=\xce\xc81\xd6\x88\x98TG\xf7\x8a\xe6$uN\xbc\x86\xbf\xcd\x11c\xbd\xa1\x13\xb9.8J{;i\xb4z\x162\t\xde\x11\xce\x9c\xc3\xce\x82\xb6!\x91\xadg\x11\xb8\x05"\x18\xee\x14\xad\x08\xa0`;\x91\xbd\xc3\xa2\xb4\xdd\xe0 \x93C\xcd\x0eVUM{2\x996\x92\xb7;\xdd4\xf4\xa0\xae?\x1e\xb28d\xc3\xc0^x\xc14\x7f\xadsy\xb4+\xdc\xc8u\xd3\xd0\xc3VSB\x0f\xa6\xa9IG\x13\xd2\x8d\x1b\xadO\x1dV\xea\x95\xdc\x1d\x7f\xc0"\xc1(\x05\x1b\xd7\xcc\xb1\x18|\x85\xd1\xdc\xf0q\xba\x8b\ng\x06\xcc\x04\xf2\xd8J\xc0"m\xa3\x8d\x12:e\xdcPE\xb8\xa8f[\xc6`;K\x18\x93\x12rS\xc3V\x0b3\x0b\x7f1\x9cz\xbd\x85\x18r0\xcf)B\xd7(@\xd2\x9cjBC\xf4\x11\xe7\x9a$\xaf]\x06\x0c\xa6\xfeB\x0e\xdb\x0b0}y\xa0\xaa\x94\nz\x19\xf0{ a\n\xce\x91+4\x87\xa4\xa0\x04&\x8b\x12<3Q/\x9b\xb1.\xc0%\xf7\x08\t\xbfG\x8d@M\xa4\xad\xd4\x90\xc9`R|\'\n1\xd2]\xe1\xe0\x1b\x9f/\xcdk\xdfDBy\xc3{T\xf3\xb7\xb8J&\x9b\x1f!S\xf1\xfe(X}8\xcdu\xb0\x88\x1edk\x82\x8b\x04\xe4/\xfcG\xb4\x8eH8`vz7\xea\x8e\xaf\xbc1_OS+\xb4\xec\x97N\xcc)U\xae\x17I0\x96tm\\\xb36\x93Z\x1de\xcc\xc0\xb3\xfcZw\xc6\x1b\x9d\xfe\xe4e\xf5\xa4;\x1f\x15\xaf\x12\x9f]\xfd\x1c=D\x8b\xc1\xcc\xd9\xe7\x98H\xec\x85\xa9MstEm\x1e\xf0s\x99F\xceN\x14\xa9\xba\xd3\xb0\x93\xbe\xf3Xf\xad\xef\x11\xb04U\x06=\xce\x13E\xbd\xe7\x915\x0f\xc1\xb2\xfe/\x0c2ec>\xc5\xc2(\x0b\xeb6\xea\x9bf%\xa4X\xa8\xa9\xd2h\xcd\x91qK\xe6\xf6\xe2\x0e\x95\xaa\xf5\x15g\xeep\x89M5\xce\xbc*\xed 6_\x8e5.\xbbax\xa2I\xc0;Z\xd2\xd9Av \x15\xd3h?\xb0\xb5ndF\xab\xf1%7\x86^)9\xd3U\x8b\x7f\xabO\x88F:\x159\xaa\x04\xa0j\x1a\xf4E\xe3\xd0\xc9B\x99\x1eZ\x0c\xabr\xd1\xfc\'q\xe82\xe9{\x9c\xc8$y\x04\xc1O\xd795\xa2\xfa|\xb3N\x97\xf8\xdf\x0e\xc3\xe7\xb3\xdb\x9f\xe9\xfb\xd0\xe9\xce\xeb|\xef1\xeaG\x95\x9f\xe6\x9fv%\xe1\x08Z}{OqB\xa4x%\xd7\xd1,d\xedJ\xaf\xb9\xd4n\xbc\x9b\x04\x14\xb2\xb9\x88Q\t=<W\xf0@\x01+\x88\xefZs!\x14\x1f\x95b\x0c,\xdadZ>g\xf5ab)\xb8\xe7\xaf\x13\xbc\x87+I\xc4\x1b\x06\x14s\xc5\xa7\xb1\xe6E(q\x9d\x82*\xa5\x9f\xaaBLLGM\x91C\ny~BV\xcer\x02\xb8{JZ\xcdEH<R\xd0\x1bLZ\xa0\xa3)\xeb\x0bS\xb3x{;\xcc\xe8\xbd-rL;\x8e7OH\xa8\\\x04\x05\xa6&\xb7k\x8d3\xc8|\xd5\xdc\xc4\xb8x\xf4CU\x93d5\xc8\xfb}\xb1\xb5_\x0cuD\xccm\x89h\xbe>\xd6\xbd\x08j\xa7\xdc?\xa8@^{\xae\x1b\xf7\x8f\xaf\x80Z\n\xe4r\xb9\xa97)<\x17T\xa1\xa7\x06\xb2\xf4\x03\x0c_u\x17\xe4\x8e\xca\x03\xdfR\x967\xa7\xe5D\xa5\xbc~\x1d\xf46\x86\xc8\xf2\xae\xab\xb6\xafuE<\xe7_\xd0S\xb4\xd2\xa68\xa0\xeb#o\x96\xd7\xd2\xd9T\xbcu\xe6K\xd1\xda\x19\x1c{\xe4T\x1e\x8cL\xb8\x8e\x0e\xd4\x06q\x18\x1c\xbe\'\xab<\x85P\x9e\xd6\x81\x81\xf5H\xa6'
```

**Comment by jbremer** [comment]
This has probably been resolved by now.. :-) Closing issue. Thanks for the feedback heh.
