### ISSUE TITLE
httpreplay-based PCAP issue

### ISSUE THREAD

**Issue by akapucu** [cuckoosandbox/cuckoo#726]
I am running issues right before report generation. Here is output from system

2016-01-13 18:50:14,673 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2016-01-13 18:52:55,482 [lib.cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
2016-01-13 18:52:58,742 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/opt/cuckoo-new/modules/processing/network.py", line 764, in run
    results.update(Pcap2(pcap_path, self.get_tlsmaster()).run())
  File "/opt/cuckoo-new/modules/processing/network.py", line 698, in run
    for s, ts, protocol, sent, recv in r.process():
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/reader.py", line 85, in process
    self.tcp and self.tcp.process(ts, ip, packet)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 88, in process
    s.process(ts, tcp, to_server)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 351, in process
    self.states[self.state](self, ts, tcp, to_server)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/smegma.py", line 173, in state_init_syn_ack
    raise InvalidTcpPacketOrder(tcp)
InvalidTcpPacketOrder: ��o,�Y��PwX~�
2016-01-13 18:52:59,585 [lib.cuckoo.core.scheduler] INFO: Task #6: reports generation completed (path=/opt/cuckoo-new/storage/analyses/6)
2016-01-13 18:52:59,598 [lib.cuckoo.core.scheduler] INFO: Task #6: analysis procedure completed

**Comment by jbremer** [comment]
Thanks. Could you maybe share the `dump.pcap` file for this analysis?

**Comment by akapucu** [comment]
here
[dump.pcap.zip](https://github.com/cuckoosandbox/cuckoo/files/89874/dump.pcap.zip)
thanks

**Comment by jbremer** [comment]
@akapucu Sorry for the delay. Could you `pip install --upgrade httpreplay` and see whether your issue is still present? It should be resolved :-)
