### ISSUE TITLE
x86(i386) qemu error

### ISSUE THREAD

**Issue by aspel** [cuckoosandbox/cuckoo#747]
Cuckoo Sandbox 2.0-rc1
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Good! You have the latest version available.

2016-02-02 19:20:18,627 [lib.cuckoo.core.scheduler] INFO: Using "qemu" as machine manager
2016-02-02 19:20:19,262 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2016-02-02 19:20:19,272 [lib.cuckoo.core.scheduler] WARNING: As you've configured Cuckoo to execute parallel analyses, we recommend you to switch to a MySQL ora PostgreSQL database as SQLite might cause some issues.
2016-02-02 19:20:19,293 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-02-02 19:20:43,706 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "phpCB.exe" (task #10, options "route=none")
2016-02-02 19:20:43,757 [lib.cuckoo.core.scheduler] INFO: File already exists at "/opt/cuckoo/storage/binaries/660958852ac24b286e46a95fe25163a6bb28f5b8468d4375dcb40d5424ca0868"
2016-02-02 19:20:43,881 [lib.cuckoo.core.scheduler] INFO: Task #10: acquired machine vm2 (label=vm2)
2016-02-02 19:20:43,909 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 20139 (interface=eth0, host=192.168.0.12, pcap=/opt/cuckoo/storage/analyses/10/dump.pcap)
dropped privs to root
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
0 packets captured
1 packet received by filter
0 packets dropped by kernel
2016-02-02 19:20:44,870 [lib.cuckoo.core.scheduler] WARNING: Unable to stop machine vm2: Trying to stop an already stopped vm vm2
2016-02-02 19:20:45,097 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 325, in launch_analysis
    machinery.start(self.machine.label, self.task)
  File "/opt/cuckoo/modules/machinery/qemu.py", line 150, in start
    arch_config = dict(QEMU_ARGS[vm_arch])
KeyError: 'x86'

---qemu.conf----
[vm2]
label = vm2
image = /opt/image/WinXP.qcow2
# vm arch (mips/mipsel/arm/x64/x86)

arch = x86
platform = windows
ip = 192.168.0.12
interface = eth0
resultserver_ip = 192.168.122.10

**Comment by jbremer** [comment]
Reading the QEMU machinery it would appear that, while `x64` is supported, `x86` is not.
To be honest, I'm not even sure if the QEMU machinery supports Windows analysis, @rep?

**Comment by doomedraven** [comment]
probably this one also can be closed, as solved no?

**Comment by jbremer** [comment]
Yes, good catch @doomedraven, thanks.

**Comment by dueland** [comment]
@jbremer - Could you please elaborate on your comment on whether "QEMU machinery supports Windows analysis in the first place"? I do not see the link between machinery module and windows support.  I'm currently trying to couple cuckoo with a project based on qemu and injection does not seem to be working. 

Possible errors:
Host: INFO: Analysis results folder does not contain any file or injection was disabled.
Guest: "No handlers could be found for logger lib.api.process"

**Comment by jbremer** [comment]
Not sure. I guess I was wondering if QEMU support Windows, but it would appear it does.

**Comment by dueland** [comment]
Thanks for taking a look. 

Perhaps the answer lies in the errors and modifications I made along the way:
- [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run: start() takes exactly 3 arguments (2 given)
TypeError: start() takes exactly 3 arguments (2 given)
- Fix: Added machinery.start(self.machine.label, self.task) to Scheduler:380 

 [lib.cuckoo.core.guest] ERROR: No valid analyzer found at path: /home/cuckoo/cuckoo/analyzer/linux
- This is an odd one. Is there a reason why it is looking for the analyzer folder for linux when I'm trying to run a windows guest? I added the folder and then I got it to run.

Guest:
No handlers could be found for logger lib.api.process
the system cannot accept the date entered

Host: 
2016-07-10 12:01:22,386 [modules.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.

Another oddity: The file in question is not being started it seems, there should be a GUI visible. The file has been successfully uploaded to the guest.

My modified qemu.py does not make use of the standard snapshot format so I commented that out. I simply wanted to start up qemu with a single command to Popen, added attachment.
[qemu.py.zip](https://github.com/cuckoosandbox/cuckoo/files/355992/qemu.py.zip)

**Comment by dueland** [comment]
My mistake! The default platform was set to linux in the configuration file. Everything is working now, thank you.

**Comment by doomedraven** [comment]
@jbremer i found another bug in qemu

https://github.com/cuckoosandbox/cuckoo/blob/master/modules/machinery/qemu.py#L179

```
        # magic arg building
        final_cmdline = [i.format(**params) for i in cmdline]
```

doesn't generate anymore correct cmdline command
```
 DEBUG: Executing QEMU ['qemu-system-arm', '-display', 'none', '-M', 'versatilepb', '-m', '256M', '-kernel', '{imagepath}/vmlinuz-3.2.0-4-versatile-arm', '-initrd', '{imagepath}/initrd-3.2.0-4-versatile-arm'..
```

**Comment by doomedraven** [comment]
i found the solution, there also one error in config of qemu, will do PR in a bit

@jbremer looks like everything works for @dueland so you can close it

**Comment by jbremer** [comment]
Ok, thanks!
