### ISSUE TITLE
JSONDecode Error

### ISSUE THREAD

**Issue by momurder** [cuckoosandbox/cuckoo#753]
Hi Cuckoo Team,

using your sandbox solution really a while but have already since 1.1 Problems with JSONDumps, etc. something i have fixed, and it worked until my release upgrade last friday to 2.0RC1.

Agent.py is accessible from Controller where ./cuckoo.py is started. checked with curl.

2016-02-09 11:36:44,628 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "binary (2)" (task #1145, options "")
2016-02-09 11:36:44,682 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/cuckoo-user/cuckoo/storage/binaries/e020006d504f856a058e8f630de4520f9e6df1ab7e4dc64e8e126835bb6dd58f"
2016-02-09 11:36:44,711 [lib.cuckoo.core.scheduler] INFO: Task #1145: acquired machine WXP-admin-01 (label=Cuckoo-SB-XP-admin-01)
2016-02-09 11:36:44,719 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6840 (interface=eth1, host=192.168.99.11, pcap=/home/cuckoo-user/cuckoo/storage/analyses/1145/dump.pcap)
2016-02-09 11:36:47,485 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=WXP-admin-01, ip=192.168.99.11)
2016-02-09 11:37:59,668 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo-user/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/cuckoo-user/cuckoo/lib/cuckoo/core/scheduler.py", line 339, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo-user/cuckoo/lib/cuckoo/core/scheduler.py", line 257, in guest_manage
    guest.start_analysis(options, monitor)
  File "/home/cuckoo-user/cuckoo/lib/cuckoo/core/guest.py", line 393, in start_analysis
    r.json().get("version"), self.vmid, self.ipaddr)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by momurder** [comment]
already tried to switch to bson, using cuckoomon_bson.dll but not working......

**Comment by jbremer** [comment]
It would appear that you're having issues connecting to the guest. Your network is setup correctly etc?
You're not the first to post similar issues so I'll provide a workaround, but I think this is a setup error on your side.

**Comment by jbremer** [comment]
Closing this issue much like the other related issues. Please upgrade to the latest development version which has a couple of improvements on this end. If you still experience related issues (or any issue really), please feel free to open new Github issues.
