### ISSUE TITLE
Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by satwikbh** [cuckoosandbox/cuckoo#765]
Hi 

I recently updated cuckoo to 2.0-RC1 and since then I'm facing the above issue. 

> Traceback (most recent call last):
>   File "/home/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
>     self.launch_analysis()
>   File "/home/cuckoo/lib/cuckoo/core/scheduler.py", line 339, in launch_analysis
>     self.guest_manage(options)
>   File "/home/cuckoo/lib/cuckoo/core/scheduler.py", line 257, in guest_manage
>     guest.start_analysis(options, monitor)
>   File "/home/cuckoo/lib/cuckoo/core/guest.py", line 393, in start_analysis
>     r.json().get("version"), self.vmid, self.ipaddr)
>   File "/usr/lib/python2.7/dist-packages/requests/models.py", line 819, in json
>     return json.loads(self.text, **kwargs)
>   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded

Is this a bug since I did no major changes to cuckoo except for setting up as per docs.

**Comment by jekil** [comment]
Could you please give us more information?
Did you just upgrade or did you setup from scratch (as suggested in the documentaiton)?
Does his error heppen with all samples or just one?

**Comment by satwikbh** [comment]
I did it from scratch as mentioned in docs and this error happens for all samples.

**Comment by jbremer** [comment]
Hi @satwikbh, could you temporarily comment out the following lines of code in your Cuckoo setup, do one analysis, and provide us with the `dump.pcap` file from that analysis, please?
That should allow us to further help you.

https://github.com/cuckoosandbox/cuckoo/blob/master/modules/auxiliary/sniffer.py#L62-L71

**Comment by satwikbh** [comment]
Posting the contents here as I couldn't attach the pcap file.

> reading from file dump.pcap, link-type EN10MB (Ethernet)
> 03:42:25.852874 ARP, Request who-has 192.168.56.101 tell 192.168.56.1, length 28
> 	0x0000:  0001 0800 0604 0001 0a00 2700 0000 c0a8  ..........'.....
> 	0x0010:  3801 0000 0000 0000 c0a8 3865            8.........8e
> 03:42:26.851254 ARP, Request who-has 192.168.56.101 tell 192.168.56.1, length 28
> 	0x0000:  0001 0800 0604 0001 0a00 2700 0000 c0a8  ..........'.....
> 	0x0010:  3801 0000 0000 0000 c0a8 3865            8.........8e
> 03:42:27.851287 ARP, Request who-has 192.168.56.101 tell 192.168.56.1, length 28
> 	0x0000:  0001 0800 0604 0001 0a00 2700 0000 c0a8  ..........'.....
> 	0x0010:  3801 0000 0000 0000 c0a8 3865            8.........8e
> 03:42:29.860601 ARP, Request who-has 192.168.56.101 tell 192.168.56.1, length 28
> 	0x0000:  0001 0800 0604 0001 0a00 2700 0000 c0a8  ..........'.....
> 	0x0010:  3801 0000 0000 0000 c0a8 3865            8.........8e

**Comment by jbremer** [comment]
Thanks, those ARP requests look great. Yeah, I think your network settings are incorrect ;-)

**Comment by satwikbh** [comment]
I dont get it. These are the same network settings that I followed since long and which worked on my previous version of cuckoo. 
Any suggestion on what exactly are the network settings that need to be corrected.

**Comment by jbremer** [comment]
Oh, right, sorry, my bad. I mistook your issue for another issue there. We've seen this issue being reported a few times before, but I'm not sure why; so it would greatly help if you could share a pcap file to help us debug the issue at your setup.
There have been some changes that lead to this bug being triggered, but why the bug triggers I'm not completely sure as it works fine on my own systems etc. It could be a different version of certain libraries on your system, but to pinpoint that I'm going to need the pcap.

**Comment by satwikbh** [comment]
Here it is 
[dump.pcap.zip](https://github.com/cuckoosandbox/cuckoo/files/129438/dump.pcap.zip)

**Comment by satwikbh** [comment]
Hi is the bug resolved?

**Comment by jbremer** [comment]
No, so far it's a bug at your side. Did you check the pcap file? It's literally not doing anything - just a couple of ARP packets.

**Comment by jbagel2** [comment]
So, if it is related to my issue (which looks the same). It appears that there is a timeout property expected in the virtualbox.conf that needs to be set. It fails the socket check about 500ms prior to the box becoming pingable. 

The core.guest.py is trying to calculate from a self.timeout that apparently isn't being set (or left at a very sort default). I added the timeout property to the virtualbox.conf and set it to 30 (just a random time) and the next submit worked.

**Comment by jbremer** [comment]
Interesting @jbagel2. Just to be sure; could you please share your patch here? :-) Thanks!

**Comment by ravi231** [comment]
I ran into the same problem , below are the error message i got while running cuckoo to 2.0-RC1.

2016-02-25 17:50:45,749 [lib.cuckoo.core.scheduler] INFO: Task #4: acquired machine cuckoo1 (label=cuckoo1)
2016-02-25 17:50:45,754 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5598 (interface=vboxnet0, host=192.168.56.101, pcap=/home/cuckoo/cuckoo/storage/analyses/4/dump.pcap)
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 65535 bytes
2016-02-25 17:50:49,365 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
880 packets captured
880 packets received by filter
0 packets dropped by kernel
2016-02-25 17:53:26,942 [lib.cuckoo.core.scheduler] ERROR: **Failure in AnalysisManager.run
Traceback (most recent call last):**
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 339, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 257, in guest_manage
    guest.start_analysis(options, monitor)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 393, in start_analysis
    r.json().get("version"), self.vmid, self.ipaddr)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by satwikbh** [comment]
@jbagel2 Can you tell me how to add the timeout property?
There seems to be no such option in virtualbox.conf

**Comment by jbremer** [comment]
A number of related issues have been resolved since the `2.0-rc1` release. For those who are still experiencing these issues, please upgrade to the latest development version of Cuckoo (i.e., clone Cuckoo from our Git repository), and create new Github issues if the issues still persist - with updated tracebacks etc.

Closing this issue for now. Again, feel free to create new issues.

**Comment by bganeshmail** [comment]
Even with new version issues exist.

 _______ _     _ _______ _     _  _____   _____ 
   |       |     | |       |____/  |     | |     |
   |_____  |_____| |_____  |    \_ |_____| |_____|

 Cuckoo Sandbox 2.0-rc1
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

2016-09-17 20:38:33,670 [root] INFO: Updated running task ID 6 status to failed_analysis
2016-09-17 20:38:33,688 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2016-09-17 20:38:34,828 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-09-17 20:38:34,849 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-09-17 20:39:22,581 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "tini.exe" (task #7, options "")
2016-09-17 20:39:22,587 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/cuckoo/storage/binaries/9654bb748199882b0fb29b1fa597c0cfe3b9d610adf4188a0b440f3faf5ee527"
2016-09-17 20:39:22,700 [lib.cuckoo.core.scheduler] INFO: Task #7: acquired machine xp_1 (label=xp_1)
2016-09-17 20:39:22,707 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 7823 (interface=vboxnet0, host=192.168.56.101
snapshot = snap1
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042, pcap=/home/cuckoo/storage/analyses/7/dump.pcap)
tcpdump: syntax error
2016-09-17 20:39:26,906 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=xp_1, ip=192.168.56.101
snapshot = snap1
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042)
2016-09-17 20:39:33,612 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/cuckoo/lib/cuckoo/core/scheduler.py", line 339, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/lib/cuckoo/core/scheduler.py", line 257, in guest_manage
    guest.start_analysis(options, monitor)
  File "/home/cuckoo/lib/cuckoo/core/guest.py", line 382, in start_analysis
    r = self.get("/")
  File "/home/cuckoo/lib/cuckoo/core/guest.py", line 255, in get
    return requests.get(url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)

**Comment by doomedraven** [comment]
rc1 is not new, use master branch(dev version)

**Comment by bganeshmail** [comment]
Installed the dev version from github.

root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo# ./cuckoo.py

                      __                  
  .----..--.--..----.|  |--..-----..-----.
  |  __||  |  ||  __||    < |  _  ||  _  |
  |____||_____||____||__|__||_____||_____|

 Cuckoo Sandbox 2.0-dev
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

2016-09-29 11:02:50,821 [root] INFO: Updated running task ID 9 status to failed_analysis
2016-09-29 11:02:51,030 [root] INFO: Updated running task ID 8 status to failed_analysis
2016-09-29 11:02:51,049 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2016-09-29 11:02:52,030 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-09-29 11:02:52,043 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-09-29 11:03:44,417 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "Lnwtg.exe" (task #10, options "")
2016-09-29 11:03:44,436 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/cuckoo/cuckoo/cuckoo/storage/binaries/6ea73055329027aff1e330a1851576d2de2423b8591967910bceab5357065070"
2016-09-29 11:03:44,629 [lib.cuckoo.core.scheduler] INFO: Task #10: acquired machine xp (label=xp)
2016-09-29 11:03:44,639 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6762 (interface=vboxnet0, host=192.168.56.101
snapshot = snap1
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042, pcap=/home/cuckoo/cuckoo/cuckoo/storage/analyses/10/dump.pcap)
2016-09-29 11:03:45,089 [lib.cuckoo.core.scheduler] ERROR: Machinery error: Trying to start an already started vm xp
2016-09-29 11:03:45,255 [lib.cuckoo.core.scheduler] CRITICAL: A critical error has occurred trying to use the machine with name xp during an analysis due to which it is no longer in a working state, please report this issue and all of the related environment details to the developers so we can improve this situation. (Note that before we would simply remove this VM from doing any more analyses, but as all the VMs will eventually be depleted that way, hopefully we'll find a better solution now).
2016-09-29 11:03:45,255 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: syntax error\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (only applies to Ubuntu)?
2016-09-29 11:03:47,361 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path '/home/cuckoo/cuckoo/cuckoo/storage/analyses/10/logs'.
2016-09-29 11:03:47,648 [lib.cuckoo.common.objects] WARNING: Unable to import yara (please compile from sources)
2016-09-29 11:03:47,651 [modules.processing.network] WARNING: The PCAP file does not exist at path "/home/cuckoo/cuckoo/cuckoo/storage/analyses/10/dump.pcap".
2016-09-29 11:03:49,338 [lib.cuckoo.core.scheduler] INFO: Task #10: reports generation completed (path=/home/cuckoo/cuckoo/cuckoo/storage/analyses/10)
2016-09-29 11:03:49,572 [lib.cuckoo.core.scheduler] INFO: Task #10: analysis procedure completed

1.Please advice if this warning are ok to skip
2.I could wee report in html file with some minimal information but runserver is not getting laoded even with fresh install.

root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo# ./cuckoo.py

                      __                  
  .----..--.--..----.|  |--..-----..-----.
  |  __||  |  ||  __||    < |  _  ||  _  |
  |____||_____||____||__|__||_____||_____|

 Cuckoo Sandbox 2.0-dev
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

2016-09-29 11:02:50,821 [root] INFO: Updated running task ID 9 status to failed_analysis
2016-09-29 11:02:51,030 [root] INFO: Updated running task ID 8 status to failed_analysis
2016-09-29 11:02:51,049 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2016-09-29 11:02:52,030 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-09-29 11:02:52,043 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-09-29 11:03:44,417 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "Lnwtg.exe" (task #10, options "")
2016-09-29 11:03:44,436 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/cuckoo/cuckoo/cuckoo/storage/binaries/6ea73055329027aff1e330a1851576d2de2423b8591967910bceab5357065070"
2016-09-29 11:03:44,629 [lib.cuckoo.core.scheduler] INFO: Task #10: acquired machine xp (label=xp)
2016-09-29 11:03:44,639 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6762 (interface=vboxnet0, host=192.168.56.101
snapshot = snap1
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042, pcap=/home/cuckoo/cuckoo/cuckoo/storage/analyses/10/dump.pcap)
2016-09-29 11:03:45,089 [lib.cuckoo.core.scheduler] ERROR: Machinery error: Trying to start an already started vm xp
2016-09-29 11:03:45,255 [lib.cuckoo.core.scheduler] CRITICAL: A critical error has occurred trying to use the machine with name xp during an analysis due to which it is no longer in a working state, please report this issue and all of the related environment details to the developers so we can improve this situation. (Note that before we would simply remove this VM from doing any more analyses, but as all the VMs will eventually be depleted that way, hopefully we'll find a better solution now).
2016-09-29 11:03:45,255 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: syntax error\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (only applies to Ubuntu)?
2016-09-29 11:03:47,361 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path '/home/cuckoo/cuckoo/cuckoo/storage/analyses/10/logs'.
2016-09-29 11:03:47,648 [lib.cuckoo.common.objects] WARNING: Unable to import yara (please compile from sources)
2016-09-29 11:03:47,651 [modules.processing.network] WARNING: The PCAP file does not exist at path "/home/cuckoo/cuckoo/cuckoo/storage/analyses/10/dump.pcap".
2016-09-29 11:03:49,338 [lib.cuckoo.core.scheduler] INFO: Task #10: reports generation completed (path=/home/cuckoo/cuckoo/cuckoo/storage/analyses/10)
2016-09-29 11:03:49,572 [lib.cuckoo.core.scheduler] INFO: Task #10: analysis procedure completed

**Comment by bganeshmail** [comment]
Missed to provide runserver django details .
root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo/web# python manage.py runserver 0.0.0.0:8000
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0xb5675b8c>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 420, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (admin.E402) 'django.contrib.auth.context_processors.auth' must be in TEMPLATES in order to use the admin application.

System check identified 1 issue (0 silenced).

**Comment by kallimanis79** [comment]
Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/root/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 160, in stop
    module.stop()
  File "/root/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 151, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = 'tcpdump: vboxnet0: That device is not up\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?

**Comment by doomedraven** [comment]
Read your post you have solution there

**Comment by kallimanis79** [comment]
I read but I can't solve it. I don't understand which is the solution! Please help me.

**Comment by Nwinternights** [comment]
first check if vboxnet0 is up. then follow this part of the cuckoo guide:
 sudo apt-get install tcpdump apparmor-utils
 sudo aa-disable /usr/sbin/tcpdump
"Note that the AppArmor profile disabling (the aa-disable command) is only required when using the default CWD directory as AppArmor would otherwise prevent the creation of the actual PCAP files (see also Permission denied for tcpdump)."
For Linux platforms with AppArmor disabled (e.g., Debian) the following command will suffice to install tcpdump:
sudo apt-get install tcpdump
Tcpdump requires root privileges, but since you don’t want Cuckoo to run as root you’ll have to set specific Linux capabilities to the binary:

sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
You can verify the results of the last command with:
getcap /usr/sbin/tcpdump
/usr/sbin/tcpdump = cap_net_admin,cap_net_raw+eip
If you don’t have setcap installed you can get it with:
 sudo apt-get install libcap2-bin

**Comment by kallimanis79** [comment]
Thank you for your response Nwinternights.I had read these instructions and I try to solve it with them but I have the same problem.Please take an eye https://www.youtube.com/watch?v=oABDf4095I8&feature=youtu.be. Thank you very much.

**Comment by Nwinternights** [comment]
I just gave a quick look at the video and I've noticed a couple of things such as:
you never downloaded signatures (cuckoo signature)
you didn't install pillow on guest
you didn't put agent.pyw in automatic start (admin rights)
you're using cuckoo 2.0.3 ( @jbremer released 2.0.4a4) pip install cuckoo==2.0.4 (at least)
Do you have enabled sort pcap = on on cuckoo.conf 
On auxiliary.conf the sniffer is set to yes
On auxiliary.conf the path of tcpdump is correct?
when you start a submission, on host type : ps -ef |grep tcpdump and look at the output
if you type :  getcap /usr/sbin/tcpdump  what is the outputs?
I don't understand how u installed cuckoo... root? venv?
hope it helps

**Comment by kallimanis79** [comment]
Firstly I installed cuckoo in venv. All is ok but I have a problem because I have an error about the critical time and error about the sniffer.I think is better for me to have a good manual to start to install cuckoo from the base, especially on 2.0.4 version. Please help me to have a good malware analysis.Thank you very much.

**Comment by icedxu** [comment]
I  use the " sudo aa-disable /usr/sbin/tcpdump ",but it show error
icedxu@icedxu:~$ sudo aa-disable /usr/sbin/tcpdump

ERROR: Syntax Error: Unknown line found in file /etc/apparmor.d/usr.lib.snapd.snap-confine.real line 100:
    change_profile unsafe /** -> [^u/]**,

what should I do?

**Comment by doomedraven** [comment]
googling would be good also ;)
