### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by AntonAsssssa** [cuckoosandbox/cuckoo#782]
Cuckoo Sandbox 2.0-rc1

2016-02-25 10:04:02,484 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 339, in launch_analysis
    self.guest_manage(options)
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 257, in guest_manage
    guest.start_analysis(options, monitor)
  File "/opt/cuckoo/lib/cuckoo/core/guest.py", line 393, in start_analysis
    r.json().get("version"), self.vmid, self.ipaddr)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by AntonAsssssa** [comment]
I thivk, it is the same issue https://github.com/cuckoosandbox/cuckoo/issues/765
I have also been updated with the last version.

**Comment by jbremer** [comment]
As part of #753 I added a tweak that at least gets rid of the exception that you posted (see also 22c3a2e39ac3c6770d735e6ef1bf96e206fea302). Please upgrade to the latest version and also share a pcap file as outlined in #765. I'm still not sure why you're getting this error ;-)
Thanks!

**Comment by AntonAsssssa** [comment]
The guest.py was updated and now):

2016-02-25 15:49:34,344 [lib.cuckoo.common.objects] WARNING: Unable to import androguard (`pip install androguard`)
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 65535 bytes
2016-02-25 15:49:36,667 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=WindowsXP, ip=192.168.56.101)
2016-02-25 15:49:42,686 [lib.cuckoo.core.guest] CRITICAL: We were unable to detect either the Old or New Agent in the Guest VM, are you sure you have set it up correctly? Please go through the documentation once more and otherwise inform the Cuckoo Developers of your issue.
2 packets captured
2 packets received by filter
0 packets dropped by kernel
2016-02-25 15:49:48,781 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label WindowsXP to path /opt/cuckoo/storage/analyses/8/memory.dmp
2016-02-25 15:49:50,177 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 339, in launch_analysis
    self.guest_manage(options)
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 257, in guest_manage
    guest.start_analysis(options, monitor)
  File "/opt/cuckoo/lib/cuckoo/core/guest.py", line 401, in start_analysis
    self.db.guest_set_status(self.task_id, "failed")
AttributeError: 'GuestManager' object has no attribute 'db'

**Comment by jbremer** [comment]
@AntonAsssssa, please try again with the commit above applied :-)

**Comment by AntonAsssssa** [comment]
2016-02-25 17:17:26,732 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=WindowsXP, ip=192.168.56.101)
2016-02-25 17:17:32,793 [lib.cuckoo.core.guest] CRITICAL: We were unable to detect either the Old or New Agent in the Guest VM, are you sure you have set it up correctly? Please go through the documentation once more and otherwise inform the Cuckoo Developers of your issue.
2 packets captured
2 packets received by filter
0 packets dropped by kernel
2016-02-25 17:17:37,829 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label WindowsXP to path /opt/cuckoo/storage/analyses/4/memory.dmp
2016-02-25 17:17:39,546 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path '/opt/cuckoo/storage/analyses/4/logs'.

**Comment by AntonAsssssa** [comment]
Maybe problem is here?
root@grr:/opt/cuckoo# curl 192.168.56.101:8000
<html><head><title>502 Bad Gateway</title></head>
<body><h2>502 Bad Gateway</h2><h3>Host Not Found or connection failed</h3></body></html>

**Comment by jbremer** [comment]
Can you paste the entire http request/response, i.e., `curl -vvv 192.168.56.101:8000`?

**Comment by AntonAsssssa** [comment]
PORT     STATE SERVICE
8000/tcp open  http-alt

root@grr:/opt/cuckoo# curl -vvv 192.168.56.101:8000
* Rebuilt URL to: 192.168.56.101:8000/
* Hostname was NOT found in DNS cache
*   Trying 10.7.40.100...
* Connected to 10.7.40.100 (10.7.40.100) port 3888 (#0)
> GET HTTP://192.168.56.101:8000/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.56.101:8000
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* HTTP 1.0, assume close after body
< HTTP/1.0 502 Bad Gateway
< Proxy-Connection: close
< Content-type: text/html; charset=us-ascii
<
<html><head><title>502 Bad Gateway</title></head>
<body><h2>502 Bad Gateway</h2><h3>Host Not Found or connection failed</h3></body></html>
* Closing connection 0

oops proxy. The problem was here.

**Comment by jbremer** [comment]
Exactly..

**Comment by botherder** [comment]
Please, close if it's rejected.

**Comment by jbremer** [comment]
With the commit above I hope to notify other users about this misbehaviour in the future - you're not the first to run into it..
