### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Zimmer45** [cuckoosandbox/cuckoo#859]
Hello, 

I have a problem in launching the cuckoo version 2.0-rc1 and analyze file. 
The problem is "ValueError: No JSON object could be decoded."
But if I’m not connected to Internet (the host), I don't have this problem. 

```
2016-04-14 10:49:15,916 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2016-04-14 10:50:22,691 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 339, in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 257, in guest_manage
    guest.start_analysis(options, monitor)
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 393, in start_analysis
    r.json().get("version"), self.vmid, self.ipaddr)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`
```

**Comment by jbremer** [comment]
Which Agent do you have installed in the VM? If you go to `192.168.56.101:8000` in your browser, what is the response?

**Comment by jbremer** [comment]
Going to close this issue as user error if you won't provide us with more information ;-)

**Comment by jbremer** [comment]
And I believe this has been fixed already anyway.
