### ISSUE TITLE
ERROR: Failed to run the processing module "NetworkAnalysis"

### ISSUE THREAD

**Issue by Nadacsc** [cuckoosandbox/cuckoo#862]
I am getting this error (for number of samples : only when there are no packets have been captured and the dump.pcap is 24 bytes) .. is this normal ? 

0 packets captured
0 packets received by filter
0 packets dropped by kernel
2016-04-17 10:35:23,041 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "NetworkAnalysis" for task #570:
Traceback (most recent call last):
  File "/var/tmp/cuckoo/lib/cuckoo/core/plugins.py", line 215, in process
    data = current.run()
  File "/var/tmp/cuckoo/modules/processing/network.py", line 755, in run
    results["sorted_pcap_sha256"] = File(sorted_path).get_sha256()
  File "/var/tmp/cuckoo/lib/cuckoo/common/objects.py", line 208, in get_sha256
    self.calc_hashes()
  File "/var/tmp/cuckoo/lib/cuckoo/common/objects.py", line 153, in calc_hashes
    for chunk in self.get_chunks():
  File "/var/tmp/cuckoo/lib/cuckoo/common/objects.py", line 138, in get_chunks
    with open(self.file_path, "rb") as fd:
IOError: [Errno 2] No such file or directory: '/var/tmp/cuckoo/storage/analyses/570/dump_sorted.pcap'

**Comment by jbremer** [comment]
I believe I fixed this issue, but yeah, you can ignore it.

**Comment by Nadacsc** [comment]
I see .. thanks for the quick reply

I've dowloaded the last version of cuckoo available 'Cuckoo Sandbox 2.0-RC1' 
Is the fix here on github only ? how can I merge it to my version of cuckoo ?

**Comment by jbremer** [comment]
By applying the following commit e24eeaac61cbd4a087fc9548c16c84a2b0d670b6 :)
Let me know if that fixes your issue.

**Comment by jbremer** [comment]
This has been resolved in the latest Cuckoo so closing this as fixed, thanks!
