### ISSUE TITLE
ValueError: time data '2016-04-19T11:36:44' does not match format '%Y-%m-%dT%H:%M:%S.%f'

### ISSUE THREAD

**Issue by doomedraven** [cuckoosandbox/cuckoo#868]
looks like we don't need .%f at the end

````
ERROR:lib.cuckoo.core.plugins:Failed to run the processing module "AnalysisInfo" for task #524:
Traceback (most recent call last):
  File "/opt/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 215, in process
    data = current.run()
  File "/opt/cuckoo/utils/../modules/processing/analysisinfo.py", line 35, in run
    task = json_decode(open(self.taskinfo_path).read())
  File "/opt/cuckoo/utils/../lib/cuckoo/common/utils.py", line 434, in json_decode
    return json.loads(x, object_hook=json_hook)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/opt/cuckoo/utils/../lib/cuckoo/common/utils.py", line 425, in json_hook
    return datetime.strptime(x, "%Y-%m-%dT%H:%M:%S.%f")
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2016-04-19T11:36:44' does not match format '%Y-%m-%dT%H:%M:%S.%f'
```

**Comment by jekil** [comment]
Which database are you using?

**Comment by doomedraven** [comment]
@jekil  PostgreSQL

**Comment by jbremer** [comment]
Kind of weird though - are you using any odd locale perhaps?

**Comment by doomedraven** [comment]
you refer to this?
```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by jekil** [comment]
@doomedraven I tried to replicate with Postgres without success.
BTW that date comes from the db and pass an isoformat(), so it could be related to db or localization settings. 
We need more information about your setup.

**Comment by doomedraven** [comment]
@jekil

 from the same server
```
>>> datetime.datetime.now().isoformat()
'2016-05-12T15:05:16.828574'
```

i had similar issues on the same server
* https://github.com/cuckoosandbox/cuckoo/issues/874
* https://github.com/cuckoosandbox/cuckoo/issues/871

Stupid but, could it be related in some case from where it was uploaded? as it was uploaded from different countries?

**Comment by doomedraven** [comment]
I will return to this soon to improve distribution in general, so will see if will get it for new this bug, at the moment will close it, will reopen if will get it for new

**Comment by doomedraven** [comment]
just got it for new with last pull
```
ERROR:lib.cuckoo.core.plugins:Failed to run the processing module "AnalysisInfo" for task #233:
Traceback (most recent call last):
  File "/opt/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 242, in process
    data = current.run()
  File "/opt/cuckoo/utils/../modules/processing/analysisinfo.py", line 36, in run
    task = json_decode(open(self.taskinfo_path).read())
  File "/opt/cuckoo/utils/../lib/cuckoo/common/utils.py", line 434, in json_decode
    return json.loads(x, object_hook=json_hook)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/opt/cuckoo/utils/../lib/cuckoo/common/utils.py", line 425, in json_hook
    return datetime.strptime(x, "%Y-%m-%dT%H:%M:%S.%f")
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2016-07-12T11:44:09' does not match format '%Y-%m-%dT%H:%M:%S.%f'
```

with this one 
https://github.com/a0rtega/pafish/blob/master/pafish.exe


```
datetime.datetime.now().isoformat()
'2016-07-18T14:19:24.438575'
```

**Comment by doomedraven** [comment]
PS no db selected, 
`connection =`

**Comment by doomedraven** [comment]
had loaded page in browser
```
2016-07-18 07:26:01,905 [analyzer] WARNING: Unable to find the correct offsets for functions of: 32-bit kernel32.dll (with timestamp 0x4ce7b8ef)
2016-07-18 07:26:01,905 [analyzer] WARNING: Unable to find the correct offsets for functions of: 32-bit kernel32.dll (with timestamp 0x4ce7b8ef)
```

**Comment by doomedraven** [comment]
hash 0f445d5a17773c9f65167c8fd6612e96

no report generated, as it failed

```
ERROR:lib.cuckoo.core.plugins:Failed to run the processing module "AnalysisInfo" for task #345:
Traceback (most recent call last):
  File "/opt/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 242, in process
    data = current.run()
  File "/opt/cuckoo/utils/../modules/processing/analysisinfo.py", line 37, in run
    task = json_decode(open(self.taskinfo_path).read())
  File "/opt/cuckoo/utils/../lib/cuckoo/common/utils.py", line 434, in json_decode
    return json.loads(x, object_hook=json_hook)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/opt/cuckoo/utils/../lib/cuckoo/common/utils.py", line 425, in json_hook
    return datetime.strptime(x, "%Y-%m-%dT%H:%M:%S.%f")
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2016-09-07T10:24:33' does not match format '%Y-%m-%dT%H:%M:%S.%f'
```

**Comment by doomedraven** [comment]
i will provide exported analysis a bit later, i was able generate report with process -r

**Comment by doomedraven** [comment]
hm is like random error, i resubmited sample, and not i didn't get that bug

**Comment by doomedraven** [comment]
just got this bug for new in another server, tried to see what can make influence to that

what about to try to replace it to something like this?
``` 
import dateutil.parser
return dateutil.parser.parse(x)
```

i replaced that on my side to this solution to see if still will have this issues or not
