### ISSUE TITLE
ValueError: time data 'Tue, 19 Apr 2016 16:30:49 GMT' does not match format '%Y-%m-%d %H:%M:%S'

### ISSUE THREAD

**Issue by doomedraven** [cuckoosandbox/cuckoo#871]
* curl http://cucko_dist_master:9003/api/task -F file=@pafish.exe

```
DEBUG:dist-cuckoo0:Submitted 0 tasks to cuckoo0
Traceback (most recent call last):
  File "./distributed/instance.py", line 183, in <module>
    handle_node(args.instance)
  File "./distributed/instance.py", line 152, in handle_node
    "%Y-%m-%d %H:%M:%S")
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data 'Tue, 19 Apr 2016 16:30:49 GMT' does not match format '%Y-%m-%d %H:%M:%S'
```

**Comment by jbremer** [comment]
Which database backend are you running at the Cuckoo node?

**Comment by doomedraven** [comment]
postgress 9.3 as is distributed

**Comment by doomedraven** [comment]
i close this as this issuse will be checked here https://github.com/cuckoosandbox/cuckoo/issues/874
