### ISSUE TITLE
DocumentTooLarge: BSON document too large

### ISSUE THREAD

**Issue by doomedraven** [cuckoosandbox/cuckoo#877]
any possible solution? i checked this http://stackoverflow.com/a/25553887

````
ERROR:lib.cuckoo.core.plugins:Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/opt/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 506, in process
    current.run(self.results)
  File "/opt/cuckoo/utils/../modules/reporting/mongodb.py", line 227, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 2182, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 530, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 512, in _insert_one
    check_keys=check_keys)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 218, in command
    self._raise_connection_failure(error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 346, in _raise_connection_failure
    raise error
DocumentTooLarge: BSON document too large (18575204 bytes) - the connected server supports BSON document sizes up to 16793598 bytes.

```

**Comment by doomedraven** [comment]
duplicated sorry https://github.com/cuckoosandbox/cuckoo/issues/358

**Comment by nadir3392** [comment]
for me the problem is in progress, if you have the solution for my problem (eg how broke the limit of MongoDB 16M), help me.

**Comment by doomedraven** [comment]
you have my solution poster many times in issues, just search it
