### ISSUE TITLE
Error when running cuckoo in parallel

### ISSUE THREAD

**Issue by Nadacsc** [cuckoosandbox/cuckoo#887]
I am using the latest cuckoo 2.0 RC1

and my cuckoo settings is perfect, however when I tried to run it in parallel I encountered some errors: 
```
Traceback (most recent call last):
  File "./cuckoo.py", line 118, in <module>
    test=args.test)
  File "./cuckoo.py", line 78, in cuckoo_init
    ResultServer()
  File "/var/tmp/cuckoo/lib/cuckoo/common/utils.py", line 183, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/var/tmp/cuckoo/lib/cuckoo/core/resultserver.py", line 46, in __init__
    self.port = int(self.cfg.resultserver.port)
TypeError: int() argument must be a string or a number, not 'NoneType'

```
I understand that this is referring to the port no which I have commented out in the cuckoo.conf , however with each machine in virtualbox.conf I specified a specific port .. so my complete settings are as follows: 

```
# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = ee_mm,ee_mm2

[ee_mm]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = ee_mm

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.56.101

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
 snapshot = snapshot1

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
 interface = vboxnet0

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here 
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
 resultserver_ip = 192.168.56.1

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port = 2042

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
# tags = windows_xp_sp3,32_bit,acrobat_reader_6

[ee_mm2]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = ee_mm2

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.57.101

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
 snapshot = snapshot2

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
 interface = vboxnet1

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here 
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
 resultserver_ip = 192.168.57.1

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port = 2043

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
# tags = windows_xp_sp3,32_bit,acrobat_reader_6

```

and when setting the two cuckoo machines to the same port ( and specifying the result port on cuckoo.conf as 2042 I got the following error: 

```
2016-04-28 10:29:08,748 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "f0838224e3bd814d03dcd36133af280c" (task #95, options "")
2016-04-28 10:29:08,941 [lib.cuckoo.core.scheduler] INFO: Task #95: acquired machine ee_mm (label=ee_mm)
2016-04-28 10:29:08,949 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5744 (interface=vboxnet0, host=192.168.56.101
snapshot = snapshot1
interface = vboxnet0
resultserver_ip = 192.168.56.1, pcap=/var/tmp/cuckoo/storage/analyses/95/dump.pcap)
tcpdump: syntax error
2016-04-28 10:29:09,975 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "f1218dd4e77a7c66478c53f6ff8ff9b9" (task #96, options "")
2016-04-28 10:29:10,286 [lib.cuckoo.core.scheduler] INFO: Task #96: acquired machine ee_mm2 (label=ee_mm2)
2016-04-28 10:29:10,294 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5803 (interface=vboxnet0, host=192.168.57.101
snapshot = snapshot2
interface = vboxnet1
resultserver_ip = 192.168.57.1, pcap=/var/tmp/cuckoo/storage/analyses/96/dump.pcap)
tcpdump: syntax error
2016-04-28 10:29:15,856 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=ee_mm, ip=192.168.56.101
snapshot = snapshot1
interface = vboxnet0
resultserver_ip = 192.168.56.1)
2016-04-28 10:29:18,630 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=ee_mm2, ip=192.168.57.101
snapshot = snapshot2
interface = vboxnet1
resultserver_ip = 192.168.57.1)
2016-04-28 10:29:19,500 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/var/tmp/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/var/tmp/cuckoo/lib/cuckoo/core/scheduler.py", line 339, in launch_analysis
    self.guest_manage(options)
  File "/var/tmp/cuckoo/lib/cuckoo/core/scheduler.py", line 257, in guest_manage
    guest.start_analysis(options, monitor)
  File "/var/tmp/cuckoo/lib/cuckoo/core/guest.py", line 373, in start_analysis
    self.wait_available()
  File "/var/tmp/cuckoo/lib/cuckoo/core/guest.py", line 268, in wait_available
    socket.create_connection((self.ipaddr, self.port), 1).close()
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/usr/lib/python2.7/encodings/idna.py", line 73, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long
2016-04-28 10:29:20,774 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run

```

please help !

**Comment by jbremer** [comment]
As-is we only run one resultserver, this implies that only one IP address / port combination can be used. The first exception is just a small fix and for the second one - did you specify the `resultserver_ip` for the machines where you also provided the `resultserver_port`?
However, what I'm wondering about is why it is possible to specify a per-VM resultserver if in reality only one resultserver ip/port can be handled. Perhaps @rep can clarify on this? :-)

**Comment by Nadacsc** [comment]
I am very sorry I didn't quit get it 
do you mean I have only to use 1 interface ( vboxnet0) only and then the guest vms will be 192.168.56.1 and 198.168.56.2 ? so like that the result ip and port will be only one ? but how can tcpdump distinguish the connections that came from the first vm and the second ?

**Comment by jbremer** [comment]
The resultserver configuration is just so the Guest knows how to connect to the Host. Closing this issue as irrelevant to general purpose usage of Cuckoo.
