### ISSUE TITLE
Unsupported operand type in modules

### ISSUE THREAD

**Issue by McCurity** [cuckoosandbox/cuckoo#890]
Had an install of 1.2 working but ran Ubuntu updates which caused an issue.  I wanted to get 2.0 running so I performed a fresh install of OS, packages, and cuckoo.  I'm receiving the error below when submitting a pdf via the web interface.

2016-04-28 19:57:26,458 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.pdf" start function encountered an unhandled exception: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by jbremer** [comment]
Could you add a `log.exception("hello")` line before the following line and re-run your analysis?
https://github.com/cuckoosandbox/cuckoo/blob/master/analyzer/windows/analyzer.py#L615

Did you enable any special configuration or analysis options?

**Comment by McCurity** [comment]
Nothing special about the install.  Followed the docs with Yara & PyDeep but I didn't do Volatility.  Here's the analysis.log with the requested edit.

cuckuser@ubuntu:~/cuckoo$ cat storage/analyses/5/analysis.log 
2016-04-29 04:43:16,015 [analyzer] DEBUG: Starting analyzer from: C:\avxwoc
2016-04-29 04:43:16,015 [analyzer] DEBUG: Pipe server name: \\.\PIPE\SkXtQEeQvbNBITWfZU
2016-04-29 04:43:16,015 [analyzer] DEBUG: Log pipe server name: \\.\PIPE\QQoMszEoGOhDsUMIdsVDSAohh
2016-04-29 04:43:16,015 [analyzer] DEBUG: No analysis package specified, trying to detect it automagically.
2016-04-29 04:43:16,015 [analyzer] INFO: Automatically selected analysis package "pdf"
2016-04-29 04:43:22,108 [analyzer] DEBUG: Started auxiliary module Disguise
2016-04-29 04:43:22,375 [analyzer] WARNING: PRF unable to locate the PRF function [aborting hook]
2016-04-29 04:43:22,375 [analyzer] WARNING: PRF unable to locate the PRF function [aborting hook]
2016-04-29 04:43:22,375 [analyzer] DEBUG: Loaded monitor into process with pid 432
2016-04-29 04:43:22,375 [lib.api.process] INFO: Successfully injected process with pid None
2016-04-29 04:43:22,375 [analyzer] DEBUG: Started auxiliary module DumpTLSMasterSecrets
2016-04-29 04:43:22,375 [analyzer] DEBUG: Started auxiliary module Human
2016-04-29 04:43:24,375 [modules.auxiliary.installcert] INFO: Successfully installed PFX certificate.
2016-04-29 04:43:24,375 [analyzer] DEBUG: Started auxiliary module InstallCertificate
2016-04-29 04:43:24,375 [analyzer] DEBUG: Started auxiliary module Screenshots
2016-04-29 04:43:24,375 [analyzer] ERROR: hello
Traceback (most recent call last):
  File "C:\avxwoc\analyzer.py", line 546, in run
    pids = self.package.start(self.target)
  File "C:\avxwoc\modules\packages\pdf.py", line 17, in start
    reader = self.get_path("Adobe Reader")
  File "C:\avxwoc\lib\common\abstracts.py", line 77, in get_path
    for path in self.enum_paths():
  File "C:\avxwoc\lib\common\abstracts.py", line 60, in enum_paths
    os.getenv("HomeDrive") + "\\",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
cuckuser@ubuntu:~/cuckoo$ 

I also tried checking python on the VBox guest and was able to perform the os.getenv("HomeDrive") + "\\"
![vboxguest](https://cloud.githubusercontent.com/assets/18730969/14915242/67ce045a-0ddf-11e6-8608-a84c05901d10.jpg)

**Comment by jbremer** [comment]
Thanks, that definitely helps! So even though it would appear that in your Python session `%HomeDrive% is set, this doesn't seem to be the case during the Cuckoo analysis.
Could you perhaps add the following line somewhere in the `enum_paths()` function in order to take a look at the environment variables that are defined?

```python
import logging
log = logging.getLogger(__name__)
log.info("env; %s", os.environ)
```

Thanks!

**Comment by McCurity** [comment]
Here is the log output I believe you're looking for.  I did however continue to troubleshoot on my own and found what may have fixed the issue.  I was running the guest's agent using task scheduler as system.  I've since moved the agent into the startup folder (as directed) and the submissions are completing.  Still trying to figure out how PIL, Pillow, and tesseract-ocr work together for screen shots as I'm not getting any.

Sorry for not getting back to you in a more timely manner.

2016-05-02 05:38:54,500 [lib.common.abstracts] INFO: env; {'TMP': 'C:\\Windows\\TEMP', 'COMPUTERNAME': 'FIRM-NYK7XF', 'USERDOMAIN': 'WORKGROUP', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3a09', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Python27;C:\\Python27\\Scripts', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'TK_LIBRARY': 'C:\\Python27\\tcl\\tk8.5', 'TEMP': 'C:\\Windows\\TEMP', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'TIX_LIBRARY': 'C:\\Python27\\tcl\\tix8.4.3', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'FIRM-NYK7XF$', 'WINDOWS_TRACING_FLAGS': '3', 'PROGRAMDATA': 'C:\\ProgramData', 'TCL_LIBRARY': 'C:\\Python27\\tcl\\tcl8.5', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log', 'APPDATA': 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '1', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Windows\\system32\\config\\systemprofile'}
2016-05-02 05:38:54,515 [analyzer] ERROR: hello
Traceback (most recent call last):
  File "C:\ykixvdppye\analyzer.py", line 546, in run
    pids = self.package.start(self.target)
  File "C:\ykixvdppye\modules\packages\pdf.py", line 40, in start
    reader = self.get_path("Adobe Reader")
  File "C:\ykixvdppye\lib\common\abstracts.py", line 82, in get_path
    for path in self.enum_paths():
  File "C:\ykixvdppye\lib\common\abstracts.py", line 65, in enum_paths
    os.getenv("HomeDrive") + "\\",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
cuckuser@ubuntu:~/cuckoo/storage/analyses$ 

Thanks!

**Comment by jbremer** [comment]
Exactly, that'd explain ;-) We could probably fall back to another environment variable if `HomeDrive` isn't available, although I'm not sure if anyone else will ever run into this issue.

**Comment by jbremer** [comment]
Regarding screenshots. Please install either `PIL` or `Pillow` in the Guest, that should do the job. For OCR we have `tesseract` as dependency (so run that on the Host), but that's an optional feature.

**Comment by jbremer** [comment]
Closing this issue, I think the issue(s) were resolved :-)
