### ISSUE TITLE
modules.processing.network:Error running httpreplay-based PCAP analysis

### ISSUE THREAD

**Issue by takboo** [cuckoosandbox/cuckoo#923]
Traceback (most recent call last):
  File "/home/cuckoo/SourceCode/cuckoo/utils/../modules/processing/network.py", line 809, in run
    results.update(p2.run())
  File "/home/cuckoo/SourceCode/cuckoo/utils/../modules/processing/network.py", line 723, in run
    r = httpreplay.reader.PcapReader(open(self.pcap_path, "rb"))
  File "/home/cuckoo/.virtualenvs/cuckoo-env/local/lib/python2.7/site-packages/httpreplay/reader.py", line 25, in __init__
    self.pcap = dpkt.pcap.Reader(open(filepath, "rb"))
TypeError: coercing to Unicode: need string or buffer, file found

**Comment by takboo** [comment]
sorry,it's my fault. my HTTPReplay version is 0.1.14,not 0.1.15.
