### ISSUE TITLE
libvirtError occurred when using Cuckoo on Xen hypervisor

### ISSUE THREAD

**Issue by alexandrafengfei** [cuckoosandbox/cuckoo#925]
Hi.
I am using xen hypervisor 4.4 with libvirt 1.2.2 on ubuntu 14.04.
I create a xen machinery by using LibVirtMachinery.
However, I got the following error after submitting an exe file.

2016-05-18 16:00:49,573 [root] DEBUG: Imported "machinery" modules:
2016-05-18 16:00:49,573 [root] DEBUG:    `-- xen
2016-05-18 16:00:49,574 [root] DEBUG: Checking for locked tasks..
2016-05-18 16:00:49,619 [root] DEBUG: Checking for pending service tasks..
2016-05-18 16:00:49,623 [root] DEBUG: Initializing Yara...
2016-05-18 16:00:49,632 [root] DEBUG:    |-- index_binaries.yar
2016-05-18 16:00:49,633 [root] DEBUG:`-- index_memory.yar
2016-05-18 16:00:49,644 [lib.cuckoo.core.resultserver] DEBUG: ResultServer running on 192.168.122.1:2042.
2016-05-18 16:00:49,647 [lib.cuckoo.core.scheduler] INFO: Using "xen" as machine manager
2016-05-18 16:00:51,262 [lib.cuckoo.common.abstracts] DEBUG: Stopping machine win7-32bit-trial
2016-05-18 16:00:51,263 [lib.cuckoo.common.abstracts] DEBUG: Getting status for win7-32bit-trial
2016-05-18 16:00:53,904 [lib.cuckoo.common.abstracts] DEBUG: Getting status for win7-32bit-trial
2016-05-18 16:00:54,225 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-05-18 16:00:54,241 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-05-18 16:01:05,716 [lib.cuckoo.core.scheduler] DEBUG: Processing task #43
2016-05-18 16:01:05,720 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "pafish.exe" (task #43, options "route=none")
2016-05-18 16:01:05,749 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/cuckoo/cuckoo/storage/binaries/fe5e8153e3972d32d41c3a5ee53a9e99f44116fca98c480b703dca780cb3fd4c"
2016-05-18 16:01:05,895 [lib.cuckoo.core.scheduler] INFO: Task #43: acquired machine win7-32bit-trial (label=win7-32bit-trial)
2016-05-18 16:01:05,937 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 3380 (interface=virbr0, host=192.168.122.2, pcap=/home/cuckoo/cuckoo/storage/analyses/43/dump.pcap)
2016-05-18 16:01:05,938 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2016-05-18 16:01:06,178 [lib.cuckoo.common.abstracts] DEBUG: Starting machine win7-32bit-trial
2016-05-18 16:01:06,179 [lib.cuckoo.common.abstracts] DEBUG: Getting status for win7-32bit-trial
2016-05-18 16:01:06,349 [lib.cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2016-05-18 16:01:06,350 [lib.cuckoo.common.abstracts] DEBUG: Stopping machine win7-32bit-trial
2016-05-18 16:01:06,350 [lib.cuckoo.common.abstracts] DEBUG: Getting status for win7-32bit-trial
2016-05-18 16:01:06,497 [lib.cuckoo.core.scheduler] WARNING: Unable to stop machine win7-32bit-trial: Trying to stop an already stopped machine win7-32bit-trial
2016-05-18 16:01:06,741 [lib.cuckoo.core.scheduler] **ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):**
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 325, in launch_analysis
    machinery.start(self.machine.label, self.task)
  File "/home/cuckoo/cuckoo/lib/cuckoo/common/abstracts.py", line 367, in start
    snapshot_list = self.vms[label].snapshotListNames(flags=0)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 2308, in snapshotListNames
    if ret is None: raise libvirtError ('virDomainSnapshotListNames() failed', dom=self)
**libvirtError: this function is not supported by the connection driver: virDomainSnapshotNum**

Then I found this 
https://www.redhat.com/archives/libvirt-users/2015-May/msg00035.html
which says libvirt doesn't support snapshot for xen because libxl doesn't support snapshot.

Has anyone ever used Cuckoo on xen hypervisor? Which version of xen and libvirt did you use?

**Comment by doomedraven** [comment]
i don't use xen, but i use kvm and both they use libvirt, and there are bug in ubuntu 14.04 with libvirt which fails with snapshots, at least you was able create snapshot from virsh/virt-manager?

**Comment by alexandrafengfei** [comment]
Oh, really? Then what OS do you use to fix this problem? I haven't tried to create snapshot from virsh/virt-manager.

**Comment by doomedraven** [comment]
Ubuntu 16.04, as i tried compile from sources on 14.04 but no way to make it works correctly

**Comment by jbremer** [comment]
@alexandrafengfei Did you properly setup Xen? Is this issue still relevant? If you resolved it, do you mind posting the solution here?

**Comment by jbremer** [comment]
Closing as issue has expired.
