### ISSUE TITLE
IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by geek-li** [cuckoosandbox/cuckoo#944]
this is the debug  information:"
2016-06-02 23:40:10,165 [root] DEBUG: Importing modules...
2016-06-02 23:40:10,268 [root] DEBUG: Imported "signatures" modules:
2016-06-02 23:40:10,268 [root] DEBUG: 	 |-- CreatesExe
2016-06-02 23:40:10,268 [root] DEBUG: 	 `-- SystemMetrics
2016-06-02 23:40:10,268 [root] DEBUG: Imported "processing" modules:
2016-06-02 23:40:10,268 [root] DEBUG: 	 |-- AnalysisInfo
2016-06-02 23:40:10,268 [root] DEBUG: 	 |-- ApkInfo
2016-06-02 23:40:10,268 [root] DEBUG: 	 |-- Baseline
2016-06-02 23:40:10,268 [root] DEBUG: 	 |-- BehaviorAnalysis
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- DroppedBuffer
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- Debug
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- Droidmon
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- Dropped
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- TLSMasterSecrets
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- GooglePlay
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- Memory
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- NetworkAnalysis
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- ProcessMemory
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- Screenshots
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- Snort
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- Static
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- Strings
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- Suricata
2016-06-02 23:40:10,269 [root] DEBUG: 	 |-- TargetInfo
2016-06-02 23:40:10,269 [root] DEBUG: 	 `-- VirusTotal
2016-06-02 23:40:10,269 [root] DEBUG: Imported "auxiliary" modules:
2016-06-02 23:40:10,270 [root] DEBUG: 	 |-- MITM
2016-06-02 23:40:10,270 [root] DEBUG: 	 |-- Services
2016-06-02 23:40:10,270 [root] DEBUG: 	 `-- Sniffer
2016-06-02 23:40:10,270 [root] DEBUG: Imported "reporting" modules:
2016-06-02 23:40:10,270 [root] DEBUG: 	 |-- JsonDump
2016-06-02 23:40:10,270 [root] DEBUG: 	 |-- Moloch
2016-06-02 23:40:10,270 [root] DEBUG: 	 |-- MongoDB
2016-06-02 23:40:10,270 [root] DEBUG: 	 `-- ReportHTML
2016-06-02 23:40:10,270 [root] DEBUG: Imported "machinery" modules:
2016-06-02 23:40:10,270 [root] DEBUG: 	 `-- VirtualBox
2016-06-02 23:40:10,271 [root] DEBUG: Checking for locked tasks..
2016-06-02 23:40:10,358 [root] INFO: Updated running task ID 13 status to failed_analysis
2016-06-02 23:40:10,359 [root] DEBUG: Checking for pending service tasks..
2016-06-02 23:40:10,362 [root] DEBUG: Initializing Yara...
2016-06-02 23:40:10,362 [root] DEBUG: 	 |-- index_binaries.yar
2016-06-02 23:40:10,362 [root] DEBUG: 	 `-- index_memory.yar
2016-06-02 23:40:10,364 [lib.cuckoo.core.resultserver] DEBUG: ResultServer running on 10.18.201.130:2042.
2016-06-02 23:40:10,365 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2016-06-02 23:40:10,625 [modules.machinery.virtualbox] DEBUG: Getting status for win7
2016-06-02 23:40:10,694 [modules.machinery.virtualbox] DEBUG: Machine win7 status poweroff
2016-06-02 23:40:10,782 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-06-02 23:40:10,793 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-06-02 23:40:15,157 [lib.cuckoo.core.scheduler] DEBUG: Processing task #14
2016-06-02 23:40:15,160 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "1.exe" (task #14, options "route=none")
2016-06-02 23:40:15,167 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/wwb/Downloads/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/wwb/Downloads/cuckoo/lib/cuckoo/core/scheduler.py", line 287, in launch_analysis
    if not self.check_file():
  File "/home/wwb/Downloads/cuckoo/lib/cuckoo/core/scheduler.py", line 86, in check_file
    sha256 = File(self.task.target).get_sha256()
  File "/home/wwb/Downloads/cuckoo/lib/cuckoo/common/objects.py", line 208, in get_sha256
    self.calc_hashes()
  File "/home/wwb/Downloads/cuckoo/lib/cuckoo/common/objects.py", line 153, in calc_hashes
    for chunk in self.get_chunks():
  File "/home/wwb/Downloads/cuckoo/lib/cuckoo/common/objects.py", line 138, in get_chunks
    with open(self.file_path, "rb") as fd:
IOError: [Errno 13] Permission denied: u'/tmp/cuckoo-tmp/upload_IAZoVD/1.exe

====
and  then cuckoosandbox was  blocked :(
what should  I do

**Comment by geek-li** [comment]
the issue fixed .

**Comment by michaelkasede** [comment]
I keep getting this issue. I have checked over and over again and everythign seems fine. But I cant get cuckoo to run.

> @RicoVZ Please help. You have the best suggestions so far I have seen, but that too hasn't worked for me.

**Comment by RicoVZ** [comment]
@michaelkasede Hi, I have posted a response on your issue: #2562
