### ISSUE TITLE
RuntimeError: Maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#949]
HI

Im  running Cuckoo 2.0-rc1 and I have the web interface turned on with mongodb , when i submit through the web interface i get the following error...
ERROR:lib.cuckoo.core.plugins:Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/xxxx/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/home/xxxxt/cuckoo/utils/../modules/reporting/mongodb.py", line 224, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
  File "/usr/lib/python2.7/abc.py", line 132, in __instancecheck__
    if subclass is not None and subclass in cls._abc_cache:
  File "/usr/lib/python2.7/_weakrefset.py", line 75, in __contains__
    return wr in self.data
RuntimeError: maximum recursion depth exceeded in cmp

Any idea how to address this ?

Cheers
Sparx

**Comment by jbremer** [comment]
Odd exception.. you'd expect a traceback with ~1000 function calls in it (the default recursion count, I believe). Could you provide some more information please?

**Comment by jbremer** [comment]
Is this still an issue? Going to close it otherwise. Never seen this issue myself so far. Are you running the "correct" `pymongo` version (`3.0.3`)?

**Comment by Ads5740** [comment]
I just had the same issue:
2016-10-12 10:37:08,596 [lib.cuckoo.core.plugins] DEBUG: Analysis matched signature: network_http
2016-10-12 10:37:08,599 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "JsonDump":
Traceback (most recent call last):
  File "/home/cuculus/cuckoo/lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/home/cuculus/cuckoo/modules/reporting/jsondump.py", line 68, in run
    indent=int(indent), encoding=encoding)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 348, in _iterencode_dict
    raise ValueError("Circular reference detected")
ValueError: Circular reference detected
2016-10-12 10:37:09,621 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/cuculus/cuckoo/lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/home/cuculus/cuckoo/modules/reporting/mongodb.py", line 224, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 436, in _insert
    self.codec_options, sock_info)
  File "/usr/lib/python2.7/abc.py", line 132, in __instancecheck__
    if subclass is not None and subclass in cls._abc_cache:
  File "/usr/lib/python2.7/_weakrefset.py", line 75, in __contains__
    return wr in self.data
RuntimeError: maximum recursion depth exceeded in cmp
2016-10-12 10:37:10,421 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "ReportHTML"

**Comment by jbremer** [comment]
Could you share all of the analysis files that belong to this analysis?

**Comment by Ads5740** [comment]
I have fixed this, this was due to a custom processing module which had been changed. The module itself zips file submissions and was falling over during url submissions.

**Comment by SparkyNZL** [comment]
Cheers :) ill close this too as it hasn't pop up again.

**Comment by soutzis** [comment]
I think you should reopen this issue. It happens a lot for me (with certain malware families). A typical example would be 'dinwod'/'upatre' variants. 

For example, this sample causes the error every time: https://www.virustotal.com/gui/file/11d93a0d541d10137491611524ac89bb51f1d3c9aff10bacb15a1d2508bdc61e/detection

![image](https://user-images.githubusercontent.com/25797286/92409060-090ce200-f148-11ea-923f-bade043116f4.png)
![image](https://user-images.githubusercontent.com/25797286/92409093-1cb84880-f148-11ea-8cff-5bbe5c4c2079.png)

I can provide one such binary if you want.
