### ISSUE TITLE
issue with process memory dump and images

### ISSUE THREAD

**Issue by akapucu** [cuckoosandbox/cuckoo#953]
I am seeing this in debug mode what would be the reason for that?

2016-06-09 16:05:35,519 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Debug" on analysis at "/opt/cuckoo-latest/storage/analyses/2"
2016-06-09 16:05:35,520 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" on analysis at "/opt/cuckoo-latest/storage/analyses/2"
2016-06-09 16:05:35,566 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "ProcessMemory" for task #2:
Traceback (most recent call last):
  File "/opt/cuckoo-latest/lib/cuckoo/core/plugins.py", line 242, in process
    data = current.run()
  File "/opt/cuckoo-latest/modules/processing/procmemory.py", line 218, in run
    proc["extracted"] = list(self.dump_images(proc))
  File "/opt/cuckoo-latest/modules/processing/procmemory.py", line 158, in dump_images
    if pe.is_dll() and not drop_dlls:
AttributeError: PE instance has no attribute 'is_dll'
2016-06-09 16:05:35,568 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Static" on analysis at "/opt/cuckoo-latest/storage/analyses/2"
2016-06-09 16:05:35,570 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "Strings" on analysis at "/opt/cuckoo-latest/storage/analyses/2"
2016-06-09 16:05:35,573 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" on analysis at "/opt/cuckoo-latest/storage/analyses/2"
2016-06-09 16:05:35,627 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/opt/cuckoo-latest/modules/processing/network.py", line 815, in run
    results.update(p2.run())
  File "/opt/cuckoo-latest/modules/processing/network.py", line 729, in run
    r = httpreplay.reader.PcapReader(open(self.pcap_path, "rb"))
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/reader.py", line 25, in __init__
    self.pcap = dpkt.pcap.Reader(open(filepath, "rb"))
TypeError: coercing to Unicode: need string or buffer, file found
2016-06-09 16:05:35,628 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" on analysis at "/opt/cuckoo-latest/storage/analyses/2"
2016-06-09 16:05:35,826 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "VirusTotal" on analysis at "/opt/cuckoo-latest/storage/analyses/2"
2016-06-09 16:05:35,826 [lib.cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" on analysis at "/opt/cuckoo-latest/storage/analyses/2"

**Comment by jbremer** [comment]
This is actually related to the network related processing. Did you upgrade `httpreplay` to the correct version (`0.1.15` in this case)?

**Comment by akapucu** [comment]
looks like not but i can not upgarde to 0.1.15

pip install --upgrade httpreplay
Downloading/unpacking httpreplay from https://pypi.python.org/packages/0e/42/dc0e06bdeb032ad089e387f6666e0850798b67f905cc19815131bd64b842/HTTPReplay-0.1.15.tar.gz#md5=739eeec1332a0c2ec7d39fa743e46cf7
  Downloading HTTPReplay-0.1.15.tar.gz
  Running setup.py (path:/tmp/pip-build-Ibdy2U/httpreplay/setup.py) egg_info for package httpreplay

Requirement already up-to-date: dpkt==1.8.7 in /usr/local/lib/python2.7/dist-packages (from httpreplay)
Downloading/unpacking tlslite-ng==0.6.0a3 (from httpreplay)
  Could not find a version that satisfies the requirement tlslite-ng==0.6.0a3 (from httpreplay) (from versions: 0.6.0-alpha5, 0.5.0-beta5, 0.5.0, 0.6.0-alpha4, 0.5.2, 0.5.1, 0.5.0-beta1, 0.5.0-beta2, 0.5.0-beta4, 0.5.0-beta3, 0.6.0-alpha2, 0.5.0-beta6, 0.6.0-alpha1, 0.6.0-alpha3)
Cleaning up...
No distributions matching the version for tlslite-ng==0.6.0a3 (from httpreplay)
Storing debug log for failure in /root/.pip/pip.log

**Comment by akapucu** [comment]
Well i used help here

https://github.com/cuckoosandbox/cuckoo/issues/929
Problem resolved
