### ISSUE TITLE
Failed to run the reporting module "MongoDB"

### ISSUE THREAD

**Issue by lab313ru** [cuckoosandbox/cuckoo#959]
When internet is enabled: **route = internet**, **internet = eth0** and **cuckoo-rooter** is started, I'm getting this error:
```
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/home/cuckoo/cuckoo/modules/reporting/mongodb.py", line 89, in run
    if "cuckoo_schema" in self.db.collection_names():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 488, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 699, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 663, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused
```

**Comment by jbremer** [comment]
MongoDB is not running :-)

**Comment by lab313ru** [comment]
But it is running. Problem appeared after enabling internet for cuckoo.

**Comment by jbremer** [comment]
That's unrelated. Please check again.

**Comment by lab313ru** [comment]
In traceback there is a line about socket. And, /tmp/cuckoo-rooter occupies some socket too, doesn't it?

**Comment by jbremer** [comment]
`/tmp/cuckoo-rooter` unix socket vs MongoDB's `127.0.0.1:27017`.

**Comment by lab313ru** [comment]
Hmm... Sorry, but problems are in some other place. Investigating...

Could it be related to storing memory dumps in mongodb? I have enabled saving volatility memory dumps before too.

**Comment by lab313ru** [comment]
I have 32-bit OS, and I have such error:
```
Mon Jun 13 16:54:27.670 [initandlisten] MongoDB starting : pid=873 port=27017 dbpath=/var/lib/mongodb 32-bit host=cuckoo-pc
Mon Jun 13 16:54:27.671 [initandlisten] 
Mon Jun 13 16:54:27.671 [initandlisten] ** NOTE: This is a 32 bit MongoDB binary.
Mon Jun 13 16:54:27.671 [initandlisten] **       32 bit builds are limited to less than 2GB of data (or less with --journal).
Mon Jun 13 16:54:27.671 [initandlisten] **       See http://dochub.mongodb.org/core/32bit
Mon Jun 13 16:54:27.671 [initandlisten] 
Mon Jun 13 16:54:27.671 [initandlisten] db version v2.4.9
Mon Jun 13 16:54:27.671 [initandlisten] git version: nogitversion
Mon Jun 13 16:54:27.671 [initandlisten] build info: Linux comet 3.2.0-58-generic #88-Ubuntu SMP Tue Dec 3 17:37:58 UTC 2013 i686 BOOST_LIB_VERSION=1_54
Mon Jun 13 16:54:27.671 [initandlisten] allocator: tcmalloc
Mon Jun 13 16:54:27.671 [initandlisten] options: { bind_ip: "127.0.0.1", config: "/etc/mongodb.conf", dbpath: "/var/lib/mongodb", journal: "true", logappend: "true", logpath: "/var/log/mongodb/mongodb.log" }
Mon Jun 13 16:54:27.966 [initandlisten] journal dir=/var/lib/mongodb/journal
Mon Jun 13 16:54:28.074 [initandlisten] recover : no journal files present, no recovery needed
Mon Jun 13 16:54:29.531 [initandlisten] ERROR: mmap private failed with out of memory. You are using a 32-bit build and probably need to upgrade to 64
Mon Jun 13 16:54:29.531 [initandlisten] Assertion: 13636:file /var/lib/mongodb/cuckoo.6 open/create failed in createPrivateMap (look in log for more information)
```

**Comment by jbremer** [comment]
If it exits, it's not running, just saying :P Please use a proper machine with 64-bit MongoDB etc.

**Comment by lab313ru** [comment]
I mean... It is not possible to use cuckoo-sandbox at x86 OS?

**Comment by jbremer** [comment]
Probably it is, but those MongoDB related issues are out of scope for us. If you get that to work it should be fine.

**Comment by lab313ru** [comment]
Ported at x64 OS.
