### ISSUE TITLE
Error running httpreplay-based PCAP analysis

### ISSUE THREAD

**Issue by lab313ru** [cuckoosandbox/cuckoo#964]
Version is 2.0-dev (current master):
```
2016-06-16 16:57:49,706 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/modules/processing/network.py", line 815, in run
    results.update(p2.run())
  File "/home/cuckoo/cuckoo/modules/processing/network.py", line 729, in run
    r = httpreplay.reader.PcapReader(open(self.pcap_path, "rb"))
  File "build/bdist.linux-x86_64/egg/httpreplay/reader.py", line 25, in __init__
    self.pcap = dpkt.pcap.Reader(open(filepath, "rb"))
TypeError: coercing to Unicode: need string or buffer, file found
```

**Comment by jbremer** [comment]
Please use the correct version of httpreplay in combination with your version of Cuckoo, see also the `requirements.txt` file. Going to close this as I know that fixes your error ;-)
