### ISSUE TITLE
error in analyzer_zipfile

### ISSUE THREAD

**Issue by alonlavian** [cuckoosandbox/cuckoo#976]
Hi,

Trying to run with latest master (27.6.16) I get :
The path in the error exists but it is not a directory but a file.
Any idea?

2016-06-27 14:40:39,502 [lib.cuckoo.core.resultserver] DEBUG: ResultServer running on 192.168.56.1:2042.
2016-06-27 14:40:39,508 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2016-06-27 14:40:39,635 [modules.machinery.virtualbox] DEBUG: Getting status for win7
2016-06-27 14:40:39,743 [modules.machinery.virtualbox] DEBUG: Machine win7 status poweroff
2016-06-27 14:40:39,764 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-06-27 14:40:39,780 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-06-27 14:41:09,381 [lib.cuckoo.core.scheduler] DEBUG: Processing task #1
2016-06-27 14:41:09,395 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "0a07f2c6b806b3c267320c300e44f04c7c57de4572313b4edfc4d42027e0c1bf.exe" (task #1, options "")
2016-06-27 14:41:09,423 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired machine win7 (label=win7)
2016-06-27 14:41:09,442 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 17221 (interface=vboxnet0, host=192.168.56.102, pcap=/home/alon/cuckoo/storage/analyses/1/dump.pcap)
2016-06-27 14:41:09,443 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2016-06-27 14:41:09,472 [modules.machinery.virtualbox] DEBUG: Starting vm win7
2016-06-27 14:41:09,473 [modules.machinery.virtualbox] DEBUG: Getting status for win7
dropped privs to root
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
2016-06-27 14:41:09,581 [modules.machinery.virtualbox] DEBUG: Machine win7 status poweroff
2016-06-27 14:41:09,601 [modules.machinery.virtualbox] DEBUG: Using current snapshot for virtual machine win7
2016-06-27 14:41:09,686 [modules.machinery.virtualbox] DEBUG: Getting status for win7
2016-06-27 14:41:09,819 [modules.machinery.virtualbox] DEBUG: Machine win7 status saved
2016-06-27 14:41:12,501 [modules.machinery.virtualbox] DEBUG: Getting status for win7
2016-06-27 14:41:12,638 [modules.machinery.virtualbox] DEBUG: Machine win7 status running
2016-06-27 14:41:12,694 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=win7, ip=192.168.56.102)
2016-06-27 14:41:13,698 [lib.cuckoo.core.guest] DEBUG: win7: not ready yet
2016-06-27 14:41:14,706 [lib.cuckoo.core.guest] DEBUG: win7: not ready yet
2016-06-27 14:41:15,710 [lib.cuckoo.core.guest] DEBUG: win7: not ready yet
2016-06-27 14:41:16,715 [lib.cuckoo.core.guest] DEBUG: win7: not ready yet
2016-06-27 14:41:17,720 [lib.cuckoo.core.guest] DEBUG: win7: not ready yet
2016-06-27 14:41:17,756 [lib.cuckoo.core.guest] DEBUG: win7: waiting for status 0x0001
2016-06-27 14:41:17,765 [lib.cuckoo.core.guest] DEBUG: win7: status ready
0 packets captured
8 packets received by filter
0 packets dropped by kernel
2016-06-27 14:41:17,771 [lib.cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2016-06-27 14:41:17,771 [modules.machinery.virtualbox] DEBUG: Stopping vm win7
2016-06-27 14:41:17,771 [modules.machinery.virtualbox] DEBUG: Getting status for win7
2016-06-27 14:41:17,896 [modules.machinery.virtualbox] DEBUG: Machine win7 status running
2016-06-27 14:41:18,909 [modules.machinery.virtualbox] DEBUG: Getting status for win7
2016-06-27 14:41:19,013 [modules.machinery.virtualbox] DEBUG: Machine win7 status poweroff
2016-06-27 14:41:19,031 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/alon/cuckoo/lib/cuckoo/core/scheduler.py", line 496, in run
    self.launch_analysis()
  File "/home/alon/cuckoo/lib/cuckoo/core/scheduler.py", line 382, in launch_analysis
    self.guest_manage(options)
  File "/home/alon/cuckoo/lib/cuckoo/core/scheduler.py", line 289, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/home/alon/cuckoo/lib/cuckoo/core/guest.py", line 386, in start_analysis
    self.old.start_analysis(options, monitor)
  File "/home/alon/cuckoo/lib/cuckoo/core/guest.py", line 173, in start_analysis
    self.upload_analyzer(monitor)
  File "/home/alon/cuckoo/lib/cuckoo/core/guest.py", line 136, in upload_analyzer
    zip_data = analyzer_zipfile(self.platform, monitor)
  File "/home/alon/cuckoo/lib/cuckoo/core/guest.py", line 60, in analyzer_zipfile
    for name in os.listdir(dirpath):
OSError: [Errno 20] Not a directory: '/home/alon/cuckoo/data/monitor/latest'

**Comment by jbremer** [comment]
Could you please share the output of `ls -al /home/alon/cuckoo/data/monitor/latest` and `ls -al /home/alon/cuckoo/data/monitor/latest/`?

**Comment by alonlavian** [comment]
alon@alon-virtual-machine:~/cuckoo$ ls -al data/monitor/latest 
-rw-rw-r-- 1 alon alon 41 יונ 27 15:01 data/monitor/latest

alon@alon-virtual-machine:~/cuckoo$ ls -al data/monitor/latest/ 
ls: cannot access 'data/monitor/latest/': Not a directory

**Comment by jbremer** [comment]
And what are the contents of the file? :)

**Comment by alonlavian** [comment]
cf3b0957e39242885f7e5a7d6f49245b3a88a2fd

**Comment by jbremer** [comment]
Yeah, I see. So `latest` is supposed to be a symbolic link, but it doesn't look like that worked out for you. Did you do anything special to get Cuckoo Community or is this is a plain Cuckoo install?

**Comment by jbremer** [comment]
Alternatively you can try out the following patch which should also do the trick with your current setup https://github.com/cuckoosandbox/cuckoo/commit/bd6244d38cc76e6409c423ebe367a9a50f4316b3.
Let us know if it works and thanks again!

**Comment by alonlavian** [comment]
no, just took the master from today

**Comment by doomedraven** [comment]
did you execute ?

`./utils/community.py -waf`

**Comment by jbremer** [comment]
Added in some additional error checking at Cuckoo startup, perhaps that will inform users what to do ;-)

**Comment by alonlavian** [comment]
./utils/community.py -waf

Did the trick, thanks guys.

**Comment by doomedraven** [comment]
cool, close this then
