### ISSUE TITLE
submitting a URL to darwin fails

### ISSUE THREAD

**Issue by alonlavian** [cuckoosandbox/cuckoo#990]
Trying to submit url with a --url option fails with:

2016-06-26 07:26:29,691 [root] DEBUG: Starting analyzer from /private/var/root/anlynh
2016-06-26 07:26:29,692 [root] DEBUG: Storing results at: /tmp/XGbKUDP
2016-06-26 07:26:29,692 [root] ERROR: Traceback (most recent call last):
  File "/var/root/anlynh/analyzer.py", line 150, in <module>
    success = analyzer.run()
  File "/var/root/anlynh/analyzer.py", line 48, in run
    package = self._setup_analysis_package()
  File "/var/root/anlynh/analyzer.py", line 81, in _setup_analysis_package
    package_class = choose_package_class(self.config.file_type,
AttributeError: Config instance has no attribute 'file_type'

it seems that in a "url" flow we are not supposed to get there at all.

**Comment by botherder** [comment]
I think you're right, it should implement an additional check in invoking that function.

**Comment by alonlavian** [comment]
Yes, or just assign "None" too "file_type" and "file_name" in case of "url" category.

**Comment by jbremer** [comment]
You're opening a URL on a Mac OS X guest? I guess that hasn't been tested ;-)
@alonlavian Did you happen to do a PR to fix this issue by any chance?

**Comment by alonlavian** [comment]
nope, didn't touch it for a while.
I can try and do something this week.
