### ISSUE TITLE
ERROR: Missing dependency: cannot import name PCAP

### ISSUE THREAD

**Issue by josu98** [cuckoosandbox/cuckoo#991]
Trying to start Cuckoo (cuckoo.py) on Ubuntu 16.04 and I get the error :  ERROR: Missing dependency: cannot import name PCAP

I have installed requred dependencies as specified in the manual.

Regards,
JOSU

**Comment by jbremer** [comment]
Could you please show the output of `pip install -r requirements.txt`?

**Comment by josu98** [comment]
Here´s the output
----------------------------------
Collecting alembic==0.8.0 (from -r requirements.txt (line 1))
  Downloading alembic-0.8.0.tar.gz (918kB)
    100% |████████████████████████████████| 921kB 657kB/s
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4==4.4.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2))
Collecting cffi==1.2.1 (from -r requirements.txt (line 3))
  Downloading cffi-1.2.1.tar.gz (335kB)
    100% |████████████████████████████████| 337kB 808kB/s
Requirement already satisfied (use --upgrade to upgrade): chardet==2.3.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4))
Collecting cryptography==1.0 (from -r requirements.txt (line 5))
  Downloading cryptography-1.0.tar.gz (331kB)
    100% |████████████████████████████████| 337kB 744kB/s
Collecting Django==1.8.4 (from -r requirements.txt (line 6))
  Downloading Django-1.8.4-py2.py3-none-any.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 139kB/s
Collecting dpkt==1.8.6.2 (from -r requirements.txt (line 7))
  Downloading dpkt-1.8.6.2-py2.py3-none-any.whl (100kB)
    100% |████████████████████████████████| 102kB 573kB/s
Collecting ecdsa==0.13 (from -r requirements.txt (line 8))
  Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 794kB/s
Collecting enum34==1.0.4 (from -r requirements.txt (line 9))
  Downloading enum34-1.0.4.zip (43kB)
    100% |████████████████████████████████| 51kB 1.2MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-g4nppujq/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/usr/local/lib/python3.5/dist-packages/setuptools-23.1.0-py3.5.egg/setuptools/__init__.py", line 11, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/usr/local/lib/python3.5/dist-packages/setuptools-23.1.0-py3.5.egg/setuptools/extern/__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/usr/local/lib/python3.5/dist-packages/setuptools-23.1.0-py3.5.egg/pkg_resources/__init__.py", line 32, in <module>
      File "/usr/lib/python3.5/platform.py", line 117, in <module>
        import sys, os, re, subprocess
      File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
        import signal
      File "/usr/lib/python3.5/signal.py", line 8, in <module>
        _IntEnum._convert(
      File "/tmp/pip-build-g4nppujq/enum34/enum/__init__.py", line 373, in __getattr__
        raise AttributeError(name)
    AttributeError: _convert
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/tmp/pip-build-g4nppujq/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 12, in <module>
        import subprocess, tempfile, os.path, re, pwd, grp, os, time
      File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
        import signal
      File "/usr/lib/python3.5/signal.py", line 8, in <module>
        _IntEnum._convert(
      File "/tmp/pip-build-g4nppujq/enum34/enum/__init__.py", line 373, in __getattr__
        raise AttributeError(name)
    AttributeError: _convert

    Original exception was:
    Traceback (most recent call last):
      File "/tmp/pip-build-g4nppujq/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/usr/local/lib/python3.5/dist-packages/setuptools-23.1.0-py3.5.egg/setuptools/__init__.py", line 11, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/usr/local/lib/python3.5/dist-packages/setuptools-23.1.0-py3.5.egg/setuptools/extern/__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/usr/local/lib/python3.5/dist-packages/setuptools-23.1.0-py3.5.egg/pkg_resources/__init__.py", line 32, in <module>
      File "/usr/lib/python3.5/platform.py", line 117, in <module>
        import sys, os, re, subprocess
      File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
        import signal
      File "/usr/lib/python3.5/signal.py", line 8, in <module>
        _IntEnum._convert(
      File "/tmp/pip-build-g4nppujq/enum34/enum/__init__.py", line 373, in __getattr__
        raise AttributeError(name)
    AttributeError: _convert

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g4nppujq/enum34/

**Comment by josu98** [comment]
No error with cuckoo, my fault.
